unit IDE.LocalizeFunc.Japanese;

{
  Inno Setup
  Copyright (C) 1997-2026 Jordan Russell
  Portions by Martijn Laan
  For conditions of distribution and use, see LICENSE.TXT.

  Compiler IDE Japanese translations
}

interface

uses
  IDE.LocalizeFunc;

const
  JapaneseIDETranslations: array [0..898] of TTranslationPair = (
    (English: 'Command line usage:'; Localized: 'コマンドラインの使用法:'),
    (English: 'Examples:'; Localized: '使用例:'),
    (English: 'script file'; Localized: 'スクリプトファイル'),
    (English: 'wizard name'; Localized: 'ウィザード名'),
    (English: 'My script'; Localized: 'マイ スクリプト'),
    (English: 'My Script Wizard'; Localized: 'マイ スクリプトウィザード'),
    (English: 'Could not load %1: %2'; Localized: '%1 を読み込めませんでした: %2'),
    (English: 'Inno Setup Compiler'; Localized: 'Inno Setup Compiler'),
    (English: 'Example scripts...'; Localized: 'サンプルスクリプト...'),
    (English: 'More files...'; Localized: 'その他のファイル...'),
    (English: 'Untitled'; Localized: '無題'),
    (English: 'Preprocessor Output'; Localized: 'プリプロセッサー出力'),
    (English: 'Run Parameters'; Localized: '実行パラメーター'),
    (English: 'Command line parameters for %1 and %2:'; Localized: '%1 と %2 のコマンドラインパラメーター:'),
    (English: 'Inno Setup Script files'; Localized: 'Inno Setup スクリプトファイル'),
    (English: 'All files'; Localized: 'すべてのファイル'),
    (English: 'Application files'; Localized: 'アプリケーションファイル'),
    (English: 'Documentation files'; Localized: 'ドキュメントファイル'),
    (English: 'Registry files'; Localized: 'レジストリファイル'),
    (English: 'Icon files'; Localized: 'アイコンファイル'),
    (English: 'Inno Setup Script Wizard'; Localized: 'Inno Setup スクリプトウィザード'),
    (English: 'Welcome'; Localized: 'ようこそ'),
    (English: 'Application Information'; Localized: 'アプリケーション情報'),
    (English: 'Please specify some basic information about your application.'; Localized: 'アプリケーションの基本的な情報を指定してください。'),
    (English: 'Application Folder'; Localized: 'アプリケーションフォルダー'),
    (English: 'Please specify folder information about your application.'; Localized: 'アプリケーションのフォルダー情報を指定してください。'),
    (English: 'Application Files'; Localized: 'アプリケーションファイル'),
    (English: 'Please specify the files that are part of your application.'; Localized: 'アプリケーションを構成するファイルを指定してください。'),
    (English: 'Please specify the source folder.'; Localized: 'ソースフォルダーを指定してください。'),
    (English: 'Should files in subfolders of "%1" also be included?'; Localized: '"%1" のサブフォルダー内のファイルも含めますか？'),
    (English: 'URL:'; Localized: 'URL:'),
    (English: 'Is the file to download an archive which should be extracted?'; Localized: 'ダウンロードするファイルは、展開すべきアーカイブですか？'),
    (English: 'Name of the file:'; Localized: 'ファイルの名前:'),
    (English: 'Name of the file (extension should match archive format):'; Localized: 'ファイルの名前 (拡張子はアーカイブ形式と一致する必要があります):'),
    (English: 'Approximate size of the file in megabytes:'; Localized: 'ファイルのおおよそのサイズ (メガバイト):'),
    (English: 'Application File Association'; Localized: 'アプリケーションのファイルの関連付け'),
    (English: 'Please specify which file association should be created for your application.'; Localized: 'アプリケーションに対して作成するファイルの関連付けを指定してください。'),
    (English: '%1 File'; Localized: '%1 ファイル'),
    (English: 'Application Shortcuts'; Localized: 'アプリケーションのショートカット'),
    (English: 'Please specify which shortcuts should be created for your application.'; Localized: 'アプリケーションに対して作成するショートカットを指定してください。'),
    (English: 'Application Documentation'; Localized: 'アプリケーションのドキュメント'),
    (English: 'Please specify which documentation files should be shown by Setup during installation.'; Localized: 'インストール中にセットアップが表示するドキュメントファイルを指定してください。'),
    (English: 'Setup Install Mode'; Localized: 'セットアップのインストールモード'),
    (English: 'Please specify in which install mode Setup should run.'; Localized: 'セットアップを実行するインストールモードを指定してください。'),
    (English: 'Application Registry Keys And Values'; Localized: 'アプリケーションのレジストリキーと値'),
    (English: 'Please specify the registry keys and values that are part of your application.'; Localized: 'アプリケーションを構成するレジストリキーと値を指定してください。'),
    (English: 'Setup Languages'; Localized: 'セットアップの言語'),
    (English: 'Please specify which Setup languages should be included.'; Localized: '含めるセットアップの言語を指定してください。'),
    (English: 'Compiler Settings'; Localized: 'コンパイラー設定'),
    (English: 'Please specify some basic compiler settings.'; Localized: 'コンパイラーの基本的な設定を指定してください。'),
    (English: 'Please specify the folder.'; Localized: 'フォルダーを指定してください。'),
    (English: 'Wizard Style'; Localized: 'ウィザードスタイル'),
    (English: 'Please specify which wizard style should be used.'; Localized: '使用するウィザードスタイルを指定してください。'),
    (English: 'Inno Setup Preprocessor'; Localized: 'Inno Setup プリプロセッサー'),
    (English: 'Please specify whether Inno Setup Preprocessor should be used.'; Localized: 'Inno Setup プリプロセッサーを使用するかどうかを指定してください。'),
    (English: 'The %1 can use %2 compiler directives to simplify your script. Although this is not necessary, it will make it easier to manually change the script later.%n%nDo you want the %1 to use %2 compiler directives?'; Localized: '%1 は、%2 コンパイラーディレクティブを使用してスクリプトを簡素化できます。これは必須ではありませんが、後でスクリプトを手動で変更する作業が容易になります。%n%n%1 で %2 コンパイラーディレクティブを使用しますか？'),
    (English: '&Yes, use %1 compiler directives'; Localized: 'はい、%1 コンパイラーディレクティブを使用する(&Y)'),
    (English: 'Finished'; Localized: '完了'),
    (English: '&Next'; Localized: '次へ(&N)'),
    (English: '&Finish'; Localized: '完了(&F)'),
    (English: 'The %1 is not complete. If you quit now, the new script file will not be generated.%n%nExit anyway?'; Localized: '%1 は完了していません。ここで終了すると、新しいスクリプトファイルは生成されません。%n%nそれでも終了しますか？'),
    (English: 'Please specify the application name.'; Localized: 'アプリケーション名を指定してください。'),
    (English: 'Please specify the application version.'; Localized: 'アプリケーションのバージョンを指定してください。'),
    (English: 'Please specify the application destination base folder.'; Localized: 'アプリケーションのインストール先ベースフォルダーを指定してください。'),
    (English: 'Please specify the application folder name.'; Localized: 'アプリケーションのフォルダー名を指定してください。'),
    (English: 'Please specify the application main executable file.'; Localized: 'アプリケーションのメイン実行ファイルを指定してください。'),
    (English: 'The specified application main executable file does not exist.'; Localized: '指定されたアプリケーションのメイン実行ファイルは存在しません。'),
    (English: 'Please specify the application Start Menu group name.'; Localized: 'アプリケーションのスタートメニューのグループ名を指定してください。'),
    (English: 'Please specify the destination base folder.'; Localized: 'インストール先ベースフォルダーを指定してください。'),
    (English: 'Please specify a destination base folder other than the application folder.'; Localized: 'アプリケーションフォルダー以外のインストール先ベースフォルダーを指定してください。'),
    (English: 'Please select at least one language.'; Localized: '少なくとも 1 つの言語を選択してください。'),
    (English: '&Source URL:'; Localized: 'ソース URL(&S):'),
    (English: 'Script generated by the %1.'; Localized: 'このスクリプトは %1 によって生成されました。'),
    (English: 'SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!'; Localized: 'Inno Setup スクリプトファイルの作成方法の詳細については、ドキュメントを参照してください！'),
    (English: 'NOTE: The value of %1 uniquely identifies this application. Do not use the same %1 value in installers for other applications.'; Localized: '注意: %1 の値はこのアプリケーションを一意に識別します。他のアプリケーションのインストーラーで同じ %1 の値を使用しないでください。'),
    (English: '(To generate a new GUID, click Tools | Generate GUID inside the IDE.)'; Localized: '(新しい GUID を生成するには、IDE 内で「ツール」|「GUID の生成」をクリックしてください。)'),
    (English: '"%1" specifies that Setup cannot run on anything but x64 and Windows 11 on Arm.'; Localized: '"%1" は、セットアップが x64 および Arm 版 Windows 11 以外では実行できないことを指定します。'),
    (English: '"%1" requests that the install be done in "64-bit mode" on x64 or Windows 11 on Arm.'; Localized: '"%1" は、x64 または Arm 版 Windows 11 で「64 ビットモード」でインストールを実行するように要求します。'),
    (English: 'This means it should use the native 64-bit Program Files directory and the 64-bit view of the registry.'; Localized: 'これは、ネイティブの 64 ビット Program Files フォルダーおよびレジストリの 64 ビットビューを使用することを意味します。'),
    (English: 'Uncomment the following line to use a 64-bit installer.'; Localized: '64 ビットインストーラーを使用するには、次の行のコメントを解除してください。'),
    (English: 'Use "%1" if all your archives are .%2 files.'; Localized: 'すべてのアーカイブが .%2 ファイルの場合は "%1" を使用してください。'),
    (English: 'Use "%1" if all your archives are not password-protected.'; Localized: 'すべてのアーカイブがパスワードで保護されていない場合は "%1" を使用してください。'),
    (English: 'Uncomment the following line to run in non administrative install mode (install for current user only).'; Localized: '非管理者インストールモード (現在のユーザーのみにインストール) で実行するには、次の行のコメントを解除してください。'),
    (English: 'Remove the following line to run in administrative install mode (install for all users).'; Localized: '管理者インストールモード (すべてのユーザーにインストール) で実行するには、次の行を削除してください。'),
    (English: 'NOTE: Don''t use "%1" on any shared system files.'; Localized: '注意: 共有システムファイルには "%1" を使用しないでください。'),
    (English: 'NOTE: Use the "%1" flag or the "%2" parameter to verify downloads.'; Localized: '注意: ダウンロードを検証するには、"%1" フラグまたは "%2" パラメーターを使用してください。'),
    (English: 'Registry data from file %1'; Localized: 'ファイル %1 のレジストリデータ'),
    (English: 'COULD NOT IMPORT %1'; Localized: '%1 をインポートできませんでした'),
    (English: 'End of registry data from file %1'; Localized: 'ファイル %1 のレジストリデータの終わり'),
    (English: 'SOME KEYS FILTERED DUE TO %1 SETTINGS!'; Localized: '%1 設定により一部のキーが除外されました！'),
    (English: 'SOME VALUES WITH UNSUPPORTED TYPES SKIPPED!'; Localized: 'サポートされていない型の一部の値がスキップされました！'),
    (English: 'Would you like to compile the new script now?'; Localized: '新しいスクリプトを今すぐコンパイルしますか？'),
    (English: 'My Program'; Localized: 'マイ プログラム'),
    (English: 'My Company, Inc.'; Localized: 'My Company, Inc.'),
    (English: 'Application directory'; Localized: 'アプリケーションフォルダー'),
    (English: 'Program Files directory'; Localized: 'Program Files フォルダー'),
    (English: 'Common Files directory'; Localized: 'Common Files フォルダー'),
    (English: 'Windows directory'; Localized: 'Windows フォルダー'),
    (English: 'Windows system directory'; Localized: 'Windows システムフォルダー'),
    (English: 'Setup source directory'; Localized: 'セットアップソースフォルダー'),
    (English: 'System drive root directory'; Localized: 'システムドライブのルートフォルダー'),
    (English: '(Custom)'; Localized: '(カスタム)'),
    (English: 'Starting compile.%1[%2]'; Localized: 'コンパイルを開始しています。%1[%2]'),
    (English: 'Finished.%1[%2, %3 elapsed]'; Localized: '完了しました。%1[%2, %3 経過]'),
    (English: 'Compile aborted.'; Localized: 'コンパイルを中止しました。'),
    (English: 'Log size limit reached, list reset.'; Localized: 'ログサイズの上限に達したため、リストをリセットしました。'),
    (English: '%1 started'; Localized: '%1 を開始しました'),
    (English: 'Terminating process'; Localized: 'プロセスを終了しています'),
    (English: 'Removing left-over temporary directory: %1'; Localized: '残された一時フォルダーを削除しています: %1'),
    (English: 'Failed to remove temporary directory'; Localized: '一時フォルダーを削除できませんでした'),
    (English: '%1 Call Stack'; Localized: '%1 コール スタック'),
    (English: 'Cannot run Setup at this time. Please compile Setup successfully to completion first, with output enabled'; Localized: '現在セットアップを実行できません。先に出力を有効にして、セットアップを最後まで正常にコンパイルしてください'),
    (English: 'Cannot run Uninstall at this time. Please run Setup successfully to completion first'; Localized: '現在アンインストールを実行できません。先にセットアップを最後まで正常に実行してください'),
    (English: 'Error executing "%1":%n%n%2: %3'; Localized: '"%1" の実行中にエラーが発生しました:%n%n%2: %3'),
    (English: 'Are you sure you want to abort the compile?'; Localized: 'コンパイルを中止してもよろしいですか？'),
    (English: 'File %1:'; Localized: 'ファイル %1:'),
    (English: 'Line %1:'; Localized: '行 %1:'),
    (English: 'Compiler Error'; Localized: 'コンパイラーエラー'),
    (English: 'Illegal null character on line %1'; Localized: '%1 行目に不正な null 文字があります'),
    (English: 'Cannot find "%1"'; Localized: '"%1" が見つかりません'),
    (English: 'Invalid regular expression "%1"'; Localized: '無効な正規表現 "%1"'),
    (English: '%1 (%2 hits):'; Localized: '%1 (%2 ヒット):'),
    (English: 'Find "%1" (%2 hits in %3 files)'; Localized: '"%1" の検索 (%3 ファイル中 %2 ヒット)'),
    (English: '%1 occurrence(s) replaced.'; Localized: '%1 個の出現箇所を置換しました。'),
    (English: 'The .%1 extension was successfully associated for the current user with:%n%2'; Localized: '.%1 拡張子は、現在のユーザーに対して次のものに正常に関連付けられました:%n%2'),
    (English: 'The .%1 extension was successfully associated for all users with:%n%2'; Localized: '.%1 拡張子は、すべてのユーザーに対して次のものに正常に関連付けられました:%n%2'),
    (English: 'Error creating file association:%n%1 - %2'; Localized: 'ファイルの関連付けの作成中にエラーが発生しました:%n%1 - %2'),
    (English: 'Unable to associate for all users without administrative privileges. Do you want to associate only for yourself instead?'; Localized: '管理者権限がないため、すべてのユーザーに対して関連付けることができません。代わりに現在のユーザーに対してのみ関連付けますか？'),
    (English: 'Associate'; Localized: '関連付け'),
    (English: 'Inno Setup Script'; Localized: 'Inno Setup スクリプト'),
    (English: 'Compi&le'; Localized: 'コンパイル(&L)'),
    (English: '&Script has %1'; Localized: 'スクリプトに %1 があります(&S)'),
    (English: 'Script has %1 set'; Localized: 'スクリプトに %1 が設定されています'),
    (English: 'Invalid file format.'; Localized: '無効なファイル形式です。'),
    (English: 'Setup'; Localized: 'セットアップ'),
    (English: 'Your message text.'; Localized: 'メッセージのテキスト。'),
    (English: 'Enter your text here...'; Localized: 'ここにテキストを入力してください...'),
    (English: 'Return values'; Localized: '戻り値'),
    (English: 'Default'; Localized: '既定'),
    (English: 'Shield'; Localized: 'シールド'),
    (English: 'Instruction Text'; Localized: '指示テキスト'),
    (English: 'Message Text'; Localized: 'メッセージテキスト'),
    (English: 'user clicked %1'; Localized: 'ユーザーが %1 をクリックしました'),
    (English: 'OK'; Localized: 'OK'),
    (English: 'Yes'; Localized: 'はい'),
    (English: 'No'; Localized: 'いいえ'),
    (English: 'Cancel'; Localized: 'キャンセル'),
    (English: 'Retry'; Localized: '再試行'),
    (English: 'Ignore'; Localized: '無視'),
    (English: 'Abort'; Localized: '中止'),
    (English: 'Display a message box'; Localized: 'メッセージボックスを表示する'),
    (English: 'Name of the Sign Tool:'; Localized: '署名ツールの名前:'),
    (English: 'Invalid name.'; Localized: '無効な名前です。'),
    (English: 'Duplicate name.'; Localized: '名前が重複しています。'),
    (English: 'Command of the Sign Tool:'; Localized: '署名ツールのコマンド:'),
    (English: 'Invalid command.'; Localized: '無効なコマンドです。'),
    (English: 'The generated GUID will be inserted into the editor at the cursor position. Continue?'; Localized: '生成された GUID は、エディターのカーソル位置に挿入されます。続行しますか？'),
    (English: 'The generated Pascal script will be inserted into the editor at the cursor position, but the cursor is not in the %1 section. Continue anyway?'; Localized: '生成された Pascal スクリプトは、エディターのカーソル位置に挿入されますが、カーソルは %1 セクション内にありません。それでも続行しますか？'),
    (English: 'Classic'; Localized: 'クラシック'),
    (English: 'Visual Studio / Visual Studio Code'; Localized: 'Visual Studio / Visual Studio Code'),
    (English: 'Classic / Visual Studio'; Localized: 'クラシック / Visual Studio'),
    (English: 'Visual Studio Code'; Localized: 'Visual Studio Code'),
    (English: 'Light'; Localized: 'ライト'),
    (English: 'Dark'; Localized: 'ダーク'),
    (English: 'The new language will take effect the next time you start Inno Setup Compiler.'; Localized: '新しい言語は、次回 Inno Setup Compiler を起動したときに反映されます。'),
    (English: '&New...'; Localized: '新規(&N)...'),
    (English: '&New'; Localized: '新規(&N)'),
    (English: 'Line %1'; Localized: '行 %1'),
    (English: '%1: %2'; Localized: '%1: %2'),
    (English: 'Back (%1)'; Localized: '戻る (%1)'),
    (English: 'Forward (%1)'; Localized: '進む (%1)'),
    (English: 'Ctrl+'; Localized: 'Ctrl+'),
    (English: 'Shift+'; Localized: 'Shift+'),
    (English: 'Alt+'; Localized: 'Alt+'),
    (English: 'Num %1'; Localized: 'Num %1'),
    (English: '(32-bit)'; Localized: '(32 ビット)'),
    (English: '[Compiling]'; Localized: '[コンパイル中]'),
    (English: '[Running]'; Localized: '[実行中]'),
    (English: '[Paused]'; Localized: '[一時停止中]'),
    (English: 'Read only'; Localized: '読み取り専用'),
    (English: 'Modified'; Localized: '変更あり'),
    (English: 'Overwrite'; Localized: '上書き'),
    (English: 'Insert'; Localized: '挿入'),
    (English: 'Tabs closed: %1'; Localized: '閉じたタブ数: %1'),
    (English: 'Estimated time remaining: %1'; Localized: '推定残り時間: %1'),
    (English: 'Average KB/sec: %1'; Localized: '平均 KB/秒: %1'),
    (English: 'There was an error opening the file. Remove it from the list?'; Localized: 'ファイルを開くときにエラーが発生しました。リストから削除しますか？'),
    (English: 'The text in the %1 file has changed.%n%nDo you want to save the changes?'; Localized: '%1 ファイルのテキストが変更されています。%n%n変更を保存しますか？'),
    (English: 'Please stop the compile process before performing this command.'; Localized: 'このコマンドを実行する前に、コンパイルプロセスを停止してください。'),
    (English: 'A compile is already in progress.'; Localized: 'コンパイルは既に実行中です。'),
    (English: 'The text in the %1 file has changed and must be saved before compiling.%n%nSave the changes and continue?'; Localized: '%1 ファイルのテキストが変更されているため、コンパイル前に保存する必要があります。%n%n変更を保存して続行しますか？'),
    (English: 'Would you like to save the script before compiling?%n%nIf you answer No, the compiled installation will be placed under your My Documents folder by default.'; Localized: 'コンパイル前にスクリプトを保存しますか？%n%n「いいえ」を選択すると、コンパイルされたインストーラーは既定でマイ ドキュメントフォルダーの下に配置されます。'),
    (English: 'The selected file is an %1 file. Go to its tab instead of opening it as the new main file?'; Localized: '選択されたファイルは %1 ファイルです。新しいメインファイルとして開く代わりに、そのタブに移動しますか？'),
    (English: 'The selected file is not available as a tab. Opening as the new main file instead.'; Localized: '選択されたファイルはタブとして利用できません。代わりに新しいメインファイルとして開きます。'),
    (English: 'Error creating file (code %1). Could not save file'; Localized: 'ファイルの作成中にエラーが発生しました (コード %1)。ファイルを保存できませんでした'),
    (English: 'Error creating backup file. Could not save file'; Localized: 'バックアップファイルの作成中にエラーが発生しました。ファイルを保存できませんでした'),
    (English: 'Error removing existing file (code %1). Could not save file'; Localized: '既存のファイルの削除中にエラーが発生しました (コード %1)。ファイルを保存できませんでした'),
    (English: 'Error renaming temporary file (code %1). Could not save file'; Localized: '一時ファイルの名前変更中にエラーが発生しました (コード %1)。ファイルを保存できませんでした'),
    (English: 'Failed to open included file: %1'; Localized: 'インクルードファイルを開けませんでした: %1'),
    (English: 'Cannot start printer document.'; Localized: '印刷ジョブを開始できません。'),
    (English: 'Are you sure you want to clear the list of recently opened files?'; Localized: '最近使ったファイルのリストをクリアしてもよろしいですか？'),
    (English: 'The %1 file has been modified outside of the source editor. You might want to reload it.'; Localized: '%1 ファイルがソースエディター外で変更されました。再読み込みすることをお勧めします。'),
    (English: 'The %1 file has been modified outside of the source editor.%n%nDo you want to reload the file?'; Localized: '%1 ファイルがソースエディター外で変更されました。%n%nファイルを再読み込みしますか？'),
    (English: 'The %1 file has been modified outside of the source editor. Changes have also been made in the source editor.%n%nDo you want to reload the file and lose the changes made in the source editor?'; Localized: '%1 ファイルがソースエディター外で変更されました。ソースエディター内でも変更が行われています。%n%nファイルを再読み込みして、ソースエディターで行った変更を破棄しますか？'),
    (English: 'File not opened.'; Localized: 'ファイルが開かれていません。'),
    (English: 'Go to Line'; Localized: '行へ移動'),
    (English: 'Line number:'; Localized: '行番号:'),
    (English: 'Do you want to copy your current license key to the clipboard before opening our order page? You will need it to be able to renew it.'; Localized: '注文ページを開く前に、現在のライセンスキーをクリップボードにコピーしますか？更新の際に必要になります。'),
    (English: 'New commercial license key has been registered:%n%n%1%n%nThanks for your support!'; Localized: '新しい商用ライセンスキーが登録されました:%n%n%1%n%nご支援ありがとうございます！'),
    (English: 'Are you sure you want to remove your commercial license key and revert to non-commercial use only?'; Localized: '商用ライセンスキーを削除して、非商用利用のみに戻してもよろしいですか？'),
    (English: 'Commercial license key has been removed.'; Localized: '商用ライセンスキーが削除されました。'),
    (English: 'Your version of Inno Setup has been updated! <a id="%1">See what''s new</a>.'; Localized: 'ご使用の Inno Setup のバージョンが更新されました！<a id="%1">新機能を見る</a>。'),
    (English: 'VS Code-style editor shortcuts added! Use the <a id="%1">Editor Keys option</a> in Options dialog.'; Localized: 'VS Code スタイルのエディターショートカットが追加されました！「オプション」ダイアログで <a id="%1">エディターの「キー」オプション</a>を使用してください。'),
    (English: 'Inno Setup Compiler is available in your language! Use the <a id="%1">Language option</a> in Options dialog.'; Localized: 'Inno Setup Compiler をお使いの言語でご利用いただけます！「オプション」ダイアログで <a id="%1">「言語」オプション</a>を使用してください。'),
    (English: '<a id="%1">Ideas board is open!</a> Share your ideas and vote on others, this month only.'; Localized: '<a id="%1">アイデアボードが公開されました！</a> あなたのアイデアを共有し、他の人のアイデアに投票してください。今月限定です。'),
    (English: 'Running a version released after your update entitlement ended. <a id="%1">Renew license</a>, <a id="%2">remove key</a>, or <a id="%3">exit</a>.'; Localized: 'アップデート権の終了後にリリースされたバージョンを実行しています。<a id="%1">ライセンスを更新</a>、<a id="%2">キーを削除</a>、または <a id="%3">終了</a>。'),
    (English: 'Your update entitlement is ending soon. Please <a id="%1">renew your license</a>. Thanks!'; Localized: 'アップデート権はまもなく終了します。<a id="%1">ライセンスを更新</a>してください。よろしくお願いします！'),
    (English: 'Your update entitlement has ended. Please <a id="%1">renew your license</a>. Thanks!'; Localized: 'アップデート権が終了しました。<a id="%1">ライセンスを更新</a>してください。よろしくお願いします！'),
    (English: 'Using Inno Setup commercially? Please <a id="%1">purchase a license</a>. Thanks!'; Localized: 'Inno Setup を商用利用していますか？<a id="%1">ライセンスを購入</a>してください。よろしくお願いします！'),
    (English: 'Uninstall'; Localized: 'アンインストール'),
    (English: '%1 exit code: 0x%2'; Localized: '%1 の終了コード: 0x%2'),
    (English: '%1 exit code: %2'; Localized: '%1 の終了コード: %2'),
    (English: 'Unable to get %1 exit code (%2 failed)'; Localized: '%1 の終了コードを取得できません (%2 が失敗しました)'),
    (English: '%1 is still running; can''t get exit code'; Localized: '%1 はまだ実行中のため、終了コードを取得できません'),
    (English: 'Please stop the running %1 process before performing this command.'; Localized: 'このコマンドを実行する前に、実行中の %1 プロセスを停止してください。'),
    (English: 'This command will detach the debugger from the running %1 process. Continue?'; Localized: 'このコマンドは、実行中の %1 プロセスからデバッガーを切り離します。続行しますか？'),
    (English: 'The changes you made will not take effect until you re-compile.%n%nContinue running anyway?'; Localized: '行った変更は、再コンパイルするまで反映されません。%n%nこのまま実行を続行しますか？'),
    (English: 'A pause is already pending.'; Localized: '一時停止は既に保留中です。'),
    (English: 'No code was generated for the current line.'; Localized: '現在の行に対して生成されたコードはありません。'),
    (English: 'This will unconditionally terminate the running %1 process. Continue?'; Localized: 'これにより、実行中の %1 プロセスが無条件に強制終了されます。続行しますか？'),
    (English: 'Note that if %1 is currently in the installation phase, any changes made to the system thus far will not be undone, nor will uninstall data be written.'; Localized: '%1 が現在インストールフェーズにある場合、これまでにシステムに加えられた変更は元に戻されず、アンインストール情報も書き込まれないことに注意してください。'),
    (English: 'Evaluate'; Localized: '評価'),
    (English: 'Constant to evaluate (for example, "%1"):'; Localized: '評価する定数 (例: "%1"):'),
    (English: 'Evaluate Result'; Localized: '評価結果'),
    (English: 'Evaluate Error'; Localized: '評価エラー'),
    (English: 'An unknown error occurred.'; Localized: '不明なエラーが発生しました。'),
    (English: '%1 = "%2"'; Localized: '%1 = "%2"'),
    (English: '%1 = Exception: %2'; Localized: '%1 = 例外: %2'),
    (English: '%1 = Unknown error'; Localized: '%1 = 不明なエラー'),
    (English: 'Unknown error'; Localized: '不明なエラー'),
    (English: 'Line %1:%n%2'; Localized: '行 %1:%n%2'),
    (English: 'Runtime Error'; Localized: '実行時エラー'),
    (English: '%1 (Update entitlement ended)'; Localized: '%1 (アップデート権終了)'),
    (English: '%1 (Update entitlement ended but updated anyway)'; Localized: '%1 (アップデート権は終了済みですが更新されました)'),
    (English: 'Non-commercial use only'; Localized: '非商用利用のみ'),
    (English: 'Single User'; Localized: 'Single User'),
    (English: 'Team'; Localized: 'Team'),
    (English: 'Enterprise'; Localized: 'Enterprise'),
    (English: 'Inno Setup %1 License'; Localized: 'Inno Setup %1 ライセンス'),
    (English: '%1, %2.'; Localized: '%1、%2。'),
    (English: 'Includes updates until %1, major and minor.'; Localized: '%1 までのメジャーおよびマイナーアップデートを含みます。'),
    (English: 'Includes all future updates, major and minor.'; Localized: '将来のすべてのメジャーおよびマイナーアップデートを含みます。'),
    (English: '%1 Entries Designer'; Localized: '%1 エントリデザイナー'),
    (English: '&Insert'; Localized: '挿入(&I)'),
    (English: '&Parameters...'; Localized: 'パラメーター(&P)...'),
    (English: 'Remo&ve'; Localized: '削除(&V)'),
    (English: 'Add Fol&der...'; Localized: 'フォルダーの追加(&D)...'),
    (English: '&Add File(s)...'; Localized: 'ファイルの追加(&A)...'),
    (English: '&Files:'; Localized: 'ファイル(&F):'),
    (English: 'Add D&ownload...'; Localized: 'ダウンロードの追加(&O)...'),
    (English: 'Go to File'; Localized: 'ファイルに移動'),
    (English: 'Enter Commercial License Key'; Localized: '商用ライセンスキーの入力'),
    (English: 'Paste your license key below'; Localized: 'ライセンスキーを下に貼り付けてください'),
    (English: 'Close'; Localized: '閉じる'),
    (English: 'New Main Script (%1)'; Localized: '新しいメインスクリプト (%1)'),
    (English: 'Open Main Script (%1)'; Localized: 'メインスクリプトを開く (%1)'),
    (English: 'Save (%1)'; Localized: '保存 (%1)'),
    (English: 'Stop Compile (%1)'; Localized: 'コンパイルの停止 (%1)'),
    (English: 'Target Setup (%1)'; Localized: 'セットアップをターゲットに設定 (%1)'),
    (English: 'Target Uninstall (%1)'; Localized: 'アンインストールをターゲットに設定 (%1)'),
    (English: 'Help (%1)'; Localized: 'ヘルプ (%1)'),
    (English: 'Main Script'; Localized: 'メインスクリプト'),
    (English: 'Close Banner'; Localized: 'バナーを閉じる'),
    (English: '&File'; Localized: 'ファイル(&F)'),
    (English: '&Open...'; Localized: '開く(&O)...'),
    (English: 'Open &Recent'; Localized: '最近使ったファイル(&R)'),
    (English: '&Clear Recently Opened'; Localized: '最近使ったファイルをクリア(&C)'),
    (English: '&Save'; Localized: '保存(&S)'),
    (English: 'Save &As...'; Localized: '名前を付けて保存(&A)...'),
    (English: 'Save &Encoding'; Localized: 'エンコードを指定して保存(&E)'),
    (English: '&Auto (ANSI or UTF-8)'; Localized: '自動(&A) (ANSI または UTF-8)'),
    (English: '&UTF-8'; Localized: 'UTF-8(&U)'),
    (English: 'UTF-8 with &BOM'; Localized: 'BOM 付き UTF-8(&B)'),
    (English: 'Sa&ve All'; Localized: 'すべて保存(&V)'),
    (English: '&Print...'; Localized: '印刷(&P)...'),
    (English: 'E&xit'; Localized: '終了(&X)'),
    (English: '&Edit'; Localized: '編集(&E)'),
    (English: '&Undo'; Localized: '元に戻す(&U)'),
    (English: '&Redo'; Localized: 'やり直し(&R)'),
    (English: 'Cu&t'; Localized: '切り取り(&T)'),
    (English: '&Copy'; Localized: 'コピー(&C)'),
    (English: '&Paste'; Localized: '貼り付け(&P)'),
    (English: 'De&lete'; Localized: '削除(&L)'),
    (English: 'Select &All'; Localized: 'すべて選択(&A)'),
    (English: 'Add Next &Occurrence'; Localized: '次の出現箇所を追加(&O)'),
    (English: '&Select All Occurrences'; Localized: 'すべての出現箇所を選択(&S)'),
    (English: 'Select All Find &Matches'; Localized: 'すべての検索一致箇所を選択(&M)'),
    (English: '&Find...'; Localized: '検索(&F)...'),
    (English: 'F&ind in Files...'; Localized: 'ファイル内を検索(&I)...'),
    (English: 'Find &Next'; Localized: '次を検索(&N)'),
    (English: 'Find Pre&vious'; Localized: '前を検索(&V)'),
    (English: 'R&eplace...'; Localized: '置換(&E)...'),
    (English: 'Use Regular E&xpressions'; Localized: '正規表現を使用(&X)'),
    (English: 'Fol&d Section'; Localized: 'セクションの折りたたみ(&D)'),
    (English: '&Unfold Section'; Localized: 'セクションの展開(&U)'),
    (English: 'Go to File...'; Localized: 'ファイルに移動...'),
    (English: '&Go to Line...'; Localized: '行へ移動(&G)...'),
    (English: 'Toggle Line Comment'; Localized: '行コメントの切り替え'),
    (English: 'Go To Matching Brace'; Localized: '対応するかっこへ移動'),
    (English: '&View'; Localized: '表示(&V)'),
    (English: '&Zoom'; Localized: 'ズーム(&Z)'),
    (English: 'Zoom &In'; Localized: '拡大(&I)'),
    (English: 'Zoom &Out'; Localized: '縮小(&O)'),
    (English: '&Reset'; Localized: 'リセット(&R)'),
    (English: '&Toolbar'; Localized: 'ツール バー(&T)'),
    (English: 'St&atus Bar'; Localized: 'ステータス バー(&A)'),
    (English: '&Next Tab'; Localized: '次のタブ(&N)'),
    (English: '&Previous Tab'; Localized: '前のタブ(&P)'),
    (English: 'C&lose Tab'; Localized: 'タブを閉じる(&L)'),
    (English: 'Re&open Tab'; Localized: 'タブを再度開く(&O)'),
    (English: 'Reopen &All Tabs'; Localized: 'すべてのタブを再度開く(&A)'),
    (English: 'C&lose Current Tab'; Localized: '現在のタブを閉じる(&L)'),
    (English: '&Compiler Output'; Localized: 'コンパイラー出力(&C)'),
    (English: '&Debug Output'; Localized: 'デバッグ出力(&D)'),
    (English: 'D&ebug Call Stack'; Localized: 'デバッグ コール スタック(&E)'),
    (English: '&Find Results'; Localized: '検索結果(&F)'),
    (English: '&Hide Bottom Pane'; Localized: '下部ペインを非表示(&H)'),
    (English: '&Word Wrap'; Localized: '折り返し(&W)'),
    (English: '&Build'; Localized: 'ビルド(&B)'),
    (English: '&Compile'; Localized: 'コンパイル(&C)'),
    (English: 'S&top Compile'; Localized: 'コンパイルの停止(&T)'),
    (English: '&Low Priority During Compile'; Localized: 'コンパイル中は低優先度(&L)'),
    (English: '&Disable Output'; Localized: '出力を無効化(&D)'),
    (English: 'Disable Co&mpression'; Localized: '圧縮を無効化(&M)'),
    (English: 'Disable &Signing'; Localized: '署名を無効化(&S)'),
    (English: 'Disable Signcheck &Validation'; Localized: '署名チェックの検証を無効化(&V)'),
    (English: '&Open Output Folder'; Localized: '出力フォルダーを開く(&O)'),
    (English: '&Run'; Localized: '実行(&R)'),
    (English: '&Run...'; Localized: '実行(&R)...'),
    (English: 'Run to &Cursor'; Localized: 'カーソル位置まで実行(&C)'),
    (English: 'Step &Into'; Localized: 'ステップ イン(&I)'),
    (English: 'Step &Over'; Localized: 'ステップ オーバー(&O)'),
    (English: 'Step Out'; Localized: 'ステップ アウト'),
    (English: 'Toggle &Breakpoint'; Localized: 'ブレークポイントの切り替え(&B)'),
    (English: '&Delete All Breakpoints'; Localized: 'すべてのブレークポイントを削除(&D)'),
    (English: 'P&ause'; Localized: '一時停止(&A)'),
    (English: '&Terminate'; Localized: '強制終了(&T)'),
    (English: '&Evaluate Constant...'; Localized: '定数の評価(&E)...'),
    (English: 'Target &Setup'; Localized: 'セットアップをターゲットに設定(&S)'),
    (English: 'Target &Uninstall'; Localized: 'アンインストールをターゲットに設定(&U)'),
    (English: '&Tools'; Localized: 'ツール(&T)'),
    (English: '&Add/Remove Programs'; Localized: 'プログラムの追加と削除(&A)'),
    (English: 'Generate &GUID'; Localized: 'GUID の生成(&G)'),
    (English: 'Generate %1 Entries...'; Localized: '%1 エントリの生成...'),
    (English: 'Generate %1 Call...'; Localized: '%1 呼び出しの生成...'),
    (English: '&Configure Sign Tools...'; Localized: '署名ツールの構成(&C)...'),
    (English: '&Options...'; Localized: 'オプション(&O)...'),
    (English: '&Help'; Localized: 'ヘルプ(&H)'),
    (English: 'Purchase or Renew Commercial &License'; Localized: '商用ライセンスの購入または更新(&L)'),
    (English: 'Enter Commercial License &Key...'; Localized: '商用ライセンスキーの入力(&K)...'),
    (English: 'Remove Commercial License Key'; Localized: '商用ライセンスキーの削除'),
    (English: '&Donate'; Localized: '寄付(&D)'),
    (English: '&Keyboard And Mouse Commands'; Localized: 'キーボードとマウスのコマンド(&K)'),
    (English: 'Regular E&xpressions'; Localized: '正規表現(&X)'),
    (English: 'Inno &Setup Documentation'; Localized: 'Inno Setup ドキュメント(&S)'),
    (English: 'Inno Setup &Example Scripts'; Localized: 'Inno Setup サンプルスクリプト(&E)'),
    (English: 'Inno Setup &FAQ'; Localized: 'Inno Setup FAQ(&F)'),
    (English: 'Inno Setup &Mailing List'; Localized: 'Inno Setup メーリングリスト(&M)'),
    (English: 'Inno Setup &Revision History'; Localized: 'Inno Setup 改訂履歴(&R)'),
    (English: 'Inno Setup &Web Site'; Localized: 'Inno Setup Web サイト(&W)'),
    (English: 'Inno Setup &Preprocessor Documentation'; Localized: 'Inno Setup プリプロセッサードキュメント(&P)'),
    (English: '&About Inno Setup'; Localized: 'Inno Setup のバージョン情報(&A)'),
    (English: '%1 Call Designer'; Localized: '%1 呼び出しデザイナー'),
    (English: 'Instruction'; Localized: '指示'),
    (English: 'Message'; Localized: 'メッセージ'),
    (English: 'Buttons'; Localized: 'ボタン'),
    (English: ' Type '; Localized: ' 種類 '),
    (English: 'Suppressible'; Localized: '抑制可能'),
    (English: ' Flags '; Localized: ' フラグ '),
    (English: 'Default button'; Localized: '既定のボタン'),
    (English: ' Icon '; Localized: ' アイコン '),
    (English: ' Return values '; Localized: ' 戻り値 '),
    (English: '&Preview'; Localized: 'プレビュー(&P)'),
    (English: 'Options'; Localized: 'オプション'),
    (English: ' Miscellaneous '; Localized: ' その他 '),
    (English: 'Show &Welcome dialog at startup'; Localized: '起動時にようこそダイアログを表示(&W)'),
    (English: 'Use the Inno Setup &Script Wizard'; Localized: 'Inno Setup スクリプトウィザードを使用(&S)'),
    (English: 'Automatically sa&ve before compiling'; Localized: 'コンパイル前に自動的に保存(&V)'),
    (English: 'Create &backups when saving'; Localized: '保存時にバックアップを作成(&B)'),
    (English: 'Allow &Undo after save'; Localized: '保存後に元に戻すことを許可(&U)'),
    (English: 'Display &full path in title bar'; Localized: 'タイトル バーに完全なパスを表示(&F)'),
    (English: '&Pause on exceptions'; Localized: '例外発生時に一時停止(&P)'),
    (English: '&Launch Setup/Uninstall as administrator'; Localized: 'セットアップ/アンインストールを管理者として起動(&L)'),
    (English: 'Colori&ze "Compiler Output" view'; Localized: '「コンパイラー出力」ビューに色を付ける(&Z)'),
    (English: 'Automatically open %1 files'; Localized: '%1 ファイルを自動的に開く'),
    (English: 'Automatically show preprocessor output'; Localized: 'プリプロセッサー出力を自動的に表示'),
    (English: 'Menu &keys:'; Localized: 'メニューキー(&K):'),
    (English: 'Automatically reload files'; Localized: 'ファイルを自動的に再読み込み'),
    (English: 'Allow Undo after reload'; Localized: '再読み込み後に元に戻すことを許可'),
    (English: 'Keep new %1 files closed'; Localized: '新しい %1 ファイルを閉じたままにする'),
    (English: 'Language:'; Localized: '言語:'),
    (English: ' Editor '; Localized: ' エディター '),
    (English: 'Invoke autoco&mplete automatically'; Localized: 'オートコンプリートを自動的に呼び出す(&M)'),
    (English: 'Use syntax &highlighting'; Localized: '構文の強調表示を使用(&H)'),
    (English: 'U&nderline syntax errors'; Localized: '構文エラーに下線を引く(&N)'),
    (English: 'Allow cursor to move beyond &end of lines'; Localized: 'カーソルが行末を越えて移動することを許可(&E)'),
    (English: 'Enable section f&olding'; Localized: 'セクションの折りたたみを有効化(&O)'),
    (English: 'Use tab cha&racter'; Localized: 'タブ文字を使用(&R)'),
    (English: 'Auto &indent mode'; Localized: '自動インデントモード(&I)'),
    (English: 'Show indentation &guides'; Localized: 'インデント ガイドを表示(&G)'),
    (English: 'Font:'; Localized: 'フォント:'),
    (English: 'AaBbXxZz'; Localized: 'AaBbXxZz'),
    (English: '&Change...'; Localized: '変更(&C)...'),
    (English: '&Tab Width:'; Localized: 'タブ幅(&T):'),
    (English: 'Show &line numbers in gutter'; Localized: 'ガターに行番号を表示(&L)'),
    (English: 'T&heme:'; Localized: 'テーマ(&H):'),
    (English: 'Highlight occurrences of current selection'; Localized: '現在の選択範囲の出現箇所を強調表示'),
    (English: 'Highlight occurrences of current wor&d'; Localized: '現在の単語の出現箇所を強調表示(&D)'),
    (English: 'Ke&ys:'; Localized: 'キー(&Y):'),
    (English: 'Show whitespace'; Localized: '空白文字を表示'),
    (English: 'Smart Home key'; Localized: 'スマート Home キー'),
    (English: '&Associate .%1 files with this compiler'; Localized: '.%1 ファイルをこのコンパイラーに関連付ける(&A)'),
    (English: '&Windows registry file (.%1) to import:'; Localized: 'インポートする Windows レジストリファイル (.%1)(&W):'),
    (English: 'B&rowse...'; Localized: '参照(&R)...'),
    (English: 'Settings (for all keys and values):'; Localized: '設定 (すべてのキーと値に対して):'),
    (English: 'Also delete keys which are not empty'; Localized: '空でないキーも削除する'),
    (English: 'Delete keys which are empty on uninstall'; Localized: 'アンインストール時に空のキーを削除する'),
    (English: 'Delete values on uninstall'; Localized: 'アンインストール時に値を削除する'),
    (English: 'Minimum Windows version:'; Localized: 'Windows の最小バージョン:'),
    (English: 'Configure Sign Tools'; Localized: '署名ツールの構成'),
    (English: ' Sign Tools '; Localized: ' 署名ツール '),
    (English: '&Add...'; Localized: '追加(&A)...'),
    (English: '&Edit...'; Localized: '編集(&E)...'),
    (English: 'Be notified by e-mail of new Inno Setup releases'; Localized: '新しい Inno Setup のリリース通知を電子メールで受け取る'),
    (English: 'Subscribe'; Localized: '登録'),
    (English: ' New file '; Localized: ' 新しいファイル '),
    (English: 'Create a new &empty script file'; Localized: '新しい空のスクリプトファイルを作成(&E)'),
    (English: 'Create a new script file using the &Script Wizard'; Localized: 'スクリプトウィザードを使用して新しいスクリプトファイルを作成(&S)'),
    (English: ' Open file '; Localized: ' ファイルを開く '),
    (English: 'Open an e&xisting script file'; Localized: '既存のスクリプトファイルを開く(&X)'),
    (English: '&Don''t show this dialog again'; Localized: 'このダイアログを再度表示しない(&D)'),
    (English: 'Script Wizard File'; Localized: 'スクリプトウィザードファイル'),
    (English: 'bold'; Localized: '太字'),
    (English: ' = required'; Localized: ' = 必須'),
    (English: ' Destination '; Localized: ' インストール先 '),
    (English: 'Destination &base folder:'; Localized: 'インストール先ベースフォルダー(&B):'),
    (English: 'Destination &subfolder:'; Localized: 'インストール先サブフォルダー(&S):'),
    (English: 'Destination &name:'; Localized: 'インストール先の名前(&N):'),
    (English: ' Source '; Localized: ' ソース '),
    (English: '&Source file or folder:'; Localized: 'ソースファイルまたはフォルダー(&S):'),
    (English: '&Recurse subfolders'; Localized: 'サブフォルダーを再帰的に処理(&R)'),
    (English: '&Include empty subfolders'; Localized: '空のサブフォルダーを含める(&I)'),
    (English: '&Extract archive'; Localized: 'アーカイブを展開(&E)'),
    (English: 'Welcome to the %1'; Localized: '%1 へようこそ'),
    (English: 'This wizard will guide you through the process of creating a new Inno Setup script file. The results will be used to generate a new script file which can be compiled directly or saved on disk for later use.%n%nNot all features of Inno Setup are covered by this wizard. See the documentation for details on creating Inno Setup script files.%n%nClick Next to continue, or Cancel to exit this wizard.'; Localized: 'このウィザードは、新しい Inno Setup スクリプトファイルを作成する手順をご案内します。入力内容は、直接コンパイルすることも、後で使用するためにディスクに保存することもできる新しいスクリプトファイルの生成に使用されます。%n%nInno Setup のすべての機能がこのウィザードでカバーされているわけではありません。Inno Setup スクリプトファイルの作成方法の詳細については、ドキュメントを参照してください。%n%n続行するには「次へ」を、このウィザードを終了するには「キャンセル」をクリックしてください。'),
    (English: 'Application na&me:'; Localized: 'アプリケーション名(&M):'),
    (English: 'Application &version:'; Localized: 'アプリケーションのバージョン(&V):'),
    (English: 'Application &publisher:'; Localized: 'アプリケーションの発行元(&P):'),
    (English: 'Application &website:'; Localized: 'アプリケーションの Web サイト(&W):'),
    (English: 'Application folder na&me:'; Localized: 'アプリケーションフォルダー名(&M):'),
    (English: 'Application &destination base folder:'; Localized: 'アプリケーションのインストール先ベースフォルダー(&D):'),
    (English: 'Other:'; Localized: 'その他:'),
    (English: 'Allow user to &change the application folder'; Localized: 'ユーザーがアプリケーションフォルダーを変更できるようにする(&C)'),
    (English: 'The application doe&sn''t need a folder'; Localized: 'アプリケーションにフォルダーは不要(&S)'),
    (English: 'Other application &files:'; Localized: 'その他のアプリケーションファイル(&F):'),
    (English: 'Application &main executable file:'; Localized: 'アプリケーションのメイン実行ファイル(&M):'),
    (English: 'Allow &user to start the application after Setup has finished'; Localized: 'セットアップ完了後にユーザーがアプリケーションを起動できるようにする(&U)'),
    (English: 'The application doe&sn''t have a main executable file'; Localized: 'アプリケーションにメイン実行ファイルがない(&S)'),
    (English: 'Application file type na&me:'; Localized: 'アプリケーションのファイルの種類の名前(&M):'),
    (English: '&Associate a file type to the main executable'; Localized: 'メイン実行ファイルにファイルの種類を関連付ける(&A)'),
    (English: 'Application file type &extension:'; Localized: 'アプリケーションのファイルの種類の拡張子(&E):'),
    (English: 'Application &Start Menu folder name:'; Localized: 'アプリケーションのスタートメニューフォルダー名(&S):'),
    (English: 'Other shortcuts to the main executable:'; Localized: 'メイン実行ファイルへのその他のショートカット:'),
    (English: 'Allow user to &change the Start Menu folder name'; Localized: 'ユーザーがスタートメニューフォルダー名を変更できるようにする(&C)'),
    (English: 'Allow user to &disable Start Menu folder creation'; Localized: 'ユーザーがスタートメニューフォルダーの作成を無効にできるようにする(&D)'),
    (English: 'Allow user to create a deskto&p shortcut'; Localized: 'ユーザーがデスクトップショートカットを作成できるようにする(&P)'),
    (English: 'Create an &Uninstall shortcut in the Start Menu folder'; Localized: 'スタートメニューフォルダーにアンインストールのショートカットを作成(&U)'),
    (English: 'Create an &Internet shortcut in the Start Menu folder'; Localized: 'スタートメニューフォルダーにインターネットショートカットを作成(&I)'),
    (English: '&Create a Start Menu shortcut but no folder'; Localized: 'フォルダーは作成せず、スタートメニューにショートカットを作成(&C)'),
    (English: '&License file:'; Localized: 'ライセンスファイル(&L):'),
    (English: '&Information file shown before installation:'; Localized: 'インストール前に表示する情報ファイル(&I):'),
    (English: 'Information file shown &after installation:'; Localized: 'インストール後に表示する情報ファイル(&A):'),
    (English: 'Install mode:'; Localized: 'インストールモード:'),
    (English: '&Administrative install mode (install for all users)'; Localized: '管理者インストールモード(&A) (すべてのユーザーにインストール)'),
    (English: 'Non a&dministrative install mode (install for current user only)'; Localized: '非管理者インストールモード(&D) (現在のユーザーのみにインストール)'),
    (English: 'Allow user to &override the install mode via the command line'; Localized: 'ユーザーがコマンドラインでインストールモードを上書きできるようにする(&O)'),
    (English: 'Ask the user to &choose the install mode at startup'; Localized: '起動時にユーザーにインストールモードの選択を求める(&C)'),
    (English: '&Languages:'; Localized: '言語(&L):'),
    (English: '&Deselect All'; Localized: 'すべて選択解除(&D)'),
    (English: 'Custom compiler output fol&der:'; Localized: 'カスタムコンパイラー出力フォルダー(&D):'),
    (English: 'Compiler output base &file name:'; Localized: 'コンパイラー出力のベースファイル名(&F):'),
    (English: 'Custom Setup &icon file:'; Localized: 'カスタムセットアップアイコンファイル(&I):'),
    (English: 'Setup &password:'; Localized: 'セットアップパスワード(&P):'),
    (English: 'Use the password to &encrypt the application files'; Localized: 'パスワードを使用してアプリケーションファイルを暗号化(&E)'),
    (English: '&Wizard style:'; Localized: 'ウィザードスタイル(&W):'),
    (English: 'You have successfully completed the %1.%n%nTo close this wizard and generate the new script file, click Finish.'; Localized: '%1 が正常に完了しました。%n%nこのウィザードを閉じて新しいスクリプトファイルを生成するには、「完了」をクリックしてください。'),
    (English: '&Back'; Localized: '戻る(&B)'),
    (English: '''%s'' is not a valid integer value'; Localized: '''%s'' は有効な整数値ではありません'),
    (English: '''%s'' is not a valid integer value for %s type'; Localized: '''%s'' は %s 型の有効な整数値ではありません'),
    (English: '''%s'' is not a valid floating point value'; Localized: '''%s'' は有効な浮動小数点値ではありません'),
    (English: '''%d.%d'' is not a valid timestamp'; Localized: '''%d.%d'' は有効なタイムスタンプではありません'),
    (English: '''%s'' is not a valid GUID value'; Localized: '''%s'' は有効な GUID 値ではありません'),
    (English: 'Invalid argument to time encode'; Localized: '時刻のエンコードに対する引数が無効です'),
    (English: 'Invalid argument to date encode'; Localized: '日付のエンコードに対する引数が無効です'),
    (English: 'Out of memory'; Localized: 'メモリ不足'),
    (English: 'I/O error %d'; Localized: '入出力エラー %d'),
    (English: 'File not found'; Localized: 'ファイルが見つかりません'),
    (English: 'Invalid filename'; Localized: '無効なファイル名'),
    (English: 'Too many open files'; Localized: '開いているファイルが多すぎます'),
    (English: 'File access denied'; Localized: 'ファイルへのアクセスが拒否されました'),
    (English: 'Read beyond end of file'; Localized: 'ファイルの末尾を超えて読み取りました'),
    (English: 'Disk full'; Localized: 'ディスクがいっぱいです'),
    (English: 'Invalid numeric input'; Localized: '無効な数値入力'),
    (English: 'Division by zero'; Localized: 'ゼロによる除算'),
    (English: 'Range check error'; Localized: '範囲チェックエラー'),
    (English: 'Integer overflow'; Localized: '整数オーバーフロー'),
    (English: 'Invalid floating point operation'; Localized: '無効な浮動小数点演算'),
    (English: 'Floating point division by zero'; Localized: '浮動小数点のゼロによる除算'),
    (English: 'Floating point overflow'; Localized: '浮動小数点オーバーフロー'),
    (English: 'Floating point underflow'; Localized: '浮動小数点アンダーフロー'),
    (English: 'Invalid pointer operation'; Localized: '無効なポインター操作'),
    (English: 'Invalid class typecast'; Localized: '無効なクラスの型変換'),
    (English: 'Access violation at address %p. %s of address %p'; Localized: 'アドレス %p でアクセス違反が発生しました。%s（アドレス %p）'),
    (English: 'Access violation'; Localized: 'アクセス違反'),
    (English: 'Stack overflow'; Localized: 'スタックオーバーフロー'),
    (English: 'Control-C hit'; Localized: 'Control-C が押されました'),
    (English: 'Privileged instruction'; Localized: '特権命令'),
    (English: 'Operation aborted'; Localized: '操作が中止されました'),
    (English: 'Exception %s in module %s at %p.'#13#10'%s%s'#13#10; Localized: '例外 %s がモジュール %s の %p で発生しました。'#13#10'%s%s'#13#10),
    (English: 'Application Error'; Localized: 'アプリケーションエラー'),
    (English: 'Format ''%s'' invalid or incompatible with argument'; Localized: '書式 ''%s'' が無効か、引数と互換性がありません'),
    (English: 'No argument for format ''%s'''; Localized: '書式 ''%s'' に対応する引数がありません'),
    (English: 'Variant method calls not supported'; Localized: 'Variant のメソッド呼び出しはサポートされていません'),
    (English: 'Read'; Localized: '読み取り'),
    (English: 'Write'; Localized: '書き込み'),
    (English: 'Execution'; Localized: '実行'),
    (English: 'Invalid access'; Localized: '無効なアクセス'),
    (English: 'Error creating variant or safe array'; Localized: 'Variant またはセーフ配列の作成中にエラーが発生しました'),
    (English: 'Variant or safe array index out of bounds'; Localized: 'Variant またはセーフ配列のインデックスが範囲外です'),
    (English: 'Variant or safe array is locked'; Localized: 'Variant またはセーフ配列がロックされています'),
    (English: 'Invalid variant type conversion'; Localized: '無効な Variant 型変換'),
    (English: 'Invalid variant operation'; Localized: '無効な Variant 操作'),
    (English: 'Invalid NULL variant operation'; Localized: '無効な NULL Variant 操作'),
    (English: 'Invalid variant operation (%s%.8x)'#10'%s'; Localized: '無効な Variant 操作 (%s%.8x)'#10'%s'),
    (English: 'Could not convert variant of type (%s) into type (%s)'; Localized: '型 (%s) の Variant を型 (%s) に変換できませんでした'),
    (English: 'Overflow while converting variant of type (%s) into type (%s)'; Localized: '型 (%s) の Variant を型 (%s) に変換中にオーバーフローが発生しました'),
    (English: 'Variant overflow'; Localized: 'Variant のオーバーフロー'),
    (English: 'Invalid argument'; Localized: '無効な引数'),
    (English: 'Invalid variant type'; Localized: '無効な Variant 型'),
    (English: 'Operation not supported'; Localized: '操作はサポートされていません'),
    (English: 'Unexpected variant error'; Localized: '予期しない Variant エラー'),
    (English: 'External exception %x'; Localized: '外部例外 %x'),
    (English: 'Assertion failed'; Localized: 'アサーションに失敗しました'),
    (English: 'Interface not supported'; Localized: 'インターフェイスはサポートされていません'),
    (English: 'Exception in safecall method'; Localized: 'safecall メソッドで例外が発生しました'),
    (English: 'Object lock not owned'; Localized: 'オブジェクトのロックを所有していません'),
    (English: 'Monitor support function not initialized'; Localized: 'モニターのサポート関数が初期化されていません'),
    (English: 'Feature not implemented'; Localized: '機能が実装されていません'),
    (English: 'Method called on disposed object'; Localized: '破棄されたオブジェクトに対してメソッドが呼び出されました'),
    (English: '%s (%s, line %d)'; Localized: '%s (%s, %d 行目)'),
    (English: 'Abstract Error'; Localized: '抽象エラー'),
    (English: 'Access violation at address %p in module ''%s'' (offset %x). %s of address %p'; Localized: 'アドレス %p（モジュール ''%s''、オフセット %x）でアクセス違反が発生しました。%s（アドレス %p）'),
    (English: 'System Error.  Code: %d.'#13#10'%s%s'; Localized: 'システムエラー。  コード: %d。'#13#10'%s%s'),
    (English: 'A call to an OS function failed'; Localized: 'OS 関数の呼び出しに失敗しました'),
    (English: 'Jan'; Localized: '1月'),
    (English: 'Feb'; Localized: '2月'),
    (English: 'Mar'; Localized: '3月'),
    (English: 'Apr'; Localized: '4月'),
    (English: 'May'; Localized: '5月'),
    (English: 'Jun'; Localized: '6月'),
    (English: 'Jul'; Localized: '7月'),
    (English: 'Aug'; Localized: '8月'),
    (English: 'Sep'; Localized: '9月'),
    (English: 'Oct'; Localized: '10月'),
    (English: 'Nov'; Localized: '11月'),
    (English: 'Dec'; Localized: '12月'),
    (English: 'January'; Localized: '1月'),
    (English: 'February'; Localized: '2月'),
    (English: 'March'; Localized: '3月'),
    (English: 'April'; Localized: '4月'),
    (English: 'June'; Localized: '6月'),
    (English: 'July'; Localized: '7月'),
    (English: 'August'; Localized: '8月'),
    (English: 'September'; Localized: '9月'),
    (English: 'October'; Localized: '10月'),
    (English: 'November'; Localized: '11月'),
    (English: 'December'; Localized: '12月'),
    (English: 'Sun'; Localized: '日'),
    (English: 'Mon'; Localized: '月'),
    (English: 'Tue'; Localized: '火'),
    (English: 'Wed'; Localized: '水'),
    (English: 'Thu'; Localized: '木'),
    (English: 'Fri'; Localized: '金'),
    (English: 'Sat'; Localized: '土'),
    (English: 'Sunday'; Localized: '日曜日'),
    (English: 'Monday'; Localized: '月曜日'),
    (English: 'Tuesday'; Localized: '火曜日'),
    (English: 'Wednesday'; Localized: '水曜日'),
    (English: 'Thursday'; Localized: '木曜日'),
    (English: 'Friday'; Localized: '金曜日'),
    (English: 'Saturday'; Localized: '土曜日'),
    (English: 'Invalid source array'; Localized: '無効なソース配列'),
    (English: 'Invalid destination array'; Localized: '無効なコピー先配列'),
    (English: 'Character index out of bounds (%d)'; Localized: '文字インデックスが範囲外です (%d)'),
    (English: 'Start index out of bounds (%d)'; Localized: '開始インデックスが範囲外です (%d)'),
    (English: 'Invalid count (%d)'; Localized: '無効なカウント (%d)'),
    (English: 'Invalid destination index (%d)'; Localized: '無効なコピー先インデックス (%d)'),
    (English: 'Invalid code page'; Localized: '無効なコード ページ'),
    (English: 'No mapping for the Unicode character exists in the target multi-byte code page'; Localized: '対象のマルチバイト コード ページに、その Unicode 文字のマッピングが存在しません'),
    (English: 'Invalid StringBaseIndex'; Localized: '無効な StringBaseIndex'),
    (English: '''%s'' is not a valid %s color value'; Localized: '''%s'' は有効な %s の色の値ではありません'),
    (English: 'Ancestor for ''%s'' not found'; Localized: '''%s'' の先祖が見つかりません'),
    (English: 'Cannot assign a %s to a %s'; Localized: '%s を %s に割り当てることはできません'),
    (English: 'Bits index out of range'; Localized: 'ビットのインデックスが範囲外です'),
    (English: 'Can''t write to a read-only resource stream'; Localized: '読み取り専用のリソース ストリームには書き込めません'),
    (English: '''''%s'''' expected'; Localized: '''''%s'''' が必要です'),
    (English: 'CheckSynchronize called from thread $%x, which is NOT the main thread'; Localized: 'CheckSynchronize がスレッド $%x から呼び出されました。これはメイン スレッドではありません'),
    (English: 'Class %s not found'; Localized: 'クラス %s が見つかりません'),
    (English: 'A class named %s already exists'; Localized: '%s という名前のクラスは既に存在します'),
    (English: 'List does not allow duplicates ($0%x)'; Localized: 'リストは重複を許可しません ($0%x)'),
    (English: 'A component named %s already exists'; Localized: '%s という名前のコンポーネントは既に存在します'),
    (English: 'String list does not allow duplicates'; Localized: '文字列リストは重複を許可しません'),
    (English: 'Cannot create file "%s". %s'; Localized: 'ファイル "%s" を作成できません。%s'),
    (English: 'Cannot open file "%s". %s'; Localized: 'ファイル "%s" を開けません。%s'),
    (English: 'Identifier expected'; Localized: '識別子が必要です'),
    (English: 'Invalid binary value'; Localized: '無効なバイナリ値'),
    (English: 'Invalid stream format'; Localized: '無効なストリーム形式'),
    (English: '''%s'' is an invalid mask at (%d)'; Localized: '''%s'' は (%d) で無効なマスクです'),
    (English: '''''%s'''' is not a valid component name'; Localized: '''''%s'''' は有効なコンポーネント名ではありません'),
    (English: 'Invalid property value'; Localized: '無効なプロパティ値'),
    (English: 'Invalid property path'; Localized: '無効なプロパティ パス'),
    (English: 'Invalid data type for ''%s'''; Localized: '''%s'' の無効なデータ型'),
    (English: 'Invalid string constant'; Localized: '無効な文字列定数'),
    (English: 'Line too long'; Localized: '行が長すぎます'),
    (English: 'List capacity out of bounds (%d)'; Localized: 'リストの容量が範囲外です (%d)'),
    (English: 'List count out of bounds (%d)'; Localized: 'リストのカウントが範囲外です (%d)'),
    (English: 'List index out of bounds (%d)'; Localized: 'リストのインデックスが範囲外です (%d)'),
    (English: '.  %s range is 0..%d'; Localized: '.  %s の範囲は 0..%d です'),
    (English: '.  %s is empty'; Localized: '.  %s は空です'),
    (English: 'Out of memory while expanding memory stream'; Localized: 'メモリ ストリームの拡張中にメモリが不足しました'),
    (English: '%s has not been registered as a COM class'; Localized: '%s は COM クラスとして登録されていません'),
    (English: 'Printer is not currently printing'; Localized: 'プリンターは現在印刷していません'),
    (English: 'Number expected'; Localized: '数値が必要です'),
    (English: 'ANSI or UTF8 encoding expected'; Localized: 'ANSI または UTF8 エンコードが必要です'),
    (English: '%s on line %d'; Localized: '%s (%d 行目)'),
    (English: 'Error reading %s%s%s: %s'; Localized: '%s%s%s の読み取り中にエラーが発生しました: %s'),
    (English: 'Printing in progress'; Localized: '印刷を実行中です'),
    (English: 'Stream read error'; Localized: 'ストリームの読み取りエラー'),
    (English: 'Property is read-only'; Localized: 'プロパティは読み取り専用です'),
    (English: 'Failed to create key %s'; Localized: 'キー %s の作成に失敗しました'),
    (English: 'Failed to get data for ''%s'''; Localized: '''%s'' のデータの取得に失敗しました'),
    (English: 'Failed to set data for ''%s'''; Localized: '''%s'' のデータの設定に失敗しました'),
    (English: 'Resource %s not found'; Localized: 'リソース %s が見つかりません'),
    (English: '%s.Seek not implemented'; Localized: '%s.Seek は実装されていません'),
    (English: 'Operation not allowed on sorted list'; Localized: 'ソートされたリストでは許可されない操作です'),
    (English: 'String expected'; Localized: '文字列が必要です'),
    (English: '%s expected'; Localized: '%s が必要です'),
    (English: '%s not in a class registration group'; Localized: '%s はクラス登録グループに含まれていません'),
    (English: 'Property %s does not exist'; Localized: 'プロパティ %s は存在しません'),
    (English: 'Stream write error'; Localized: 'ストリームの書き込みエラー'),
    (English: 'Thread creation error: %s'; Localized: 'スレッドの作成エラー: %s'),
    (English: 'Thread Error: %s (%d)'; Localized: 'スレッド エラー: %s (%d)'),
    (English: 'Cannot terminate an externally created thread'; Localized: '外部で作成されたスレッドは強制終了できません'),
    (English: 'Cannot wait for an externally created thread'; Localized: '外部で作成されたスレッドは待機できません'),
    (English: 'Cannot call Start on a running or suspended thread'; Localized: '実行中または中断中のスレッドで Start を呼び出すことはできません'),
    (English: 'Parameter %s cannot be nil'; Localized: 'パラメーター %s を nil にすることはできません'),
    (English: 'Parameter %s cannot be a negative value'; Localized: 'パラメーター %s を負の値にすることはできません'),
    (English: 'Invalid characters in path'; Localized: 'パスに無効な文字が含まれています'),
    (English: 'Invalid characters in search pattern'; Localized: '検索パターンに無効な文字が含まれています'),
    (English: 'Path is empty'; Localized: 'パスが空です'),
    (English: 'Search pattern is empty'; Localized: '検索パターンが空です'),
    (English: 'The specified path is too long'; Localized: '指定されたパスが長すぎます'),
    (English: 'The specified path was not found'; Localized: '指定されたパスが見つかりませんでした'),
    (English: 'The path format is not supported'; Localized: 'パスの形式はサポートされていません'),
    (English: 'No help viewer that supports filters'; Localized: 'フィルターをサポートするヘルプ ビューアーがありません'),
    (English: 'String index out of range (%d).  Must be >= %d and <= %d'; Localized: '文字列インデックスが範囲外です (%d)。  %d 以上 %d 以下である必要があります'),
    (English: 'Invalid UTF32 character value.  Must be >= 0 and <= $10FFFF, excluding surrogate pair ranges'; Localized: '無効な UTF32 文字値です。  0 以上 $10FFFF 以下である必要があります (サロゲート ペアの範囲を除く)'),
    (English: 'High surrogate char without a following low surrogate char at index: %d. Check that the string is encoded properly'; Localized: 'インデックス %d に、後続の下位サロゲート文字のない上位サロゲート文字があります。文字列が正しくエンコードされているか確認してください'),
    (English: 'Low surrogate char without a preceding high surrogate char at index: %d. Check that the string is encoded properly'; Localized: 'インデックス %d に、先行する上位サロゲート文字のない下位サロゲート文字があります。文字列が正しくエンコードされているか確認してください'),
    (English: 'Source and Destination arrays must not be the same'; Localized: 'ソース配列とコピー先配列を同じにすることはできません'),
    (English: 'SpinCount out of range. Must be between 0 and %d'; Localized: 'SpinCount が範囲外です。0 から %d の間である必要があります'),
    (English: 'No context-sensitive help installed'; Localized: 'コンテキスト依存のヘルプがインストールされていません'),
    (English: 'No help found for context %d'; Localized: 'コンテキスト %d のヘルプが見つかりません'),
    (English: 'Unable to open Index'; Localized: 'インデックスを開けません'),
    (English: 'Unable to open Search'; Localized: '検索を開けません'),
    (English: 'Unable to find a Table of Contents'; Localized: '目次が見つかりません'),
    (English: 'No topic-based help system installed'; Localized: 'トピック ベースのヘルプ システムがインストールされていません'),
    (English: 'No help found for %s'; Localized: '%s のヘルプが見つかりません'),
    (English: 'Argument out of range'; Localized: '引数が範囲外です'),
    (English: 'Argument must not be nil'; Localized: '引数を nil にすることはできません'),
    (English: 'Item not found'; Localized: '項目が見つかりません'),
    (English: 'Duplicates not allowed'; Localized: '重複は許可されていません'),
    (English: 'Insufficient RTTI available to support this operation'; Localized: 'この操作をサポートするために利用できる RTTI が不足しています'),
    (English: 'Parameter count mismatch'; Localized: 'パラメーター数が一致しません'),
    (English: 'Parameter count exceeded'; Localized: 'パラメーター数を超えました'),
    (English: 'Type ''%s'' is not declared in the interface section of a unit'; Localized: '型 ''%s'' はユニットの interface セクションで宣言されていません'),
    (English: 'VAR and OUT arguments must match parameter type exactly'; Localized: 'VAR および OUT 引数は、パラメーターの型と完全に一致する必要があります'),
    (English: 'Property ''%s'' is read-only'; Localized: 'プロパティ ''%s'' は読み取り専用です'),
    (English: 'Property ''%s'' is write-only'; Localized: 'プロパティ ''%s'' は書き込み専用です'),
    (English: 'RTTI objects cannot be manually destroyed by application code'; Localized: 'RTTI オブジェクトをアプリケーション コードで手動で破棄することはできません'),
    (English: '%s (Version %d.%d, Build %d, %5:s)'; Localized: '%s (バージョン %d.%d, ビルド %d, %5:s)'),
    (English: '%s Service Pack %4:d (Version %1:d.%2:d, Build %3:d, %5:s)'; Localized: '%s Service Pack %4:d (バージョン %1:d.%2:d, ビルド %3:d, %5:s)'),
    (English: '32-bit Edition'; Localized: '32 ビット エディション'),
    (English: '64-bit Edition'; Localized: '64 ビット エディション'),
    (English: 'Windows'; Localized: 'Windows'),
    (English: 'Windows Vista'; Localized: 'Windows Vista'),
    (English: 'Windows Server 2008'; Localized: 'Windows Server 2008'),
    (English: 'Windows 7'; Localized: 'Windows 7'),
    (English: 'Windows Server 2008 R2'; Localized: 'Windows Server 2008 R2'),
    (English: 'Windows 2000'; Localized: 'Windows 2000'),
    (English: 'Windows XP'; Localized: 'Windows XP'),
    (English: 'Windows Server 2003'; Localized: 'Windows Server 2003'),
    (English: 'Windows Server 2003 R2'; Localized: 'Windows Server 2003 R2'),
    (English: 'Windows Server 2012'; Localized: 'Windows Server 2012'),
    (English: 'Windows Server 2012 R2'; Localized: 'Windows Server 2012 R2'),
    (English: 'Windows Server 2016'; Localized: 'Windows Server 2016'),
    (English: 'Windows Server 2019'; Localized: 'Windows Server 2019'),
    (English: 'Windows Server 2022'; Localized: 'Windows Server 2022'),
    (English: 'Windows 8'; Localized: 'Windows 8'),
    (English: 'Windows 8.1'; Localized: 'Windows 8.1'),
    (English: 'Windows 10'; Localized: 'Windows 10'),
    (English: 'Windows 11'; Localized: 'Windows 11'),
    (English: 'Cannot create instance of class %s'; Localized: 'クラス %s のインスタンスを作成できません'),
    (English: 'Observer is not supported'; Localized: 'オブザーバーはサポートされていません'),
    (English: 'Cannot have multiple single cast observers added to the observers collection'; Localized: 'オブザーバー コレクションに複数のシングルキャスト オブザーバーを追加することはできません'),
    (English: 'The object does not implement the observer interface'; Localized: 'オブジェクトはオブザーバー インターフェイスを実装していません'),
    (English: 'No single cast observer with ID %d was added to the observer collection'; Localized: 'ID %d のシングルキャスト オブザーバーはオブザーバー コレクションに追加されていません'),
    (English: 'No multi cast observer with ID %d was added to the observer collection'; Localized: 'ID %d のマルチキャスト オブザーバーはオブザーバー コレクションに追加されていません'),
    (English: 'Observer is not available'; Localized: 'オブザーバーは利用できません'),
    (English: 'SHA2: Cannot update a finalized hash'; Localized: 'SHA2: 確定したハッシュは更新できません'),
    (English: 'Must wait on at least one event'; Localized: '少なくとも 1 つのイベントを待機する必要があります'),
    (English: 'Cannot call BeginInvoke on a TComponent in the process of destruction'; Localized: '破棄処理中の TComponent で BeginInvoke を呼び出すことはできません'),
    (English: 'OLE error %.8x'; Localized: 'OLE エラー %.8x'),
    (English: 'Method ''%s'' not supported by automation object'; Localized: 'メソッド ''%s'' はオートメーション オブジェクトでサポートされていません'),
    (English: 'Variant does not reference an automation object'; Localized: 'Variant はオートメーション オブジェクトを参照していません'),
    (English: 'Dispatch methods do not support more than 64 parameters'; Localized: 'Dispatch メソッドは 64 個を超えるパラメーターをサポートしません'),
    (English: 'A regular expression specified in RegEx is required'; Localized: 'RegEx で指定する正規表現が必要です'),
    (English: 'Error in regular expression at offset %d: %s'; Localized: 'オフセット %d の正規表現にエラーがあります: %s'),
    (English: 'Successful match required'; Localized: '成功した一致が必要です'),
    (English: 'Index out of bounds (%d)'; Localized: 'インデックスが範囲外です (%d)'),
    (English: 'Bitmap image is not valid'; Localized: 'ビットマップ画像が無効です'),
    (English: 'Icon image is not valid'; Localized: 'アイコン画像が無効です'),
    (English: 'Metafile is not valid'; Localized: 'メタファイルが無効です'),
    (English: 'Invalid pixel format'; Localized: '無効なピクセル形式'),
    (English: 'Invalid image'; Localized: '無効な画像'),
    (English: 'Scan line index out of range'; Localized: '走査線のインデックスが範囲外です'),
    (English: 'Cannot change the size of an icon'; Localized: 'アイコンのサイズは変更できません'),
    (English: 'Cannot change the size of a WIC Image'; Localized: 'WIC 画像のサイズは変更できません'),
    (English: 'Unsupported clipboard format'; Localized: 'サポートされていないクリップボード形式'),
    (English: 'Unsupported stream format'; Localized: 'サポートされていないストリーム形式'),
    (English: 'Out of system resources'; Localized: 'システム リソースが不足しています'),
    (English: 'Canvas does not allow drawing'; Localized: 'キャンバスでは描画できません'),
    (English: 'Text format flag ''%s'' not supported'; Localized: 'テキスト形式フラグ ''%s'' はサポートされていません'),
    (English: 'Invalid image frame index %d: there are %d frames (0-%d)'; Localized: '無効な画像フレーム インデックス %d: フレームは %d 個あります (0-%d)'),
    (English: 'Invalid image size'; Localized: '無効な画像サイズ'),
    (English: 'Invalid ImageList'; Localized: '無効な ImageList'),
    (English: 'Invalid ImageList Index'; Localized: '無効な ImageList インデックス'),
    (English: 'Failed to read ImageList data from stream'; Localized: 'ストリームからの ImageList データの読み取りに失敗しました'),
    (English: 'Failed to write ImageList data to stream'; Localized: 'ストリームへの ImageList データの書き込みに失敗しました'),
    (English: 'Error creating window device context'; Localized: 'ウィンドウ デバイス コンテキストの作成中にエラーが発生しました'),
    (English: 'Error creating window class'; Localized: 'ウィンドウ クラスの作成中にエラーが発生しました'),
    (English: 'Cannot focus a disabled or invisible window'; Localized: '無効または非表示のウィンドウにフォーカスを設定することはできません'),
    (English: 'Control ''%s'' has no parent window'; Localized: 'コントロール ''%s'' には親ウィンドウがありません'),
    (English: '. Path:'#13#10'%s'; Localized: '. パス:'#13#10'%s'),
    (English: 'Parent given is not a parent of ''%s'''; Localized: '指定された親は ''%s'' の親ではありません'),
    (English: 'Cannot hide an MDI Child Form'; Localized: 'MDI 子フォームを非表示にすることはできません'),
    (English: 'Cannot change Visible in OnShow or OnHide'; Localized: 'OnShow または OnHide で Visible を変更することはできません'),
    (English: 'Cannot make a visible window modal'; Localized: '表示されているウィンドウをモーダルにすることはできません'),
    (English: 'Scrollbar property out of range'; Localized: 'スクロール バーのプロパティが範囲外です'),
    (English: '%s property out of range'; Localized: '%s プロパティが範囲外です'),
    (English: 'Check state can only be set when CheckBoxes is True'; Localized: 'チェック状態は CheckBoxes が True の場合にのみ設定できます'),
    (English: 'Check state incompatible with treeview''s CheckStyles'; Localized: 'チェック状態がツリービューの CheckStyles と互換性がありません'),
    (English: 'Menu index out of range'; Localized: 'メニューのインデックスが範囲外です'),
    (English: 'Menu inserted twice'; Localized: 'メニューが 2 回挿入されました'),
    (English: 'Sub-menu is not in menu'; Localized: 'サブメニューがメニューに含まれていません'),
    (English: 'Not enough timers available'; Localized: '利用できるタイマーが足りません'),
    (English: 'Printer index out of range'; Localized: 'プリンターのインデックスが範囲外です'),
    (English: 'Printer selected is not valid'; Localized: '選択されたプリンターは無効です'),
    (English: '%s on %s'; Localized: '%s (%s)'),
    (English: 'GroupIndex cannot be less than a previous menu item''s GroupIndex'; Localized: 'GroupIndex を前のメニュー項目の GroupIndex より小さくすることはできません'),
    (English: 'Cannot create form. No MDI forms are currently active'; Localized: 'フォームを作成できません。現在アクティブな MDI フォームがありません'),
    (English: 'Can only modify an image if it contains a bitmap'; Localized: '画像を変更できるのは、ビットマップが含まれている場合のみです'),
    (English: 'A control cannot have itself as its parent'; Localized: 'コントロールは自身を親にすることはできません'),
    (English: 'Control ''%s'' is used on a not main thread'; Localized: 'コントロール ''%s'' がメイン スレッド以外で使用されています'),
    (English: '&Yes'; Localized: 'はい(&Y)'),
    (English: '&No'; Localized: 'いいえ(&N)'),
    (English: '&Close'; Localized: '閉じる(&C)'),
    (English: '&Ignore'; Localized: '無視(&I)'),
    (English: '&Retry'; Localized: '再試行(&R)'),
    (English: '&All'; Localized: 'すべて(&A)'),
    (English: 'Cannot drag a form'; Localized: 'フォームをドラッグすることはできません'),
    (English: 'Metafiles'; Localized: 'メタファイル'),
    (English: 'Enhanced Metafiles'; Localized: '拡張メタファイル'),
    (English: 'Icons'; Localized: 'アイコン'),
    (English: 'Bitmaps'; Localized: 'ビットマップ'),
    (English: 'TIFF Images'; Localized: 'TIFF 画像'),
    (English: 'Warning'; Localized: '警告'),
    (English: 'Error'; Localized: 'エラー'),
    (English: 'Information'; Localized: '情報'),
    (English: 'Confirm'; Localized: '確認'),
    (English: '&Abort'; Localized: '中止(&A)'),
    (English: 'N&o to All'; Localized: 'すべていいえ(&O)'),
    (English: 'Yes to &All'; Localized: 'すべてはい(&A)'),
    (English: 'BkSp'; Localized: 'BkSp'),
    (English: 'Tab'; Localized: 'Tab'),
    (English: 'Esc'; Localized: 'Esc'),
    (English: 'Enter'; Localized: 'Enter'),
    (English: 'Space'; Localized: 'Space'),
    (English: 'PgUp'; Localized: 'PgUp'),
    (English: 'PgDn'; Localized: 'PgDn'),
    (English: 'End'; Localized: 'End'),
    (English: 'Home'; Localized: 'Home'),
    (English: 'Left'; Localized: 'Left'),
    (English: 'Up'; Localized: 'Up'),
    (English: 'Right'; Localized: 'Right'),
    (English: 'Down'; Localized: 'Down'),
    (English: 'Ins'; Localized: 'Ins'),
    (English: 'Del'; Localized: 'Del'),
    (English: 'Value must be between %d and %d'; Localized: '値は %d から %d の間でなければなりません'),
    (English: 'Unable to insert a line'; Localized: '行を挿入できません'),
    (English: 'Invalid clipboard format'; Localized: '無効なクリップボード形式'),
    (English: 'Clipboard does not support Icons'; Localized: 'クリップボードはアイコンをサポートしていません'),
    (English: 'Cannot open clipboard: %s'; Localized: 'クリップボードを開けません: %s'),
    (English: 'Text exceeds memo capacity'; Localized: 'テキストがメモの容量を超えています'),
    (English: 'Operation not supported on selected printer'; Localized: '選択されたプリンターではサポートされていない操作です'),
    (English: 'There is no default printer currently selected'; Localized: '現在、既定のプリンターが選択されていません'),
    (English: 'Menu ''%s'' is already being used by another form'; Localized: 'メニュー ''%s'' は既に別のフォームで使用されています'),
    (English: 'Docked control must have a name'; Localized: 'ドッキングされたコントロールには名前が必要です'),
    (English: 'Error removing control from dock tree'; Localized: 'ドック ツリーからのコントロールの削除中にエラーが発生しました'),
    (English: ' - Dock zone not found'; Localized: ' - ドック ゾーンが見つかりません'),
    (English: ' - Dock zone has no control'; Localized: ' - ドック ゾーンにコントロールがありません'),
    (English: 'Error loading dock zone from the stream. Expecting version %d, but found %d.'; Localized: 'ストリームからのドック ゾーンの読み込み中にエラーが発生しました。バージョン %d が必要ですが、%d が見つかりました。'),
    (English: 'Multiselect mode must be on for this feature'; Localized: 'この機能では複数選択モードがオンになっている必要があります'),
    (English: 'Length of value array must be >= length of prompt array'; Localized: '値の配列の長さは、プロンプトの配列の長さ以上である必要があります'),
    (English: 'Prompt array must not be empty'; Localized: 'プロンプトの配列を空にすることはできません'),
    (English: '&Username'; Localized: 'ユーザー名(&U)'),
    (English: '&Password'; Localized: 'パスワード(&P)'),
    (English: '&Domain'; Localized: 'ドメイン(&D)'),
    (English: 'Login'; Localized: 'ログイン'),
    (English: 'Separator'; Localized: '区切り'),
    (English: 'Error setting %s.Count'; Localized: '%s.Count の設定中にエラーが発生しました'),
    (English: 'Listbox (%s) style must be virtual in order to set Count'; Localized: 'Count を設定するには、リストボックス (%s) のスタイルが仮想である必要があります'),
    (English: 'No OnGetItem event handler assigned'; Localized: 'OnGetItem イベント ハンドラーが割り当てられていません'),
    (English: 'Cannot remove shell notification icon'; Localized: 'シェル通知アイコンを削除できません'),
    (English: '%s requires Windows Vista or later'; Localized: '%s には Windows Vista 以降が必要です'),
    (English: 'Button%d'; Localized: 'ボタン%d'),
    (English: 'RadioButton%d'; Localized: 'ラジオボタン%d'),
    (English: 'Caption cannot be empty'; Localized: 'キャプションを空にすることはできません'),
    (English: 'Invalid canvas operation'; Localized: '無効なキャンバス操作'),
    (English: '%s has no owner'; Localized: '%s には所有者がいません'),
    (English: 'Source and destination require the same owner'; Localized: 'コピー元とコピー先には同じ所有者が必要です'),
    (English: '%s cannot be owned by a different canvas'; Localized: '%s を別のキャンバスが所有することはできません'),
    (English: 'Not a solid color brush'; Localized: '単色ブラシではありません'),
    (English: 'Invalid brush style'; Localized: '無効なブラシ スタイル'),
    (English: 'Unable to load style ''%s'''; Localized: 'スタイル ''%s'' を読み込めません'),
    (English: 'Unable to load styles: %s'; Localized: 'スタイルを読み込めません: %s'),
    (English: 'Style ''%s'' already registered'; Localized: 'スタイル ''%s'' は既に登録されています'),
    (English: 'Style class ''%s'' already registered'; Localized: 'スタイル クラス ''%s'' は既に登録されています'),
    (English: 'Style ''%s'' not found'; Localized: 'スタイル ''%s'' が見つかりません'),
    (English: 'Style class ''%s'' not found'; Localized: 'スタイル クラス ''%s'' が見つかりません'),
    (English: 'Invalid style format'; Localized: '無効なスタイル形式'),
    (English: 'VCL Style File'; Localized: 'VCL スタイル ファイル'),
    (English: 'Class ''%s'' is already registered for ''%s'''; Localized: 'クラス ''%s'' は ''%s'' に対して既に登録されています'),
    (English: 'Class ''%s'' is not registered for ''%s'''; Localized: 'クラス ''%s'' は ''%s'' に対して登録されていません'),
    (English: '%s parameter cannot be nil'; Localized: '%s パラメーターを nil にすることはできません'),
    (English: 'A StyleHook class has not been registered for %s'; Localized: '%s に対して StyleHook クラスが登録されていません'),
    (English: 'Feature not supported by this style'; Localized: 'この機能はこのスタイルではサポートされていません'),
    (English: 'Cannot call BeginInvoke on a control with no parent or window handle'; Localized: '親またはウィンドウ ハンドルのないコントロールで BeginInvoke を呼び出すことはできません'),
    (English: 'CardPanel card index is out of range'; Localized: 'CardPanel のカード インデックスが範囲外です'),
    (English: 'CardPanel.ActiveCard cannot be nil'; Localized: 'CardPanel.ActiveCard を nil にすることはできません'),
    (English: 'Invalid index'; Localized: '無効なインデックス'),
    (English: 'Unable to insert an item'; Localized: '項目を挿入できません'),
    (English: 'Invalid owner'; Localized: '無効な所有者'),
    (English: '%s is already associated with %s'; Localized: '%s は既に %s に関連付けられています'),
    (English: 'This control requires version 4.70 or greater of COMCTL32.DLL'; Localized: 'このコントロールには COMCTL32.DLL のバージョン 4.70 以降が必要です'),
    (English: 'ListView item can be added only when OwnerData is False.  Use OnData instead.'; Localized: 'ListView 項目は OwnerData が False の場合にのみ追加できます。  代わりに OnData を使用してください。'),
    (English: 'This "Portable Network Graphics" image is not valid because it contains invalid pieces of data (crc error)'; Localized: 'この "Portable Network Graphics" 画像は、無効なデータ部分が含まれているため無効です (CRC エラー)'),
    (English: 'The "Portable Network Graphics" image could not be loaded because one of its main piece of data (ihdr) might be corrupted'; Localized: '"Portable Network Graphics" 画像を読み込めませんでした。主要なデータ部分の 1 つ (ihdr) が破損している可能性があります'),
    (English: 'This "Portable Network Graphics" image is invalid because it has missing image parts.'; Localized: 'この "Portable Network Graphics" 画像は、画像の一部が欠落しているため無効です。'),
    (English: 'Could not decompress the image because it contains invalid compressed data.'#13#10' Description: '; Localized: '無効な圧縮データが含まれているため、画像を展開できませんでした。'#13#10' 説明: '),
    (English: 'The "Portable Network Graphics" image contains an invalid palette.'; Localized: '"Portable Network Graphics" 画像に無効なパレットが含まれています。'),
    (English: 'The file being read is not a valid "Portable Network Graphics" image because it contains an invalid header. This file may be corrupted, try obtaining it again'; Localized: '読み取り中のファイルは、無効なヘッダーが含まれているため、有効な "Portable Network Graphics" 画像ではありません。このファイルは破損している可能性があります。もう一度取得してみてください'),
    (English: 'This "Portable Network Graphics" image is not supported or it might be invalid.'#13#10'(IHDR chunk is not the first)'; Localized: 'この "Portable Network Graphics" 画像はサポートされていないか、無効である可能性があります。'#13#10'(IHDR チャンクが最初ではありません)'),
    (English: 'This "Portable Network Graphics" image is not supported because either its width or height exceeds the maximum size of 65535 pixels.'; Localized: 'この "Portable Network Graphics" 画像は、幅または高さが最大サイズの 65535 ピクセルを超えているため、サポートされていません。'),
    (English: 'There is no such palette entry.'; Localized: 'そのようなパレット エントリはありません。'),
    (English: 'This "Portable Network Graphics" image contains an unknown critical part which could not be decoded.'; Localized: 'この "Portable Network Graphics" 画像には、デコードできない不明な必須部分が含まれています。'),
    (English: 'This "Portable Network Graphics" image is encoded with an unknown compression scheme which could not be decoded.'; Localized: 'この "Portable Network Graphics" 画像は、デコードできない不明な圧縮方式でエンコードされています。'),
    (English: 'This "Portable Network Graphics" image uses an unknown interlace scheme which could not be decoded.'; Localized: 'この "Portable Network Graphics" 画像は、デコードできない不明なインターレース方式を使用しています。'),
    (English: 'This "Portable Network Graphics" image uses an unknown color type which could not be decoded.'; Localized: 'この "Portable Network Graphics" 画像は、デコードできない不明なカラー タイプを使用しています。'),
    (English: 'The chunks must be compatible to be assigned.'; Localized: 'チャンクを割り当てるには、互換性がある必要があります。'),
    (English: 'This "Portable Network Graphics" image is invalid because the decoder found an unexpected end of the file.'; Localized: 'この "Portable Network Graphics" 画像は、デコーダーが予期しないファイルの終わりを検出したため無効です。'),
    (English: 'This "Portable Network Graphics" image contains no data.'; Localized: 'この "Portable Network Graphics" 画像にはデータが含まれていません。'),
    (English: 'The program tried to add a existent critical chunk to the current image which is not allowed.'; Localized: 'プログラムが既存の必須チャンクを現在の画像に追加しようとしましたが、これは許可されていません。'),
    (English: 'It''s not allowed to add a new chunk because the current image is invalid.'; Localized: '現在の画像が無効であるため、新しいチャンクを追加することは許可されていません。'),
    (English: 'Some operation could not be performed because the system is out of resources. Close some windows and try again.'; Localized: 'システムのリソースが不足しているため、一部の操作を実行できませんでした。いくつかのウィンドウを閉じてからもう一度お試しください。'),
    (English: 'Setting bit transparency color is not allowed for png images containing alpha value for each pixel (COLOR_RGBALPHA and COLOR_GRAYSCALEALPHA)'; Localized: 'ピクセルごとにアルファ値を含む PNG 画像 (COLOR_RGBALPHA および COLOR_GRAYSCALEALPHA) では、ビット透過色の設定は許可されていません'),
    (English: 'This operation is not valid because the current image contains no valid header.'; Localized: '現在の画像に有効なヘッダーが含まれていないため、この操作は無効です。'),
    (English: 'The new size provided for image resizing is invalid.'; Localized: '画像のサイズ変更のために指定された新しいサイズが無効です。'),
    (English: 'The "Portable Network Graphics" image could not be loaded because it uses an invalid image bit depth.'; Localized: '"Portable Network Graphics" 画像は、無効な画像のビット深度を使用しているため読み込めませんでした。'));

implementation

end.
