unit IDE.LocalizeFunc.Korean;

{
  Inno Setup
  Copyright (C) 1997-2026 Jordan Russell
  Portions by Martijn Laan
  For conditions of distribution and use, see LICENSE.TXT.

  Compiler IDE Korean translations
}

interface

uses
  IDE.LocalizeFunc;

const
  KoreanIDETranslations: array [0..1015] of TTranslationPair = (
    (English: 'Command-line usage:'; Localized: '명령줄 사용법:'),
    (English: 'Examples:'; Localized: '사용 예:'),
    (English: 'script file'; Localized: '스크립트 파일'),
    (English: 'wizard name'; Localized: '마법사 이름'),
    (English: 'My script'; Localized: '내 스크립트'),
    (English: 'My Script Wizard'; Localized: '내 스크립트 마법사'),
    (English: 'Could not load %1: %2'; Localized: '%1을(를) 로드할 수 없습니다: %2'),
    (English: 'Inno Setup Compiler'; Localized: 'Inno Setup Compiler'),
    (English: 'Example scripts...'; Localized: '예제 스크립트...'),
    (English: 'More files...'; Localized: '기타 파일...'),
    (English: 'Untitled'; Localized: '제목 없음'),
    (English: 'Preprocessor Output'; Localized: '전처리기 출력'),
    (English: 'Run Parameters'; Localized: '실행 매개 변수'),
    (English: 'Command-line parameters for %1 and %2:'; Localized: '%1 및 %2의 명령줄 매개 변수:'),
    (English: 'Inno Setup Script files'; Localized: 'Inno Setup 스크립트 파일'),
    (English: 'All files'; Localized: '모든 파일'),
    (English: 'Application files'; Localized: '응용 프로그램 파일'),
    (English: 'Documentation files'; Localized: '설명서 파일'),
    (English: 'Rich Text Format files'; Localized: '서식 있는 텍스트 파일'),
    (English: 'Registry files'; Localized: '레지스트리 파일'),
    (English: 'Icon files'; Localized: '아이콘 파일'),
    (English: 'Image files'; Localized: '이미지 파일'),
    (English: 'VCL Styles files'; Localized: 'VCL Styles 파일'),
    (English: 'Inno Setup Messages files'; Localized: 'Inno Setup 메시지 파일'),
    (English: 'Public key files'; Localized: '공개 키 파일'),
    (English: 'Text files'; Localized: '텍스트 파일'),
    (English: 'Inno Setup Script Wizard'; Localized: 'Inno Setup 스크립트 마법사'),
    (English: 'Welcome'; Localized: '환영합니다'),
    (English: 'Application Information'; Localized: '응용 프로그램 정보'),
    (English: 'Please specify some basic information about your application.'; Localized: '응용 프로그램에 대한 기본 정보를 지정하세요.'),
    (English: 'Application Folder'; Localized: '응용 프로그램 폴더'),
    (English: 'Please specify folder information about your application.'; Localized: '응용 프로그램의 폴더 정보를 지정하세요.'),
    (English: 'Application Files'; Localized: '응용 프로그램 파일'),
    (English: 'Please specify the files that are part of your application.'; Localized: '응용 프로그램에 포함할 파일을 지정하세요.'),
    (English: 'Please specify the source folder.'; Localized: '원본 폴더를 지정하세요.'),
    (English: 'Should files in subfolders of "%1" also be included?'; Localized: '"%1"의 하위 폴더에 있는 파일도 포함하시겠습니까?'),
    (English: 'URL:'; Localized: 'URL:'),
    (English: 'Is the file to download an archive which should be extracted?'; Localized: '다운로드할 파일이 추출해야 하는 압축 파일입니까?'),
    (English: 'Name of the file:'; Localized: '파일 이름:'),
    (English: 'Name of the file (extension should match archive format):'; Localized: '파일 이름 (확장자는 압축 파일 형식과 일치해야 함):'),
    (English: 'Approximate size of the file in megabytes:'; Localized: '파일의 대략적인 크기 (MB 단위):'),
    (English: 'Application File Association'; Localized: '응용 프로그램 파일 연결'),
    (English: 'Please specify which file association should be created for your application.'; Localized: '응용 프로그램에 대해 만들 파일 연결을 지정하세요.'),
    (English: '%1 File'; Localized: '%1 파일'),
    (English: 'Application Shortcuts'; Localized: '응용 프로그램 바로 가기'),
    (English: 'Please specify which shortcuts should be created for your application.'; Localized: '응용 프로그램에 대해 만들 바로 가기를 지정하세요.'),
    (English: 'Application Documentation'; Localized: '응용 프로그램 설명서'),
    (English: 'Please specify which documentation files should be shown by Setup during installation.'; Localized: '설치 중에 설치 프로그램이 표시할 설명서 파일을 지정하세요.'),
    (English: 'Setup Install Mode'; Localized: '설치 모드'),
    (English: 'Please specify in which install mode Setup should run.'; Localized: '설치 프로그램을 실행할 설치 모드를 지정하세요.'),
    (English: 'Application Registry Keys And Values'; Localized: '응용 프로그램 레지스트리 키 및 값'),
    (English: 'Please specify the registry keys and values that are part of your application.'; Localized: '응용 프로그램에 포함할 레지스트리 키 및 값을 지정하세요.'),
    (English: 'Setup Languages'; Localized: '설치 언어'),
    (English: 'Please specify which Setup languages should be included.'; Localized: '포함할 설치 언어를 지정하세요.'),
    (English: 'Compiler Settings'; Localized: '컴파일러 설정'),
    (English: 'Please specify some basic compiler settings.'; Localized: '기본 컴파일러 설정을 지정하세요.'),
    (English: 'Please specify the folder.'; Localized: '폴더를 지정하세요.'),
    (English: 'Wizard Style'; Localized: '마법사 스타일'),
    (English: 'Please specify which wizard style should be used.'; Localized: '사용할 마법사 스타일을 지정하세요.'),
    (English: 'Inno Setup Preprocessor'; Localized: 'Inno Setup 전처리기'),
    (English: 'Please specify whether Inno Setup Preprocessor should be used.'; Localized: 'Inno Setup 전처리기를 사용할지 여부를 지정하세요.'),
    (English: 'The %1 can use %2 compiler directives to simplify your script. Although this is not necessary, it will make it easier to manually change the script later.%n%nDo you want the %1 to use %2 compiler directives?'; Localized: '%1은(는) %2 컴파일러 지시문을 사용하여 스크립트를 간단하게 만들 수 있습니다. 필수는 아니지만 나중에 스크립트를 수동으로 변경하기가 더 쉬워집니다.%n%n%1이(가) %2 컴파일러 지시문을 사용하도록 하시겠습니까?'),
    (English: '&Yes, use %1 compiler directives'; Localized: '예, %1 컴파일러 지시문 사용(&Y)'),
    (English: 'Finished'; Localized: '완료'),
    (English: '&Next'; Localized: '다음(&N)'),
    (English: '&Finish'; Localized: '마침(&F)'),
    (English: 'The %1 is not complete. If you quit now, the new script file will not be generated.%n%nExit anyway?'; Localized: '%1이(가) 완료되지 않았습니다. 지금 종료하면 새 스크립트 파일이 생성되지 않습니다.%n%n그래도 종료하시겠습니까?'),
    (English: 'Please specify the application name.'; Localized: '응용 프로그램 이름을 지정하세요.'),
    (English: 'Please specify the application version.'; Localized: '응용 프로그램 버전을 지정하세요.'),
    (English: 'Please specify the application destination base folder.'; Localized: '응용 프로그램 대상 기본 폴더를 지정하세요.'),
    (English: 'Please specify the application folder name.'; Localized: '응용 프로그램 폴더 이름을 지정하세요.'),
    (English: 'Please specify the application main executable file.'; Localized: '응용 프로그램 주 실행 파일을 지정하세요.'),
    (English: 'The specified application main executable file does not exist.'; Localized: '지정한 응용 프로그램 주 실행 파일이 없습니다.'),
    (English: 'Please specify the application Start Menu group name.'; Localized: '응용 프로그램 시작 메뉴 그룹 이름을 지정하세요.'),
    (English: 'Please specify the destination base folder.'; Localized: '대상 기본 폴더를 지정하세요.'),
    (English: 'Please specify a destination base folder other than the application folder.'; Localized: '응용 프로그램 폴더가 아닌 다른 대상 기본 폴더를 지정하세요.'),
    (English: 'Please specify the destination name.'; Localized: '대상 이름을 지정하세요.'),
    (English: 'Please select at least one language.'; Localized: '언어를 하나 이상 선택하세요.'),
    (English: '&Source URL:'; Localized: '원본 URL(&S):'),
    (English: 'Script generated by the %1.'; Localized: '%1에서 생성한 스크립트입니다.'),
    (English: 'SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!'; Localized: 'Inno Setup 스크립트 파일 만들기에 대한 자세한 내용은 설명서를 참조하세요!'),
    (English: 'NOTE: The value of %1 uniquely identifies this application. Do not use the same %1 value in installers for other applications.'; Localized: '참고: %1 값은 이 응용 프로그램을 고유하게 식별합니다. 다른 응용 프로그램의 설치 프로그램에서 같은 %1 값을 사용하지 마세요.'),
    (English: '(To generate a new GUID, click Tools | Generate GUID inside the IDE.)'; Localized: '(새 GUID를 생성하려면 IDE에서 도구 | GUID 생성을 클릭하세요.)'),
    (English: '"%1" specifies that Setup cannot run on anything but x64 and Windows 11 on Arm.'; Localized: '"%1"은(는) 설치 프로그램이 x64 및 Windows 11 on Arm에서만 실행되도록 지정합니다.'),
    (English: '"%1" requests that the install be done in "64-bit mode" on x64 or Windows 11 on Arm.'; Localized: '"%1"은(는) x64 또는 Windows 11 on Arm에서 "64비트 모드"로 설치하도록 요청합니다.'),
    (English: 'This means it should use the native 64-bit Program Files directory and the 64-bit view of the registry.'; Localized: '즉, 네이티브 64비트 Program Files 폴더와 레지스트리의 64비트 보기를 사용해야 합니다.'),
    (English: 'Uncomment the following line to use a 64-bit installer.'; Localized: '64비트 설치 프로그램을 사용하려면 다음 줄의 주석 처리를 제거하세요.'),
    (English: 'Use "%1" if all your archives are .%2 files.'; Localized: '모든 압축 파일이 .%2 파일인 경우 "%1"을(를) 사용하세요.'),
    (English: 'Use "%1" if all your archives are not password-protected.'; Localized: '모든 압축 파일이 암호로 보호되어 있지 않은 경우 "%1"을(를) 사용하세요.'),
    (English: 'Uncomment the following line to run in non administrative install mode (install for current user only).'; Localized: '비관리자 설치 모드 (현재 사용자용으로만 설치)로 실행하려면 다음 줄의 주석 처리를 제거하세요.'),
    (English: 'Remove the following line to run in administrative install mode (install for all users).'; Localized: '관리자 설치 모드 (모든 사용자용으로 설치)로 실행하려면 다음 줄을 제거하세요.'),
    (English: 'NOTE: Don''t use "%1" on any shared system files.'; Localized: '참고: 공유 시스템 파일에는 "%1"을(를) 사용하지 마세요.'),
    (English: 'NOTE: Use the "%1" flag or the "%2" parameter to verify downloads.'; Localized: '참고: 다운로드를 검증하려면 "%1" 플래그 또는 "%2" 매개 변수를 사용하세요.'),
    (English: 'Registry data from file %1'; Localized: '%1 파일의 레지스트리 데이터'),
    (English: 'COULD NOT IMPORT %1'; Localized: '%1을(를) 가져올 수 없음'),
    (English: 'End of registry data from file %1'; Localized: '%1 파일의 레지스트리 데이터 끝'),
    (English: 'SOME KEYS FILTERED DUE TO %1 SETTINGS!'; Localized: '%1 설정으로 인해 일부 키가 필터링되었습니다!'),
    (English: 'SOME VALUES WITH UNSUPPORTED TYPES SKIPPED!'; Localized: '지원되지 않는 형식의 일부 값을 건너뛰었습니다!'),
    (English: 'Would you like to compile the new script now?'; Localized: '지금 새 스크립트를 컴파일하시겠습니까?'),
    (English: 'My Program'; Localized: '내 프로그램'),
    (English: 'My Company, Inc.'; Localized: '내 회사'),
    (English: 'Application directory'; Localized: '응용 프로그램 폴더'),
    (English: 'Program Files directory'; Localized: 'Program Files 폴더'),
    (English: 'Common Files directory'; Localized: 'Common Files 폴더'),
    (English: 'Windows directory'; Localized: 'Windows 폴더'),
    (English: 'Windows system directory'; Localized: 'Windows 시스템 폴더'),
    (English: 'Setup source directory'; Localized: '설치 프로그램 원본 폴더'),
    (English: 'System drive root directory'; Localized: '시스템 드라이브 루트 폴더'),
    (English: '(Custom)'; Localized: '(사용자 지정)'),
    (English: 'Starting compile.%1[%2]'; Localized: '컴파일을 시작합니다.%1[%2]'),
    (English: 'Finished.%1[%2, %3 elapsed]'; Localized: '완료되었습니다.%1[%2, %3 경과]'),
    (English: 'Compile aborted.'; Localized: '컴파일이 중단되었습니다.'),
    (English: 'Log size limit reached, list reset.'; Localized: '로그 크기 제한에 도달하여 목록을 다시 설정했습니다.'),
    (English: '%1 started'; Localized: '%1이 시작되었습니다'),
    (English: 'Terminating process'; Localized: '프로세스를 종료하는 중'),
    (English: 'Removing left-over temporary directory: %1'; Localized: '남아 있는 임시 폴더를 제거하는 중: %1'),
    (English: 'Failed to remove temporary directory'; Localized: '임시 폴더를 제거하지 못했습니다'),
    (English: '%1 Call Stack'; Localized: '%1 호출 스택'),
    (English: 'Cannot run Setup at this time. Please compile Setup successfully to completion first, with output enabled'; Localized: '지금은 설치 프로그램을 실행할 수 없습니다. 먼저 출력을 사용하도록 설정한 상태에서 설치 프로그램을 끝까지 성공적으로 컴파일하세요'),
    (English: 'Cannot run Uninstall at this time. Please run Setup successfully to completion first'; Localized: '지금은 제거 프로그램을 실행할 수 없습니다. 먼저 설치 프로그램을 끝까지 성공적으로 실행하세요'),
    (English: 'Error executing "%1":%n%n%2: %3'; Localized: '"%1"을(를) 실행하는 동안 오류가 발생했습니다:%n%n%2: %3'),
    (English: 'Are you sure you want to abort the compile?'; Localized: '컴파일을 중단하시겠습니까?'),
    (English: 'File %1:'; Localized: '파일 %1:'),
    (English: 'Line %1:'; Localized: '줄 %1:'),
    (English: 'Compiler Error'; Localized: '컴파일러 오류'),
    (English: 'Illegal null character on line %1'; Localized: '줄 %1에 잘못된 null 문자가 있습니다'),
    (English: 'Cannot find "%1"'; Localized: '"%1"을(를) 찾을 수 없습니다'),
    (English: 'Invalid regular expression "%1"'; Localized: '정규식 "%1"이(가) 잘못되었습니다'),
    (English: '%1 (%2 hits):'; Localized: '%1 (%2개 일치 항목):'),
    (English: 'Find "%1" (%2 hits in %3 files)'; Localized: '"%1" 찾기 (%3개 파일에서 %2개 일치 항목)'),
    (English: '%1 occurrence(s) replaced.'; Localized: '%1개 항목을 바꿨습니다.'),
    (English: 'The .%1 extension was successfully associated for the current user with:%n%2'; Localized: '.%1 확장자를 현재 사용자에 대해 다음 프로그램에 성공적으로 연결했습니다:%n%2'),
    (English: 'The .%1 extension was successfully associated for all users with:%n%2'; Localized: '.%1 확장자를 모든 사용자에 대해 다음 프로그램에 성공적으로 연결했습니다:%n%2'),
    (English: 'Error creating file association:%n%1 - %2'; Localized: '파일 연결을 만드는 동안 오류가 발생했습니다:%n%1 - %2'),
    (English: 'Unable to associate for all users without administrative privileges. Do you want to associate only for yourself instead?'; Localized: '관리자 권한 없이는 모든 사용자에 대해 연결할 수 없습니다. 대신 현재 사용자에 대해서만 연결하시겠습니까?'),
    (English: 'Associate'; Localized: '연결'),
    (English: 'Inno Setup Script'; Localized: 'Inno Setup 스크립트'),
    (English: 'Compi&le'; Localized: '컴파일(&L)'),
    (English: '&Script has %1'; Localized: '스크립트에 %1이(가) 있음(&S)'),
    (English: 'Script has %1 set'; Localized: '스크립트에 %1이(가) 설정되어 있음'),
    (English: 'Invalid file format.'; Localized: '파일 형식이 잘못되었습니다.'),
    (English: 'The specified registry file does not exist.'; Localized: '지정한 레지스트리 파일이 없습니다.'),
    (English: 'Setup'; Localized: '설치 프로그램'),
    (English: 'Your message text.'; Localized: '메시지 텍스트입니다.'),
    (English: 'Enter your text here...'; Localized: '여기에 텍스트를 입력하세요...'),
    (English: 'Return values'; Localized: '반환 값'),
    (English: 'Default'; Localized: '기본값'),
    (English: 'Shield'; Localized: '방패'),
    (English: 'Instruction Text'; Localized: '지침 텍스트'),
    (English: 'Message Text'; Localized: '메시지 텍스트'),
    (English: 'user clicked %1'; Localized: '사용자가 %1을(를) 클릭함'),
    (English: 'OK'; Localized: '확인'),
    (English: 'Yes'; Localized: '예'),
    (English: 'No'; Localized: '아니요'),
    (English: 'Cancel'; Localized: '취소'),
    (English: 'Retry'; Localized: '다시 시도'),
    (English: 'Ignore'; Localized: '무시'),
    (English: 'Abort'; Localized: '중단'),
    (English: 'Display a message box'; Localized: '메시지 상자 표시'),
    (English: 'Name of the Sign Tool:'; Localized: '서명 도구의 이름:'),
    (English: 'Invalid name.'; Localized: '이름이 잘못되었습니다.'),
    (English: 'Duplicate name.'; Localized: '이름이 중복되었습니다.'),
    (English: 'Command of the Sign Tool:'; Localized: '서명 도구의 명령:'),
    (English: 'Invalid command.'; Localized: '명령이 잘못되었습니다.'),
    (English: 'Value of "%1" is invalid'; Localized: '"%1"의 값이 잘못되었습니다'),
    (English: 'The script cannot be edited because it is read-only'; Localized: '스크립트가 읽기 전용이므로 편집할 수 없습니다'),
    (English: 'Parameter "%1" cannot be browsed for when the "%2" flag is used'; Localized: '"%2" 플래그를 사용하는 경우 "%1" 매개 변수는 찾아보기할 수 없습니다'),
    (English: 'Move to a parameter entry or a key/value or [Code] section'; Localized: '매개 변수 항목, 키/값 섹션 또는 [Code] 섹션으로 이동하세요'),
    (English: 'Move to a parameter entry or a non-empty key/value or [Code] section'; Localized: '매개 변수 항목, 비어 있지 않은 키/값 섹션 또는 [Code] 섹션으로 이동하세요'),
    (English: 'Select entries of one section type, and no other content'; Localized: '한 섹션 유형의 항목만 선택하고 다른 내용은 선택하지 마세요'),
    (English: 'Unspecified directives are hidden because this section occurs more than once'; Localized: '이 섹션이 두 번 이상 나타나므로 지정되지 않은 지시문은 숨겨집니다'),
    (English: 'Unspecified directives are hidden because this is not the main script file'; Localized: '주 스크립트 파일이 아니므로 지정되지 않은 지시문은 숨겨집니다'),
    (English: 'Routines'; Localized: '루틴'),
    (English: 'Types'; Localized: '형식'),
    (English: 'Symbols'; Localized: '기호'),
    (English: 'Parameters'; Localized: '매개 변수'),
    (English: 'Locals'; Localized: '지역 변수'),
    (English: 'The generated GUID will be inserted into the editor at the cursor position. Continue?'; Localized: '생성된 GUID가 편집기의 커서 위치에 삽입됩니다. 계속하시겠습니까?'),
    (English: 'The generated Pascal script will be inserted into the editor at the cursor position, but the cursor is not in the %1 section. Continue anyway?'; Localized: '생성된 Pascal 스크립트가 편집기의 커서 위치에 삽입되지만 커서가 %1 섹션에 있지 않습니다. 그래도 계속하시겠습니까?'),
    (English: 'Classic'; Localized: '클래식'),
    (English: 'Visual Studio / Visual Studio Code'; Localized: 'Visual Studio / Visual Studio Code'),
    (English: 'Classic / Visual Studio'; Localized: '클래식 / Visual Studio'),
    (English: 'Visual Studio Code'; Localized: 'Visual Studio Code'),
    (English: 'Light'; Localized: '라이트'),
    (English: 'Dark'; Localized: '다크'),
    (English: 'The new language will take effect the next time you start Inno Setup Compiler.'; Localized: '새 언어는 다음에 Inno Setup Compiler를 시작할 때 적용됩니다.'),
    (English: '&New...'; Localized: '새로 만들기(&N)...'),
    (English: '&New'; Localized: '새로 만들기(&N)'),
    (English: 'Line %1'; Localized: '줄 %1'),
    (English: '%1: %2'; Localized: '%1: %2'),
    (English: 'Back (%1)'; Localized: '뒤로 (%1)'),
    (English: 'Forward (%1)'; Localized: '앞으로 (%1)'),
    (English: 'Back'; Localized: '뒤로'),
    (English: 'Forward'; Localized: '앞으로'),
    (English: 'Open'; Localized: '열기'),
    (English: 'Run'; Localized: '실행'),
    (English: 'Save As'; Localized: '다른 이름으로 저장'),
    (English: 'Font'; Localized: '글꼴'),
    (English: 'Text Color'; Localized: '텍스트 색'),
    (English: 'Background Color'; Localized: '배경색'),
    (English: 'Ctrl+'; Localized: 'Ctrl+'),
    (English: 'Shift+'; Localized: 'Shift+'),
    (English: 'Alt+'; Localized: 'Alt+'),
    (English: 'Num %1'; Localized: 'Num %1'),
    (English: '(32-bit)'; Localized: '(32비트)'),
    (English: '[Compiling]'; Localized: '[컴파일 중]'),
    (English: '[Running]'; Localized: '[실행 중]'),
    (English: '[Paused]'; Localized: '[일시 중지됨]'),
    (English: 'Read only'; Localized: '읽기 전용'),
    (English: 'Modified'; Localized: '수정됨'),
    (English: 'Overwrite'; Localized: '겹쳐쓰기'),
    (English: 'Insert'; Localized: '삽입'),
    (English: 'Tabs closed: %1'; Localized: '닫힌 탭: %1'),
    (English: 'Estimated time remaining: %1'; Localized: '예상 남은 시간: %1'),
    (English: 'Average KB/sec: %1'; Localized: '평균 KB/초: %1'),
    (English: 'There was an error opening the file. Remove it from the list?'; Localized: '파일을 여는 동안 오류가 발생했습니다. 목록에서 제거하시겠습니까?'),
    (English: 'The text in the %1 file has changed.%n%nDo you want to save the changes?'; Localized: '%1 파일의 텍스트가 변경되었습니다.%n%n변경 내용을 저장하시겠습니까?'),
    (English: 'Please stop the compile process before performing this command.'; Localized: '이 명령을 수행하기 전에 컴파일 프로세스를 중지하세요.'),
    (English: 'A compile is already in progress.'; Localized: '컴파일이 이미 진행 중입니다.'),
    (English: 'The text in the %1 file has changed and must be saved before compiling.%n%nSave the changes and continue?'; Localized: '%1 파일의 텍스트가 변경되었으며 컴파일하기 전에 저장해야 합니다.%n%n변경 내용을 저장하고 계속하시겠습니까?'),
    (English: 'Would you like to save the script before compiling?%n%nIf you answer No, the compiled installation will be placed under your My Documents folder by default.'; Localized: '컴파일하기 전에 스크립트를 저장하시겠습니까?%n%n아니요를 선택하면 컴파일된 설치 프로그램이 기본적으로 내 문서 폴더 아래에 저장됩니다.'),
    (English: 'The selected file is an %1 file. Go to its tab instead of opening it as the new main file?'; Localized: '선택한 파일은 %1 파일입니다. 새 주 파일로 여는 대신 해당 탭으로 이동하시겠습니까?'),
    (English: 'The selected file is not available as a tab. Opening as the new main file instead.'; Localized: '선택한 파일은 탭으로 사용할 수 없습니다. 대신 새 주 파일로 엽니다.'),
    (English: 'Error creating file (code %1). Could not save file'; Localized: '파일을 만드는 동안 오류가 발생했습니다 (코드 %1). 파일을 저장할 수 없습니다'),
    (English: 'Error creating backup file. Could not save file'; Localized: '백업 파일을 만드는 동안 오류가 발생했습니다. 파일을 저장할 수 없습니다'),
    (English: 'Error removing existing file (code %1). Could not save file'; Localized: '기존 파일을 제거하는 동안 오류가 발생했습니다 (코드 %1). 파일을 저장할 수 없습니다'),
    (English: 'Error renaming temporary file (code %1). Could not save file'; Localized: '임시 파일의 이름을 바꾸는 동안 오류가 발생했습니다 (코드 %1). 파일을 저장할 수 없습니다'),
    (English: 'Failed to open included file: %1'; Localized: '포함 파일을 열지 못했습니다: %1'),
    (English: 'Cannot start printer document.'; Localized: '프린터 문서를 시작할 수 없습니다.'),
    (English: 'Are you sure you want to clear the list of recently opened files?'; Localized: '최근에 연 파일 목록을 지우시겠습니까?'),
    (English: 'The %1 file has been modified outside of the source editor. You might want to reload it.'; Localized: '%1 파일이 소스 편집기 외부에서 수정되었습니다. 다시 로드하는 것이 좋습니다.'),
    (English: 'The %1 file has been modified outside of the source editor.%n%nDo you want to reload the file?'; Localized: '%1 파일이 소스 편집기 외부에서 수정되었습니다.%n%n파일을 다시 로드하시겠습니까?'),
    (English: 'The %1 file has been modified outside of the source editor. Changes have also been made in the source editor.%n%nDo you want to reload the file and lose the changes made in the source editor?'; Localized: '%1 파일이 소스 편집기 외부에서 수정되었습니다. 소스 편집기에서도 변경한 내용이 있습니다.%n%n파일을 다시 로드하고 소스 편집기에서 변경한 내용을 버리시겠습니까?'),
    (English: 'File not opened.'; Localized: '파일이 열리지 않았습니다.'),
    (English: 'Go to Line'; Localized: '줄로 이동'),
    (English: 'Line number:'; Localized: '줄 번호:'),
    (English: 'Could not load file (code %1)'; Localized: '파일을 로드할 수 없습니다 (코드 %1)'),
    (English: 'Could not save file (code %1)'; Localized: '파일을 저장할 수 없습니다 (코드 %1)'),
    (English: 'Do you want to copy your current license key to the clipboard before opening our order page? You will need it to be able to renew it.'; Localized: '주문 페이지를 열기 전에 현재 라이선스 키를 클립보드에 복사하시겠습니까? 라이선스를 갱신하려면 이 키가 필요합니다.'),
    (English: 'New commercial license key has been registered:%n%n%1%n%nThanks for your support!'; Localized: '새 상용 라이선스 키가 등록되었습니다:%n%n%1%n%n지원해 주셔서 감사합니다!'),
    (English: 'Are you sure you want to remove your commercial license key and revert to non-commercial use only?'; Localized: '상용 라이선스 키를 제거하고 비상업적 용도로만 사용하도록 되돌리시겠습니까?'),
    (English: 'Commercial license key has been removed.'; Localized: '상용 라이선스 키가 제거되었습니다.'),
    (English: 'Your version of Inno Setup has been updated! <a id="%1">See what''s new</a>.'; Localized: 'Inno Setup 버전이 업데이트되었습니다! <a id="%1">새로운 기능 보기</a>.'),
    (English: 'VS Code-style editor shortcuts added! Use the <a id="%1">Editor Keys option</a> in Options dialog.'; Localized: 'VS Code 스타일 편집기 바로 가기 키가 추가되었습니다! 옵션 대화 상자의 <a id="%1">편집기 키 옵션</a>을 사용하세요.'),
    (English: 'RTF Editor added, a built-in WordPad replacement! Use the <a id="%1">RTF Editor item</a> in Tools menu.'; Localized: '기본 제공 워드패드 대체 도구인 RTF 편집기가 추가되었습니다! 도구 메뉴의 <a id="%1">RTF 편집기 항목</a>을 사용하세요.'),
    (English: 'Inno Setup Compiler is available in your language! Use the <a id="%1">Language option</a> in Options dialog.'; Localized: 'Inno Setup Compiler를 한국어로 사용할 수 있습니다! 옵션 대화 상자의 <a id="%1">언어 옵션</a>을 사용하세요.'),
    (English: '<a id="%1">Ideas board is open!</a> Share your ideas and vote on others, this month only.'; Localized: '<a id="%1">아이디어 게시판이 열렸습니다!</a> 이번 달에만 아이디어를 공유하고 다른 아이디어에 투표하세요.'),
    (English: 'Running a version released after your update entitlement ended. <a id="%1">Renew license</a>, <a id="%2">remove key</a>, or <a id="%3">exit</a>.'; Localized: '업데이트 권한이 종료된 후 릴리스된 버전을 실행하고 있습니다. <a id="%1">라이선스 갱신</a>, <a id="%2">키 제거</a> 또는 <a id="%3">종료</a>를 선택하세요.'),
    (English: 'Your update entitlement is ending soon. Please <a id="%1">renew your license</a>. Thanks!'; Localized: '업데이트 권한이 곧 종료됩니다. <a id="%1">라이선스를 갱신</a>하세요. 감사합니다!'),
    (English: 'Your update entitlement has ended. Please <a id="%1">renew your license</a>. Thanks!'; Localized: '업데이트 권한이 종료되었습니다. <a id="%1">라이선스를 갱신</a>하세요. 감사합니다!'),
    (English: 'Using Inno Setup commercially? Please <a id="%1">purchase a license</a>. Thanks!'; Localized: 'Inno Setup을 상업적으로 사용하고 계십니까? <a id="%1">라이선스를 구매</a>하세요. 감사합니다!'),
    (English: 'Uninstall'; Localized: '제거 프로그램'),
    (English: '%1 exit code: 0x%2'; Localized: '%1 종료 코드: 0x%2'),
    (English: '%1 exit code: %2'; Localized: '%1 종료 코드: %2'),
    (English: 'Unable to get %1 exit code (%2 failed)'; Localized: '%1 종료 코드를 가져올 수 없습니다 (%2 실패)'),
    (English: '%1 is still running; can''t get exit code'; Localized: '%1이 아직 실행 중입니다. 종료 코드를 가져올 수 없습니다'),
    (English: 'Please stop the running %1 process before performing this command.'; Localized: '이 명령을 수행하기 전에 실행 중인 %1 프로세스를 중지하세요.'),
    (English: 'This command will detach the debugger from the running %1 process. Continue?'; Localized: '이 명령은 실행 중인 %1 프로세스에서 디버거를 분리합니다. 계속하시겠습니까?'),
    (English: 'The changes you made will not take effect until you re-compile.%n%nContinue running anyway?'; Localized: '변경한 내용은 다시 컴파일할 때까지 적용되지 않습니다.%n%n그래도 계속 실행하시겠습니까?'),
    (English: 'A pause is already pending.'; Localized: '일시 중지가 이미 보류 중입니다.'),
    (English: 'No code was generated for the current line.'; Localized: '현재 줄에 대해 생성된 코드가 없습니다.'),
    (English: 'This will unconditionally terminate the running %1 process. Continue?'; Localized: '실행 중인 %1 프로세스를 무조건 종료합니다. 계속하시겠습니까?'),
    (English: 'Note that if %1 is currently in the installation phase, any changes made to the system thus far will not be undone, nor will uninstall data be written.'; Localized: '%1이 현재 설치 단계에 있는 경우 지금까지 시스템에 적용된 변경 내용은 롤백되지 않으며 제거 정보도 기록되지 않습니다.'),
    (English: 'Evaluate'; Localized: '평가'),
    (English: 'Constant to evaluate (for example, "%1"):'; Localized: '평가할 상수 (예: "%1"):'),
    (English: 'Evaluate Result'; Localized: '평가 결과'),
    (English: 'Evaluate Error'; Localized: '평가 오류'),
    (English: 'An unknown error occurred.'; Localized: '알 수 없는 오류가 발생했습니다.'),
    (English: '%1 = "%2"'; Localized: '%1 = "%2"'),
    (English: '%1 = Exception: %2'; Localized: '%1 = 예외: %2'),
    (English: '%1 = Unknown error'; Localized: '%1 = 알 수 없는 오류'),
    (English: 'Unknown error'; Localized: '알 수 없는 오류'),
    (English: 'Line %1:%n%2'; Localized: '줄 %1:%n%2'),
    (English: 'Runtime Error'; Localized: '런타임 오류'),
    (English: '%1 (Update entitlement ended)'; Localized: '%1 (업데이트 권한 종료됨)'),
    (English: '%1 (Update entitlement ended but updated anyway)'; Localized: '%1 (업데이트 권한 종료 후에도 업데이트됨)'),
    (English: 'Non-commercial use only'; Localized: '비상업적 용도로만 사용'),
    (English: 'Single User'; Localized: '단일 사용자'),
    (English: 'Team'; Localized: '팀'),
    (English: 'Enterprise'; Localized: '엔터프라이즈'),
    (English: 'Inno Setup %1 License'; Localized: 'Inno Setup %1 라이선스'),
    (English: '%1, %2.'; Localized: '%1, %2.'),
    (English: 'Includes updates until %1, major and minor.'; Localized: '%1까지의 주 버전 및 부 버전 업데이트가 포함됩니다.'),
    (English: 'Includes all future updates, major and minor.'; Localized: '향후 모든 주 버전 및 부 버전 업데이트가 포함됩니다.'),
    (English: '%1 Entries Designer'; Localized: '%1 항목 디자이너'),
    (English: '&Insert'; Localized: '삽입(&I)'),
    (English: '&Parameters...'; Localized: '매개 변수(&P)...'),
    (English: 'Remo&ve'; Localized: '제거(&V)'),
    (English: 'Add Fol&der...'; Localized: '폴더 추가(&D)...'),
    (English: '&Add File(s)...'; Localized: '파일 추가(&A)...'),
    (English: '&Files:'; Localized: '파일(&F):'),
    (English: 'Add D&ownload...'; Localized: '다운로드 추가(&O)...'),
    (English: 'Go to File'; Localized: '파일로 이동'),
    (English: 'Enter Commercial License Key'; Localized: '상용 라이선스 키 입력'),
    (English: 'Paste your license key below'; Localized: '아래에 라이선스 키를 붙여넣으세요'),
    (English: 'Close'; Localized: '닫기'),
    (English: 'Filter'; Localized: '필터'),
    (English: 'Inspector Menu'; Localized: '검사기 메뉴'),
    (English: 'Sections'; Localized: '섹션'),
    (English: 'New Main Script (%1)'; Localized: '새 주 스크립트 (%1)'),
    (English: 'Open Main Script (%1)'; Localized: '주 스크립트 열기 (%1)'),
    (English: 'Save (%1)'; Localized: '저장 (%1)'),
    (English: 'Stop Compile (%1)'; Localized: '컴파일 중지 (%1)'),
    (English: 'Target Setup (%1)'; Localized: '설치 프로그램을 대상으로 설정 (%1)'),
    (English: 'Target Uninstall (%1)'; Localized: '제거 프로그램을 대상으로 설정 (%1)'),
    (English: 'Help (%1)'; Localized: '도움말 (%1)'),
    (English: 'Main Script'; Localized: '주 스크립트'),
    (English: 'Close Banner'; Localized: '배너 닫기'),
    (English: '&File'; Localized: '파일(&F)'),
    (English: '&Open...'; Localized: '열기(&O)...'),
    (English: 'Open &Recent'; Localized: '최근 항목 열기(&R)'),
    (English: '&Clear Recently Opened'; Localized: '최근 사용 항목 지우기(&C)'),
    (English: '&Save'; Localized: '저장(&S)'),
    (English: 'Save &As...'; Localized: '다른 이름으로 저장(&A)...'),
    (English: 'Save &Encoding'; Localized: '저장 인코딩(&E)'),
    (English: '&Auto (ANSI or UTF-8)'; Localized: '자동 (ANSI 또는 UTF-8)(&A)'),
    (English: '&UTF-8'; Localized: 'UTF-8(&U)'),
    (English: 'UTF-8 with &BOM'; Localized: 'BOM이 있는 UTF-8(&B)'),
    (English: 'Sa&ve All'; Localized: '모두 저장(&V)'),
    (English: '&Print...'; Localized: '인쇄(&P)...'),
    (English: 'E&xit'; Localized: '끝내기(&X)'),
    (English: '&Edit'; Localized: '편집(&E)'),
    (English: '&Undo'; Localized: '실행 취소(&U)'),
    (English: '&Redo'; Localized: '다시 실행(&R)'),
    (English: 'Cu&t'; Localized: '잘라내기(&T)'),
    (English: '&Copy'; Localized: '복사(&C)'),
    (English: '&Paste'; Localized: '붙여넣기(&P)'),
    (English: 'De&lete'; Localized: '삭제(&L)'),
    (English: 'Select &All'; Localized: '모두 선택(&A)'),
    (English: 'Add Next &Occurrence'; Localized: '다음 일치 항목 추가(&O)'),
    (English: '&Select All Occurrences'; Localized: '모든 일치 항목 선택(&S)'),
    (English: 'Select All Find &Matches'; Localized: '모든 찾기 일치 항목 선택(&M)'),
    (English: '&Find...'; Localized: '찾기(&F)...'),
    (English: 'F&ind in Files...'; Localized: '파일에서 찾기(&I)...'),
    (English: 'Find &Next'; Localized: '다음 찾기(&N)'),
    (English: 'Find Pre&vious'; Localized: '이전 찾기(&V)'),
    (English: 'R&eplace...'; Localized: '바꾸기(&E)...'),
    (English: 'Use Regular E&xpressions'; Localized: '정규식 사용(&X)'),
    (English: 'Fol&d Section'; Localized: '섹션 접기(&D)'),
    (English: 'Unfold Section'; Localized: '섹션 펼치기'),
    (English: 'Go to File...'; Localized: '파일로 이동...'),
    (English: '&Go to Line...'; Localized: '줄로 이동(&G)...'),
    (English: 'Toggle Line Comment'; Localized: '줄 주석 설정/해제'),
    (English: 'Go To Matching Brace'; Localized: '일치하는 괄호로 이동'),
    (English: '&View'; Localized: '보기(&V)'),
    (English: '&Zoom'; Localized: '확대/축소(&Z)'),
    (English: 'Zoom &In'; Localized: '확대(&I)'),
    (English: 'Zoom &Out'; Localized: '축소(&O)'),
    (English: '&Reset'; Localized: '다시 설정(&R)'),
    (English: '&Toolbar'; Localized: '도구 모음(&T)'),
    (English: 'Na&vigator'; Localized: '탐색기(&V)'),
    (English: '&Inspector'; Localized: '검사기(&I)'),
    (English: 'St&atus Bar'; Localized: '상태 표시줄(&A)'),
    (English: '&Next Tab'; Localized: '다음 탭(&N)'),
    (English: '&Previous Tab'; Localized: '이전 탭(&P)'),
    (English: 'C&lose Tab'; Localized: '탭 닫기(&L)'),
    (English: 'Re&open Tab'; Localized: '탭 다시 열기(&O)'),
    (English: 'Reopen &All Tabs'; Localized: '모든 탭 다시 열기(&A)'),
    (English: 'C&lose Current Tab'; Localized: '현재 탭 닫기(&L)'),
    (English: 'Focus Navi&gator'; Localized: '탐색기에 포커스(&G)'),
    (English: 'Focus And &Select Navigator'; Localized: '탐색기에 포커스 및 선택(&S)'),
    (English: '&Compiler Output'; Localized: '컴파일러 출력(&C)'),
    (English: '&Debug Output'; Localized: '디버그 출력(&D)'),
    (English: 'D&ebug Call Stack'; Localized: '디버그 호출 스택(&E)'),
    (English: '&Find Results'; Localized: '찾기 결과(&F)'),
    (English: '&Hide Bottom Pane'; Localized: '아래쪽 창 숨기기(&H)'),
    (English: '&Word Wrap'; Localized: '자동 줄 바꿈(&W)'),
    (English: '&Go to'; Localized: '이동(&G)'),
    (English: 'Show all known directives'; Localized: '알려진 모든 지시문 표시'),
    (English: 'Follow cursor'; Localized: '커서 따라가기'),
    (English: 'Quote new directive values'; Localized: '새 지시문 값을 따옴표로 묶기'),
    (English: 'Quote new parameter values'; Localized: '새 매개 변수 값을 따옴표로 묶기'),
    (English: '&Help'; Localized: '도움말(&H)'),
    (English: '&Build'; Localized: '빌드(&B)'),
    (English: '&Compile'; Localized: '컴파일(&C)'),
    (English: 'S&top Compile'; Localized: '컴파일 중지(&T)'),
    (English: '&Low Priority During Compile'; Localized: '컴파일 중 낮은 우선 순위(&L)'),
    (English: '&Disable Output'; Localized: '출력 사용 안 함(&D)'),
    (English: 'Disable Co&mpression'; Localized: '압축 사용 안 함(&M)'),
    (English: 'Disable &Signing'; Localized: '서명 사용 안 함(&S)'),
    (English: 'Disable Signcheck &Validation'; Localized: '서명 확인 유효성 검사 사용 안 함(&V)'),
    (English: '&Open Output Folder'; Localized: '출력 폴더 열기(&O)'),
    (English: '&Run'; Localized: '실행(&R)'),
    (English: '&Run...'; Localized: '실행(&R)...'),
    (English: 'Run to &Cursor'; Localized: '커서까지 실행(&C)'),
    (English: 'Step &Into'; Localized: '한 단계씩 코드 실행(&I)'),
    (English: 'Step &Over'; Localized: '프로시저 단위 실행(&O)'),
    (English: 'Step Out'; Localized: '프로시저 나가기'),
    (English: 'Toggle &Breakpoint'; Localized: '중단점 설정/해제(&B)'),
    (English: '&Delete All Breakpoints'; Localized: '모든 중단점 제거(&D)'),
    (English: 'P&ause'; Localized: '일시 중지(&A)'),
    (English: '&Terminate'; Localized: '종료(&T)'),
    (English: '&Evaluate Constant...'; Localized: '상수 평가(&E)...'),
    (English: 'Target &Setup'; Localized: '설치 프로그램을 대상으로 설정(&S)'),
    (English: 'Target &Uninstall'; Localized: '제거 프로그램을 대상으로 설정(&U)'),
    (English: '&Tools'; Localized: '도구(&T)'),
    (English: '&Add/Remove Programs'; Localized: '프로그램 추가/제거(&A)'),
    (English: 'Generate &GUID'; Localized: 'GUID 생성(&G)'),
    (English: 'Generate %1 Entries...'; Localized: '%1 항목 생성...'),
    (English: 'Generate %1 Call...'; Localized: '%1 호출 생성...'),
    (English: '&Configure Sign Tools...'; Localized: '서명 도구 구성(&C)...'),
    (English: 'R&TF Editor...'; Localized: 'RTF 편집기(&T)...'),
    (English: '&Options...'; Localized: '옵션(&O)...'),
    (English: 'Purchase or Renew Commercial &License'; Localized: '상용 라이선스 구매 또는 갱신(&L)'),
    (English: 'Enter Commercial License &Key...'; Localized: '상용 라이선스 키 입력(&K)...'),
    (English: 'Remove Commercial License Key'; Localized: '상용 라이선스 키 제거'),
    (English: '&Donate'; Localized: '기부(&D)'),
    (English: '&Keyboard And Mouse Commands'; Localized: '키보드 및 마우스 명령(&K)'),
    (English: 'Regular E&xpressions'; Localized: '정규식(&X)'),
    (English: 'Inno &Setup Documentation'; Localized: 'Inno Setup 설명서(&S)'),
    (English: 'Inno Setup &Example Scripts'; Localized: 'Inno Setup 예제 스크립트(&E)'),
    (English: 'Inno Setup &FAQ'; Localized: 'Inno Setup FAQ(&F)'),
    (English: 'Inno Setup &Mailing List'; Localized: 'Inno Setup 메일링 리스트(&M)'),
    (English: 'Inno Setup &Revision History'; Localized: 'Inno Setup 개정 내역(&R)'),
    (English: 'Inno Setup &Web Site'; Localized: 'Inno Setup 웹 사이트(&W)'),
    (English: 'Inno Setup &Preprocessor Documentation'; Localized: 'Inno Setup 전처리기 설명서(&P)'),
    (English: '&About Inno Setup'; Localized: 'Inno Setup 정보(&A)'),
    (English: '%1 Call Designer'; Localized: '%1 호출 디자이너'),
    (English: 'Instruction'; Localized: '지침'),
    (English: 'Message'; Localized: '메시지'),
    (English: 'Buttons'; Localized: '단추'),
    (English: ' Type '; Localized: ' 유형 '),
    (English: 'Suppressible'; Localized: '숨김 가능'),
    (English: ' Flags '; Localized: ' 플래그 '),
    (English: 'Default button'; Localized: '기본 단추'),
    (English: ' Icon '; Localized: ' 아이콘 '),
    (English: ' Return values '; Localized: ' 반환 값 '),
    (English: '&Preview'; Localized: '미리 보기(&P)'),
    (English: 'Options'; Localized: '옵션'),
    (English: ' Miscellaneous '; Localized: ' 기타 '),
    (English: 'Show &Welcome dialog at startup'; Localized: '시작할 때 시작 대화 상자 표시(&W)'),
    (English: 'Use the Inno Setup &Script Wizard'; Localized: 'Inno Setup 스크립트 마법사 사용(&S)'),
    (English: 'Automatically sa&ve before compiling'; Localized: '컴파일하기 전에 자동으로 저장(&V)'),
    (English: 'Create &backups when saving'; Localized: '저장 시 백업 만들기(&B)'),
    (English: 'Allow &Undo after save'; Localized: '저장 후 실행 취소 허용(&U)'),
    (English: 'Display &full path in title bar'; Localized: '제목 표시줄에 전체 경로 표시(&F)'),
    (English: '&Pause on exceptions'; Localized: '예외 발생 시 일시 중지(&P)'),
    (English: '&Launch Setup/Uninstall as administrator'; Localized: '설치 프로그램/제거 프로그램을 관리자로 실행(&L)'),
    (English: 'Colori&ze "Compiler Output" view'; Localized: '"컴파일러 출력" 보기에 색 지정(&Z)'),
    (English: 'Automatically open %1 files'; Localized: '%1 파일 자동으로 열기'),
    (English: 'Automatically show preprocessor output'; Localized: '전처리기 출력 자동으로 표시'),
    (English: 'Menu &keys:'; Localized: '메뉴 키(&K):'),
    (English: 'Automatically reload files'; Localized: '파일 자동으로 다시 로드'),
    (English: 'Allow Undo after reload'; Localized: '다시 로드 후 실행 취소 허용'),
    (English: 'Keep new %1 files closed'; Localized: '새 %1 파일을 닫힌 상태로 유지'),
    (English: 'Language:'; Localized: '언어:'),
    (English: ' Inspector '; Localized: ' 검사기 '),
    (English: ' Editor '; Localized: ' 편집기 '),
    (English: 'Invoke autoco&mplete automatically'; Localized: '자동 완성 자동으로 호출(&M)'),
    (English: 'Use syntax &highlighting'; Localized: '구문 강조 표시 사용(&H)'),
    (English: 'U&nderline syntax errors'; Localized: '구문 오류에 밑줄 표시(&N)'),
    (English: 'Allow cursor to move beyond &end of lines'; Localized: '커서가 줄 끝을 넘어 이동하도록 허용(&E)'),
    (English: 'Enable section f&olding'; Localized: '섹션 접기 사용(&O)'),
    (English: 'Use tab cha&racter'; Localized: '탭 문자 사용(&R)'),
    (English: 'Auto &indent mode'; Localized: '자동 들여쓰기 모드(&I)'),
    (English: 'Show indentation &guides'; Localized: '들여쓰기 안내선 표시(&G)'),
    (English: 'Font:'; Localized: '글꼴:'),
    (English: 'AaBbXxZz'; Localized: 'AaBbXxZz'),
    (English: '&Change...'; Localized: '변경(&C)...'),
    (English: '&Tab Width:'; Localized: '탭 너비(&T):'),
    (English: 'Show &line numbers in gutter'; Localized: '여백에 줄 번호 표시(&L)'),
    (English: 'T&heme:'; Localized: '테마(&H):'),
    (English: 'Highlight occurrences of current selection'; Localized: '현재 선택 영역의 일치 항목 강조 표시'),
    (English: 'Highlight occurrences of current wor&d'; Localized: '현재 단어의 일치 항목 강조 표시(&D)'),
    (English: 'Ke&ys:'; Localized: '키(&Y):'),
    (English: 'Show whitespace'; Localized: '공백 표시'),
    (English: 'Smart Home key'; Localized: '스마트 Home 키'),
    (English: '&Associate .%1 files with this compiler'; Localized: '.%1 파일을 이 컴파일러에 연결(&A)'),
    (English: '&Windows registry file (.%1) to import:'; Localized: '가져올 Windows 레지스트리 파일 (.%1)(&W):'),
    (English: 'B&rowse...'; Localized: '찾아보기(&R)...'),
    (English: 'Settings (for all keys and values):'; Localized: '설정 (모든 키 및 값에 적용):'),
    (English: 'Also delete keys which are not empty'; Localized: '비어 있지 않은 키도 삭제'),
    (English: 'Delete keys which are empty on uninstall'; Localized: '제거 시 비어 있는 키 삭제'),
    (English: 'Delete values on uninstall'; Localized: '제거 시 값 삭제'),
    (English: 'Minimum Windows version:'; Localized: '최소 Windows 버전:'),
    (English: 'RTF Editor'; Localized: 'RTF 편집기'),
    (English: 'New (%1)'; Localized: '새로 만들기 (%1)'),
    (English: 'Open (%1)'; Localized: '열기 (%1)'),
    (English: 'Cut (%1)'; Localized: '잘라내기 (%1)'),
    (English: 'Copy (%1)'; Localized: '복사 (%1)'),
    (English: 'Paste (%1)'; Localized: '붙여넣기 (%1)'),
    (English: 'Undo (%1)'; Localized: '실행 취소 (%1)'),
    (English: 'Redo (%1)'; Localized: '다시 실행 (%1)'),
    (English: 'Bold (%1)'; Localized: '굵게 (%1)'),
    (English: 'Italic (%1)'; Localized: '기울임꼴 (%1)'),
    (English: 'Underline (%1)'; Localized: '밑줄 (%1)'),
    (English: '&Bold'; Localized: '굵게(&B)'),
    (English: '&Italic'; Localized: '기울임꼴(&I)'),
    (English: '&Underline'; Localized: '밑줄(&U)'),
    (English: '&Font...'; Localized: '글꼴(&F)...'),
    (English: '&Increase Font Size'; Localized: '글꼴 크기 크게(&I)'),
    (English: '&Decrease Font Size'; Localized: '글꼴 크기 작게(&D)'),
    (English: 'Text &Color...'; Localized: '텍스트 색(&C)...'),
    (English: '&Background Color...'; Localized: '배경색(&B)...'),
    (English: 'Reset &Colors'; Localized: '색 다시 설정(&C)'),
    (English: 'Align &Left'; Localized: '왼쪽 맞춤(&L)'),
    (English: '&Center'; Localized: '가운데 맞춤(&C)'),
    (English: 'Align &Right'; Localized: '오른쪽 맞춤(&R)'),
    (English: 'Bulle&ts'; Localized: '글머리 기호(&T)'),
    (English: 'Increase &Indent'; Localized: '들여쓰기 늘리기(&I)'),
    (English: 'Decrease Inden&t'; Localized: '들여쓰기 줄이기(&T)'),
    (English: 'Configure Sign Tools'; Localized: '서명 도구 구성'),
    (English: ' Sign Tools '; Localized: ' 서명 도구 '),
    (English: '&Add...'; Localized: '추가(&A)...'),
    (English: '&Edit...'; Localized: '편집(&E)...'),
    (English: 'Be notified by e-mail of new Inno Setup releases'; Localized: '새 Inno Setup 릴리스가 나오면 이메일로 알림 받기'),
    (English: 'Subscribe'; Localized: '구독'),
    (English: ' New file '; Localized: ' 새 파일 '),
    (English: 'Create a new &empty script file'; Localized: '새 빈 스크립트 파일 만들기(&E)'),
    (English: 'Create a new script file using the &Script Wizard'; Localized: '스크립트 마법사를 사용하여 새 스크립트 파일 만들기(&S)'),
    (English: ' Open file '; Localized: ' 파일 열기 '),
    (English: 'Open an e&xisting script file'; Localized: '기존 스크립트 파일 열기(&X)'),
    (English: '&Don''t show this dialog again'; Localized: '이 대화 상자를 다시 표시하지 않음(&D)'),
    (English: 'Script Wizard File'; Localized: '스크립트 마법사 파일'),
    (English: 'bold'; Localized: '굵게'),
    (English: ' = required'; Localized: ' = 필수'),
    (English: ' Destination '; Localized: ' 대상 '),
    (English: 'Destination &base folder:'; Localized: '대상 기본 폴더(&B):'),
    (English: 'Destination &subfolder:'; Localized: '대상 하위 폴더(&S):'),
    (English: 'Destination &name:'; Localized: '대상 이름(&N):'),
    (English: ' Source '; Localized: ' 원본 '),
    (English: '&Source file or folder:'; Localized: '원본 파일 또는 폴더(&S):'),
    (English: '&Recurse subfolders'; Localized: '하위 폴더를 재귀적으로 처리(&R)'),
    (English: '&Include empty subfolders'; Localized: '빈 하위 폴더 포함(&I)'),
    (English: '&Extract archive'; Localized: '압축 파일 추출(&E)'),
    (English: 'Welcome to the %1'; Localized: '%1에 오신 것을 환영합니다'),
    (English: 'This wizard will guide you through the process of creating a new Inno Setup script file. The results will be used to generate a new script file which can be compiled directly or saved on disk for later use.%n%nNot all features of Inno Setup are covered by this wizard. See the documentation for details on creating Inno Setup script files.%n%nClick Next to continue, or Cancel to exit this wizard.'; Localized: '이 마법사는 새 Inno Setup 스크립트 파일을 만드는 과정을 안내합니다. 결과는 새 스크립트 파일을 생성하는 데 사용되며, 이 파일은 바로 컴파일하거나 나중에 사용하기 위해 디스크에 저장할 수 있습니다.%n%n이 마법사는 Inno Setup의 모든 기능을 다루지는 않습니다. Inno Setup 스크립트 파일 만들기에 대한 자세한 내용은 설명서를 참조하세요.%n%n계속하려면 다음을 클릭하고, 이 마법사를 종료하려면 취소를 클릭하세요.'),
    (English: 'Application na&me:'; Localized: '응용 프로그램 이름(&M):'),
    (English: 'Application &version:'; Localized: '응용 프로그램 버전(&V):'),
    (English: 'Application &publisher:'; Localized: '응용 프로그램 게시자(&P):'),
    (English: 'Application &website:'; Localized: '응용 프로그램 웹 사이트(&W):'),
    (English: 'Application folder na&me:'; Localized: '응용 프로그램 폴더 이름(&M):'),
    (English: 'Application &destination base folder:'; Localized: '응용 프로그램 대상 기본 폴더(&D):'),
    (English: 'Other:'; Localized: '기타:'),
    (English: 'Allow user to &change the application folder'; Localized: '사용자가 응용 프로그램 폴더를 변경하도록 허용(&C)'),
    (English: 'The application doe&sn''t need a folder'; Localized: '응용 프로그램에 폴더가 필요하지 않음(&S)'),
    (English: 'Other application &files:'; Localized: '기타 응용 프로그램 파일(&F):'),
    (English: 'Application &main executable file:'; Localized: '응용 프로그램 주 실행 파일(&M):'),
    (English: 'Allow &user to start the application after Setup has finished'; Localized: '설치가 완료된 후 사용자가 응용 프로그램을 시작하도록 허용(&U)'),
    (English: 'The application doe&sn''t have a main executable file'; Localized: '응용 프로그램에 주 실행 파일이 없음(&S)'),
    (English: 'Application file type na&me:'; Localized: '응용 프로그램 파일 형식 이름(&M):'),
    (English: '&Associate a file type to the main executable'; Localized: '파일 형식을 주 실행 파일에 연결(&A)'),
    (English: 'Application file type &extension:'; Localized: '응용 프로그램 파일 형식 확장자(&E):'),
    (English: 'Application &Start Menu folder name:'; Localized: '응용 프로그램 시작 메뉴 폴더 이름(&S):'),
    (English: 'Other shortcuts to the main executable:'; Localized: '주 실행 파일에 대한 기타 바로 가기:'),
    (English: 'Allow user to &change the Start Menu folder name'; Localized: '사용자가 시작 메뉴 폴더 이름을 변경하도록 허용(&C)'),
    (English: 'Allow user to &disable Start Menu folder creation'; Localized: '사용자가 시작 메뉴 폴더를 만들지 않도록 허용(&D)'),
    (English: 'Allow user to create a deskto&p shortcut'; Localized: '사용자가 바탕 화면 바로 가기를 만들도록 허용(&P)'),
    (English: 'Create an &Uninstall shortcut in the Start Menu folder'; Localized: '시작 메뉴 폴더에 제거 바로 가기 만들기(&U)'),
    (English: 'Create an &Internet shortcut in the Start Menu folder'; Localized: '시작 메뉴 폴더에 인터넷 바로 가기 만들기(&I)'),
    (English: '&Create a Start Menu shortcut but no folder'; Localized: '폴더 없이 시작 메뉴 바로 가기 만들기(&C)'),
    (English: '&License file:'; Localized: '라이선스 파일(&L):'),
    (English: '&Information file shown before installation:'; Localized: '설치 전에 표시할 정보 파일(&I):'),
    (English: 'Information file shown &after installation:'; Localized: '설치 후에 표시할 정보 파일(&A):'),
    (English: 'Install mode:'; Localized: '설치 모드:'),
    (English: '&Administrative install mode (install for all users)'; Localized: '관리자 설치 모드 (모든 사용자용으로 설치)(&A)'),
    (English: 'Non a&dministrative install mode (install for current user only)'; Localized: '비관리자 설치 모드 (현재 사용자용으로만 설치)(&D)'),
    (English: 'Allow user to &override the install mode via the command line'; Localized: '사용자가 명령줄로 설치 모드를 재정의하도록 허용(&O)'),
    (English: 'Ask the user to &choose the install mode at startup'; Localized: '시작할 때 사용자에게 설치 모드를 선택하도록 요청(&C)'),
    (English: '&Languages:'; Localized: '언어(&L):'),
    (English: '&Deselect All'; Localized: '모두 선택 취소(&D)'),
    (English: 'Custom compiler output fol&der:'; Localized: '사용자 지정 컴파일러 출력 폴더(&D):'),
    (English: 'Compiler output base &file name:'; Localized: '컴파일러 출력 기본 파일 이름(&F):'),
    (English: 'Custom Setup &icon file:'; Localized: '사용자 지정 설치 프로그램 아이콘 파일(&I):'),
    (English: 'Setup &password:'; Localized: '설치 암호(&P):'),
    (English: 'Use the password to &encrypt the application files'; Localized: '암호를 사용하여 응용 프로그램 파일 암호화(&E)'),
    (English: '&Wizard style:'; Localized: '마법사 스타일(&W):'),
    (English: 'You have successfully completed the %1.%n%nTo close this wizard and generate the new script file, click Finish.'; Localized: '%1을(를) 성공적으로 완료했습니다.%n%n이 마법사를 닫고 새 스크립트 파일을 생성하려면 마침을 클릭하세요.'),
    (English: '&Back'; Localized: '뒤로(&B)'),
    (English: '''%s'' is not a valid integer value'; Localized: '''%s''은(는) 올바른 정수 값이 아닙니다'),
    (English: '''%s'' is not a valid integer value for %s type'; Localized: '''%s''은(는) %s 형식에 대한 올바른 정수 값이 아닙니다'),
    (English: '''%s'' is not a valid floating point value'; Localized: '''%s''은(는) 올바른 부동 소수점 값이 아닙니다'),
    (English: '''%d.%d'' is not a valid timestamp'; Localized: '''%d.%d''은(는) 올바른 타임스탬프가 아닙니다'),
    (English: '''%s'' is not a valid GUID value'; Localized: '''%s''은(는) 올바른 GUID 값이 아닙니다'),
    (English: 'Invalid argument to time encode'; Localized: '시간 인코딩에 대한 인수가 잘못되었습니다'),
    (English: 'Invalid argument to date encode'; Localized: '날짜 인코딩에 대한 인수가 잘못되었습니다'),
    (English: 'Out of memory'; Localized: '메모리가 부족합니다'),
    (English: 'I/O error %d'; Localized: 'I/O 오류 %d'),
    (English: 'File not found'; Localized: '파일을 찾을 수 없습니다'),
    (English: 'Invalid filename'; Localized: '잘못된 파일 이름'),
    (English: 'Too many open files'; Localized: '열려 있는 파일이 너무 많습니다'),
    (English: 'File access denied'; Localized: '파일 액세스가 거부되었습니다'),
    (English: 'Read beyond end of file'; Localized: '파일 끝을 넘어 읽었습니다'),
    (English: 'Disk full'; Localized: '디스크가 가득 찼습니다'),
    (English: 'Invalid numeric input'; Localized: '잘못된 숫자 입력'),
    (English: 'Division by zero'; Localized: '0으로 나누기'),
    (English: 'Range check error'; Localized: '범위 검사 오류'),
    (English: 'Integer overflow'; Localized: '정수 오버플로'),
    (English: 'Invalid floating point operation'; Localized: '잘못된 부동 소수점 연산'),
    (English: 'Floating point division by zero'; Localized: '부동 소수점 0으로 나누기'),
    (English: 'Floating point overflow'; Localized: '부동 소수점 오버플로'),
    (English: 'Floating point underflow'; Localized: '부동 소수점 언더플로'),
    (English: 'Invalid pointer operation'; Localized: '잘못된 포인터 작업'),
    (English: 'Invalid class typecast'; Localized: '잘못된 클래스 캐스트'),
    (English: 'Access violation at address %p. %s of address %p'; Localized: '%0:p 주소에서 액세스 위반이 발생했습니다. 주소 %2:p에 대한 %1:s'),
    (English: 'Access violation'; Localized: '액세스 위반'),
    (English: 'Stack overflow'; Localized: '스택 오버플로'),
    (English: 'Control-C hit'; Localized: 'Control-C를 눌렀습니다'),
    (English: 'Privileged instruction'; Localized: '권한 있는 명령'),
    (English: 'Operation aborted'; Localized: '작업이 중단되었습니다'),
    (English: 'Exception %s in module %s at %p.'#13#10'%s%s'#13#10; Localized: '%s 예외가 %s 모듈의 %p 위치에서 발생했습니다.'#13#10'%s%s'#13#10),
    (English: 'Application Error'; Localized: '응용 프로그램 오류'),
    (English: 'Format ''%s'' invalid or incompatible with argument'; Localized: '''%s'' 형식이 잘못되었거나 인수와 호환되지 않습니다'),
    (English: 'No argument for format ''%s'''; Localized: '''%s'' 형식에 대한 인수가 없습니다'),
    (English: 'Variant method calls not supported'; Localized: 'Variant 메서드 호출은 지원되지 않습니다'),
    (English: 'Read'; Localized: '읽기'),
    (English: 'Write'; Localized: '쓰기'),
    (English: 'Execution'; Localized: '실행'),
    (English: 'Invalid access'; Localized: '잘못된 액세스'),
    (English: 'Error creating variant or safe array'; Localized: 'Variant 또는 안전 배열을 만드는 동안 오류가 발생했습니다'),
    (English: 'Variant or safe array index out of bounds'; Localized: 'Variant 또는 안전 배열 인덱스가 범위를 벗어났습니다'),
    (English: 'Variant or safe array is locked'; Localized: 'Variant 또는 안전 배열이 잠겨 있습니다'),
    (English: 'Invalid variant type conversion'; Localized: '잘못된 Variant 형식 변환'),
    (English: 'Invalid variant operation'; Localized: '잘못된 Variant 작업'),
    (English: 'Invalid NULL variant operation'; Localized: '잘못된 NULL Variant 작업'),
    (English: 'Invalid variant operation (%s%.8x)'#10'%s'; Localized: '잘못된 Variant 작업 (%s%.8x)'#10'%s'),
    (English: 'Could not convert variant of type (%s) into type (%s)'; Localized: '(%s) 형식의 Variant를 (%s) 형식으로 변환할 수 없습니다'),
    (English: 'Overflow while converting variant of type (%s) into type (%s)'; Localized: '(%s) 형식의 Variant를 (%s) 형식으로 변환하는 동안 오버플로가 발생했습니다'),
    (English: 'Variant overflow'; Localized: 'Variant 오버플로'),
    (English: 'Invalid argument'; Localized: '잘못된 인수'),
    (English: 'Invalid variant type'; Localized: '잘못된 Variant 형식'),
    (English: 'Operation not supported'; Localized: '작업이 지원되지 않습니다'),
    (English: 'Unexpected variant error'; Localized: '예기치 않은 Variant 오류'),
    (English: 'External exception %x'; Localized: '외부 예외 %x'),
    (English: 'Assertion failed'; Localized: '어설션 실패'),
    (English: 'Interface not supported'; Localized: '인터페이스가 지원되지 않습니다'),
    (English: 'Exception in safecall method'; Localized: 'safecall 메서드에서 예외가 발생했습니다'),
    (English: 'Object lock not owned'; Localized: '개체 잠금을 소유하고 있지 않습니다'),
    (English: 'Monitor support function not initialized'; Localized: 'Monitor 지원 함수가 초기화되지 않았습니다'),
    (English: 'Feature not implemented'; Localized: '기능이 구현되지 않았습니다'),
    (English: 'Method called on disposed object'; Localized: '삭제된 개체에서 메서드를 호출했습니다'),
    (English: '%s (%s, line %d)'; Localized: '%s (%s, 줄 %d)'),
    (English: 'Abstract Error'; Localized: '추상 메서드 오류'),
    (English: 'Access violation at address %p in module ''%s'' (offset %x). %s of address %p'; Localized: '''%1:s'' 모듈의 %0:p 위치에서 액세스 위반이 발생했습니다 (오프셋 %2:x). 주소 %4:p에 대한 %3:s'),
    (English: 'System Error.  Code: %d.'#13#10'%s%s'; Localized: '시스템 오류.  코드: %d.'#13#10'%s%s'),
    (English: 'A call to an OS function failed'; Localized: 'OS 함수 호출이 실패했습니다'),
    (English: 'Jan'; Localized: '1월'),
    (English: 'Feb'; Localized: '2월'),
    (English: 'Mar'; Localized: '3월'),
    (English: 'Apr'; Localized: '4월'),
    (English: 'May'; Localized: '5월'),
    (English: 'Jun'; Localized: '6월'),
    (English: 'Jul'; Localized: '7월'),
    (English: 'Aug'; Localized: '8월'),
    (English: 'Sep'; Localized: '9월'),
    (English: 'Oct'; Localized: '10월'),
    (English: 'Nov'; Localized: '11월'),
    (English: 'Dec'; Localized: '12월'),
    (English: 'January'; Localized: '1월'),
    (English: 'February'; Localized: '2월'),
    (English: 'March'; Localized: '3월'),
    (English: 'April'; Localized: '4월'),
    (English: 'June'; Localized: '6월'),
    (English: 'July'; Localized: '7월'),
    (English: 'August'; Localized: '8월'),
    (English: 'September'; Localized: '9월'),
    (English: 'October'; Localized: '10월'),
    (English: 'November'; Localized: '11월'),
    (English: 'December'; Localized: '12월'),
    (English: 'Sun'; Localized: '일'),
    (English: 'Mon'; Localized: '월'),
    (English: 'Tue'; Localized: '화'),
    (English: 'Wed'; Localized: '수'),
    (English: 'Thu'; Localized: '목'),
    (English: 'Fri'; Localized: '금'),
    (English: 'Sat'; Localized: '토'),
    (English: 'Sunday'; Localized: '일요일'),
    (English: 'Monday'; Localized: '월요일'),
    (English: 'Tuesday'; Localized: '화요일'),
    (English: 'Wednesday'; Localized: '수요일'),
    (English: 'Thursday'; Localized: '목요일'),
    (English: 'Friday'; Localized: '금요일'),
    (English: 'Saturday'; Localized: '토요일'),
    (English: 'Invalid source array'; Localized: '잘못된 원본 배열'),
    (English: 'Invalid destination array'; Localized: '잘못된 대상 배열'),
    (English: 'Character index out of bounds (%d)'; Localized: '문자 인덱스가 범위를 벗어났습니다 (%d)'),
    (English: 'Start index out of bounds (%d)'; Localized: '시작 인덱스가 범위를 벗어났습니다 (%d)'),
    (English: 'Invalid count (%d)'; Localized: '잘못된 개수 (%d)'),
    (English: 'Invalid destination index (%d)'; Localized: '잘못된 대상 인덱스 (%d)'),
    (English: 'Invalid code page'; Localized: '잘못된 코드 페이지'),
    (English: 'No mapping for the Unicode character exists in the target multi-byte code page'; Localized: '대상 멀티바이트 코드 페이지에 이 유니코드 문자의 매핑이 없습니다'),
    (English: 'Invalid StringBaseIndex'; Localized: '잘못된 StringBaseIndex'),
    (English: '''%s'' is not a valid %s color value'; Localized: '''%s''은(는) 올바른 %s 색 값이 아닙니다'),
    (English: 'Ancestor for ''%s'' not found'; Localized: '''%s''의 상위 항목을 찾을 수 없습니다'),
    (English: 'Cannot assign a %s to a %s'; Localized: '%s을(를) %s에 할당할 수 없습니다'),
    (English: 'Bits index out of range'; Localized: 'Bits 인덱스가 범위를 벗어났습니다'),
    (English: 'Can''t write to a read-only resource stream'; Localized: '읽기 전용 리소스 스트림에는 쓸 수 없습니다'),
    (English: '''''%s'''' expected'; Localized: '''''%s''''이(가) 필요합니다'),
    (English: 'CheckSynchronize called from thread $%x, which is NOT the main thread'; Localized: 'CheckSynchronize가 주 스레드가 아닌 $%x 스레드에서 호출되었습니다'),
    (English: 'Class %s not found'; Localized: '%s 클래스를 찾을 수 없습니다'),
    (English: 'A class named %s already exists'; Localized: '이름이 %s인 클래스가 이미 존재합니다'),
    (English: 'List does not allow duplicates ($0%x)'; Localized: '목록에는 중복이 허용되지 않습니다 ($0%x)'),
    (English: 'A component named %s already exists'; Localized: '이름이 %s인 구성 요소가 이미 존재합니다'),
    (English: 'String list does not allow duplicates'; Localized: '문자열 목록에는 중복이 허용되지 않습니다'),
    (English: 'Cannot create file "%s". %s'; Localized: '"%s" 파일을 만들 수 없습니다. %s'),
    (English: 'Cannot open file "%s". %s'; Localized: '"%s" 파일을 열 수 없습니다. %s'),
    (English: 'Identifier expected'; Localized: '식별자가 필요합니다'),
    (English: 'Invalid binary value'; Localized: '잘못된 이진 값'),
    (English: 'Invalid stream format'; Localized: '잘못된 스트림 형식'),
    (English: '''%s'' is an invalid mask at (%d)'; Localized: '''%s''은(는) (%d)에서 잘못된 마스크입니다'),
    (English: '''''%s'''' is not a valid component name'; Localized: '''''%s''''은(는) 올바른 구성 요소 이름이 아닙니다'),
    (English: 'Invalid property value'; Localized: '잘못된 속성 값'),
    (English: 'Invalid property path'; Localized: '잘못된 속성 경로'),
    (English: 'Invalid data type for ''%s'''; Localized: '''%s''의 데이터 형식이 잘못되었습니다'),
    (English: 'Invalid string constant'; Localized: '잘못된 문자열 상수'),
    (English: 'Line too long'; Localized: '줄이 너무 깁니다'),
    (English: 'List capacity out of bounds (%d)'; Localized: '목록 용량이 범위를 벗어났습니다 (%d)'),
    (English: 'List count out of bounds (%d)'; Localized: '목록 개수가 범위를 벗어났습니다 (%d)'),
    (English: 'List index out of bounds (%d)'; Localized: '목록 인덱스가 범위를 벗어났습니다 (%d)'),
    (English: '.  %s range is 0..%d'; Localized: '.  %s 범위는 0..%d입니다'),
    (English: '.  %s is empty'; Localized: '.  %s이(가) 비어 있습니다'),
    (English: 'Out of memory while expanding memory stream'; Localized: '메모리 스트림을 확장하는 동안 메모리가 부족해졌습니다'),
    (English: '%s has not been registered as a COM class'; Localized: '%s이(가) COM 클래스로 등록되지 않았습니다'),
    (English: 'Printer is not currently printing'; Localized: '프린터가 현재 인쇄하고 있지 않습니다'),
    (English: 'Number expected'; Localized: '숫자가 필요합니다'),
    (English: 'ANSI or UTF8 encoding expected'; Localized: 'ANSI 또는 UTF8 인코딩이 필요합니다'),
    (English: '%s on line %d'; Localized: '%s (줄 %d)'),
    (English: 'Error reading %s%s%s: %s'; Localized: '%s%s%s을(를) 읽는 동안 오류가 발생했습니다: %s'),
    (English: 'Printing in progress'; Localized: '인쇄 진행 중'),
    (English: 'Stream read error'; Localized: '스트림 읽기 오류'),
    (English: 'Property is read-only'; Localized: '속성이 읽기 전용입니다'),
    (English: 'Failed to create key %s'; Localized: '%s 키를 만들지 못했습니다'),
    (English: 'Failed to get data for ''%s'''; Localized: '''%s''의 데이터를 가져오지 못했습니다'),
    (English: 'Failed to set data for ''%s'''; Localized: '''%s''의 데이터를 설정하지 못했습니다'),
    (English: 'Resource %s not found'; Localized: '%s 리소스를 찾을 수 없습니다'),
    (English: '%s.Seek not implemented'; Localized: '%s.Seek이(가) 구현되지 않았습니다'),
    (English: 'Operation not allowed on sorted list'; Localized: '정렬된 목록에서는 작업이 허용되지 않습니다'),
    (English: 'String expected'; Localized: '문자열이 필요합니다'),
    (English: '%s expected'; Localized: '%s이(가) 필요합니다'),
    (English: '%s not in a class registration group'; Localized: '%s이(가) 클래스 등록 그룹에 없습니다'),
    (English: 'Property %s does not exist'; Localized: '%s 속성이 존재하지 않습니다'),
    (English: 'Stream write error'; Localized: '스트림 쓰기 오류'),
    (English: 'Thread creation error: %s'; Localized: '스레드 만들기 오류: %s'),
    (English: 'Thread Error: %s (%d)'; Localized: '스레드 오류: %s (%d)'),
    (English: 'Cannot terminate an externally created thread'; Localized: '외부에서 만든 스레드는 종료할 수 없습니다'),
    (English: 'Cannot wait for an externally created thread'; Localized: '외부에서 만든 스레드는 대기할 수 없습니다'),
    (English: 'Cannot call Start on a running or suspended thread'; Localized: '실행 중이거나 일시 중단된 스레드에서는 Start를 호출할 수 없습니다'),
    (English: 'Parameter %s cannot be nil'; Localized: '매개 변수 %s은(는) nil일 수 없습니다'),
    (English: 'Parameter %s cannot be a negative value'; Localized: '매개 변수 %s은(는) 음수 값일 수 없습니다'),
    (English: 'Invalid characters in path'; Localized: '경로에 잘못된 문자가 있습니다'),
    (English: 'Invalid characters in search pattern'; Localized: '검색 패턴에 잘못된 문자가 있습니다'),
    (English: 'Path is empty'; Localized: '경로가 비어 있습니다'),
    (English: 'Search pattern is empty'; Localized: '검색 패턴이 비어 있습니다'),
    (English: 'The specified path is too long'; Localized: '지정한 경로가 너무 깁니다'),
    (English: 'The specified path was not found'; Localized: '지정한 경로를 찾을 수 없습니다'),
    (English: 'The path format is not supported'; Localized: '경로 형식이 지원되지 않습니다'),
    (English: 'No help viewer that supports filters'; Localized: '필터를 지원하는 도움말 뷰어가 없습니다'),
    (English: 'String index out of range (%d).  Must be >= %d and <= %d'; Localized: '문자열 인덱스가 범위를 벗어났습니다 (%d).  >= %d 및 <= %d이어야 합니다'),
    (English: 'Invalid UTF32 character value.  Must be >= 0 and <= $10FFFF, excluding surrogate pair ranges'; Localized: '잘못된 UTF32 문자 값입니다.  서로게이트 쌍 범위를 제외하고 >= 0 및 <= $10FFFF이어야 합니다'),
    (English: 'High surrogate char without a following low surrogate char at index: %d. Check that the string is encoded properly'; Localized: '인덱스 %d에서 상위 서로게이트 문자 뒤에 하위 서로게이트 문자가 없습니다. 문자열이 올바르게 인코딩되었는지 확인하세요'),
    (English: 'Low surrogate char without a preceding high surrogate char at index: %d. Check that the string is encoded properly'; Localized: '인덱스 %d에서 하위 서로게이트 문자 앞에 상위 서로게이트 문자가 없습니다. 문자열이 올바르게 인코딩되었는지 확인하세요'),
    (English: 'Source and Destination arrays must not be the same'; Localized: '원본과 대상 배열은 같을 수 없습니다'),
    (English: 'SpinCount out of range. Must be between 0 and %d'; Localized: 'SpinCount가 범위를 벗어났습니다. 0과 %d 사이여야 합니다'),
    (English: 'No context-sensitive help installed'; Localized: '상황에 맞는 도움말이 설치되어 있지 않습니다'),
    (English: 'No help found for context %d'; Localized: '컨텍스트 %d에 대한 도움말을 찾을 수 없습니다'),
    (English: 'Unable to open Index'; Localized: '색인을 열 수 없습니다'),
    (English: 'Unable to open Search'; Localized: '검색을 열 수 없습니다'),
    (English: 'Unable to find a Table of Contents'; Localized: '목차를 찾을 수 없습니다'),
    (English: 'No topic-based help system installed'; Localized: '항목 기반 도움말 시스템이 설치되어 있지 않습니다'),
    (English: 'No help found for %s'; Localized: '%s에 대한 도움말을 찾을 수 없습니다'),
    (English: 'Argument out of range'; Localized: '인수가 범위를 벗어났습니다'),
    (English: 'Argument must not be nil'; Localized: '인수는 nil일 수 없습니다'),
    (English: 'Item not found'; Localized: '항목을 찾을 수 없습니다'),
    (English: 'Duplicates not allowed'; Localized: '중복이 허용되지 않습니다'),
    (English: 'Insufficient RTTI available to support this operation'; Localized: '이 작업을 지원하기에 충분한 RTTI를 사용할 수 없습니다'),
    (English: 'Parameter count mismatch'; Localized: '매개 변수 개수가 일치하지 않습니다'),
    (English: 'Parameter count exceeded'; Localized: '매개 변수 개수가 초과되었습니다'),
    (English: 'Type ''%s'' is not declared in the interface section of a unit'; Localized: '''%s'' 형식이 유닛의 인터페이스 섹션에 선언되어 있지 않습니다'),
    (English: 'VAR and OUT arguments must match parameter type exactly'; Localized: 'VAR 및 OUT 인수는 매개 변수 형식과 정확히 일치해야 합니다'),
    (English: 'Property ''%s'' is read-only'; Localized: '''%s'' 속성은 읽기 전용입니다'),
    (English: 'Property ''%s'' is write-only'; Localized: '''%s'' 속성은 쓰기 전용입니다'),
    (English: 'RTTI objects cannot be manually destroyed by application code'; Localized: 'RTTI 개체는 응용 프로그램 코드에서 수동으로 삭제할 수 없습니다'),
    (English: '%s (Version %d.%d, Build %d, %5:s)'; Localized: '%s (버전 %d.%d, 빌드 %d, %5:s)'),
    (English: '%s Service Pack %4:d (Version %1:d.%2:d, Build %3:d, %5:s)'; Localized: '%s 서비스 팩 %4:d (버전 %1:d.%2:d, 빌드 %3:d, %5:s)'),
    (English: '32-bit Edition'; Localized: '32비트 에디션'),
    (English: '64-bit Edition'; Localized: '64비트 에디션'),
    (English: 'Windows'; Localized: 'Windows'),
    (English: 'Windows Vista'; Localized: 'Windows Vista'),
    (English: 'Windows Server 2008'; Localized: 'Windows Server 2008'),
    (English: 'Windows 7'; Localized: 'Windows 7'),
    (English: 'Windows Server 2008 R2'; Localized: 'Windows Server 2008 R2'),
    (English: 'Windows 2000'; Localized: 'Windows 2000'),
    (English: 'Windows XP'; Localized: 'Windows XP'),
    (English: 'Windows Server 2003'; Localized: 'Windows Server 2003'),
    (English: 'Windows Server 2003 R2'; Localized: 'Windows Server 2003 R2'),
    (English: 'Windows Server 2012'; Localized: 'Windows Server 2012'),
    (English: 'Windows Server 2012 R2'; Localized: 'Windows Server 2012 R2'),
    (English: 'Windows Server 2016'; Localized: 'Windows Server 2016'),
    (English: 'Windows Server 2019'; Localized: 'Windows Server 2019'),
    (English: 'Windows Server 2022'; Localized: 'Windows Server 2022'),
    (English: 'Windows 8'; Localized: 'Windows 8'),
    (English: 'Windows 8.1'; Localized: 'Windows 8.1'),
    (English: 'Windows 10'; Localized: 'Windows 10'),
    (English: 'Windows 11'; Localized: 'Windows 11'),
    (English: 'Cannot create instance of class %s'; Localized: '%s 클래스의 인스턴스를 만들 수 없습니다'),
    (English: 'Observer is not supported'; Localized: '관찰자가 지원되지 않습니다'),
    (English: 'Cannot have multiple single cast observers added to the observers collection'; Localized: '관찰자 컬렉션에는 여러 단일 캐스트 관찰자를 추가할 수 없습니다'),
    (English: 'The object does not implement the observer interface'; Localized: '개체가 관찰자 인터페이스를 구현하지 않습니다'),
    (English: 'No single cast observer with ID %d was added to the observer collection'; Localized: 'ID가 %d인 단일 캐스트 관찰자가 관찰자 컬렉션에 추가되지 않았습니다'),
    (English: 'No multi cast observer with ID %d was added to the observer collection'; Localized: 'ID가 %d인 멀티캐스트 관찰자가 관찰자 컬렉션에 추가되지 않았습니다'),
    (English: 'Observer is not available'; Localized: '관찰자를 사용할 수 없습니다'),
    (English: 'SHA2: Cannot update a finalized hash'; Localized: 'SHA2: 완료된 해시는 업데이트할 수 없습니다'),
    (English: 'Must wait on at least one event'; Localized: '하나 이상의 이벤트를 대기해야 합니다'),
    (English: 'Cannot call BeginInvoke on a TComponent in the process of destruction'; Localized: '삭제 중인 TComponent에서는 BeginInvoke를 호출할 수 없습니다'),
    (English: 'OLE error %.8x'; Localized: 'OLE 오류 %.8x'),
    (English: 'Method ''%s'' not supported by automation object'; Localized: '자동화 개체가 ''%s'' 메서드를 지원하지 않습니다'),
    (English: 'Variant does not reference an automation object'; Localized: 'Variant가 자동화 개체를 참조하지 않습니다'),
    (English: 'Dispatch methods do not support more than 64 parameters'; Localized: '디스패치 메서드는 64개를 초과하는 매개 변수를 지원하지 않습니다'),
    (English: 'A regular expression specified in RegEx is required'; Localized: 'RegEx에 지정된 정규식이 필요합니다'),
    (English: 'Error in regular expression at offset %d: %s'; Localized: '정규식의 오프셋 %d에서 오류가 발생했습니다: %s'),
    (English: 'Successful match required'; Localized: '성공한 일치가 필요합니다'),
    (English: 'Index out of bounds (%d)'; Localized: '인덱스가 범위를 벗어났습니다 (%d)'),
    (English: 'Bitmap image is not valid'; Localized: '비트맵 이미지가 잘못되었습니다'),
    (English: 'Icon image is not valid'; Localized: '아이콘 이미지가 잘못되었습니다'),
    (English: 'Metafile is not valid'; Localized: '메타파일이 잘못되었습니다'),
    (English: 'Invalid pixel format'; Localized: '잘못된 픽셀 형식'),
    (English: 'Invalid image'; Localized: '잘못된 이미지'),
    (English: 'Scan line index out of range'; Localized: '스캔 라인 인덱스가 범위를 벗어났습니다'),
    (English: 'Cannot change the size of an icon'; Localized: '아이콘의 크기는 변경할 수 없습니다'),
    (English: 'Cannot change the size of a WIC Image'; Localized: 'WIC 이미지의 크기는 변경할 수 없습니다'),
    (English: 'Unsupported clipboard format'; Localized: '지원되지 않는 클립보드 형식'),
    (English: 'Unsupported stream format'; Localized: '지원되지 않는 스트림 형식'),
    (English: 'Out of system resources'; Localized: '시스템 리소스가 부족합니다'),
    (English: 'Canvas does not allow drawing'; Localized: '캔버스에서 그리기가 허용되지 않습니다'),
    (English: 'Text format flag ''%s'' not supported'; Localized: '''%s'' 텍스트 형식 플래그는 지원되지 않습니다'),
    (English: 'Invalid image frame index %d: there are %d frames (0-%d)'; Localized: '잘못된 이미지 프레임 인덱스 %d: 프레임이 %d개 있습니다 (0-%d)'),
    (English: 'Invalid image size'; Localized: '잘못된 이미지 크기'),
    (English: 'Invalid ImageList'; Localized: '잘못된 ImageList'),
    (English: 'Invalid ImageList Index'; Localized: '잘못된 ImageList 인덱스'),
    (English: 'Failed to read ImageList data from stream'; Localized: '스트림에서 ImageList 데이터를 읽지 못했습니다'),
    (English: 'Failed to write ImageList data to stream'; Localized: '스트림에 ImageList 데이터를 쓰지 못했습니다'),
    (English: 'Error creating window device context'; Localized: '창 디바이스 컨텍스트를 만드는 동안 오류가 발생했습니다'),
    (English: 'Error creating window class'; Localized: '창 클래스를 만드는 동안 오류가 발생했습니다'),
    (English: 'Cannot focus a disabled or invisible window'; Localized: '사용할 수 없거나 보이지 않는 창에는 포커스를 설정할 수 없습니다'),
    (English: 'Control ''%s'' has no parent window'; Localized: '''%s'' 컨트롤에 부모 창이 없습니다'),
    (English: '. Path:'#13#10'%s'; Localized: '. 경로:'#13#10'%s'),
    (English: 'Parent given is not a parent of ''%s'''; Localized: '지정된 부모는 ''%s''의 부모가 아닙니다'),
    (English: 'Cannot hide an MDI Child Form'; Localized: 'MDI 자식 폼은 숨길 수 없습니다'),
    (English: 'Cannot change Visible in OnShow or OnHide'; Localized: 'OnShow 또는 OnHide에서는 Visible을 변경할 수 없습니다'),
    (English: 'Cannot make a visible window modal'; Localized: '표시되어 있는 창은 모달로 만들 수 없습니다'),
    (English: 'Scrollbar property out of range'; Localized: '스크롤 막대 속성이 범위를 벗어났습니다'),
    (English: '%s property out of range'; Localized: '%s 속성이 범위를 벗어났습니다'),
    (English: 'Check state can only be set when CheckBoxes is True'; Localized: '선택 상태는 CheckBoxes가 True인 경우에만 설정할 수 있습니다'),
    (English: 'Check state incompatible with treeview''s CheckStyles'; Localized: '트리 뷰의 CheckStyles와 호환되지 않는 선택 상태'),
    (English: 'Menu index out of range'; Localized: '메뉴 인덱스가 범위를 벗어났습니다'),
    (English: 'Menu inserted twice'; Localized: '메뉴가 두 번 삽입되었습니다'),
    (English: 'Sub-menu is not in menu'; Localized: '하위 메뉴가 메뉴에 없습니다'),
    (English: 'Not enough timers available'; Localized: '사용할 수 있는 타이머가 부족합니다'),
    (English: 'Printer index out of range'; Localized: '프린터 인덱스가 범위를 벗어났습니다'),
    (English: 'Printer selected is not valid'; Localized: '선택한 프린터가 잘못되었습니다'),
    (English: '%s on %s'; Localized: '%s (%s)'),
    (English: 'GroupIndex cannot be less than a previous menu item''s GroupIndex'; Localized: 'GroupIndex는 이전 메뉴 항목의 GroupIndex보다 작을 수 없습니다'),
    (English: 'Cannot create form. No MDI forms are currently active'; Localized: '폼을 만들 수 없습니다. 현재 활성 상태인 MDI 폼이 없습니다'),
    (English: 'Can only modify an image if it contains a bitmap'; Localized: '이미지는 비트맵이 포함되어 있는 경우에만 수정할 수 있습니다'),
    (English: 'A control cannot have itself as its parent'; Localized: '컨트롤은 자신을 부모로 가질 수 없습니다'),
    (English: 'Control ''%s'' is used on a not main thread'; Localized: '''%s'' 컨트롤이 주 스레드가 아닌 스레드에서 사용되고 있습니다'),
    (English: '&Yes'; Localized: '예(&Y)'),
    (English: '&No'; Localized: '아니요(&N)'),
    (English: '&Close'; Localized: '닫기(&C)'),
    (English: '&Ignore'; Localized: '무시(&I)'),
    (English: '&Retry'; Localized: '다시 시도(&R)'),
    (English: '&All'; Localized: '모두(&A)'),
    (English: 'Cannot drag a form'; Localized: '폼을 끌 수 없습니다'),
    (English: 'Metafiles'; Localized: '메타파일'),
    (English: 'Enhanced Metafiles'; Localized: '확장 메타파일'),
    (English: 'Icons'; Localized: '아이콘'),
    (English: 'Bitmaps'; Localized: '비트맵'),
    (English: 'TIFF Images'; Localized: 'TIFF 이미지'),
    (English: 'Warning'; Localized: '경고'),
    (English: 'Error'; Localized: '오류'),
    (English: 'Information'; Localized: '정보'),
    (English: 'Confirm'; Localized: '확인'),
    (English: '&Abort'; Localized: '중단(&A)'),
    (English: 'N&o to All'; Localized: '모두 아니요(&O)'),
    (English: 'Yes to &All'; Localized: '모두 예(&A)'),
    (English: 'BkSp'; Localized: 'BkSp'),
    (English: 'Tab'; Localized: 'Tab'),
    (English: 'Esc'; Localized: 'Esc'),
    (English: 'Enter'; Localized: 'Enter'),
    (English: 'Space'; Localized: 'Space'),
    (English: 'PgUp'; Localized: 'PgUp'),
    (English: 'PgDn'; Localized: 'PgDn'),
    (English: 'End'; Localized: 'End'),
    (English: 'Home'; Localized: 'Home'),
    (English: 'Left'; Localized: 'Left'),
    (English: 'Up'; Localized: 'Up'),
    (English: 'Right'; Localized: 'Right'),
    (English: 'Down'; Localized: 'Down'),
    (English: 'Ins'; Localized: 'Ins'),
    (English: 'Del'; Localized: 'Del'),
    (English: 'Value must be between %d and %d'; Localized: '값은 %d과(와) %d 사이여야 합니다'),
    (English: 'Unable to insert a line'; Localized: '줄을 삽입할 수 없습니다'),
    (English: 'Invalid clipboard format'; Localized: '잘못된 클립보드 형식'),
    (English: 'Clipboard does not support Icons'; Localized: '클립보드는 아이콘을 지원하지 않습니다'),
    (English: 'Cannot open clipboard: %s'; Localized: '클립보드를 열 수 없습니다: %s'),
    (English: 'Text exceeds memo capacity'; Localized: '텍스트가 Memo 컨트롤의 용량을 초과합니다'),
    (English: 'Operation not supported on selected printer'; Localized: '선택한 프린터에서는 작업이 지원되지 않습니다'),
    (English: 'There is no default printer currently selected'; Localized: '현재 선택된 기본 프린터가 없습니다'),
    (English: 'Menu ''%s'' is already being used by another form'; Localized: '''%s'' 메뉴는 다른 폼에서 이미 사용하고 있습니다'),
    (English: 'Other'; Localized: '기타'),
    (English: 'Docked control must have a name'; Localized: '도킹된 컨트롤에는 이름이 있어야 합니다'),
    (English: 'Error removing control from dock tree'; Localized: '도킹 트리에서 컨트롤을 제거하는 동안 오류가 발생했습니다'),
    (English: ' - Dock zone not found'; Localized: ' - 도킹 영역을 찾을 수 없습니다'),
    (English: ' - Dock zone has no control'; Localized: ' - 도킹 영역에 컨트롤이 없습니다'),
    (English: 'Error loading dock zone from the stream. Expecting version %d, but found %d.'; Localized: '스트림에서 도킹 영역을 로드하는 동안 오류가 발생했습니다. 버전 %d이(가) 필요하지만 %d을(를) 찾았습니다.'),
    (English: 'Multiselect mode must be on for this feature'; Localized: '이 기능을 사용하려면 다중 선택 모드가 켜져 있어야 합니다'),
    (English: 'Length of value array must be >= length of prompt array'; Localized: '값 배열의 길이는 프롬프트 배열의 길이 이상이어야 합니다'),
    (English: 'Prompt array must not be empty'; Localized: '프롬프트 배열은 비워 둘 수 없습니다'),
    (English: '&Username'; Localized: '사용자 이름(&U)'),
    (English: '&Password'; Localized: '암호(&P)'),
    (English: '&Domain'; Localized: '도메인(&D)'),
    (English: 'Login'; Localized: '로그인'),
    (English: 'Expand'; Localized: '확장'),
    (English: 'Separator'; Localized: '구분 기호'),
    (English: 'Error setting %s.Count'; Localized: '%s.Count를 설정하는 동안 오류가 발생했습니다'),
    (English: 'Listbox (%s) style must be virtual in order to set Count'; Localized: 'Count를 설정하려면 목록 상자 (%s) 스타일은 가상이어야 합니다'),
    (English: 'No OnGetItem event handler assigned'; Localized: '할당된 OnGetItem 이벤트 처리기가 없습니다'),
    (English: 'ANSI'; Localized: 'ANSI'),
    (English: 'ASCII'; Localized: 'ASCII'),
    (English: 'Unicode'; Localized: 'Unicode'),
    (English: 'Big Endian Unicode'; Localized: 'Big Endian Unicode'),
    (English: 'UTF-8'; Localized: 'UTF-8'),
    (English: 'UTF-7'; Localized: 'UTF-7'),
    (English: 'Cannot remove shell notification icon'; Localized: '셸 알림 아이콘을 제거할 수 없습니다'),
    (English: '%s requires Windows Vista or later'; Localized: '%s에는 Windows Vista 이상이 필요합니다'),
    (English: 'Button%d'; Localized: '단추 %d'),
    (English: 'RadioButton%d'; Localized: '라디오 단추 %d'),
    (English: 'Caption cannot be empty'; Localized: '텍스트는 비워 둘 수 없습니다'),
    (English: 'Invalid canvas operation'; Localized: '잘못된 캔버스 작업'),
    (English: '%s has no owner'; Localized: '%s에 소유자가 없습니다'),
    (English: 'Source and destination require the same owner'; Localized: '원본과 대상에는 같은 소유자가 필요합니다'),
    (English: '%s cannot be owned by a different canvas'; Localized: '%s은(는) 다른 캔버스가 소유할 수 없습니다'),
    (English: 'Not a solid color brush'; Localized: '단색 브러시가 아닙니다'),
    (English: 'Invalid brush style'; Localized: '잘못된 브러시 스타일'),
    (English: 'Unable to load style ''%s'''; Localized: '''%s'' 스타일을 로드할 수 없습니다'),
    (English: 'Unable to load styles: %s'; Localized: '스타일을 로드할 수 없습니다: %s'),
    (English: 'Style ''%s'' already registered'; Localized: '''%s'' 스타일이 이미 등록되어 있습니다'),
    (English: 'Style class ''%s'' already registered'; Localized: '''%s'' 스타일 클래스가 이미 등록되어 있습니다'),
    (English: 'Style ''%s'' not found'; Localized: '''%s'' 스타일을 찾을 수 없습니다'),
    (English: 'Style class ''%s'' not found'; Localized: '''%s'' 스타일 클래스를 찾을 수 없습니다'),
    (English: 'Invalid style format'; Localized: '잘못된 스타일 형식'),
    (English: 'VCL Style File'; Localized: 'VCL 스타일 파일'),
    (English: 'Class ''%s'' is already registered for ''%s'''; Localized: '''%s'' 클래스가 ''%s''에 대해 이미 등록되어 있습니다'),
    (English: 'Class ''%s'' is not registered for ''%s'''; Localized: '''%s'' 클래스가 ''%s''에 대해 등록되어 있지 않습니다'),
    (English: '%s parameter cannot be nil'; Localized: '%s 매개 변수는 nil일 수 없습니다'),
    (English: 'A StyleHook class has not been registered for %s'; Localized: '%s에 대해 StyleHook 클래스가 등록되지 않았습니다'),
    (English: 'Feature not supported by this style'; Localized: '이 스타일에서 지원되지 않는 기능입니다'),
    (English: 'Cannot call BeginInvoke on a control with no parent or window handle'; Localized: '부모 또는 창 핸들이 없는 컨트롤에서는 BeginInvoke를 호출할 수 없습니다'),
    (English: 'CardPanel card index is out of range'; Localized: 'CardPanel 카드 인덱스가 범위를 벗어났습니다'),
    (English: 'CardPanel.ActiveCard cannot be nil'; Localized: 'CardPanel.ActiveCard는 nil일 수 없습니다'),
    (English: 'Invalid index'; Localized: '잘못된 인덱스'),
    (English: 'Unable to insert an item'; Localized: '항목을 삽입할 수 없습니다'),
    (English: 'Invalid owner'; Localized: '잘못된 소유자'),
    (English: 'RichEdit line insertion error'; Localized: 'RichEdit 줄 삽입 오류'),
    (English: 'Failed to Load Stream'; Localized: '스트림을 로드하지 못했습니다'),
    (English: 'Failed to Save Stream'; Localized: '스트림을 저장하지 못했습니다'),
    (English: '%s is already associated with %s'; Localized: '%s이(가) %s과(와) 이미 연결되어 있습니다'),
    (English: 'This control requires version 4.70 or greater of COMCTL32.DLL'; Localized: '이 컨트롤에는 COMCTL32.DLL 버전 4.70 이상이 필요합니다'),
    (English: 'ListView item can be added only when OwnerData is False.  Use OnData instead.'; Localized: 'ListView 항목은 OwnerData가 False인 경우에만 추가할 수 있습니다.  대신 OnData를 사용하세요.'),
    (English: 'This "Portable Network Graphics" image is not valid because it contains invalid pieces of data (crc error)'; Localized: '이 "Portable Network Graphics" 이미지는 잘못된 데이터 조각이 포함되어 있으므로 잘못되었습니다 (crc 오류)'),
    (English: 'The "Portable Network Graphics" image could not be loaded because one of its main piece of data (ihdr) might be corrupted'; Localized: '주요 데이터 조각 (ihdr) 중 하나가 손상되었을 수 있으므로 "Portable Network Graphics" 이미지를 로드할 수 없습니다'),
    (English: 'This "Portable Network Graphics" image is invalid because it has missing image parts.'; Localized: '이 "Portable Network Graphics" 이미지는 누락된 이미지 부분이 있으므로 잘못되었습니다.'),
    (English: 'Could not decompress the image because it contains invalid compressed data.'#13#10' Description: '; Localized: '잘못된 압축 데이터가 포함되어 있으므로 이미지의 압축을 풀 수 없습니다.'#13#10' 설명: '),
    (English: 'The "Portable Network Graphics" image contains an invalid palette.'; Localized: '"Portable Network Graphics" 이미지에 잘못된 팔레트가 포함되어 있습니다.'),
    (English: 'The file being read is not a valid "Portable Network Graphics" image because it contains an invalid header. This file may be corrupted, try obtaining it again'; Localized: '읽고 있는 파일에 잘못된 헤더가 포함되어 있으므로 올바른 "Portable Network Graphics" 이미지가 아닙니다. 이 파일은 손상되었을 수 있으니 다시 가져오세요'),
    (English: 'This "Portable Network Graphics" image is not supported or it might be invalid.'#13#10'(IHDR chunk is not the first)'; Localized: '이 "Portable Network Graphics" 이미지는 지원되지 않거나 잘못되었을 수 있습니다.'#13#10'(IHDR 청크가 첫 번째가 아님)'),
    (English: 'This "Portable Network Graphics" image is not supported because either its width or height exceeds the maximum size of 65535 pixels.'; Localized: '이 "Portable Network Graphics" 이미지는 너비 또는 높이가 최대 크기인 65535픽셀을 초과하므로 지원되지 않습니다.'),
    (English: 'There is no such palette entry.'; Localized: '해당 팔레트 항목이 없습니다.'),
    (English: 'This "Portable Network Graphics" image contains an unknown critical part which could not be decoded.'; Localized: '이 "Portable Network Graphics" 이미지에는 디코딩할 수 없는 알 수 없는 중요 부분이 포함되어 있습니다.'),
    (English: 'This "Portable Network Graphics" image is encoded with an unknown compression scheme which could not be decoded.'; Localized: '이 "Portable Network Graphics" 이미지는 디코딩할 수 없는 알 수 없는 압축 방식으로 인코딩되어 있습니다.'),
    (English: 'This "Portable Network Graphics" image uses an unknown interlace scheme which could not be decoded.'; Localized: '이 "Portable Network Graphics" 이미지는 디코딩할 수 없는 알 수 없는 인터레이스 방식을 사용합니다.'),
    (English: 'This "Portable Network Graphics" image uses an unknown color type which could not be decoded.'; Localized: '이 "Portable Network Graphics" 이미지는 디코딩할 수 없는 알 수 없는 색 유형을 사용합니다.'),
    (English: 'The chunks must be compatible to be assigned.'; Localized: '청크를 할당하려면 서로 호환되어야 합니다.'),
    (English: 'This "Portable Network Graphics" image is invalid because the decoder found an unexpected end of the file.'; Localized: '이 "Portable Network Graphics" 이미지는 디코더가 예기치 않은 파일 끝을 발견했으므로 잘못되었습니다.'),
    (English: 'This "Portable Network Graphics" image contains no data.'; Localized: '이 "Portable Network Graphics" 이미지에는 데이터가 없습니다.'),
    (English: 'The program tried to add a existent critical chunk to the current image which is not allowed.'; Localized: '프로그램이 현재 이미지에 이미 존재하는 중요 청크를 추가하려고 했으며 이는 허용되지 않습니다.'),
    (English: 'It''s not allowed to add a new chunk because the current image is invalid.'; Localized: '현재 이미지가 잘못되었으므로 새 청크를 추가하는 것은 허용되지 않습니다.'),
    (English: 'Some operation could not be performed because the system is out of resources. Close some windows and try again.'; Localized: '시스템 리소스가 부족하므로 작업을 수행할 수 없습니다. 일부 창을 닫고 다시 시도하세요.'),
    (English: 'Setting bit transparency color is not allowed for png images containing alpha value for each pixel (COLOR_RGBALPHA and COLOR_GRAYSCALEALPHA)'; Localized: '각 픽셀에 대한 알파 값이 포함된 png 이미지에는 비트 투명 색 설정이 허용되지 않습니다 (COLOR_RGBALPHA 및 COLOR_GRAYSCALEALPHA)'),
    (English: 'This operation is not valid because the current image contains no valid header.'; Localized: '현재 이미지에 올바른 헤더가 없으므로 이 작업은 잘못되었습니다.'),
    (English: 'The new size provided for image resizing is invalid.'; Localized: '이미지 크기 조정을 위해 제공된 새 크기가 잘못되었습니다.'),
    (English: 'The "Portable Network Graphics" image could not be loaded because it uses an invalid image bit depth.'; Localized: '"Portable Network Graphics" 이미지가 잘못된 이미지 비트 심도를 사용하므로 로드할 수 없습니다.'),
    (English: 'Exception '; Localized: '예외 '),
    (English: 'Data cannot be accessed as %s'; Localized: '데이터를 %s(으)로 액세스할 수 없습니다'),
    (English: 'Check'; Localized: '선택'),
    (English: 'Uncheck'; Localized: '선택 취소'),
    (English: 'Collapse'; Localized: '축소'),
    (English: 'Obsolete'; Localized: '사용되지 않음'),
    (English: 'Custom Messages'; Localized: '사용자 지정 메시지'),
    (English: 'Language Options'; Localized: '언어 옵션'),
    (English: 'Messages'; Localized: '메시지'),
    (English: 'Component'; Localized: '구성 요소'),
    (English: 'Directory'; Localized: '폴더'),
    (English: 'File'; Localized: '파일'),
    (English: 'Icon'; Localized: '아이콘'),
    (English: 'INI'; Localized: 'INI'),
    (English: 'Delete'; Localized: '삭제'),
    (English: 'ISSig Key'; Localized: 'ISSig 키'),
    (English: 'Language'; Localized: '언어'),
    (English: 'Registry'; Localized: '레지스트리'),
    (English: 'Task'; Localized: '작업'),
    (English: 'Type'; Localized: '유형'),
    (English: 'Appearance'; Localized: '모양'),
    (English: 'Application Details'; Localized: '응용 프로그램 세부 정보'),
    (English: 'Application Directory'; Localized: '응용 프로그램 폴더'),
    (English: 'Applications in Use'; Localized: '사용 중인 응용 프로그램'),
    (English: 'Compression'; Localized: '압축'),
    (English: 'Disk Spanning'; Localized: '디스크 분할'),
    (English: 'Installation Pages'; Localized: '설치 페이지'),
    (English: 'Security'; Localized: '보안'),
    (English: 'Start Menu Folder'; Localized: '시작 메뉴 폴더'),
    (English: 'System Requirements'; Localized: '시스템 요구 사항'),
    (English: 'Uninstallation'; Localized: '제거'),
    (English: 'User Information'; Localized: '사용자 정보'),
    (English: 'Version Information'; Localized: '버전 정보'),
    (English: 'Common'; Localized: '일반'));

implementation

end.
