unit IDE.LocalizeFunc.German;

{
  Inno Setup
  Copyright (C) 1997-2026 Jordan Russell
  Portions by Martijn Laan
  For conditions of distribution and use, see LICENSE.TXT.

  Compiler IDE German translations
}

interface

uses
  IDE.LocalizeFunc;

const
  GermanIDETranslations: array [0..500] of TTranslationPair = (
    (English: 'Command line usage:'; Localized: 'Befehlszeilenverwendung:'),
    (English: 'Examples:'; Localized: 'Beispiele:'),
    (English: 'script file'; Localized: 'Skriptdatei'),
    (English: 'wizard name'; Localized: 'Assistentenname'),
    (English: 'My script'; Localized: 'Mein Skript'),
    (English: 'My Script Wizard'; Localized: 'Mein Skript-Assistent'),
    (English: 'Could not load %1: %2'; Localized: '%1 konnte nicht geladen werden: %2'),
    (English: 'Inno Setup Compiler'; Localized: 'Inno Setup Compiler'),
    (English: 'Example scripts...'; Localized: 'Beispielskripte...'),
    (English: 'More files...'; Localized: 'Weitere Dateien...'),
    (English: 'Untitled'; Localized: 'Unbenannt'),
    (English: 'Preprocessor Output'; Localized: 'Präprozessor-Ausgabe'),
    (English: 'Run Parameters'; Localized: 'Ausführungsparameter'),
    (English: 'Command line parameters for %1 and %2:'; Localized: 'Befehlszeilenparameter für %1 und %2:'),
    (English: 'Inno Setup Script files'; Localized: 'Inno Setup-Skriptdateien'),
    (English: 'All files'; Localized: 'Alle Dateien'),
    (English: 'Application files'; Localized: 'Anwendungsdateien'),
    (English: 'Documentation files'; Localized: 'Dokumentationsdateien'),
    (English: 'Registry files'; Localized: 'Registry-Dateien'),
    (English: 'Icon files'; Localized: 'Symboldateien'),
    (English: 'Inno Setup Script Wizard'; Localized: 'Inno Setup Skript-Assistent'),
    (English: 'Welcome'; Localized: 'Willkommen'),
    (English: 'Application Information'; Localized: 'Anwendungsinformationen'),
    (English: 'Please specify some basic information about your application.'; Localized: 'Bitte geben Sie einige grundlegende Informationen zu Ihrer Anwendung an.'),
    (English: 'Application Folder'; Localized: 'Anwendungsordner'),
    (English: 'Please specify folder information about your application.'; Localized: 'Bitte geben Sie Ordnerinformationen zu Ihrer Anwendung an.'),
    (English: 'Application Files'; Localized: 'Anwendungsdateien'),
    (English: 'Please specify the files that are part of your application.'; Localized: 'Bitte geben Sie die Dateien an, die Teil Ihrer Anwendung sind.'),
    (English: 'Please specify the source folder.'; Localized: 'Bitte geben Sie den Quellordner an.'),
    (English: 'Should files in subfolders of "%1" also be included?'; Localized: 'Sollen auch Dateien in Unterordnern von "%1" einbezogen werden?'),
    (English: 'URL:'; Localized: 'URL:'),
    (English: 'Is the file to download an archive which should be extracted?'; Localized: 'Ist die herunterzuladende Datei ein Archiv, das entpackt werden soll?'),
    (English: 'Name of the file:'; Localized: 'Name der Datei:'),
    (English: 'Name of the file (extension should match archive format):'; Localized: 'Name der Datei (Dateierweiterung sollte zum Archivformat passen):'),
    (English: 'Approximate size of the file in megabytes:'; Localized: 'Ungefähre Größe der Datei in Megabyte:'),
    (English: 'Application File Association'; Localized: 'Anwendungsdateizuordnung'),
    (English: 'Please specify which file association should be created for your application.'; Localized: 'Bitte geben Sie an, welche Dateizuordnung für Ihre Anwendung erstellt werden soll.'),
    (English: '%1 File'; Localized: '%1-Datei'),
    (English: 'Application Shortcuts'; Localized: 'Anwendungsverknüpfungen'),
    (English: 'Please specify which shortcuts should be created for your application.'; Localized: 'Bitte geben Sie an, welche Verknüpfungen für Ihre Anwendung erstellt werden sollen.'),
    (English: 'Application Documentation'; Localized: 'Anwendungsdokumentation'),
    (English: 'Please specify which documentation files should be shown by Setup during installation.'; Localized: 'Bitte geben Sie an, welche Dokumentationsdateien von Setup während der Installation angezeigt werden sollen.'),
    (English: 'Setup Install Mode'; Localized: 'Setup-Installationsmodus'),
    (English: 'Please specify in which install mode Setup should run.'; Localized: 'Bitte geben Sie an, in welchem Installationsmodus Setup ausgeführt werden soll.'),
    (English: 'Application Registry Keys And Values'; Localized: 'Registry-Schlüssel und -Werte der Anwendung'),
    (English: 'Please specify the registry keys and values that are part of your application.'; Localized: 'Bitte geben Sie die Registry-Schlüssel und -Werte an, die Teil Ihrer Anwendung sind.'),
    (English: 'Setup Languages'; Localized: 'Setup-Sprachen'),
    (English: 'Please specify which Setup languages should be included.'; Localized: 'Bitte geben Sie an, welche Setup-Sprachen einbezogen werden sollen.'),
    (English: 'Compiler Settings'; Localized: 'Compiler-Einstellungen'),
    (English: 'Please specify some basic compiler settings.'; Localized: 'Bitte geben Sie einige grundlegende Compiler-Einstellungen an.'),
    (English: 'Please specify the folder.'; Localized: 'Bitte geben Sie den Ordner an.'),
    (English: 'Wizard Style'; Localized: 'Assistentenstil'),
    (English: 'Please specify which wizard style should be used.'; Localized: 'Bitte geben Sie an, welcher Assistentenstil verwendet werden soll.'),
    (English: 'Inno Setup Preprocessor'; Localized: 'Inno Setup-Präprozessor'),
    (English: 'Please specify whether Inno Setup Preprocessor should be used.'; Localized: 'Bitte geben Sie an, ob der Inno Setup-Präprozessor verwendet werden soll.'),
    (English: 'The %1 can use %2 compiler directives to simplify your script. Although this is not necessary, it will make it easier to manually change the script later.%n%nDo you want the %1 to use %2 compiler directives?'; Localized: 'Der %1 kann %2-Compilerdirektiven verwenden, um Ihr Skript zu vereinfachen. Obwohl dies nicht notwendig ist, erleichtert es spätere manuelle Änderungen am Skript.%n%nMöchten Sie, dass der %1 %2-Compilerdirektiven verwendet?'),
    (English: '&Yes, use %1 compiler directives'; Localized: '&Ja, %1-Compilerdirektiven verwenden'),
    (English: 'Finished'; Localized: 'Fertiggestellt'),
    (English: '&Next'; Localized: '&Weiter'),
    (English: '&Finish'; Localized: '&Fertigstellen'),
    (English: 'The %1 is not complete. If you quit now, the new script file will not be generated.%n%nExit anyway?'; Localized: 'Der %1 ist nicht vollständig. Wenn Sie jetzt beenden, wird die neue Skriptdatei nicht generiert.%n%nTrotzdem beenden?'),
    (English: 'Please specify the application name.'; Localized: 'Bitte geben Sie den Anwendungsnamen an.'),
    (English: 'Please specify the application version.'; Localized: 'Bitte geben Sie die Anwendungsversion an.'),
    (English: 'Please specify the application destination base folder.'; Localized: 'Bitte geben Sie den Ziel-Basisordner der Anwendung an.'),
    (English: 'Please specify the application folder name.'; Localized: 'Bitte geben Sie den Namen des Anwendungsordners an.'),
    (English: 'Please specify the application main executable file.'; Localized: 'Bitte geben Sie die ausführbare Hauptdatei der Anwendung an.'),
    (English: 'Please specify the application Start Menu group name.'; Localized: 'Bitte geben Sie den Namen des Startmenüordners der Anwendung an.'),
    (English: 'Please specify the destination base folder.'; Localized: 'Bitte geben Sie den Ziel-Basisordner an.'),
    (English: 'Please specify a destination base folder other than the application folder'; Localized: 'Bitte geben Sie einen anderen Ziel-Basisordner als den Anwendungsordner an'),
    (English: 'Please select at least one language.'; Localized: 'Bitte wählen Sie mindestens eine Sprache aus.'),
    (English: '&Source URL:'; Localized: '&Quell-URL:'),
    (English: 'Script generated by the %1.'; Localized: 'Der %1 hat dieses Skript generiert.'),
    (English: 'SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!'; Localized: 'EINZELHEITEN ZUM ERSTELLEN VON INNO SETUP-SKRIPTDATEIEN FINDEN SIE IN DER DOKUMENTATION!'),
    (English: 'NOTE: The value of %1 uniquely identifies this application. Do not use the same %1 value in installers for other applications.'; Localized: 'HINWEIS: Der Wert von %1 identifiziert diese Anwendung eindeutig. Verwenden Sie denselben %1-Wert nicht in Installationsprogrammen für andere Anwendungen.'),
    (English: '(To generate a new GUID, click Tools | Generate GUID inside the IDE.)'; Localized: '(Um eine neue GUID zu generieren, klicken Sie in der IDE auf Extras | GUID generieren.)'),
    (English: '"%1" specifies that Setup cannot run on anything but x64 and Windows 11 on Arm.'; Localized: '"%1" gibt an, dass Setup nur unter x64 und Windows 11 auf Arm ausgeführt werden kann.'),
    (English: '"%1" requests that the install be done in "64-bit mode" on x64 or Windows 11 on Arm.'; Localized: '"%1" fordert, dass die Installation im "64-Bit-Modus" unter x64 oder Windows 11 auf Arm durchgeführt wird.'),
    (English: 'This means it should use the native 64-bit Program Files directory and the 64-bit view of the registry.'; Localized: 'Das bedeutet, dass der native 64-Bit-Ordner "Program Files" und die 64-Bit-Ansicht der Registry verwendet werden sollen.'),
    (English: 'Uncomment the following line to use a 64-bit installer.'; Localized: 'Entfernen Sie das Kommentarzeichen der folgenden Zeile, um ein 64-Bit-Installationsprogramm zu verwenden.'),
    (English: 'Use "%1" if all your archives are .%2 files.'; Localized: 'Verwenden Sie "%1", wenn alle Ihre Archive .%2-Dateien sind.'),
    (English: 'Use "%1" if all your archives are not password-protected.'; Localized: 'Verwenden Sie "%1", wenn keines Ihrer Archive passwortgeschützt ist.'),
    (English: 'Uncomment the following line to run in non administrative install mode (install for current user only).'; Localized: 'Entfernen Sie das Kommentarzeichen der folgenden Zeile, um im nicht administrativen Installationsmodus auszuführen (Installation nur für aktuellen Benutzer).'),
    (English: 'Remove the following line to run in administrative install mode (install for all users).'; Localized: 'Entfernen Sie die folgende Zeile, um im administrativen Installationsmodus auszuführen (Installation für alle Benutzer).'),
    (English: 'NOTE: Don''t use "%1" on any shared system files.'; Localized: 'HINWEIS: Verwenden Sie "%1" nicht für gemeinsam genutzte Systemdateien.'),
    (English: 'NOTE: Use the "%1" flag or the "%2" parameter to verify downloads.'; Localized: 'HINWEIS: Verwenden Sie das Flag "%1" oder den Parameter "%2", um Downloads zu verifizieren.'),
    (English: 'Registry data from file %1'; Localized: 'Registry-Daten aus Datei %1'),
    (English: 'COULD NOT IMPORT %1'; Localized: 'KONNTE %1 NICHT IMPORTIEREN'),
    (English: 'End of registry data from file %1'; Localized: 'Ende der Registry-Daten aus Datei %1'),
    (English: 'SOME KEYS FILTERED DUE TO %1 SETTINGS!'; Localized: 'EINIGE SCHLÜSSEL WURDEN AUFGRUND DER %1-EINSTELLUNGEN GEFILTERT!'),
    (English: 'SOME VALUES WITH UNSUPPORTED TYPES SKIPPED!'; Localized: 'EINIGE WERTE MIT NICHT UNTERSTÜTZTEN TYPEN WURDEN ÜBERSPRUNGEN!'),
    (English: 'Would you like to compile the new script now?'; Localized: 'Möchten Sie das neue Skript jetzt kompilieren?'),
    (English: 'My Program'; Localized: 'Mein Programm'),
    (English: 'My Company, Inc.'; Localized: 'My Company, Inc.'),
    (English: 'Application directory'; Localized: 'Anwendungsordner'),
    (English: 'Program Files directory'; Localized: 'Program Files-Ordner'),
    (English: 'Common Files directory'; Localized: 'Common Files-Ordner'),
    (English: 'Windows directory'; Localized: 'Windows-Ordner'),
    (English: 'Windows system directory'; Localized: 'Windows-Systemordner'),
    (English: 'Setup source directory'; Localized: 'Setup-Quellordner'),
    (English: 'System drive root directory'; Localized: 'Stammordner des Systemlaufwerks'),
    (English: '(Custom)'; Localized: '(Benutzerdefiniert)'),
    (English: 'Starting compile.%1[%2]'; Localized: 'Kompilierung wird gestartet.%1[%2]'),
    (English: 'Finished.%1[%2, %3 elapsed]'; Localized: 'Fertig.%1[%2, %3 vergangen]'),
    (English: 'Compile aborted.'; Localized: 'Kompilierung abgebrochen.'),
    (English: 'Log size limit reached, list reset.'; Localized: 'Maximale Protokollgröße erreicht, Liste zurückgesetzt.'),
    (English: '%1 started'; Localized: '%1 gestartet'),
    (English: 'Terminating process'; Localized: 'Prozess wird beendet'),
    (English: 'Removing left-over temporary directory: %1'; Localized: 'Übrig gebliebener temporärer Ordner wird entfernt: %1'),
    (English: 'Failed to remove temporary directory'; Localized: 'Temporärer Ordner konnte nicht entfernt werden'),
    (English: '%1 Call Stack'; Localized: '%1-Aufrufliste'),
    (English: 'Cannot run Setup at this time. Please compile Setup successfully to completion first, with output enabled'; Localized: 'Setup kann derzeit nicht ausgeführt werden. Bitte kompilieren Sie Setup zuerst vollständig und erfolgreich, mit aktivierter Ausgabe'),
    (English: 'Cannot run Uninstall at this time. Please run Setup successfully to completion first'; Localized: 'Deinstallation kann derzeit nicht ausgeführt werden. Bitte führen Sie Setup zuerst vollständig und erfolgreich aus'),
    (English: 'Error executing "%1":%n%n%2: %3'; Localized: 'Fehler beim Ausführen von "%1":%n%n%2: %3'),
    (English: 'Are you sure you want to abort the compile?'; Localized: 'Möchten Sie die Kompilierung wirklich abbrechen?'),
    (English: 'File %1:'; Localized: 'Datei %1:'),
    (English: 'Line %1:'; Localized: 'Zeile %1:'),
    (English: 'Compiler Error'; Localized: 'Compiler-Fehler'),
    (English: 'Illegal null character on line %1'; Localized: 'Ungültiges Nullzeichen in Zeile %1'),
    (English: 'Cannot find "%1"'; Localized: '"%1" kann nicht gefunden werden'),
    (English: 'Invalid regular expression "%1"'; Localized: 'Ungültiger regulärer Ausdruck "%1"'),
    (English: '%1 (%2 hits):'; Localized: '%1 (%2 Treffer):'),
    (English: 'Find "%1" (%2 hits in %3 files)'; Localized: 'Suche nach "%1" (%2 Treffer in %3 Dateien)'),
    (English: '%1 occurrence(s) replaced.'; Localized: '%1 Vorkommen ersetzt.'),
    (English: 'The .%1 extension was successfully associated for the current user with:%n%2'; Localized: 'Die Dateierweiterung .%1 wurde erfolgreich für den aktuellen Benutzer dem folgenden Programm zugeordnet:%n%2'),
    (English: 'The .%1 extension was successfully associated for all users with:%n%2'; Localized: 'Die Dateierweiterung .%1 wurde erfolgreich für alle Benutzer dem folgenden Programm zugeordnet:%n%2'),
    (English: 'Error creating file association:%n%1 - %2'; Localized: 'Fehler beim Erstellen der Dateizuordnung:%n%1 - %2'),
    (English: 'Unable to associate for all users without administrative privileges. Do you want to associate only for yourself instead?'; Localized: 'Eine Zuordnung für alle Benutzer ist ohne Administratorrechte nicht möglich. Möchten Sie die Zuordnung stattdessen nur für sich selbst vornehmen?'),
    (English: 'Associate'; Localized: 'Zuordnen'),
    (English: 'Inno Setup Script'; Localized: 'Inno Setup-Skript'),
    (English: 'Compi&le'; Localized: '&Kompilieren'),
    (English: '&Script has %1'; Localized: '&Skript enthält %1'),
    (English: 'Script has %1 set'; Localized: 'Im Skript ist %1 gesetzt'),
    (English: 'Invalid file format.'; Localized: 'Ungültiges Dateiformat.'),
    (English: 'Setup'; Localized: 'Setup'),
    (English: 'Your message text.'; Localized: 'Ihr Meldungstext.'),
    (English: 'Enter your text here...'; Localized: 'Geben Sie hier Ihren Text ein...'),
    (English: 'Return values'; Localized: 'Rückgabewerte'),
    (English: 'Default'; Localized: 'Standard'),
    (English: 'Shield'; Localized: 'Schild'),
    (English: 'Instruction Text'; Localized: 'Anweisungstext'),
    (English: 'Message Text'; Localized: 'Meldungstext'),
    (English: 'user clicked %1'; Localized: 'Benutzer hat auf %1 geklickt'),
    (English: 'OK'; Localized: 'OK'),
    (English: 'Yes'; Localized: 'Ja'),
    (English: 'No'; Localized: 'Nein'),
    (English: 'Cancel'; Localized: 'Abbrechen'),
    (English: 'Retry'; Localized: 'Wiederholen'),
    (English: 'Ignore'; Localized: 'Ignorieren'),
    (English: 'Abort'; Localized: 'Abbrechen'),
    (English: 'Display a message box'; Localized: 'Ein Meldungsfeld anzeigen'),
    (English: 'Name of the Sign Tool:'; Localized: 'Name des Signaturtools:'),
    (English: 'Invalid name.'; Localized: 'Ungültiger Name.'),
    (English: 'Duplicate name.'; Localized: 'Doppelter Name.'),
    (English: 'Command of the Sign Tool:'; Localized: 'Befehl des Signaturtools:'),
    (English: 'Invalid command.'; Localized: 'Ungültiger Befehl.'),
    (English: 'The generated GUID will be inserted into the editor at the cursor position. Continue?'; Localized: 'Die generierte GUID wird an der Cursorposition in den Editor eingefügt. Fortfahren?'),
    (English: 'The generated Pascal script will be inserted into the editor at the cursor position, but the cursor is not in the %1 section. Continue anyway?'; Localized: 'Das generierte Pascal-Skript wird an der Cursorposition in den Editor eingefügt, aber der Cursor befindet sich nicht im Abschnitt %1. Trotzdem fortfahren?'),
    (English: 'Classic'; Localized: 'Klassisch'),
    (English: 'Visual Studio / Visual Studio Code'; Localized: 'Visual Studio / Visual Studio Code'),
    (English: 'Classic / Visual Studio'; Localized: 'Klassisch / Visual Studio'),
    (English: 'Visual Studio Code'; Localized: 'Visual Studio Code'),
    (English: 'Light'; Localized: 'Hell'),
    (English: 'Dark'; Localized: 'Dunkel'),
    (English: 'The new language will take effect the next time you start Inno Setup Compiler.'; Localized: 'Die neue Sprache wird beim nächsten Start von Inno Setup Compiler wirksam.'),
    (English: '&New...'; Localized: '&Neu...'),
    (English: '&New'; Localized: '&Neu'),
    (English: 'Line %1'; Localized: 'Zeile %1'),
    (English: '%1: %2'; Localized: '%1: %2'),
    (English: 'Back (%1)'; Localized: 'Zurück (%1)'),
    (English: 'Forward (%1)'; Localized: 'Vorwärts (%1)'),
    (English: 'Ctrl+'; Localized: 'Strg+'),
    (English: 'Shift+'; Localized: 'Umschalt+'),
    (English: 'Alt+'; Localized: 'Alt+'),
    (English: 'Num %1'; Localized: 'Num %1'),
    (English: '(32-bit)'; Localized: '(32-Bit)'),
    (English: '[Compiling]'; Localized: '[Wird kompiliert]'),
    (English: '[Running]'; Localized: '[Wird ausgeführt]'),
    (English: '[Paused]'; Localized: '[Angehalten]'),
    (English: 'Read only'; Localized: 'Schreibgeschützt'),
    (English: 'Modified'; Localized: 'Geändert'),
    (English: 'Overwrite'; Localized: 'Überschreiben'),
    (English: 'Insert'; Localized: 'Einfügen'),
    (English: 'Tabs closed: %1'; Localized: 'Geschlossene Registerkarten: %1'),
    (English: 'Estimated time remaining: %1'; Localized: 'Geschätzte verbleibende Zeit: %1'),
    (English: 'Average KB/sec: %1'; Localized: 'Durchschnittliche KB/s: %1'),
    (English: 'There was an error opening the file. Remove it from the list?'; Localized: 'Beim Öffnen der Datei ist ein Fehler aufgetreten. Aus der Liste entfernen?'),
    (English: 'The text in the %1 file has changed.%n%nDo you want to save the changes?'; Localized: 'Der Text in der Datei %1 wurde geändert.%n%nMöchten Sie die Änderungen speichern?'),
    (English: 'Please stop the compile process before performing this command.'; Localized: 'Bitte stoppen Sie den Kompiliervorgang, bevor Sie diesen Befehl ausführen.'),
    (English: 'A compile is already in progress.'; Localized: 'Eine Kompilierung wird bereits ausgeführt.'),
    (English: 'The text in the %1 file has changed and must be saved before compiling.%n%nSave the changes and continue?'; Localized: 'Der Text in der Datei %1 wurde geändert und muss vor dem Kompilieren gespeichert werden.%n%nÄnderungen speichern und fortfahren?'),
    (English: 'Would you like to save the script before compiling?%n%nIf you answer No, the compiled installation will be placed under your My Documents folder by default.'; Localized: 'Möchten Sie das Skript vor dem Kompilieren speichern?%n%nWenn Sie mit Nein antworten, wird die kompilierte Installation standardmäßig in Ihrem Ordner "Eigene Dokumente" abgelegt.'),
    (English: 'The selected file is an %1 file. Go to its tab instead of opening it as the new main file?'; Localized: 'Die ausgewählte Datei ist eine %1-Datei. Zu ihrer Registerkarte wechseln, anstatt sie als neue Hauptdatei zu öffnen?'),
    (English: 'The selected file is not available as a tab. Opening as the new main file instead.'; Localized: 'Die ausgewählte Datei ist nicht als Registerkarte verfügbar. Sie wird stattdessen als neue Hauptdatei geöffnet.'),
    (English: 'Error creating file (code %1). Could not save file'; Localized: 'Fehler beim Erstellen der Datei (Code %1). Datei konnte nicht gespeichert werden'),
    (English: 'Error creating backup file. Could not save file'; Localized: 'Fehler beim Erstellen der Sicherungsdatei. Datei konnte nicht gespeichert werden'),
    (English: 'Error removing existing file (code %1). Could not save file'; Localized: 'Fehler beim Entfernen der vorhandenen Datei (Code %1). Datei konnte nicht gespeichert werden'),
    (English: 'Error renaming temporary file (code %1). Could not save file'; Localized: 'Fehler beim Umbenennen der temporären Datei (Code %1). Datei konnte nicht gespeichert werden'),
    (English: 'Failed to open included file: %1'; Localized: 'Eingebundene Datei konnte nicht geöffnet werden: %1'),
    (English: 'Cannot start printer document.'; Localized: 'Druckdokument kann nicht gestartet werden.'),
    (English: 'Are you sure you want to clear the list of recently opened files?'; Localized: 'Möchten Sie die Liste der zuletzt geöffneten Dateien wirklich löschen?'),
    (English: 'The %1 file has been modified outside of the source editor. You might want to reload it.'; Localized: 'Die Datei %1 wurde außerhalb des Quelltexteditors geändert. Sie sollten sie möglicherweise neu laden.'),
    (English: 'The %1 file has been modified outside of the source editor.%n%nDo you want to reload the file?'; Localized: 'Die Datei %1 wurde außerhalb des Quelltexteditors geändert.%n%nMöchten Sie die Datei neu laden?'),
    (English: 'The %1 file has been modified outside of the source editor. Changes have also been made in the source editor.%n%nDo you want to reload the file and lose the changes made in the source editor?'; Localized: 'Die Datei %1 wurde außerhalb des Quelltexteditors geändert. Es wurden auch Änderungen im Quelltexteditor vorgenommen.%n%nMöchten Sie die Datei neu laden und die im Quelltexteditor vorgenommenen Änderungen verwerfen?'),
    (English: 'File not opened.'; Localized: 'Datei nicht geöffnet.'),
    (English: 'Go to Line'; Localized: 'Gehe zu Zeile'),
    (English: 'Line number:'; Localized: 'Zeilennummer:'),
    (English: 'Do you want to copy your current license key to the clipboard before opening our order page? You will need it to be able to renew it.'; Localized: 'Möchten Sie Ihren aktuellen Lizenzschlüssel in die Zwischenablage kopieren, bevor Sie unsere Bestellseite öffnen? Sie benötigen ihn, um ihn verlängern zu können.'),
    (English: 'New commercial license key has been registered:%n%n%1%n%nThanks for your support!'; Localized: 'Neuer kommerzieller Lizenzschlüssel wurde registriert:%n%n%1%n%nVielen Dank für Ihre Unterstützung!'),
    (English: 'Are you sure you want to remove your commercial license key and revert to non-commercial use only?'; Localized: 'Möchten Sie Ihren kommerziellen Lizenzschlüssel wirklich entfernen und nur zur nicht kommerziellen Nutzung zurückkehren?'),
    (English: 'Commercial license key has been removed.'; Localized: 'Kommerzieller Lizenzschlüssel wurde entfernt.'),
    (English: 'Your version of Inno Setup has been updated! <a id="%1">See what''s new</a>.'; Localized: 'Ihre Version von Inno Setup wurde aktualisiert! <a id="%1">Neuerungen ansehen</a>.'),
    (English: 'VS Code-style editor shortcuts added! Use the <a id="%1">Editor Keys option</a> in Options dialog.'; Localized: 'Editor-Tastenkombinationen im VS Code-Stil hinzugefügt! Verwenden Sie die <a id="%1">Option "Tasten"</a> im Dialog "Optionen".'),
    (English: 'Inno Setup Compiler is available in your language! Use the <a id="%1">Language option</a> in Options dialog.'; Localized: 'Inno Setup Compiler ist in Ihrer Sprache verfügbar! Verwenden Sie die <a id="%1">Option "Sprache"</a> im Dialog "Optionen".'),
    (English: '<a id="%1">Ideas board is open!</a> Share your ideas and vote on others, this month only.'; Localized: '<a id="%1">Das Ideen-Board ist geöffnet!</a> Teilen Sie Ihre Ideen und stimmen Sie über andere ab, nur diesen Monat.'),
    (English: 'Running a version released after your update entitlement ended. <a id="%1">Renew license</a>, <a id="%2">remove key</a>, or <a id="%3">exit</a>.'; Localized: 'Sie verwenden eine Version, die nach dem Ende Ihrer Update-Berechtigung veröffentlicht wurde. <a id="%1">Lizenz verlängern</a>, <a id="%2">Schlüssel entfernen</a> oder <a id="%3">beenden</a>.'),
    (English: 'Your update entitlement is ending soon. Please <a id="%1">renew your license</a>. Thanks!'; Localized: 'Ihre Update-Berechtigung endet bald. Bitte <a id="%1">verlängern Sie Ihre Lizenz</a>. Vielen Dank!'),
    (English: 'Your update entitlement has ended. Please <a id="%1">renew your license</a>. Thanks!'; Localized: 'Ihre Update-Berechtigung ist abgelaufen. Bitte <a id="%1">verlängern Sie Ihre Lizenz</a>. Vielen Dank!'),
    (English: 'Using Inno Setup commercially? Please <a id="%1">purchase a license</a>. Thanks!'; Localized: 'Verwenden Sie Inno Setup kommerziell? Bitte <a id="%1">erwerben Sie eine Lizenz</a>. Vielen Dank!'),
    (English: 'Uninstall'; Localized: 'Deinstallation'),
    (English: '%1 exit code: 0x%2'; Localized: '%1-Exitcode: 0x%2'),
    (English: '%1 exit code: %2'; Localized: '%1-Exitcode: %2'),
    (English: 'Unable to get %1 exit code (%2 failed)'; Localized: '%1-Exitcode konnte nicht abgerufen werden (%2 fehlgeschlagen)'),
    (English: '%1 is still running; can''t get exit code'; Localized: '%1 wird noch ausgeführt; Exitcode kann nicht abgerufen werden'),
    (English: 'Please stop the running %1 process before performing this command.'; Localized: 'Bitte stoppen Sie den laufenden %1-Prozess, bevor Sie diesen Befehl ausführen.'),
    (English: 'This command will detach the debugger from the running %1 process. Continue?'; Localized: 'Mit diesem Befehl wird der Debugger vom laufenden %1-Prozess getrennt. Fortfahren?'),
    (English: 'The changes you made will not take effect until you re-compile.%n%nContinue running anyway?'; Localized: 'Die von Ihnen vorgenommenen Änderungen werden erst nach einer erneuten Kompilierung wirksam.%n%nTrotzdem mit der Ausführung fortfahren?'),
    (English: 'A pause is already pending.'; Localized: 'Eine Pause steht bereits aus.'),
    (English: 'No code was generated for the current line.'; Localized: 'Für die aktuelle Zeile wurde kein Code generiert.'),
    (English: 'This will unconditionally terminate the running %1 process. Continue?'; Localized: 'Hiermit wird der laufende %1-Prozess bedingungslos beendet. Fortfahren?'),
    (English: 'Note that if %1 is currently in the installation phase, any changes made to the system thus far will not be undone, nor will uninstall data be written.'; Localized: 'Beachten Sie: Wenn sich %1 derzeit in der Installationsphase befindet, werden die bisher am System vorgenommenen Änderungen nicht rückgängig gemacht und es werden keine Deinstallationsinformationen geschrieben.'),
    (English: 'Evaluate'; Localized: 'Auswerten'),
    (English: 'Constant to evaluate (for example, "%1"):'; Localized: 'Auszuwertende Konstante (zum Beispiel "%1"):'),
    (English: 'Evaluate Result'; Localized: 'Auswertungsergebnis'),
    (English: 'Evaluate Error'; Localized: 'Auswertungsfehler'),
    (English: 'An unknown error occurred.'; Localized: 'Ein unbekannter Fehler ist aufgetreten.'),
    (English: '%1 = "%2"'; Localized: '%1 = "%2"'),
    (English: '%1 = Exception: %2'; Localized: '%1 = Ausnahme: %2'),
    (English: '%1 = Unknown error'; Localized: '%1 = Unbekannter Fehler'),
    (English: 'Unknown error'; Localized: 'Unbekannter Fehler'),
    (English: 'Line %1:%n%2'; Localized: 'Zeile %1:%n%2'),
    (English: 'Runtime Error'; Localized: 'Laufzeitfehler'),
    (English: '%1 (Update entitlement ended)'; Localized: '%1 (Update-Berechtigung abgelaufen)'),
    (English: '%1 (Update entitlement ended but updated anyway)'; Localized: '%1 (Update-Berechtigung abgelaufen, aber trotzdem aktualisiert)'),
    (English: 'Non-commercial use only'; Localized: 'Nur nicht kommerzielle Nutzung'),
    (English: 'Single User'; Localized: 'Single User'),
    (English: 'Team'; Localized: 'Team'),
    (English: 'Enterprise'; Localized: 'Enterprise'),
    (English: 'Inno Setup %1 License'; Localized: 'Inno Setup %1-Lizenz'),
    (English: '%1, %2.'; Localized: '%1, %2.'),
    (English: 'Includes updates until %1, major and minor.'; Localized: 'Enthält Updates bis %1, Haupt- und Nebenversionen.'),
    (English: 'Includes all future updates, major and minor.'; Localized: 'Enthält alle zukünftigen Updates, Haupt- und Nebenversionen.'),
    (English: '%1 Entries Designer'; Localized: '%1-Einträge-Designer'),
    (English: '&Insert'; Localized: '&Einfügen'),
    (English: '&Parameters...'; Localized: '&Parameter...'),
    (English: 'Remo&ve'; Localized: 'Ent&fernen'),
    (English: 'Add Fol&der...'; Localized: '&Ordner hinzufügen...'),
    (English: '&Add File(s)...'; Localized: '&Datei(en) hinzufügen...'),
    (English: '&Files:'; Localized: 'D&ateien:'),
    (English: 'D&ownload...'; Localized: '&Herunterladen...'),
    (English: 'Go to File'; Localized: 'Gehe zu Datei'),
    (English: 'Enter Commercial License Key'; Localized: 'Kommerziellen Lizenzschlüssel eingeben'),
    (English: 'Paste your license key below'; Localized: 'Fügen Sie Ihren Lizenzschlüssel unten ein'),
    (English: 'Close'; Localized: 'Schließen'),
    (English: 'New Main Script (%1)'; Localized: 'Neues Hauptskript (%1)'),
    (English: 'Open Main Script (%1)'; Localized: 'Hauptskript öffnen (%1)'),
    (English: 'Save (%1)'; Localized: 'Speichern (%1)'),
    (English: 'Stop Compile (%1)'; Localized: 'Kompilierung stoppen (%1)'),
    (English: 'Target Setup (%1)'; Localized: 'Setup als Ziel festlegen (%1)'),
    (English: 'Target Uninstall (%1)'; Localized: 'Deinstallation als Ziel festlegen (%1)'),
    (English: 'Help (%1)'; Localized: 'Hilfe (%1)'),
    (English: 'Main Script'; Localized: 'Hauptskript'),
    (English: 'Close Banner'; Localized: 'Banner schließen'),
    (English: '&File'; Localized: '&Datei'),
    (English: '&Open...'; Localized: '&Öffnen...'),
    (English: 'Open &Recent'; Localized: '&Zuletzt verwendet'),
    (English: '&Clear Recently Opened'; Localized: 'Zuletzt geöffnete &löschen'),
    (English: '&Save'; Localized: '&Speichern'),
    (English: 'Save &As...'; Localized: 'Speichern &unter...'),
    (English: 'Save &Encoding'; Localized: '&Codierung speichern'),
    (English: '&Auto (ANSI or UTF-8)'; Localized: '&Automatisch (ANSI oder UTF-8)'),
    (English: '&UTF-8'; Localized: '&UTF-8'),
    (English: 'UTF-8 with &BOM'; Localized: 'UTF-8 mit &BOM'),
    (English: 'Sa&ve All'; Localized: 'A&lles speichern'),
    (English: '&Print...'; Localized: '&Drucken...'),
    (English: 'E&xit'; Localized: '&Beenden'),
    (English: '&Edit'; Localized: '&Bearbeiten'),
    (English: '&Undo'; Localized: 'Rück&gängig'),
    (English: '&Redo'; Localized: 'Wieder&holen'),
    (English: 'Cu&t'; Localized: 'A&usschneiden'),
    (English: '&Copy'; Localized: '&Kopieren'),
    (English: '&Paste'; Localized: 'Ein&fügen'),
    (English: 'De&lete'; Localized: '&Löschen'),
    (English: 'Select &All'; Localized: '&Alles auswählen'),
    (English: 'Add Next &Occurrence'; Localized: 'Nächstes &Vorkommen hinzufügen'),
    (English: '&Select All Occurrences'; Localized: 'Alle V&orkommen auswählen'),
    (English: 'Select All Find &Matches'; Localized: 'Alle &Treffer auswählen'),
    (English: '&Find...'; Localized: '&Suchen...'),
    (English: 'F&ind in Files...'; Localized: 'In &Dateien suchen...'),
    (English: 'Find &Next'; Localized: '&Weitersuchen'),
    (English: 'Find Pre&vious'; Localized: 'Vorheriges Element su&chen'),
    (English: 'R&eplace...'; Localized: 'E&rsetzen...'),
    (English: 'Use Regular E&xpressions'; Localized: 'Reguläre Ausdrücke verwe&nden'),
    (English: 'Fol&d Section'; Localized: 'Abschnitt &einklappen'),
    (English: '&Unfold Section'; Localized: 'Abschnitt auskla&ppen'),
    (English: 'Go to File...'; Localized: 'Gehe zu Datei...'),
    (English: '&Go to Line...'; Localized: 'Gehe zu &Zeile...'),
    (English: 'Toggle Line Comment'; Localized: 'Zeilenkommentar umschalten'),
    (English: 'Go To Matching Brace'; Localized: 'Zur passenden Klammer springen'),
    (English: '&View'; Localized: '&Ansicht'),
    (English: '&Zoom'; Localized: 'Zoo&m'),
    (English: 'Zoom &In'; Localized: '&Vergrößern'),
    (English: 'Zoom &Out'; Localized: 'Ver&kleinern'),
    (English: '&Reset'; Localized: '&Zurücksetzen'),
    (English: '&Toolbar'; Localized: 'S&ymbolleiste'),
    (English: 'St&atus Bar'; Localized: '&Statusleiste'),
    (English: '&Next Tab'; Localized: '&Nächste Registerkarte'),
    (English: '&Previous Tab'; Localized: '&Vorherige Registerkarte'),
    (English: 'C&lose Tab'; Localized: '&Registerkarte schließen'),
    (English: 'Re&open Tab'; Localized: 'Registerkarte erneut &öffnen'),
    (English: 'Reopen &All Tabs'; Localized: '&Alle Registerkarten erneut öffnen'),
    (English: 'C&lose Current Tab'; Localized: 'A&ktuelle Registerkarte schließen'),
    (English: '&Compiler Output'; Localized: '&Compiler-Ausgabe'),
    (English: '&Debug Output'; Localized: '&Debug-Ausgabe'),
    (English: 'D&ebug Call Stack'; Localized: 'Debug-Aufruf&liste'),
    (English: '&Find Results'; Localized: 'Such&ergebnisse'),
    (English: '&Hide Bottom Pane'; Localized: 'Unteren &Bereich ausblenden'),
    (English: '&Word Wrap'; Localized: '&Zeilenumbruch'),
    (English: '&Build'; Localized: '&Erstellen'),
    (English: '&Compile'; Localized: '&Kompilieren'),
    (English: 'S&top Compile'; Localized: 'Kompilierung s&toppen'),
    (English: '&Low Priority During Compile'; Localized: '&Niedrige Priorität beim Kompilieren'),
    (English: '&Disable Output'; Localized: '&Ausgabe deaktivieren'),
    (English: 'Disable Co&mpression'; Localized: 'Ko&mprimierung deaktivieren'),
    (English: 'Disable &Signing'; Localized: '&Signierung deaktivieren'),
    (English: 'Disable Signcheck &Validation'; Localized: 'Signcheck-&Validierung deaktivieren'),
    (English: '&Open Output Folder'; Localized: 'Ausgabeordner &öffnen'),
    (English: '&Run'; Localized: 'A&usführen'),
    (English: '&Run...'; Localized: 'A&usführen...'),
    (English: 'Run to &Cursor'; Localized: 'Ausführen bis &Cursor'),
    (English: 'Step &Into'; Localized: 'E&inzelschritt'),
    (English: 'Step &Over'; Localized: 'Pr&ozedurschritt'),
    (English: 'Step Out'; Localized: 'Rücksprung'),
    (English: 'Toggle &Breakpoint'; Localized: '&Haltepunkt umschalten'),
    (English: '&Delete All Breakpoints'; Localized: 'Alle Haltepunkte &löschen'),
    (English: 'P&ause'; Localized: '&Anhalten'),
    (English: '&Terminate'; Localized: '&Beenden'),
    (English: '&Evaluate Constant...'; Localized: '&Konstante auswerten...'),
    (English: 'Target &Setup'; Localized: '&Setup als Ziel festlegen'),
    (English: 'Target &Uninstall'; Localized: '&Deinstallation als Ziel festlegen'),
    (English: '&Tools'; Localized: 'E&xtras'),
    (English: '&Add/Remove Programs'; Localized: '&Programme hinzufügen/entfernen'),
    (English: 'Generate &GUID'; Localized: '&GUID generieren'),
    (English: 'Generate %1 Entries...'; Localized: '%1-Einträge generieren...'),
    (English: 'Generate %1 Call...'; Localized: '%1-Aufruf generieren...'),
    (English: '&Configure Sign Tools...'; Localized: '&Signaturtools konfigurieren...'),
    (English: '&Options...'; Localized: '&Optionen...'),
    (English: '&Help'; Localized: '&Hilfe'),
    (English: 'Purchase or Renew Commercial &License'; Localized: 'Kommerzielle &Lizenz erwerben oder verlängern'),
    (English: 'Enter Commercial License &Key...'; Localized: '&Kommerziellen Lizenzschlüssel eingeben...'),
    (English: 'Remove Commercial License Key'; Localized: 'Kommerziellen Lizenzschlüssel entfernen'),
    (English: '&Donate'; Localized: '&Spenden'),
    (English: '&Keyboard And Mouse Commands'; Localized: '&Tastatur- und Mausbefehle'),
    (English: 'Regular E&xpressions'; Localized: 'Reguläre &Ausdrücke'),
    (English: 'Inno &Setup Documentation'; Localized: 'Inno Setup-&Dokumentation'),
    (English: 'Inno Setup &Example Scripts'; Localized: 'Inno Setup-&Beispielskripte'),
    (English: 'Inno Setup &FAQ'; Localized: 'Inno Setup-&FAQ'),
    (English: 'Inno Setup &Mailing List'; Localized: 'Inno Setup-&Mailingliste'),
    (English: 'Inno Setup &Revision History'; Localized: 'Inno Setup-&Revisionsverlauf'),
    (English: 'Inno Setup &Web Site'; Localized: 'Inno Setup-&Website'),
    (English: 'Inno Setup &Preprocessor Documentation'; Localized: 'Inno Setup-&Präprozessor-Dokumentation'),
    (English: '&About Inno Setup'; Localized: '&Über Inno Setup'),
    (English: '%1 Call Designer'; Localized: '%1-Aufruf-Designer'),
    (English: 'Instruction'; Localized: 'Anweisung'),
    (English: 'Message'; Localized: 'Meldung'),
    (English: 'Text Button1'; Localized: 'Text Schaltfläche1'),
    (English: 'Button2'; Localized: 'Schaltfläche2'),
    (English: 'Button3'; Localized: 'Schaltfläche3'),
    (English: ' Message '; Localized: ' Meldung '),
    (English: ' Type'; Localized: ' Typ'),
    (English: 'Suppressible'; Localized: 'Unterdrückbar'),
    (English: ' Flags '; Localized: ' Flags '),
    (English: 'Default button'; Localized: 'Standardschaltfläche'),
    (English: ' Icon '; Localized: ' Symbol '),
    (English: ' Buttons '; Localized: ' Schaltflächen '),
    (English: ' Return values '; Localized: ' Rückgabewerte '),
    (English: '&Preview'; Localized: '&Vorschau'),
    (English: 'Options'; Localized: 'Optionen'),
    (English: ' Miscellaneous '; Localized: ' Verschiedenes '),
    (English: 'Show &Welcome dialog at startup'; Localized: '&Willkommensdialog beim Start anzeigen'),
    (English: 'Use the Inno Setup &Script Wizard'; Localized: 'Inno Setup Skri&pt-Assistent verwenden'),
    (English: 'Automatically sa&ve before compiling'; Localized: '&Vor dem Kompilieren automatisch speichern'),
    (English: 'Create &backups when saving'; Localized: '&Beim Speichern Sicherungskopien erstellen'),
    (English: 'Allow &Undo after save'; Localized: 'Rückgängig nach dem Speichern erla&uben'),
    (English: 'Display &full path in title bar'; Localized: 'Vollständigen P&fad in der Titelleiste anzeigen'),
    (English: '&Pause on exceptions'; Localized: 'Bei Au&snahmen anhalten'),
    (English: 'Always &launch Setup/Uninstall as administrator'; Localized: 'Setup/Deinstallation &immer als Administrator starten'),
    (English: 'Colori&ze "Compiler Output" view'; Localized: 'Ansicht "C&ompiler-Ausgabe" einfärben'),
    (English: 'Automatically open %1 files'; Localized: '%1-Dateien automatisch öffnen'),
    (English: 'Automatically show preprocessor output'; Localized: 'Präprozessor-Ausgabe automatisch anzeigen'),
    (English: 'Menu &keys:'; Localized: 'Men&ütasten:'),
    (English: 'Automatically reload files'; Localized: 'Dateien automatisch neu laden'),
    (English: 'Allow Undo after reload'; Localized: 'Rückgängig nach dem Neuladen erlauben'),
    (English: 'Keep new %1 files closed'; Localized: 'Neue %1-Dateien geschlossen halten'),
    (English: 'Language:'; Localized: 'Sprache:'),
    (English: ' Editor '; Localized: ' Editor '),
    (English: 'Invoke autoco&mplete automatically'; Localized: 'Autovervollständigung auto&matisch aufrufen'),
    (English: 'Use syntax &highlighting'; Localized: 'Syntax&hervorhebung verwenden'),
    (English: 'U&nderline syntax errors'; Localized: 'Synta&xfehler unterstreichen'),
    (English: 'Allow cursor to move beyond &end of lines'; Localized: 'Cursor über das Zeilen&ende hinaus bewegen lassen'),
    (English: 'Enable section f&olding'; Localized: 'Abs&chnittsfaltung aktivieren'),
    (English: 'Use tab cha&racter'; Localized: 'Tabulato&rzeichen verwenden'),
    (English: 'Auto &indent mode'; Localized: 'Automatischer Ein&zugsmodus'),
    (English: 'Show indentation &guides'; Localized: 'Einzu&gshilfslinien anzeigen'),
    (English: 'Font:'; Localized: 'Schriftart:'),
    (English: 'AaBbXxZz'; Localized: 'AaBbXxZz'),
    (English: '&Change...'; Localized: '&Ändern...'),
    (English: '&Tab Width:'; Localized: '&Tabbreite:'),
    (English: 'Show &line numbers in gutter'; Localized: 'Zei&lennummern in der Editorleiste anzeigen'),
    (English: 'T&heme:'; Localized: '&Design:'),
    (English: 'Highlight occurrences of current selection'; Localized: 'Vorkommen der aktuellen Auswahl hervorheben'),
    (English: 'Highlight occurrences of current wor&d'; Localized: 'Vor&kommen des aktuellen Worts hervorheben'),
    (English: 'Ke&ys:'; Localized: 'Taste&n:'),
    (English: 'Show whitespace'; Localized: 'Leerzeichen anzeigen'),
    (English: 'Smart Home key'; Localized: 'Intelligente Pos1-Taste'),
    (English: '&Associate .%1 files with this compiler'; Localized: '.%1-D&ateien diesem Compiler zuordnen'),
    (English: '&Windows registry file (.%1) to import:'; Localized: '&Windows-Registry-Datei (.%1) zum Importieren:'),
    (English: 'B&rowse...'; Localized: 'Du&rchsuchen...'),
    (English: 'Settings (for all keys and values):'; Localized: 'Einstellungen (für alle Schlüssel und Werte):'),
    (English: 'Also delete keys which are not empty'; Localized: 'Auch Schlüssel löschen, die nicht leer sind'),
    (English: 'Delete keys which are empty on uninstall'; Localized: 'Bei der Deinstallation leere Schlüssel löschen'),
    (English: 'Delete values on uninstall'; Localized: 'Bei der Deinstallation Werte löschen'),
    (English: 'Minimum Windows version:'; Localized: 'Windows-Mindestversion:'),
    (English: 'Configure Sign Tools'; Localized: 'Signaturtools konfigurieren'),
    (English: ' Sign Tools '; Localized: ' Signaturtools '),
    (English: '&Add...'; Localized: '&Hinzufügen...'),
    (English: '&Edit...'; Localized: '&Bearbeiten...'),
    (English: 'Be notified by e-mail of new Inno Setup releases'; Localized: 'Per E-Mail über neue Inno Setup-Versionen benachrichtigt werden'),
    (English: 'Subscribe'; Localized: 'Abonnieren'),
    (English: ' New file '; Localized: ' Neue Datei '),
    (English: 'Create a new &empty script file'; Localized: 'Neue &leere Skriptdatei erstellen'),
    (English: 'Create a new script file using the &Script Wizard'; Localized: 'Neue Skriptdatei mit dem &Skript-Assistenten erstellen'),
    (English: ' Open file '; Localized: ' Datei öffnen '),
    (English: 'Open an e&xisting script file'; Localized: '&Vorhandene Skriptdatei öffnen'),
    (English: '&Don''t show this dialog again'; Localized: '&Diesen Dialog nicht erneut anzeigen'),
    (English: 'Script Wizard File'; Localized: 'Datei für den Skript-Assistenten'),
    (English: 'bold'; Localized: 'fett'),
    (English: ' = required'; Localized: ' = erforderlich'),
    (English: ' Destination '; Localized: ' Ziel '),
    (English: 'Destination &base folder:'; Localized: 'Ziel-&Basisordner:'),
    (English: 'Destination &subfolder:'; Localized: 'Ziel-Unte&rordner:'),
    (English: 'Destination &name:'; Localized: '&Zielname:'),
    (English: ' Source '; Localized: ' Quelle '),
    (English: '&Source file or folder:'; Localized: '&Quelldatei oder -ordner:'),
    (English: '&Recurse subfolders'; Localized: '&Unterordner rekursiv durchlaufen'),
    (English: '&Include empty subfolders'; Localized: '&Leere Unterordner einbeziehen'),
    (English: '&Extract archive'; Localized: '&Archiv entpacken'),
    (English: 'Welcome to the %1'; Localized: 'Willkommen beim %1'),
    (English: 'This wizard will guide you through the process of creating a new Inno Setup script file. The results will be used to generate a new script file which can be compiled directly or saved on disk for later use.'; Localized: 'Dieser Assistent führt Sie durch die Erstellung einer neuen Inno Setup-Skriptdatei. Die Ergebnisse werden verwendet, um eine neue Skriptdatei zu generieren, die direkt kompiliert oder zur späteren Verwendung auf dem Datenträger gespeichert werden kann.'),
    (English: 'Not all features of Inno Setup are covered by this wizard. See the documentation for details on creating Inno Setup script files.%n%nClick Next to continue, or Cancel to exit this wizard.'; Localized: 'Nicht alle Funktionen von Inno Setup werden von diesem Assistenten abgedeckt. Einzelheiten zum Erstellen von Inno Setup-Skriptdateien finden Sie in der Dokumentation.%n%n'+'Klicken Sie auf "Weiter", um fortzufahren, oder auf "Abbrechen", um diesen Assistenten zu beenden.'),
    (English: 'Application na&me:'; Localized: 'Anwendungs&name:'),
    (English: 'Application &version:'; Localized: 'Anwendungs&version:'),
    (English: 'Application &publisher:'; Localized: 'Anwendungs&herausgeber:'),
    (English: 'Application &website:'; Localized: 'Anwendungs&website:'),
    (English: 'Application folder na&me:'; Localized: '&Name des Anwendungsordners:'),
    (English: 'Application &destination base folder:'; Localized: 'Ziel-Basisordner der &Anwendung:'),
    (English: 'Other:'; Localized: 'Andere:'),
    (English: 'Allow user to &change the application folder'; Localized: 'Dem &Benutzer erlauben, den Anwendungsordner zu ändern'),
    (English: 'The application doe&sn''t need a folder'; Localized: 'Die Anwendung benötigt &keinen Ordner'),
    (English: 'Other application &files:'; Localized: 'Andere &Anwendungsdateien:'),
    (English: 'Application &main executable file:'; Localized: 'Ausführ&bare Hauptdatei der Anwendung:'),
    (English: 'Allow &user to start the application after Setup has finished'; Localized: 'Dem Ben&utzer erlauben, die Anwendung nach Abschluss von Setup zu starten'),
    (English: 'The application doe&sn''t have a main executable file'; Localized: 'Die Anwendung hat &keine ausführbare Hauptdatei'),
    (English: 'Application file type na&me:'; Localized: '&Name des Anwendungsdateityps:'),
    (English: '&Associate a file type to the main executable'; Localized: 'Einen &Dateityp der ausführbaren Hauptdatei zuordnen'),
    (English: 'Application file type &extension:'; Localized: '&Erweiterung des Anwendungsdateityps:'),
    (English: 'Application &Start Menu folder name:'; Localized: 'Name des &Startmenüordners der Anwendung:'),
    (English: 'Other shortcuts to the main executable:'; Localized: 'Andere Verknüpfungen zur ausführbaren Hauptdatei:'),
    (English: 'Allow user to &change the Start Menu folder name'; Localized: 'Dem &Benutzer erlauben, den Namen des Startmenüordners zu ändern'),
    (English: 'Allow user to &disable Start Menu folder creation'; Localized: 'Dem Benutzer erlauben, die Erstellung des Startmenüordners zu &deaktivieren'),
    (English: 'Allow user to create a deskto&p shortcut'; Localized: 'Dem Benutzer erlauben, eine Des&ktopverknüpfung zu erstellen'),
    (English: 'Create an &Uninstall shortcut in the Start Menu folder'; Localized: 'Eine Deins&tallationsverknüpfung im Startmenüordner erstellen'),
    (English: 'Create an &Internet shortcut in the Start Menu folder'; Localized: 'Eine &Internetverknüpfung im Startmenüordner erstellen'),
    (English: '&Create a shortcut to the main executable in the Start Menu Programs folder'; Localized: 'Eine &Verknüpfung zur ausführbaren Hauptdatei im Startmenü-Programmordner erstellen'),
    (English: '&License file:'; Localized: '&Lizenzdatei:'),
    (English: '&Information file shown before installation:'; Localized: '&Vor der Installation angezeigte Informationsdatei:'),
    (English: 'Information file shown &after installation:'; Localized: '&Nach der Installation angezeigte Informationsdatei:'),
    (English: 'Install mode:'; Localized: 'Installationsmodus:'),
    (English: '&Administrative install mode (install for all users)'; Localized: '&Administrativer Installationsmodus (Installation für alle Benutzer)'),
    (English: 'Non a&dministrative install mode (install for current user only)'; Localized: '&Nicht administrativer Installationsmodus (Installation nur für aktuellen Benutzer)'),
    (English: 'Allow user to &override the install mode via the command line'; Localized: 'Dem Benutzer erlauben, den &Installationsmodus über die Befehlszeile zu überschreiben'),
    (English: 'Ask the user to &choose the install mode at startup'; Localized: 'Den &Benutzer beim Start nach dem Installationsmodus fragen'),
    (English: '&Languages:'; Localized: '&Sprachen:'),
    (English: '&Deselect All'; Localized: 'Alle a&bwählen'),
    (English: 'Custom compiler output fol&der:'; Localized: 'Benutzerdefinierter Compiler-&Ausgabeordner:'),
    (English: 'Compiler output base &file name:'; Localized: 'Compiler-Ausgabe-&Basisdateiname:'),
    (English: 'Custom Setup &icon file:'; Localized: 'Benutzerdefinierte Setup-&Symboldatei:'),
    (English: 'Setup &password:'; Localized: 'Setup-&Passwort:'),
    (English: 'Use the password to &encrypt the application files'; Localized: 'Das Passwort zum &Verschlüsseln der Anwendungsdateien verwenden'),
    (English: '&Wizard style:'; Localized: '&Assistentenstil:'),
    (English: 'You have successfully completed the %1.%n%nTo close this wizard and generate the new script file, click Finish.'; Localized: 'Der %1 wurde erfolgreich abgeschlossen.%n%nKlicken Sie auf "Fertigstellen", um diesen Assistenten zu schließen und die neue Skriptdatei zu generieren.'),
    (English: '&Back'; Localized: '&Zurück'));

implementation

end.
