unit IDE.LocalizeFunc.Czech;

{
  Inno Setup
  Copyright (C) 1997-2026 Jordan Russell
  Portions by Martijn Laan
  For conditions of distribution and use, see LICENSE.TXT.

  Compiler IDE Czech translations
}

interface

uses
  IDE.LocalizeFunc;

const
  CzechIDETranslations: array [0..898] of TTranslationPair = (
    (English: 'Command-line usage:'; Localized: 'Použití příkazového řádku:'),
    (English: 'Examples:'; Localized: 'Příklady:'),
    (English: 'script file'; Localized: 'soubor skriptu'),
    (English: 'wizard name'; Localized: 'název průvodce'),
    (English: 'My script'; Localized: 'Můj skript'),
    (English: 'My Script Wizard'; Localized: 'Můj průvodce skriptem'),
    (English: 'Could not load %1: %2'; Localized: 'Nelze načíst %1: %2'),
    (English: 'Inno Setup Compiler'; Localized: 'Inno Setup Compiler'),
    (English: 'Example scripts...'; Localized: 'Ukázkové skripty...'),
    (English: 'More files...'; Localized: 'Další soubory...'),
    (English: 'Untitled'; Localized: 'Bez názvu'),
    (English: 'Preprocessor Output'; Localized: 'Výstup preprocesoru'),
    (English: 'Run Parameters'; Localized: 'Parametry spuštění'),
    (English: 'Command-line parameters for %1 and %2:'; Localized: 'Parametry příkazového řádku pro %1 a %2:'),
    (English: 'Inno Setup Script files'; Localized: 'Soubory skriptů Inno Setup'),
    (English: 'All files'; Localized: 'Všechny soubory'),
    (English: 'Application files'; Localized: 'Soubory aplikace'),
    (English: 'Documentation files'; Localized: 'Soubory dokumentace'),
    (English: 'Registry files'; Localized: 'Soubory registru'),
    (English: 'Icon files'; Localized: 'Soubory ikon'),
    (English: 'Inno Setup Script Wizard'; Localized: 'Průvodce skriptem Inno Setup'),
    (English: 'Welcome'; Localized: 'Vítejte'),
    (English: 'Application Information'; Localized: 'Informace o aplikaci'),
    (English: 'Please specify some basic information about your application.'; Localized: 'Zadejte základní informace o své aplikaci.'),
    (English: 'Application Folder'; Localized: 'Složka aplikace'),
    (English: 'Please specify folder information about your application.'; Localized: 'Zadejte informace o složce své aplikace.'),
    (English: 'Application Files'; Localized: 'Soubory aplikace'),
    (English: 'Please specify the files that are part of your application.'; Localized: 'Zadejte soubory, které jsou součástí vaší aplikace.'),
    (English: 'Please specify the source folder.'; Localized: 'Zadejte zdrojovou složku.'),
    (English: 'Should files in subfolders of "%1" also be included?'; Localized: 'Mají být zahrnuty také soubory v podsložkách "%1"?'),
    (English: 'URL:'; Localized: 'URL:'),
    (English: 'Is the file to download an archive which should be extracted?'; Localized: 'Je soubor ke stažení archiv, který se má extrahovat?'),
    (English: 'Name of the file:'; Localized: 'Název souboru:'),
    (English: 'Name of the file (extension should match archive format):'; Localized: 'Název souboru (přípona by měla odpovídat formátu archivu):'),
    (English: 'Approximate size of the file in megabytes:'; Localized: 'Přibližná velikost souboru v megabajtech:'),
    (English: 'Application File Association'; Localized: 'Přidružení souboru aplikace'),
    (English: 'Please specify which file association should be created for your application.'; Localized: 'Zadejte, které přidružení souboru se má pro vaši aplikaci vytvořit.'),
    (English: '%1 File'; Localized: 'Soubor %1'),
    (English: 'Application Shortcuts'; Localized: 'Zástupci aplikace'),
    (English: 'Please specify which shortcuts should be created for your application.'; Localized: 'Zadejte, kteří zástupci se mají pro vaši aplikaci vytvořit.'),
    (English: 'Application Documentation'; Localized: 'Dokumentace aplikace'),
    (English: 'Please specify which documentation files should be shown by Setup during installation.'; Localized: 'Zadejte, které soubory dokumentace má Setup zobrazit během instalace.'),
    (English: 'Setup Install Mode'; Localized: 'Režim instalace'),
    (English: 'Please specify in which install mode Setup should run.'; Localized: 'Zadejte, ve kterém režimu instalace má Setup běžet.'),
    (English: 'Application Registry Keys And Values'; Localized: 'Klíče a hodnoty registru aplikace'),
    (English: 'Please specify the registry keys and values that are part of your application.'; Localized: 'Zadejte klíče a hodnoty registru, které jsou součástí vaší aplikace.'),
    (English: 'Setup Languages'; Localized: 'Jazyky instalace'),
    (English: 'Please specify which Setup languages should be included.'; Localized: 'Zadejte, které jazyky instalace mají být zahrnuty.'),
    (English: 'Compiler Settings'; Localized: 'Nastavení kompilátoru'),
    (English: 'Please specify some basic compiler settings.'; Localized: 'Zadejte základní nastavení kompilátoru.'),
    (English: 'Please specify the folder.'; Localized: 'Zadejte složku.'),
    (English: 'Wizard Style'; Localized: 'Styl průvodce'),
    (English: 'Please specify which wizard style should be used.'; Localized: 'Zadejte, který styl průvodce se má použít.'),
    (English: 'Inno Setup Preprocessor'; Localized: 'Inno Setup Preprocessor'),
    (English: 'Please specify whether Inno Setup Preprocessor should be used.'; Localized: 'Zadejte, zda se má použít Inno Setup Preprocessor.'),
    (English: 'The %1 can use %2 compiler directives to simplify your script. Although this is not necessary, it will make it easier to manually change the script later.%n%nDo you want the %1 to use %2 compiler directives?'; Localized: '%1 může pro zjednodušení vašeho skriptu používat direktivy kompilátoru %2. I když to není nutné, usnadní to pozdější ruční úpravy skriptu.%n%nMá %1 používat direktivy kompilátoru %2?'),
    (English: '&Yes, use %1 compiler directives'; Localized: '&Ano, používat direktivy kompilátoru %1'),
    (English: 'Finished'; Localized: 'Dokončeno'),
    (English: '&Next'; Localized: '&Další'),
    (English: '&Finish'; Localized: '&Dokončit'),
    (English: 'The %1 is not complete. If you quit now, the new script file will not be generated.%n%nExit anyway?'; Localized: '%1 není dokončen. Pokud nyní skončíte, nový soubor skriptu nebude vygenerován.%n%nPřesto ukončit?'),
    (English: 'Please specify the application name.'; Localized: 'Zadejte název aplikace.'),
    (English: 'Please specify the application version.'; Localized: 'Zadejte verzi aplikace.'),
    (English: 'Please specify the application destination base folder.'; Localized: 'Zadejte cílovou základní složku aplikace.'),
    (English: 'Please specify the application folder name.'; Localized: 'Zadejte název složky aplikace.'),
    (English: 'Please specify the application main executable file.'; Localized: 'Zadejte hlavní spustitelný soubor aplikace.'),
    (English: 'The specified application main executable file does not exist.'; Localized: 'Zadaný hlavní spustitelný soubor aplikace neexistuje.'),
    (English: 'Please specify the application Start Menu group name.'; Localized: 'Zadejte název složky aplikace v nabídce Start.'),
    (English: 'Please specify the destination base folder.'; Localized: 'Zadejte cílovou základní složku.'),
    (English: 'Please specify a destination base folder other than the application folder.'; Localized: 'Zadejte jinou cílovou základní složku než složku aplikace.'),
    (English: 'Please select at least one language.'; Localized: 'Vyberte alespoň jeden jazyk.'),
    (English: '&Source URL:'; Localized: '&Zdrojová URL:'),
    (English: 'Script generated by the %1.'; Localized: 'Tento skript vytvořil %1.'),
    (English: 'SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!'; Localized: 'PODROBNOSTI O VYTVÁŘENÍ SOUBORŮ SKRIPTŮ INNO SETUP NAJDETE V DOKUMENTACI!'),
    (English: 'NOTE: The value of %1 uniquely identifies this application. Do not use the same %1 value in installers for other applications.'; Localized: 'POZNÁMKA: Hodnota %1 jednoznačně identifikuje tuto aplikaci. Nepoužívejte stejnou hodnotu %1 v instalátorech jiných aplikací.'),
    (English: '(To generate a new GUID, click Tools | Generate GUID inside the IDE.)'; Localized: '(Chcete-li vygenerovat nový GUID, klikněte v IDE na Nástroje | Vygenerovat GUID.)'),
    (English: '"%1" specifies that Setup cannot run on anything but x64 and Windows 11 on Arm.'; Localized: '"%1" určuje, že Setup může běžet pouze na x64 a Windows 11 on Arm.'),
    (English: '"%1" requests that the install be done in "64-bit mode" on x64 or Windows 11 on Arm.'; Localized: '"%1" požaduje, aby instalace proběhla v "64bitovém režimu" na x64 nebo Windows 11 on Arm.'),
    (English: 'This means it should use the native 64-bit Program Files directory and the 64-bit view of the registry.'; Localized: 'To znamená, že by se měl použít nativní 64bitový adresář Program Files a 64bitové zobrazení registru.'),
    (English: 'Uncomment the following line to use a 64-bit installer.'; Localized: 'Zrušte komentář u následujícího řádku, chcete-li použít 64bitový instalátor.'),
    (English: 'Use "%1" if all your archives are .%2 files.'; Localized: 'Použijte "%1", pokud jsou všechny vaše archivy soubory .%2.'),
    (English: 'Use "%1" if all your archives are not password-protected.'; Localized: 'Použijte "%1", pokud žádný z vašich archivů není chráněn heslem.'),
    (English: 'Uncomment the following line to run in non administrative install mode (install for current user only).'; Localized: 'Zrušte komentář u následujícího řádku, chcete-li spustit instalaci v režimu bez práv správce (instalace jen pro aktuálního uživatele).'),
    (English: 'Remove the following line to run in administrative install mode (install for all users).'; Localized: 'Odeberte následující řádek, chcete-li spustit instalaci v režimu pro správce (instalace pro všechny uživatele).'),
    (English: 'NOTE: Don''t use "%1" on any shared system files.'; Localized: 'POZNÁMKA: Nepoužívejte "%1" u žádných sdílených systémových souborů.'),
    (English: 'NOTE: Use the "%1" flag or the "%2" parameter to verify downloads.'; Localized: 'POZNÁMKA: K ověření stažených souborů použijte příznak "%1" nebo parametr "%2".'),
    (English: 'Registry data from file %1'; Localized: 'Data registru ze souboru %1'),
    (English: 'COULD NOT IMPORT %1'; Localized: 'NELZE IMPORTOVAT %1'),
    (English: 'End of registry data from file %1'; Localized: 'Konec dat registru ze souboru %1'),
    (English: 'SOME KEYS FILTERED DUE TO %1 SETTINGS!'; Localized: 'NĚKTERÉ KLÍČE BYLY ODFILTROVÁNY KVŮLI NASTAVENÍ %1!'),
    (English: 'SOME VALUES WITH UNSUPPORTED TYPES SKIPPED!'; Localized: 'NĚKTERÉ HODNOTY S NEPODPOROVANÝMI TYPY BYLY PŘESKOČENY!'),
    (English: 'Would you like to compile the new script now?'; Localized: 'Chcete nyní nový skript zkompilovat?'),
    (English: 'My Program'; Localized: 'Můj program'),
    (English: 'My Company, Inc.'; Localized: 'My Company, Inc.'),
    (English: 'Application directory'; Localized: 'Adresář aplikace'),
    (English: 'Program Files directory'; Localized: 'Adresář Program Files'),
    (English: 'Common Files directory'; Localized: 'Adresář Common Files'),
    (English: 'Windows directory'; Localized: 'Adresář Windows'),
    (English: 'Windows system directory'; Localized: 'Systémový adresář Windows'),
    (English: 'Setup source directory'; Localized: 'Zdrojový adresář instalace'),
    (English: 'System drive root directory'; Localized: 'Kořenový adresář systémového disku'),
    (English: '(Custom)'; Localized: '(Vlastní)'),
    (English: 'Starting compile.%1[%2]'; Localized: 'Spouští se kompilace.%1[%2]'),
    (English: 'Finished.%1[%2, %3 elapsed]'; Localized: 'Dokončeno.%1[%2, uplynulo %3]'),
    (English: 'Compile aborted.'; Localized: 'Kompilace přerušena.'),
    (English: 'Log size limit reached, list reset.'; Localized: 'Dosažen limit velikosti protokolu, seznam byl vynulován.'),
    (English: '%1 started'; Localized: '%1 spuštěn'),
    (English: 'Terminating process'; Localized: 'Ukončování procesu'),
    (English: 'Removing left-over temporary directory: %1'; Localized: 'Odebírání zbylého dočasného adresáře: %1'),
    (English: 'Failed to remove temporary directory'; Localized: 'Nepodařilo se odebrat dočasný adresář'),
    (English: '%1 Call Stack'; Localized: 'Zásobník volání %1'),
    (English: 'Cannot run Setup at this time. Please compile Setup successfully to completion first, with output enabled'; Localized: 'Setup nyní nelze spustit. Nejprve úspěšně zkompilujte Setup až do konce se zapnutým výstupem'),
    (English: 'Cannot run Uninstall at this time. Please run Setup successfully to completion first'; Localized: 'Uninstall nyní nelze spustit. Nejprve úspěšně spusťte Setup až do konce'),
    (English: 'Error executing "%1":%n%n%2: %3'; Localized: 'Chyba při spuštění "%1":%n%n%2: %3'),
    (English: 'Are you sure you want to abort the compile?'; Localized: 'Opravdu chcete přerušit kompilaci?'),
    (English: 'File %1:'; Localized: 'Soubor %1:'),
    (English: 'Line %1:'; Localized: 'Řádek %1:'),
    (English: 'Compiler Error'; Localized: 'Chyba kompilátoru'),
    (English: 'Illegal null character on line %1'; Localized: 'Neplatný nulový znak na řádku %1'),
    (English: 'Cannot find "%1"'; Localized: 'Nelze najít "%1"'),
    (English: 'Invalid regular expression "%1"'; Localized: 'Neplatný regulární výraz "%1"'),
    (English: '%1 (%2 hits):'; Localized: '%1 (počet výskytů: %2):'),
    (English: 'Find "%1" (%2 hits in %3 files)'; Localized: 'Najít "%1" (počet výskytů: %2, počet souborů: %3)'),
    (English: '%1 occurrence(s) replaced.'; Localized: 'Počet nahrazených výskytů: %1.'),
    (English: 'The .%1 extension was successfully associated for the current user with:%n%2'; Localized: 'Přípona .%1 byla úspěšně přidružena pro aktuálního uživatele k:%n%2'),
    (English: 'The .%1 extension was successfully associated for all users with:%n%2'; Localized: 'Přípona .%1 byla úspěšně přidružena pro všechny uživatele k:%n%2'),
    (English: 'Error creating file association:%n%1 - %2'; Localized: 'Chyba při vytváření přidružení souboru:%n%1 - %2'),
    (English: 'Unable to associate for all users without administrative privileges. Do you want to associate only for yourself instead?'; Localized: 'Bez oprávnění správce nelze přidružit pro všechny uživatele. Chcete místo toho přidružit jen pro sebe?'),
    (English: 'Associate'; Localized: 'Přidružit'),
    (English: 'Inno Setup Script'; Localized: 'Skript Inno Setup'),
    (English: 'Compi&le'; Localized: 'Kompi&lovat'),
    (English: '&Script has %1'; Localized: '&Skript obsahuje %1'),
    (English: 'Script has %1 set'; Localized: 'Skript má nastaveno %1'),
    (English: 'Invalid file format.'; Localized: 'Neplatný formát souboru.'),
    (English: 'Setup'; Localized: 'Setup'),
    (English: 'Your message text.'; Localized: 'Text vaší zprávy.'),
    (English: 'Enter your text here...'; Localized: 'Sem zadejte text...'),
    (English: 'Return values'; Localized: 'Návratové hodnoty'),
    (English: 'Default'; Localized: 'Výchozí'),
    (English: 'Shield'; Localized: 'Štít'),
    (English: 'Instruction Text'; Localized: 'Text pokynu'),
    (English: 'Message Text'; Localized: 'Text zprávy'),
    (English: 'user clicked %1'; Localized: 'uživatel klikl na %1'),
    (English: 'OK'; Localized: 'OK'),
    (English: 'Yes'; Localized: 'Ano'),
    (English: 'No'; Localized: 'Ne'),
    (English: 'Cancel'; Localized: 'Zrušit'),
    (English: 'Retry'; Localized: 'Opakovat'),
    (English: 'Ignore'; Localized: 'Ignorovat'),
    (English: 'Abort'; Localized: 'Přerušit'),
    (English: 'Display a message box'; Localized: 'Zobrazit okno se zprávou'),
    (English: 'Name of the Sign Tool:'; Localized: 'Název nástroje pro podepisování:'),
    (English: 'Invalid name.'; Localized: 'Neplatný název.'),
    (English: 'Duplicate name.'; Localized: 'Duplicitní název.'),
    (English: 'Command of the Sign Tool:'; Localized: 'Příkaz nástroje pro podepisování:'),
    (English: 'Invalid command.'; Localized: 'Neplatný příkaz.'),
    (English: 'The generated GUID will be inserted into the editor at the cursor position. Continue?'; Localized: 'Vygenerovaný GUID bude vložen do editoru na pozici kurzoru. Pokračovat?'),
    (English: 'The generated Pascal script will be inserted into the editor at the cursor position, but the cursor is not in the %1 section. Continue anyway?'; Localized: 'Vygenerovaný skript Pascal bude vložen do editoru na pozici kurzoru, ale kurzor není v sekci %1. Přesto pokračovat?'),
    (English: 'Classic'; Localized: 'Klasické'),
    (English: 'Visual Studio / Visual Studio Code'; Localized: 'Visual Studio / Visual Studio Code'),
    (English: 'Classic / Visual Studio'; Localized: 'Klasické / Visual Studio'),
    (English: 'Visual Studio Code'; Localized: 'Visual Studio Code'),
    (English: 'Light'; Localized: 'Světlý'),
    (English: 'Dark'; Localized: 'Tmavý'),
    (English: 'The new language will take effect the next time you start Inno Setup Compiler.'; Localized: 'Nový jazyk se projeví při příštím spuštění aplikace Inno Setup Compiler.'),
    (English: '&New...'; Localized: '&Nový...'),
    (English: '&New'; Localized: '&Nový'),
    (English: 'Line %1'; Localized: 'Řádek %1'),
    (English: '%1: %2'; Localized: '%1: %2'),
    (English: 'Back (%1)'; Localized: 'Zpět (%1)'),
    (English: 'Forward (%1)'; Localized: 'Vpřed (%1)'),
    (English: 'Ctrl+'; Localized: 'Ctrl+'),
    (English: 'Shift+'; Localized: 'Shift+'),
    (English: 'Alt+'; Localized: 'Alt+'),
    (English: 'Num %1'; Localized: 'Num %1'),
    (English: '(32-bit)'; Localized: '(32-bit)'),
    (English: '[Compiling]'; Localized: '[Kompilace]'),
    (English: '[Running]'; Localized: '[Spuštěno]'),
    (English: '[Paused]'; Localized: '[Pozastaveno]'),
    (English: 'Read only'; Localized: 'Pouze pro čtení'),
    (English: 'Modified'; Localized: 'Změněno'),
    (English: 'Overwrite'; Localized: 'Přepisování'),
    (English: 'Insert'; Localized: 'Vkládání'),
    (English: 'Tabs closed: %1'; Localized: 'Zavřené karty: %1'),
    (English: 'Estimated time remaining: %1'; Localized: 'Odhadovaný zbývající čas: %1'),
    (English: 'Average KB/sec: %1'; Localized: 'Průměr KB/s: %1'),
    (English: 'There was an error opening the file. Remove it from the list?'; Localized: 'Při otevírání souboru došlo k chybě. Odebrat jej ze seznamu?'),
    (English: 'The text in the %1 file has changed.%n%nDo you want to save the changes?'; Localized: 'Text v souboru %1 byl změněn.%n%nChcete změny uložit?'),
    (English: 'Please stop the compile process before performing this command.'; Localized: 'Před provedením tohoto příkazu zastavte proces kompilace.'),
    (English: 'A compile is already in progress.'; Localized: 'Kompilace již probíhá.'),
    (English: 'The text in the %1 file has changed and must be saved before compiling.%n%nSave the changes and continue?'; Localized: 'Text v souboru %1 byl změněn a před kompilací musí být uložen.%n%nUložit změny a pokračovat?'),
    (English: 'Would you like to save the script before compiling?%n%nIf you answer No, the compiled installation will be placed under your My Documents folder by default.'; Localized: 'Chcete skript před kompilací uložit?%n%nPokud odpovíte Ne, zkompilovaná instalace bude ve výchozím nastavení umístěna do složky Dokumenty.'),
    (English: 'The selected file is an %1 file. Go to its tab instead of opening it as the new main file?'; Localized: 'Vybraný soubor je soubor %1. Přejít na jeho kartu místo otevření jako nového hlavního souboru?'),
    (English: 'The selected file is not available as a tab. Opening as the new main file instead.'; Localized: 'Vybraný soubor není k dispozici jako karta. Otevře se místo toho jako nový hlavní soubor.'),
    (English: 'Error creating file (code %1). Could not save file'; Localized: 'Chyba při vytváření souboru (kód %1). Soubor nelze uložit'),
    (English: 'Error creating backup file. Could not save file'; Localized: 'Chyba při vytváření záložního souboru. Soubor nelze uložit'),
    (English: 'Error removing existing file (code %1). Could not save file'; Localized: 'Chyba při odebírání existujícího souboru (kód %1). Soubor nelze uložit'),
    (English: 'Error renaming temporary file (code %1). Could not save file'; Localized: 'Chyba při přejmenování dočasného souboru (kód %1). Soubor nelze uložit'),
    (English: 'Failed to open included file: %1'; Localized: 'Nepodařilo se otevřít vložený soubor: %1'),
    (English: 'Cannot start printer document.'; Localized: 'Nelze spustit tiskovou úlohu.'),
    (English: 'Are you sure you want to clear the list of recently opened files?'; Localized: 'Opravdu chcete vymazat seznam naposledy otevřených souborů?'),
    (English: 'The %1 file has been modified outside of the source editor. You might want to reload it.'; Localized: 'Soubor %1 byl změněn mimo editor zdrojového kódu. Možná jej budete chtít znovu načíst.'),
    (English: 'The %1 file has been modified outside of the source editor.%n%nDo you want to reload the file?'; Localized: 'Soubor %1 byl změněn mimo editor zdrojového kódu.%n%nChcete soubor znovu načíst?'),
    (English: 'The %1 file has been modified outside of the source editor. Changes have also been made in the source editor.%n%nDo you want to reload the file and lose the changes made in the source editor?'; Localized: 'Soubor %1 byl změněn mimo editor zdrojového kódu. Změny byly provedeny také v editoru zdrojového kódu.%n%nChcete soubor znovu načíst a přijít o změny provedené v editoru zdrojového kódu?'),
    (English: 'File not opened.'; Localized: 'Soubor nebyl otevřen.'),
    (English: 'Go to Line'; Localized: 'Přejít na řádek'),
    (English: 'Line number:'; Localized: 'Číslo řádku:'),
    (English: 'Do you want to copy your current license key to the clipboard before opening our order page? You will need it to be able to renew it.'; Localized: 'Chcete před otevřením naší objednávkové stránky zkopírovat svůj aktuální licenční klíč do schránky? Budete jej potřebovat k obnovení licence.'),
    (English: 'New commercial license key has been registered:%n%n%1%n%nThanks for your support!'; Localized: 'Nový komerční licenční klíč byl zaregistrován:%n%n%1%n%nDěkujeme za vaši podporu!'),
    (English: 'Are you sure you want to remove your commercial license key and revert to non-commercial use only?'; Localized: 'Opravdu chcete odebrat svůj komerční licenční klíč a vrátit se pouze k nekomerčnímu použití?'),
    (English: 'Commercial license key has been removed.'; Localized: 'Komerční licenční klíč byl odebrán.'),
    (English: 'Your version of Inno Setup has been updated! <a id="%1">See what''s new</a>.'; Localized: 'Vaše verze Inno Setup byla aktualizována! <a id="%1">Podívejte se na novinky</a>.'),
    (English: 'VS Code-style editor shortcuts added! Use the <a id="%1">Editor Keys option</a> in Options dialog.'; Localized: 'Byly přidány klávesové zkratky editoru ve stylu VS Code! Použijte možnost <a id="%1">Klávesy editoru</a> v dialogu Možnosti.'),
    (English: 'Inno Setup Compiler is available in your language! Use the <a id="%1">Language option</a> in Options dialog.'; Localized: 'Inno Setup Compiler je k dispozici ve vašem jazyce! Použijte možnost <a id="%1">Jazyk</a> v dialogu Možnosti.'),
    (English: '<a id="%1">Ideas board is open!</a> Share your ideas and vote on others, this month only.'; Localized: '<a id="%1">Nástěnka nápadů je otevřená!</a> Sdílejte své nápady a hlasujte o ostatních, pouze tento měsíc.'),
    (English: 'Running a version released after your update entitlement ended. <a id="%1">Renew license</a>, <a id="%2">remove key</a>, or <a id="%3">exit</a>.'; Localized: 'Používáte verzi vydanou po skončení vašeho nároku na aktualizace. <a id="%1">Obnovit licenci</a>, <a id="%2">odebrat klíč</a> nebo <a id="%3">ukončit</a>.'),
    (English: 'Your update entitlement is ending soon. Please <a id="%1">renew your license</a>. Thanks!'; Localized: 'Váš nárok na aktualizace brzy skončí. <a id="%1">Obnovte si licenci</a>. Děkujeme!'),
    (English: 'Your update entitlement has ended. Please <a id="%1">renew your license</a>. Thanks!'; Localized: 'Váš nárok na aktualizace skončil. <a id="%1">Obnovte si licenci</a>. Děkujeme!'),
    (English: 'Using Inno Setup commercially? Please <a id="%1">purchase a license</a>. Thanks!'; Localized: 'Používáte Inno Setup komerčně? <a id="%1">Zakupte si licenci</a>. Děkujeme!'),
    (English: 'Uninstall'; Localized: 'Uninstall'),
    (English: '%1 exit code: 0x%2'; Localized: 'Návratový kód %1: 0x%2'),
    (English: '%1 exit code: %2'; Localized: 'Návratový kód %1: %2'),
    (English: 'Unable to get %1 exit code (%2 failed)'; Localized: 'Nelze získat návratový kód %1 (%2 selhalo)'),
    (English: '%1 is still running; can''t get exit code'; Localized: '%1 stále běží; nelze získat návratový kód'),
    (English: 'Please stop the running %1 process before performing this command.'; Localized: 'Před provedením tohoto příkazu zastavte běžící proces %1.'),
    (English: 'This command will detach the debugger from the running %1 process. Continue?'; Localized: 'Tento příkaz odpojí ladicí program od běžícího procesu %1. Pokračovat?'),
    (English: 'The changes you made will not take effect until you re-compile.%n%nContinue running anyway?'; Localized: 'Provedené změny se projeví až po opětovné kompilaci.%n%nPřesto pokračovat ve spuštění?'),
    (English: 'A pause is already pending.'; Localized: 'Pozastavení již čeká na provedení.'),
    (English: 'No code was generated for the current line.'; Localized: 'Pro aktuální řádek nebyl vygenerován žádný kód.'),
    (English: 'This will unconditionally terminate the running %1 process. Continue?'; Localized: 'Tímto bezpodmínečně ukončíte běžící proces %1. Pokračovat?'),
    (English: 'Note that if %1 is currently in the installation phase, any changes made to the system thus far will not be undone, nor will uninstall data be written.'; Localized: 'Mějte na paměti, že pokud je %1 právě ve fázi instalace, dosud provedené změny systému nebudou vráceny zpět a nebudou zapsány ani informace pro odinstalaci.'),
    (English: 'Evaluate'; Localized: 'Vyhodnotit'),
    (English: 'Constant to evaluate (for example, "%1"):'; Localized: 'Konstanta k vyhodnocení (například "%1"):'),
    (English: 'Evaluate Result'; Localized: 'Výsledek vyhodnocení'),
    (English: 'Evaluate Error'; Localized: 'Chyba vyhodnocení'),
    (English: 'An unknown error occurred.'; Localized: 'Došlo k neznámé chybě.'),
    (English: '%1 = "%2"'; Localized: '%1 = "%2"'),
    (English: '%1 = Exception: %2'; Localized: '%1 = Výjimka: %2'),
    (English: '%1 = Unknown error'; Localized: '%1 = Neznámá chyba'),
    (English: 'Unknown error'; Localized: 'Neznámá chyba'),
    (English: 'Line %1:%n%2'; Localized: 'Řádek %1:%n%2'),
    (English: 'Runtime Error'; Localized: 'Chyba za běhu'),
    (English: '%1 (Update entitlement ended)'; Localized: '%1 (Nárok na aktualizace skončil)'),
    (English: '%1 (Update entitlement ended but updated anyway)'; Localized: '%1 (Nárok na aktualizace skončil, ale přesto aktualizováno)'),
    (English: 'Non-commercial use only'; Localized: 'Pouze nekomerční použití'),
    (English: 'Single User'; Localized: 'Jeden uživatel'),
    (English: 'Team'; Localized: 'Tým'),
    (English: 'Enterprise'; Localized: 'Enterprise'),
    (English: 'Inno Setup %1 License'; Localized: 'Licence Inno Setup %1'),
    (English: '%1, %2.'; Localized: '%1, %2.'),
    (English: 'Includes updates until %1, major and minor.'; Localized: 'Zahrnuje aktualizace do %1, hlavní i dílčí.'),
    (English: 'Includes all future updates, major and minor.'; Localized: 'Zahrnuje všechny budoucí aktualizace, hlavní i dílčí.'),
    (English: '%1 Entries Designer'; Localized: 'Návrhář položek %1'),
    (English: '&Insert'; Localized: '&Vložit'),
    (English: '&Parameters...'; Localized: '&Parametry...'),
    (English: 'Remo&ve'; Localized: 'O&debrat'),
    (English: 'Add Fol&der...'; Localized: 'Přidat s&ložku...'),
    (English: '&Add File(s)...'; Localized: 'Přidat &soubory...'),
    (English: '&Files:'; Localized: 'S&oubory:'),
    (English: 'Add D&ownload...'; Localized: 'Přidat sta&hování...'),
    (English: 'Go to File'; Localized: 'Přejít na soubor'),
    (English: 'Enter Commercial License Key'; Localized: 'Zadat komerční licenční klíč'),
    (English: 'Paste your license key below'; Localized: 'Vložte svůj licenční klíč níže'),
    (English: 'Close'; Localized: 'Zavřít'),
    (English: 'New Main Script (%1)'; Localized: 'Nový hlavní skript (%1)'),
    (English: 'Open Main Script (%1)'; Localized: 'Otevřít hlavní skript (%1)'),
    (English: 'Save (%1)'; Localized: 'Uložit (%1)'),
    (English: 'Stop Compile (%1)'; Localized: 'Zastavit kompilaci (%1)'),
    (English: 'Target Setup (%1)'; Localized: 'Nastavit jako cíl Setup (%1)'),
    (English: 'Target Uninstall (%1)'; Localized: 'Nastavit jako cíl Uninstall (%1)'),
    (English: 'Help (%1)'; Localized: 'Nápověda (%1)'),
    (English: 'Main Script'; Localized: 'Hlavní skript'),
    (English: 'Close Banner'; Localized: 'Zavřít banner'),
    (English: '&File'; Localized: '&Soubor'),
    (English: '&Open...'; Localized: '&Otevřít...'),
    (English: 'Open &Recent'; Localized: 'Otevřít na&posledy otevřené'),
    (English: '&Clear Recently Opened'; Localized: '&Vymazat naposledy otevřené'),
    (English: '&Save'; Localized: '&Uložit'),
    (English: 'Save &As...'; Localized: 'Uložit &jako...'),
    (English: 'Save &Encoding'; Localized: 'Uložit &kódování'),
    (English: '&Auto (ANSI or UTF-8)'; Localized: '&Automaticky (ANSI nebo UTF-8)'),
    (English: '&UTF-8'; Localized: '&UTF-8'),
    (English: 'UTF-8 with &BOM'; Localized: 'UTF-8 s &BOM'),
    (English: 'Sa&ve All'; Localized: 'Uložit &vše'),
    (English: '&Print...'; Localized: '&Tisk...'),
    (English: 'E&xit'; Localized: 'Kone&c'),
    (English: '&Edit'; Localized: '&Upravit'),
    (English: '&Undo'; Localized: '&Zpět'),
    (English: '&Redo'; Localized: 'Znov&u'),
    (English: 'Cu&t'; Localized: 'Vy&jmout'),
    (English: '&Copy'; Localized: '&Kopírovat'),
    (English: '&Paste'; Localized: '&Vložit'),
    (English: 'De&lete'; Localized: '&Odstranit'),
    (English: 'Select &All'; Localized: 'Vy&brat vše'),
    (English: 'Add Next &Occurrence'; Localized: 'Při&dat další výskyt'),
    (English: '&Select All Occurrences'; Localized: 'Vyb&rat všechny výskyty'),
    (English: 'Select All Find &Matches'; Localized: 'Vybrat všechny s&hody hledání'),
    (English: '&Find...'; Localized: '&Najít...'),
    (English: 'F&ind in Files...'; Localized: 'Najít v &souborech...'),
    (English: 'Find &Next'; Localized: 'Najít d&alší'),
    (English: 'Find Pre&vious'; Localized: 'Najít &předchozí'),
    (English: 'R&eplace...'; Localized: 'Nahrad&it...'),
    (English: 'Use Regular E&xpressions'; Localized: 'Použít re&gulární výrazy'),
    (English: 'Fol&d Section'; Localized: 'Sba&lit sekci'),
    (English: '&Unfold Section'; Localized: 'Rozbalit sek&ci'),
    (English: 'Go to File...'; Localized: 'Přejít na soubor...'),
    (English: '&Go to Line...'; Localized: 'Přejít na řád&ek...'),
    (English: 'Toggle Line Comment'; Localized: 'Přepnout komentář řádku'),
    (English: 'Go To Matching Brace'; Localized: 'Přejít na odpovídající závorku'),
    (English: '&View'; Localized: '&Zobrazit'),
    (English: '&Zoom'; Localized: 'Př&iblížení'),
    (English: 'Zoom &In'; Localized: '&Přiblížit'),
    (English: 'Zoom &Out'; Localized: '&Oddálit'),
    (English: '&Reset'; Localized: 'O&bnovit'),
    (English: '&Toolbar'; Localized: 'Pa&nel nástrojů'),
    (English: 'St&atus Bar'; Localized: '&Stavový řádek'),
    (English: '&Next Tab'; Localized: 'Další ka&rta'),
    (English: '&Previous Tab'; Localized: '&Předchozí karta'),
    (English: 'C&lose Tab'; Localized: 'Z&avřít kartu'),
    (English: 'Re&open Tab'; Localized: 'Znovu &otevřít kartu'),
    (English: 'Reopen &All Tabs'; Localized: 'Zno&vu otevřít všechny karty'),
    (English: 'C&lose Current Tab'; Localized: 'Z&avřít aktuální kartu'),
    (English: '&Compiler Output'; Localized: 'Výstup &kompilátoru'),
    (English: '&Debug Output'; Localized: 'Výstup &ladění'),
    (English: 'D&ebug Call Stack'; Localized: 'Záso&bník volání ladění'),
    (English: '&Find Results'; Localized: 'Výsledky &hledání'),
    (English: '&Hide Bottom Pane'; Localized: 'Skrýt &dolní podokno'),
    (English: '&Word Wrap'; Localized: 'Zala&mování řádků'),
    (English: '&Build'; Localized: 'S&estavení'),
    (English: '&Compile'; Localized: '&Kompilovat'),
    (English: 'S&top Compile'; Localized: '&Zastavit kompilaci'),
    (English: '&Low Priority During Compile'; Localized: '&Nízká priorita během kompilace'),
    (English: '&Disable Output'; Localized: 'Zakázat &výstup'),
    (English: 'Disable Co&mpression'; Localized: 'Zakázat ko&mpresi'),
    (English: 'Disable &Signing'; Localized: 'Zakázat &podepisování'),
    (English: 'Disable Signcheck &Validation'; Localized: 'Zakázat ověření sign&check'),
    (English: '&Open Output Folder'; Localized: '&Otevřít výstupní složku'),
    (English: '&Run'; Localized: 'S&pustit'),
    (English: '&Run...'; Localized: '&Spustit...'),
    (English: 'Run to &Cursor'; Localized: 'Spustit &ke kurzoru'),
    (English: 'Step &Into'; Localized: 'Krokovat s &vnořením'),
    (English: 'Step &Over'; Localized: 'Krokovat &bez vnoření'),
    (English: 'Step Out'; Localized: 'Krokovat s vystoupením'),
    (English: 'Toggle &Breakpoint'; Localized: 'Přepnout &zarážku'),
    (English: '&Delete All Breakpoints'; Localized: 'O&dstranit všechny zarážky'),
    (English: 'P&ause'; Localized: 'P&ozastavit'),
    (English: '&Terminate'; Localized: '&Ukončit'),
    (English: '&Evaluate Constant...'; Localized: 'Vy&hodnotit konstantu...'),
    (English: 'Target &Setup'; Localized: '&Nastavit jako cíl Setup'),
    (English: 'Target &Uninstall'; Localized: 'Nastavit &jako cíl Uninstall'),
    (English: '&Tools'; Localized: '&Nástroje'),
    (English: '&Add/Remove Programs'; Localized: '&Přidat nebo odebrat programy'),
    (English: 'Generate &GUID'; Localized: 'Vygenerovat &GUID'),
    (English: 'Generate %1 Entries...'; Localized: 'Vygenerovat položky %1...'),
    (English: 'Generate %1 Call...'; Localized: 'Vygenerovat volání %1...'),
    (English: '&Configure Sign Tools...'; Localized: '&Konfigurovat nástroje pro podepisování...'),
    (English: '&Options...'; Localized: '&Možnosti...'),
    (English: '&Help'; Localized: 'Nápo&věda'),
    (English: 'Purchase or Renew Commercial &License'; Localized: 'Zakoupit nebo obnovit komerční &licenci'),
    (English: 'Enter Commercial License &Key...'; Localized: '&Zadat komerční licenční klíč...'),
    (English: 'Remove Commercial License Key'; Localized: 'Odebrat komerční licenční klíč'),
    (English: '&Donate'; Localized: '&Přispět'),
    (English: '&Keyboard And Mouse Commands'; Localized: 'Příkazy &klávesnice a myši'),
    (English: 'Regular E&xpressions'; Localized: 'Re&gulární výrazy'),
    (English: 'Inno &Setup Documentation'; Localized: 'Dokumentace Inno &Setup'),
    (English: 'Inno Setup &Example Scripts'; Localized: '&Ukázkové skripty Inno Setup'),
    (English: 'Inno Setup &FAQ'; Localized: 'Časté dotazy k Inno Setup (&FAQ)'),
    (English: 'Inno Setup &Mailing List'; Localized: 'E-&mailová konference Inno Setup'),
    (English: 'Inno Setup &Revision History'; Localized: '&Historie revizí Inno Setup'),
    (English: 'Inno Setup &Web Site'; Localized: '&Webové stránky Inno Setup'),
    (English: 'Inno Setup &Preprocessor Documentation'; Localized: '&Dokumentace k Inno Setup Preprocessor'),
    (English: '&About Inno Setup'; Localized: '&O aplikaci Inno Setup'),
    (English: '%1 Call Designer'; Localized: 'Návrhář volání %1'),
    (English: 'Instruction'; Localized: 'Pokyn'),
    (English: 'Message'; Localized: 'Zpráva'),
    (English: 'Buttons'; Localized: 'Tlačítka'),
    (English: ' Type '; Localized: ' Typ '),
    (English: 'Suppressible'; Localized: 'Potlačitelné'),
    (English: ' Flags '; Localized: ' Příznaky '),
    (English: 'Default button'; Localized: 'Výchozí tlačítko'),
    (English: ' Icon '; Localized: ' Ikona '),
    (English: ' Return values '; Localized: ' Návratové hodnoty '),
    (English: '&Preview'; Localized: '&Náhled'),
    (English: 'Options'; Localized: 'Možnosti'),
    (English: ' Miscellaneous '; Localized: ' Různé '),
    (English: 'Show &Welcome dialog at startup'; Localized: 'Při spuštění zobrazit dialo&g Vítejte'),
    (English: 'Use the Inno Setup &Script Wizard'; Localized: 'Používat Průvodce &skriptem Inno Setup'),
    (English: 'Automatically sa&ve before compiling'; Localized: 'Před kompilací automatick&y ukládat'),
    (English: 'Create &backups when saving'; Localized: 'Při ukládání vytvářet &zálohy'),
    (English: 'Allow &Undo after save'; Localized: 'Povolit &Zpět po uložení'),
    (English: 'Display &full path in title bar'; Localized: 'Zobrazovat úplnou &cestu v záhlaví'),
    (English: '&Pause on exceptions'; Localized: 'Pozastavit při vý&jimkách'),
    (English: '&Launch Setup/Uninstall as administrator'; Localized: 'Setup/Uninstall spo&uštět jako správce'),
    (English: 'Colori&ze "Compiler Output" view'; Localized: 'Oba&rvit zobrazení "Výstup kompilátoru"'),
    (English: 'Automatically open %1 files'; Localized: 'Automaticky otevírat soubory %1'),
    (English: 'Automatically show preprocessor output'; Localized: 'Automaticky zobrazovat výstup preprocesoru'),
    (English: 'Menu &keys:'; Localized: 'Klávesy &nabídek:'),
    (English: 'Automatically reload files'; Localized: 'Automaticky znovu načítat soubory'),
    (English: 'Allow Undo after reload'; Localized: 'Povolit Zpět po opětovném načtení'),
    (English: 'Keep new %1 files closed'; Localized: 'Nové soubory %1 ponechat zavřené'),
    (English: 'Language:'; Localized: 'Jazyk:'),
    (English: ' Editor '; Localized: ' Editor '),
    (English: 'Invoke autoco&mplete automatically'; Localized: '&Automaticky vyvolávat automatické dokončování'),
    (English: 'Use syntax &highlighting'; Localized: 'Použít zvýraznění synta&xe'),
    (English: 'U&nderline syntax errors'; Localized: 'Podtr&hávat syntaktické chyby'),
    (English: 'Allow cursor to move beyond &end of lines'; Localized: 'Povolit pohyb kurzoru za kon&ec řádků'),
    (English: 'Enable section f&olding'; Localized: 'Povolit s&kládání sekcí'),
    (English: 'Use tab cha&racter'; Localized: 'Použít znak ta&bulátoru'),
    (English: 'Auto &indent mode'; Localized: 'Rež&im automatického odsazení'),
    (English: 'Show indentation &guides'; Localized: 'Zobrazovat vo&dítka odsazení'),
    (English: 'Font:'; Localized: 'Písmo:'),
    (English: 'AaBbXxZz'; Localized: 'AaBbXxZz'),
    (English: '&Change...'; Localized: 'Z&měnit...'),
    (English: '&Tab Width:'; Localized: 'Šířka &tabulátoru:'),
    (English: 'Show &line numbers in gutter'; Localized: 'Zobrazovat čís&la řádků na okraji'),
    (English: 'T&heme:'; Localized: 'M&otiv:'),
    (English: 'Highlight occurrences of current selection'; Localized: 'Zvýraznit výskyty aktuálního výběru'),
    (English: 'Highlight occurrences of current wor&d'; Localized: 'Z&výraznit výskyty aktuálního slova'),
    (English: 'Ke&ys:'; Localized: 'Kláves&y:'),
    (English: 'Show whitespace'; Localized: 'Zobrazit prázdné znaky'),
    (English: 'Smart Home key'; Localized: 'Chytrá klávesa Home'),
    (English: '&Associate .%1 files with this compiler'; Localized: '&Přidružit soubory .%1 k tomuto kompilátoru'),
    (English: '&Windows registry file (.%1) to import:'; Localized: 'Soubor registru &Windows (.%1) k importu:'),
    (English: 'B&rowse...'; Localized: 'P&rocházet...'),
    (English: 'Settings (for all keys and values):'; Localized: 'Nastavení (pro všechny klíče a hodnoty):'),
    (English: 'Also delete keys which are not empty'; Localized: 'Odstranit také klíče, které nejsou prázdné'),
    (English: 'Delete keys which are empty on uninstall'; Localized: 'Při odinstalaci odstranit klíče, které jsou prázdné'),
    (English: 'Delete values on uninstall'; Localized: 'Při odinstalaci odstranit hodnoty'),
    (English: 'Minimum Windows version:'; Localized: 'Minimální verze Windows:'),
    (English: 'Configure Sign Tools'; Localized: 'Konfigurovat nástroje pro podepisování'),
    (English: ' Sign Tools '; Localized: ' Nástroje pro podepisování '),
    (English: '&Add...'; Localized: '&Přidat...'),
    (English: '&Edit...'; Localized: '&Upravit...'),
    (English: 'Be notified by e-mail of new Inno Setup releases'; Localized: 'Dostávejte e-mailem upozornění na nová vydání Inno Setup'),
    (English: 'Subscribe'; Localized: 'Přihlásit se k odběru'),
    (English: ' New file '; Localized: ' Nový soubor '),
    (English: 'Create a new &empty script file'; Localized: 'Vytvořit nový &prázdný soubor skriptu'),
    (English: 'Create a new script file using the &Script Wizard'; Localized: '&Vytvořit nový soubor skriptu pomocí Průvodce skriptem'),
    (English: ' Open file '; Localized: ' Otevřít soubor '),
    (English: 'Open an e&xisting script file'; Localized: 'Otevřít e&xistující soubor skriptu'),
    (English: '&Don''t show this dialog again'; Localized: '&Tento dialog příště nezobrazovat'),
    (English: 'Script Wizard File'; Localized: 'Soubor Průvodce skriptem'),
    (English: 'bold'; Localized: 'tučně'),
    (English: ' = required'; Localized: ' = povinné'),
    (English: ' Destination '; Localized: ' Cíl '),
    (English: 'Destination &base folder:'; Localized: 'Cílová &základní složka:'),
    (English: 'Destination &subfolder:'; Localized: 'Cílová &podsložka:'),
    (English: 'Destination &name:'; Localized: 'Cílový &název:'),
    (English: ' Source '; Localized: ' Zdroj '),
    (English: '&Source file or folder:'; Localized: 'Zdrojový &soubor nebo složka:'),
    (English: '&Recurse subfolders'; Localized: 'P&rocházet podsložky rekurzivně'),
    (English: '&Include empty subfolders'; Localized: 'Za&hrnout prázdné podsložky'),
    (English: '&Extract archive'; Localized: '&Extrahovat archiv'),
    (English: 'Welcome to the %1'; Localized: 'Vítá vás %1'),
    (English: 'This wizard will guide you through the process of creating a new Inno Setup script file. The results will be used to generate a new script file which can be compiled directly or saved on disk for later use.%n%n'+'Not all features of Inno Setup are covered by this wizard. See the documentation for details on creating Inno Setup script files.%n%nClick Next to continue, or Cancel to exit this wizard.'; Localized: 'Tento průvodce vás provede procesem vytváření nového souboru skriptu Inno Setup. Výsledky budou použity k vygenerování nového souboru skriptu, který lze přímo zkompilovat nebo uložit na disk pro pozdější použití.%n%n'+'Tento průvodce nepokrývá všechny funkce Inno Setup. Podrobnosti o vytváření souborů skriptů Inno Setup najdete v dokumentaci.%n%nPokračujte kliknutím na Další, nebo tohoto průvodce ukončete kliknutím na Zrušit.'),
    (English: 'Application na&me:'; Localized: '&Název aplikace:'),
    (English: 'Application &version:'; Localized: 'Ve&rze aplikace:'),
    (English: 'Application &publisher:'; Localized: '&Vydavatel aplikace:'),
    (English: 'Application &website:'; Localized: '&Web aplikace:'),
    (English: 'Application folder na&me:'; Localized: '&Název složky aplikace:'),
    (English: 'Application &destination base folder:'; Localized: '&Cílová základní složka aplikace:'),
    (English: 'Other:'; Localized: 'Jiné:'),
    (English: 'Allow user to &change the application folder'; Localized: 'Povolit uživateli z&měnit složku aplikace'),
    (English: 'The application doe&sn''t need a folder'; Localized: '&Aplikace nepotřebuje složku'),
    (English: 'Other application &files:'; Localized: '&Ostatní soubory aplikace:'),
    (English: 'Application &main executable file:'; Localized: 'Hla&vní spustitelný soubor aplikace:'),
    (English: 'Allow &user to start the application after Setup has finished'; Localized: 'Povolit &uživateli spustit aplikaci po dokončení instalace'),
    (English: 'The application doe&sn''t have a main executable file'; Localized: '&Aplikace nemá hlavní spustitelný soubor'),
    (English: 'Application file type na&me:'; Localized: '&Název typu souboru aplikace:'),
    (English: '&Associate a file type to the main executable'; Localized: '&Přidružit typ souboru k hlavnímu spustitelnému souboru'),
    (English: 'Application file type &extension:'; Localized: 'Příp&ona typu souboru aplikace:'),
    (English: 'Application &Start Menu folder name:'; Localized: '&Název složky aplikace v nabídce Start:'),
    (English: 'Other shortcuts to the main executable:'; Localized: 'Ostatní zástupci hlavního spustitelného souboru:'),
    (English: 'Allow user to &change the Start Menu folder name'; Localized: 'Povolit uživateli z&měnit název složky nabídky Start'),
    (English: 'Allow user to &disable Start Menu folder creation'; Localized: 'Povolit uživateli za&kázat vytvoření složky nabídky Start'),
    (English: 'Allow user to create a deskto&p shortcut'; Localized: 'Povolit uživateli vytvořit zástupce na &ploše'),
    (English: 'Create an &Uninstall shortcut in the Start Menu folder'; Localized: 'Vytvořit zástupce &Uninstall ve složce nabídky Start'),
    (English: 'Create an &Internet shortcut in the Start Menu folder'; Localized: 'Vytvořit &internetového zástupce ve složce nabídky Start'),
    (English: '&Create a Start Menu shortcut but no folder'; Localized: '&Vytvořit zástupce v nabídce Start, ale žádnou složku'),
    (English: '&License file:'; Localized: 'Soubor &licence:'),
    (English: '&Information file shown before installation:'; Localized: '&Informační soubor zobrazený před instalací:'),
    (English: 'Information file shown &after installation:'; Localized: 'Informační soubor zobrazený &po instalaci:'),
    (English: 'Install mode:'; Localized: 'Režim instalace:'),
    (English: '&Administrative install mode (install for all users)'; Localized: '&Režim instalace pro správce (instalace pro všechny uživatele)'),
    (English: 'Non a&dministrative install mode (install for current user only)'; Localized: 'Režim instalace &bez práv správce (instalace jen pro aktuálního uživatele)'),
    (English: 'Allow user to &override the install mode via the command line'; Localized: 'Povolit uživateli &přepsat režim instalace přes příkazový řádek'),
    (English: 'Ask the user to &choose the install mode at startup'; Localized: 'Při spuštění požádat uživatele o &volbu režimu instalace'),
    (English: '&Languages:'; Localized: '&Jazyky:'),
    (English: '&Deselect All'; Localized: 'Z&rušit výběr všech'),
    (English: 'Custom compiler output fol&der:'; Localized: '&Vlastní výstupní složka kompilátoru:'),
    (English: 'Compiler output base &file name:'; Localized: 'Zá&kladní název souboru výstupu kompilátoru:'),
    (English: 'Custom Setup &icon file:'; Localized: 'Vlastní soubor &ikony pro Setup:'),
    (English: 'Setup &password:'; Localized: '&Heslo pro Setup:'),
    (English: 'Use the password to &encrypt the application files'; Localized: 'Použít heslo k zašifrování &souborů aplikace'),
    (English: '&Wizard style:'; Localized: '&Styl průvodce:'),
    (English: 'You have successfully completed the %1.%n%nTo close this wizard and generate the new script file, click Finish.'; Localized: 'Úspěšně jste dokončili %1.%n%nChcete-li tohoto průvodce zavřít a vygenerovat nový soubor skriptu, klikněte na Dokončit.'),
    (English: '&Back'; Localized: '&Zpět'),
    (English: '''%s'' is not a valid integer value'; Localized: '''%s'' není platná celočíselná hodnota'),
    (English: '''%s'' is not a valid integer value for %s type'; Localized: '''%s'' není platná celočíselná hodnota pro typ %s'),
    (English: '''%s'' is not a valid floating point value'; Localized: '''%s'' není platná hodnota s plovoucí desetinnou čárkou'),
    (English: '''%d.%d'' is not a valid timestamp'; Localized: '''%d.%d'' není platné časové razítko'),
    (English: '''%s'' is not a valid GUID value'; Localized: '''%s'' není platná hodnota GUID'),
    (English: 'Invalid argument to time encode'; Localized: 'Neplatný argument pro kódování času'),
    (English: 'Invalid argument to date encode'; Localized: 'Neplatný argument pro kódování data'),
    (English: 'Out of memory'; Localized: 'Nedostatek paměti'),
    (English: 'I/O error %d'; Localized: 'Chyba vstupu/výstupu %d'),
    (English: 'File not found'; Localized: 'Soubor nenalezen'),
    (English: 'Invalid filename'; Localized: 'Neplatný název souboru'),
    (English: 'Too many open files'; Localized: 'Příliš mnoho otevřených souborů'),
    (English: 'File access denied'; Localized: 'Přístup k souboru odepřen'),
    (English: 'Read beyond end of file'; Localized: 'Čtení za koncem souboru'),
    (English: 'Disk full'; Localized: 'Disk je plný'),
    (English: 'Invalid numeric input'; Localized: 'Neplatný číselný vstup'),
    (English: 'Division by zero'; Localized: 'Dělení nulou'),
    (English: 'Range check error'; Localized: 'Chyba kontroly rozsahu'),
    (English: 'Integer overflow'; Localized: 'Přetečení celého čísla'),
    (English: 'Invalid floating point operation'; Localized: 'Neplatná operace s plovoucí desetinnou čárkou'),
    (English: 'Floating point division by zero'; Localized: 'Dělení nulou při operaci s plovoucí desetinnou čárkou'),
    (English: 'Floating point overflow'; Localized: 'Přetečení při operaci s plovoucí desetinnou čárkou'),
    (English: 'Floating point underflow'; Localized: 'Podtečení při operaci s plovoucí desetinnou čárkou'),
    (English: 'Invalid pointer operation'; Localized: 'Neplatná operace s ukazatelem'),
    (English: 'Invalid class typecast'; Localized: 'Neplatné přetypování třídy'),
    (English: 'Access violation at address %p. %s of address %p'; Localized: 'Porušení přístupu na adrese %p. %s adresy %p'),
    (English: 'Access violation'; Localized: 'Porušení přístupu'),
    (English: 'Stack overflow'; Localized: 'Přetečení zásobníku'),
    (English: 'Control-C hit'; Localized: 'Stisknuto Control-C'),
    (English: 'Privileged instruction'; Localized: 'Privilegovaná instrukce'),
    (English: 'Operation aborted'; Localized: 'Operace přerušena'),
    (English: 'Exception %s in module %s at %p.'#13#10'%s%s'#13#10; Localized: 'Výjimka %s v modulu %s na %p.'#13#10'%s%s'#13#10),
    (English: 'Application Error'; Localized: 'Chyba aplikace'),
    (English: 'Format ''%s'' invalid or incompatible with argument'; Localized: 'Formát ''%s'' je neplatný nebo nekompatibilní s argumentem'),
    (English: 'No argument for format ''%s'''; Localized: 'Žádný argument pro formát ''%s'''),
    (English: 'Variant method calls not supported'; Localized: 'Volání metod typu Variant nejsou podporována'),
    (English: 'Read'; Localized: 'Čtení'),
    (English: 'Write'; Localized: 'Zápis'),
    (English: 'Execution'; Localized: 'Spuštění'),
    (English: 'Invalid access'; Localized: 'Neplatný přístup'),
    (English: 'Error creating variant or safe array'; Localized: 'Chyba při vytváření pole typu variant nebo safe array'),
    (English: 'Variant or safe array index out of bounds'; Localized: 'Index pole typu variant nebo safe array mimo rozsah'),
    (English: 'Variant or safe array is locked'; Localized: 'Pole typu variant nebo safe array je uzamčeno'),
    (English: 'Invalid variant type conversion'; Localized: 'Neplatná konverze typu variant'),
    (English: 'Invalid variant operation'; Localized: 'Neplatná operace s typem variant'),
    (English: 'Invalid NULL variant operation'; Localized: 'Neplatná operace s hodnotou NULL typu variant'),
    (English: 'Invalid variant operation (%s%.8x)'#10'%s'; Localized: 'Neplatná operace s typem variant (%s%.8x)'#10'%s'),
    (English: 'Could not convert variant of type (%s) into type (%s)'; Localized: 'Nelze převést variant typu (%s) na typ (%s)'),
    (English: 'Overflow while converting variant of type (%s) into type (%s)'; Localized: 'Přetečení při převodu variantu typu (%s) na typ (%s)'),
    (English: 'Variant overflow'; Localized: 'Přetečení typu variant'),
    (English: 'Invalid argument'; Localized: 'Neplatný argument'),
    (English: 'Invalid variant type'; Localized: 'Neplatný typ variant'),
    (English: 'Operation not supported'; Localized: 'Operace není podporována'),
    (English: 'Unexpected variant error'; Localized: 'Neočekávaná chyba typu variant'),
    (English: 'External exception %x'; Localized: 'Externí výjimka %x'),
    (English: 'Assertion failed'; Localized: 'Kontrolní výraz selhal'),
    (English: 'Interface not supported'; Localized: 'Rozhraní není podporováno'),
    (English: 'Exception in safecall method'; Localized: 'Výjimka v metodě safecall'),
    (English: 'Object lock not owned'; Localized: 'Zámek objektu není vlastněn'),
    (English: 'Monitor support function not initialized'; Localized: 'Podpůrná funkce monitoru není inicializována'),
    (English: 'Feature not implemented'; Localized: 'Funkce není implementována'),
    (English: 'Method called on disposed object'; Localized: 'Metoda volána na uvolněném objektu'),
    (English: '%s (%s, line %d)'; Localized: '%s (%s, řádek %d)'),
    (English: 'Abstract Error'; Localized: 'Abstraktní chyba'),
    (English: 'Access violation at address %p in module ''%s'' (offset %x). %s of address %p'; Localized: 'Porušení přístupu na adrese %p v modulu ''%s'' (offset %x). %s adresy %p'),
    (English: 'System Error.  Code: %d.'#13#10'%s%s'; Localized: 'Chyba systému.  Kód: %d.'#13#10'%s%s'),
    (English: 'A call to an OS function failed'; Localized: 'Volání funkce operačního systému selhalo'),
    (English: 'Jan'; Localized: 'led'),
    (English: 'Feb'; Localized: 'úno'),
    (English: 'Mar'; Localized: 'bře'),
    (English: 'Apr'; Localized: 'dub'),
    (English: 'May'; Localized: 'květen'),
    (English: 'Jun'; Localized: 'čvn'),
    (English: 'Jul'; Localized: 'čvc'),
    (English: 'Aug'; Localized: 'srp'),
    (English: 'Sep'; Localized: 'zář'),
    (English: 'Oct'; Localized: 'říj'),
    (English: 'Nov'; Localized: 'lis'),
    (English: 'Dec'; Localized: 'pro'),
    (English: 'January'; Localized: 'leden'),
    (English: 'February'; Localized: 'únor'),
    (English: 'March'; Localized: 'březen'),
    (English: 'April'; Localized: 'duben'),
    (English: 'June'; Localized: 'červen'),
    (English: 'July'; Localized: 'červenec'),
    (English: 'August'; Localized: 'srpen'),
    (English: 'September'; Localized: 'září'),
    (English: 'October'; Localized: 'říjen'),
    (English: 'November'; Localized: 'listopad'),
    (English: 'December'; Localized: 'prosinec'),
    (English: 'Sun'; Localized: 'ne'),
    (English: 'Mon'; Localized: 'po'),
    (English: 'Tue'; Localized: 'út'),
    (English: 'Wed'; Localized: 'st'),
    (English: 'Thu'; Localized: 'čt'),
    (English: 'Fri'; Localized: 'pá'),
    (English: 'Sat'; Localized: 'so'),
    (English: 'Sunday'; Localized: 'neděle'),
    (English: 'Monday'; Localized: 'pondělí'),
    (English: 'Tuesday'; Localized: 'úterý'),
    (English: 'Wednesday'; Localized: 'středa'),
    (English: 'Thursday'; Localized: 'čtvrtek'),
    (English: 'Friday'; Localized: 'pátek'),
    (English: 'Saturday'; Localized: 'sobota'),
    (English: 'Invalid source array'; Localized: 'Neplatné zdrojové pole'),
    (English: 'Invalid destination array'; Localized: 'Neplatné cílové pole'),
    (English: 'Character index out of bounds (%d)'; Localized: 'Index znaku mimo rozsah (%d)'),
    (English: 'Start index out of bounds (%d)'; Localized: 'Počáteční index mimo rozsah (%d)'),
    (English: 'Invalid count (%d)'; Localized: 'Neplatný počet (%d)'),
    (English: 'Invalid destination index (%d)'; Localized: 'Neplatný cílový index (%d)'),
    (English: 'Invalid code page'; Localized: 'Neplatná znaková stránka'),
    (English: 'No mapping for the Unicode character exists in the target multi-byte code page'; Localized: 'Pro znak Unicode neexistuje mapování v cílové vícebajtové znakové stránce'),
    (English: 'Invalid StringBaseIndex'; Localized: 'Neplatný StringBaseIndex'),
    (English: '''%s'' is not a valid %s color value'; Localized: '''%s'' není platná hodnota barvy %s'),
    (English: 'Ancestor for ''%s'' not found'; Localized: 'Předek pro ''%s'' nenalezen'),
    (English: 'Cannot assign a %s to a %s'; Localized: 'Nelze přiřadit %s k %s'),
    (English: 'Bits index out of range'; Localized: 'Index bitů mimo rozsah'),
    (English: 'Can''t write to a read-only resource stream'; Localized: 'Nelze zapisovat do datového proudu prostředků určeného pouze pro čtení'),
    (English: '''''%s'''' expected'; Localized: '''''%s'''' očekáváno'),
    (English: 'CheckSynchronize called from thread $%x, which is NOT the main thread'; Localized: 'CheckSynchronize voláno z vlákna $%x, které NENÍ hlavní vlákno'),
    (English: 'Class %s not found'; Localized: 'Třída %s nenalezena'),
    (English: 'A class named %s already exists'; Localized: 'Třída s názvem %s již existuje'),
    (English: 'List does not allow duplicates ($0%x)'; Localized: 'Seznam nepovoluje duplicity ($0%x)'),
    (English: 'A component named %s already exists'; Localized: 'Komponenta s názvem %s již existuje'),
    (English: 'String list does not allow duplicates'; Localized: 'Seznam řetězců nepovoluje duplicity'),
    (English: 'Cannot create file "%s". %s'; Localized: 'Nelze vytvořit soubor "%s". %s'),
    (English: 'Cannot open file "%s". %s'; Localized: 'Nelze otevřít soubor "%s". %s'),
    (English: 'Identifier expected'; Localized: 'Očekáván identifikátor'),
    (English: 'Invalid binary value'; Localized: 'Neplatná binární hodnota'),
    (English: 'Invalid stream format'; Localized: 'Neplatný formát datového proudu'),
    (English: '''%s'' is an invalid mask at (%d)'; Localized: '''%s'' je neplatná maska na (%d)'),
    (English: '''''%s'''' is not a valid component name'; Localized: '''''%s'''' není platný název komponenty'),
    (English: 'Invalid property value'; Localized: 'Neplatná hodnota vlastnosti'),
    (English: 'Invalid property path'; Localized: 'Neplatná cesta vlastnosti'),
    (English: 'Invalid data type for ''%s'''; Localized: 'Neplatný datový typ pro ''%s'''),
    (English: 'Invalid string constant'; Localized: 'Neplatná řetězcová konstanta'),
    (English: 'Line too long'; Localized: 'Řádek je příliš dlouhý'),
    (English: 'List capacity out of bounds (%d)'; Localized: 'Kapacita seznamu mimo rozsah (%d)'),
    (English: 'List count out of bounds (%d)'; Localized: 'Počet položek seznamu mimo rozsah (%d)'),
    (English: 'List index out of bounds (%d)'; Localized: 'Index seznamu mimo rozsah (%d)'),
    (English: '.  %s range is 0..%d'; Localized: '.  Rozsah %s je 0..%d'),
    (English: '.  %s is empty'; Localized: '.  %s je prázdný'),
    (English: 'Out of memory while expanding memory stream'; Localized: 'Nedostatek paměti při rozšiřování paměťového datového proudu'),
    (English: '%s has not been registered as a COM class'; Localized: '%s nebyl zaregistrován jako třída COM'),
    (English: 'Printer is not currently printing'; Localized: 'Tiskárna momentálně netiskne'),
    (English: 'Number expected'; Localized: 'Očekáváno číslo'),
    (English: 'ANSI or UTF8 encoding expected'; Localized: 'Očekáváno kódování ANSI nebo UTF8'),
    (English: '%s on line %d'; Localized: '%s na řádku %d'),
    (English: 'Error reading %s%s%s: %s'; Localized: 'Chyba při čtení %s%s%s: %s'),
    (English: 'Printing in progress'; Localized: 'Probíhá tisk'),
    (English: 'Stream read error'; Localized: 'Chyba čtení datového proudu'),
    (English: 'Property is read-only'; Localized: 'Vlastnost je pouze pro čtení'),
    (English: 'Failed to create key %s'; Localized: 'Nepodařilo se vytvořit klíč %s'),
    (English: 'Failed to get data for ''%s'''; Localized: 'Nepodařilo se získat data pro ''%s'''),
    (English: 'Failed to set data for ''%s'''; Localized: 'Nepodařilo se nastavit data pro ''%s'''),
    (English: 'Resource %s not found'; Localized: 'Prostředek %s nenalezen'),
    (English: '%s.Seek not implemented'; Localized: '%s.Seek není implementováno'),
    (English: 'Operation not allowed on sorted list'; Localized: 'Operace není povolena u seřazeného seznamu'),
    (English: 'String expected'; Localized: 'Očekáván řetězec'),
    (English: '%s expected'; Localized: 'Očekáváno %s'),
    (English: '%s not in a class registration group'; Localized: '%s není v registrační skupině tříd'),
    (English: 'Property %s does not exist'; Localized: 'Vlastnost %s neexistuje'),
    (English: 'Stream write error'; Localized: 'Chyba zápisu datového proudu'),
    (English: 'Thread creation error: %s'; Localized: 'Chyba při vytváření vlákna: %s'),
    (English: 'Thread Error: %s (%d)'; Localized: 'Chyba vlákna: %s (%d)'),
    (English: 'Cannot terminate an externally created thread'; Localized: 'Nelze ukončit externě vytvořené vlákno'),
    (English: 'Cannot wait for an externally created thread'; Localized: 'Nelze čekat na externě vytvořené vlákno'),
    (English: 'Cannot call Start on a running or suspended thread'; Localized: 'Nelze volat Start na běžícím nebo pozastaveném vlákně'),
    (English: 'Parameter %s cannot be nil'; Localized: 'Parametr %s nesmí být nil'),
    (English: 'Parameter %s cannot be a negative value'; Localized: 'Parametr %s nesmí být záporná hodnota'),
    (English: 'Invalid characters in path'; Localized: 'Neplatné znaky v cestě'),
    (English: 'Invalid characters in search pattern'; Localized: 'Neplatné znaky ve vyhledávacím vzoru'),
    (English: 'Path is empty'; Localized: 'Cesta je prázdná'),
    (English: 'Search pattern is empty'; Localized: 'Vyhledávací vzor je prázdný'),
    (English: 'The specified path is too long'; Localized: 'Zadaná cesta je příliš dlouhá'),
    (English: 'The specified path was not found'; Localized: 'Zadaná cesta nebyla nalezena'),
    (English: 'The path format is not supported'; Localized: 'Formát cesty není podporován'),
    (English: 'No help viewer that supports filters'; Localized: 'Žádný prohlížeč nápovědy nepodporuje filtry'),
    (English: 'String index out of range (%d).  Must be >= %d and <= %d'; Localized: 'Index řetězce mimo rozsah (%d).  Musí být >= %d a <= %d'),
    (English: 'Invalid UTF32 character value.  Must be >= 0 and <= $10FFFF, excluding surrogate pair ranges'; Localized: 'Neplatná hodnota znaku UTF32.  Musí být >= 0 a <= $10FFFF, s výjimkou rozsahů náhradních párů'),
    (English: 'High surrogate char without a following low surrogate char at index: %d. Check that the string is encoded properly'; Localized: 'Vysoký náhradní znak bez následujícího nízkého náhradního znaku na indexu: %d. Zkontrolujte, zda je řetězec správně zakódován'),
    (English: 'Low surrogate char without a preceding high surrogate char at index: %d. Check that the string is encoded properly'; Localized: 'Nízký náhradní znak bez předcházejícího vysokého náhradního znaku na indexu: %d. Zkontrolujte, zda je řetězec správně zakódován'),
    (English: 'Source and Destination arrays must not be the same'; Localized: 'Zdrojové a cílové pole nesmějí být stejné'),
    (English: 'SpinCount out of range. Must be between 0 and %d'; Localized: 'SpinCount mimo rozsah. Musí být mezi 0 a %d'),
    (English: 'No context-sensitive help installed'; Localized: 'Není nainstalována kontextová nápověda'),
    (English: 'No help found for context %d'; Localized: 'Pro kontext %d nebyla nalezena žádná nápověda'),
    (English: 'Unable to open Index'; Localized: 'Nelze otevřít rejstřík'),
    (English: 'Unable to open Search'; Localized: 'Nelze otevřít hledání'),
    (English: 'Unable to find a Table of Contents'; Localized: 'Nelze najít obsah'),
    (English: 'No topic-based help system installed'; Localized: 'Není nainstalován systém nápovědy založený na tématech'),
    (English: 'No help found for %s'; Localized: 'Pro %s nebyla nalezena žádná nápověda'),
    (English: 'Argument out of range'; Localized: 'Argument mimo rozsah'),
    (English: 'Argument must not be nil'; Localized: 'Argument nesmí být nil'),
    (English: 'Item not found'; Localized: 'Položka nenalezena'),
    (English: 'Duplicates not allowed'; Localized: 'Duplicity nejsou povoleny'),
    (English: 'Insufficient RTTI available to support this operation'; Localized: 'K podpoře této operace není k dispozici dostatek RTTI'),
    (English: 'Parameter count mismatch'; Localized: 'Neshoda počtu parametrů'),
    (English: 'Parameter count exceeded'; Localized: 'Překročen počet parametrů'),
    (English: 'Type ''%s'' is not declared in the interface section of a unit'; Localized: 'Typ ''%s'' není deklarován v sekci interface jednotky'),
    (English: 'VAR and OUT arguments must match parameter type exactly'; Localized: 'Argumenty VAR a OUT musí přesně odpovídat typu parametru'),
    (English: 'Property ''%s'' is read-only'; Localized: 'Vlastnost ''%s'' je pouze pro čtení'),
    (English: 'Property ''%s'' is write-only'; Localized: 'Vlastnost ''%s'' je pouze pro zápis'),
    (English: 'RTTI objects cannot be manually destroyed by application code'; Localized: 'Objekty RTTI nelze ručně zničit kódem aplikace'),
    (English: '%s (Version %d.%d, Build %d, %5:s)'; Localized: '%s (verze %d.%d, sestavení %d, %5:s)'),
    (English: '%s Service Pack %4:d (Version %1:d.%2:d, Build %3:d, %5:s)'; Localized: '%s Service Pack %4:d (verze %1:d.%2:d, sestavení %3:d, %5:s)'),
    (English: '32-bit Edition'; Localized: '32bitová edice'),
    (English: '64-bit Edition'; Localized: '64bitová edice'),
    (English: 'Windows'; Localized: 'Windows'),
    (English: 'Windows Vista'; Localized: 'Windows Vista'),
    (English: 'Windows Server 2008'; Localized: 'Windows Server 2008'),
    (English: 'Windows 7'; Localized: 'Windows 7'),
    (English: 'Windows Server 2008 R2'; Localized: 'Windows Server 2008 R2'),
    (English: 'Windows 2000'; Localized: 'Windows 2000'),
    (English: 'Windows XP'; Localized: 'Windows XP'),
    (English: 'Windows Server 2003'; Localized: 'Windows Server 2003'),
    (English: 'Windows Server 2003 R2'; Localized: 'Windows Server 2003 R2'),
    (English: 'Windows Server 2012'; Localized: 'Windows Server 2012'),
    (English: 'Windows Server 2012 R2'; Localized: 'Windows Server 2012 R2'),
    (English: 'Windows Server 2016'; Localized: 'Windows Server 2016'),
    (English: 'Windows Server 2019'; Localized: 'Windows Server 2019'),
    (English: 'Windows Server 2022'; Localized: 'Windows Server 2022'),
    (English: 'Windows 8'; Localized: 'Windows 8'),
    (English: 'Windows 8.1'; Localized: 'Windows 8.1'),
    (English: 'Windows 10'; Localized: 'Windows 10'),
    (English: 'Windows 11'; Localized: 'Windows 11'),
    (English: 'Cannot create instance of class %s'; Localized: 'Nelze vytvořit instanci třídy %s'),
    (English: 'Observer is not supported'; Localized: 'Pozorovatel není podporován'),
    (English: 'Cannot have multiple single cast observers added to the observers collection'; Localized: 'Do kolekce pozorovatelů nelze přidat více pozorovatelů typu single cast'),
    (English: 'The object does not implement the observer interface'; Localized: 'Objekt neimplementuje rozhraní pozorovatele'),
    (English: 'No single cast observer with ID %d was added to the observer collection'; Localized: 'Do kolekce pozorovatelů nebyl přidán žádný pozorovatel typu single cast s ID %d'),
    (English: 'No multi cast observer with ID %d was added to the observer collection'; Localized: 'Do kolekce pozorovatelů nebyl přidán žádný pozorovatel typu multi cast s ID %d'),
    (English: 'Observer is not available'; Localized: 'Pozorovatel není k dispozici'),
    (English: 'SHA2: Cannot update a finalized hash'; Localized: 'SHA2: Nelze aktualizovat dokončený hash'),
    (English: 'Must wait on at least one event'; Localized: 'Je nutné čekat alespoň na jednu událost'),
    (English: 'Cannot call BeginInvoke on a TComponent in the process of destruction'; Localized: 'Nelze volat BeginInvoke na komponentě TComponent, která se právě ničí'),
    (English: 'OLE error %.8x'; Localized: 'Chyba OLE %.8x'),
    (English: 'Method ''%s'' not supported by automation object'; Localized: 'Metoda ''%s'' není podporována objektem automatizace'),
    (English: 'Variant does not reference an automation object'; Localized: 'Variant neodkazuje na objekt automatizace'),
    (English: 'Dispatch methods do not support more than 64 parameters'; Localized: 'Metody dispatch nepodporují více než 64 parametrů'),
    (English: 'A regular expression specified in RegEx is required'; Localized: 'Je vyžadován regulární výraz zadaný v RegEx'),
    (English: 'Error in regular expression at offset %d: %s'; Localized: 'Chyba v regulárním výrazu na offsetu %d: %s'),
    (English: 'Successful match required'; Localized: 'Je vyžadována úspěšná shoda'),
    (English: 'Index out of bounds (%d)'; Localized: 'Index mimo rozsah (%d)'),
    (English: 'Bitmap image is not valid'; Localized: 'Obrázek bitmapy není platný'),
    (English: 'Icon image is not valid'; Localized: 'Obrázek ikony není platný'),
    (English: 'Metafile is not valid'; Localized: 'Metasoubor není platný'),
    (English: 'Invalid pixel format'; Localized: 'Neplatný formát pixelů'),
    (English: 'Invalid image'; Localized: 'Neplatný obrázek'),
    (English: 'Scan line index out of range'; Localized: 'Index řádku rastru mimo rozsah'),
    (English: 'Cannot change the size of an icon'; Localized: 'Nelze změnit velikost ikony'),
    (English: 'Cannot change the size of a WIC Image'; Localized: 'Nelze změnit velikost obrázku WIC'),
    (English: 'Unsupported clipboard format'; Localized: 'Nepodporovaný formát schránky'),
    (English: 'Unsupported stream format'; Localized: 'Nepodporovaný formát datového proudu'),
    (English: 'Out of system resources'; Localized: 'Nedostatek systémových prostředků'),
    (English: 'Canvas does not allow drawing'; Localized: 'Plátno neumožňuje kreslení'),
    (English: 'Text format flag ''%s'' not supported'; Localized: 'Příznak formátu textu ''%s'' není podporován'),
    (English: 'Invalid image frame index %d: there are %d frames (0-%d)'; Localized: 'Neplatný index snímku obrázku %d: existuje %d snímků (0-%d)'),
    (English: 'Invalid image size'; Localized: 'Neplatná velikost obrázku'),
    (English: 'Invalid ImageList'; Localized: 'Neplatný ImageList'),
    (English: 'Invalid ImageList Index'; Localized: 'Neplatný index ImageList'),
    (English: 'Failed to read ImageList data from stream'; Localized: 'Nepodařilo se načíst data ImageList z datového proudu'),
    (English: 'Failed to write ImageList data to stream'; Localized: 'Nepodařilo se zapsat data ImageList do datového proudu'),
    (English: 'Error creating window device context'; Localized: 'Chyba při vytváření kontextu zařízení okna'),
    (English: 'Error creating window class'; Localized: 'Chyba při vytváření třídy okna'),
    (English: 'Cannot focus a disabled or invisible window'; Localized: 'Nelze zaměřit zakázané nebo neviditelné okno'),
    (English: 'Control ''%s'' has no parent window'; Localized: 'Ovládací prvek ''%s'' nemá nadřazené okno'),
    (English: '. Path:'#13#10'%s'; Localized: '. Cesta:'#13#10'%s'),
    (English: 'Parent given is not a parent of ''%s'''; Localized: 'Zadaný nadřazený prvek není nadřazeným prvkem ''%s'''),
    (English: 'Cannot hide an MDI Child Form'; Localized: 'Nelze skrýt podřízený formulář MDI'),
    (English: 'Cannot change Visible in OnShow or OnHide'; Localized: 'Nelze změnit Visible v OnShow nebo OnHide'),
    (English: 'Cannot make a visible window modal'; Localized: 'Nelze učinit viditelné okno modálním'),
    (English: 'Scrollbar property out of range'; Localized: 'Vlastnost posuvníku mimo rozsah'),
    (English: '%s property out of range'; Localized: 'Vlastnost %s mimo rozsah'),
    (English: 'Check state can only be set when CheckBoxes is True'; Localized: 'Stav zaškrtnutí lze nastavit pouze tehdy, když je CheckBoxes True'),
    (English: 'Check state incompatible with treeview''s CheckStyles'; Localized: 'Stav zaškrtnutí není kompatibilní s CheckStyles stromového zobrazení'),
    (English: 'Menu index out of range'; Localized: 'Index nabídky mimo rozsah'),
    (English: 'Menu inserted twice'; Localized: 'Nabídka vložena dvakrát'),
    (English: 'Sub-menu is not in menu'; Localized: 'Podnabídka není v nabídce'),
    (English: 'Not enough timers available'; Localized: 'Není k dispozici dostatek časovačů'),
    (English: 'Printer index out of range'; Localized: 'Index tiskárny mimo rozsah'),
    (English: 'Printer selected is not valid'; Localized: 'Vybraná tiskárna není platná'),
    (English: '%s on %s'; Localized: '%s na %s'),
    (English: 'GroupIndex cannot be less than a previous menu item''s GroupIndex'; Localized: 'GroupIndex nemůže být menší než GroupIndex předchozí položky nabídky'),
    (English: 'Cannot create form. No MDI forms are currently active'; Localized: 'Nelze vytvořit formulář. Momentálně nejsou aktivní žádné formuláře MDI'),
    (English: 'Can only modify an image if it contains a bitmap'; Localized: 'Obrázek lze upravit pouze tehdy, pokud obsahuje bitmapu'),
    (English: 'A control cannot have itself as its parent'; Localized: 'Ovládací prvek nemůže mít sám sebe jako nadřazený prvek'),
    (English: 'Control ''%s'' is used on a not main thread'; Localized: 'Ovládací prvek ''%s'' je používán v jiném než hlavním vláknu'),
    (English: '&Yes'; Localized: '&Ano'),
    (English: '&No'; Localized: '&Ne'),
    (English: '&Close'; Localized: '&Zavřít'),
    (English: '&Ignore'; Localized: '&Ignorovat'),
    (English: '&Retry'; Localized: '&Opakovat'),
    (English: '&All'; Localized: '&Vše'),
    (English: 'Cannot drag a form'; Localized: 'Nelze přetáhnout formulář'),
    (English: 'Metafiles'; Localized: 'Metasoubory'),
    (English: 'Enhanced Metafiles'; Localized: 'Rozšířené metasoubory'),
    (English: 'Icons'; Localized: 'Ikony'),
    (English: 'Bitmaps'; Localized: 'Bitmapy'),
    (English: 'TIFF Images'; Localized: 'Obrázky TIFF'),
    (English: 'Warning'; Localized: 'Upozornění'),
    (English: 'Error'; Localized: 'Chyba'),
    (English: 'Information'; Localized: 'Informace'),
    (English: 'Confirm'; Localized: 'Potvrdit'),
    (English: '&Abort'; Localized: '&Přerušit'),
    (English: 'N&o to All'; Localized: 'N&e všem'),
    (English: 'Yes to &All'; Localized: 'Ano &všem'),
    (English: 'BkSp'; Localized: 'BkSp'),
    (English: 'Tab'; Localized: 'Tab'),
    (English: 'Esc'; Localized: 'Esc'),
    (English: 'Enter'; Localized: 'Enter'),
    (English: 'Space'; Localized: 'Mezerník'),
    (English: 'PgUp'; Localized: 'PgUp'),
    (English: 'PgDn'; Localized: 'PgDn'),
    (English: 'End'; Localized: 'End'),
    (English: 'Home'; Localized: 'Home'),
    (English: 'Left'; Localized: 'Left'),
    (English: 'Up'; Localized: 'Up'),
    (English: 'Right'; Localized: 'Right'),
    (English: 'Down'; Localized: 'Down'),
    (English: 'Ins'; Localized: 'Ins'),
    (English: 'Del'; Localized: 'Del'),
    (English: 'Value must be between %d and %d'; Localized: 'Hodnota musí být mezi %d a %d'),
    (English: 'Unable to insert a line'; Localized: 'Nelze vložit řádek'),
    (English: 'Invalid clipboard format'; Localized: 'Neplatný formát schránky'),
    (English: 'Clipboard does not support Icons'; Localized: 'Schránka nepodporuje ikony'),
    (English: 'Cannot open clipboard: %s'; Localized: 'Nelze otevřít schránku: %s'),
    (English: 'Text exceeds memo capacity'; Localized: 'Text překračuje kapacitu pole memo'),
    (English: 'Operation not supported on selected printer'; Localized: 'Operace není podporována na vybrané tiskárně'),
    (English: 'There is no default printer currently selected'; Localized: 'Momentálně není vybrána žádná výchozí tiskárna'),
    (English: 'Menu ''%s'' is already being used by another form'; Localized: 'Nabídka ''%s'' je již používána jiným formulářem'),
    (English: 'Docked control must have a name'; Localized: 'Ukotvený ovládací prvek musí mít název'),
    (English: 'Error removing control from dock tree'; Localized: 'Chyba při odebírání ovládacího prvku ze stromu ukotvení'),
    (English: ' - Dock zone not found'; Localized: ' - Ukotvovací zóna nenalezena'),
    (English: ' - Dock zone has no control'; Localized: ' - Ukotvovací zóna nemá ovládací prvek'),
    (English: 'Error loading dock zone from the stream. Expecting version %d, but found %d.'; Localized: 'Chyba při načítání ukotvovací zóny z datového proudu. Očekávaná verze %d, ale nalezena %d.'),
    (English: 'Multiselect mode must be on for this feature'; Localized: 'Pro tuto funkci musí být zapnut režim vícenásobného výběru'),
    (English: 'Length of value array must be >= length of prompt array'; Localized: 'Délka pole hodnot musí být >= délce pole výzev'),
    (English: 'Prompt array must not be empty'; Localized: 'Pole výzev nesmí být prázdné'),
    (English: '&Username'; Localized: '&Uživatelské jméno'),
    (English: '&Password'; Localized: '&Heslo'),
    (English: '&Domain'; Localized: '&Doména'),
    (English: 'Login'; Localized: 'Přihlášení'),
    (English: 'Separator'; Localized: 'Oddělovač'),
    (English: 'Error setting %s.Count'; Localized: 'Chyba při nastavování %s.Count'),
    (English: 'Listbox (%s) style must be virtual in order to set Count'; Localized: 'Styl seznamu (%s) musí být virtuální, aby bylo možné nastavit Count'),
    (English: 'No OnGetItem event handler assigned'; Localized: 'Není přiřazen žádný obslužný program události OnGetItem'),
    (English: 'Cannot remove shell notification icon'; Localized: 'Nelze odebrat oznamovací ikonu prostředí'),
    (English: '%s requires Windows Vista or later'; Localized: '%s vyžaduje Windows Vista nebo novější'),
    (English: 'Button%d'; Localized: 'Tlačítko%d'),
    (English: 'RadioButton%d'; Localized: 'Přepínač%d'),
    (English: 'Caption cannot be empty'; Localized: 'Titulek nesmí být prázdný'),
    (English: 'Invalid canvas operation'; Localized: 'Neplatná operace plátna'),
    (English: '%s has no owner'; Localized: '%s nemá vlastníka'),
    (English: 'Source and destination require the same owner'; Localized: 'Zdroj a cíl vyžadují stejného vlastníka'),
    (English: '%s cannot be owned by a different canvas'; Localized: '%s nemůže být vlastněn jiným plátnem'),
    (English: 'Not a solid color brush'; Localized: 'Není to štětec s plnou barvou'),
    (English: 'Invalid brush style'; Localized: 'Neplatný styl štětce'),
    (English: 'Unable to load style ''%s'''; Localized: 'Nelze načíst styl ''%s'''),
    (English: 'Unable to load styles: %s'; Localized: 'Nelze načíst styly: %s'),
    (English: 'Style ''%s'' already registered'; Localized: 'Styl ''%s'' je již registrován'),
    (English: 'Style class ''%s'' already registered'; Localized: 'Třída stylu ''%s'' je již registrována'),
    (English: 'Style ''%s'' not found'; Localized: 'Styl ''%s'' nenalezen'),
    (English: 'Style class ''%s'' not found'; Localized: 'Třída stylu ''%s'' nenalezena'),
    (English: 'Invalid style format'; Localized: 'Neplatný formát stylu'),
    (English: 'VCL Style File'; Localized: 'Soubor stylu VCL'),
    (English: 'Class ''%s'' is already registered for ''%s'''; Localized: 'Třída ''%s'' je již registrována pro ''%s'''),
    (English: 'Class ''%s'' is not registered for ''%s'''; Localized: 'Třída ''%s'' není registrována pro ''%s'''),
    (English: '%s parameter cannot be nil'; Localized: 'Parametr %s nesmí být nil'),
    (English: 'A StyleHook class has not been registered for %s'; Localized: 'Pro %s nebyla zaregistrována žádná třída StyleHook'),
    (English: 'Feature not supported by this style'; Localized: 'Funkce není tímto stylem podporována'),
    (English: 'Cannot call BeginInvoke on a control with no parent or window handle'; Localized: 'Nelze volat BeginInvoke na ovládacím prvku bez nadřazeného prvku nebo úchytu okna'),
    (English: 'CardPanel card index is out of range'; Localized: 'Index karty CardPanel je mimo rozsah'),
    (English: 'CardPanel.ActiveCard cannot be nil'; Localized: 'CardPanel.ActiveCard nesmí být nil'),
    (English: 'Invalid index'; Localized: 'Neplatný index'),
    (English: 'Unable to insert an item'; Localized: 'Nelze vložit položku'),
    (English: 'Invalid owner'; Localized: 'Neplatný vlastník'),
    (English: '%s is already associated with %s'; Localized: '%s je již přidružen k %s'),
    (English: 'This control requires version 4.70 or greater of COMCTL32.DLL'; Localized: 'Tento ovládací prvek vyžaduje verzi 4.70 nebo vyšší souboru COMCTL32.DLL'),
    (English: 'ListView item can be added only when OwnerData is False.  Use OnData instead.'; Localized: 'Položku ListView lze přidat pouze tehdy, když je OwnerData False.  Místo toho použijte OnData.'),
    (English: 'This "Portable Network Graphics" image is not valid because it contains invalid pieces of data (crc error)'; Localized: 'Tento obrázek "Portable Network Graphics" není platný, protože obsahuje neplatné části dat (chyba CRC)'),
    (English: 'The "Portable Network Graphics" image could not be loaded because one of its main piece of data (ihdr) might be corrupted'; Localized: 'Obrázek "Portable Network Graphics" nelze načíst, protože jedna z jeho hlavních částí dat (ihdr) může být poškozena'),
    (English: 'This "Portable Network Graphics" image is invalid because it has missing image parts.'; Localized: 'Tento obrázek "Portable Network Graphics" je neplatný, protože v něm chybějí části obrázku.'),
    (English: 'Could not decompress the image because it contains invalid compressed data.'#13#10' Description: '; Localized: 'Obrázek nelze dekomprimovat, protože obsahuje neplatná komprimovaná data.'#13#10' Popis: '),
    (English: 'The "Portable Network Graphics" image contains an invalid palette.'; Localized: 'Obrázek "Portable Network Graphics" obsahuje neplatnou paletu.'),
    (English: 'The file being read is not a valid "Portable Network Graphics" image because it contains an invalid header. This file may be corrupted, try obtaining it again'; Localized: 'Čtený soubor není platný obrázek "Portable Network Graphics", protože obsahuje neplatnou hlavičku. Tento soubor může být poškozen, zkuste jej získat znovu'),
    (English: 'This "Portable Network Graphics" image is not supported or it might be invalid.'#13#10'(IHDR chunk is not the first)'; Localized: 'Tento obrázek "Portable Network Graphics" není podporován nebo může být neplatný.'#13#10'(blok IHDR není první)'),
    (English: 'This "Portable Network Graphics" image is not supported because either its width or height exceeds the maximum size of 65535 pixels.'; Localized: 'Tento obrázek "Portable Network Graphics" není podporován, protože jeho šířka nebo výška překračuje maximální velikost 65535 pixelů.'),
    (English: 'There is no such palette entry.'; Localized: 'Taková položka palety neexistuje.'),
    (English: 'This "Portable Network Graphics" image contains an unknown critical part which could not be decoded.'; Localized: 'Tento obrázek "Portable Network Graphics" obsahuje neznámou kritickou část, kterou nelze dekódovat.'),
    (English: 'This "Portable Network Graphics" image is encoded with an unknown compression scheme which could not be decoded.'; Localized: 'Tento obrázek "Portable Network Graphics" je zakódován neznámým kompresním schématem, které nelze dekódovat.'),
    (English: 'This "Portable Network Graphics" image uses an unknown interlace scheme which could not be decoded.'; Localized: 'Tento obrázek "Portable Network Graphics" používá neznámé schéma prokládání, které nelze dekódovat.'),
    (English: 'This "Portable Network Graphics" image uses an unknown color type which could not be decoded.'; Localized: 'Tento obrázek "Portable Network Graphics" používá neznámý typ barvy, který nelze dekódovat.'),
    (English: 'The chunks must be compatible to be assigned.'; Localized: 'Bloky musí být kompatibilní, aby je bylo možné přiřadit.'),
    (English: 'This "Portable Network Graphics" image is invalid because the decoder found an unexpected end of the file.'; Localized: 'Tento obrázek "Portable Network Graphics" je neplatný, protože dekodér nalezl neočekávaný konec souboru.'),
    (English: 'This "Portable Network Graphics" image contains no data.'; Localized: 'Tento obrázek "Portable Network Graphics" neobsahuje žádná data.'),
    (English: 'The program tried to add a existent critical chunk to the current image which is not allowed.'; Localized: 'Program se pokusil přidat existující kritický blok k aktuálnímu obrázku, což není povoleno.'),
    (English: 'It''s not allowed to add a new chunk because the current image is invalid.'; Localized: 'Není povoleno přidat nový blok, protože aktuální obrázek je neplatný.'),
    (English: 'Some operation could not be performed because the system is out of resources. Close some windows and try again.'; Localized: 'Některou operaci nelze provést, protože systém nemá dostatek prostředků. Zavřete některá okna a zkuste to znovu.'),
    (English: 'Setting bit transparency color is not allowed for png images containing alpha value for each pixel (COLOR_RGBALPHA and COLOR_GRAYSCALEALPHA)'; Localized: 'Nastavení bitové barvy průhlednosti není povoleno u obrázků PNG obsahujících hodnotu alfa pro každý pixel (COLOR_RGBALPHA a COLOR_GRAYSCALEALPHA)'),
    (English: 'This operation is not valid because the current image contains no valid header.'; Localized: 'Tato operace není platná, protože aktuální obrázek neobsahuje platnou hlavičku.'),
    (English: 'The new size provided for image resizing is invalid.'; Localized: 'Nová velikost zadaná pro změnu velikosti obrázku je neplatná.'),
    (English: 'The "Portable Network Graphics" image could not be loaded because it uses an invalid image bit depth.'; Localized: 'Obrázek "Portable Network Graphics" nelze načíst, protože používá neplatnou bitovou hloubku obrázku.'));

implementation

end.
