unit IDE.LocalizeFunc.German;

{
  Inno Setup
  Copyright (C) 1997-2026 Jordan Russell
  Portions by Martijn Laan
  For conditions of distribution and use, see LICENSE.TXT.

  Compiler IDE German translations
}

interface

uses
  IDE.LocalizeFunc;

const
  GermanIDETranslations: array [0..942] of TTranslationPair = (
    (English: 'Command-line usage:'; Localized: 'Befehlszeilenverwendung:'),
    (English: 'Examples:'; Localized: 'Beispiele:'),
    (English: 'script file'; Localized: 'Skriptdatei'),
    (English: 'wizard name'; Localized: 'Assistentenname'),
    (English: 'My script'; Localized: 'Mein Skript'),
    (English: 'My Script Wizard'; Localized: 'Mein Skript-Assistent'),
    (English: 'Could not load %1: %2'; Localized: '%1 konnte nicht geladen werden: %2'),
    (English: 'Inno Setup Compiler'; Localized: 'Inno Setup Compiler'),
    (English: 'Example scripts...'; Localized: 'Beispielskripte...'),
    (English: 'More files...'; Localized: 'Weitere Dateien...'),
    (English: 'Untitled'; Localized: 'Unbenannt'),
    (English: 'Preprocessor Output'; Localized: 'Präprozessor-Ausgabe'),
    (English: 'Run Parameters'; Localized: 'Ausführungsparameter'),
    (English: 'Command-line parameters for %1 and %2:'; Localized: 'Befehlszeilenparameter für %1 und %2:'),
    (English: 'Inno Setup Script files'; Localized: 'Inno Setup-Skriptdateien'),
    (English: 'All files'; Localized: 'Alle Dateien'),
    (English: 'Application files'; Localized: 'Anwendungsdateien'),
    (English: 'Documentation files'; Localized: 'Dokumentationsdateien'),
    (English: 'Rich Text Format files'; Localized: 'Rich-Text-Format-Dateien'),
    (English: 'Registry files'; Localized: 'Registry-Dateien'),
    (English: 'Icon files'; Localized: 'Symboldateien'),
    (English: 'Inno Setup Script Wizard'; Localized: 'Inno Setup Skript-Assistent'),
    (English: 'Welcome'; Localized: 'Willkommen'),
    (English: 'Application Information'; Localized: 'Anwendungsinformationen'),
    (English: 'Please specify some basic information about your application.'; Localized: 'Bitte geben Sie einige grundlegende Informationen zu Ihrer Anwendung an.'),
    (English: 'Application Folder'; Localized: 'Anwendungsordner'),
    (English: 'Please specify folder information about your application.'; Localized: 'Bitte geben Sie Ordnerinformationen zu Ihrer Anwendung an.'),
    (English: 'Application Files'; Localized: 'Anwendungsdateien'),
    (English: 'Please specify the files that are part of your application.'; Localized: 'Bitte geben Sie die Dateien an, die Teil Ihrer Anwendung sind.'),
    (English: 'Please specify the source folder.'; Localized: 'Bitte geben Sie den Quellordner an.'),
    (English: 'Should files in subfolders of "%1" also be included?'; Localized: 'Sollen auch Dateien in Unterordnern von "%1" einbezogen werden?'),
    (English: 'URL:'; Localized: 'URL:'),
    (English: 'Is the file to download an archive which should be extracted?'; Localized: 'Ist die herunterzuladende Datei ein Archiv, das entpackt werden soll?'),
    (English: 'Name of the file:'; Localized: 'Name der Datei:'),
    (English: 'Name of the file (extension should match archive format):'; Localized: 'Name der Datei (Dateierweiterung sollte zum Archivformat passen):'),
    (English: 'Approximate size of the file in megabytes:'; Localized: 'Ungefähre Größe der Datei in Megabyte:'),
    (English: 'Application File Association'; Localized: 'Anwendungsdateizuordnung'),
    (English: 'Please specify which file association should be created for your application.'; Localized: 'Bitte geben Sie an, welche Dateizuordnung für Ihre Anwendung erstellt werden soll.'),
    (English: '%1 File'; Localized: '%1-Datei'),
    (English: 'Application Shortcuts'; Localized: 'Anwendungsverknüpfungen'),
    (English: 'Please specify which shortcuts should be created for your application.'; Localized: 'Bitte geben Sie an, welche Verknüpfungen für Ihre Anwendung erstellt werden sollen.'),
    (English: 'Application Documentation'; Localized: 'Anwendungsdokumentation'),
    (English: 'Please specify which documentation files should be shown by Setup during installation.'; Localized: 'Bitte geben Sie an, welche Dokumentationsdateien von Setup während der Installation angezeigt werden sollen.'),
    (English: 'Setup Install Mode'; Localized: 'Setup-Installationsmodus'),
    (English: 'Please specify in which install mode Setup should run.'; Localized: 'Bitte geben Sie an, in welchem Installationsmodus Setup ausgeführt werden soll.'),
    (English: 'Application Registry Keys And Values'; Localized: 'Registry-Schlüssel und -Werte der Anwendung'),
    (English: 'Please specify the registry keys and values that are part of your application.'; Localized: 'Bitte geben Sie die Registry-Schlüssel und -Werte an, die Teil Ihrer Anwendung sind.'),
    (English: 'Setup Languages'; Localized: 'Setup-Sprachen'),
    (English: 'Please specify which Setup languages should be included.'; Localized: 'Bitte geben Sie an, welche Setup-Sprachen einbezogen werden sollen.'),
    (English: 'Compiler Settings'; Localized: 'Compiler-Einstellungen'),
    (English: 'Please specify some basic compiler settings.'; Localized: 'Bitte geben Sie einige grundlegende Compiler-Einstellungen an.'),
    (English: 'Please specify the folder.'; Localized: 'Bitte geben Sie den Ordner an.'),
    (English: 'Wizard Style'; Localized: 'Assistentenstil'),
    (English: 'Please specify which wizard style should be used.'; Localized: 'Bitte geben Sie an, welcher Assistentenstil verwendet werden soll.'),
    (English: 'Inno Setup Preprocessor'; Localized: 'Inno Setup-Präprozessor'),
    (English: 'Please specify whether Inno Setup Preprocessor should be used.'; Localized: 'Bitte geben Sie an, ob der Inno Setup-Präprozessor verwendet werden soll.'),
    (English: 'The %1 can use %2 compiler directives to simplify your script. Although this is not necessary, it will make it easier to manually change the script later.%n%nDo you want the %1 to use %2 compiler directives?'; Localized: 'Der %1 kann %2-Compilerdirektiven verwenden, um Ihr Skript zu vereinfachen. Obwohl dies nicht notwendig ist, erleichtert es spätere manuelle Änderungen am Skript.%n%nMöchten Sie, dass der %1 %2-Compilerdirektiven verwendet?'),
    (English: '&Yes, use %1 compiler directives'; Localized: '&Ja, %1-Compilerdirektiven verwenden'),
    (English: 'Finished'; Localized: 'Fertiggestellt'),
    (English: '&Next'; Localized: '&Weiter'),
    (English: '&Finish'; Localized: '&Fertigstellen'),
    (English: 'The %1 is not complete. If you quit now, the new script file will not be generated.%n%nExit anyway?'; Localized: 'Der %1 ist nicht vollständig. Wenn Sie jetzt beenden, wird die neue Skriptdatei nicht generiert.%n%nTrotzdem beenden?'),
    (English: 'Please specify the application name.'; Localized: 'Bitte geben Sie den Anwendungsnamen an.'),
    (English: 'Please specify the application version.'; Localized: 'Bitte geben Sie die Anwendungsversion an.'),
    (English: 'Please specify the application destination base folder.'; Localized: 'Bitte geben Sie den Ziel-Basisordner der Anwendung an.'),
    (English: 'Please specify the application folder name.'; Localized: 'Bitte geben Sie den Namen des Anwendungsordners an.'),
    (English: 'Please specify the application main executable file.'; Localized: 'Bitte geben Sie die ausführbare Hauptdatei der Anwendung an.'),
    (English: 'The specified application main executable file does not exist.'; Localized: 'Die angegebene ausführbare Hauptdatei der Anwendung ist nicht vorhanden.'),
    (English: 'Please specify the application Start Menu group name.'; Localized: 'Bitte geben Sie den Namen des Startmenüordners der Anwendung an.'),
    (English: 'Please specify the destination base folder.'; Localized: 'Bitte geben Sie den Ziel-Basisordner an.'),
    (English: 'Please specify a destination base folder other than the application folder.'; Localized: 'Bitte geben Sie einen anderen Ziel-Basisordner als den Anwendungsordner an.'),
    (English: 'Please specify the destination name.'; Localized: 'Bitte geben Sie den Zielnamen an.'),
    (English: 'Please select at least one language.'; Localized: 'Bitte wählen Sie mindestens eine Sprache aus.'),
    (English: '&Source URL:'; Localized: '&Quell-URL:'),
    (English: 'Script generated by the %1.'; Localized: 'Der %1 hat dieses Skript generiert.'),
    (English: 'SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!'; Localized: 'EINZELHEITEN ZUM ERSTELLEN VON INNO SETUP-SKRIPTDATEIEN FINDEN SIE IN DER DOKUMENTATION!'),
    (English: 'NOTE: The value of %1 uniquely identifies this application. Do not use the same %1 value in installers for other applications.'; Localized: 'HINWEIS: Der Wert von %1 identifiziert diese Anwendung eindeutig. Verwenden Sie denselben %1-Wert nicht in Installationsprogrammen für andere Anwendungen.'),
    (English: '(To generate a new GUID, click Tools | Generate GUID inside the IDE.)'; Localized: '(Um eine neue GUID zu generieren, klicken Sie in der IDE auf Extras | GUID generieren.)'),
    (English: '"%1" specifies that Setup cannot run on anything but x64 and Windows 11 on Arm.'; Localized: '"%1" gibt an, dass Setup nur unter x64 und Windows 11 auf Arm ausgeführt werden kann.'),
    (English: '"%1" requests that the install be done in "64-bit mode" on x64 or Windows 11 on Arm.'; Localized: '"%1" fordert, dass die Installation im "64-Bit-Modus" unter x64 oder Windows 11 auf Arm durchgeführt wird.'),
    (English: 'This means it should use the native 64-bit Program Files directory and the 64-bit view of the registry.'; Localized: 'Das bedeutet, dass der native 64-Bit-Ordner "Program Files" und die 64-Bit-Ansicht der Registry verwendet werden sollen.'),
    (English: 'Uncomment the following line to use a 64-bit installer.'; Localized: 'Entfernen Sie das Kommentarzeichen der folgenden Zeile, um ein 64-Bit-Installationsprogramm zu verwenden.'),
    (English: 'Use "%1" if all your archives are .%2 files.'; Localized: 'Verwenden Sie "%1", wenn alle Ihre Archive .%2-Dateien sind.'),
    (English: 'Use "%1" if all your archives are not password-protected.'; Localized: 'Verwenden Sie "%1", wenn keines Ihrer Archive passwortgeschützt ist.'),
    (English: 'Uncomment the following line to run in non administrative install mode (install for current user only).'; Localized: 'Entfernen Sie das Kommentarzeichen der folgenden Zeile, um im nicht administrativen Installationsmodus auszuführen (Installation nur für aktuellen Benutzer).'),
    (English: 'Remove the following line to run in administrative install mode (install for all users).'; Localized: 'Entfernen Sie die folgende Zeile, um im administrativen Installationsmodus auszuführen (Installation für alle Benutzer).'),
    (English: 'NOTE: Don''t use "%1" on any shared system files.'; Localized: 'HINWEIS: Verwenden Sie "%1" nicht für gemeinsam genutzte Systemdateien.'),
    (English: 'NOTE: Use the "%1" flag or the "%2" parameter to verify downloads.'; Localized: 'HINWEIS: Verwenden Sie das Flag "%1" oder den Parameter "%2", um Downloads zu verifizieren.'),
    (English: 'Registry data from file %1'; Localized: 'Registry-Daten aus Datei %1'),
    (English: 'COULD NOT IMPORT %1'; Localized: 'KONNTE %1 NICHT IMPORTIEREN'),
    (English: 'End of registry data from file %1'; Localized: 'Ende der Registry-Daten aus Datei %1'),
    (English: 'SOME KEYS FILTERED DUE TO %1 SETTINGS!'; Localized: 'EINIGE SCHLÜSSEL WURDEN AUFGRUND DER %1-EINSTELLUNGEN GEFILTERT!'),
    (English: 'SOME VALUES WITH UNSUPPORTED TYPES SKIPPED!'; Localized: 'EINIGE WERTE MIT NICHT UNTERSTÜTZTEN TYPEN WURDEN ÜBERSPRUNGEN!'),
    (English: 'Would you like to compile the new script now?'; Localized: 'Möchten Sie das neue Skript jetzt kompilieren?'),
    (English: 'My Program'; Localized: 'Mein Programm'),
    (English: 'My Company, Inc.'; Localized: 'My Company, Inc.'),
    (English: 'Application directory'; Localized: 'Anwendungsordner'),
    (English: 'Program Files directory'; Localized: 'Program Files-Ordner'),
    (English: 'Common Files directory'; Localized: 'Common Files-Ordner'),
    (English: 'Windows directory'; Localized: 'Windows-Ordner'),
    (English: 'Windows system directory'; Localized: 'Windows-Systemordner'),
    (English: 'Setup source directory'; Localized: 'Setup-Quellordner'),
    (English: 'System drive root directory'; Localized: 'Stammordner des Systemlaufwerks'),
    (English: '(Custom)'; Localized: '(Benutzerdefiniert)'),
    (English: 'Starting compile.%1[%2]'; Localized: 'Kompilierung wird gestartet.%1[%2]'),
    (English: 'Finished.%1[%2, %3 elapsed]'; Localized: 'Fertig.%1[%2, %3 vergangen]'),
    (English: 'Compile aborted.'; Localized: 'Kompilierung abgebrochen.'),
    (English: 'Log size limit reached, list reset.'; Localized: 'Maximale Protokollgröße erreicht, Liste zurückgesetzt.'),
    (English: '%1 started'; Localized: '%1 gestartet'),
    (English: 'Terminating process'; Localized: 'Prozess wird beendet'),
    (English: 'Removing left-over temporary directory: %1'; Localized: 'Übrig gebliebener temporärer Ordner wird entfernt: %1'),
    (English: 'Failed to remove temporary directory'; Localized: 'Temporärer Ordner konnte nicht entfernt werden'),
    (English: '%1 Call Stack'; Localized: '%1-Aufrufliste'),
    (English: 'Cannot run Setup at this time. Please compile Setup successfully to completion first, with output enabled'; Localized: 'Setup kann derzeit nicht ausgeführt werden. Bitte kompilieren Sie Setup zuerst vollständig und erfolgreich, mit aktivierter Ausgabe'),
    (English: 'Cannot run Uninstall at this time. Please run Setup successfully to completion first'; Localized: 'Deinstallation kann derzeit nicht ausgeführt werden. Bitte führen Sie Setup zuerst vollständig und erfolgreich aus'),
    (English: 'Error executing "%1":%n%n%2: %3'; Localized: 'Fehler beim Ausführen von "%1":%n%n%2: %3'),
    (English: 'Are you sure you want to abort the compile?'; Localized: 'Möchten Sie die Kompilierung wirklich abbrechen?'),
    (English: 'File %1:'; Localized: 'Datei %1:'),
    (English: 'Line %1:'; Localized: 'Zeile %1:'),
    (English: 'Compiler Error'; Localized: 'Compiler-Fehler'),
    (English: 'Illegal null character on line %1'; Localized: 'Ungültiges Nullzeichen in Zeile %1'),
    (English: 'Cannot find "%1"'; Localized: '"%1" kann nicht gefunden werden'),
    (English: 'Invalid regular expression "%1"'; Localized: 'Ungültiger regulärer Ausdruck "%1"'),
    (English: '%1 (%2 hits):'; Localized: '%1 (%2 Treffer):'),
    (English: 'Find "%1" (%2 hits in %3 files)'; Localized: 'Suche nach "%1" (%2 Treffer in %3 Dateien)'),
    (English: '%1 occurrence(s) replaced.'; Localized: '%1 Vorkommen ersetzt.'),
    (English: 'The .%1 extension was successfully associated for the current user with:%n%2'; Localized: 'Die Dateierweiterung .%1 wurde erfolgreich für den aktuellen Benutzer dem folgenden Programm zugeordnet:%n%2'),
    (English: 'The .%1 extension was successfully associated for all users with:%n%2'; Localized: 'Die Dateierweiterung .%1 wurde erfolgreich für alle Benutzer dem folgenden Programm zugeordnet:%n%2'),
    (English: 'Error creating file association:%n%1 - %2'; Localized: 'Fehler beim Erstellen der Dateizuordnung:%n%1 - %2'),
    (English: 'Unable to associate for all users without administrative privileges. Do you want to associate only for yourself instead?'; Localized: 'Eine Zuordnung für alle Benutzer ist ohne Administratorrechte nicht möglich. Möchten Sie die Zuordnung stattdessen nur für sich selbst vornehmen?'),
    (English: 'Associate'; Localized: 'Zuordnen'),
    (English: 'Inno Setup Script'; Localized: 'Inno Setup-Skript'),
    (English: 'Compi&le'; Localized: '&Kompilieren'),
    (English: '&Script has %1'; Localized: '&Skript enthält %1'),
    (English: 'Script has %1 set'; Localized: 'Im Skript ist %1 gesetzt'),
    (English: 'Invalid file format.'; Localized: 'Ungültiges Dateiformat.'),
    (English: 'Setup'; Localized: 'Setup'),
    (English: 'Your message text.'; Localized: 'Ihr Meldungstext.'),
    (English: 'Enter your text here...'; Localized: 'Geben Sie hier Ihren Text ein...'),
    (English: 'Return values'; Localized: 'Rückgabewerte'),
    (English: 'Default'; Localized: 'Standard'),
    (English: 'Shield'; Localized: 'Schild'),
    (English: 'Instruction Text'; Localized: 'Anweisungstext'),
    (English: 'Message Text'; Localized: 'Meldungstext'),
    (English: 'user clicked %1'; Localized: 'Benutzer hat auf %1 geklickt'),
    (English: 'OK'; Localized: 'OK'),
    (English: 'Yes'; Localized: 'Ja'),
    (English: 'No'; Localized: 'Nein'),
    (English: 'Cancel'; Localized: 'Abbrechen'),
    (English: 'Retry'; Localized: 'Wiederholen'),
    (English: 'Ignore'; Localized: 'Ignorieren'),
    (English: 'Abort'; Localized: 'Abbrechen'),
    (English: 'Display a message box'; Localized: 'Ein Meldungsfeld anzeigen'),
    (English: 'Name of the Sign Tool:'; Localized: 'Name des Signaturtools:'),
    (English: 'Invalid name.'; Localized: 'Ungültiger Name.'),
    (English: 'Duplicate name.'; Localized: 'Doppelter Name.'),
    (English: 'Command of the Sign Tool:'; Localized: 'Befehl des Signaturtools:'),
    (English: 'Invalid command.'; Localized: 'Ungültiger Befehl.'),
    (English: 'The generated GUID will be inserted into the editor at the cursor position. Continue?'; Localized: 'Die generierte GUID wird an der Cursorposition in den Editor eingefügt. Fortfahren?'),
    (English: 'The generated Pascal script will be inserted into the editor at the cursor position, but the cursor is not in the %1 section. Continue anyway?'; Localized: 'Das generierte Pascal-Skript wird an der Cursorposition in den Editor eingefügt, aber der Cursor befindet sich nicht im Abschnitt %1. Trotzdem fortfahren?'),
    (English: 'Classic'; Localized: 'Klassisch'),
    (English: 'Visual Studio / Visual Studio Code'; Localized: 'Visual Studio / Visual Studio Code'),
    (English: 'Classic / Visual Studio'; Localized: 'Klassisch / Visual Studio'),
    (English: 'Visual Studio Code'; Localized: 'Visual Studio Code'),
    (English: 'Light'; Localized: 'Hell'),
    (English: 'Dark'; Localized: 'Dunkel'),
    (English: 'The new language will take effect the next time you start Inno Setup Compiler.'; Localized: 'Die neue Sprache wird beim nächsten Start von Inno Setup Compiler wirksam.'),
    (English: '&New...'; Localized: '&Neu...'),
    (English: '&New'; Localized: '&Neu'),
    (English: 'Line %1'; Localized: 'Zeile %1'),
    (English: '%1: %2'; Localized: '%1: %2'),
    (English: 'Back (%1)'; Localized: 'Zurück (%1)'),
    (English: 'Forward (%1)'; Localized: 'Vorwärts (%1)'),
    (English: 'Ctrl+'; Localized: 'Strg+'),
    (English: 'Shift+'; Localized: 'Umschalt+'),
    (English: 'Alt+'; Localized: 'Alt+'),
    (English: 'Num %1'; Localized: 'Num %1'),
    (English: '(32-bit)'; Localized: '(32-Bit)'),
    (English: '[Compiling]'; Localized: '[Wird kompiliert]'),
    (English: '[Running]'; Localized: '[Wird ausgeführt]'),
    (English: '[Paused]'; Localized: '[Angehalten]'),
    (English: 'Read only'; Localized: 'Schreibgeschützt'),
    (English: 'Modified'; Localized: 'Geändert'),
    (English: 'Overwrite'; Localized: 'Überschreiben'),
    (English: 'Insert'; Localized: 'Einfügen'),
    (English: 'Tabs closed: %1'; Localized: 'Geschlossene Registerkarten: %1'),
    (English: 'Estimated time remaining: %1'; Localized: 'Geschätzte verbleibende Zeit: %1'),
    (English: 'Average KB/sec: %1'; Localized: 'Durchschnittliche KB/s: %1'),
    (English: 'There was an error opening the file. Remove it from the list?'; Localized: 'Beim Öffnen der Datei ist ein Fehler aufgetreten. Aus der Liste entfernen?'),
    (English: 'The text in the %1 file has changed.%n%nDo you want to save the changes?'; Localized: 'Der Text in der Datei %1 wurde geändert.%n%nMöchten Sie die Änderungen speichern?'),
    (English: 'Please stop the compile process before performing this command.'; Localized: 'Bitte stoppen Sie den Kompiliervorgang, bevor Sie diesen Befehl ausführen.'),
    (English: 'A compile is already in progress.'; Localized: 'Eine Kompilierung wird bereits ausgeführt.'),
    (English: 'The text in the %1 file has changed and must be saved before compiling.%n%nSave the changes and continue?'; Localized: 'Der Text in der Datei %1 wurde geändert und muss vor dem Kompilieren gespeichert werden.%n%nÄnderungen speichern und fortfahren?'),
    (English: 'Would you like to save the script before compiling?%n%nIf you answer No, the compiled installation will be placed under your My Documents folder by default.'; Localized: 'Möchten Sie das Skript vor dem Kompilieren speichern?%n%nWenn Sie mit Nein antworten, wird die kompilierte Installation standardmäßig in Ihrem Ordner "Eigene Dokumente" abgelegt.'),
    (English: 'The selected file is an %1 file. Go to its tab instead of opening it as the new main file?'; Localized: 'Die ausgewählte Datei ist eine %1-Datei. Zu ihrer Registerkarte wechseln, anstatt sie als neue Hauptdatei zu öffnen?'),
    (English: 'The selected file is not available as a tab. Opening as the new main file instead.'; Localized: 'Die ausgewählte Datei ist nicht als Registerkarte verfügbar. Sie wird stattdessen als neue Hauptdatei geöffnet.'),
    (English: 'Error creating file (code %1). Could not save file'; Localized: 'Fehler beim Erstellen der Datei (Code %1). Datei konnte nicht gespeichert werden'),
    (English: 'Error creating backup file. Could not save file'; Localized: 'Fehler beim Erstellen der Sicherungsdatei. Datei konnte nicht gespeichert werden'),
    (English: 'Error removing existing file (code %1). Could not save file'; Localized: 'Fehler beim Entfernen der vorhandenen Datei (Code %1). Datei konnte nicht gespeichert werden'),
    (English: 'Error renaming temporary file (code %1). Could not save file'; Localized: 'Fehler beim Umbenennen der temporären Datei (Code %1). Datei konnte nicht gespeichert werden'),
    (English: 'Failed to open included file: %1'; Localized: 'Eingebundene Datei konnte nicht geöffnet werden: %1'),
    (English: 'Cannot start printer document.'; Localized: 'Druckdokument kann nicht gestartet werden.'),
    (English: 'Are you sure you want to clear the list of recently opened files?'; Localized: 'Möchten Sie die Liste der zuletzt geöffneten Dateien wirklich löschen?'),
    (English: 'The %1 file has been modified outside of the source editor. You might want to reload it.'; Localized: 'Die Datei %1 wurde außerhalb des Quelltexteditors geändert. Sie sollten sie möglicherweise neu laden.'),
    (English: 'The %1 file has been modified outside of the source editor.%n%nDo you want to reload the file?'; Localized: 'Die Datei %1 wurde außerhalb des Quelltexteditors geändert.%n%nMöchten Sie die Datei neu laden?'),
    (English: 'The %1 file has been modified outside of the source editor. Changes have also been made in the source editor.%n%nDo you want to reload the file and lose the changes made in the source editor?'; Localized: 'Die Datei %1 wurde außerhalb des Quelltexteditors geändert. Es wurden auch Änderungen im Quelltexteditor vorgenommen.%n%nMöchten Sie die Datei neu laden und die im Quelltexteditor vorgenommenen Änderungen verwerfen?'),
    (English: 'File not opened.'; Localized: 'Datei nicht geöffnet.'),
    (English: 'Go to Line'; Localized: 'Gehe zu Zeile'),
    (English: 'Line number:'; Localized: 'Zeilennummer:'),
    (English: 'Could not load file (code %1)'; Localized: 'Datei konnte nicht geladen werden (Code %1)'),
    (English: 'Could not save file (code %1)'; Localized: 'Datei konnte nicht gespeichert werden (Code %1)'),
    (English: 'Do you want to copy your current license key to the clipboard before opening our order page? You will need it to be able to renew it.'; Localized: 'Möchten Sie Ihren aktuellen Lizenzschlüssel in die Zwischenablage kopieren, bevor Sie unsere Bestellseite öffnen? Sie benötigen ihn, um ihn verlängern zu können.'),
    (English: 'New commercial license key has been registered:%n%n%1%n%nThanks for your support!'; Localized: 'Neuer kommerzieller Lizenzschlüssel wurde registriert:%n%n%1%n%nVielen Dank für Ihre Unterstützung!'),
    (English: 'Are you sure you want to remove your commercial license key and revert to non-commercial use only?'; Localized: 'Möchten Sie Ihren kommerziellen Lizenzschlüssel wirklich entfernen und nur zur nicht kommerziellen Nutzung zurückkehren?'),
    (English: 'Commercial license key has been removed.'; Localized: 'Kommerzieller Lizenzschlüssel wurde entfernt.'),
    (English: 'Your version of Inno Setup has been updated! <a id="%1">See what''s new</a>.'; Localized: 'Ihre Version von Inno Setup wurde aktualisiert! <a id="%1">Neuerungen ansehen</a>.'),
    (English: 'VS Code-style editor shortcuts added! Use the <a id="%1">Editor Keys option</a> in Options dialog.'; Localized: 'Editor-Tastenkombinationen im VS Code-Stil hinzugefügt! Verwenden Sie die <a id="%1">Option "Tasten"</a> im Dialog "Optionen".'),
    (English: 'Inno Setup Compiler is available in your language! Use the <a id="%1">Language option</a> in Options dialog.'; Localized: 'Inno Setup Compiler ist in Ihrer Sprache verfügbar! Verwenden Sie die <a id="%1">Option "Sprache"</a> im Dialog "Optionen".'),
    (English: '<a id="%1">Ideas board is open!</a> Share your ideas and vote on others, this month only.'; Localized: '<a id="%1">Das Ideen-Board ist geöffnet!</a> Teilen Sie Ihre Ideen und stimmen Sie über andere ab, nur diesen Monat.'),
    (English: 'Running a version released after your update entitlement ended. <a id="%1">Renew license</a>, <a id="%2">remove key</a>, or <a id="%3">exit</a>.'; Localized: 'Sie verwenden eine Version, die nach dem Ende Ihrer Update-Berechtigung veröffentlicht wurde. <a id="%1">Lizenz verlängern</a>, <a id="%2">Schlüssel entfernen</a> oder <a id="%3">beenden</a>.'),
    (English: 'Your update entitlement is ending soon. Please <a id="%1">renew your license</a>. Thanks!'; Localized: 'Ihre Update-Berechtigung endet bald. Bitte <a id="%1">verlängern Sie Ihre Lizenz</a>. Vielen Dank!'),
    (English: 'Your update entitlement has ended. Please <a id="%1">renew your license</a>. Thanks!'; Localized: 'Ihre Update-Berechtigung ist abgelaufen. Bitte <a id="%1">verlängern Sie Ihre Lizenz</a>. Vielen Dank!'),
    (English: 'Using Inno Setup commercially? Please <a id="%1">purchase a license</a>. Thanks!'; Localized: 'Verwenden Sie Inno Setup kommerziell? Bitte <a id="%1">erwerben Sie eine Lizenz</a>. Vielen Dank!'),
    (English: 'Uninstall'; Localized: 'Deinstallation'),
    (English: '%1 exit code: 0x%2'; Localized: '%1-Exitcode: 0x%2'),
    (English: '%1 exit code: %2'; Localized: '%1-Exitcode: %2'),
    (English: 'Unable to get %1 exit code (%2 failed)'; Localized: '%1-Exitcode konnte nicht abgerufen werden (%2 fehlgeschlagen)'),
    (English: '%1 is still running; can''t get exit code'; Localized: '%1 wird noch ausgeführt; Exitcode kann nicht abgerufen werden'),
    (English: 'Please stop the running %1 process before performing this command.'; Localized: 'Bitte stoppen Sie den laufenden %1-Prozess, bevor Sie diesen Befehl ausführen.'),
    (English: 'This command will detach the debugger from the running %1 process. Continue?'; Localized: 'Mit diesem Befehl wird der Debugger vom laufenden %1-Prozess getrennt. Fortfahren?'),
    (English: 'The changes you made will not take effect until you re-compile.%n%nContinue running anyway?'; Localized: 'Die von Ihnen vorgenommenen Änderungen werden erst nach einer erneuten Kompilierung wirksam.%n%nTrotzdem mit der Ausführung fortfahren?'),
    (English: 'A pause is already pending.'; Localized: 'Eine Pause steht bereits aus.'),
    (English: 'No code was generated for the current line.'; Localized: 'Für die aktuelle Zeile wurde kein Code generiert.'),
    (English: 'This will unconditionally terminate the running %1 process. Continue?'; Localized: 'Hiermit wird der laufende %1-Prozess bedingungslos beendet. Fortfahren?'),
    (English: 'Note that if %1 is currently in the installation phase, any changes made to the system thus far will not be undone, nor will uninstall data be written.'; Localized: 'Beachten Sie: Wenn sich %1 derzeit in der Installationsphase befindet, werden die bisher am System vorgenommenen Änderungen nicht rückgängig gemacht und es werden keine Deinstallationsinformationen geschrieben.'),
    (English: 'Evaluate'; Localized: 'Auswerten'),
    (English: 'Constant to evaluate (for example, "%1"):'; Localized: 'Auszuwertende Konstante (zum Beispiel "%1"):'),
    (English: 'Evaluate Result'; Localized: 'Auswertungsergebnis'),
    (English: 'Evaluate Error'; Localized: 'Auswertungsfehler'),
    (English: 'An unknown error occurred.'; Localized: 'Ein unbekannter Fehler ist aufgetreten.'),
    (English: '%1 = "%2"'; Localized: '%1 = "%2"'),
    (English: '%1 = Exception: %2'; Localized: '%1 = Ausnahme: %2'),
    (English: '%1 = Unknown error'; Localized: '%1 = Unbekannter Fehler'),
    (English: 'Unknown error'; Localized: 'Unbekannter Fehler'),
    (English: 'Line %1:%n%2'; Localized: 'Zeile %1:%n%2'),
    (English: 'Runtime Error'; Localized: 'Laufzeitfehler'),
    (English: '%1 (Update entitlement ended)'; Localized: '%1 (Update-Berechtigung abgelaufen)'),
    (English: '%1 (Update entitlement ended but updated anyway)'; Localized: '%1 (Update-Berechtigung abgelaufen, aber trotzdem aktualisiert)'),
    (English: 'Non-commercial use only'; Localized: 'Nur nicht kommerzielle Nutzung'),
    (English: 'Single User'; Localized: 'Single User'),
    (English: 'Team'; Localized: 'Team'),
    (English: 'Enterprise'; Localized: 'Enterprise'),
    (English: 'Inno Setup %1 License'; Localized: 'Inno Setup %1-Lizenz'),
    (English: '%1, %2.'; Localized: '%1, %2.'),
    (English: 'Includes updates until %1, major and minor.'; Localized: 'Enthält Updates bis %1, Haupt- und Nebenversionen.'),
    (English: 'Includes all future updates, major and minor.'; Localized: 'Enthält alle zukünftigen Updates, Haupt- und Nebenversionen.'),
    (English: '%1 Entries Designer'; Localized: '%1-Einträge-Designer'),
    (English: '&Insert'; Localized: '&Einfügen'),
    (English: '&Parameters...'; Localized: '&Parameter...'),
    (English: 'Remo&ve'; Localized: 'Ent&fernen'),
    (English: 'Add Fol&der...'; Localized: '&Ordner hinzufügen...'),
    (English: '&Add File(s)...'; Localized: '&Datei(en) hinzufügen...'),
    (English: '&Files:'; Localized: 'D&ateien:'),
    (English: 'Add D&ownload...'; Localized: 'Do&wnload hinzufügen...'),
    (English: 'Go to File'; Localized: 'Gehe zu Datei'),
    (English: 'Enter Commercial License Key'; Localized: 'Kommerziellen Lizenzschlüssel eingeben'),
    (English: 'Paste your license key below'; Localized: 'Fügen Sie Ihren Lizenzschlüssel unten ein'),
    (English: 'Close'; Localized: 'Schließen'),
    (English: 'New Main Script (%1)'; Localized: 'Neues Hauptskript (%1)'),
    (English: 'Open Main Script (%1)'; Localized: 'Hauptskript öffnen (%1)'),
    (English: 'Save (%1)'; Localized: 'Speichern (%1)'),
    (English: 'Stop Compile (%1)'; Localized: 'Kompilierung stoppen (%1)'),
    (English: 'Target Setup (%1)'; Localized: 'Setup als Ziel festlegen (%1)'),
    (English: 'Target Uninstall (%1)'; Localized: 'Deinstallation als Ziel festlegen (%1)'),
    (English: 'Help (%1)'; Localized: 'Hilfe (%1)'),
    (English: 'Main Script'; Localized: 'Hauptskript'),
    (English: 'Close Banner'; Localized: 'Banner schließen'),
    (English: '&File'; Localized: '&Datei'),
    (English: '&Open...'; Localized: '&Öffnen...'),
    (English: 'Open &Recent'; Localized: '&Zuletzt verwendet'),
    (English: '&Clear Recently Opened'; Localized: 'Zuletzt geöffnete &löschen'),
    (English: '&Save'; Localized: '&Speichern'),
    (English: 'Save &As...'; Localized: 'Speichern &unter...'),
    (English: 'Save &Encoding'; Localized: '&Codierung speichern'),
    (English: '&Auto (ANSI or UTF-8)'; Localized: '&Automatisch (ANSI oder UTF-8)'),
    (English: '&UTF-8'; Localized: '&UTF-8'),
    (English: 'UTF-8 with &BOM'; Localized: 'UTF-8 mit &BOM'),
    (English: 'Sa&ve All'; Localized: 'A&lles speichern'),
    (English: '&Print...'; Localized: '&Drucken...'),
    (English: 'E&xit'; Localized: '&Beenden'),
    (English: '&Edit'; Localized: '&Bearbeiten'),
    (English: '&Undo'; Localized: 'Rück&gängig'),
    (English: '&Redo'; Localized: 'Wieder&holen'),
    (English: 'Cu&t'; Localized: 'A&usschneiden'),
    (English: '&Copy'; Localized: '&Kopieren'),
    (English: '&Paste'; Localized: 'Ein&fügen'),
    (English: 'De&lete'; Localized: '&Löschen'),
    (English: 'Select &All'; Localized: '&Alles auswählen'),
    (English: 'Add Next &Occurrence'; Localized: 'Nächstes &Vorkommen hinzufügen'),
    (English: '&Select All Occurrences'; Localized: 'Alle V&orkommen auswählen'),
    (English: 'Select All Find &Matches'; Localized: 'Alle &Treffer auswählen'),
    (English: '&Find...'; Localized: '&Suchen...'),
    (English: 'F&ind in Files...'; Localized: 'In &Dateien suchen...'),
    (English: 'Find &Next'; Localized: '&Weitersuchen'),
    (English: 'Find Pre&vious'; Localized: 'Vorheriges Element su&chen'),
    (English: 'R&eplace...'; Localized: 'E&rsetzen...'),
    (English: 'Use Regular E&xpressions'; Localized: 'Reguläre Ausdrücke verwe&nden'),
    (English: 'Fol&d Section'; Localized: 'Abschnitt &einklappen'),
    (English: '&Unfold Section'; Localized: 'Abschnitt auskla&ppen'),
    (English: 'Go to File...'; Localized: 'Gehe zu Datei...'),
    (English: '&Go to Line...'; Localized: 'Gehe zu &Zeile...'),
    (English: 'Toggle Line Comment'; Localized: 'Zeilenkommentar umschalten'),
    (English: 'Go To Matching Brace'; Localized: 'Zur passenden Klammer springen'),
    (English: '&View'; Localized: '&Ansicht'),
    (English: '&Zoom'; Localized: 'Zoo&m'),
    (English: 'Zoom &In'; Localized: '&Vergrößern'),
    (English: 'Zoom &Out'; Localized: 'Ver&kleinern'),
    (English: '&Reset'; Localized: '&Zurücksetzen'),
    (English: '&Toolbar'; Localized: 'S&ymbolleiste'),
    (English: 'St&atus Bar'; Localized: '&Statusleiste'),
    (English: '&Next Tab'; Localized: '&Nächste Registerkarte'),
    (English: '&Previous Tab'; Localized: '&Vorherige Registerkarte'),
    (English: 'C&lose Tab'; Localized: '&Registerkarte schließen'),
    (English: 'Re&open Tab'; Localized: 'Registerkarte erneut &öffnen'),
    (English: 'Reopen &All Tabs'; Localized: '&Alle Registerkarten erneut öffnen'),
    (English: 'C&lose Current Tab'; Localized: 'A&ktuelle Registerkarte schließen'),
    (English: '&Compiler Output'; Localized: '&Compiler-Ausgabe'),
    (English: '&Debug Output'; Localized: '&Debug-Ausgabe'),
    (English: 'D&ebug Call Stack'; Localized: 'Debug-Aufruf&liste'),
    (English: '&Find Results'; Localized: 'Such&ergebnisse'),
    (English: '&Hide Bottom Pane'; Localized: 'Unteren &Bereich ausblenden'),
    (English: '&Word Wrap'; Localized: '&Zeilenumbruch'),
    (English: '&Build'; Localized: '&Erstellen'),
    (English: '&Compile'; Localized: '&Kompilieren'),
    (English: 'S&top Compile'; Localized: 'Kompilierung s&toppen'),
    (English: '&Low Priority During Compile'; Localized: '&Niedrige Priorität beim Kompilieren'),
    (English: '&Disable Output'; Localized: '&Ausgabe deaktivieren'),
    (English: 'Disable Co&mpression'; Localized: 'Ko&mprimierung deaktivieren'),
    (English: 'Disable &Signing'; Localized: '&Signierung deaktivieren'),
    (English: 'Disable Signcheck &Validation'; Localized: 'Signcheck-&Validierung deaktivieren'),
    (English: '&Open Output Folder'; Localized: 'Ausgabeordner &öffnen'),
    (English: '&Run'; Localized: 'A&usführen'),
    (English: '&Run...'; Localized: 'A&usführen...'),
    (English: 'Run to &Cursor'; Localized: 'Ausführen bis &Cursor'),
    (English: 'Step &Into'; Localized: 'E&inzelschritt'),
    (English: 'Step &Over'; Localized: 'Pr&ozedurschritt'),
    (English: 'Step Out'; Localized: 'Rücksprung'),
    (English: 'Toggle &Breakpoint'; Localized: '&Haltepunkt umschalten'),
    (English: '&Delete All Breakpoints'; Localized: 'Alle Haltepunkte &löschen'),
    (English: 'P&ause'; Localized: '&Anhalten'),
    (English: '&Terminate'; Localized: '&Beenden'),
    (English: '&Evaluate Constant...'; Localized: '&Konstante auswerten...'),
    (English: 'Target &Setup'; Localized: '&Setup als Ziel festlegen'),
    (English: 'Target &Uninstall'; Localized: '&Deinstallation als Ziel festlegen'),
    (English: '&Tools'; Localized: 'E&xtras'),
    (English: '&Add/Remove Programs'; Localized: '&Programme hinzufügen/entfernen'),
    (English: 'Generate &GUID'; Localized: '&GUID generieren'),
    (English: 'Generate %1 Entries...'; Localized: '%1-Einträge generieren...'),
    (English: 'Generate %1 Call...'; Localized: '%1-Aufruf generieren...'),
    (English: '&Configure Sign Tools...'; Localized: '&Signaturtools konfigurieren...'),
    (English: 'R&TF Editor...'; Localized: 'R&TF-Editor...'),
    (English: '&Options...'; Localized: '&Optionen...'),
    (English: '&Help'; Localized: '&Hilfe'),
    (English: 'Purchase or Renew Commercial &License'; Localized: 'Kommerzielle &Lizenz erwerben oder verlängern'),
    (English: 'Enter Commercial License &Key...'; Localized: '&Kommerziellen Lizenzschlüssel eingeben...'),
    (English: 'Remove Commercial License Key'; Localized: 'Kommerziellen Lizenzschlüssel entfernen'),
    (English: '&Donate'; Localized: '&Spenden'),
    (English: '&Keyboard And Mouse Commands'; Localized: '&Tastatur- und Mausbefehle'),
    (English: 'Regular E&xpressions'; Localized: 'Reguläre &Ausdrücke'),
    (English: 'Inno &Setup Documentation'; Localized: 'Inno Setup-&Dokumentation'),
    (English: 'Inno Setup &Example Scripts'; Localized: 'Inno Setup-&Beispielskripte'),
    (English: 'Inno Setup &FAQ'; Localized: 'Inno Setup-&FAQ'),
    (English: 'Inno Setup &Mailing List'; Localized: 'Inno Setup-&Mailingliste'),
    (English: 'Inno Setup &Revision History'; Localized: 'Inno Setup-&Revisionsverlauf'),
    (English: 'Inno Setup &Web Site'; Localized: 'Inno Setup-&Website'),
    (English: 'Inno Setup &Preprocessor Documentation'; Localized: 'Inno Setup-&Präprozessor-Dokumentation'),
    (English: '&About Inno Setup'; Localized: '&Über Inno Setup'),
    (English: '%1 Call Designer'; Localized: '%1-Aufruf-Designer'),
    (English: 'Instruction'; Localized: 'Anweisung'),
    (English: 'Message'; Localized: 'Meldung'),
    (English: 'Buttons'; Localized: 'Schaltflächen'),
    (English: ' Type '; Localized: ' Typ '),
    (English: 'Suppressible'; Localized: 'Unterdrückbar'),
    (English: ' Flags '; Localized: ' Flags '),
    (English: 'Default button'; Localized: 'Standardschaltfläche'),
    (English: ' Icon '; Localized: ' Symbol '),
    (English: ' Return values '; Localized: ' Rückgabewerte '),
    (English: '&Preview'; Localized: '&Vorschau'),
    (English: 'Options'; Localized: 'Optionen'),
    (English: ' Miscellaneous '; Localized: ' Verschiedenes '),
    (English: 'Show &Welcome dialog at startup'; Localized: '&Willkommensdialog beim Start anzeigen'),
    (English: 'Use the Inno Setup &Script Wizard'; Localized: 'Inno Setup Skri&pt-Assistent verwenden'),
    (English: 'Automatically sa&ve before compiling'; Localized: '&Vor dem Kompilieren automatisch speichern'),
    (English: 'Create &backups when saving'; Localized: '&Beim Speichern Sicherungskopien erstellen'),
    (English: 'Allow &Undo after save'; Localized: 'Rückgängig nach dem Speichern erla&uben'),
    (English: 'Display &full path in title bar'; Localized: 'Vollständigen P&fad in der Titelleiste anzeigen'),
    (English: '&Pause on exceptions'; Localized: 'Bei Au&snahmen anhalten'),
    (English: '&Launch Setup/Uninstall as administrator'; Localized: 'Setup/Deinstallation als Adm&inistrator starten'),
    (English: 'Colori&ze "Compiler Output" view'; Localized: 'Ansicht "C&ompiler-Ausgabe" einfärben'),
    (English: 'Automatically open %1 files'; Localized: '%1-Dateien automatisch öffnen'),
    (English: 'Automatically show preprocessor output'; Localized: 'Präprozessor-Ausgabe automatisch anzeigen'),
    (English: 'Menu &keys:'; Localized: 'Men&ütasten:'),
    (English: 'Automatically reload files'; Localized: 'Dateien automatisch neu laden'),
    (English: 'Allow Undo after reload'; Localized: 'Rückgängig nach dem Neuladen erlauben'),
    (English: 'Keep new %1 files closed'; Localized: 'Neue %1-Dateien geschlossen halten'),
    (English: 'Language:'; Localized: 'Sprache:'),
    (English: ' Editor '; Localized: ' Editor '),
    (English: 'Invoke autoco&mplete automatically'; Localized: 'Autovervollständigung auto&matisch aufrufen'),
    (English: 'Use syntax &highlighting'; Localized: 'Syntax&hervorhebung verwenden'),
    (English: 'U&nderline syntax errors'; Localized: 'Synta&xfehler unterstreichen'),
    (English: 'Allow cursor to move beyond &end of lines'; Localized: 'Cursor über das Zeilen&ende hinaus bewegen lassen'),
    (English: 'Enable section f&olding'; Localized: 'Abs&chnittsfaltung aktivieren'),
    (English: 'Use tab cha&racter'; Localized: 'Tabulato&rzeichen verwenden'),
    (English: 'Auto &indent mode'; Localized: 'Automatischer Ein&zugsmodus'),
    (English: 'Show indentation &guides'; Localized: 'Einzu&gshilfslinien anzeigen'),
    (English: 'Font:'; Localized: 'Schriftart:'),
    (English: 'AaBbXxZz'; Localized: 'AaBbXxZz'),
    (English: '&Change...'; Localized: '&Ändern...'),
    (English: '&Tab Width:'; Localized: '&Tabbreite:'),
    (English: 'Show &line numbers in gutter'; Localized: 'Zei&lennummern in der Editorleiste anzeigen'),
    (English: 'T&heme:'; Localized: '&Design:'),
    (English: 'Highlight occurrences of current selection'; Localized: 'Vorkommen der aktuellen Auswahl hervorheben'),
    (English: 'Highlight occurrences of current wor&d'; Localized: 'Vor&kommen des aktuellen Worts hervorheben'),
    (English: 'Ke&ys:'; Localized: 'Taste&n:'),
    (English: 'Show whitespace'; Localized: 'Leerzeichen anzeigen'),
    (English: 'Smart Home key'; Localized: 'Intelligente Pos1-Taste'),
    (English: '&Associate .%1 files with this compiler'; Localized: '.%1-D&ateien diesem Compiler zuordnen'),
    (English: '&Windows registry file (.%1) to import:'; Localized: '&Windows-Registry-Datei (.%1) zum Importieren:'),
    (English: 'B&rowse...'; Localized: 'Du&rchsuchen...'),
    (English: 'Settings (for all keys and values):'; Localized: 'Einstellungen (für alle Schlüssel und Werte):'),
    (English: 'Also delete keys which are not empty'; Localized: 'Auch Schlüssel löschen, die nicht leer sind'),
    (English: 'Delete keys which are empty on uninstall'; Localized: 'Bei der Deinstallation leere Schlüssel löschen'),
    (English: 'Delete values on uninstall'; Localized: 'Bei der Deinstallation Werte löschen'),
    (English: 'Minimum Windows version:'; Localized: 'Windows-Mindestversion:'),
    (English: 'RTF Editor'; Localized: 'RTF-Editor'),
    (English: 'New (%1)'; Localized: 'Neu (%1)'),
    (English: 'Open (%1)'; Localized: 'Öffnen (%1)'),
    (English: 'Save As'; Localized: 'Speichern unter'),
    (English: 'Cut (%1)'; Localized: 'Ausschneiden (%1)'),
    (English: 'Copy (%1)'; Localized: 'Kopieren (%1)'),
    (English: 'Paste (%1)'; Localized: 'Einfügen (%1)'),
    (English: 'Undo (%1)'; Localized: 'Rückgängig (%1)'),
    (English: 'Redo (%1)'; Localized: 'Wiederholen (%1)'),
    (English: 'Bold (%1)'; Localized: 'Fett (%1)'),
    (English: 'Italic (%1)'; Localized: 'Kursiv (%1)'),
    (English: 'Underline (%1)'; Localized: 'Unterstrichen (%1)'),
    (English: 'Font'; Localized: 'Schriftart'),
    (English: 'Text Color'; Localized: 'Textfarbe'),
    (English: 'Background Color'; Localized: 'Hintergrundfarbe'),
    (English: '&Bold'; Localized: 'F&ett'),
    (English: '&Italic'; Localized: 'Kurs&iv'),
    (English: '&Underline'; Localized: 'Un&terstrichen'),
    (English: '&Font...'; Localized: 'Schrift&art...'),
    (English: '&Increase Font Size'; Localized: 'Schriftgrad &vergrößern'),
    (English: '&Decrease Font Size'; Localized: 'Schriftgra&d verkleinern'),
    (English: 'Text &Color...'; Localized: 'Te&xtfarbe...'),
    (English: '&Background Color...'; Localized: 'Hintergrundfar&be...'),
    (English: 'Reset &Colors'; Localized: 'Farben zurü&cksetzen'),
    (English: 'Align &Left'; Localized: '&Linksbündig'),
    (English: '&Center'; Localized: '&Zentriert'),
    (English: 'Align &Right'; Localized: '&Rechtsbündig'),
    (English: 'Bulle&ts'; Localized: 'Aufz&ählung'),
    (English: 'Increase &Indent'; Localized: 'E&inzug vergrößern'),
    (English: 'Decrease Inden&t'; Localized: 'Einzug verk&leinern'),
    (English: 'Configure Sign Tools'; Localized: 'Signaturtools konfigurieren'),
    (English: ' Sign Tools '; Localized: ' Signaturtools '),
    (English: '&Add...'; Localized: '&Hinzufügen...'),
    (English: '&Edit...'; Localized: '&Bearbeiten...'),
    (English: 'Be notified by e-mail of new Inno Setup releases'; Localized: 'Per E-Mail über neue Inno Setup-Versionen benachrichtigt werden'),
    (English: 'Subscribe'; Localized: 'Abonnieren'),
    (English: ' New file '; Localized: ' Neue Datei '),
    (English: 'Create a new &empty script file'; Localized: 'Neue &leere Skriptdatei erstellen'),
    (English: 'Create a new script file using the &Script Wizard'; Localized: 'Neue Skriptdatei mit dem &Skript-Assistenten erstellen'),
    (English: ' Open file '; Localized: ' Datei öffnen '),
    (English: 'Open an e&xisting script file'; Localized: '&Vorhandene Skriptdatei öffnen'),
    (English: '&Don''t show this dialog again'; Localized: '&Diesen Dialog nicht erneut anzeigen'),
    (English: 'Script Wizard File'; Localized: 'Datei für den Skript-Assistenten'),
    (English: 'bold'; Localized: 'fett'),
    (English: ' = required'; Localized: ' = erforderlich'),
    (English: ' Destination '; Localized: ' Ziel '),
    (English: 'Destination &base folder:'; Localized: 'Ziel-&Basisordner:'),
    (English: 'Destination &subfolder:'; Localized: 'Ziel-Unte&rordner:'),
    (English: 'Destination &name:'; Localized: '&Zielname:'),
    (English: ' Source '; Localized: ' Quelle '),
    (English: '&Source file or folder:'; Localized: '&Quelldatei oder -ordner:'),
    (English: '&Recurse subfolders'; Localized: '&Unterordner rekursiv durchlaufen'),
    (English: '&Include empty subfolders'; Localized: '&Leere Unterordner einbeziehen'),
    (English: '&Extract archive'; Localized: '&Archiv entpacken'),
    (English: 'Welcome to the %1'; Localized: 'Der %1 heißt Sie willkommen'),
    (English: 'This wizard will guide you through the process of creating a new Inno Setup script file. The results will be used to generate a new script file which can be compiled directly or saved on disk for later use.%n%n'+'Not all features of Inno Setup are covered by this wizard. See the documentation for details on creating Inno Setup script files.%n%nClick Next to continue, or Cancel to exit this wizard.'; Localized: 'Dieser Assistent führt Sie durch die Erstellung einer neuen Inno Setup-Skriptdatei. Die Ergebnisse werden verwendet, um eine neue Skriptdatei zu generieren, die direkt kompiliert oder zur späteren Verwendung '+'auf dem Datenträger gespeichert werden kann.%n%nNicht alle Funktionen von Inno Setup werden von diesem Assistenten abgedeckt. Einzelheiten zum Erstellen von Inno Setup-Skriptdateien finden Sie in der Dokumentation.%n%n'+'Klicken Sie auf "Weiter", um fortzufahren, oder auf "Abbrechen", um diesen Assistenten zu beenden.'),
    (English: 'Application na&me:'; Localized: 'Anwendungs&name:'),
    (English: 'Application &version:'; Localized: 'Anwendungs&version:'),
    (English: 'Application &publisher:'; Localized: 'Anwendungs&herausgeber:'),
    (English: 'Application &website:'; Localized: 'Anwendungs&website:'),
    (English: 'Application folder na&me:'; Localized: '&Name des Anwendungsordners:'),
    (English: 'Application &destination base folder:'; Localized: 'Ziel-Basisordner der &Anwendung:'),
    (English: 'Other:'; Localized: 'Andere:'),
    (English: 'Allow user to &change the application folder'; Localized: 'Dem &Benutzer erlauben, den Anwendungsordner zu ändern'),
    (English: 'The application doe&sn''t need a folder'; Localized: 'Die Anwendung benötigt &keinen Ordner'),
    (English: 'Other application &files:'; Localized: 'Andere &Anwendungsdateien:'),
    (English: 'Application &main executable file:'; Localized: 'Ausführ&bare Hauptdatei der Anwendung:'),
    (English: 'Allow &user to start the application after Setup has finished'; Localized: 'Dem Ben&utzer erlauben, die Anwendung nach Abschluss von Setup zu starten'),
    (English: 'The application doe&sn''t have a main executable file'; Localized: 'Die Anwendung hat &keine ausführbare Hauptdatei'),
    (English: 'Application file type na&me:'; Localized: '&Name des Anwendungsdateityps:'),
    (English: '&Associate a file type to the main executable'; Localized: 'Einen &Dateityp der ausführbaren Hauptdatei zuordnen'),
    (English: 'Application file type &extension:'; Localized: '&Erweiterung des Anwendungsdateityps:'),
    (English: 'Application &Start Menu folder name:'; Localized: 'Name des &Startmenüordners der Anwendung:'),
    (English: 'Other shortcuts to the main executable:'; Localized: 'Andere Verknüpfungen zur ausführbaren Hauptdatei:'),
    (English: 'Allow user to &change the Start Menu folder name'; Localized: 'Dem &Benutzer erlauben, den Namen des Startmenüordners zu ändern'),
    (English: 'Allow user to &disable Start Menu folder creation'; Localized: 'Dem Benutzer erlauben, die Erstellung des Startmenüordners zu &deaktivieren'),
    (English: 'Allow user to create a deskto&p shortcut'; Localized: 'Dem Benutzer erlauben, eine Des&ktopverknüpfung zu erstellen'),
    (English: 'Create an &Uninstall shortcut in the Start Menu folder'; Localized: 'Eine Deins&tallationsverknüpfung im Startmenüordner erstellen'),
    (English: 'Create an &Internet shortcut in the Start Menu folder'; Localized: 'Eine &Internetverknüpfung im Startmenüordner erstellen'),
    (English: '&Create a Start Menu shortcut but no folder'; Localized: 'Eine &Verknüpfung im Startmenü erstellen, aber keinen Ordner'),
    (English: '&License file:'; Localized: '&Lizenzdatei:'),
    (English: '&Information file shown before installation:'; Localized: '&Vor der Installation angezeigte Informationsdatei:'),
    (English: 'Information file shown &after installation:'; Localized: '&Nach der Installation angezeigte Informationsdatei:'),
    (English: 'Install mode:'; Localized: 'Installationsmodus:'),
    (English: '&Administrative install mode (install for all users)'; Localized: '&Administrativer Installationsmodus (Installation für alle Benutzer)'),
    (English: 'Non a&dministrative install mode (install for current user only)'; Localized: '&Nicht administrativer Installationsmodus (Installation nur für aktuellen Benutzer)'),
    (English: 'Allow user to &override the install mode via the command line'; Localized: 'Dem Benutzer erlauben, den &Installationsmodus über die Befehlszeile zu überschreiben'),
    (English: 'Ask the user to &choose the install mode at startup'; Localized: 'Den &Benutzer beim Start nach dem Installationsmodus fragen'),
    (English: '&Languages:'; Localized: '&Sprachen:'),
    (English: '&Deselect All'; Localized: 'Alle a&bwählen'),
    (English: 'Custom compiler output fol&der:'; Localized: 'Benutzerdefinierter Compiler-&Ausgabeordner:'),
    (English: 'Compiler output base &file name:'; Localized: 'Compiler-Ausgabe-&Basisdateiname:'),
    (English: 'Custom Setup &icon file:'; Localized: 'Benutzerdefinierte Setup-&Symboldatei:'),
    (English: 'Setup &password:'; Localized: 'Setup-&Passwort:'),
    (English: 'Use the password to &encrypt the application files'; Localized: 'Das Passwort zum &Verschlüsseln der Anwendungsdateien verwenden'),
    (English: '&Wizard style:'; Localized: '&Assistentenstil:'),
    (English: 'You have successfully completed the %1.%n%nTo close this wizard and generate the new script file, click Finish.'; Localized: 'Der %1 wurde erfolgreich abgeschlossen.%n%nKlicken Sie auf "Fertigstellen", um diesen Assistenten zu schließen und die neue Skriptdatei zu generieren.'),
    (English: '&Back'; Localized: '&Zurück'),
    (English: '''%s'' is not a valid integer value'; Localized: '''%s'' ist kein gültiger Ganzzahlwert'),
    (English: '''%s'' is not a valid integer value for %s type'; Localized: '''%s'' ist kein gültiger Ganzzahlwert für den Typ %s'),
    (English: '''%s'' is not a valid floating point value'; Localized: '''%s'' ist kein gültiger Gleitkommawert'),
    (English: '''%d.%d'' is not a valid timestamp'; Localized: '''%d.%d'' ist kein gültiger Zeitstempel'),
    (English: '''%s'' is not a valid GUID value'; Localized: '''%s'' ist kein gültiger GUID-Wert'),
    (English: 'Invalid argument to time encode'; Localized: 'Ungültiges Argument für die Zeitcodierung'),
    (English: 'Invalid argument to date encode'; Localized: 'Ungültiges Argument für die Datumscodierung'),
    (English: 'Out of memory'; Localized: 'Nicht genügend Arbeitsspeicher'),
    (English: 'I/O error %d'; Localized: 'E/A-Fehler %d'),
    (English: 'File not found'; Localized: 'Datei nicht gefunden'),
    (English: 'Invalid filename'; Localized: 'Ungültiger Dateiname'),
    (English: 'Too many open files'; Localized: 'Zu viele geöffnete Dateien'),
    (English: 'File access denied'; Localized: 'Dateizugriff verweigert'),
    (English: 'Read beyond end of file'; Localized: 'Lesen über das Dateiende hinaus'),
    (English: 'Disk full'; Localized: 'Datenträger voll'),
    (English: 'Invalid numeric input'; Localized: 'Ungültige numerische Eingabe'),
    (English: 'Division by zero'; Localized: 'Division durch null'),
    (English: 'Range check error'; Localized: 'Bereichsprüfungsfehler'),
    (English: 'Integer overflow'; Localized: 'Ganzzahlüberlauf'),
    (English: 'Invalid floating point operation'; Localized: 'Ungültige Gleitkommaoperation'),
    (English: 'Floating point division by zero'; Localized: 'Gleitkomma-Division durch null'),
    (English: 'Floating point overflow'; Localized: 'Gleitkommaüberlauf'),
    (English: 'Floating point underflow'; Localized: 'Gleitkommaunterlauf'),
    (English: 'Invalid pointer operation'; Localized: 'Ungültige Zeigeroperation'),
    (English: 'Invalid class typecast'; Localized: 'Ungültige Klassentypumwandlung'),
    (English: 'Access violation at address %p. %s of address %p'; Localized: 'Zugriffsverletzung an Adresse %p. %s von Adresse %p'),
    (English: 'Access violation'; Localized: 'Zugriffsverletzung'),
    (English: 'Stack overflow'; Localized: 'Stapelüberlauf'),
    (English: 'Control-C hit'; Localized: 'Strg+C gedrückt'),
    (English: 'Privileged instruction'; Localized: 'Privilegierte Anweisung'),
    (English: 'Operation aborted'; Localized: 'Vorgang abgebrochen'),
    (English: 'Exception %s in module %s at %p.'#13#10'%s%s'#13#10; Localized: 'Ausnahme %s in Modul %s bei %p.'#13#10'%s%s'#13#10),
    (English: 'Application Error'; Localized: 'Anwendungsfehler'),
    (English: 'Format ''%s'' invalid or incompatible with argument'; Localized: 'Format ''%s'' ungültig oder mit Argument inkompatibel'),
    (English: 'No argument for format ''%s'''; Localized: 'Kein Argument für Format ''%s'''),
    (English: 'Variant method calls not supported'; Localized: 'Variant-Methodenaufrufe werden nicht unterstützt'),
    (English: 'Read'; Localized: 'Lesen'),
    (English: 'Write'; Localized: 'Schreiben'),
    (English: 'Execution'; Localized: 'Ausführung'),
    (English: 'Invalid access'; Localized: 'Ungültiger Zugriff'),
    (English: 'Error creating variant or safe array'; Localized: 'Fehler beim Erstellen eines Variant- oder Safe-Arrays'),
    (English: 'Variant or safe array index out of bounds'; Localized: 'Variant- oder Safe-Array-Index außerhalb des gültigen Bereichs'),
    (English: 'Variant or safe array is locked'; Localized: 'Variant- oder Safe-Array ist gesperrt'),
    (English: 'Invalid variant type conversion'; Localized: 'Ungültige Variant-Typkonvertierung'),
    (English: 'Invalid variant operation'; Localized: 'Ungültige Variant-Operation'),
    (English: 'Invalid NULL variant operation'; Localized: 'Ungültige NULL-Variant-Operation'),
    (English: 'Invalid variant operation (%s%.8x)'#10'%s'; Localized: 'Ungültige Variant-Operation (%s%.8x)'#10'%s'),
    (English: 'Could not convert variant of type (%s) into type (%s)'; Localized: 'Variant vom Typ (%s) konnte nicht in Typ (%s) konvertiert werden'),
    (English: 'Overflow while converting variant of type (%s) into type (%s)'; Localized: 'Überlauf beim Konvertieren von Variant des Typs (%s) in Typ (%s)'),
    (English: 'Variant overflow'; Localized: 'Variant-Überlauf'),
    (English: 'Invalid argument'; Localized: 'Ungültiges Argument'),
    (English: 'Invalid variant type'; Localized: 'Ungültiger Variant-Typ'),
    (English: 'Operation not supported'; Localized: 'Vorgang wird nicht unterstützt'),
    (English: 'Unexpected variant error'; Localized: 'Unerwarteter Variant-Fehler'),
    (English: 'External exception %x'; Localized: 'Externe Ausnahme %x'),
    (English: 'Assertion failed'; Localized: 'Assertion fehlgeschlagen'),
    (English: 'Interface not supported'; Localized: 'Schnittstelle nicht unterstützt'),
    (English: 'Exception in safecall method'; Localized: 'Ausnahme in Safecall-Methode'),
    (English: 'Object lock not owned'; Localized: 'Objektsperre nicht im Besitz'),
    (English: 'Monitor support function not initialized'; Localized: 'Monitor-Unterstützungsfunktion nicht initialisiert'),
    (English: 'Feature not implemented'; Localized: 'Funktion nicht implementiert'),
    (English: 'Method called on disposed object'; Localized: 'Methode für freigegebenes Objekt aufgerufen'),
    (English: '%s (%s, line %d)'; Localized: '%s (%s, Zeile %d)'),
    (English: 'Abstract Error'; Localized: 'Abstrakter Fehler'),
    (English: 'Access violation at address %p in module ''%s'' (offset %x). %s of address %p'; Localized: 'Zugriffsverletzung an Adresse %p in Modul ''%s'' (Offset %x). %s von Adresse %p'),
    (English: 'System Error.  Code: %d.'#13#10'%s%s'; Localized: 'Systemfehler.  Code: %d.'#13#10'%s%s'),
    (English: 'A call to an OS function failed'; Localized: 'Ein Aufruf einer Betriebssystemfunktion ist fehlgeschlagen'),
    (English: 'Jan'; Localized: 'Jan'),
    (English: 'Feb'; Localized: 'Feb'),
    (English: 'Mar'; Localized: 'Mär'),
    (English: 'Apr'; Localized: 'Apr'),
    (English: 'May'; Localized: 'Mai'),
    (English: 'Jun'; Localized: 'Jun'),
    (English: 'Jul'; Localized: 'Jul'),
    (English: 'Aug'; Localized: 'Aug'),
    (English: 'Sep'; Localized: 'Sep'),
    (English: 'Oct'; Localized: 'Okt'),
    (English: 'Nov'; Localized: 'Nov'),
    (English: 'Dec'; Localized: 'Dez'),
    (English: 'January'; Localized: 'Januar'),
    (English: 'February'; Localized: 'Februar'),
    (English: 'March'; Localized: 'März'),
    (English: 'April'; Localized: 'April'),
    (English: 'June'; Localized: 'Juni'),
    (English: 'July'; Localized: 'Juli'),
    (English: 'August'; Localized: 'August'),
    (English: 'September'; Localized: 'September'),
    (English: 'October'; Localized: 'Oktober'),
    (English: 'November'; Localized: 'November'),
    (English: 'December'; Localized: 'Dezember'),
    (English: 'Sun'; Localized: 'So'),
    (English: 'Mon'; Localized: 'Mo'),
    (English: 'Tue'; Localized: 'Di'),
    (English: 'Wed'; Localized: 'Mi'),
    (English: 'Thu'; Localized: 'Do'),
    (English: 'Fri'; Localized: 'Fr'),
    (English: 'Sat'; Localized: 'Sa'),
    (English: 'Sunday'; Localized: 'Sonntag'),
    (English: 'Monday'; Localized: 'Montag'),
    (English: 'Tuesday'; Localized: 'Dienstag'),
    (English: 'Wednesday'; Localized: 'Mittwoch'),
    (English: 'Thursday'; Localized: 'Donnerstag'),
    (English: 'Friday'; Localized: 'Freitag'),
    (English: 'Saturday'; Localized: 'Samstag'),
    (English: 'Invalid source array'; Localized: 'Ungültiges Quell-Array'),
    (English: 'Invalid destination array'; Localized: 'Ungültiges Ziel-Array'),
    (English: 'Character index out of bounds (%d)'; Localized: 'Zeichenindex außerhalb des gültigen Bereichs (%d)'),
    (English: 'Start index out of bounds (%d)'; Localized: 'Startindex außerhalb des gültigen Bereichs (%d)'),
    (English: 'Invalid count (%d)'; Localized: 'Ungültige Anzahl (%d)'),
    (English: 'Invalid destination index (%d)'; Localized: 'Ungültiger Zielindex (%d)'),
    (English: 'Invalid code page'; Localized: 'Ungültige Codepage'),
    (English: 'No mapping for the Unicode character exists in the target multi-byte code page'; Localized: 'Für das Unicode-Zeichen ist in der Multibyte-Ziel-Codepage keine Zuordnung vorhanden'),
    (English: 'Invalid StringBaseIndex'; Localized: 'Ungültiger StringBaseIndex'),
    (English: '''%s'' is not a valid %s color value'; Localized: '''%s'' ist kein gültiger %s-Farbwert'),
    (English: 'Ancestor for ''%s'' not found'; Localized: 'Vorfahr für ''%s'' nicht gefunden'),
    (English: 'Cannot assign a %s to a %s'; Localized: '%s kann keinem %s zugewiesen werden'),
    (English: 'Bits index out of range'; Localized: 'Bitindex außerhalb des gültigen Bereichs'),
    (English: 'Can''t write to a read-only resource stream'; Localized: 'In einen schreibgeschützten Ressourcen-Stream kann nicht geschrieben werden'),
    (English: '''''%s'''' expected'; Localized: '''''%s'''' erwartet'),
    (English: 'CheckSynchronize called from thread $%x, which is NOT the main thread'; Localized: 'CheckSynchronize wurde aus Thread $%x aufgerufen, der NICHT der Hauptthread ist'),
    (English: 'Class %s not found'; Localized: 'Klasse %s nicht gefunden'),
    (English: 'A class named %s already exists'; Localized: 'Eine Klasse namens %s ist bereits vorhanden'),
    (English: 'List does not allow duplicates ($0%x)'; Localized: 'Liste lässt keine Duplikate zu ($0%x)'),
    (English: 'A component named %s already exists'; Localized: 'Eine Komponente namens %s ist bereits vorhanden'),
    (English: 'String list does not allow duplicates'; Localized: 'Stringliste lässt keine Duplikate zu'),
    (English: 'Cannot create file "%s". %s'; Localized: 'Datei "%s" kann nicht erstellt werden. %s'),
    (English: 'Cannot open file "%s". %s'; Localized: 'Datei "%s" kann nicht geöffnet werden. %s'),
    (English: 'Identifier expected'; Localized: 'Bezeichner erwartet'),
    (English: 'Invalid binary value'; Localized: 'Ungültiger Binärwert'),
    (English: 'Invalid stream format'; Localized: 'Ungültiges Stream-Format'),
    (English: '''%s'' is an invalid mask at (%d)'; Localized: '''%s'' ist eine ungültige Maske bei (%d)'),
    (English: '''''%s'''' is not a valid component name'; Localized: '''''%s'''' ist kein gültiger Komponentenname'),
    (English: 'Invalid property value'; Localized: 'Ungültiger Eigenschaftswert'),
    (English: 'Invalid property path'; Localized: 'Ungültiger Eigenschaftspfad'),
    (English: 'Invalid data type for ''%s'''; Localized: 'Ungültiger Datentyp für ''%s'''),
    (English: 'Invalid string constant'; Localized: 'Ungültige Stringkonstante'),
    (English: 'Line too long'; Localized: 'Zeile zu lang'),
    (English: 'List capacity out of bounds (%d)'; Localized: 'Listenkapazität außerhalb des gültigen Bereichs (%d)'),
    (English: 'List count out of bounds (%d)'; Localized: 'Listenanzahl außerhalb des gültigen Bereichs (%d)'),
    (English: 'List index out of bounds (%d)'; Localized: 'Listenindex außerhalb des gültigen Bereichs (%d)'),
    (English: '.  %s range is 0..%d'; Localized: '.  %s-Bereich ist 0..%d'),
    (English: '.  %s is empty'; Localized: '.  %s ist leer'),
    (English: 'Out of memory while expanding memory stream'; Localized: 'Nicht genügend Arbeitsspeicher beim Erweitern des Speicher-Streams'),
    (English: '%s has not been registered as a COM class'; Localized: '%s wurde nicht als COM-Klasse registriert'),
    (English: 'Printer is not currently printing'; Localized: 'Drucker druckt derzeit nicht'),
    (English: 'Number expected'; Localized: 'Zahl erwartet'),
    (English: 'ANSI or UTF8 encoding expected'; Localized: 'ANSI- oder UTF8-Codierung erwartet'),
    (English: '%s on line %d'; Localized: '%s in Zeile %d'),
    (English: 'Error reading %s%s%s: %s'; Localized: 'Fehler beim Lesen von %s%s%s: %s'),
    (English: 'Printing in progress'; Localized: 'Druckvorgang läuft'),
    (English: 'Stream read error'; Localized: 'Stream-Lesefehler'),
    (English: 'Property is read-only'; Localized: 'Eigenschaft ist schreibgeschützt'),
    (English: 'Failed to create key %s'; Localized: 'Fehler beim Erstellen des Schlüssels %s'),
    (English: 'Failed to get data for ''%s'''; Localized: 'Fehler beim Abrufen der Daten für ''%s'''),
    (English: 'Failed to set data for ''%s'''; Localized: 'Fehler beim Festlegen der Daten für ''%s'''),
    (English: 'Resource %s not found'; Localized: 'Ressource %s nicht gefunden'),
    (English: '%s.Seek not implemented'; Localized: '%s.Seek nicht implementiert'),
    (English: 'Operation not allowed on sorted list'; Localized: 'Vorgang für sortierte Liste nicht zulässig'),
    (English: 'String expected'; Localized: 'String erwartet'),
    (English: '%s expected'; Localized: '%s erwartet'),
    (English: '%s not in a class registration group'; Localized: '%s nicht in einer Klassenregistrierungsgruppe'),
    (English: 'Property %s does not exist'; Localized: 'Eigenschaft %s ist nicht vorhanden'),
    (English: 'Stream write error'; Localized: 'Stream-Schreibfehler'),
    (English: 'Thread creation error: %s'; Localized: 'Fehler beim Erstellen des Threads: %s'),
    (English: 'Thread Error: %s (%d)'; Localized: 'Thread-Fehler: %s (%d)'),
    (English: 'Cannot terminate an externally created thread'; Localized: 'Ein extern erstellter Thread kann nicht beendet werden'),
    (English: 'Cannot wait for an externally created thread'; Localized: 'Auf einen extern erstellten Thread kann nicht gewartet werden'),
    (English: 'Cannot call Start on a running or suspended thread'; Localized: 'Start kann für einen laufenden oder angehaltenen Thread nicht aufgerufen werden'),
    (English: 'Parameter %s cannot be nil'; Localized: 'Parameter %s darf nicht nil sein'),
    (English: 'Parameter %s cannot be a negative value'; Localized: 'Parameter %s darf kein negativer Wert sein'),
    (English: 'Invalid characters in path'; Localized: 'Ungültige Zeichen im Pfad'),
    (English: 'Invalid characters in search pattern'; Localized: 'Ungültige Zeichen im Suchmuster'),
    (English: 'Path is empty'; Localized: 'Pfad ist leer'),
    (English: 'Search pattern is empty'; Localized: 'Suchmuster ist leer'),
    (English: 'The specified path is too long'; Localized: 'Der angegebene Pfad ist zu lang'),
    (English: 'The specified path was not found'; Localized: 'Der angegebene Pfad wurde nicht gefunden'),
    (English: 'The path format is not supported'; Localized: 'Das Pfadformat wird nicht unterstützt'),
    (English: 'No help viewer that supports filters'; Localized: 'Kein Hilfe-Viewer, der Filter unterstützt'),
    (English: 'String index out of range (%d).  Must be >= %d and <= %d'; Localized: 'Stringindex außerhalb des gültigen Bereichs (%d).  Muss >= %d und <= %d sein'),
    (English: 'Invalid UTF32 character value.  Must be >= 0 and <= $10FFFF, excluding surrogate pair ranges'; Localized: 'Ungültiger UTF32-Zeichenwert.  Muss >= 0 und <= $10FFFF sein, ausschließlich der Ersatzzeichenpaar-Bereiche'),
    (English: 'High surrogate char without a following low surrogate char at index: %d. Check that the string is encoded properly'; Localized: 'Hohes Ersatzzeichen ohne nachfolgendes niedriges Ersatzzeichen bei Index: %d. Prüfen Sie, ob der String korrekt codiert ist'),
    (English: 'Low surrogate char without a preceding high surrogate char at index: %d. Check that the string is encoded properly'; Localized: 'Niedriges Ersatzzeichen ohne vorangehendes hohes Ersatzzeichen bei Index: %d. Prüfen Sie, ob der String korrekt codiert ist'),
    (English: 'Source and Destination arrays must not be the same'; Localized: 'Quell- und Ziel-Array dürfen nicht identisch sein'),
    (English: 'SpinCount out of range. Must be between 0 and %d'; Localized: 'SpinCount außerhalb des gültigen Bereichs. Muss zwischen 0 und %d liegen'),
    (English: 'No context-sensitive help installed'; Localized: 'Keine kontextsensitive Hilfe installiert'),
    (English: 'No help found for context %d'; Localized: 'Keine Hilfe für Kontext %d gefunden'),
    (English: 'Unable to open Index'; Localized: 'Index kann nicht geöffnet werden'),
    (English: 'Unable to open Search'; Localized: 'Suche kann nicht geöffnet werden'),
    (English: 'Unable to find a Table of Contents'; Localized: 'Es kann kein Inhaltsverzeichnis gefunden werden'),
    (English: 'No topic-based help system installed'; Localized: 'Kein themenbasiertes Hilfesystem installiert'),
    (English: 'No help found for %s'; Localized: 'Keine Hilfe für %s gefunden'),
    (English: 'Argument out of range'; Localized: 'Argument außerhalb des gültigen Bereichs'),
    (English: 'Argument must not be nil'; Localized: 'Argument darf nicht nil sein'),
    (English: 'Item not found'; Localized: 'Element nicht gefunden'),
    (English: 'Duplicates not allowed'; Localized: 'Duplikate nicht zulässig'),
    (English: 'Insufficient RTTI available to support this operation'; Localized: 'Nicht genügend RTTI verfügbar, um diesen Vorgang zu unterstützen'),
    (English: 'Parameter count mismatch'; Localized: 'Parameteranzahl stimmt nicht überein'),
    (English: 'Parameter count exceeded'; Localized: 'Parameteranzahl überschritten'),
    (English: 'Type ''%s'' is not declared in the interface section of a unit'; Localized: 'Typ ''%s'' ist nicht im Interface-Abschnitt einer Unit deklariert'),
    (English: 'VAR and OUT arguments must match parameter type exactly'; Localized: 'VAR- und OUT-Argumente müssen exakt dem Parametertyp entsprechen'),
    (English: 'Property ''%s'' is read-only'; Localized: 'Eigenschaft ''%s'' ist schreibgeschützt'),
    (English: 'Property ''%s'' is write-only'; Localized: 'Eigenschaft ''%s'' kann nur geschrieben werden'),
    (English: 'RTTI objects cannot be manually destroyed by application code'; Localized: 'RTTI-Objekte können nicht manuell durch Anwendungscode freigegeben werden'),
    (English: '%s (Version %d.%d, Build %d, %5:s)'; Localized: '%s (Version %d.%d, Build %d, %5:s)'),
    (English: '%s Service Pack %4:d (Version %1:d.%2:d, Build %3:d, %5:s)'; Localized: '%s Service Pack %4:d (Version %1:d.%2:d, Build %3:d, %5:s)'),
    (English: '32-bit Edition'; Localized: '32-Bit-Edition'),
    (English: '64-bit Edition'; Localized: '64-Bit-Edition'),
    (English: 'Windows'; Localized: 'Windows'),
    (English: 'Windows Vista'; Localized: 'Windows Vista'),
    (English: 'Windows Server 2008'; Localized: 'Windows Server 2008'),
    (English: 'Windows 7'; Localized: 'Windows 7'),
    (English: 'Windows Server 2008 R2'; Localized: 'Windows Server 2008 R2'),
    (English: 'Windows 2000'; Localized: 'Windows 2000'),
    (English: 'Windows XP'; Localized: 'Windows XP'),
    (English: 'Windows Server 2003'; Localized: 'Windows Server 2003'),
    (English: 'Windows Server 2003 R2'; Localized: 'Windows Server 2003 R2'),
    (English: 'Windows Server 2012'; Localized: 'Windows Server 2012'),
    (English: 'Windows Server 2012 R2'; Localized: 'Windows Server 2012 R2'),
    (English: 'Windows Server 2016'; Localized: 'Windows Server 2016'),
    (English: 'Windows Server 2019'; Localized: 'Windows Server 2019'),
    (English: 'Windows Server 2022'; Localized: 'Windows Server 2022'),
    (English: 'Windows 8'; Localized: 'Windows 8'),
    (English: 'Windows 8.1'; Localized: 'Windows 8.1'),
    (English: 'Windows 10'; Localized: 'Windows 10'),
    (English: 'Windows 11'; Localized: 'Windows 11'),
    (English: 'Cannot create instance of class %s'; Localized: 'Instanz der Klasse %s kann nicht erstellt werden'),
    (English: 'Observer is not supported'; Localized: 'Beobachter wird nicht unterstützt'),
    (English: 'Cannot have multiple single cast observers added to the observers collection'; Localized: 'Es können nicht mehrere Single-Cast-Beobachter zur Beobachtersammlung hinzugefügt werden'),
    (English: 'The object does not implement the observer interface'; Localized: 'Das Objekt implementiert die Beobachterschnittstelle nicht'),
    (English: 'No single cast observer with ID %d was added to the observer collection'; Localized: 'Es wurde kein Single-Cast-Beobachter mit der ID %d zur Beobachtersammlung hinzugefügt'),
    (English: 'No multi cast observer with ID %d was added to the observer collection'; Localized: 'Es wurde kein Multi-Cast-Beobachter mit der ID %d zur Beobachtersammlung hinzugefügt'),
    (English: 'Observer is not available'; Localized: 'Beobachter ist nicht verfügbar'),
    (English: 'SHA2: Cannot update a finalized hash'; Localized: 'SHA2: Ein finalisierter Hash kann nicht aktualisiert werden'),
    (English: 'Must wait on at least one event'; Localized: 'Es muss auf mindestens ein Ereignis gewartet werden'),
    (English: 'Cannot call BeginInvoke on a TComponent in the process of destruction'; Localized: 'BeginInvoke kann nicht für eine TComponent aufgerufen werden, die gerade zerstört wird'),
    (English: 'OLE error %.8x'; Localized: 'OLE-Fehler %.8x'),
    (English: 'Method ''%s'' not supported by automation object'; Localized: 'Methode ''%s'' wird vom Automatisierungsobjekt nicht unterstützt'),
    (English: 'Variant does not reference an automation object'; Localized: 'Variant verweist nicht auf ein Automatisierungsobjekt'),
    (English: 'Dispatch methods do not support more than 64 parameters'; Localized: 'Dispatch-Methoden unterstützen nicht mehr als 64 Parameter'),
    (English: 'A regular expression specified in RegEx is required'; Localized: 'Ein in RegEx angegebener regulärer Ausdruck ist erforderlich'),
    (English: 'Error in regular expression at offset %d: %s'; Localized: 'Fehler im regulären Ausdruck an Offset %d: %s'),
    (English: 'Successful match required'; Localized: 'Erfolgreiche Übereinstimmung erforderlich'),
    (English: 'Index out of bounds (%d)'; Localized: 'Index außerhalb des gültigen Bereichs (%d)'),
    (English: 'Bitmap image is not valid'; Localized: 'Bitmap-Bild ist ungültig'),
    (English: 'Icon image is not valid'; Localized: 'Symbolbild ist ungültig'),
    (English: 'Metafile is not valid'; Localized: 'Metadatei ist ungültig'),
    (English: 'Invalid pixel format'; Localized: 'Ungültiges Pixelformat'),
    (English: 'Invalid image'; Localized: 'Ungültiges Bild'),
    (English: 'Scan line index out of range'; Localized: 'Scanzeilen-Index außerhalb des gültigen Bereichs'),
    (English: 'Cannot change the size of an icon'; Localized: 'Die Größe eines Symbols kann nicht geändert werden'),
    (English: 'Cannot change the size of a WIC Image'; Localized: 'Die Größe eines WIC-Bilds kann nicht geändert werden'),
    (English: 'Unsupported clipboard format'; Localized: 'Nicht unterstütztes Zwischenablageformat'),
    (English: 'Unsupported stream format'; Localized: 'Nicht unterstütztes Stream-Format'),
    (English: 'Out of system resources'; Localized: 'Nicht genügend Systemressourcen'),
    (English: 'Canvas does not allow drawing'; Localized: 'Zeichenfläche lässt kein Zeichnen zu'),
    (English: 'Text format flag ''%s'' not supported'; Localized: 'Textformat-Flag ''%s'' wird nicht unterstützt'),
    (English: 'Invalid image frame index %d: there are %d frames (0-%d)'; Localized: 'Ungültiger Bildframe-Index %d: Es gibt %d Frames (0-%d)'),
    (English: 'Invalid image size'; Localized: 'Ungültige Bildgröße'),
    (English: 'Invalid ImageList'; Localized: 'Ungültige ImageList'),
    (English: 'Invalid ImageList Index'; Localized: 'Ungültiger ImageList-Index'),
    (English: 'Failed to read ImageList data from stream'; Localized: 'Fehler beim Lesen der ImageList-Daten aus dem Stream'),
    (English: 'Failed to write ImageList data to stream'; Localized: 'Fehler beim Schreiben der ImageList-Daten in den Stream'),
    (English: 'Error creating window device context'; Localized: 'Fehler beim Erstellen des Fenster-Gerätekontexts'),
    (English: 'Error creating window class'; Localized: 'Fehler beim Erstellen der Fensterklasse'),
    (English: 'Cannot focus a disabled or invisible window'; Localized: 'Ein deaktiviertes oder unsichtbares Fenster kann nicht fokussiert werden'),
    (English: 'Control ''%s'' has no parent window'; Localized: 'Steuerelement ''%s'' hat kein übergeordnetes Fenster'),
    (English: '. Path:'#13#10'%s'; Localized: '. Pfad:'#13#10'%s'),
    (English: 'Parent given is not a parent of ''%s'''; Localized: 'Das angegebene übergeordnete Element ist kein übergeordnetes Element von ''%s'''),
    (English: 'Cannot hide an MDI Child Form'; Localized: 'Ein MDI-Unterformular kann nicht ausgeblendet werden'),
    (English: 'Cannot change Visible in OnShow or OnHide'; Localized: 'Visible kann in OnShow oder OnHide nicht geändert werden'),
    (English: 'Cannot make a visible window modal'; Localized: 'Ein sichtbares Fenster kann nicht modal gemacht werden'),
    (English: 'Scrollbar property out of range'; Localized: 'Bildlaufleisten-Eigenschaft außerhalb des gültigen Bereichs'),
    (English: '%s property out of range'; Localized: 'Eigenschaft %s außerhalb des gültigen Bereichs'),
    (English: 'Check state can only be set when CheckBoxes is True'; Localized: 'Der Kontrollkästchenstatus kann nur festgelegt werden, wenn CheckBoxes True ist'),
    (English: 'Check state incompatible with treeview''s CheckStyles'; Localized: 'Kontrollkästchenstatus inkompatibel mit den CheckStyles der Baumansicht'),
    (English: 'Menu index out of range'; Localized: 'Menüindex außerhalb des gültigen Bereichs'),
    (English: 'Menu inserted twice'; Localized: 'Menü zweimal eingefügt'),
    (English: 'Sub-menu is not in menu'; Localized: 'Untermenü ist nicht im Menü'),
    (English: 'Not enough timers available'; Localized: 'Nicht genügend Timer verfügbar'),
    (English: 'Printer index out of range'; Localized: 'Druckerindex außerhalb des gültigen Bereichs'),
    (English: 'Printer selected is not valid'; Localized: 'Der ausgewählte Drucker ist ungültig'),
    (English: '%s on %s'; Localized: '%s an %s'),
    (English: 'GroupIndex cannot be less than a previous menu item''s GroupIndex'; Localized: 'GroupIndex darf nicht kleiner als der GroupIndex eines vorherigen Menüelements sein'),
    (English: 'Cannot create form. No MDI forms are currently active'; Localized: 'Formular kann nicht erstellt werden. Derzeit sind keine MDI-Formulare aktiv'),
    (English: 'Can only modify an image if it contains a bitmap'; Localized: 'Ein Bild kann nur geändert werden, wenn es eine Bitmap enthält'),
    (English: 'A control cannot have itself as its parent'; Localized: 'Ein Steuerelement kann nicht sich selbst als übergeordnetes Element haben'),
    (English: 'Control ''%s'' is used on a not main thread'; Localized: 'Steuerelement ''%s'' wird in einem Nicht-Hauptthread verwendet'),
    (English: '&Yes'; Localized: '&Ja'),
    (English: '&No'; Localized: '&Nein'),
    (English: '&Close'; Localized: '&Schließen'),
    (English: '&Ignore'; Localized: '&Ignorieren'),
    (English: '&Retry'; Localized: '&Wiederholen'),
    (English: '&All'; Localized: '&Alle'),
    (English: 'Cannot drag a form'; Localized: 'Ein Formular kann nicht gezogen werden'),
    (English: 'Metafiles'; Localized: 'Metadateien'),
    (English: 'Enhanced Metafiles'; Localized: 'Erweiterte Metadateien'),
    (English: 'Icons'; Localized: 'Symbole'),
    (English: 'Bitmaps'; Localized: 'Bitmaps'),
    (English: 'TIFF Images'; Localized: 'TIFF-Bilder'),
    (English: 'Warning'; Localized: 'Warnung'),
    (English: 'Error'; Localized: 'Fehler'),
    (English: 'Information'; Localized: 'Information'),
    (English: 'Confirm'; Localized: 'Bestätigen'),
    (English: '&Abort'; Localized: '&Abbrechen'),
    (English: 'N&o to All'; Localized: 'N&ein für alle'),
    (English: 'Yes to &All'; Localized: 'Ja für &alle'),
    (English: 'BkSp'; Localized: 'Rück'),
    (English: 'Tab'; Localized: 'Tab'),
    (English: 'Esc'; Localized: 'Esc'),
    (English: 'Enter'; Localized: 'Enter'),
    (English: 'Space'; Localized: 'Leer'),
    (English: 'PgUp'; Localized: 'BildAuf'),
    (English: 'PgDn'; Localized: 'BildAb'),
    (English: 'End'; Localized: 'Ende'),
    (English: 'Home'; Localized: 'Pos1'),
    (English: 'Left'; Localized: 'Links'),
    (English: 'Up'; Localized: 'Auf'),
    (English: 'Right'; Localized: 'Rechts'),
    (English: 'Down'; Localized: 'Ab'),
    (English: 'Ins'; Localized: 'Einfg'),
    (English: 'Del'; Localized: 'Entf'),
    (English: 'Value must be between %d and %d'; Localized: 'Wert muss zwischen %d und %d liegen'),
    (English: 'Unable to insert a line'; Localized: 'Eine Zeile kann nicht eingefügt werden'),
    (English: 'Invalid clipboard format'; Localized: 'Ungültiges Zwischenablageformat'),
    (English: 'Clipboard does not support Icons'; Localized: 'Die Zwischenablage unterstützt keine Symbole'),
    (English: 'Cannot open clipboard: %s'; Localized: 'Zwischenablage kann nicht geöffnet werden: %s'),
    (English: 'Text exceeds memo capacity'; Localized: 'Text überschreitet die Kapazität des Memos'),
    (English: 'Operation not supported on selected printer'; Localized: 'Vorgang wird vom ausgewählten Drucker nicht unterstützt'),
    (English: 'There is no default printer currently selected'; Localized: 'Derzeit ist kein Standarddrucker ausgewählt'),
    (English: 'Menu ''%s'' is already being used by another form'; Localized: 'Menü ''%s'' wird bereits von einem anderen Formular verwendet'),
    (English: 'Docked control must have a name'; Localized: 'Angedocktes Steuerelement muss einen Namen haben'),
    (English: 'Error removing control from dock tree'; Localized: 'Fehler beim Entfernen des Steuerelements aus dem Andockbaum'),
    (English: ' - Dock zone not found'; Localized: ' - Andockzone nicht gefunden'),
    (English: ' - Dock zone has no control'; Localized: ' - Andockzone hat kein Steuerelement'),
    (English: 'Error loading dock zone from the stream. Expecting version %d, but found %d.'; Localized: 'Fehler beim Laden der Andockzone aus dem Stream. Erwartet wird Version %d, gefunden wurde jedoch %d.'),
    (English: 'Multiselect mode must be on for this feature'; Localized: 'Für diese Funktion muss der Mehrfachauswahlmodus aktiviert sein'),
    (English: 'Length of value array must be >= length of prompt array'; Localized: 'Die Länge des Wert-Arrays muss >= der Länge des Prompt-Arrays sein'),
    (English: 'Prompt array must not be empty'; Localized: 'Das Prompt-Array darf nicht leer sein'),
    (English: '&Username'; Localized: '&Benutzername'),
    (English: '&Password'; Localized: '&Kennwort'),
    (English: '&Domain'; Localized: '&Domäne'),
    (English: 'Login'; Localized: 'Anmeldung'),
    (English: 'Separator'; Localized: 'Trennzeichen'),
    (English: 'Error setting %s.Count'; Localized: 'Fehler beim Festlegen von %s.Count'),
    (English: 'Listbox (%s) style must be virtual in order to set Count'; Localized: 'Der Stil der Listbox (%s) muss virtuell sein, um Count festzulegen'),
    (English: 'No OnGetItem event handler assigned'; Localized: 'Kein OnGetItem-Ereignishandler zugewiesen'),
    (English: 'ANSI'; Localized: 'ANSI'),
    (English: 'ASCII'; Localized: 'ASCII'),
    (English: 'Unicode'; Localized: 'Unicode'),
    (English: 'Big Endian Unicode'; Localized: 'Big Endian Unicode'),
    (English: 'UTF-8'; Localized: 'UTF-8'),
    (English: 'UTF-7'; Localized: 'UTF-7'),
    (English: 'Cannot remove shell notification icon'; Localized: 'Das Shell-Benachrichtigungssymbol kann nicht entfernt werden'),
    (English: '%s requires Windows Vista or later'; Localized: '%s erfordert Windows Vista oder höher'),
    (English: 'Button%d'; Localized: 'Schaltfläche%d'),
    (English: 'RadioButton%d'; Localized: 'Optionsfeld%d'),
    (English: 'Caption cannot be empty'; Localized: 'Beschriftung darf nicht leer sein'),
    (English: 'Invalid canvas operation'; Localized: 'Ungültiger Zeichenflächenvorgang'),
    (English: '%s has no owner'; Localized: '%s hat keinen Besitzer'),
    (English: 'Source and destination require the same owner'; Localized: 'Quelle und Ziel erfordern denselben Besitzer'),
    (English: '%s cannot be owned by a different canvas'; Localized: '%s kann nicht zu einer anderen Zeichenfläche gehören'),
    (English: 'Not a solid color brush'; Localized: 'Kein Pinsel mit Volltonfarbe'),
    (English: 'Invalid brush style'; Localized: 'Ungültiger Pinselstil'),
    (English: 'Unable to load style ''%s'''; Localized: 'Stil ''%s'' kann nicht geladen werden'),
    (English: 'Unable to load styles: %s'; Localized: 'Stile können nicht geladen werden: %s'),
    (English: 'Style ''%s'' already registered'; Localized: 'Stil ''%s'' ist bereits registriert'),
    (English: 'Style class ''%s'' already registered'; Localized: 'Stilklasse ''%s'' ist bereits registriert'),
    (English: 'Style ''%s'' not found'; Localized: 'Stil ''%s'' nicht gefunden'),
    (English: 'Style class ''%s'' not found'; Localized: 'Stilklasse ''%s'' nicht gefunden'),
    (English: 'Invalid style format'; Localized: 'Ungültiges Stilformat'),
    (English: 'VCL Style File'; Localized: 'VCL-Stildatei'),
    (English: 'Class ''%s'' is already registered for ''%s'''; Localized: 'Klasse ''%s'' ist bereits für ''%s'' registriert'),
    (English: 'Class ''%s'' is not registered for ''%s'''; Localized: 'Klasse ''%s'' ist nicht für ''%s'' registriert'),
    (English: '%s parameter cannot be nil'; Localized: 'Parameter %s darf nicht nil sein'),
    (English: 'A StyleHook class has not been registered for %s'; Localized: 'Für %s wurde keine StyleHook-Klasse registriert'),
    (English: 'Feature not supported by this style'; Localized: 'Funktion wird von diesem Stil nicht unterstützt'),
    (English: 'Cannot call BeginInvoke on a control with no parent or window handle'; Localized: 'BeginInvoke kann nicht für ein Steuerelement ohne übergeordnetes Element oder Fensterhandle aufgerufen werden'),
    (English: 'CardPanel card index is out of range'; Localized: 'Der CardPanel-Kartenindex liegt außerhalb des gültigen Bereichs'),
    (English: 'CardPanel.ActiveCard cannot be nil'; Localized: 'CardPanel.ActiveCard darf nicht nil sein'),
    (English: 'Invalid index'; Localized: 'Ungültiger Index'),
    (English: 'Unable to insert an item'; Localized: 'Ein Element kann nicht eingefügt werden'),
    (English: 'Invalid owner'; Localized: 'Ungültiger Besitzer'),
    (English: 'RichEdit line insertion error'; Localized: 'Fehler beim Einfügen einer RichEdit-Zeile'),
    (English: 'Failed to Load Stream'; Localized: 'Fehler beim Laden des Streams'),
    (English: 'Failed to Save Stream'; Localized: 'Fehler beim Speichern des Streams'),
    (English: '%s is already associated with %s'; Localized: '%s ist bereits mit %s verknüpft'),
    (English: 'This control requires version 4.70 or greater of COMCTL32.DLL'; Localized: 'Dieses Steuerelement erfordert Version 4.70 oder höher von COMCTL32.DLL'),
    (English: 'ListView item can be added only when OwnerData is False.  Use OnData instead.'; Localized: 'Ein ListView-Element kann nur hinzugefügt werden, wenn OwnerData False ist.  Verwenden Sie stattdessen OnData.'),
    (English: 'This "Portable Network Graphics" image is not valid because it contains invalid pieces of data (crc error)'; Localized: 'Dieses "Portable Network Graphics"-Bild ist ungültig, da es ungültige Datenteile enthält (CRC-Fehler)'),
    (English: 'The "Portable Network Graphics" image could not be loaded because one of its main piece of data (ihdr) might be corrupted'; Localized: 'Das "Portable Network Graphics"-Bild konnte nicht geladen werden, da einer seiner Hauptdatenteile (ihdr) möglicherweise beschädigt ist'),
    (English: 'This "Portable Network Graphics" image is invalid because it has missing image parts.'; Localized: 'Dieses "Portable Network Graphics"-Bild ist ungültig, da Bildteile fehlen.'),
    (English: 'Could not decompress the image because it contains invalid compressed data.'#13#10' Description: '; Localized: 'Das Bild konnte nicht dekomprimiert werden, da es ungültige komprimierte Daten enthält.'#13#10' Beschreibung: '),
    (English: 'The "Portable Network Graphics" image contains an invalid palette.'; Localized: 'Das "Portable Network Graphics"-Bild enthält eine ungültige Palette.'),
    (English: 'The file being read is not a valid "Portable Network Graphics" image because it contains an invalid header. This file may be corrupted, try obtaining it again'; Localized: 'Die gelesene Datei ist kein gültiges "Portable Network Graphics"-Bild, da sie einen ungültigen Header enthält. Diese Datei ist möglicherweise beschädigt; versuchen Sie, sie erneut zu beziehen'),
    (English: 'This "Portable Network Graphics" image is not supported or it might be invalid.'#13#10'(IHDR chunk is not the first)'; Localized: 'Dieses "Portable Network Graphics"-Bild wird nicht unterstützt oder ist möglicherweise ungültig.'#13#10'(IHDR-Chunk ist nicht der erste)'),
    (English: 'This "Portable Network Graphics" image is not supported because either its width or height exceeds the maximum size of 65535 pixels.'; Localized: 'Dieses "Portable Network Graphics"-Bild wird nicht unterstützt, da seine Breite oder Höhe die maximale Größe von 65535 Pixeln überschreitet.'),
    (English: 'There is no such palette entry.'; Localized: 'Es gibt keinen solchen Paletteneintrag.'),
    (English: 'This "Portable Network Graphics" image contains an unknown critical part which could not be decoded.'; Localized: 'Dieses "Portable Network Graphics"-Bild enthält einen unbekannten kritischen Teil, der nicht decodiert werden konnte.'),
    (English: 'This "Portable Network Graphics" image is encoded with an unknown compression scheme which could not be decoded.'; Localized: 'Dieses "Portable Network Graphics"-Bild ist mit einem unbekannten Komprimierungsverfahren codiert, das nicht decodiert werden konnte.'),
    (English: 'This "Portable Network Graphics" image uses an unknown interlace scheme which could not be decoded.'; Localized: 'Dieses "Portable Network Graphics"-Bild verwendet ein unbekanntes Interlace-Verfahren, das nicht decodiert werden konnte.'),
    (English: 'This "Portable Network Graphics" image uses an unknown color type which could not be decoded.'; Localized: 'Dieses "Portable Network Graphics"-Bild verwendet einen unbekannten Farbtyp, der nicht decodiert werden konnte.'),
    (English: 'The chunks must be compatible to be assigned.'; Localized: 'Die Chunks müssen kompatibel sein, um zugewiesen werden zu können.'),
    (English: 'This "Portable Network Graphics" image is invalid because the decoder found an unexpected end of the file.'; Localized: 'Dieses "Portable Network Graphics"-Bild ist ungültig, da der Decoder ein unerwartetes Dateiende gefunden hat.'),
    (English: 'This "Portable Network Graphics" image contains no data.'; Localized: 'Dieses "Portable Network Graphics"-Bild enthält keine Daten.'),
    (English: 'The program tried to add a existent critical chunk to the current image which is not allowed.'; Localized: 'Das Programm hat versucht, einen vorhandenen kritischen Chunk zum aktuellen Bild hinzuzufügen, was nicht zulässig ist.'),
    (English: 'It''s not allowed to add a new chunk because the current image is invalid.'; Localized: 'Es ist nicht zulässig, einen neuen Chunk hinzuzufügen, da das aktuelle Bild ungültig ist.'),
    (English: 'Some operation could not be performed because the system is out of resources. Close some windows and try again.'; Localized: 'Ein Vorgang konnte nicht ausgeführt werden, da dem System die Ressourcen ausgegangen sind. Schließen Sie einige Fenster und versuchen Sie es erneut.'),
    (English: 'Setting bit transparency color is not allowed for png images containing alpha value for each pixel (COLOR_RGBALPHA and COLOR_GRAYSCALEALPHA)'; Localized: 'Das Festlegen einer Bit-Transparenzfarbe ist für PNG-Bilder mit einem Alphawert pro Pixel nicht zulässig (COLOR_RGBALPHA und COLOR_GRAYSCALEALPHA)'),
    (English: 'This operation is not valid because the current image contains no valid header.'; Localized: 'Dieser Vorgang ist ungültig, da das aktuelle Bild keinen gültigen Header enthält.'),
    (English: 'The new size provided for image resizing is invalid.'; Localized: 'Die für die Bildgrößenänderung angegebene neue Größe ist ungültig.'),
    (English: 'The "Portable Network Graphics" image could not be loaded because it uses an invalid image bit depth.'; Localized: 'Das "Portable Network Graphics"-Bild konnte nicht geladen werden, da es eine ungültige Bildbittiefe verwendet.'));

implementation

end.
