unit IDE.LocalizeFunc.Dutch;

{
  Inno Setup
  Copyright (C) 1997-2026 Jordan Russell
  Portions by Martijn Laan
  For conditions of distribution and use, see LICENSE.TXT.

  Compiler IDE Dutch translations
}

interface

uses
  IDE.LocalizeFunc;

const
  DutchIDETranslations: array [0..495] of TTranslationPair = (
    (English: 'Command line usage:'; Localized: 'Opdrachtregelgebruik:'),
    (English: 'Examples:'; Localized: 'Voorbeelden:'),
    (English: 'script file'; Localized: 'scriptbestand'),
    (English: 'wizard name'; Localized: 'wizardnaam'),
    (English: 'My script'; Localized: 'Mijn script'),
    (English: 'My Script Wizard'; Localized: 'Mijn Scriptwizard'),
    (English: 'Could not load %1: %2'; Localized: 'Kon %1 niet laden: %2'),
    (English: 'Inno Setup Compiler'; Localized: 'Inno Setup Compiler'),
    (English: 'Example scripts...'; Localized: 'Voorbeeldscripts...'),
    (English: 'More files...'; Localized: 'Meer bestanden...'),
    (English: 'Untitled'; Localized: 'Naamloos'),
    (English: 'Preprocessor Output'; Localized: 'Preprocessor-uitvoer'),
    (English: 'Run Parameters'; Localized: 'Uitvoeringsparameters'),
    (English: 'Command line parameters for %1 and %2:'; Localized: 'Opdrachtregelparameters voor %1 en %2:'),
    (English: 'Inno Setup Script files'; Localized: 'Inno Setup-scriptbestanden'),
    (English: 'All files'; Localized: 'Alle bestanden'),
    (English: 'Application files'; Localized: 'Toepassingsbestanden'),
    (English: 'Documentation files'; Localized: 'Documentatiebestanden'),
    (English: 'Registry files'; Localized: 'Registerbestanden'),
    (English: 'Icon files'; Localized: 'Pictogrambestanden'),
    (English: 'Inno Setup Script Wizard'; Localized: 'Inno Setup-scriptwizard'),
    (English: 'Welcome'; Localized: 'Welkom'),
    (English: 'Application Information'; Localized: 'Toepassingsinformatie'),
    (English: 'Please specify some basic information about your application.'; Localized: 'Geef enige basisinformatie over uw toepassing op.'),
    (English: 'Application Folder'; Localized: 'Toepassingsmap'),
    (English: 'Please specify folder information about your application.'; Localized: 'Geef mapinformatie over uw toepassing op.'),
    (English: 'Application Files'; Localized: 'Toepassingsbestanden'),
    (English: 'Please specify the files that are part of your application.'; Localized: 'Geef de bestanden op die deel uitmaken van uw toepassing.'),
    (English: 'Please specify the source folder.'; Localized: 'Geef de bronmap op.'),
    (English: 'Should files in subfolders of "%1" also be included?'; Localized: 'Moeten ook bestanden in submappen van "%1" worden opgenomen?'),
    (English: 'URL:'; Localized: 'URL:'),
    (English: 'Is the file to download an archive which should be extracted?'; Localized: 'Is het te downloaden bestand een archief dat moet worden uitgepakt?'),
    (English: 'Name of the file:'; Localized: 'Naam van het bestand:'),
    (English: 'Name of the file (extension should match archive format):'; Localized: 'Naam van het bestand (extensie moet overeenkomen met het archiefformaat):'),
    (English: 'Approximate size of the file in megabytes:'; Localized: 'Geschatte grootte van het bestand in megabytes:'),
    (English: 'Application File Association'; Localized: 'Toepassingsbestandskoppeling'),
    (English: 'Please specify which file association should be created for your application.'; Localized: 'Geef op welke bestandskoppeling voor uw toepassing moet worden gemaakt.'),
    (English: '%1 File'; Localized: '%1-bestand'),
    (English: 'Application Shortcuts'; Localized: 'Toepassingssnelkoppelingen'),
    (English: 'Please specify which shortcuts should be created for your application.'; Localized: 'Geef op welke snelkoppelingen voor uw toepassing moeten worden gemaakt.'),
    (English: 'Application Documentation'; Localized: 'Toepassingsdocumentatie'),
    (English: 'Please specify which documentation files should be shown by Setup during installation.'; Localized: 'Geef op welke documentatiebestanden Setup tijdens de installatie moet tonen.'),
    (English: 'Setup Install Mode'; Localized: 'Setup-installatiemodus'),
    (English: 'Please specify in which install mode Setup should run.'; Localized: 'Geef op in welke installatiemodus Setup moet worden uitgevoerd.'),
    (English: 'Application Registry Keys And Values'; Localized: 'Registersleutels en -waarden van de toepassing'),
    (English: 'Please specify the registry keys and values that are part of your application.'; Localized: 'Geef de registersleutels en -waarden op die deel uitmaken van uw toepassing.'),
    (English: 'Setup Languages'; Localized: 'Setup-talen'),
    (English: 'Please specify which Setup languages should be included.'; Localized: 'Geef op welke Setup-talen moeten worden opgenomen.'),
    (English: 'Compiler Settings'; Localized: 'Compiler-instellingen'),
    (English: 'Please specify some basic compiler settings.'; Localized: 'Geef enige basisinstellingen voor de compiler op.'),
    (English: 'Please specify the folder.'; Localized: 'Geef de map op.'),
    (English: 'Wizard Style'; Localized: 'Wizardstijl'),
    (English: 'Please specify which wizard style should be used.'; Localized: 'Geef op welke wizardstijl moet worden gebruikt.'),
    (English: 'Inno Setup Preprocessor'; Localized: 'Inno Setup Preprocessor'),
    (English: 'Please specify whether Inno Setup Preprocessor should be used.'; Localized: 'Geef op of de Inno Setup Preprocessor moet worden gebruikt.'),
    (English: 'The %1 can use %2 compiler directives to simplify your script. Although this is not necessary, it will make it easier to manually change the script later.%n%nDo you want the %1 to use %2 compiler directives?'; Localized: 'De %1 kan %2-compilerdirectieven gebruiken om uw script te vereenvoudigen. Hoewel dit niet noodzakelijk is, maakt het wel eenvoudiger om het script later handmatig te wijzigen.%n%nWilt u dat de %1 %2-compilerdirectieven gebruikt?'),
    (English: '&Yes, use %1 compiler directives'; Localized: '&Ja, gebruik %1-compilerdirectieven'),
    (English: 'Finished'; Localized: 'Voltooid'),
    (English: '&Next'; Localized: '&Volgende'),
    (English: '&Finish'; Localized: '&Voltooien'),
    (English: 'The %1 is not complete. If you quit now, the new script file will not be generated.%n%nExit anyway?'; Localized: 'De %1 is niet voltooid. Als u nu stopt, wordt het nieuwe scriptbestand niet gegenereerd.%n%nToch afsluiten?'),
    (English: 'Please specify the application name.'; Localized: 'Geef de naam van de toepassing op.'),
    (English: 'Please specify the application version.'; Localized: 'Geef de versie van de toepassing op.'),
    (English: 'Please specify the application destination base folder.'; Localized: 'Geef de doelbasismap van de toepassing op.'),
    (English: 'Please specify the application folder name.'; Localized: 'Geef de naam van de toepassingsmap op.'),
    (English: 'Please specify the application main executable file.'; Localized: 'Geef het hoofduitvoerbare bestand van de toepassing op.'),
    (English: 'Please specify the application Start Menu group name.'; Localized: 'Geef de groepsnaam in het menu Start van de toepassing op.'),
    (English: 'Please specify the destination base folder.'; Localized: 'Geef de doelbasismap op.'),
    (English: 'Please specify a destination base folder other than the application folder'; Localized: 'Geef een andere doelbasismap op dan de toepassingsmap'),
    (English: 'Please select at least one language.'; Localized: 'Selecteer ten minste één taal.'),
    (English: '&Source URL:'; Localized: '&Bron-URL:'),
    (English: 'Script generated by the %1.'; Localized: 'Script gegenereerd door de %1.'),
    (English: 'SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!'; Localized: 'RAADPLEEG DE DOCUMENTATIE VOOR DETAILS OVER HET MAKEN VAN INNO SETUP-SCRIPTBESTANDEN!'),
    (English: 'NOTE: The value of %1 uniquely identifies this application. Do not use the same %1 value in installers for other applications.'; Localized: 'OPMERKING: De waarde van %1 identificeert deze toepassing op unieke wijze. Gebruik dezelfde %1-waarde niet in installatieprogramma''s voor andere toepassingen.'),
    (English: '(To generate a new GUID, click Tools | Generate GUID inside the IDE.)'; Localized: '(Klik in de IDE op Extra | GUID genereren om een nieuwe GUID te genereren.)'),
    (English: '"%1" specifies that Setup cannot run on anything but x64 and Windows 11 on Arm.'; Localized: '"%1" geeft aan dat Setup alleen kan worden uitgevoerd op x64 en Windows 11 op Arm.'),
    (English: '"%1" requests that the install be done in "64-bit mode" on x64 or Windows 11 on Arm.'; Localized: '"%1" verzoekt dat de installatie wordt uitgevoerd in "64-bits modus" op x64 of Windows 11 op Arm.'),
    (English: 'This means it should use the native 64-bit Program Files directory and the 64-bit view of the registry.'; Localized: 'Dit betekent dat de native 64-bits map Program Files en de 64-bits weergave van het register gebruikt zouden moeten worden.'),
    (English: 'Uncomment the following line to use a 64-bit installer.'; Localized: 'Verwijder het commentaarteken van de volgende regel om een 64-bits installatieprogramma te gebruiken.'),
    (English: 'Use "%1" if all your archives are .%2 files.'; Localized: 'Gebruik "%1" als al uw archieven .%2-bestanden zijn.'),
    (English: 'Use "%1" if all your archives are not password-protected.'; Localized: 'Gebruik "%1" als al uw archieven niet met een wachtwoord zijn beveiligd.'),
    (English: 'Uncomment the following line to run in non administrative install mode (install for current user only).'; Localized: 'Verwijder het commentaarteken van de volgende regel om in niet-administratieve installatiemodus uit te voeren (installeren voor alleen de huidige gebruiker).'),
    (English: 'Remove the following line to run in administrative install mode (install for all users).'; Localized: 'Verwijder de volgende regel om in administratieve installatiemodus uit te voeren (installeren voor alle gebruikers).'),
    (English: 'NOTE: Don''t use "%1" on any shared system files.'; Localized: 'OPMERKING: Gebruik "%1" niet op gedeelde systeembestanden.'),
    (English: 'NOTE: Use the "%1" flag or the "%2" parameter to verify downloads.'; Localized: 'OPMERKING: Gebruik de vlag "%1" of de parameter "%2" om downloads te verifiëren.'),
    (English: 'Registry data from file %1'; Localized: 'Registergegevens uit bestand %1'),
    (English: 'COULD NOT IMPORT %1'; Localized: 'KON %1 NIET IMPORTEREN'),
    (English: 'End of registry data from file %1'; Localized: 'Einde van registergegevens uit bestand %1'),
    (English: 'SOME KEYS FILTERED DUE TO %1 SETTINGS!'; Localized: 'SOMMIGE SLEUTELS GEFILTERD VANWEGE %1-INSTELLINGEN!'),
    (English: 'SOME VALUES WITH UNSUPPORTED TYPES SKIPPED!'; Localized: 'SOMMIGE WAARDEN MET NIET-ONDERSTEUNDE TYPEN OVERGESLAGEN!'),
    (English: 'Would you like to compile the new script now?'; Localized: 'Wilt u het nieuwe script nu compileren?'),
    (English: 'My Program'; Localized: 'Mijn programma'),
    (English: 'My Company, Inc.'; Localized: 'My Company, Inc.'),
    (English: 'Application directory'; Localized: 'Toepassingsmap'),
    (English: 'Program Files directory'; Localized: 'Map Program Files'),
    (English: 'Common Files directory'; Localized: 'Map Common Files'),
    (English: 'Windows directory'; Localized: 'Windows-map'),
    (English: 'Windows system directory'; Localized: 'Windows-systeemmap'),
    (English: 'Setup source directory'; Localized: 'Setup-bronmap'),
    (English: 'System drive root directory'; Localized: 'Hoofdmap van systeemstation'),
    (English: '(Custom)'; Localized: '(Aangepast)'),
    (English: 'Starting compile.%1[%2]'; Localized: 'Compileren wordt gestart.%1[%2]'),
    (English: 'Finished.%1[%2, %3 elapsed]'; Localized: 'Voltooid.%1[%2, %3 verstreken]'),
    (English: 'Compile aborted.'; Localized: 'Compileren afgebroken.'),
    (English: 'Log size limit reached, list reset.'; Localized: 'Maximale loggrootte bereikt, lijst opnieuw ingesteld.'),
    (English: '%1 started'; Localized: '%1 gestart'),
    (English: 'Terminating process'; Localized: 'Proces wordt beëindigd'),
    (English: 'Removing left-over temporary directory: %1'; Localized: 'Achtergebleven tijdelijke map wordt verwijderd: %1'),
    (English: 'Failed to remove temporary directory'; Localized: 'Tijdelijke map kon niet worden verwijderd'),
    (English: '%1 Call Stack'; Localized: '%1-aanroepstack'),
    (English: 'Cannot run Setup at this time. Please compile Setup successfully to completion first, with output enabled'; Localized: 'Setup kan op dit moment niet worden uitgevoerd. Compileer Setup eerst volledig en zonder fouten, met uitvoer ingeschakeld'),
    (English: 'Cannot run Uninstall at this time. Please run Setup successfully to completion first'; Localized: 'Verwijderprogramma kan op dit moment niet worden uitgevoerd. Voer Setup eerst volledig en zonder fouten uit'),
    (English: 'Error executing "%1":%n%n%2: %3'; Localized: 'Fout bij uitvoeren van "%1":%n%n%2: %3'),
    (English: 'Are you sure you want to abort the compile?'; Localized: 'Weet u zeker dat u het compileren wilt afbreken?'),
    (English: 'File %1:'; Localized: 'Bestand %1:'),
    (English: 'Line %1:'; Localized: 'Regel %1:'),
    (English: 'Compiler Error'; Localized: 'Compilerfout'),
    (English: 'Illegal null character on line %1'; Localized: 'Ongeldig null-teken op regel %1'),
    (English: 'Cannot find "%1"'; Localized: 'Kan "%1" niet vinden'),
    (English: 'Invalid regular expression "%1"'; Localized: 'Ongeldige reguliere expressie "%1"'),
    (English: '%1 (%2 hits):'; Localized: '%1 (%2 treffers):'),
    (English: 'Find "%1" (%2 hits in %3 files)'; Localized: 'Zoeken naar "%1" (%2 treffers in %3 bestanden)'),
    (English: '%1 occurrence(s) replaced.'; Localized: '%1 exemplaren vervangen.'),
    (English: 'The .%1 extension was successfully associated for the current user with:%n%2'; Localized: 'De extensie .%1 is voor de huidige gebruiker gekoppeld aan:%n%2'),
    (English: 'The .%1 extension was successfully associated for all users with:%n%2'; Localized: 'De extensie .%1 is voor alle gebruikers gekoppeld aan:%n%2'),
    (English: 'Error creating file association:%n%1 - %2'; Localized: 'Fout bij het maken van de bestandskoppeling:%n%1 - %2'),
    (English: 'Unable to associate for all users without administrative privileges. Do you want to associate only for yourself instead?'; Localized: 'Koppelen voor alle gebruikers is niet mogelijk zonder administratieve rechten. Wilt u in plaats daarvan alleen voor uzelf koppelen?'),
    (English: 'Associate'; Localized: 'Koppelen'),
    (English: 'Inno Setup Script'; Localized: 'Inno Setup-script'),
    (English: 'Compi&le'; Localized: 'Compi&leren'),
    (English: '&Script has %1'; Localized: '&Script heeft %1'),
    (English: 'Script has %1 set'; Localized: 'In het script is %1 ingesteld'),
    (English: 'Invalid file format.'; Localized: 'Ongeldige bestandsindeling.'),
    (English: 'Setup'; Localized: 'Setup'),
    (English: 'Your message text.'; Localized: 'Uw berichttekst.'),
    (English: 'Enter your text here...'; Localized: 'Voer hier uw tekst in...'),
    (English: 'Return values'; Localized: 'Retourwaarden'),
    (English: 'Default'; Localized: 'Standaard'),
    (English: 'Shield'; Localized: 'Schild'),
    (English: 'Instruction Text'; Localized: 'Instructietekst'),
    (English: 'Message Text'; Localized: 'Berichttekst'),
    (English: 'user clicked %1'; Localized: 'gebruiker klikte op %1'),
    (English: 'OK'; Localized: 'OK'),
    (English: 'Yes'; Localized: 'Ja'),
    (English: 'No'; Localized: 'Nee'),
    (English: 'Cancel'; Localized: 'Annuleren'),
    (English: 'Retry'; Localized: 'Opnieuw proberen'),
    (English: 'Ignore'; Localized: 'Negeren'),
    (English: 'Abort'; Localized: 'Afbreken'),
    (English: 'Display a message box'; Localized: 'Een berichtvenster weergeven'),
    (English: 'Name of the Sign Tool:'; Localized: 'Naam van de ondertekeningstool:'),
    (English: 'Invalid name.'; Localized: 'Ongeldige naam.'),
    (English: 'Duplicate name.'; Localized: 'Dubbele naam.'),
    (English: 'Command of the Sign Tool:'; Localized: 'Opdracht van de ondertekeningstool:'),
    (English: 'Invalid command.'; Localized: 'Ongeldige opdracht.'),
    (English: 'The generated GUID will be inserted into the editor at the cursor position. Continue?'; Localized: 'De gegenereerde GUID wordt op de cursorpositie in de editor ingevoegd. Doorgaan?'),
    (English: 'The generated Pascal script will be inserted into the editor at the cursor position, but the cursor is not in the %1 section. Continue anyway?'; Localized: 'Het gegenereerde Pascal-script wordt op de cursorpositie in de editor ingevoegd, maar de cursor staat niet in de sectie %1. Toch doorgaan?'),
    (English: 'Classic'; Localized: 'Klassiek'),
    (English: 'Visual Studio / Visual Studio Code'; Localized: 'Visual Studio / Visual Studio Code'),
    (English: 'Classic / Visual Studio'; Localized: 'Klassiek / Visual Studio'),
    (English: 'Visual Studio Code'; Localized: 'Visual Studio Code'),
    (English: 'Light'; Localized: 'Licht'),
    (English: 'Dark'; Localized: 'Donker'),
    (English: 'The new language will take effect the next time you start Inno Setup Compiler.'; Localized: 'De nieuwe taal wordt van kracht de volgende keer dat u Inno Setup Compiler start.'),
    (English: '&New...'; Localized: '&Nieuw...'),
    (English: '&New'; Localized: '&Nieuw'),
    (English: 'Line %1'; Localized: 'Regel %1'),
    (English: '%1: %2'; Localized: '%1: %2'),
    (English: 'Back (%1)'; Localized: 'Vorige (%1)'),
    (English: 'Forward (%1)'; Localized: 'Volgende (%1)'),
    (English: 'Ctrl+'; Localized: 'Ctrl+'),
    (English: 'Shift+'; Localized: 'Shift+'),
    (English: 'Alt+'; Localized: 'Alt+'),
    (English: 'Num %1'; Localized: 'Num %1'),
    (English: '(32-bit)'; Localized: '(32-bits)'),
    (English: '[Compiling]'; Localized: '[Compileren]'),
    (English: '[Running]'; Localized: '[Wordt uitgevoerd]'),
    (English: '[Paused]'; Localized: '[Gepauzeerd]'),
    (English: 'Read only'; Localized: 'Alleen-lezen'),
    (English: 'Modified'; Localized: 'Gewijzigd'),
    (English: 'Overwrite'; Localized: 'Overschrijven'),
    (English: 'Insert'; Localized: 'Invoegen'),
    (English: 'Tabs closed: %1'; Localized: 'Gesloten tabbladen: %1'),
    (English: 'Estimated time remaining: %1'; Localized: 'Geschatte resterende tijd: %1'),
    (English: 'Average KB/sec: %1'; Localized: 'Gemiddeld KB/sec: %1'),
    (English: 'There was an error opening the file. Remove it from the list?'; Localized: 'Er is een fout opgetreden bij het openen van het bestand. Uit de lijst verwijderen?'),
    (English: 'The text in the %1 file has changed.%n%nDo you want to save the changes?'; Localized: 'De tekst in het bestand %1 is gewijzigd.%n%nWilt u de wijzigingen opslaan?'),
    (English: 'Please stop the compile process before performing this command.'; Localized: 'Stop het compilatieproces voordat u deze opdracht uitvoert.'),
    (English: 'A compile is already in progress.'; Localized: 'Er is al een compilatie bezig.'),
    (English: 'The text in the %1 file has changed and must be saved before compiling.%n%nSave the changes and continue?'; Localized: 'De tekst in het bestand %1 is gewijzigd en moet worden opgeslagen vóór het compileren.%n%nDe wijzigingen opslaan en doorgaan?'),
    (English: 'Would you like to save the script before compiling?%n%nIf you answer No, the compiled installation will be placed under your My Documents folder by default.'; Localized: 'Wilt u het script opslaan vóór het compileren?%n%nAls u Nee antwoordt, wordt de gecompileerde installatie standaard in uw map Mijn documenten geplaatst.'),
    (English: 'The selected file is an %1 file. Go to its tab instead of opening it as the new main file?'; Localized: 'Het geselecteerde bestand is een %1-bestand. Naar het bijbehorende tabblad gaan in plaats van het als nieuw hoofdbestand te openen?'),
    (English: 'The selected file is not available as a tab. Opening as the new main file instead.'; Localized: 'Het geselecteerde bestand is niet beschikbaar als tabblad. Het wordt in plaats daarvan als nieuw hoofdbestand geopend.'),
    (English: 'Error creating file (code %1). Could not save file'; Localized: 'Fout bij het maken van het bestand (code %1). Bestand kon niet worden opgeslagen'),
    (English: 'Error creating backup file. Could not save file'; Localized: 'Fout bij het maken van het back-upbestand. Bestand kon niet worden opgeslagen'),
    (English: 'Error removing existing file (code %1). Could not save file'; Localized: 'Fout bij het verwijderen van het bestaande bestand (code %1). Bestand kon niet worden opgeslagen'),
    (English: 'Error renaming temporary file (code %1). Could not save file'; Localized: 'Fout bij het hernoemen van het tijdelijke bestand (code %1). Bestand kon niet worden opgeslagen'),
    (English: 'Failed to open included file: %1'; Localized: 'Kon include-bestand niet openen: %1'),
    (English: 'Cannot start printer document.'; Localized: 'Kan printerdocument niet starten.'),
    (English: 'Are you sure you want to clear the list of recently opened files?'; Localized: 'Weet u zeker dat u de lijst met recent geopende bestanden wilt wissen?'),
    (English: 'The %1 file has been modified outside of the source editor. You might want to reload it.'; Localized: 'Het bestand %1 is buiten de broneditor gewijzigd. Misschien wilt u het opnieuw laden.'),
    (English: 'The %1 file has been modified outside of the source editor.%n%nDo you want to reload the file?'; Localized: 'Het bestand %1 is buiten de broneditor gewijzigd.%n%nWilt u het bestand opnieuw laden?'),
    (English: 'The %1 file has been modified outside of the source editor. Changes have also been made in the source editor.%n%nDo you want to reload the file and lose the changes made in the source editor?'; Localized: 'Het bestand %1 is buiten de broneditor gewijzigd. Er zijn ook wijzigingen aangebracht in de broneditor.%n%nWilt u het bestand opnieuw laden en de in de broneditor aangebrachte wijzigingen verliezen?'),
    (English: 'File not opened.'; Localized: 'Bestand niet geopend.'),
    (English: 'Go to Line'; Localized: 'Ga naar regel'),
    (English: 'Line number:'; Localized: 'Regelnummer:'),
    (English: 'Do you want to copy your current license key to the clipboard before opening our order page? You will need it to be able to renew it.'; Localized: 'Wilt u uw huidige licentiesleutel naar het klembord kopiëren voordat u onze bestelpagina opent? U hebt deze nodig om de licentie te kunnen verlengen.'),
    (English: 'New commercial license key has been registered:%n%n%1%n%nThanks for your support!'; Localized: 'Nieuwe commerciële licentiesleutel is geregistreerd:%n%n%1%n%nBedankt voor uw ondersteuning!'),
    (English: 'Are you sure you want to remove your commercial license key and revert to non-commercial use only?'; Localized: 'Weet u zeker dat u uw commerciële licentiesleutel wilt verwijderen en wilt terugkeren naar uitsluitend niet-commercieel gebruik?'),
    (English: 'Commercial license key has been removed.'; Localized: 'Commerciële licentiesleutel is verwijderd.'),
    (English: 'Your version of Inno Setup has been updated! <a id="%1">See what''s new</a>.'; Localized: 'Uw versie van Inno Setup is bijgewerkt! <a id="%1">Bekijk wat er nieuw is</a>.'),
    (English: 'VS Code-style editor shortcuts added! Use the <a id="%1">Editor Keys option</a> in Options dialog.'; Localized: 'Editorsneltoetsen in VS Code-stijl toegevoegd! Gebruik de <a id="%1">optie Editortoetsen</a> in het venster Opties.'),
    (English: 'Inno Setup Compiler is available in your language! Use the <a id="%1">Language option</a> in Options dialog.'; Localized: 'Inno Setup Compiler is beschikbaar in uw taal! Gebruik de <a id="%1">optie Taal</a> in het venster Opties.'),
    (English: '<a id="%1">Ideas board is open!</a> Share your ideas and vote on others, this month only.'; Localized: '<a id="%1">Het ideeënbord is open!</a> Deel uw ideeën en stem op die van anderen, alleen deze maand.'),
    (English: 'Running a version released after your update entitlement ended. <a id="%1">Renew license</a>, <a id="%2">remove key</a>, or <a id="%3">exit</a>.'; Localized: 'U gebruikt een versie die is uitgebracht nadat uw recht op updates is verlopen. <a id="%1">Licentie verlengen</a>, <a id="%2">licentiesleutel verwijderen</a> of <a id="%3">afsluiten</a>.'),
    (English: 'Your update entitlement is ending soon. Please <a id="%1">renew your license</a>. Thanks!'; Localized: 'Uw recht op updates verloopt binnenkort. <a id="%1">Verleng uw licentie</a>. Bedankt!'),
    (English: 'Your update entitlement has ended. Please <a id="%1">renew your license</a>. Thanks!'; Localized: 'Uw recht op updates is verlopen. <a id="%1">Verleng uw licentie</a>. Bedankt!'),
    (English: 'Using Inno Setup commercially? Please <a id="%1">purchase a license</a>. Thanks!'; Localized: 'Gebruikt u Inno Setup commercieel? <a id="%1">Schaf een licentie aan</a>. Bedankt!'),
    (English: 'Uninstall'; Localized: 'Verwijderprogramma'),
    (English: '%1 exit code: 0x%2'; Localized: 'Afsluitcode van %1: 0x%2'),
    (English: '%1 exit code: %2'; Localized: 'Afsluitcode van %1: %2'),
    (English: 'Unable to get %1 exit code (%2 failed)'; Localized: 'Kan afsluitcode van %1 niet ophalen (%2 mislukt)'),
    (English: '%1 is still running; can''t get exit code'; Localized: '%1 wordt nog uitgevoerd; kan afsluitcode niet ophalen'),
    (English: 'Please stop the running %1 process before performing this command.'; Localized: 'Stop het actieve %1-proces voordat u deze opdracht uitvoert.'),
    (English: 'This command will detach the debugger from the running %1 process. Continue?'; Localized: 'Met deze opdracht wordt de debugger losgekoppeld van het actieve %1-proces. Doorgaan?'),
    (English: 'The changes you made will not take effect until you re-compile.%n%nContinue running anyway?'; Localized: 'De wijzigingen die u hebt aangebracht, worden pas van kracht nadat u opnieuw compileert.%n%nToch doorgaan met uitvoeren?'),
    (English: 'A pause is already pending.'; Localized: 'Er is al een pauze in behandeling.'),
    (English: 'No code was generated for the current line.'; Localized: 'Er is geen code gegenereerd voor de huidige regel.'),
    (English: 'This will unconditionally terminate the running %1 process. Continue?'; Localized: 'Hiermee wordt het actieve %1-proces onvoorwaardelijk beëindigd. Doorgaan?'),
    (English: 'Note that if %1 is currently in the installation phase, any changes made to the system thus far will not be undone, nor will uninstall data be written.'; Localized: 'Houd er rekening mee dat als %1 zich momenteel in de installatiefase bevindt, de tot nu toe aangebrachte wijzigingen in het systeem niet ongedaan worden gemaakt en er geen verwijderingsinformatie wordt weggeschreven.'),
    (English: 'Evaluate'; Localized: 'Evalueren'),
    (English: 'Constant to evaluate (for example, "%1"):'; Localized: 'Te evalueren constante (bijvoorbeeld "%1"):'),
    (English: 'Evaluate Result'; Localized: 'Evaluatieresultaat'),
    (English: 'Evaluate Error'; Localized: 'Evaluatiefout'),
    (English: 'An unknown error occurred.'; Localized: 'Er is een onbekende fout opgetreden.'),
    (English: '%1 = "%2"'; Localized: '%1 = "%2"'),
    (English: '%1 = Exception: %2'; Localized: '%1 = Uitzondering: %2'),
    (English: '%1 = Unknown error'; Localized: '%1 = Onbekende fout'),
    (English: 'Unknown error'; Localized: 'Onbekende fout'),
    (English: 'Line %1:%n%2'; Localized: 'Regel %1:%n%2'),
    (English: 'Runtime Error'; Localized: 'Runtimefout'),
    (English: '%1 (Update entitlement ended)'; Localized: '%1 (Recht op updates verlopen)'),
    (English: '%1 (Update entitlement ended but updated anyway)'; Localized: '%1 (Recht op updates verlopen maar toch bijgewerkt)'),
    (English: 'Non-commercial use only'; Localized: 'Alleen niet-commercieel gebruik'),
    (English: 'Single User'; Localized: 'Single User'),
    (English: 'Team'; Localized: 'Team'),
    (English: 'Enterprise'; Localized: 'Enterprise'),
    (English: 'Inno Setup %1 License'; Localized: 'Inno Setup %1-licentie'),
    (English: '%1, %2.'; Localized: '%1, %2.'),
    (English: 'Includes updates until %1, major and minor.'; Localized: 'Inclusief updates tot %1, hoofd- en subversies.'),
    (English: 'Includes all future updates, major and minor.'; Localized: 'Inclusief alle toekomstige updates, hoofd- en subversies.'),
    (English: '%1 Entries Designer'; Localized: 'Ontwerper voor %1-vermeldingen'),
    (English: '&Insert'; Localized: '&Invoegen'),
    (English: '&Parameters...'; Localized: 'P&arameters...'),
    (English: 'Remo&ve'; Localized: '&Verwijderen'),
    (English: 'Add Fol&der...'; Localized: '&Map toevoegen...'),
    (English: '&Add File(s)...'; Localized: 'Bestand(en) &toevoegen...'),
    (English: '&Files:'; Localized: '&Bestanden:'),
    (English: 'Add D&ownload...'; Localized: '&Download toevoegen...'),
    (English: 'Go to File'; Localized: 'Ga naar bestand'),
    (English: 'Enter Commercial License Key'; Localized: 'Commerciële licentiesleutel invoeren'),
    (English: 'Paste your license key below'; Localized: 'Plak hieronder uw licentiesleutel'),
    (English: 'Close'; Localized: 'Sluiten'),
    (English: 'New Main Script (%1)'; Localized: 'Nieuw hoofdscript (%1)'),
    (English: 'Open Main Script (%1)'; Localized: 'Hoofdscript openen (%1)'),
    (English: 'Save (%1)'; Localized: 'Opslaan (%1)'),
    (English: 'Stop Compile (%1)'; Localized: 'Compileren stoppen (%1)'),
    (English: 'Target Setup (%1)'; Localized: 'Setup als doel instellen (%1)'),
    (English: 'Target Uninstall (%1)'; Localized: 'Verwijderprogramma als doel instellen (%1)'),
    (English: 'Help (%1)'; Localized: 'Help (%1)'),
    (English: 'Main Script'; Localized: 'Hoofdscript'),
    (English: 'Close Banner'; Localized: 'Banner sluiten'),
    (English: '&File'; Localized: '&Bestand'),
    (English: '&Open...'; Localized: '&Openen...'),
    (English: 'Open &Recent'; Localized: '&Recente bestanden'),
    (English: '&Clear Recently Opened'; Localized: 'Recente bestanden &wissen'),
    (English: '&Save'; Localized: 'Op&slaan'),
    (English: 'Save &As...'; Localized: 'Opslaan &als...'),
    (English: 'Save &Encoding'; Localized: '&Codering opslaan'),
    (English: '&Auto (ANSI or UTF-8)'; Localized: '&Automatisch (ANSI of UTF-8)'),
    (English: '&UTF-8'; Localized: '&UTF-8'),
    (English: 'UTF-8 with &BOM'; Localized: 'UTF-8 met &BOM'),
    (English: 'Sa&ve All'; Localized: 'A&lles opslaan'),
    (English: '&Print...'; Localized: 'Af&drukken...'),
    (English: 'E&xit'; Localized: 'Afslui&ten'),
    (English: '&Edit'; Localized: 'Be&werken'),
    (English: '&Undo'; Localized: '&Ongedaan maken'),
    (English: '&Redo'; Localized: 'Opnieu&w'),
    (English: 'Cu&t'; Localized: 'K&nippen'),
    (English: '&Copy'; Localized: '&Kopiëren'),
    (English: '&Paste'; Localized: '&Plakken'),
    (English: 'De&lete'; Localized: '&Verwijderen'),
    (English: 'Select &All'; Localized: '&Alles selecteren'),
    (English: 'Add Next &Occurrence'; Localized: 'Volgend e&xemplaar toevoegen'),
    (English: '&Select All Occurrences'; Localized: 'Alle exemplaren &selecteren'),
    (English: 'Select All Find &Matches'; Localized: 'Alle zoekovereenko&msten selecteren'),
    (English: '&Find...'; Localized: '&Zoeken...'),
    (English: 'F&ind in Files...'; Localized: 'Zoeken in &bestanden...'),
    (English: 'Find &Next'; Localized: 'Volgen&de zoeken'),
    (English: 'Find Pre&vious'; Localized: 'Vor&ige zoeken'),
    (English: 'R&eplace...'; Localized: 'Ve&rvangen...'),
    (English: 'Use Regular E&xpressions'; Localized: 'Regu&liere expressies gebruiken'),
    (English: 'Fol&d Section'; Localized: 'Se&ctie samenvouwen'),
    (English: '&Unfold Section'; Localized: 'Sectie &uitvouwen'),
    (English: 'Go to File...'; Localized: 'Ga naar bestand...'),
    (English: '&Go to Line...'; Localized: '&Ga naar regel...'),
    (English: 'Toggle Line Comment'; Localized: 'Regelcommentaar aan/uit'),
    (English: 'Go To Matching Brace'; Localized: 'Ga naar bijbehorend haakje'),
    (English: '&View'; Localized: 'B&eeld'),
    (English: '&Zoom'; Localized: 'Zoo&men'),
    (English: 'Zoom &In'; Localized: '&Inzoomen'),
    (English: 'Zoom &Out'; Localized: '&Uitzoomen'),
    (English: '&Reset'; Localized: '&Herstellen'),
    (English: '&Toolbar'; Localized: '&Werkbalk'),
    (English: 'St&atus Bar'; Localized: '&Statusbalk'),
    (English: '&Next Tab'; Localized: '&Volgend tabblad'),
    (English: '&Previous Tab'; Localized: 'Vo&rig tabblad'),
    (English: 'C&lose Tab'; Localized: 'Tabblad sl&uiten'),
    (English: 'Re&open Tab'; Localized: 'Tabblad &opnieuw openen'),
    (English: 'Reopen &All Tabs'; Localized: 'A&lle tabbladen opnieuw openen'),
    (English: 'C&lose Current Tab'; Localized: 'Huidig tabblad sl&uiten'),
    (English: '&Compiler Output'; Localized: '&Compiler-uitvoer'),
    (English: '&Debug Output'; Localized: '&Debug-uitvoer'),
    (English: 'D&ebug Call Stack'; Localized: 'Debug-&aanroepstack'),
    (English: '&Find Results'; Localized: '&Zoekresultaten'),
    (English: '&Hide Bottom Pane'; Localized: 'Onderste deelvenster ver&bergen'),
    (English: '&Word Wrap'; Localized: '&Tekstterugloop'),
    (English: '&Build'; Localized: 'B&ouwen'),
    (English: '&Compile'; Localized: '&Compileren'),
    (English: 'S&top Compile'; Localized: 'Compileren s&toppen'),
    (English: '&Low Priority During Compile'; Localized: '&Lage prioriteit tijdens compileren'),
    (English: '&Disable Output'; Localized: '&Uitvoer uitschakelen'),
    (English: 'Disable Co&mpression'; Localized: 'Co&mpressie uitschakelen'),
    (English: 'Disable &Signing'; Localized: 'Ondertekenen uit&schakelen'),
    (English: 'Disable Signcheck &Validation'; Localized: 'Signcheck-&validatie uitschakelen'),
    (English: '&Open Output Folder'; Localized: 'Uitvoermap &openen'),
    (English: '&Run'; Localized: '&Uitvoeren'),
    (English: '&Run...'; Localized: '&Uitvoeren...'),
    (English: 'Run to &Cursor'; Localized: 'Uitvoeren tot &cursor'),
    (English: 'Step &Into'; Localized: 'Stap &in'),
    (English: 'Step &Over'; Localized: 'Stap o&ver'),
    (English: 'Step Out'; Localized: 'Stap uit'),
    (English: 'Toggle &Breakpoint'; Localized: '&Onderbrekingspunt aan/uit'),
    (English: '&Delete All Breakpoints'; Localized: 'Alle onderbrekingspunten ver&wijderen'),
    (English: 'P&ause'; Localized: '&Pauzeren'),
    (English: '&Terminate'; Localized: '&Beëindigen'),
    (English: '&Evaluate Constant...'; Localized: 'Constante &evalueren...'),
    (English: 'Target &Setup'; Localized: '&Setup als doel instellen'),
    (English: 'Target &Uninstall'; Localized: 'Verwijderprogramma als &doel instellen'),
    (English: '&Tools'; Localized: 'E&xtra'),
    (English: '&Add/Remove Programs'; Localized: '&Programma''s toevoegen of verwijderen'),
    (English: 'Generate &GUID'; Localized: '&GUID genereren'),
    (English: 'Generate %1 Entries...'; Localized: '%1-vermeldingen genereren...'),
    (English: 'Generate %1 Call...'; Localized: '%1-aanroep genereren...'),
    (English: '&Configure Sign Tools...'; Localized: 'Ondertekeningstools &configureren...'),
    (English: '&Options...'; Localized: '&Opties...'),
    (English: '&Help'; Localized: '&Help'),
    (English: 'Purchase or Renew Commercial &License'; Localized: 'Commerciële &licentie aanschaffen of verlengen'),
    (English: 'Enter Commercial License &Key...'; Localized: 'Commerciële licentie&sleutel invoeren...'),
    (English: 'Remove Commercial License Key'; Localized: 'Commerciële licentiesleutel verwijderen'),
    (English: '&Donate'; Localized: '&Doneren'),
    (English: '&Keyboard And Mouse Commands'; Localized: '&Toetsenbord- en muisopdrachten'),
    (English: 'Regular E&xpressions'; Localized: 'Reguliere e&xpressies'),
    (English: 'Inno &Setup Documentation'; Localized: 'Inno Setup-do&cumentatie'),
    (English: 'Inno Setup &Example Scripts'; Localized: 'Inno Setup-&voorbeeldscripts'),
    (English: 'Inno Setup &FAQ'; Localized: 'Inno Setup-&FAQ'),
    (English: 'Inno Setup &Mailing List'; Localized: 'Inno Setup-&mailinglijst'),
    (English: 'Inno Setup &Revision History'; Localized: 'Inno Setup-&revisiegeschiedenis'),
    (English: 'Inno Setup &Web Site'; Localized: 'Inno Setup-&website'),
    (English: 'Inno Setup &Preprocessor Documentation'; Localized: 'Inno Setup &Preprocessor-documentatie'),
    (English: '&About Inno Setup'; Localized: '&Over Inno Setup'),
    (English: '%1 Call Designer'; Localized: 'Ontwerper voor %1-aanroep'),
    (English: 'Instruction'; Localized: 'Instructie'),
    (English: 'Message'; Localized: 'Bericht'),
    (English: 'Buttons'; Localized: 'Knoppen'),
    (English: ' Type '; Localized: ' Type '),
    (English: 'Suppressible'; Localized: 'Onderdrukbaar'),
    (English: ' Flags '; Localized: ' Vlaggen '),
    (English: 'Default button'; Localized: 'Standaardknop'),
    (English: ' Icon '; Localized: ' Pictogram '),
    (English: ' Return values '; Localized: ' Retourwaarden '),
    (English: '&Preview'; Localized: '&Voorbeeld'),
    (English: 'Options'; Localized: 'Opties'),
    (English: ' Miscellaneous '; Localized: ' Diversen '),
    (English: 'Show &Welcome dialog at startup'; Localized: '&Welkomstvenster tonen bij opstarten'),
    (English: 'Use the Inno Setup &Script Wizard'; Localized: 'De Inno Setup-scriptwi&zard gebruiken'),
    (English: 'Automatically sa&ve before compiling'; Localized: 'Automatisch opslaan &vóór compileren'),
    (English: 'Create &backups when saving'; Localized: '&Back-ups maken bij opslaan'),
    (English: 'Allow &Undo after save'; Localized: 'Ongedaan maken na ops&laan toestaan'),
    (English: 'Display &full path in title bar'; Localized: 'V&olledig pad in titelbalk tonen'),
    (English: '&Pause on exceptions'; Localized: '&Pauzeren bij uitzonderingen'),
    (English: '&Launch Setup/Uninstall as administrator'; Localized: 'Setup/V&erwijderprogramma als beheerder starten'),
    (English: 'Colori&ze "Compiler Output" view'; Localized: 'Wee&rgave "Compiler-uitvoer" inkleuren'),
    (English: 'Automatically open %1 files'; Localized: '%1-bestanden automatisch openen'),
    (English: 'Automatically show preprocessor output'; Localized: 'Preprocessor-uitvoer automatisch tonen'),
    (English: 'Menu &keys:'; Localized: 'Men&utoetsen:'),
    (English: 'Automatically reload files'; Localized: 'Bestanden automatisch opnieuw laden'),
    (English: 'Allow Undo after reload'; Localized: 'Ongedaan maken na opnieuw laden toestaan'),
    (English: 'Keep new %1 files closed'; Localized: 'Nieuwe %1-bestanden gesloten houden'),
    (English: 'Language:'; Localized: 'Taal:'),
    (English: ' Editor '; Localized: ' Editor '),
    (English: 'Invoke autoco&mplete automatically'; Localized: 'Aa&nvulling automatisch aanroepen'),
    (English: 'Use syntax &highlighting'; Localized: 'S&yntaxismarkering gebruiken'),
    (English: 'U&nderline syntax errors'; Localized: 'Syntaxis&fouten onderstrepen'),
    (English: 'Allow cursor to move beyond &end of lines'; Localized: '&Cursor voorbij regeleinde laten gaan'),
    (English: 'Enable section f&olding'; Localized: 'Sectievouwen inscha&kelen'),
    (English: 'Use tab cha&racter'; Localized: '&Tabteken gebruiken'),
    (English: 'Auto &indent mode'; Localized: 'Auto&matisch inspringen'),
    (English: 'Show indentation &guides'; Localized: '&Inspringhulplijnen tonen'),
    (English: 'Font:'; Localized: 'Lettertype:'),
    (English: 'AaBbXxZz'; Localized: 'AaBbXxZz'),
    (English: '&Change...'; Localized: 'Wijzi&gen...'),
    (English: '&Tab Width:'; Localized: 'Tabbree&dte:'),
    (English: 'Show &line numbers in gutter'; Localized: 'Regelnummers in kantli&jn tonen'),
    (English: 'T&heme:'; Localized: 'T&hema:'),
    (English: 'Highlight occurrences of current selection'; Localized: 'Exemplaren van huidige selectie markeren'),
    (English: 'Highlight occurrences of current wor&d'; Localized: 'E&xemplaren van huidig woord markeren'),
    (English: 'Ke&ys:'; Localized: 'Toet&sen:'),
    (English: 'Show whitespace'; Localized: 'Witruimte tonen'),
    (English: 'Smart Home key'; Localized: 'Slimme Home-toets'),
    (English: '&Associate .%1 files with this compiler'; Localized: '.%1-bestanden &aan deze compiler koppelen'),
    (English: '&Windows registry file (.%1) to import:'; Localized: '&Windows-registerbestand (.%1) om te importeren:'),
    (English: 'B&rowse...'; Localized: 'Bladere&n...'),
    (English: 'Settings (for all keys and values):'; Localized: 'Instellingen (voor alle sleutels en waarden):'),
    (English: 'Also delete keys which are not empty'; Localized: 'Ook sleutels verwijderen die niet leeg zijn'),
    (English: 'Delete keys which are empty on uninstall'; Localized: 'Lege sleutels verwijderen bij het verwijderen'),
    (English: 'Delete values on uninstall'; Localized: 'Waarden verwijderen bij het verwijderen'),
    (English: 'Minimum Windows version:'; Localized: 'Minimale Windows-versie:'),
    (English: 'Configure Sign Tools'; Localized: 'Ondertekeningstools configureren'),
    (English: ' Sign Tools '; Localized: ' Ondertekeningstools '),
    (English: '&Add...'; Localized: '&Toevoegen...'),
    (English: '&Edit...'; Localized: '&Bewerken...'),
    (English: 'Be notified by e-mail of new Inno Setup releases'; Localized: 'Word per e-mail op de hoogte gesteld van nieuwe Inno Setup-uitgaven'),
    (English: 'Subscribe'; Localized: 'Abonneren'),
    (English: ' New file '; Localized: ' Nieuw bestand '),
    (English: 'Create a new &empty script file'; Localized: 'Een nieuw &leeg scriptbestand maken'),
    (English: 'Create a new script file using the &Script Wizard'; Localized: 'Een nieuw scriptbestand maken met de &Scriptwizard'),
    (English: ' Open file '; Localized: ' Bestand openen '),
    (English: 'Open an e&xisting script file'; Localized: 'Een &bestaand scriptbestand openen'),
    (English: '&Don''t show this dialog again'; Localized: '&Dit venster niet opnieuw tonen'),
    (English: 'Script Wizard File'; Localized: 'Scriptwizardbestand'),
    (English: 'bold'; Localized: 'vet'),
    (English: ' = required'; Localized: ' = vereist'),
    (English: ' Destination '; Localized: ' Doel '),
    (English: 'Destination &base folder:'; Localized: 'Doel&basismap:'),
    (English: 'Destination &subfolder:'; Localized: 'Doel&submap:'),
    (English: 'Destination &name:'; Localized: 'Doel&naam:'),
    (English: ' Source '; Localized: ' Bron '),
    (English: '&Source file or folder:'; Localized: 'B&ronbestand of -map:'),
    (English: '&Recurse subfolders'; Localized: 'Submappen &doorlopen'),
    (English: '&Include empty subfolders'; Localized: '&Lege submappen opnemen'),
    (English: '&Extract archive'; Localized: '&Archief uitpakken'),
    (English: 'Welcome to the %1'; Localized: 'Welkom bij de %1'),
    (English: 'This wizard will guide you through the process of creating a new Inno Setup script file. The results will be used to generate a new script file which can be compiled directly or saved on disk for later use.%n%nNot all features of Inno Setup are covered by this wizard. See the documentation for details on creating Inno Setup script files.%n%nClick Next to continue, or Cancel to exit this wizard.'; Localized: 'Deze wizard begeleidt u bij het maken van een nieuw Inno Setup-scriptbestand. De resultaten worden gebruikt om een nieuw scriptbestand te genereren dat direct kan worden gecompileerd of op schijf kan worden opgeslagen voor later gebruik.%n%nNiet alle functies van Inno Setup worden door deze wizard behandeld. Raadpleeg de documentatie voor details over het maken van Inno Setup-scriptbestanden.%n%nKlik op Volgende om door te gaan of op Annuleren om deze wizard af te sluiten.'),
    (English: 'Application na&me:'; Localized: 'Toepassings&naam:'),
    (English: 'Application &version:'; Localized: 'Toepassings&versie:'),
    (English: 'Application &publisher:'; Localized: 'Toepassings&uitgever:'),
    (English: 'Application &website:'; Localized: 'Toepassings&website:'),
    (English: 'Application folder na&me:'; Localized: '&Naam toepassingsmap:'),
    (English: 'Application &destination base folder:'; Localized: '&Doelbasismap van toepassing:'),
    (English: 'Other:'; Localized: 'Overig:'),
    (English: 'Allow user to &change the application folder'; Localized: 'Gebruiker mag de toepassingsmap &wijzigen'),
    (English: 'The application doe&sn''t need a folder'; Localized: 'De toepassing heeft &geen map nodig'),
    (English: 'Other application &files:'; Localized: 'Andere toepassings&bestanden:'),
    (English: 'Application &main executable file:'; Localized: '&Hoofduitvoerbaar bestand van toepassing:'),
    (English: 'Allow &user to start the application after Setup has finished'; Localized: 'Toestaan dat de gebr&uiker de toepassing start nadat Setup is voltooid'),
    (English: 'The application doe&sn''t have a main executable file'; Localized: 'De toepassing heeft &geen hoofduitvoerbaar bestand'),
    (English: 'Application file type na&me:'; Localized: '&Naam toepassingsbestandstype:'),
    (English: '&Associate a file type to the main executable'; Localized: 'Een bestandstype aan het hoofduitvoerbare bestand &koppelen'),
    (English: 'Application file type &extension:'; Localized: '&Extensie toepassingsbestandstype:'),
    (English: 'Application &Start Menu folder name:'; Localized: '&Naam map in menu Start van toepassing:'),
    (English: 'Other shortcuts to the main executable:'; Localized: 'Andere snelkoppelingen naar het hoofduitvoerbare bestand:'),
    (English: 'Allow user to &change the Start Menu folder name'; Localized: 'Gebruiker mag de mapnaam in het menu Start &wijzigen'),
    (English: 'Allow user to &disable Start Menu folder creation'; Localized: 'Gebruiker mag het maken van de map in het menu Start &uitschakelen'),
    (English: 'Allow user to create a deskto&p shortcut'; Localized: 'Gebruiker mag een &bureaubladsnelkoppeling maken'),
    (English: 'Create an &Uninstall shortcut in the Start Menu folder'; Localized: 'Een snelkoppeling naar het &verwijderprogramma maken in de map van het menu Start'),
    (English: 'Create an &Internet shortcut in the Start Menu folder'; Localized: 'Een &internetsnelkoppeling maken in de map van het menu Start'),
    (English: '&Create a Start Menu shortcut but no folder'; Localized: 'Een &snelkoppeling in het menu Start maken, maar geen map'),
    (English: '&License file:'; Localized: '&Licentiebestand:'),
    (English: '&Information file shown before installation:'; Localized: '&Informatiebestand dat vóór installatie wordt getoond:'),
    (English: 'Information file shown &after installation:'; Localized: 'Informatiebestand dat na installatie wordt &getoond:'),
    (English: 'Install mode:'; Localized: 'Installatiemodus:'),
    (English: '&Administrative install mode (install for all users)'; Localized: '&Administratieve installatiemodus (installeren voor alle gebruikers)'),
    (English: 'Non a&dministrative install mode (install for current user only)'; Localized: 'Niet-a&dministratieve installatiemodus (installeren voor alleen de huidige gebruiker)'),
    (English: 'Allow user to &override the install mode via the command line'; Localized: 'Gebruiker mag de installatiemodus &overschrijven via de opdrachtregel'),
    (English: 'Ask the user to &choose the install mode at startup'; Localized: 'Gebruiker bij het opstarten vragen de installatiemodus te &kiezen'),
    (English: '&Languages:'; Localized: '&Talen:'),
    (English: '&Deselect All'; Localized: 'Alles &deselecteren'),
    (English: 'Custom compiler output fol&der:'; Localized: 'Aangepaste compiler-uitvoer&map:'),
    (English: 'Compiler output base &file name:'; Localized: 'Basis&bestandsnaam van compiler-uitvoer:'),
    (English: 'Custom Setup &icon file:'; Localized: 'Aangepast Setup-&pictogrambestand:'),
    (English: 'Setup &password:'; Localized: 'Setup-&wachtwoord:'),
    (English: 'Use the password to &encrypt the application files'; Localized: 'Het wachtwoord gebruiken om de toepassingsbestanden te &versleutelen'),
    (English: '&Wizard style:'; Localized: '&Wizardstijl:'),
    (English: 'You have successfully completed the %1.%n%nTo close this wizard and generate the new script file, click Finish.'; Localized: 'U hebt de %1 voltooid.%n%nKlik op Voltooien om deze wizard te sluiten en het nieuwe scriptbestand te genereren.'),
    (English: '&Back'; Localized: 'Vo&rige'));

implementation

end.
