unit IDE.LocalizeFunc.Ukrainian;

{
  Inno Setup
  Copyright (C) 1997-2026 Jordan Russell
  Portions by Martijn Laan
  For conditions of distribution and use, see LICENSE.TXT.

  Compiler IDE Ukrainian translations
}

interface

uses
  IDE.LocalizeFunc;

const
  UkrainianIDETranslations: array [0..1015] of TTranslationPair = (
    (English: 'Command-line usage:'; Localized: 'Використання командного рядка:'),
    (English: 'Examples:'; Localized: 'Приклади:'),
    (English: 'script file'; Localized: 'файл сценарію'),
    (English: 'wizard name'; Localized: 'назва майстра'),
    (English: 'My script'; Localized: 'Мій сценарій'),
    (English: 'My Script Wizard'; Localized: 'Мій майстер сценаріїв'),
    (English: 'Could not load %1: %2'; Localized: 'Не вдалося завантажити %1: %2'),
    (English: 'Inno Setup Compiler'; Localized: 'Inno Setup Compiler'),
    (English: 'Example scripts...'; Localized: 'Приклади сценаріїв...'),
    (English: 'More files...'; Localized: 'Інші файли сценаріїв...'),
    (English: 'Untitled'; Localized: 'Без назви'),
    (English: 'Preprocessor Output'; Localized: 'Вихід препроцесора'),
    (English: 'Run Parameters'; Localized: 'Параметри командного рядка'),
    (English: 'Command-line parameters for %1 and %2:'; Localized: 'Параметри запуску для %1 та %2:'),
    (English: 'Inno Setup Script files'; Localized: 'Сценарії Inno Setup'),
    (English: 'All files'; Localized: 'Усі файли'),
    (English: 'Application files'; Localized: 'Файли програм'),
    (English: 'Documentation files'; Localized: 'Файли документів'),
    (English: 'Rich Text Format files'; Localized: 'Файли RTF'),
    (English: 'Registry files'; Localized: 'Файли реєстру'),
    (English: 'Icon files'; Localized: 'Файли значків'),
    (English: 'Image files'; Localized: 'Файли зображень'),
    (English: 'VCL Styles files'; Localized: 'Файли стилів VCL'),
    (English: 'Inno Setup Messages files'; Localized: 'Файли повідомлень Inno Setup'),
    (English: 'Public key files'; Localized: 'Файли відкритих ключів'),
    (English: 'Text files'; Localized: 'Текстові файли'),
    (English: 'Inno Setup Script Wizard'; Localized: 'Майстер створення сценаріїв Inno Setup'),
    (English: 'Welcome'; Localized: 'Ласкаво просимо'),
    (English: 'Application Information'; Localized: 'Відомості про програму'),
    (English: 'Please specify some basic information about your application.'; Localized: 'Вкажіть основну інформацію про вашу програму.'),
    (English: 'Application Folder'; Localized: 'Тека встановлення'),
    (English: 'Please specify folder information about your application.'; Localized: 'Вкажіть цільову теку для встановлення вашої програми.'),
    (English: 'Application Files'; Localized: 'Файли програми'),
    (English: 'Please specify the files that are part of your application.'; Localized: 'Вкажіть файли, що входять до складу вашої програми.'),
    (English: 'Please specify the source folder.'; Localized: 'Вкажіть теку з вихідними файлами.'),
    (English: 'Should files in subfolders of "%1" also be included?'; Localized: 'Бажаєте також додати всі файли, що знаходяться у підтеках "%1"?'),
    (English: 'URL:'; Localized: 'URL:'),
    (English: 'Is the file to download an archive which should be extracted?'; Localized: 'Чи є файл для завантаження архівом, який потрібно розпакувати?'),
    (English: 'Name of the file:'; Localized: 'Ім’я файлу:'),
    (English: 'Name of the file (extension should match archive format):'; Localized: 'Ім’я файлу (розширення має відповідати формату архіва):'),
    (English: 'Approximate size of the file in megabytes:'; Localized: 'Приблизний розмір файлу в мегабайтах:'),
    (English: 'Application File Association'; Localized: 'Асоціація файлів'),
    (English: 'Please specify which file association should be created for your application.'; Localized: 'Вкажіть, яку асоціацію файлів слід створити для вашої програми.'),
    (English: '%1 File'; Localized: 'файл %1'),
    (English: 'Application Shortcuts'; Localized: 'Ярлики програми'),
    (English: 'Please specify which shortcuts should be created for your application.'; Localized: 'Вкажіть ярлики, які слід створити для вашої програми.'),
    (English: 'Application Documentation'; Localized: 'Документація програми'),
    (English: 'Please specify which documentation files should be shown by Setup during installation.'; Localized: 'Вкажіть файли документів, які мають відображатися під час встановлення.'),
    (English: 'Setup Install Mode'; Localized: 'Режим встановлення'),
    (English: 'Please specify in which install mode Setup should run.'; Localized: 'Вкажіть режим запуску програми встановлення.'),
    (English: 'Application Registry Keys And Values'; Localized: 'Ключі та значення реєстру'),
    (English: 'Please specify the registry keys and values that are part of your application.'; Localized: 'Додайте ключі та значення реєстру, пов’язані з вашою програмою.'),
    (English: 'Setup Languages'; Localized: 'Мовна підтримка'),
    (English: 'Please specify which Setup languages should be included.'; Localized: 'Вкажіть мови, які слід додати у програму встановлення.'),
    (English: 'Compiler Settings'; Localized: 'Налаштування компілятора'),
    (English: 'Please specify some basic compiler settings.'; Localized: 'Вкажіть деякі основні налаштування компілятора.'),
    (English: 'Please specify the folder.'; Localized: 'Вкажіть теку для створення файлу встановлення.'),
    (English: 'Wizard Style'; Localized: 'Стиль майстра встановлення'),
    (English: 'Please specify which wizard style should be used.'; Localized: 'Вкажіть, який стиль майстра слід використовувати.'),
    (English: 'Inno Setup Preprocessor'; Localized: 'Препроцесор Inno Setup'),
    (English: 'Please specify whether Inno Setup Preprocessor should be used.'; Localized: 'Вкажіть, чи слід використовувати препроцесор Inno Setup.'),
    (English: 'The %1 can use %2 compiler directives to simplify your script. Although this is not necessary, it will make it easier to manually change the script later.%n%nDo you want the %1 to use %2 compiler directives?'; Localized: '%1 може використовувати директиви компілятора %2 для спрощення вашого сценарію. Хоча це не обов’язково, це полегшить редагування сценарію вручну пізніше.%n%nБажаєте, щоб %1 використовував директиви %2?'),
    (English: '&Yes, use %1 compiler directives'; Localized: 'Т&ак, використовувати директиви компілятора %1'),
    (English: 'Finished'; Localized: 'Завершено'),
    (English: '&Next'; Localized: '&Далі'),
    (English: '&Finish'; Localized: '&Завершити'),
    (English: 'The %1 is not complete. If you quit now, the new script file will not be generated.%n%nExit anyway?'; Localized: '%1 не завершив роботу. Якщо ви зараз вийдете, новий файл сценарію не буде згенеровано.%n%nУсе одно бажаєте вийти?'),
    (English: 'Please specify the application name.'; Localized: 'Будь ласка, вкажіть назву програми.'),
    (English: 'Please specify the application version.'; Localized: 'Будь ласка, вкажіть версію програми.'),
    (English: 'Please specify the application destination base folder.'; Localized: 'Будь ласка, вкажіть теку для встановлення програми.'),
    (English: 'Please specify the application folder name.'; Localized: 'Будь ласка, вкажіть назву теки.'),
    (English: 'Please specify the application main executable file.'; Localized: 'Будь ласка, вкажіть головний виконуваний файл програми.'),
    (English: 'The specified application main executable file does not exist.'; Localized: 'Вказаний головний виконуваний файл програми не існує.'),
    (English: 'Please specify the application Start Menu group name.'; Localized: 'Будь ласка, вкажіть назву групи програм у меню ПУСК.'),
    (English: 'Please specify the destination base folder.'; Localized: 'Будь ласка, вкажіть цільову теку встановлення.'),
    (English: 'Please specify a destination base folder other than the application folder.'; Localized: 'Будь ласка, вкажіть цільову теку встановлення, відмінну від теки програми.'),
    (English: 'Please specify the destination name.'; Localized: 'Будь ласка, вкажіть назву призначення.'),
    (English: 'Please select at least one language.'; Localized: 'Будь ласка, вкажіть принаймні одну мову підтримки.'),
    (English: '&Source URL:'; Localized: 'URL-&адреса:'),
    (English: 'Script generated by the %1.'; Localized: 'Цей сценарій згенерував %1.'),
    (English: 'SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!'; Localized: 'ВІДОМОСТІ ЩОДО СТВОРЕННЯ СЦЕНАРІЇВ ДИВІТЬСЯ В ДОКУМЕНТАЦІЇ INNO SETUP!'),
    (English: 'NOTE: The value of %1 uniquely identifies this application. Do not use the same %1 value in installers for other applications.'; Localized: 'ПРИМІТКА. Значення %1 однозначно ідентифікує цю програму. Не використовуйте те саме значення %1 в інсталяторах для інших програм.'),
    (English: '(To generate a new GUID, click Tools | Generate GUID inside the IDE.)'; Localized: '(Щоб створити новий GUID, натисніть в меню "Інструменти" пункт "Створити GUID".)'),
    (English: '"%1" specifies that Setup cannot run on anything but x64 and Windows 11 on Arm.'; Localized: '"%1" вказує, що інсталяція не може працювати на жодних системах, зокрема х64 та Windows 11 на Arm.'),
    (English: '"%1" requests that the install be done in "64-bit mode" on x64 or Windows 11 on Arm.'; Localized: '"%1" вимагає виконання встановлення в "64-розрядному режимі" на системах x64 або Windows 11 на Arm.'),
    (English: 'This means it should use the native 64-bit Program Files directory and the 64-bit view of the registry.'; Localized: 'Це означає, що програма повинна використовувати власний 64-розрядний каталог "Program Files" та 64-розрядне подання реєстру.'),
    (English: 'Uncomment the following line to use a 64-bit installer.'; Localized: 'Розкоментуйте наступний рядок, щоб використовувати 64-розрядний інсталятор.'),
    (English: 'Use "%1" if all your archives are .%2 files.'; Localized: 'Вкажіть "%1", якщо всі архіви є файлами .%2.'),
    (English: 'Use "%1" if all your archives are not password-protected.'; Localized: 'Вкажіть "%1", якщо всі архіви не захищені паролем.'),
    (English: 'Uncomment the following line to run in non administrative install mode (install for current user only).'; Localized: 'Розкоментуйте наступний рядок, щоб запустити інсталятор в режимі встановлення без прав адміністратора (лише для поточного користувача).'),
    (English: 'Remove the following line to run in administrative install mode (install for all users).'; Localized: 'Видаліть наступний рядок, щоб запустити інсталятор в режимі встановлення з правами адміністратора (для всіх користувачів).'),
    (English: 'NOTE: Don''t use "%1" on any shared system files.'; Localized: 'ПРИМІТКА: не використовуйте "%1" для спільних системних файлів.'),
    (English: 'NOTE: Use the "%1" flag or the "%2" parameter to verify downloads.'; Localized: 'ПРИМІТКА: використовуйте флаг "%1" або параметр "%2" для перевірки завантажень.'),
    (English: 'Registry data from file %1'; Localized: 'Дані реєстру з файлу %1'),
    (English: 'COULD NOT IMPORT %1'; Localized: 'НЕ ВДАЛОСЯ ВИКОНАТИ ІМПОРТ %1'),
    (English: 'End of registry data from file %1'; Localized: 'Кінець даних реєстру з файлу %1'),
    (English: 'SOME KEYS FILTERED DUE TO %1 SETTINGS!'; Localized: 'ДЕЯКІ КЛЮЧІ БУЛО ВИКЛЮЧЕНО ЧЕРЕЗ НАЛАШТУВАННЯ %1!'),
    (English: 'SOME VALUES WITH UNSUPPORTED TYPES SKIPPED!'; Localized: 'ДЕЯКІ ЗНАЧЕННЯ БУЛО ПРОПУЩЕНО ЧЕРЕЗ НЕПІДТРИМУВАНІ ТИПИ!'),
    (English: 'Would you like to compile the new script now?'; Localized: 'Бажаєте скомпілювати новий сценарій зараз?'),
    (English: 'My Program'; Localized: 'My Program'),
    (English: 'My Company, Inc.'; Localized: 'My Company, Inc.'),
    (English: 'Application directory'; Localized: 'Тека програми'),
    (English: 'Program Files directory'; Localized: 'Тека "Program Files"'),
    (English: 'Common Files directory'; Localized: 'Тека "Common Files"'),
    (English: 'Windows directory'; Localized: 'Тека Windows'),
    (English: 'Windows system directory'; Localized: 'Системна тека Windows'),
    (English: 'Setup source directory'; Localized: 'Початкова тека встановлення'),
    (English: 'System drive root directory'; Localized: 'Коренева тека системного диска'),
    (English: '(Custom)'; Localized: '(За вибором користувача)'),
    (English: 'Starting compile.%1[%2]'; Localized: 'Початок компіляції.%1[%2]'),
    (English: 'Finished.%1[%2, %3 elapsed]'; Localized: 'Компіляцію завершено.%1[%2, минуло %3]'),
    (English: 'Compile aborted.'; Localized: 'Компіляцію перервано.'),
    (English: 'Log size limit reached, list reset.'; Localized: 'Досягнуто ліміту розміру журналу, список скинуто.'),
    (English: '%1 started'; Localized: '%1 запущено'),
    (English: 'Terminating process'; Localized: 'Завершення процесу'),
    (English: 'Removing left-over temporary directory: %1'; Localized: 'Очищення тимчасової теки: %1'),
    (English: 'Failed to remove temporary directory'; Localized: 'Не вдалося видалити тимчасову теку'),
    (English: '%1 Call Stack'; Localized: 'Стек секції %1'),
    (English: 'Cannot run Setup at this time. Please compile Setup successfully to completion first, with output enabled'; Localized: 'Наразі неможливо запустити програму інсталяції. Будь ласка, спочатку успішно скомпілюйте програму інсталяції до кінця з виведенням файлу.'),
    (English: 'Cannot run Uninstall at this time. Please run Setup successfully to completion first'; Localized: 'Наразі неможливо запустити програму видалення. Будь ласка, спочатку успішно завершіть інсталяцію.'),
    (English: 'Error executing "%1":%n%n%2: %3'; Localized: 'Помилка виконання "%1":%n%n%2: %3'),
    (English: 'Are you sure you want to abort the compile?'; Localized: 'Ви дійсно бажаєте перервати компіляцію?'),
    (English: 'File %1:'; Localized: 'Файл %1:'),
    (English: 'Line %1:'; Localized: 'Рядок %1:'),
    (English: 'Compiler Error'; Localized: 'Помилка компіляції'),
    (English: 'Illegal null character on line %1'; Localized: 'Неприпустимий нульовий символ у рядку %1'),
    (English: 'Cannot find "%1"'; Localized: 'Не вдається знайти "%1"'),
    (English: 'Invalid regular expression "%1"'; Localized: 'Неприпустимий регулярний вираз "%1"'),
    (English: '%1 (%2 hits):'; Localized: '%1 (%2 збігів):'),
    (English: 'Find "%1" (%2 hits in %3 files)'; Localized: 'Пошук "%1" (%2 збігів в %3 Файлах)'),
    (English: '%1 occurrence(s) replaced.'; Localized: 'Виконано замін: %1.'),
    (English: 'The .%1 extension was successfully associated for the current user with:%n%2'; Localized: 'Розширення .%1 успішно пов’язано для поточного користувача з:%n%2'),
    (English: 'The .%1 extension was successfully associated for all users with:%n%2'; Localized: 'Розширення .%1 успішно пов’язано для всіх користувачів з:%n%2'),
    (English: 'Error creating file association:%n%1 - %2'; Localized: 'Помилка створення асоціації файлів:%n%1 - %2'),
    (English: 'Unable to associate for all users without administrative privileges. Do you want to associate only for yourself instead?'; Localized: 'Неможливо виконати асоціацію для всіх користувачів без адміністративних привілеїв. Бажаєте встановити асоціацію лише для себе?'),
    (English: 'Associate'; Localized: 'Асоціація файлів'),
    (English: 'Inno Setup Script'; Localized: 'Сценарій Inno Setup'),
    (English: 'Compi&le'; Localized: '&Компілювати'),
    (English: '&Script has %1'; Localized: '&Сценарій використовує %1'),
    (English: 'Script has %1 set'; Localized: 'Сценарій використовує %1'),
    (English: 'Invalid file format.'; Localized: 'Неприпустимий формат файлу.'),
    (English: 'The specified registry file does not exist.'; Localized: 'Вказаний файл реєстру не існує.'),
    (English: 'Setup'; Localized: 'Setup'),
    (English: 'Your message text.'; Localized: 'Текст повідомлення.'),
    (English: 'Enter your text here...'; Localized: 'Введіть тут текст вашого повідомлення...'),
    (English: 'Return values'; Localized: ' Повернення '),
    (English: 'Default'; Localized: ' Типове '),
    (English: 'Shield'; Localized: ' Щит '),
    (English: 'Instruction Text'; Localized: 'Інструкція'),
    (English: 'Message Text'; Localized: 'Повідомлення'),
    (English: 'user clicked %1'; Localized: 'користувач натиснув %1'),
    (English: 'OK'; Localized: 'ОК'),
    (English: 'Yes'; Localized: 'Так'),
    (English: 'No'; Localized: 'Ні'),
    (English: 'Cancel'; Localized: 'Скасувати'),
    (English: 'Retry'; Localized: 'Повторити'),
    (English: 'Ignore'; Localized: 'Пропустити'),
    (English: 'Abort'; Localized: 'Перервати'),
    (English: 'Display a message box'; Localized: 'Виклик діалогового вікна повідомлення'),
    (English: 'Name of the Sign Tool:'; Localized: 'Введіть назву інструмента:'),
    (English: 'Invalid name.'; Localized: 'Неприпустима назва.'),
    (English: 'Duplicate name.'; Localized: 'Ця назва вже використовується. Введіть інше.'),
    (English: 'Command of the Sign Tool:'; Localized: 'Введіть команду:'),
    (English: 'Invalid command.'; Localized: 'Неприпустимий формат команди або її не вказано.'),
    (English: '%1 must be an integer value'; Localized: '%1 має бути цілим числом'),
    (English: 'The script cannot be edited because it is read-only'; Localized: 'Сценарій доступний лише для читання і не може бути відредагований'),
    (English: 'Parameter "%1" cannot be browsed for when the "%2" flag is used'; Localized: 'Неможливо виконати пошук параметра "%1", коли використовується флаг "%2"'),
    (English: 'Move to a parameter entry or a key/value or [Code] section'; Localized: 'Перейдіть до параметра, ключа/значення або секції [Code]'),
    (English: 'Move to a parameter entry or a non-empty key/value or [Code] section'; Localized: 'Перейдіть до параметра, непорожнього ключа/значення або секції [Code]'),
    (English: 'Select entries of one section type, and no other content'; Localized: 'Вибрати записи лише одного типу розділу й нічого більше'),
    (English: 'Unspecified directives are hidden because this section occurs more than once'; Localized: 'Невказані директиви приховано, оскільки цей розділ повторюється більш ніж один раз'),
    (English: 'Unspecified directives are hidden because this is not the main script file'; Localized: 'Невказані директиви приховано, оскільки це не головний файл сценарію'),
    (English: 'Routines'; Localized: 'Процедури та функції'),
    (English: 'Types'; Localized: 'Типи'),
    (English: 'Symbols'; Localized: 'Символи'),
    (English: 'Parameters'; Localized: 'Параметри'),
    (English: 'Locals'; Localized: 'Локальні змінні'),
    (English: 'The generated GUID will be inserted into the editor at the cursor position. Continue?'; Localized: 'Згенерований GUID буде вставлено у місце, де знаходиться курсор. Продовжити?'),
    (English: 'The generated Pascal script will be inserted into the editor at the cursor position, but the cursor is not in the %1 section. Continue anyway?'; Localized: 'Створений сценарій Pascal буде вставлений у місці, де знаходиться курсор, але курсор перебуває поза секцією %1. Продовжити?'),
    (English: 'Classic'; Localized: 'Classic'),
    (English: 'Visual Studio / Visual Studio Code'; Localized: 'Visual Studio / Visual Studio Code'),
    (English: 'Classic / Visual Studio'; Localized: 'Classic / Visual Studio'),
    (English: 'Visual Studio Code'; Localized: 'Visual Studio Code'),
    (English: 'Light'; Localized: 'Світла'),
    (English: 'Dark'; Localized: 'Темна'),
    (English: 'The new language will take effect the next time you start Inno Setup Compiler.'; Localized: 'Нові налаштування мови набудуть чинності під час наступного запуску Inno Setup Compiler.'),
    (English: '&New...'; Localized: '&Новий...'),
    (English: '&New'; Localized: '&Новий'),
    (English: 'Line %1'; Localized: 'Рядок %1'),
    (English: '%1: %2'; Localized: '%1: %2'),
    (English: 'Back (%1)'; Localized: 'Назад (%1)'),
    (English: 'Forward (%1)'; Localized: 'Вперед (%1)'),
    (English: 'Back'; Localized: 'Назад'),
    (English: 'Forward'; Localized: 'Вперед'),
    (English: 'Open'; Localized: 'Відкрити'),
    (English: 'Run'; Localized: 'Виконати'),
    (English: 'Save As'; Localized: 'Зберегти як'),
    (English: 'Font'; Localized: 'Шрифт'),
    (English: 'Text Color'; Localized: 'Колір тексту'),
    (English: 'Background Color'; Localized: 'Колір фону'),
    (English: 'Ctrl+'; Localized: 'Ctrl+'),
    (English: 'Shift+'; Localized: 'Shift+'),
    (English: 'Alt+'; Localized: 'Alt+'),
    (English: 'Num %1'; Localized: 'Num %1'),
    (English: '(32-bit)'; Localized: '(32-біт)'),
    (English: '[Compiling]'; Localized: '[Компіляція]'),
    (English: '[Running]'; Localized: '[Виконання]'),
    (English: '[Paused]'; Localized: '[Пауза]'),
    (English: 'Read only'; Localized: 'Лише читання'),
    (English: 'Modified'; Localized: 'Змінено'),
    (English: 'Overwrite'; Localized: 'Заміна'),
    (English: 'Insert'; Localized: 'Вставлення'),
    (English: 'Tabs closed: %1'; Localized: 'Закриті вкладки: %1'),
    (English: 'Estimated time remaining: %1'; Localized: 'Час, що залишився: %1'),
    (English: 'Average KB/sec: %1'; Localized: 'Швидкість Kб/сек: %1'),
    (English: 'There was an error opening the file. Remove it from the list?'; Localized: 'Під час відкриття файлу сталася помилка. Видалити його зі списку?'),
    (English: 'The text in the %1 file has changed.%n%nDo you want to save the changes?'; Localized: 'Текст у файлі "%1" було змінено.%n%nБажаєте зберегти ці зміни?'),
    (English: 'Please stop the compile process before performing this command.'; Localized: 'Будь ласка, зупиніть процес компіляції перед виконанням цієї команди.'),
    (English: 'A compile is already in progress.'; Localized: 'Процес компіляції вже запущено.'),
    (English: 'The text in the %1 file has changed and must be saved before compiling.%n%nSave the changes and continue?'; Localized: 'Текст у файлі "%1" було змінено і його потрібно зберегти перед компіляцією.%n%nБажаєте зберегти ці зміни та продовжити?'),
    (English: 'Would you like to save the script before compiling?%n%nIf you answer No, the compiled installation will be placed under your My Documents folder by default.'; Localized: 'Бажаєте зберегти сценарій перед компіляцією?%n%nЯкщо ви відповісте "Ні", скомпільована інсталяція буде розміщена у вашій папці "Мої документи" за замовчуванням.'),
    (English: 'The selected file is an %1 file. Go to its tab instead of opening it as the new main file?'; Localized: 'Вибраний файл – це доданий файл "%1". Перейти до його вкладки замість того, щоб відкривати його як новий головний файл?'),
    (English: 'The selected file is not available as a tab. Opening as the new main file instead.'; Localized: 'Вибраний файл недоступний як вкладка. Натомість його буде відкрито як новий головний файл сценарію.'),
    (English: 'Error creating file (code %1). Could not save file'; Localized: 'Помилка створення файлу (код %1). Не вдалося зберегти файл'),
    (English: 'Error creating backup file. Could not save file'; Localized: 'Помилка створення резервної копії. Не вдалося зберегти файл'),
    (English: 'Error removing existing file (code %1). Could not save file'; Localized: 'Помилка видалення файлу (код %1). Не вдалося зберегти файл'),
    (English: 'Error renaming temporary file (code %1). Could not save file'; Localized: 'Помилка перейменування тимчасового файлу (код %1). Не вдалося зберегти файл'),
    (English: 'Failed to open included file: %1'; Localized: 'Не вдалося відкрити доданий файл: %1'),
    (English: 'Cannot start printer document.'; Localized: 'Не вдається розпочати друк документа.'),
    (English: 'Are you sure you want to clear the list of recently opened files?'; Localized: 'Ви впевнені, що бажаєте очистити список нещодавно відкритих файлів?'),
    (English: 'The %1 file has been modified outside of the source editor. You might want to reload it.'; Localized: 'Файл "%1" було змінено поза межами цього редактора. Можливо, його слід перезавантажити.'),
    (English: 'The %1 file has been modified outside of the source editor.%n%nDo you want to reload the file?'; Localized: 'Файл "%1" було змінено поза межами цього редактора.%n%nБажаєте перезавантажити цей файл?'),
    (English: 'The %1 file has been modified outside of the source editor. Changes have also been made in the source editor.%n%nDo you want to reload the file and lose the changes made in the source editor?'; Localized: 'Файл "%1" було змінено поза межами цього редактора. Зміни також було внесено в сучасному редакторі.%n%nЧи бажаєте ви перезавантажити файл і втратити зміни, внесені в сучасному редакторі?'),
    (English: 'File not opened.'; Localized: 'Файл не відкрито.'),
    (English: 'Go to Line'; Localized: 'Перейти до рядка'),
    (English: 'Line number:'; Localized: 'Введіть номер рядка:'),
    (English: 'Could not load file (code %1)'; Localized: 'Не вдалося завантажити файл (код %1)'),
    (English: 'Could not save file (code %1)'; Localized: 'Не вдалося зберегти файл (код %1)'),
    (English: 'Do you want to copy your current license key to the clipboard before opening our order page? You will need it to be able to renew it.'; Localized: 'Бажаєте скопіювати свій поточний ліцензійний ключ у буфер обміну, перш ніж відкривати сторінку замовлення? Він знадобиться вам для його поновлення.'),
    (English: 'New commercial license key has been registered:%n%n%1%n%nThanks for your support!'; Localized: 'Новий комерційний ліцензійний ключ зареєстровано:%n%n%1%n%nДякуємо за вашу підтримку!'),
    (English: 'Are you sure you want to remove your commercial license key and revert to non-commercial use only?'; Localized: 'Ви дійсно бажаєте видалити свій комерційний ліцензійний ключ і повернутися до використання лише для некомерційних цілей?'),
    (English: 'Commercial license key has been removed.'; Localized: 'Ключ комерційної ліцензії видалено.'),
    (English: 'Your version of Inno Setup has been updated! <a id="%1">See what''s new</a>.'; Localized: 'Ваша версия Inno Setup була оновлена! Натисніть <a id="%1">тут</a>, щоб дізнатися про зміни.'),
    (English: 'VS Code-style editor shortcuts added! Use the <a id="%1">Editor Keys option</a> in Options dialog.'; Localized: 'Додано комбінації клавіш у стилі VS Code! Натисніть <a id="%1">параметр клавіш редактора</a> у діалоговому вікні налаштувань.'),
    (English: 'RTF Editor added, a built-in WordPad replacement! Use the <a id="%1">RTF Editor item</a> in Tools menu.'; Localized: 'Додано редактор RTF — вбудовану альтернативу WordPad! Виберіть в меню "Інструменти" пункт <a id="%1">Редактор RTF</a>.'),
    (English: 'Inno Setup Compiler is available in your language! Use the <a id="%1">Language option</a> in Options dialog.'; Localized: 'Inno Setup Compiler доступний вашою мовою! Натисніть <a id="%1">тут</a> і виберіть її в налаштуваннях.'),
    (English: '<a id="%1">Ideas board is open!</a> Share your ideas and vote on others, this month only.'; Localized: '<a id="%1">Дошка ідей відкрита!</a> Висловлюйте свої ідеї та голосуйте за ідеї інших — лише цього місяця.'),
    (English: 'Running a version released after your update entitlement ended. <a id="%1">Renew license</a>, <a id="%2">remove key</a>, or <a id="%3">exit</a>.'; Localized: 'Ви використовуєте версію, випущену після закінчення терміну дії вашого права на оновлення. <a id="%1">Поновити ліцензію</a>, <a id="%2">видалити ключ</a> або <a id="%3">завершити роботу</a>.'),
    (English: 'Your update entitlement is ending soon. Please <a id="%1">renew your license</a>. Thanks!'; Localized: 'Ваше право на оновлення незабаром закінчиться. Будь ласка, <a id="%1">поновіть свою ліцензію</a>. Дякуємо!'),
    (English: 'Your update entitlement has ended. Please <a id="%1">renew your license</a>. Thanks!'; Localized: 'Ваше право на оновлення закінчилося. Будь ласка, <a id="%1">поновіть свою ліцензію</a>. Дякуємо!'),
    (English: 'Using Inno Setup commercially? Please <a id="%1">purchase a license</a>. Thanks!'; Localized: 'Використовуєте Inno Setup у комерційних цілях? Будь ласка, <a id="%1">придбайте ліцензію</a>. Дякуємо!'),
    (English: 'Uninstall'; Localized: 'Uninstall'),
    (English: '%1 exit code: 0x%2'; Localized: 'Код виходу %1: 0x%2'),
    (English: '%1 exit code: %2'; Localized: 'Код виходу %1: %2'),
    (English: 'Unable to get %1 exit code (%2 failed)'; Localized: 'Не вдалося отримати код виходу %1 (помилка %2)'),
    (English: '%1 is still running; can''t get exit code'; Localized: '%1 все ще працює; не вдається отримати код виходу'),
    (English: 'Please stop the running %1 process before performing this command.'; Localized: 'Будь ласка, зупиніть процес %1 перед виконанням цієї команди.'),
    (English: 'This command will detach the debugger from the running %1 process. Continue?'; Localized: 'Ця команда від’єднає відладчик від запущеного процесу %1. Продовжити?'),
    (English: 'The changes you made will not take effect until you re-compile.%n%nContinue running anyway?'; Localized: 'Внесені зміни набудуть чинності лише після повторної компіляції.%n%nПродовжити виконання?'),
    (English: 'A pause is already pending.'; Localized: 'Процес виконання вже призупинено.'),
    (English: 'No code was generated for the current line.'; Localized: 'Для поточного рядка код не було згенеровано.'),
    (English: 'This will unconditionally terminate the running %1 process. Continue?'; Localized: 'Виконання цієї команди безумовно припинить запущений процес %1. Продовжити?'),
    (English: 'Note that if %1 is currently in the installation phase, any changes made to the system thus far will not be undone, nor will uninstall data be written.'; Localized: 'Зверніть увагу, що якщо %1 зараз перебуває на етапі встановлення, будь-які зміни, внесені до системи на цей момент, не будуть скасовані, а дані видалення не будуть записані.'),
    (English: 'Evaluate'; Localized: 'Значення константи'),
    (English: 'Constant to evaluate (for example, "%1"):'; Localized: 'Ім’я константи (наприклад, "%1"):'),
    (English: 'Evaluate Result'; Localized: 'Результат'),
    (English: 'Evaluate Error'; Localized: 'Помилка'),
    (English: 'An unknown error occurred.'; Localized: 'Сталася невідома помилка.'),
    (English: '%1 = "%2"'; Localized: '%1 = "%2"'),
    (English: '%1 = Exception: %2'; Localized: '%1 = Виняток: %2'),
    (English: '%1 = Unknown error'; Localized: '%1 = Невідома помилка'),
    (English: 'Unknown error'; Localized: 'Невідома помилка'),
    (English: 'Line %1:%n%2'; Localized: 'Рядок %1:%n%2'),
    (English: 'Runtime Error'; Localized: 'Помилка виконання'),
    (English: '%1 (Update entitlement ended)'; Localized: '%1 (Термін підписки закінчився)'),
    (English: '%1 (Update entitlement ended but updated anyway)'; Localized: '%1 (Термін підписки закінчився, але оновлення  було зроблено)'),
    (English: 'Non-commercial use only'; Localized: 'Тільки для некомерційного використання'),
    (English: 'Single User'; Localized: 'Single User'),
    (English: 'Team'; Localized: 'Team'),
    (English: 'Enterprise'; Localized: 'Enterprise'),
    (English: 'Inno Setup %1 License'; Localized: 'Inno Setup %1 License'),
    (English: '%1, %2.'; Localized: '%1, %2.'),
    (English: 'Includes updates until %1, major and minor.'; Localized: 'Включає оновлення до версії %1, як основні, так і другорядні.'),
    (English: 'Includes all future updates, major and minor.'; Localized: 'Включає всі майбутні оновлення, як значні, так і незначні.'),
    (English: '%1 Entries Designer'; Localized: 'Конструктор записів %1'),
    (English: '&Insert'; Localized: '&Вставити'),
    (English: '&Parameters...'; Localized: '&Параметри...'),
    (English: 'Remo&ve'; Localized: 'Вид&алити'),
    (English: 'Add Fol&der...'; Localized: 'Додати те&ку...'),
    (English: '&Add File(s)...'; Localized: 'Додати фай&л(и)...'),
    (English: '&Files:'; Localized: '&Файли:'),
    (English: 'Add D&ownload...'; Localized: '&Завантажити...'),
    (English: 'Go to File'; Localized: 'Перейти до файлу'),
    (English: 'Enter Commercial License Key'; Localized: 'Комерційна ліцензія'),
    (English: 'Paste your license key below'; Localized: 'Додайте свій ліцензійний ключ'),
    (English: 'Close'; Localized: 'Закрити'),
    (English: 'Filter'; Localized: 'Фільтр'),
    (English: 'Inspector Menu'; Localized: 'Меню інспектора'),
    (English: 'Sections'; Localized: 'Розділи'),
    (English: 'New Main Script (%1)'; Localized: 'Новий сценарій (%1)'),
    (English: 'Open Main Script (%1)'; Localized: 'Відкрити сценарій (%1)'),
    (English: 'Save (%1)'; Localized: 'Зберегти (%1)'),
    (English: 'Stop Compile (%1)'; Localized: 'Завершити компіляцію (%1)'),
    (English: 'Target Setup (%1)'; Localized: 'Налагодження Setup (%1)'),
    (English: 'Target Uninstall (%1)'; Localized: 'Налагодження Uninstall (%1)'),
    (English: 'Help (%1)'; Localized: 'Допомога (%1)'),
    (English: 'Main Script'; Localized: 'Головний сценарій'),
    (English: 'Close Banner'; Localized: 'Закрити'),
    (English: '&File'; Localized: '&Файл'),
    (English: '&Open...'; Localized: '&Відкрити...'),
    (English: 'Open &Recent'; Localized: 'Н&ещодавні файли'),
    (English: '&Clear Recently Opened'; Localized: '&Очистити нещодавні файли'),
    (English: '&Save'; Localized: '&Зберегти'),
    (English: 'Save &As...'; Localized: 'Зберегти я&к...'),
    (English: 'Save &Encoding'; Localized: 'Зберегти у код&уванні'),
    (English: '&Auto (ANSI or UTF-8)'; Localized: '&Автоматично (ANSI або UTF-8)'),
    (English: '&UTF-8'; Localized: '&UTF-8'),
    (English: 'UTF-8 with &BOM'; Localized: 'UTF-8 з &BOM'),
    (English: 'Sa&ve All'; Localized: 'Збе&регти все'),
    (English: '&Print...'; Localized: '&Друк...'),
    (English: 'E&xit'; Localized: 'Ви&хід'),
    (English: '&Edit'; Localized: '&Редагувати'),
    (English: '&Undo'; Localized: '&Скасувати'),
    (English: '&Redo'; Localized: '&Повторити'),
    (English: 'Cu&t'; Localized: 'Виріза&ти'),
    (English: '&Copy'; Localized: '&Копіювати'),
    (English: '&Paste'; Localized: 'Вст&авити'),
    (English: 'De&lete'; Localized: 'Ви&далити'),
    (English: 'Select &All'; Localized: '&Вибрати все'),
    (English: 'Add Next &Occurrence'; Localized: 'Додати наступне вход&ження'),
    (English: '&Select All Occurrences'; Localized: 'Виділити всі в&ходження'),
    (English: 'Select All Find &Matches'; Localized: 'Вид&ілити всі знайдені збіги'),
    (English: '&Find...'; Localized: 'З&найти...'),
    (English: 'F&ind in Files...'; Localized: 'Знайти у &файлах...'),
    (English: 'Find &Next'; Localized: 'Зна&йти наступне'),
    (English: 'Find Pre&vious'; Localized: 'Знайти поп&ереднє'),
    (English: 'R&eplace...'; Localized: '&Замінити...'),
    (English: 'Use Regular E&xpressions'; Localized: 'Використовувати ре&гулярні вирази'),
    (English: 'Fol&d Section'; Localized: 'Згорн&ути розділ'),
    (English: 'Unfold Section'; Localized: '&Розгорнути розділ'),
    (English: 'Go to File...'; Localized: 'Перейти до файлу...'),
    (English: '&Go to Line...'; Localized: 'Перейт&и до рядка...'),
    (English: 'Toggle Line Comment'; Localized: 'Перемкнути коментар рядка'),
    (English: 'Go To Matching Brace'; Localized: 'Перейти до відповідної дужки'),
    (English: '&View'; Localized: '&Вигляд'),
    (English: '&Zoom'; Localized: '&Масштаб'),
    (English: 'Zoom &In'; Localized: 'Збі&льшити'),
    (English: 'Zoom &Out'; Localized: 'З&меншити'),
    (English: '&Reset'; Localized: '&Скинути'),
    (English: '&Toolbar'; Localized: '&Панель інструментів'),
    (English: 'Na&vigator'; Localized: '&Навігатор'),
    (English: '&Inspector'; Localized: '&Інспектор'),
    (English: 'St&atus Bar'; Localized: 'Рядок &стану'),
    (English: '&Next Tab'; Localized: 'Наступна вк&ладка'),
    (English: '&Previous Tab'; Localized: 'Попере&дня вкладка'),
    (English: 'C&lose Tab'; Localized: '&Закрити вкладку'),
    (English: 'Re&open Tab'; Localized: 'Знову відкрити вкладк&у'),
    (English: 'Reopen &All Tabs'; Localized: 'Знову відкри&ти всі вкладки'),
    (English: 'C&lose Current Tab'; Localized: 'З&акрити поточну вкладку'),
    (English: 'Focus Navi&gator'; Localized: 'Перейти до наві&гатора'),
    (English: 'Focus And &Select Navigator'; Localized: 'Відкрити навігатор для ви&бору'),
    (English: '&Compiler Output'; Localized: 'Повідомлення &компілятора'),
    (English: '&Debug Output'; Localized: 'Повідомлення налаг&одження'),
    (English: 'D&ebug Call Stack'; Localized: 'Стек &викликів'),
    (English: '&Find Results'; Localized: '&Результати пошуку'),
    (English: '&Hide Bottom Pane'; Localized: 'Сховати ни&жню панель'),
    (English: '&Word Wrap'; Localized: 'П&еренесення за словами'),
    (English: '&Go to'; Localized: '&Перейти до'),
    (English: 'Show all known directives'; Localized: 'Відображати всі відомі директиви'),
    (English: 'Follow cursor'; Localized: 'Стежити за курсором'),
    (English: 'Quote new directive values'; Localized: 'Брати значення нових директив у лапки'),
    (English: 'Quote new parameter values'; Localized: 'Брати значення нових параметрів у лапки'),
    (English: '&Help'; Localized: '&Довідка'),
    (English: '&Build'; Localized: '&Будування'),
    (English: '&Compile'; Localized: '&Компілювати'),
    (English: 'S&top Compile'; Localized: '&Зупинити компіляцію'),
    (English: '&Low Priority During Compile'; Localized: '&Низький пріоритет під час компіляції'),
    (English: '&Disable Output'; Localized: 'Вимкнути &вихід'),
    (English: 'Disable Co&mpression'; Localized: 'Вимкнути &стиснення'),
    (English: 'Disable &Signing'; Localized: 'Вимкнути &цифровий підпис'),
    (English: 'Disable Signcheck &Validation'; Localized: 'Вимкнути &перевірку підпису'),
    (English: '&Open Output Folder'; Localized: 'Відкрити &теку створення'),
    (English: '&Run'; Localized: '&Налагодження'),
    (English: '&Run...'; Localized: '&Виконати...'),
    (English: 'Run to &Cursor'; Localized: 'Виконати до &курсора'),
    (English: 'Step &Into'; Localized: 'Крок із &заходом'),
    (English: 'Step &Over'; Localized: 'Крок з &обходом'),
    (English: 'Step Out'; Localized: 'Крок до виходу'),
    (English: 'Toggle &Breakpoint'; Localized: 'Перемкнути &точку зупинки'),
    (English: '&Delete All Breakpoints'; Localized: 'Ви&далити всі точки зупинки'),
    (English: 'P&ause'; Localized: 'П&ризупинити'),
    (English: '&Terminate'; Localized: 'З&авершити'),
    (English: '&Evaluate Constant...'; Localized: 'З&начення констант...'),
    (English: 'Target &Setup'; Localized: 'Налагодження &Setup'),
    (English: 'Target &Uninstall'; Localized: 'Налагодження &Uninstall'),
    (English: '&Tools'; Localized: '&Інструменти'),
    (English: '&Add/Remove Programs'; Localized: '&Додати/Видалити програми'),
    (English: 'Generate &GUID'; Localized: '&Створити GUID'),
    (English: 'Generate %1 Entries...'; Localized: 'Створити записи %1...'),
    (English: 'Generate %1 Call...'; Localized: 'Створити виклик %1...'),
    (English: '&Configure Sign Tools...'; Localized: 'Налаштування &цифрового підпису...'),
    (English: 'R&TF Editor...'; Localized: '&Редактор RTF...'),
    (English: '&Options...'; Localized: '&Налаштування...'),
    (English: 'Purchase or Renew Commercial &License'; Localized: 'Придбати або поновити комерційну &ліцензію'),
    (English: 'Enter Commercial License &Key...'; Localized: 'Ввести &ключ комерційної ліцензії...'),
    (English: 'Remove Commercial License Key'; Localized: 'Видалити ключ комерційної ліцензії'),
    (English: '&Donate'; Localized: 'Зробити &пожертву'),
    (English: '&Keyboard And Mouse Commands'; Localized: 'Ко&манди клавіатури та миші'),
    (English: 'Regular E&xpressions'; Localized: '&Регулярні вирази'),
    (English: 'Inno &Setup Documentation'; Localized: 'Документ&ація до Inno Setup'),
    (English: 'Inno Setup &Example Scripts'; Localized: 'Приклади сц&енаріїв Inno Setup'),
    (English: 'Inno Setup &FAQ'; Localized: 'Часті запи&тання щодо Inno Setup'),
    (English: 'Inno Setup &Mailing List'; Localized: '&Список розсилки Inno Setup'),
    (English: 'Inno Setup &Revision History'; Localized: 'Історі&я оновлень Inno Setup'),
    (English: 'Inno Setup &Web Site'; Localized: '&Домашня сторінка Inno Setup'),
    (English: 'Inno Setup &Preprocessor Documentation'; Localized: 'Документація до препро&цесора Inno Setup'),
    (English: '&About Inno Setup'; Localized: 'Пр&о Inno Setup'),
    (English: '%1 Call Designer'; Localized: 'Конструктор виклику %1'),
    (English: 'Instruction'; Localized: 'Інструкція:'),
    (English: 'Message'; Localized: 'Повідомлення:'),
    (English: 'Buttons'; Localized: ' Кнопки '),
    (English: ' Type '; Localized: ' Тип '),
    (English: 'Suppressible'; Localized: 'Придушене повідомлення'),
    (English: ' Flags '; Localized: ' Атрибути '),
    (English: 'Default button'; Localized: 'Кнопка за промовчанням'),
    (English: ' Icon '; Localized: ' Піктограма '),
    (English: ' Return values '; Localized: ' Повернення '),
    (English: '&Preview'; Localized: '&Перегляд'),
    (English: 'Options'; Localized: 'Налаштування'),
    (English: ' Miscellaneous '; Localized: ' Різне '),
    (English: 'Show &Welcome dialog at startup'; Localized: 'Відображати вікно пр&ивітання під час запуску'),
    (English: 'Use the Inno Setup &Script Wizard'; Localized: 'Використовувати Майстер с&ценаріїв Inno Setup'),
    (English: 'Automatically sa&ve before compiling'; Localized: '&Автоматичне збереження перед компіляцією'),
    (English: 'Create &backups when saving'; Localized: 'Створювати &резервні копії під час збереження'),
    (English: 'Allow &Undo after save'; Localized: 'Д&озволити скасування після збереження'),
    (English: 'Display &full path in title bar'; Localized: 'Відображати повний шлях у за&головку вікна'),
    (English: '&Pause on exceptions'; Localized: '&Призупиняти налагодження при виникненні винятків'),
    (English: '&Launch Setup/Uninstall as administrator'; Localized: 'Запускати Setup/Uninstall від імені адміні&стратора'),
    (English: 'Colori&ze "Compiler Output" view'; Localized: 'На&дати колір в рядках повідомлень компіляції'),
    (English: 'Automatically open %1 files'; Localized: 'Автоматично відкривати файли %1'),
    (English: 'Automatically show preprocessor output'; Localized: 'Автоматично відображати дані препроцесора'),
    (English: 'Menu &keys:'; Localized: '&Управління:'),
    (English: 'Automatically reload files'; Localized: 'Автоматично оновлювати файли'),
    (English: 'Allow Undo after reload'; Localized: 'Дозволити скасування після оновлення'),
    (English: 'Keep new %1 files closed'; Localized: 'Залишати нові файли %1 закритими'),
    (English: 'Language:'; Localized: 'Мова:'),
    (English: ' Inspector '; Localized: ' Інспектор '),
    (English: ' Editor '; Localized: ' Редактор '),
    (English: 'Invoke autoco&mplete automatically'; Localized: 'Активувати &функцію автозаповнення'),
    (English: 'Use syntax &highlighting'; Localized: 'Використовувати підсвічування си&нтаксису'),
    (English: 'U&nderline syntax errors'; Localized: 'Підкреслювати синтакси&чні помилки'),
    (English: 'Allow cursor to move beyond &end of lines'; Localized: 'Дозволити курсору перемі&щатися за межі рядків'),
    (English: 'Enable section f&olding'; Localized: 'У&вімкнути згортання розділів'),
    (English: 'Use tab cha&racter'; Localized: 'Використовувати символ та&буляції'),
    (English: 'Auto &indent mode'; Localized: 'Ре&жим автоматичного відступу'),
    (English: 'Show indentation &guides'; Localized: 'Відображати напрямні відс&тупів'),
    (English: 'Font:'; Localized: 'Шрифт:'),
    (English: 'AaBbXxZz'; Localized: 'AaBbXxZz'),
    (English: '&Change...'; Localized: '&Змінити...'),
    (English: '&Tab Width:'; Localized: '&Ширина TAB:'),
    (English: 'Show &line numbers in gutter'; Localized: 'Відображати но&мери рядків'),
    (English: 'T&heme:'; Localized: 'Т&ема:'),
    (English: 'Highlight occurrences of current selection'; Localized: 'Підсвічувати входження поточного виділення'),
    (English: 'Highlight occurrences of current wor&d'; Localized: 'Підсвічувати в&ходження поточного слова'),
    (English: 'Ke&ys:'; Localized: '&Клавіши:'),
    (English: 'Show whitespace'; Localized: 'Відображати пробіли'),
    (English: 'Smart Home key'; Localized: 'Розумний режим [Home]'),
    (English: '&Associate .%1 files with this compiler'; Localized: 'Асоціювати файли .%1 з цим компіл&ятором'),
    (English: '&Windows registry file (.%1) to import:'; Localized: '&Вкажіть файл реєстру Windows для імпорту (.%1):'),
    (English: 'B&rowse...'; Localized: '&Огляд...'),
    (English: 'Settings (for all keys and values):'; Localized: 'Параметри (для всіх ключів і значень):'),
    (English: 'Also delete keys which are not empty'; Localized: 'Також видалити ключі, які не є порожніми'),
    (English: 'Delete keys which are empty on uninstall'; Localized: 'Видалити ключі, які є порожніми, під час видалення'),
    (English: 'Delete values on uninstall'; Localized: 'Видалити значення під час видалення'),
    (English: 'Minimum Windows version:'; Localized: 'Створити для версії Windows не нижче:'),
    (English: 'RTF Editor'; Localized: 'Редактор RTF'),
    (English: 'New (%1)'; Localized: 'Новий (%1)'),
    (English: 'Open (%1)'; Localized: 'Відкрити (%1)'),
    (English: 'Cut (%1)'; Localized: 'Вирізати (%1)'),
    (English: 'Copy (%1)'; Localized: 'Копіювати (%1)'),
    (English: 'Paste (%1)'; Localized: 'Вставити (%1)'),
    (English: 'Undo (%1)'; Localized: 'Скасувати (%1)'),
    (English: 'Redo (%1)'; Localized: 'Повторити (%1)'),
    (English: 'Bold (%1)'; Localized: 'Жирний (%1)'),
    (English: 'Italic (%1)'; Localized: 'Курсив (%1)'),
    (English: 'Underline (%1)'; Localized: 'Підкреслений (%1)'),
    (English: '&Bold'; Localized: '&Жирний'),
    (English: '&Italic'; Localized: '&Курсив'),
    (English: '&Underline'; Localized: 'Пі&дкреслений'),
    (English: '&Font...'; Localized: '&Шрифт...'),
    (English: '&Increase Font Size'; Localized: 'Збільшити &розмір шрифту'),
    (English: '&Decrease Font Size'; Localized: 'Зменшити ро&змір шрифту'),
    (English: 'Text &Color...'; Localized: 'Колір &тексту...'),
    (English: '&Background Color...'; Localized: 'Колір &фона...'),
    (English: 'Reset &Colors'; Localized: '&Скинути налаштування кольорів'),
    (English: 'Align &Left'; Localized: 'Вирівняти &ліворуч'),
    (English: '&Center'; Localized: 'Вирівняти по &центру'),
    (English: 'Align &Right'; Localized: 'Вирівняти &праворуч'),
    (English: 'Bulle&ts'; Localized: '&Маркери'),
    (English: 'Increase &Indent'; Localized: 'Збільшити відс&туп'),
    (English: 'Decrease Inden&t'; Localized: 'Зменшити відст&уп'),
    (English: 'Configure Sign Tools'; Localized: 'Налаштування інструментів підписання'),
    (English: ' Sign Tools '; Localized: ' Інструменти для підпису '),
    (English: '&Add...'; Localized: '&Додати...'),
    (English: '&Edit...'; Localized: 'З&мінити...'),
    (English: 'Be notified by e-mail of new Inno Setup releases'; Localized: 'Отримуйте повідомлення електронною поштою про нові версії Inno Setup'),
    (English: 'Subscribe'; Localized: 'Підписка'),
    (English: ' New file '; Localized: ' Новий файл '),
    (English: 'Create a new &empty script file'; Localized: 'Створити новий &порожній файл сценарію'),
    (English: 'Create a new script file using the &Script Wizard'; Localized: 'Створити новий файл сценарію за допомогою &Майстра'),
    (English: ' Open file '; Localized: ' Відкрити файл '),
    (English: 'Open an e&xisting script file'; Localized: 'Відкрити наявний &файл сценарію'),
    (English: '&Don''t show this dialog again'; Localized: '&Більше не показувати цей діалог'),
    (English: 'Script Wizard File'; Localized: 'Майстер сценарію'),
    (English: 'bold'; Localized: 'bold'),
    (English: ' = required'; Localized: ' = обов’язкові поля'),
    (English: ' Destination '; Localized: ' Призначення '),
    (English: 'Destination &base folder:'; Localized: 'Г&оловна тека призначення:'),
    (English: 'Destination &subfolder:'; Localized: 'Цільова вкладена те&ка:'),
    (English: 'Destination &name:'; Localized: '&Цільова назва:'),
    (English: ' Source '; Localized: ' Вхідні дані '),
    (English: '&Source file or folder:'; Localized: 'В&хідний файл або тека:'),
    (English: '&Recurse subfolders'; Localized: '&Додати вкладені теки'),
    (English: '&Include empty subfolders'; Localized: '&Включно з порожніми вкладеними теками'),
    (English: '&Extract archive'; Localized: 'Ро&зпакувати архів'),
    (English: 'Welcome to the %1'; Localized: 'Ласкаво просимо до %1'),
    (English: 'This wizard will guide you through the process of creating a new Inno Setup script file. The results will be used to generate a new script file which can be compiled directly or saved on disk for later use.%n%n'+'Not all features of Inno Setup are covered by this wizard. See the documentation for details on creating Inno Setup script files.%n%nClick Next to continue, or Cancel to exit this wizard.'; Localized: 'Цей майстер допоможе вам створити найпростіший сценарій Inno Setup для вашої програми. ' +
              'Отриманий результат ви можете використати для компіляції проєкту або зберегти на диск для подальшого використання.%n%n' +
              'Майте на увазі, що цей майстер охоплює не всі функції Inno Setup. Зверніться до довідкової документації, щоб дізнатися більше про створення сценаріїв.%n%n' +
              'Натисніть "Далі", щоб продовжити роботу майстра, або "Скасувати", щоб завершити його роботу.'),
    (English: 'Application na&me:'; Localized: 'Н&азва програми:'),
    (English: 'Application &version:'; Localized: '&Версія програми:'),
    (English: 'Application &publisher:'; Localized: 'В&идавець програми:'),
    (English: 'Application &website:'; Localized: 'Веб-&сайт програми:'),
    (English: 'Application folder na&me:'; Localized: 'Н&азва теки для встановлення програми:'),
    (English: 'Application &destination base folder:'; Localized: 'Г&оловний шлях встановлення програми:'),
    (English: 'Other:'; Localized: 'Інші параметри:'),
    (English: 'Allow user to &change the application folder'; Localized: 'Дозволити ко&ристувачеві змінювати теку встановлення'),
    (English: 'The application doe&sn''t need a folder'; Localized: 'Програма н&е потребує створення теки встановлення'),
    (English: 'Other application &files:'; Localized: 'Інші &файли програми:'),
    (English: 'Application &main executable file:'; Localized: '&Головний виконуваний файл програми:'),
    (English: 'Allow &user to start the application after Setup has finished'; Localized: 'Дозволити ко&ристувачеві запускати програму після завершення встановлення'),
    (English: 'The application doe&sn''t have a main executable file'; Localized: 'Програма н&е має головного виконуваного файлу'),
    (English: 'Application file type na&me:'; Localized: 'Назва &типу файлу:'),
    (English: '&Associate a file type to the main executable'; Localized: 'А&соціювати тип файлу з головним виконуваним файлом'),
    (English: 'Application file type &extension:'; Localized: '&Розширення типу файлу:'),
    (English: 'Application &Start Menu folder name:'; Localized: 'Назва теки програми в меню &ПУСК:'),
    (English: 'Other shortcuts to the main executable:'; Localized: 'Додаткові ярлики для головного виконуваного файлу:'),
    (English: 'Allow user to &change the Start Menu folder name'; Localized: 'Дозволити користувачеві з&мінювати назву теки в меню ПУСК'),
    (English: 'Allow user to &disable Start Menu folder creation'; Localized: 'Дозволити користувачеві скасува&ти створення теки в меню ПУСК'),
    (English: 'Allow user to create a deskto&p shortcut'; Localized: 'Дозволити користувачеві створювати ярлик на &Робочому столі'),
    (English: 'Create an &Uninstall shortcut in the Start Menu folder'; Localized: 'Створити ярлик видал&ення в теці меню ПУСК'),
    (English: 'Create an &Internet shortcut in the Start Menu folder'; Localized: 'Створити &ярлик інтернет-посилання в теці меню ПУСК'),
    (English: '&Create a Start Menu shortcut but no folder'; Localized: '&Створити ярлик в меню ПУСК, но без теки'),
    (English: '&License file:'; Localized: 'Файл &ліцензії:'),
    (English: '&Information file shown before installation:'; Localized: 'Файл з ін&формацією, що відображається перед встановленням:'),
    (English: 'Information file shown &after installation:'; Localized: 'Файл з інформацією, що відображається &після встановлення:'),
    (English: 'Install mode:'; Localized: 'Режим встановлення:'),
    (English: '&Administrative install mode (install for all users)'; Localized: 'З правами &администратора (для всіх користувачів)'),
    (English: 'Non a&dministrative install mode (install for current user only)'; Localized: '&Без прав администратора (лише для поточного користувача)'),
    (English: 'Allow user to &override the install mode via the command line'; Localized: 'Дозволити пе&ревизначення режиму встановлення у командному рядку'),
    (English: 'Ask the user to &choose the install mode at startup'; Localized: 'Пропонувати користувачеві &вибір режиму встановлення під час запуску'),
    (English: '&Languages:'; Localized: 'Мов&и встановлення:'),
    (English: '&Deselect All'; Localized: '&Скасувати все'),
    (English: 'Custom compiler output fol&der:'; Localized: 'Тек&а для збереження готового файлу інсталяції:'),
    (English: 'Compiler output base &file name:'; Localized: 'Назва &файлу інсталяції:'),
    (English: 'Custom Setup &icon file:'; Localized: 'І&конка файлу інсталяції:'),
    (English: 'Setup &password:'; Localized: '&Пароль для встановлення:'),
    (English: 'Use the password to &encrypt the application files'; Localized: 'Використовувати пароль для &шифрування файлів програми'),
    (English: '&Wizard style:'; Localized: '&Стиль майстра:'),
    (English: 'You have successfully completed the %1.%n%nTo close this wizard and generate the new script file, click Finish.'; Localized: 'Ви успішно завершили %1.%n%nЩоб завершити роботу майстра і створити новий сценарій, натисніть "Готово".'),
    (English: '&Back'; Localized: '&Назад'),
    (English: '''%s'' is not a valid integer value'; Localized: '''%s'' не є дійсним цілим значенням'),
    (English: '''%s'' is not a valid integer value for %s type'; Localized: '''%s'' не є дійсним цілим значенням для типу %s'),
    (English: '''%s'' is not a valid floating point value'; Localized: '''%s'' не є дійсним значенням з плаваючою комою'),
    (English: '''%d.%d'' is not a valid timestamp'; Localized: '''%d.%d'' не є дійсною міткою часу'),
    (English: '''%s'' is not a valid GUID value'; Localized: '''%s'' не є дійсним значенням GUID'),
    (English: 'Invalid argument to time encode'; Localized: 'Недійсний аргумент для кодування часу'),
    (English: 'Invalid argument to date encode'; Localized: 'Недійсний аргумент для кодування дати'),
    (English: 'Out of memory'; Localized: 'Не вистачає пам’яті'),
    (English: 'I/O error %d'; Localized: 'Помилка вводу/виводу %d'),
    (English: 'File not found'; Localized: 'Файл не знайдено'),
    (English: 'Invalid filename'; Localized: 'Недійсна назва файлу'),
    (English: 'Too many open files'; Localized: 'Забагато відкритих файлів'),
    (English: 'File access denied'; Localized: 'Доступ до файлу заборонено'),
    (English: 'Read beyond end of file'; Localized: 'Читання за межами кінця файлу'),
    (English: 'Disk full'; Localized: 'Диск переповнений'),
    (English: 'Invalid numeric input'; Localized: 'Недопустиме числове значення'),
    (English: 'Division by zero'; Localized: 'Ділення на нуль'),
    (English: 'Range check error'; Localized: 'Помилка перевірки діапазону'),
    (English: 'Integer overflow'; Localized: 'Переповнення цілого числа'),
    (English: 'Invalid floating point operation'; Localized: 'Неправильна операція з плаваючою комою'),
    (English: 'Floating point division by zero'; Localized: 'Ділення з плаваючою комою на нуль'),
    (English: 'Floating point overflow'; Localized: 'Переповнення з плаваючою комою'),
    (English: 'Floating point underflow'; Localized: 'Недоповнення з плаваючою комою'),
    (English: 'Invalid pointer operation'; Localized: 'Недійсна операція покажчика'),
    (English: 'Invalid class typecast'; Localized: 'Недійсний тип класу'),
    (English: 'Access violation at address %p. %s of address %p'; Localized: 'Порушення доступу за адресою %p. %s адреси %p'),
    (English: 'Access violation'; Localized: 'Порушення доступу'),
    (English: 'Stack overflow'; Localized: 'Переповнення стека'),
    (English: 'Control-C hit'; Localized: 'Натиснута комбінація Control-C'),
    (English: 'Privileged instruction'; Localized: 'Привілейована інструкція'),
    (English: 'Operation aborted'; Localized: 'Операція перервана'),
    (English: 'Exception %s in module %s at %p.'#13#10'%s%s'#13#10; Localized: 'Виняток %s у модулі %s за адресою %p.'#13#10'%s%s'#13#10),
    (English: 'Application Error'; Localized: 'Помилка програми'),
    (English: 'Format ''%s'' invalid or incompatible with argument'; Localized: 'Формат ''%s'' недійсний або несумісний з аргументом'),
    (English: 'No argument for format ''%s'''; Localized: 'Немає аргументів для формату ''%s'''),
    (English: 'Variant method calls not supported'; Localized: 'Виклики методів Variant не підтримуються'),
    (English: 'Read'; Localized: 'Читання'),
    (English: 'Write'; Localized: 'Запис'),
    (English: 'Execution'; Localized: 'Виконання'),
    (English: 'Invalid access'; Localized: 'Недійсний доступ'),
    (English: 'Error creating variant or safe array'; Localized: 'Помилка створення Variant або SafeArray'),
    (English: 'Variant or safe array index out of bounds'; Localized: 'Індекс Variant або SafeArray поза межами'),
    (English: 'Variant or safe array is locked'; Localized: 'Variant або SafeArray заблоковано'),
    (English: 'Invalid variant type conversion'; Localized: 'Недійсне перетворення типу Variant'),
    (English: 'Invalid variant operation'; Localized: 'Недійсна операція з Variant'),
    (English: 'Invalid NULL variant operation'; Localized: 'Недійсна операція з NULL Variant'),
    (English: 'Invalid variant operation (%s%.8x)'#10'%s'; Localized: 'Недійсна операція з Variant (%s%.8x)'#10'%s'),
    (English: 'Could not convert variant of type (%s) into type (%s)'; Localized: 'Не вдалося перетворити Variant типу (%s) на тип (%s)'),
    (English: 'Overflow while converting variant of type (%s) into type (%s)'; Localized: 'Переповнення під час перетворення Variant типу (%s) на тип (%s)'),
    (English: 'Variant overflow'; Localized: 'Переповнення Variant'),
    (English: 'Invalid argument'; Localized: 'Недійсний аргумент'),
    (English: 'Invalid variant type'; Localized: 'Недійсний тип Variant'),
    (English: 'Operation not supported'; Localized: 'Операція не підтримується'),
    (English: 'Unexpected variant error'; Localized: 'Неочікувана помилка Variant'),
    (English: 'External exception %x'; Localized: 'Зовнішній виняток %x'),
    (English: 'Assertion failed'; Localized: 'Виконання твердження не вдалося'),
    (English: 'Interface not supported'; Localized: 'Інтерфейс не підтримується'),
    (English: 'Exception in safecall method'; Localized: 'Виняток у методі safecall'),
    (English: 'Object lock not owned'; Localized: 'Об’єкт блокування не належить користувачеві'),
    (English: 'Monitor support function not initialized'; Localized: 'Функція підтримки монітора не ініціалізована'),
    (English: 'Feature not implemented'; Localized: 'Функція не реалізована'),
    (English: 'Method called on disposed object'; Localized: 'Виклик методу для об’єкта, що був видалений'),
    (English: '%s (%s, line %d)'; Localized: '%s (%s, рядок %d)'),
    (English: 'Abstract Error'; Localized: 'Абстрактна помилка'),
    (English: 'Access violation at address %p in module ''%s'' (offset %x). %s of address %p'; Localized: 'Порушення доступу за адресою %p у модулі ''%s'' зсув %x). %s адреси %p'),
    (English: 'System Error.  Code: %d.'#13#10'%s%s'; Localized: 'Системна помилка. Код: %d.'#13#10'%s%s'),
    (English: 'A call to an OS function failed'; Localized: 'Виклик функції ОС не вдався'),
    (English: 'Jan'; Localized: 'Січ'),
    (English: 'Feb'; Localized: 'Лют'),
    (English: 'Mar'; Localized: 'Бер'),
    (English: 'Apr'; Localized: 'Кві'),
    (English: 'May'; Localized: 'Травень'),
    (English: 'Jun'; Localized: 'Чер'),
    (English: 'Jul'; Localized: 'Лип'),
    (English: 'Aug'; Localized: 'Сер'),
    (English: 'Sep'; Localized: 'Вер'),
    (English: 'Oct'; Localized: 'Жов'),
    (English: 'Nov'; Localized: 'Лис'),
    (English: 'Dec'; Localized: 'Гру'),
    (English: 'January'; Localized: 'Січень'),
    (English: 'February'; Localized: 'Лютий'),
    (English: 'March'; Localized: 'Березень'),
    (English: 'April'; Localized: 'Квітень'),
    (English: 'June'; Localized: 'Червень'),
    (English: 'July'; Localized: 'Липень'),
    (English: 'August'; Localized: 'Серпень'),
    (English: 'September'; Localized: 'Вересень'),
    (English: 'October'; Localized: 'Жовтень'),
    (English: 'November'; Localized: 'Листопад'),
    (English: 'December'; Localized: 'Грудень'),
    (English: 'Sun'; Localized: 'Нд'),
    (English: 'Mon'; Localized: 'Пн'),
    (English: 'Tue'; Localized: 'Вт'),
    (English: 'Wed'; Localized: 'Ср'),
    (English: 'Thu'; Localized: 'Чт'),
    (English: 'Fri'; Localized: 'Пт'),
    (English: 'Sat'; Localized: 'Сб'),
    (English: 'Sunday'; Localized: 'Неділя'),
    (English: 'Monday'; Localized: 'Понеділок'),
    (English: 'Tuesday'; Localized: 'Вівторок'),
    (English: 'Wednesday'; Localized: 'Середа'),
    (English: 'Thursday'; Localized: 'Четвер'),
    (English: 'Friday'; Localized: 'П’ятниця'),
    (English: 'Saturday'; Localized: 'Субота'),
    (English: 'Invalid source array'; Localized: 'Недійсний масив даних'),
    (English: 'Invalid destination array'; Localized: 'Недійсний масив призначення'),
    (English: 'Character index out of bounds (%d)'; Localized: 'Індекс символу поза межами діапазону (%d)'),
    (English: 'Start index out of bounds (%d)'; Localized: 'Початковий індекс поза межами (%d)'),
    (English: 'Invalid count (%d)'; Localized: 'Недійсна кількість (%d)'),
    (English: 'Invalid destination index (%d)'; Localized: 'Недійсний індекс призначення (%d)'),
    (English: 'Invalid code page'; Localized: 'Недійсна кодова сторінка'),
    (English: 'No mapping for the Unicode character exists in the target multi-byte code page'; Localized: 'У цільовій багатобайтовій кодовій сторінці відсутнє відповідне відображення для цього символу Unicode'),
    (English: 'Invalid StringBaseIndex'; Localized: 'Недійсний StringBaseIndex'),
    (English: '''%s'' is not a valid %s color value'; Localized: '''%s'' не є допустимим значенням кольору %s'),
    (English: 'Ancestor for ''%s'' not found'; Localized: 'Не знайдено предка для ''%s'''),
    (English: 'Cannot assign a %s to a %s'; Localized: 'Неможливо присвоїти %s до %s'),
    (English: 'Bits index out of range'; Localized: 'Індекс бітів поза межами діапазону'),
    (English: 'Can''t write to a read-only resource stream'; Localized: 'Неможливо записати дані в потік ресурсу, доступний лише для читання'),
    (English: '''''%s'''' expected'; Localized: 'Очікувалося ''''%s'''''),
    (English: 'CheckSynchronize called from thread $%x, which is NOT the main thread'; Localized: 'CheckSynchronize викликано з потоку $%x, який НЕ є головним потоком'),
    (English: 'Class %s not found'; Localized: 'Клас %s не знайдено'),
    (English: 'A class named %s already exists'; Localized: 'Клас з назвою %s уже існує'),
    (English: 'List does not allow duplicates ($0%x)'; Localized: 'Список не допускає дублікатів ($0%x)'),
    (English: 'A component named %s already exists'; Localized: 'Компонент з назвою %s уже існує'),
    (English: 'String list does not allow duplicates'; Localized: 'Список рядків не допускає дублікатів'),
    (English: 'Cannot create file "%s". %s'; Localized: 'Неможливо створити файл "%s". %s'),
    (English: 'Cannot open file "%s". %s'; Localized: 'Неможливо відкрити файл "%s". %s'),
    (English: 'Identifier expected'; Localized: 'Очікується ідентифікатор'),
    (English: 'Invalid binary value'; Localized: 'Недійсне бінарне значення'),
    (English: 'Invalid stream format'; Localized: 'Недійсний формат потоку'),
    (English: '''%s'' is an invalid mask at (%d)'; Localized: '''%s'' – недійсна маска в позиції (%d)'),
    (English: '''''%s'''' is not a valid component name'; Localized: '''''%s'''' – недійсна назва компонента'),
    (English: 'Invalid property value'; Localized: 'Недійсне значення властивості'),
    (English: 'Invalid property path'; Localized: 'Недійсний шлях до властивості'),
    (English: 'Invalid data type for ''%s'''; Localized: 'Недійсний тип даних для ''%s'''),
    (English: 'Invalid string constant'; Localized: 'Недійсна рядкова константа'),
    (English: 'Line too long'; Localized: 'Рядок занадто довгий'),
    (English: 'List capacity out of bounds (%d)'; Localized: 'Місткість списку поза межами дозволеного (%d)'),
    (English: 'List count out of bounds (%d)'; Localized: 'Кількість елементів у списку виходить за межі діапазону (%d)'),
    (English: 'List index out of bounds (%d)'; Localized: 'Індекс списку поза межами діапазону (%d)'),
    (English: '.  %s range is 0..%d'; Localized: '. Діапазон %s: 0..%d'),
    (English: '.  %s is empty'; Localized: '.  %s порожній'),
    (English: 'Out of memory while expanding memory stream'; Localized: 'Не вистачає пам’яті під час розширення потоку пам’яті'),
    (English: '%s has not been registered as a COM class'; Localized: '%s не зареєстровано як клас COM'),
    (English: 'Printer is not currently printing'; Localized: 'Принтер наразі не друкує'),
    (English: 'Number expected'; Localized: 'Очікується число'),
    (English: 'ANSI or UTF8 encoding expected'; Localized: 'Очікується кодіровка ANSI або UTF-8'),
    (English: '%s on line %d'; Localized: '%s у рядку %d'),
    (English: 'Error reading %s%s%s: %s'; Localized: 'Помилка під час зчитування %s%s%s: %s'),
    (English: 'Printing in progress'; Localized: 'Триває друк'),
    (English: 'Stream read error'; Localized: 'Помилка читання потоку'),
    (English: 'Property is read-only'; Localized: 'Атрибут доступний лише для читання'),
    (English: 'Failed to create key %s'; Localized: 'Не вдалося створити ключ %s'),
    (English: 'Failed to get data for ''%s'''; Localized: 'Не вдалося отримати дані для ''%s'''),
    (English: 'Failed to set data for ''%s'''; Localized: 'Не вдалося встановити дані для ''%s'''),
    (English: 'Resource %s not found'; Localized: 'Ресурс %s не знайдено'),
    (English: '%s.Seek not implemented'; Localized: '%s.Seek не реалізована'),
    (English: 'Operation not allowed on sorted list'; Localized: 'Операція не дозволена для відсортованого списку'),
    (English: 'String expected'; Localized: 'Очікується рядок'),
    (English: '%s expected'; Localized: 'Очікується %s'),
    (English: '%s not in a class registration group'; Localized: '%s не входить до групи реєстрації класу'),
    (English: 'Property %s does not exist'; Localized: 'Атрибут %s не існує'),
    (English: 'Stream write error'; Localized: 'Помилка запису потоку'),
    (English: 'Thread creation error: %s'; Localized: 'Помилка створення потока: %s'),
    (English: 'Thread Error: %s (%d)'; Localized: 'Помилка потока: %s (%d)'),
    (English: 'Cannot terminate an externally created thread'; Localized: 'Неможливо завершити потік, створений зовні'),
    (English: 'Cannot wait for an externally created thread'; Localized: 'Неможливо дочекатися завершення потоку, створеного зовні'),
    (English: 'Cannot call Start on a running or suspended thread'; Localized: 'Неможливо викликати Start для запущеного або призупиненого потоку'),
    (English: 'Parameter %s cannot be nil'; Localized: 'Параметр %s не може бути nil'),
    (English: 'Parameter %s cannot be a negative value'; Localized: 'Параметр %s не може бути від’ємним значенням'),
    (English: 'Invalid characters in path'; Localized: 'Недійсні символи в шляху'),
    (English: 'Invalid characters in search pattern'; Localized: 'Недійсні символи в шаблоні пошуку'),
    (English: 'Path is empty'; Localized: 'Шлях порожній'),
    (English: 'Search pattern is empty'; Localized: 'Шаблон пошуку порожній'),
    (English: 'The specified path is too long'; Localized: 'Вказаний шлях занадто довгий'),
    (English: 'The specified path was not found'; Localized: 'Вказаний шлях не знайдено'),
    (English: 'The path format is not supported'; Localized: 'Формат шляху не підтримується'),
    (English: 'No help viewer that supports filters'; Localized: 'Немає переглядача довідки з підтримкою фільтрів'),
    (English: 'String index out of range (%d).  Must be >= %d and <= %d'; Localized: 'Індекс рядка поза діапазоном (%d). Має бути >= %d та <= %d'),
    (English: 'Invalid UTF32 character value.  Must be >= 0 and <= $10FFFF, excluding surrogate pair ranges'; Localized: 'Неприпустиме значення символу UTF32. Має бути >= 0 та <= $10FFFF, за винятком діапазонів сурогатних пар'),
    (English: 'High surrogate char without a following low surrogate char at index: %d. Check that the string is encoded properly'; Localized: 'Старший сурогатний символ без наступного молодшого сурогатного символу за індексом: %d. Перевірте, чи рядок закодовано правильно.'),
    (English: 'Low surrogate char without a preceding high surrogate char at index: %d. Check that the string is encoded properly'; Localized: 'Молодший сурогатний символ без наступного молодшого сурогатного символу за індексом: %d. Перевірте, чи рядок закодовано правильно.'),
    (English: 'Source and Destination arrays must not be the same'; Localized: 'Масиви джерела та призначення не повинні бути однаковими'),
    (English: 'SpinCount out of range. Must be between 0 and %d'; Localized: 'SpinCount поза діапазоном. Має бути між 0 та %d'),
    (English: 'No context-sensitive help installed'; Localized: 'Контекстна довідка не встановлена'),
    (English: 'No help found for context %d'; Localized: 'Довідки для контексту %d не знайдено'),
    (English: 'Unable to open Index'; Localized: 'Не вдається відкрити індекс'),
    (English: 'Unable to open Search'; Localized: 'Не вдається відкрити пошук'),
    (English: 'Unable to find a Table of Contents'; Localized: 'Не вдається знайти зміст'),
    (English: 'No topic-based help system installed'; Localized: 'Тематична довідкова система не встановлена'),
    (English: 'No help found for %s'; Localized: 'Довідки для %s не знайдено'),
    (English: 'Argument out of range'; Localized: 'Аргумент поза межами діапазону'),
    (English: 'Argument must not be nil'; Localized: 'Аргумент не може бути nil'),
    (English: 'Item not found'; Localized: 'Элемент не знайдено'),
    (English: 'Duplicates not allowed'; Localized: 'Дублікати заборонені'),
    (English: 'Insufficient RTTI available to support this operation'; Localized: 'Недостатньо RTTI для підтримки цієї операції'),
    (English: 'Parameter count mismatch'; Localized: 'Невідповідність кількості параметрів'),
    (English: 'Parameter count exceeded'; Localized: 'Перевищено кількість параметрів'),
    (English: 'Type ''%s'' is not declared in the interface section of a unit'; Localized: 'Тип ''%s'' не оголошено в розділі інтерфейсу модуля'),
    (English: 'VAR and OUT arguments must match parameter type exactly'; Localized: 'Аргументи VAR та OUT повинні точно відповідати типу параметра'),
    (English: 'Property ''%s'' is read-only'; Localized: 'Властивість ''%s'' доступна лише для читання'),
    (English: 'Property ''%s'' is write-only'; Localized: 'Властивість ''%s'' доступна лише для запису'),
    (English: 'RTTI objects cannot be manually destroyed by application code'; Localized: 'Об’єкти RTTI не можуть бути знищені вручну кодом програми'),
    (English: '%s (Version %d.%d, Build %d, %5:s)'; Localized: '%s (версія %d.%d, сбірка %d, %5:s)'),
    (English: '%s Service Pack %4:d (Version %1:d.%2:d, Build %3:d, %5:s)'; Localized: '%s Service Pack %4:d (версія %1:d.%2:d, сбірка %3:d, %5:s)'),
    (English: '32-bit Edition'; Localized: '32-bit Edition'),
    (English: '64-bit Edition'; Localized: '64-bit Edition'),
    (English: 'Windows'; Localized: 'Windows'),
    (English: 'Windows Vista'; Localized: 'Windows Vista'),
    (English: 'Windows Server 2008'; Localized: 'Windows Server 2008'),
    (English: 'Windows 7'; Localized: 'Windows 7'),
    (English: 'Windows Server 2008 R2'; Localized: 'Windows Server 2008 R2'),
    (English: 'Windows 2000'; Localized: 'Windows 2000'),
    (English: 'Windows XP'; Localized: 'Windows XP'),
    (English: 'Windows Server 2003'; Localized: 'Windows Server 2003'),
    (English: 'Windows Server 2003 R2'; Localized: 'Windows Server 2003 R2'),
    (English: 'Windows Server 2012'; Localized: 'Windows Server 2012'),
    (English: 'Windows Server 2012 R2'; Localized: 'Windows Server 2012 R2'),
    (English: 'Windows Server 2016'; Localized: 'Windows Server 2016'),
    (English: 'Windows Server 2019'; Localized: 'Windows Server 2019'),
    (English: 'Windows Server 2022'; Localized: 'Windows Server 2022'),
    (English: 'Windows 8'; Localized: 'Windows 8'),
    (English: 'Windows 8.1'; Localized: 'Windows 8.1'),
    (English: 'Windows 10'; Localized: 'Windows 10'),
    (English: 'Windows 11'; Localized: 'Windows 11'),
    (English: 'Cannot create instance of class %s'; Localized: 'Неможливо створити екземпляр класу %s'),
    (English: 'Observer is not supported'; Localized: 'Спостерігач не підтримується'),
    (English: 'Cannot have multiple single cast observers added to the observers collection'; Localized: 'Не можна додати кілька спостерігачів з одним приведенням до колекції спостерігачів'),
    (English: 'The object does not implement the observer interface'; Localized: 'Об’єкт не реалізує інтерфейс спостерігача'),
    (English: 'No single cast observer with ID %d was added to the observer collection'; Localized: 'До колекції спостерігачів не було додано жодного спостерігача з ID %d'),
    (English: 'No multi cast observer with ID %d was added to the observer collection'; Localized: 'До колекції спостерігачів не було додано жодного спостерігача багатоадресної розсилки з ID %d'),
    (English: 'Observer is not available'; Localized: 'Спостерігач недоступний'),
    (English: 'SHA2: Cannot update a finalized hash'; Localized: 'SHA2: неможливо оновити фіналізований хеш'),
    (English: 'Must wait on at least one event'; Localized: 'Необхідно дочекатися принаймні однієї події'),
    (English: 'Cannot call BeginInvoke on a TComponent in the process of destruction'; Localized: 'Неможливо викликати BeginInvoke для TComponent у процесі знищення'),
    (English: 'OLE error %.8x'; Localized: 'Помилка OLE %.8x'),
    (English: 'Method ''%s'' not supported by automation object'; Localized: 'Метод ''%s'' не підтримується об’єктом автоматизації'),
    (English: 'Variant does not reference an automation object'; Localized: 'Variant не посилається на об’єкт автоматизації'),
    (English: 'Dispatch methods do not support more than 64 parameters'; Localized: 'Dispatch-методи не підтримують більше 64 параметрів'),
    (English: 'A regular expression specified in RegEx is required'; Localized: 'Необхідно вказати регулярний вираз, зазначений у RegEx'),
    (English: 'Error in regular expression at offset %d: %s'; Localized: 'Помилка в регулярному виразі зі зміщенням %d: %s'),
    (English: 'Successful match required'; Localized: 'Потрібне успішне збігання'),
    (English: 'Index out of bounds (%d)'; Localized: 'Індекс поза межами (%d)'),
    (English: 'Bitmap image is not valid'; Localized: 'Растрове зображення недійсне'),
    (English: 'Icon image is not valid'; Localized: 'Зображення значка недійсне'),
    (English: 'Metafile is not valid'; Localized: 'Метафайл недійсний'),
    (English: 'Invalid pixel format'; Localized: 'Недійсний формат пікселя'),
    (English: 'Invalid image'; Localized: 'Недійсне зображення'),
    (English: 'Scan line index out of range'; Localized: 'Індекс рядка сканування поза діапазоном'),
    (English: 'Cannot change the size of an icon'; Localized: 'Неможливо змінити розмір значка'),
    (English: 'Cannot change the size of a WIC Image'; Localized: 'Неможливо змінити розмір WIC Image'),
    (English: 'Unsupported clipboard format'; Localized: 'Непідтримуваний формат буфера обміну'),
    (English: 'Unsupported stream format'; Localized: 'Непідтримуваний формат потоку'),
    (English: 'Out of system resources'; Localized: 'Недостатньо системних ресурсів'),
    (English: 'Canvas does not allow drawing'; Localized: 'Полотно не дозволяє малювати'),
    (English: 'Text format flag ''%s'' not supported'; Localized: 'Флаг формату тексту ''%s'' не підтримується'),
    (English: 'Invalid image frame index %d: there are %d frames (0-%d)'; Localized: 'Недійсний індекс кадру зображення %d: усього %d кадрів (0-%d)'),
    (English: 'Invalid image size'; Localized: 'Недійсний розмір зображення'),
    (English: 'Invalid ImageList'; Localized: 'Недійсний ImageList'),
    (English: 'Invalid ImageList Index'; Localized: 'Недійсний індекс ImageList'),
    (English: 'Failed to read ImageList data from stream'; Localized: 'Не вдалося прочитати дані ImageList з потоку'),
    (English: 'Failed to write ImageList data to stream'; Localized: 'Не вдалося записати дані ImageList у потік'),
    (English: 'Error creating window device context'; Localized: 'Помилка створення контексту пристрою вікна'),
    (English: 'Error creating window class'; Localized: 'Помилка створення класу вікна'),
    (English: 'Cannot focus a disabled or invisible window'; Localized: 'Не вдається сфокусувати вимкнене або невидиме вікно'),
    (English: 'Control ''%s'' has no parent window'; Localized: 'Елемент керування ''%s'' не має батьківського вікна'),
    (English: '. Path:'#13#10'%s'; Localized: '. Шлях:'#13#10'%s'),
    (English: 'Parent given is not a parent of ''%s'''; Localized: 'Вказаний батьківський елемент не є батьківським для ''%s'''),
    (English: 'Cannot hide an MDI Child Form'; Localized: 'Неможливо приховати дочірню форму MDI'),
    (English: 'Cannot change Visible in OnShow or OnHide'; Localized: 'Неможливо змінити значення Visible у методах OnShow або OnHide'),
    (English: 'Cannot make a visible window modal'; Localized: 'Неможливо зробити видимим модальне вікно'),
    (English: 'Scrollbar property out of range'; Localized: 'Властивість смужки прокрутки поза межами діапазону'),
    (English: '%s property out of range'; Localized: 'Властивість %s поза межами діапазону'),
    (English: 'Check state can only be set when CheckBoxes is True'; Localized: 'Стан перевірки можна встановити лише тоді, коли CheckBoxs = True'),
    (English: 'Check state incompatible with treeview''s CheckStyles'; Localized: 'Перевірка стану несумісна зі стилями CheckStyles дерева'),
    (English: 'Menu index out of range'; Localized: 'Індекс меню поза межами діапазону'),
    (English: 'Menu inserted twice'; Localized: 'Меню вставлено двічі'),
    (English: 'Sub-menu is not in menu'; Localized: 'Підменю не в меню'),
    (English: 'Not enough timers available'; Localized: 'Недостатньо доступних таймерів'),
    (English: 'Printer index out of range'; Localized: 'Індекс принтера поза діапазоном'),
    (English: 'Printer selected is not valid'; Localized: 'Вибраний принтер недійсний'),
    (English: '%s on %s'; Localized: '%s на %s'),
    (English: 'GroupIndex cannot be less than a previous menu item''s GroupIndex'; Localized: 'GroupIndex не може бути меншим за GroupIndex попереднього елемента меню'),
    (English: 'Cannot create form. No MDI forms are currently active'; Localized: 'Не вдається створити форму. Наразі немає активних MDI-форм'),
    (English: 'Can only modify an image if it contains a bitmap'; Localized: 'Зображення можна змінювати, лише якщо воно містить растрове зображення'),
    (English: 'A control cannot have itself as its parent'; Localized: 'Елемент керування не може бути батьківським елементом'),
    (English: 'Control ''%s'' is used on a not main thread'; Localized: 'Елемент керування ''%s'' використовується не в основному потоці'),
    (English: '&Yes'; Localized: 'Т&ак'),
    (English: '&No'; Localized: '&Ні'),
    (English: '&Close'; Localized: '&Закрити'),
    (English: '&Ignore'; Localized: 'П&ропустити'),
    (English: '&Retry'; Localized: '&Повторити'),
    (English: '&All'; Localized: 'В&се'),
    (English: 'Cannot drag a form'; Localized: 'Не вдається перетягнути форму'),
    (English: 'Metafiles'; Localized: 'Метафайли'),
    (English: 'Enhanced Metafiles'; Localized: 'Розширені метафайли'),
    (English: 'Icons'; Localized: 'Іконки'),
    (English: 'Bitmaps'; Localized: 'Растрові зображення'),
    (English: 'TIFF Images'; Localized: 'Зображення TIFF'),
    (English: 'Warning'; Localized: 'Попередження'),
    (English: 'Error'; Localized: 'Помилка'),
    (English: 'Information'; Localized: 'Інформація'),
    (English: 'Confirm'; Localized: 'Підтвердження'),
    (English: '&Abort'; Localized: 'П&ерервати'),
    (English: 'N&o to All'; Localized: 'Ні для всі&х'),
    (English: 'Yes to &All'; Localized: 'Так &для всіх'),
    (English: 'BkSp'; Localized: 'BkSp'),
    (English: 'Tab'; Localized: 'Tab'),
    (English: 'Esc'; Localized: 'Esc'),
    (English: 'Enter'; Localized: 'Enter'),
    (English: 'Space'; Localized: 'Space'),
    (English: 'PgUp'; Localized: 'PgUp'),
    (English: 'PgDn'; Localized: 'PgDn'),
    (English: 'End'; Localized: 'End'),
    (English: 'Home'; Localized: 'Home'),
    (English: 'Left'; Localized: 'Left'),
    (English: 'Up'; Localized: 'Up'),
    (English: 'Right'; Localized: 'Right'),
    (English: 'Down'; Localized: 'Down'),
    (English: 'Ins'; Localized: 'Ins'),
    (English: 'Del'; Localized: 'Del'),
    (English: 'Value must be between %d and %d'; Localized: 'Значення має бути між %d та %d'),
    (English: 'Unable to insert a line'; Localized: 'Не вдається вставити рядок'),
    (English: 'Invalid clipboard format'; Localized: 'Недійсний формат буфера обміну'),
    (English: 'Clipboard does not support Icons'; Localized: 'Буфер обміну не підтримує значки'),
    (English: 'Cannot open clipboard: %s'; Localized: 'Не вдається відкрити буфер обміну: %s'),
    (English: 'Text exceeds memo capacity'; Localized: 'Текст перевищує місткість нотатки'),
    (English: 'Operation not supported on selected printer'; Localized: 'Операція не підтримується на вибраному принтері'),
    (English: 'There is no default printer currently selected'; Localized: 'Наразі не обрано принтер за замовчуванням'),
    (English: 'Menu ''%s'' is already being used by another form'; Localized: 'Меню ''%s'' вже використовується іншою формою'),
    (English: 'Other'; Localized: 'Інше'),
    (English: 'Docked control must have a name'; Localized: 'Прив’язаний елемент керування повинен мати назву'),
    (English: 'Error removing control from dock tree'; Localized: 'Помилка видалення керування з дерева закріплень'),
    (English: ' - Dock zone not found'; Localized: ' - Зона закріплення не знайдена'),
    (English: ' - Dock zone has no control'; Localized: ' - Зона закріплення не містить елемента управління'),
    (English: 'Error loading dock zone from the stream. Expecting version %d, but found %d.'; Localized: 'Помилка завантаження зони закріплення з потока. Очікується версія %d, але знайдено %d.'),
    (English: 'Multiselect mode must be on for this feature'; Localized: 'Для цієї функції має бути ввімкнено режим множинного вибору'),
    (English: 'Length of value array must be >= length of prompt array'; Localized: 'Довжина масиву значень має бути >= довжина масиву запитів'),
    (English: 'Prompt array must not be empty'; Localized: 'Масив запитів не може бути порожнім'),
    (English: '&Username'; Localized: 'К&ористувач'),
    (English: '&Password'; Localized: '&Пароль'),
    (English: '&Domain'; Localized: '&Домен'),
    (English: 'Login'; Localized: 'Логін'),
    (English: 'Expand'; Localized: 'Розгорнути'),
    (English: 'Separator'; Localized: 'Розділювач'),
    (English: 'Error setting %s.Count'; Localized: 'Помилка встановлення %s.Count'),
    (English: 'Listbox (%s) style must be virtual in order to set Count'; Localized: 'Стиль Listbox (%s) повинен бути virtual для встановлення Count'),
    (English: 'No OnGetItem event handler assigned'; Localized: 'Не призначено обробника події OnGetItem'),
    (English: 'ANSI'; Localized: 'ANSI'),
    (English: 'ASCII'; Localized: 'ASCII'),
    (English: 'Unicode'; Localized: 'Unicode'),
    (English: 'Big Endian Unicode'; Localized: 'Big Endian Unicode'),
    (English: 'UTF-8'; Localized: 'UTF-8'),
    (English: 'UTF-7'; Localized: 'UTF-7'),
    (English: 'Cannot remove shell notification icon'; Localized: 'Не вдається видалити позначку повідомлення'),
    (English: '%s requires Windows Vista or later'; Localized: '%s вимагає Windows Vista або пізніша версія'),
    (English: 'Button%d'; Localized: 'Button%d'),
    (English: 'RadioButton%d'; Localized: 'RadioButton%d'),
    (English: 'Caption cannot be empty'; Localized: 'Заголовок не може бути порожнім'),
    (English: 'Invalid canvas operation'; Localized: 'Неправильна операція з полотном'),
    (English: '%s has no owner'; Localized: '%s не має власника'),
    (English: 'Source and destination require the same owner'; Localized: 'Походження та призначення повинні належати одному й тому ж власнику'),
    (English: '%s cannot be owned by a different canvas'; Localized: '%s не може належати іншому полотну'),
    (English: 'Not a solid color brush'; Localized: 'Щітка не однотонного кольору'),
    (English: 'Invalid brush style'; Localized: 'Недійсний стиль пензля'),
    (English: 'Unable to load style ''%s'''; Localized: 'Не вдалося завантажити стиль ''%s'''),
    (English: 'Unable to load styles: %s'; Localized: 'Не вдалося завантажити стилі: %s'),
    (English: 'Style ''%s'' already registered'; Localized: 'Стиль ''%s'' вже зареєстрований'),
    (English: 'Style class ''%s'' already registered'; Localized: 'Класс стиля ''%s'' вже зареєстрований'),
    (English: 'Style ''%s'' not found'; Localized: 'Стиль ''%s'' не знайдено'),
    (English: 'Style class ''%s'' not found'; Localized: 'Клас стиля ''%s'' не знайдено'),
    (English: 'Invalid style format'; Localized: 'Недійсний формат стилю'),
    (English: 'VCL Style File'; Localized: 'Файл VCL Style'),
    (English: 'Class ''%s'' is already registered for ''%s'''; Localized: 'Клас ''%s'' для ''%s'' вже зареєстрований'),
    (English: 'Class ''%s'' is not registered for ''%s'''; Localized: 'Клас ''%s'' для ''%s''не зареєстрований'),
    (English: '%s parameter cannot be nil'; Localized: 'Параметр %s не може бути nil'),
    (English: 'A StyleHook class has not been registered for %s'; Localized: 'Для %s не зареєстровано клас StyleHook'),
    (English: 'Feature not supported by this style'; Localized: 'Ця функція не підтримується в цьому стилі'),
    (English: 'Cannot call BeginInvoke on a control with no parent or window handle'; Localized: 'Неможливо викликати BeginInvoke для елемента управління, який не має власника або дескриптора вікна'),
    (English: 'CardPanel card index is out of range'; Localized: 'Значення індексу картки CardPanel виходить за межі діапазону'),
    (English: 'CardPanel.ActiveCard cannot be nil'; Localized: 'CardPanel.ActiveCard не може бути nil'),
    (English: 'Invalid index'; Localized: 'Недійсний індекс'),
    (English: 'Unable to insert an item'; Localized: 'Не вдається додати елемент'),
    (English: 'Invalid owner'; Localized: 'Недійсний власник'),
    (English: 'RichEdit line insertion error'; Localized: 'Помилка RichEdit вставки рядка'),
    (English: 'Failed to Load Stream'; Localized: 'Не вдалося завантажити потік'),
    (English: 'Failed to Save Stream'; Localized: 'Не вдалося зберегти потік'),
    (English: '%s is already associated with %s'; Localized: '%s вже пов’язаний з %s'),
    (English: 'This control requires version 4.70 or greater of COMCTL32.DLL'; Localized: 'Для роботи цього елемента управління потрібна версія COMCTL32.DLL 4.70 або новіша'),
    (English: 'ListView item can be added only when OwnerData is False.  Use OnData instead.'; Localized: 'Елемент ListView можна додати лише тоді, коли параметр OwnerData = False. Замість цього використовуйте OnData.'),
    (English: 'This "Portable Network Graphics" image is not valid because it contains invalid pieces of data (crc error)'; Localized: 'Це зображення "Portable Network Graphics" недійсне, оскільки містить пошкоджені дані (помилка CRC)'),
    (English: 'The "Portable Network Graphics" image could not be loaded because one of its main piece of data (ihdr) might be corrupted'; Localized: 'Зображення "Portable Network Graphics" не вдалося завантажити, оскільки один із його основних елементів даних (IHDR) может бути пошкоджений'),
    (English: 'This "Portable Network Graphics" image is invalid because it has missing image parts.'; Localized: 'Це зображення "Portable Network Graphics" недійсне, оскільки в ньому відсутні частини зображення.'),
    (English: 'Could not decompress the image because it contains invalid compressed data.'#13#10' Description: '; Localized: 'Не вдалося декодувати зображення, оскільки воно містить недійсні стислі дані.'#13#10' Опис: '),
    (English: 'The "Portable Network Graphics" image contains an invalid palette.'; Localized: 'Зображення "Portable Network Graphics" містить недійсну палітру.'),
    (English: 'The file being read is not a valid "Portable Network Graphics" image because it contains an invalid header. This file may be corrupted, try obtaining it again'; Localized: 'Файл, який зчитується, не є дійсним зображенням "Portable Network Graphics", оскільки містить недійсний заголовок. Цей файл може бути пошкоджено, спробуйте отримати його знову.'),
    (English: 'This "Portable Network Graphics" image is not supported or it might be invalid.'#13#10'(IHDR chunk is not the first)'; Localized: 'Це зображення "Portable Network Graphics" не підтримується або може бути недійсним.'#13#10'(фрагмент IHDR не перший)'),
    (English: 'This "Portable Network Graphics" image is not supported because either its width or height exceeds the maximum size of 65535 pixels.'; Localized: 'Це зображення "Portable Network Graphics" не підтримується, оскільки його ширина або висота перевищує максимальний розмір у 65535 пікселів.'),
    (English: 'There is no such palette entry.'; Localized: 'Такого запису в палітрі немає.'),
    (English: 'This "Portable Network Graphics" image contains an unknown critical part which could not be decoded.'; Localized: 'Це зображення "Portable Network Graphics" містить невідому критичну частину, яку неможливо декодувати.'),
    (English: 'This "Portable Network Graphics" image is encoded with an unknown compression scheme which could not be decoded.'; Localized: 'Це зображення "Portable Network Graphics" закодовано за допомогою невідомої схеми стиснення, яку неможливо декодувати.'),
    (English: 'This "Portable Network Graphics" image uses an unknown interlace scheme which could not be decoded.'; Localized: 'У цьому зображенні "Portable Network Graphics" використовується невідома схема чередування рядків, яку неможливо декодувати.'),
    (English: 'This "Portable Network Graphics" image uses an unknown color type which could not be decoded.'; Localized: 'У цьому зображенні "Portable Network Graphics" використовується невідомий тип кольору, який неможливо розшифрувати.'),
    (English: 'The chunks must be compatible to be assigned.'; Localized: 'Для призначення фрагменти мають бути сумісними.'),
    (English: 'This "Portable Network Graphics" image is invalid because the decoder found an unexpected end of the file.'; Localized: 'Це зображення "Portable Network Graphics" недійсне, оскільки декодер знайшов неочікуваний кінець файлу.'),
    (English: 'This "Portable Network Graphics" image contains no data.'; Localized: 'Це зображення "Portable Network Graphics" не містить даних.'),
    (English: 'The program tried to add a existent critical chunk to the current image which is not allowed.'; Localized: 'Програма спробувала додати наявний критичний фрагмент до поточного зображення, що заборонено.'),
    (English: 'It''s not allowed to add a new chunk because the current image is invalid.'; Localized: 'Не можна додавати новий фрагмент, оскільки поточне зображення недійсне.'),
    (English: 'Some operation could not be performed because the system is out of resources. Close some windows and try again.'; Localized: 'Деяку операцію не вдалося виконати, оскільки в системі немає ресурсів. Закрийте кілька вікон і повторіть спробу.'),
    (English: 'Setting bit transparency color is not allowed for png images containing alpha value for each pixel (COLOR_RGBALPHA and COLOR_GRAYSCALEALPHA)'; Localized: 'Встановлення кольору бітової прозорості не дозволяється для зображень PNG, які містять значення альфа для кожного пікселя (COLOR_RGBALPHA та COLOR_GRAYSCALEALPHA)'),
    (English: 'This operation is not valid because the current image contains no valid header.'; Localized: 'Ця операція є недійсною, оскільки поточний образ не містить дійсного заголовка.'),
    (English: 'The new size provided for image resizing is invalid.'; Localized: 'Новий розмір, вказаний для зміни розміру зображення, є недійсним.'),
    (English: 'The "Portable Network Graphics" image could not be loaded because it uses an invalid image bit depth.'; Localized: 'Зображення "Portable Network Graphics" не вдалося завантажити, оскільки воно має неправильну глибину кольору.'),
    (English: 'Exception '; Localized: 'Виняток '),
    (English: 'Data cannot be accessed as %s'; Localized: 'Неможливо отримати доступ до даних як %s'),
    (English: 'Check'; Localized: 'Позначити'),
    (English: 'Uncheck'; Localized: 'Зняти позначку'),
    (English: 'Collapse'; Localized: 'Згорнути'),
    (English: 'Obsolete'; Localized: 'Застаріле'),
    (English: 'Custom Messages'; Localized: 'Налаштовані повідомлення'),
    (English: 'Language Options'; Localized: 'Параметри мови'),
    (English: 'Messages'; Localized: 'Повідомлення'),
    (English: 'Component'; Localized: 'Компонент'),
    (English: 'Directory'; Localized: 'Каталог'),
    (English: 'File'; Localized: 'Файл'),
    (English: 'Icon'; Localized: 'Значок'),
    (English: 'INI'; Localized: 'INI'),
    (English: 'Delete'; Localized: 'Видалити'),
    (English: 'ISSig Key'; Localized: 'Ключ ISSig'),
    (English: 'Language'; Localized: 'Мова'),
    (English: 'Registry'; Localized: 'Реєстр'),
    (English: 'Task'; Localized: 'Завдання'),
    (English: 'Type'; Localized: 'Тип'),
    (English: 'Appearance'; Localized: 'Зовнішній вигляд'),
    (English: 'Application Details'; Localized: 'Деталі програми'),
    (English: 'Application Directory'; Localized: 'Каталог програми'),
    (English: 'Applications in Use'; Localized: 'Активні програми'),
    (English: 'Compression'; Localized: 'Стиснення'),
    (English: 'Disk Spanning'; Localized: 'Розподіл на диски'),
    (English: 'Installation Pages'; Localized: 'Сторінки інсталяції'),
    (English: 'Security'; Localized: 'Безпека'),
    (English: 'Start Menu Folder'; Localized: 'Тека меню ПУСК'),
    (English: 'System Requirements'; Localized: 'Системні вимоги'),
    (English: 'Uninstallation'; Localized: 'Деінсталяція'),
    (English: 'User Information'; Localized: 'Інформація про користувача'),
    (English: 'Version Information'; Localized: 'Інформація про версію'),
    (English: 'Common'; Localized: 'Загальні'));

implementation

end.
