unit IDE.LocalizeFunc.ChineseTraditional;

{
  Inno Setup
  Copyright (C) 1997-2026 Jordan Russell
  Portions by Martijn Laan
  For conditions of distribution and use, see LICENSE.TXT.

  Compiler IDE Chinese (Traditional) translations
}

interface

uses
  IDE.LocalizeFunc;

const
  ChineseTraditionalIDETranslations: array [0..1015] of TTranslationPair = (
    (English: 'Command-line usage:'; Localized: '命令列用法：'),
    (English: 'Examples:'; Localized: '範例：'),
    (English: 'script file'; Localized: '指令碼檔案'),
    (English: 'wizard name'; Localized: '精靈名稱'),
    (English: 'My script'; Localized: '我的指令碼'),
    (English: 'My Script Wizard'; Localized: '我的指令碼精靈'),
    (English: 'Could not load %1: %2'; Localized: '無法載入 %1：%2'),
    (English: 'Inno Setup Compiler'; Localized: 'Inno Setup Compiler'),
    (English: 'Example scripts...'; Localized: '範例指令碼...'),
    (English: 'More files...'; Localized: '更多檔案...'),
    (English: 'Untitled'; Localized: '未命名'),
    (English: 'Preprocessor Output'; Localized: '前置處理器輸出'),
    (English: 'Run Parameters'; Localized: '執行參數'),
    (English: 'Command-line parameters for %1 and %2:'; Localized: '%1和%2的命令列參數：'),
    (English: 'Inno Setup Script files'; Localized: 'Inno Setup 指令碼檔案'),
    (English: 'All files'; Localized: '所有檔案'),
    (English: 'Application files'; Localized: '應用程式檔案'),
    (English: 'Documentation files'; Localized: '文件檔案'),
    (English: 'Rich Text Format files'; Localized: 'RTF 格式檔案'),
    (English: 'Registry files'; Localized: '登錄檔'),
    (English: 'Icon files'; Localized: '圖示檔案'),
    (English: 'Image files'; Localized: '影像檔案'),
    (English: 'VCL Styles files'; Localized: 'VCL Styles 檔案'),
    (English: 'Inno Setup Messages files'; Localized: 'Inno Setup 訊息檔案'),
    (English: 'Public key files'; Localized: '公開金鑰檔案'),
    (English: 'Text files'; Localized: '文字檔案'),
    (English: 'Inno Setup Script Wizard'; Localized: 'Inno Setup 指令碼精靈'),
    (English: 'Welcome'; Localized: '歡迎'),
    (English: 'Application Information'; Localized: '應用程式資訊'),
    (English: 'Please specify some basic information about your application.'; Localized: '請指定應用程式的一些基本資訊。'),
    (English: 'Application Folder'; Localized: '應用程式資料夾'),
    (English: 'Please specify folder information about your application.'; Localized: '請指定應用程式的資料夾資訊。'),
    (English: 'Application Files'; Localized: '應用程式檔案'),
    (English: 'Please specify the files that are part of your application.'; Localized: '請指定屬於應用程式的檔案。'),
    (English: 'Please specify the source folder.'; Localized: '請指定來源資料夾。'),
    (English: 'Should files in subfolders of "%1" also be included?'; Localized: '是否也要包含「%1」的子資料夾中的檔案？'),
    (English: 'URL:'; Localized: 'URL：'),
    (English: 'Is the file to download an archive which should be extracted?'; Localized: '要下載的檔案是否為應解壓縮的壓縮檔？'),
    (English: 'Name of the file:'; Localized: '檔案名稱：'),
    (English: 'Name of the file (extension should match archive format):'; Localized: '檔案名稱 (副檔名應與壓縮檔格式相符)：'),
    (English: 'Approximate size of the file in megabytes:'; Localized: '檔案的大約大小 (MB)：'),
    (English: 'Application File Association'; Localized: '應用程式檔案關聯'),
    (English: 'Please specify which file association should be created for your application.'; Localized: '請指定應為應用程式建立的檔案關聯。'),
    (English: '%1 File'; Localized: '%1 檔案'),
    (English: 'Application Shortcuts'; Localized: '應用程式捷徑'),
    (English: 'Please specify which shortcuts should be created for your application.'; Localized: '請指定應為應用程式建立的捷徑。'),
    (English: 'Application Documentation'; Localized: '應用程式文件'),
    (English: 'Please specify which documentation files should be shown by Setup during installation.'; Localized: '請指定安裝程式在安裝期間應顯示的文件檔案。'),
    (English: 'Setup Install Mode'; Localized: '安裝程式安裝模式'),
    (English: 'Please specify in which install mode Setup should run.'; Localized: '請指定安裝程式應以哪種安裝模式執行。'),
    (English: 'Application Registry Keys And Values'; Localized: '應用程式登錄機碼和值'),
    (English: 'Please specify the registry keys and values that are part of your application.'; Localized: '請指定屬於應用程式的登錄機碼和值。'),
    (English: 'Setup Languages'; Localized: '安裝語言'),
    (English: 'Please specify which Setup languages should be included.'; Localized: '請指定應包含哪些安裝語言。'),
    (English: 'Compiler Settings'; Localized: '編譯器設定'),
    (English: 'Please specify some basic compiler settings.'; Localized: '請指定一些基本的編譯器設定。'),
    (English: 'Please specify the folder.'; Localized: '請指定資料夾。'),
    (English: 'Wizard Style'; Localized: '精靈樣式'),
    (English: 'Please specify which wizard style should be used.'; Localized: '請指定應使用哪種精靈樣式。'),
    (English: 'Inno Setup Preprocessor'; Localized: 'Inno Setup 前置處理器'),
    (English: 'Please specify whether Inno Setup Preprocessor should be used.'; Localized: '請指定是否應使用 Inno Setup 前置處理器。'),
    (English: 'The %1 can use %2 compiler directives to simplify your script. Although this is not necessary, it will make it easier to manually change the script later.%n%nDo you want the %1 to use %2 compiler directives?'; Localized: '%1 可以使用 %2 編譯器指示詞來簡化您的指令碼。雖然這並非必要，但這樣可以讓日後手動變更指令碼更加容易。%n%n您要讓 %1 使用 %2 編譯器指示詞嗎？'),
    (English: '&Yes, use %1 compiler directives'; Localized: '是，使用 %1 編譯器指示詞(&Y)'),
    (English: 'Finished'; Localized: '完成'),
    (English: '&Next'; Localized: '下一步(&N)'),
    (English: '&Finish'; Localized: '完成(&F)'),
    (English: 'The %1 is not complete. If you quit now, the new script file will not be generated.%n%nExit anyway?'; Localized: '%1 尚未完成。如果您現在結束，將不會產生新的指令碼檔案。%n%n仍要結束嗎？'),
    (English: 'Please specify the application name.'; Localized: '請指定應用程式名稱。'),
    (English: 'Please specify the application version.'; Localized: '請指定應用程式版本。'),
    (English: 'Please specify the application destination base folder.'; Localized: '請指定應用程式目的基底資料夾。'),
    (English: 'Please specify the application folder name.'; Localized: '請指定應用程式資料夾名稱。'),
    (English: 'Please specify the application main executable file.'; Localized: '請指定應用程式的主要可執行檔。'),
    (English: 'The specified application main executable file does not exist.'; Localized: '指定的應用程式主要可執行檔不存在。'),
    (English: 'Please specify the application Start Menu group name.'; Localized: '請指定應用程式的「開始」功能表資料夾名稱。'),
    (English: 'Please specify the destination base folder.'; Localized: '請指定目的基底資料夾。'),
    (English: 'Please specify a destination base folder other than the application folder.'; Localized: '請指定應用程式資料夾以外的目的基底資料夾。'),
    (English: 'Please specify the destination name.'; Localized: '請指定目的名稱。'),
    (English: 'Please select at least one language.'; Localized: '請至少選擇一種語言。'),
    (English: '&Source URL:'; Localized: '來源 URL(&S)：'),
    (English: 'Script generated by the %1.'; Localized: '此指令碼由 %1 產生。'),
    (English: 'SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!'; Localized: '如需建立 Inno Setup 指令碼檔案的詳細資訊，請參閱文件！'),
    (English: 'NOTE: The value of %1 uniquely identifies this application. Do not use the same %1 value in installers for other applications.'; Localized: '注意：%1 的值可唯一識別此應用程式。請勿在其他應用程式的安裝程式中使用相同的 %1 值。'),
    (English: '(To generate a new GUID, click Tools | Generate GUID inside the IDE.)'; Localized: '(若要產生新的 GUID，請在 IDE 中按一下「工具」|「產生 GUID」。)'),
    (English: '"%1" specifies that Setup cannot run on anything but x64 and Windows 11 on Arm.'; Localized: '「%1」指定安裝程式只能在 x64 和 Windows 11 on Arm 上執行。'),
    (English: '"%1" requests that the install be done in "64-bit mode" on x64 or Windows 11 on Arm.'; Localized: '「%1」要求在 x64 或 Windows 11 on Arm 上以「64 位元模式」進行安裝。'),
    (English: 'This means it should use the native 64-bit Program Files directory and the 64-bit view of the registry.'; Localized: '這表示安裝應使用原生的 64 位元 Program Files 資料夾和 64 位元的登錄檢視。'),
    (English: 'Uncomment the following line to use a 64-bit installer.'; Localized: '取消註解下面這一行即可使用 64 位元安裝程式。'),
    (English: 'Use "%1" if all your archives are .%2 files.'; Localized: '如果您的所有壓縮檔都是 .%2 檔案，請使用「%1」。'),
    (English: 'Use "%1" if all your archives are not password-protected.'; Localized: '如果您的所有壓縮檔都未受密碼保護，請使用「%1」。'),
    (English: 'Uncomment the following line to run in non administrative install mode (install for current user only).'; Localized: '取消註解下面這一行即可以非系統管理員安裝模式執行 (僅為目前使用者安裝)。'),
    (English: 'Remove the following line to run in administrative install mode (install for all users).'; Localized: '移除下面這一行即可以系統管理員安裝模式執行 (為所有使用者安裝)。'),
    (English: 'NOTE: Don''t use "%1" on any shared system files.'; Localized: '注意：請勿對任何共用的系統檔案使用「%1」。'),
    (English: 'NOTE: Use the "%1" flag or the "%2" parameter to verify downloads.'; Localized: '注意：請使用「%1」旗標或「%2」參數來驗證下載。'),
    (English: 'Registry data from file %1'; Localized: '來自檔案 %1 的登錄資料'),
    (English: 'COULD NOT IMPORT %1'; Localized: '無法匯入 %1'),
    (English: 'End of registry data from file %1'; Localized: '來自檔案 %1 的登錄資料結束'),
    (English: 'SOME KEYS FILTERED DUE TO %1 SETTINGS!'; Localized: '由於 %1 設定，部分機碼已被篩選掉！'),
    (English: 'SOME VALUES WITH UNSUPPORTED TYPES SKIPPED!'; Localized: '部分類型不受支援的值已被略過！'),
    (English: 'Would you like to compile the new script now?'; Localized: '您要現在編譯新的指令碼嗎？'),
    (English: 'My Program'; Localized: '我的程式'),
    (English: 'My Company, Inc.'; Localized: '我的公司'),
    (English: 'Application directory'; Localized: '應用程式資料夾'),
    (English: 'Program Files directory'; Localized: 'Program Files 資料夾'),
    (English: 'Common Files directory'; Localized: 'Common Files 資料夾'),
    (English: 'Windows directory'; Localized: 'Windows 資料夾'),
    (English: 'Windows system directory'; Localized: 'Windows 系統資料夾'),
    (English: 'Setup source directory'; Localized: '安裝程式來源資料夾'),
    (English: 'System drive root directory'; Localized: '系統磁碟機根資料夾'),
    (English: '(Custom)'; Localized: '(自訂)'),
    (English: 'Starting compile.%1[%2]'; Localized: '開始編譯。%1[%2]'),
    (English: 'Finished.%1[%2, %3 elapsed]'; Localized: '已完成。%1[%2，耗時 %3]'),
    (English: 'Compile aborted.'; Localized: '編譯已中止。'),
    (English: 'Log size limit reached, list reset.'; Localized: '已達記錄大小限制，清單已重設。'),
    (English: '%1 started'; Localized: '%1已啟動'),
    (English: 'Terminating process'; Localized: '正在終止處理序'),
    (English: 'Removing left-over temporary directory: %1'; Localized: '正在移除遺留的暫存資料夾：%1'),
    (English: 'Failed to remove temporary directory'; Localized: '無法移除暫存資料夾'),
    (English: '%1 Call Stack'; Localized: '%1 呼叫堆疊'),
    (English: 'Cannot run Setup at this time. Please compile Setup successfully to completion first, with output enabled'; Localized: '目前無法執行安裝程式。請先在啟用輸出的情況下將安裝程式成功編譯完成'),
    (English: 'Cannot run Uninstall at this time. Please run Setup successfully to completion first'; Localized: '目前無法執行解除安裝程式。請先將安裝程式成功執行完成'),
    (English: 'Error executing "%1":%n%n%2: %3'; Localized: '執行「%1」時發生錯誤：%n%n%2：%3'),
    (English: 'Are you sure you want to abort the compile?'; Localized: '您確定要中止編譯嗎？'),
    (English: 'File %1:'; Localized: '檔案 %1：'),
    (English: 'Line %1:'; Localized: '第 %1 行：'),
    (English: 'Compiler Error'; Localized: '編譯器錯誤'),
    (English: 'Illegal null character on line %1'; Localized: '第 %1 行含有不合法的 Null 字元'),
    (English: 'Cannot find "%1"'; Localized: '找不到「%1」'),
    (English: 'Invalid regular expression "%1"'; Localized: '無效的規則運算式「%1」'),
    (English: '%1 (%2 hits):'; Localized: '%1 (%2 個相符項目)：'),
    (English: 'Find "%1" (%2 hits in %3 files)'; Localized: '尋找「%1」(在 %3 個檔案中有 %2 個相符項目)'),
    (English: '%1 occurrence(s) replaced.'; Localized: '已取代 %1 個相符項目。'),
    (English: 'The .%1 extension was successfully associated for the current user with:%n%2'; Localized: '已成功為目前使用者將 .%1 副檔名與下列程式產生關聯：%n%2'),
    (English: 'The .%1 extension was successfully associated for all users with:%n%2'; Localized: '已成功為所有使用者將 .%1 副檔名與下列程式產生關聯：%n%2'),
    (English: 'Error creating file association:%n%1 - %2'; Localized: '建立檔案關聯時發生錯誤：%n%1 - %2'),
    (English: 'Unable to associate for all users without administrative privileges. Do you want to associate only for yourself instead?'; Localized: '沒有系統管理員權限，無法為所有使用者產生關聯。您要改為僅為自己產生關聯嗎？'),
    (English: 'Associate'; Localized: '產生關聯'),
    (English: 'Inno Setup Script'; Localized: 'Inno Setup 指令碼'),
    (English: 'Compi&le'; Localized: '編譯(&L)'),
    (English: '&Script has %1'; Localized: '指令碼已包含 %1(&S)'),
    (English: 'Script has %1 set'; Localized: '指令碼已設定 %1'),
    (English: 'Invalid file format.'; Localized: '無效的檔案格式。'),
    (English: 'The specified registry file does not exist.'; Localized: '指定的登錄檔不存在。'),
    (English: 'Setup'; Localized: '安裝程式'),
    (English: 'Your message text.'; Localized: '您的訊息文字。'),
    (English: 'Enter your text here...'; Localized: '在此輸入您的文字...'),
    (English: 'Return values'; Localized: '傳回值'),
    (English: 'Default'; Localized: '預設'),
    (English: 'Shield'; Localized: '盾牌'),
    (English: 'Instruction Text'; Localized: '指示文字'),
    (English: 'Message Text'; Localized: '訊息文字'),
    (English: 'user clicked %1'; Localized: '使用者按了 %1'),
    (English: 'OK'; Localized: '確定'),
    (English: 'Yes'; Localized: '是'),
    (English: 'No'; Localized: '否'),
    (English: 'Cancel'; Localized: '取消'),
    (English: 'Retry'; Localized: '重試'),
    (English: 'Ignore'; Localized: '略過'),
    (English: 'Abort'; Localized: '中止'),
    (English: 'Display a message box'; Localized: '顯示訊息方塊'),
    (English: 'Name of the Sign Tool:'; Localized: '簽署工具的名稱：'),
    (English: 'Invalid name.'; Localized: '無效的名稱。'),
    (English: 'Duplicate name.'; Localized: '重複的名稱。'),
    (English: 'Command of the Sign Tool:'; Localized: '簽署工具的命令：'),
    (English: 'Invalid command.'; Localized: '無效的命令。'),
    (English: '%1 must be an integer value'; Localized: '%1 必須是整數值'),
    (English: 'The script cannot be edited because it is read-only'; Localized: '指令碼為唯讀，無法編輯'),
    (English: 'Parameter "%1" cannot be browsed for when the "%2" flag is used'; Localized: '使用「%2」旗標時，無法瀏覽參數「%1」的值'),
    (English: 'Move to a parameter entry or a key/value or [Code] section'; Localized: '請移至參數項目、索引鍵/值區段或 [Code] 區段'),
    (English: 'Move to a parameter entry or a non-empty key/value or [Code] section'; Localized: '請移至參數項目、非空白的索引鍵/值區段或 [Code] 區段'),
    (English: 'Select entries of one section type, and no other content'; Localized: '請只選取一種區段類型的項目，且不要選取其他內容'),
    (English: 'Unspecified directives are hidden because this section occurs more than once'; Localized: '由於此區段出現多次，未指定的指示詞已隱藏'),
    (English: 'Unspecified directives are hidden because this is not the main script file'; Localized: '由於這不是主指令碼檔案，未指定的指示詞已隱藏'),
    (English: 'Routines'; Localized: '常式'),
    (English: 'Types'; Localized: '類型'),
    (English: 'Symbols'; Localized: '符號'),
    (English: 'Parameters'; Localized: '參數'),
    (English: 'Locals'; Localized: '區域變數'),
    (English: 'The generated GUID will be inserted into the editor at the cursor position. Continue?'; Localized: '產生的 GUID 將插入編輯器中游標所在的位置。要繼續嗎？'),
    (English: 'The generated Pascal script will be inserted into the editor at the cursor position, but the cursor is not in the %1 section. Continue anyway?'; Localized: '產生的 Pascal 指令碼將插入編輯器中游標所在的位置，但游標不在 %1 區段中。仍要繼續嗎？'),
    (English: 'Classic'; Localized: '傳統'),
    (English: 'Visual Studio / Visual Studio Code'; Localized: 'Visual Studio / Visual Studio Code'),
    (English: 'Classic / Visual Studio'; Localized: '傳統 / Visual Studio'),
    (English: 'Visual Studio Code'; Localized: 'Visual Studio Code'),
    (English: 'Light'; Localized: '淺色'),
    (English: 'Dark'; Localized: '深色'),
    (English: 'The new language will take effect the next time you start Inno Setup Compiler.'; Localized: '新的語言將在下次啟動 Inno Setup Compiler 時生效。'),
    (English: '&New...'; Localized: '新增(&N)...'),
    (English: '&New'; Localized: '新增(&N)'),
    (English: 'Line %1'; Localized: '第 %1 行'),
    (English: '%1: %2'; Localized: '%1：%2'),
    (English: 'Back (%1)'; Localized: '返回 (%1)'),
    (English: 'Forward (%1)'; Localized: '前進 (%1)'),
    (English: 'Back'; Localized: '返回'),
    (English: 'Forward'; Localized: '前進'),
    (English: 'Open'; Localized: '開啟'),
    (English: 'Run'; Localized: '執行'),
    (English: 'Save As'; Localized: '另存新檔'),
    (English: 'Font'; Localized: '字型'),
    (English: 'Text Color'; Localized: '文字色彩'),
    (English: 'Background Color'; Localized: '背景色彩'),
    (English: 'Ctrl+'; Localized: 'Ctrl+'),
    (English: 'Shift+'; Localized: 'Shift+'),
    (English: 'Alt+'; Localized: 'Alt+'),
    (English: 'Num %1'; Localized: 'Num %1'),
    (English: '(32-bit)'; Localized: '(32 位元)'),
    (English: '[Compiling]'; Localized: '[正在編譯]'),
    (English: '[Running]'; Localized: '[正在執行]'),
    (English: '[Paused]'; Localized: '[已暫停]'),
    (English: 'Read only'; Localized: '唯讀'),
    (English: 'Modified'; Localized: '已修改'),
    (English: 'Overwrite'; Localized: '取代'),
    (English: 'Insert'; Localized: '插入'),
    (English: 'Tabs closed: %1'; Localized: '已關閉的索引標籤：%1'),
    (English: 'Estimated time remaining: %1'; Localized: '預估剩餘時間：%1'),
    (English: 'Average KB/sec: %1'; Localized: '平均 KB/秒：%1'),
    (English: 'There was an error opening the file. Remove it from the list?'; Localized: '開啟檔案時發生錯誤。要將它從清單中移除嗎？'),
    (English: 'The text in the %1 file has changed.%n%nDo you want to save the changes?'; Localized: '%1 檔案中的文字已變更。%n%n您要儲存變更嗎？'),
    (English: 'Please stop the compile process before performing this command.'; Localized: '請先停止編譯，再執行此命令。'),
    (English: 'A compile is already in progress.'; Localized: '編譯已在進行中。'),
    (English: 'The text in the %1 file has changed and must be saved before compiling.%n%nSave the changes and continue?'; Localized: '%1 檔案中的文字已變更，必須在編譯前儲存。%n%n要儲存變更並繼續嗎？'),
    (English: 'Would you like to save the script before compiling?%n%nIf you answer No, the compiled installation will be placed under your My Documents folder by default.'; Localized: '您要在編譯前儲存指令碼嗎？%n%n如果您回答「否」，編譯後的安裝程式預設將放在您的「文件」資料夾中。'),
    (English: 'The selected file is an %1 file. Go to its tab instead of opening it as the new main file?'; Localized: '選取的檔案是 %1 檔案。要移至它的索引標籤，而不是將它開啟為新的主檔案嗎？'),
    (English: 'The selected file is not available as a tab. Opening as the new main file instead.'; Localized: '選取的檔案沒有可用的索引標籤。將改為開啟為新的主檔案。'),
    (English: 'Error creating file (code %1). Could not save file'; Localized: '建立檔案時發生錯誤 (代碼 %1)。無法儲存檔案'),
    (English: 'Error creating backup file. Could not save file'; Localized: '建立備份檔案時發生錯誤。無法儲存檔案'),
    (English: 'Error removing existing file (code %1). Could not save file'; Localized: '移除現有檔案時發生錯誤 (代碼 %1)。無法儲存檔案'),
    (English: 'Error renaming temporary file (code %1). Could not save file'; Localized: '重新命名暫存檔案時發生錯誤 (代碼 %1)。無法儲存檔案'),
    (English: 'Failed to open included file: %1'; Localized: '無法開啟包含檔案：%1'),
    (English: 'Cannot start printer document.'; Localized: '無法啟動印表機文件。'),
    (English: 'Are you sure you want to clear the list of recently opened files?'; Localized: '您確定要清除最近開啟的檔案清單嗎？'),
    (English: 'The %1 file has been modified outside of the source editor. You might want to reload it.'; Localized: '%1 檔案已在來源編輯器外部被修改。您可能需要重新載入它。'),
    (English: 'The %1 file has been modified outside of the source editor.%n%nDo you want to reload the file?'; Localized: '%1 檔案已在來源編輯器外部被修改。%n%n您要重新載入檔案嗎？'),
    (English: 'The %1 file has been modified outside of the source editor. Changes have also been made in the source editor.%n%nDo you want to reload the file and lose the changes made in the source editor?'; Localized: '%1 檔案已在來源編輯器外部被修改，來源編輯器中也已進行變更。%n%n您要重新載入檔案並放棄在來源編輯器中所做的變更嗎？'),
    (English: 'File not opened.'; Localized: '檔案未開啟。'),
    (English: 'Go to Line'; Localized: '移至行'),
    (English: 'Line number:'; Localized: '行號：'),
    (English: 'Could not load file (code %1)'; Localized: '無法載入檔案 (代碼 %1)'),
    (English: 'Could not save file (code %1)'; Localized: '無法儲存檔案 (代碼 %1)'),
    (English: 'Do you want to copy your current license key to the clipboard before opening our order page? You will need it to be able to renew it.'; Localized: '在開啟我們的訂購頁面之前，您要先將目前的授權金鑰複製到剪貼簿嗎？續約時您將需要它。'),
    (English: 'New commercial license key has been registered:%n%n%1%n%nThanks for your support!'; Localized: '新的商業授權金鑰已註冊：%n%n%1%n%n感謝您的支持！'),
    (English: 'Are you sure you want to remove your commercial license key and revert to non-commercial use only?'; Localized: '您確定要移除商業授權金鑰並恢復為僅限非商業使用嗎？'),
    (English: 'Commercial license key has been removed.'; Localized: '商業授權金鑰已移除。'),
    (English: 'Your version of Inno Setup has been updated! <a id="%1">See what''s new</a>.'; Localized: '您的 Inno Setup 版本已更新！<a id="%1">查看新功能</a>。'),
    (English: 'VS Code-style editor shortcuts added! Use the <a id="%1">Editor Keys option</a> in Options dialog.'; Localized: '已新增 VS Code 樣式的編輯器快速鍵！請使用「選項」對話方塊中的<a id="%1">編輯器按鍵選項</a>。'),
    (English: 'RTF Editor added, a built-in WordPad replacement! Use the <a id="%1">RTF Editor item</a> in Tools menu.'; Localized: '已新增 RTF 編輯器，這是內建的 WordPad 替代品！請使用「工具」功能表中的<a id="%1">RTF 編輯器項目</a>。'),
    (English: 'Inno Setup Compiler is available in your language! Use the <a id="%1">Language option</a> in Options dialog.'; Localized: 'Inno Setup Compiler 已提供您的語言版本！請使用「選項」對話方塊中的<a id="%1">語言選項</a>。'),
    (English: '<a id="%1">Ideas board is open!</a> Share your ideas and vote on others, this month only.'; Localized: '<a id="%1">創意看板已開放！</a>分享您的想法並為其他人的想法投票，僅限本月。'),
    (English: 'Running a version released after your update entitlement ended. <a id="%1">Renew license</a>, <a id="%2">remove key</a>, or <a id="%3">exit</a>.'; Localized: '您正在執行的版本是在您的更新權益結束後發行的。請<a id="%1">續約授權</a>、<a id="%2">移除金鑰</a>或<a id="%3">結束</a>。'),
    (English: 'Your update entitlement is ending soon. Please <a id="%1">renew your license</a>. Thanks!'; Localized: '您的更新權益即將結束。請<a id="%1">續約您的授權</a>。謝謝！'),
    (English: 'Your update entitlement has ended. Please <a id="%1">renew your license</a>. Thanks!'; Localized: '您的更新權益已結束。請<a id="%1">續約您的授權</a>。謝謝！'),
    (English: 'Using Inno Setup commercially? Please <a id="%1">purchase a license</a>. Thanks!'; Localized: '將 Inno Setup 用於商業用途？請<a id="%1">購買授權</a>。謝謝！'),
    (English: 'Uninstall'; Localized: '解除安裝程式'),
    (English: '%1 exit code: 0x%2'; Localized: '%1結束代碼：0x%2'),
    (English: '%1 exit code: %2'; Localized: '%1結束代碼：%2'),
    (English: 'Unable to get %1 exit code (%2 failed)'; Localized: '無法取得%1的結束代碼 (%2 失敗)'),
    (English: '%1 is still running; can''t get exit code'; Localized: '%1仍在執行；無法取得結束代碼'),
    (English: 'Please stop the running %1 process before performing this command.'; Localized: '請先停止正在執行的%1處理序，再執行此命令。'),
    (English: 'This command will detach the debugger from the running %1 process. Continue?'; Localized: '此命令會將偵錯工具與正在執行的%1處理序中斷連結。要繼續嗎？'),
    (English: 'The changes you made will not take effect until you re-compile.%n%nContinue running anyway?'; Localized: '您所做的變更在重新編譯之前不會生效。%n%n仍要繼續執行嗎？'),
    (English: 'A pause is already pending.'; Localized: '已有暫停要求擱置中。'),
    (English: 'No code was generated for the current line.'; Localized: '未為目前這一行產生任何程式碼。'),
    (English: 'This will unconditionally terminate the running %1 process. Continue?'; Localized: '這將無條件終止正在執行的%1處理序。要繼續嗎？'),
    (English: 'Note that if %1 is currently in the installation phase, any changes made to the system thus far will not be undone, nor will uninstall data be written.'; Localized: '請注意，如果%1目前正處於安裝階段，到目前為止對系統所做的任何變更都不會復原，也不會寫入解除安裝資訊。'),
    (English: 'Evaluate'; Localized: '評估'),
    (English: 'Constant to evaluate (for example, "%1"):'; Localized: '要評估的常數 (例如「%1」)：'),
    (English: 'Evaluate Result'; Localized: '評估結果'),
    (English: 'Evaluate Error'; Localized: '評估錯誤'),
    (English: 'An unknown error occurred.'; Localized: '發生未知的錯誤。'),
    (English: '%1 = "%2"'; Localized: '%1 = "%2"'),
    (English: '%1 = Exception: %2'; Localized: '%1 = 例外狀況：%2'),
    (English: '%1 = Unknown error'; Localized: '%1 = 未知的錯誤'),
    (English: 'Unknown error'; Localized: '未知的錯誤'),
    (English: 'Line %1:%n%2'; Localized: '第 %1 行：%n%2'),
    (English: 'Runtime Error'; Localized: '執行階段錯誤'),
    (English: '%1 (Update entitlement ended)'; Localized: '%1 (更新權益已結束)'),
    (English: '%1 (Update entitlement ended but updated anyway)'; Localized: '%1 (更新權益已結束，但仍已更新)'),
    (English: 'Non-commercial use only'; Localized: '僅限非商業使用'),
    (English: 'Single User'; Localized: '單一使用者'),
    (English: 'Team'; Localized: '團隊'),
    (English: 'Enterprise'; Localized: '企業'),
    (English: 'Inno Setup %1 License'; Localized: 'Inno Setup %1授權'),
    (English: '%1, %2.'; Localized: '%1，%2。'),
    (English: 'Includes updates until %1, major and minor.'; Localized: '包含截至 %1 的主要和次要版本更新。'),
    (English: 'Includes all future updates, major and minor.'; Localized: '包含所有未來的主要和次要版本更新。'),
    (English: '%1 Entries Designer'; Localized: '%1 項目設計工具'),
    (English: '&Insert'; Localized: '插入(&I)'),
    (English: '&Parameters...'; Localized: '參數(&P)...'),
    (English: 'Remo&ve'; Localized: '移除(&V)'),
    (English: 'Add Fol&der...'; Localized: '新增資料夾(&D)...'),
    (English: '&Add File(s)...'; Localized: '新增檔案(&A)...'),
    (English: '&Files:'; Localized: '檔案(&F)：'),
    (English: 'Add D&ownload...'; Localized: '新增下載(&O)...'),
    (English: 'Go to File'; Localized: '移至檔案'),
    (English: 'Enter Commercial License Key'; Localized: '輸入商業授權金鑰'),
    (English: 'Paste your license key below'; Localized: '請在下方貼上您的授權金鑰'),
    (English: 'Close'; Localized: '關閉'),
    (English: 'Filter'; Localized: '篩選'),
    (English: 'Inspector Menu'; Localized: '檢查器功能表'),
    (English: 'Sections'; Localized: '區段'),
    (English: 'New Main Script (%1)'; Localized: '新增主指令碼 (%1)'),
    (English: 'Open Main Script (%1)'; Localized: '開啟主指令碼 (%1)'),
    (English: 'Save (%1)'; Localized: '儲存 (%1)'),
    (English: 'Stop Compile (%1)'; Localized: '停止編譯 (%1)'),
    (English: 'Target Setup (%1)'; Localized: '將安裝程式設為目標 (%1)'),
    (English: 'Target Uninstall (%1)'; Localized: '將解除安裝程式設為目標 (%1)'),
    (English: 'Help (%1)'; Localized: '說明 (%1)'),
    (English: 'Main Script'; Localized: '主指令碼'),
    (English: 'Close Banner'; Localized: '關閉橫幅'),
    (English: '&File'; Localized: '檔案(&F)'),
    (English: '&Open...'; Localized: '開啟(&O)...'),
    (English: 'Open &Recent'; Localized: '開啟最近的檔案(&R)'),
    (English: '&Clear Recently Opened'; Localized: '清除最近開啟的檔案(&C)'),
    (English: '&Save'; Localized: '儲存(&S)'),
    (English: 'Save &As...'; Localized: '另存新檔(&A)...'),
    (English: 'Save &Encoding'; Localized: '儲存編碼(&E)'),
    (English: '&Auto (ANSI or UTF-8)'; Localized: '自動 (ANSI 或 UTF-8)(&A)'),
    (English: '&UTF-8'; Localized: 'UTF-8(&U)'),
    (English: 'UTF-8 with &BOM'; Localized: '含 BOM 的 UTF-8(&B)'),
    (English: 'Sa&ve All'; Localized: '全部儲存(&V)'),
    (English: '&Print...'; Localized: '列印(&P)...'),
    (English: 'E&xit'; Localized: '結束(&X)'),
    (English: '&Edit'; Localized: '編輯(&E)'),
    (English: '&Undo'; Localized: '復原(&U)'),
    (English: '&Redo'; Localized: '取消復原(&R)'),
    (English: 'Cu&t'; Localized: '剪下(&T)'),
    (English: '&Copy'; Localized: '複製(&C)'),
    (English: '&Paste'; Localized: '貼上(&P)'),
    (English: 'De&lete'; Localized: '刪除(&L)'),
    (English: 'Select &All'; Localized: '全選(&A)'),
    (English: 'Add Next &Occurrence'; Localized: '新增下一個相符項目(&O)'),
    (English: '&Select All Occurrences'; Localized: '選取所有相符項目(&S)'),
    (English: 'Select All Find &Matches'; Localized: '選取所有找到的相符項目(&M)'),
    (English: '&Find...'; Localized: '尋找(&F)...'),
    (English: 'F&ind in Files...'; Localized: '在檔案中尋找(&I)...'),
    (English: 'Find &Next'; Localized: '尋找下一個(&N)'),
    (English: 'Find Pre&vious'; Localized: '尋找上一個(&V)'),
    (English: 'R&eplace...'; Localized: '取代(&E)...'),
    (English: 'Use Regular E&xpressions'; Localized: '使用規則運算式(&X)'),
    (English: 'Fol&d Section'; Localized: '摺疊區段(&D)'),
    (English: 'Unfold Section'; Localized: '展開區段'),
    (English: 'Go to File...'; Localized: '移至檔案...'),
    (English: '&Go to Line...'; Localized: '移至行(&G)...'),
    (English: 'Toggle Line Comment'; Localized: '切換行註解'),
    (English: 'Go To Matching Brace'; Localized: '移至對應的大括號'),
    (English: '&View'; Localized: '檢視(&V)'),
    (English: '&Zoom'; Localized: '縮放(&Z)'),
    (English: 'Zoom &In'; Localized: '放大(&I)'),
    (English: 'Zoom &Out'; Localized: '縮小(&O)'),
    (English: '&Reset'; Localized: '重設(&R)'),
    (English: '&Toolbar'; Localized: '工具列(&T)'),
    (English: 'Na&vigator'; Localized: '導覽器(&V)'),
    (English: '&Inspector'; Localized: '檢查器(&I)'),
    (English: 'St&atus Bar'; Localized: '狀態列(&A)'),
    (English: '&Next Tab'; Localized: '下一個索引標籤(&N)'),
    (English: '&Previous Tab'; Localized: '上一個索引標籤(&P)'),
    (English: 'C&lose Tab'; Localized: '關閉索引標籤(&L)'),
    (English: 'Re&open Tab'; Localized: '重新開啟索引標籤(&O)'),
    (English: 'Reopen &All Tabs'; Localized: '重新開啟所有索引標籤(&A)'),
    (English: 'C&lose Current Tab'; Localized: '關閉目前的索引標籤(&L)'),
    (English: 'Focus Navi&gator'; Localized: '聚焦導覽器(&G)'),
    (English: 'Focus And &Select Navigator'; Localized: '聚焦並選取導覽器(&S)'),
    (English: '&Compiler Output'; Localized: '編譯器輸出(&C)'),
    (English: '&Debug Output'; Localized: '偵錯輸出(&D)'),
    (English: 'D&ebug Call Stack'; Localized: '偵錯呼叫堆疊(&E)'),
    (English: '&Find Results'; Localized: '尋找結果(&F)'),
    (English: '&Hide Bottom Pane'; Localized: '隱藏底部窗格(&H)'),
    (English: '&Word Wrap'; Localized: '自動換行(&W)'),
    (English: '&Go to'; Localized: '移至(&G)'),
    (English: 'Show all known directives'; Localized: '顯示所有已知的指示詞'),
    (English: 'Follow cursor'; Localized: '跟隨游標'),
    (English: 'Quote new directive values'; Localized: '以引號括住新的指示詞值'),
    (English: 'Quote new parameter values'; Localized: '以引號括住新的參數值'),
    (English: '&Help'; Localized: '說明(&H)'),
    (English: '&Build'; Localized: '建置(&B)'),
    (English: '&Compile'; Localized: '編譯(&C)'),
    (English: 'S&top Compile'; Localized: '停止編譯(&T)'),
    (English: '&Low Priority During Compile'; Localized: '編譯時使用低優先順序(&L)'),
    (English: '&Disable Output'; Localized: '停用輸出(&D)'),
    (English: 'Disable Co&mpression'; Localized: '停用壓縮(&M)'),
    (English: 'Disable &Signing'; Localized: '停用簽署(&S)'),
    (English: 'Disable Signcheck &Validation'; Localized: '停用簽章檢查驗證(&V)'),
    (English: '&Open Output Folder'; Localized: '開啟輸出資料夾(&O)'),
    (English: '&Run'; Localized: '執行(&R)'),
    (English: '&Run...'; Localized: '執行(&R)...'),
    (English: 'Run to &Cursor'; Localized: '執行至游標處(&C)'),
    (English: 'Step &Into'; Localized: '逐步執行(&I)'),
    (English: 'Step &Over'; Localized: '不進入函式(&O)'),
    (English: 'Step Out'; Localized: '跳離函式'),
    (English: 'Toggle &Breakpoint'; Localized: '切換中斷點(&B)'),
    (English: '&Delete All Breakpoints'; Localized: '移除所有中斷點(&D)'),
    (English: 'P&ause'; Localized: '暫停(&A)'),
    (English: '&Terminate'; Localized: '終止(&T)'),
    (English: '&Evaluate Constant...'; Localized: '評估常數(&E)...'),
    (English: 'Target &Setup'; Localized: '將安裝程式設為目標(&S)'),
    (English: 'Target &Uninstall'; Localized: '將解除安裝程式設為目標(&U)'),
    (English: '&Tools'; Localized: '工具(&T)'),
    (English: '&Add/Remove Programs'; Localized: '新增或移除程式(&A)'),
    (English: 'Generate &GUID'; Localized: '產生 GUID(&G)'),
    (English: 'Generate %1 Entries...'; Localized: '產生 %1 項目...'),
    (English: 'Generate %1 Call...'; Localized: '產生 %1 呼叫...'),
    (English: '&Configure Sign Tools...'; Localized: '設定簽署工具(&C)...'),
    (English: 'R&TF Editor...'; Localized: 'RTF 編輯器(&T)...'),
    (English: '&Options...'; Localized: '選項(&O)...'),
    (English: 'Purchase or Renew Commercial &License'; Localized: '購買或續約商業授權(&L)'),
    (English: 'Enter Commercial License &Key...'; Localized: '輸入商業授權金鑰(&K)...'),
    (English: 'Remove Commercial License Key'; Localized: '移除商業授權金鑰'),
    (English: '&Donate'; Localized: '捐款(&D)'),
    (English: '&Keyboard And Mouse Commands'; Localized: '鍵盤和滑鼠命令(&K)'),
    (English: 'Regular E&xpressions'; Localized: '規則運算式(&X)'),
    (English: 'Inno &Setup Documentation'; Localized: 'Inno Setup 文件(&S)'),
    (English: 'Inno Setup &Example Scripts'; Localized: 'Inno Setup 範例指令碼(&E)'),
    (English: 'Inno Setup &FAQ'; Localized: 'Inno Setup FAQ(&F)'),
    (English: 'Inno Setup &Mailing List'; Localized: 'Inno Setup 郵寄清單(&M)'),
    (English: 'Inno Setup &Revision History'; Localized: 'Inno Setup 修訂歷程記錄(&R)'),
    (English: 'Inno Setup &Web Site'; Localized: 'Inno Setup 網站(&W)'),
    (English: 'Inno Setup &Preprocessor Documentation'; Localized: 'Inno Setup 前置處理器文件(&P)'),
    (English: '&About Inno Setup'; Localized: '關於 Inno Setup(&A)'),
    (English: '%1 Call Designer'; Localized: '%1 呼叫設計工具'),
    (English: 'Instruction'; Localized: '指示'),
    (English: 'Message'; Localized: '訊息'),
    (English: 'Buttons'; Localized: '按鈕'),
    (English: ' Type '; Localized: ' 類型 '),
    (English: 'Suppressible'; Localized: '可隱藏'),
    (English: ' Flags '; Localized: ' 旗標 '),
    (English: 'Default button'; Localized: '預設按鈕'),
    (English: ' Icon '; Localized: ' 圖示 '),
    (English: ' Return values '; Localized: ' 傳回值 '),
    (English: '&Preview'; Localized: '預覽(&P)'),
    (English: 'Options'; Localized: '選項'),
    (English: ' Miscellaneous '; Localized: ' 其他 '),
    (English: 'Show &Welcome dialog at startup'; Localized: '啟動時顯示「歡迎」對話方塊(&W)'),
    (English: 'Use the Inno Setup &Script Wizard'; Localized: '使用 Inno Setup 指令碼精靈(&S)'),
    (English: 'Automatically sa&ve before compiling'; Localized: '編譯前自動儲存(&V)'),
    (English: 'Create &backups when saving'; Localized: '儲存時建立備份(&B)'),
    (English: 'Allow &Undo after save'; Localized: '允許在儲存後復原(&U)'),
    (English: 'Display &full path in title bar'; Localized: '在標題列顯示完整路徑(&F)'),
    (English: '&Pause on exceptions'; Localized: '發生例外狀況時暫停(&P)'),
    (English: '&Launch Setup/Uninstall as administrator'; Localized: '以系統管理員身分啟動安裝程式/解除安裝程式(&L)'),
    (English: 'Colori&ze "Compiler Output" view'; Localized: '為「編譯器輸出」檢視加上色彩(&Z)'),
    (English: 'Automatically open %1 files'; Localized: '自動開啟 %1 檔案'),
    (English: 'Automatically show preprocessor output'; Localized: '自動顯示前置處理器輸出'),
    (English: 'Menu &keys:'; Localized: '功能表按鍵(&K)：'),
    (English: 'Automatically reload files'; Localized: '自動重新載入檔案'),
    (English: 'Allow Undo after reload'; Localized: '允許在重新載入後復原'),
    (English: 'Keep new %1 files closed'; Localized: '保持新的 %1 檔案關閉'),
    (English: 'Language:'; Localized: '語言：'),
    (English: ' Inspector '; Localized: ' 檢查器 '),
    (English: ' Editor '; Localized: ' 編輯器 '),
    (English: 'Invoke autoco&mplete automatically'; Localized: '自動叫用自動完成(&M)'),
    (English: 'Use syntax &highlighting'; Localized: '使用語法醒目提示(&H)'),
    (English: 'U&nderline syntax errors'; Localized: '為語法錯誤加上底線(&N)'),
    (English: 'Allow cursor to move beyond &end of lines'; Localized: '允許游標移至行尾之後(&E)'),
    (English: 'Enable section f&olding'; Localized: '啟用區段摺疊(&O)'),
    (English: 'Use tab cha&racter'; Localized: '使用定位字元(&R)'),
    (English: 'Auto &indent mode'; Localized: '自動縮排模式(&I)'),
    (English: 'Show indentation &guides'; Localized: '顯示縮排輔助線(&G)'),
    (English: 'Font:'; Localized: '字型：'),
    (English: 'AaBbXxZz'; Localized: 'AaBbXxZz'),
    (English: '&Change...'; Localized: '變更(&C)...'),
    (English: '&Tab Width:'; Localized: '定位點寬度(&T)：'),
    (English: 'Show &line numbers in gutter'; Localized: '在裝訂邊顯示行號(&L)'),
    (English: 'T&heme:'; Localized: '佈景主題(&H)：'),
    (English: 'Highlight occurrences of current selection'; Localized: '醒目提示目前選取範圍的相符項目'),
    (English: 'Highlight occurrences of current wor&d'; Localized: '醒目提示目前單字的相符項目(&D)'),
    (English: 'Ke&ys:'; Localized: '按鍵(&Y)：'),
    (English: 'Show whitespace'; Localized: '顯示空白字元'),
    (English: 'Smart Home key'; Localized: '智慧 Home 鍵'),
    (English: '&Associate .%1 files with this compiler'; Localized: '將 .%1 檔案與此編譯器產生關聯(&A)'),
    (English: '&Windows registry file (.%1) to import:'; Localized: '要匯入的 Windows 登錄檔 (.%1)(&W)：'),
    (English: 'B&rowse...'; Localized: '瀏覽(&R)...'),
    (English: 'Settings (for all keys and values):'; Localized: '設定 (適用於所有機碼和值)：'),
    (English: 'Also delete keys which are not empty'; Localized: '也刪除非空白的機碼'),
    (English: 'Delete keys which are empty on uninstall'; Localized: '解除安裝時刪除空白的機碼'),
    (English: 'Delete values on uninstall'; Localized: '解除安裝時刪除值'),
    (English: 'Minimum Windows version:'; Localized: '最低 Windows 版本：'),
    (English: 'RTF Editor'; Localized: 'RTF 編輯器'),
    (English: 'New (%1)'; Localized: '新增 (%1)'),
    (English: 'Open (%1)'; Localized: '開啟 (%1)'),
    (English: 'Cut (%1)'; Localized: '剪下 (%1)'),
    (English: 'Copy (%1)'; Localized: '複製 (%1)'),
    (English: 'Paste (%1)'; Localized: '貼上 (%1)'),
    (English: 'Undo (%1)'; Localized: '復原 (%1)'),
    (English: 'Redo (%1)'; Localized: '取消復原 (%1)'),
    (English: 'Bold (%1)'; Localized: '粗體 (%1)'),
    (English: 'Italic (%1)'; Localized: '斜體 (%1)'),
    (English: 'Underline (%1)'; Localized: '底線 (%1)'),
    (English: '&Bold'; Localized: '粗體(&B)'),
    (English: '&Italic'; Localized: '斜體(&I)'),
    (English: '&Underline'; Localized: '底線(&U)'),
    (English: '&Font...'; Localized: '字型(&F)...'),
    (English: '&Increase Font Size'; Localized: '放大字型(&I)'),
    (English: '&Decrease Font Size'; Localized: '縮小字型(&D)'),
    (English: 'Text &Color...'; Localized: '文字色彩(&C)...'),
    (English: '&Background Color...'; Localized: '背景色彩(&B)...'),
    (English: 'Reset &Colors'; Localized: '重設色彩(&C)'),
    (English: 'Align &Left'; Localized: '靠左對齊(&L)'),
    (English: '&Center'; Localized: '置中(&C)'),
    (English: 'Align &Right'; Localized: '靠右對齊(&R)'),
    (English: 'Bulle&ts'; Localized: '項目符號(&T)'),
    (English: 'Increase &Indent'; Localized: '增加縮排(&I)'),
    (English: 'Decrease Inden&t'; Localized: '減少縮排(&T)'),
    (English: 'Configure Sign Tools'; Localized: '設定簽署工具'),
    (English: ' Sign Tools '; Localized: ' 簽署工具 '),
    (English: '&Add...'; Localized: '新增(&A)...'),
    (English: '&Edit...'; Localized: '編輯(&E)...'),
    (English: 'Be notified by e-mail of new Inno Setup releases'; Localized: '在 Inno Setup 發行新版本時透過電子郵件接收通知'),
    (English: 'Subscribe'; Localized: '訂閱'),
    (English: ' New file '; Localized: ' 新增檔案 '),
    (English: 'Create a new &empty script file'; Localized: '建立新的空白指令碼檔案(&E)'),
    (English: 'Create a new script file using the &Script Wizard'; Localized: '使用指令碼精靈建立新的指令碼檔案(&S)'),
    (English: ' Open file '; Localized: ' 開啟檔案 '),
    (English: 'Open an e&xisting script file'; Localized: '開啟現有的指令碼檔案(&X)'),
    (English: '&Don''t show this dialog again'; Localized: '不要再顯示此對話方塊(&D)'),
    (English: 'Script Wizard File'; Localized: '指令碼精靈檔案'),
    (English: 'bold'; Localized: '粗體'),
    (English: ' = required'; Localized: ' = 必填'),
    (English: ' Destination '; Localized: ' 目的地 '),
    (English: 'Destination &base folder:'; Localized: '目的基底資料夾(&B)：'),
    (English: 'Destination &subfolder:'; Localized: '目的子資料夾(&S)：'),
    (English: 'Destination &name:'; Localized: '目的名稱(&N)：'),
    (English: ' Source '; Localized: ' 來源 '),
    (English: '&Source file or folder:'; Localized: '來源檔案或資料夾(&S)：'),
    (English: '&Recurse subfolders'; Localized: '遞迴子資料夾(&R)'),
    (English: '&Include empty subfolders'; Localized: '包含空白子資料夾(&I)'),
    (English: '&Extract archive'; Localized: '解壓縮壓縮檔(&E)'),
    (English: 'Welcome to the %1'; Localized: '歡迎使用 %1'),
    (English: 'This wizard will guide you through the process of creating a new Inno Setup script file. The results will be used to generate a new script file which can be compiled directly or saved on disk for later use.%n%nNot all features of Inno Setup are covered by this wizard. See the documentation for details on creating Inno Setup script files.%n%nClick Next to continue, or Cancel to exit this wizard.'; Localized: '此精靈將引導您完成建立新 Inno Setup 指令碼檔案的程序。其結果將用於產生新的指令碼檔案，該檔案可直接編譯，或儲存到磁碟供日後使用。%n%n此精靈並未涵蓋 Inno Setup 的所有功能。如需建立 Inno Setup 指令碼檔案的詳細資訊，請參閱文件。%n%n按「下一步」繼續，或按「取消」結束此精靈。'),
    (English: 'Application na&me:'; Localized: '應用程式名稱(&M)：'),
    (English: 'Application &version:'; Localized: '應用程式版本(&V)：'),
    (English: 'Application &publisher:'; Localized: '應用程式發行者(&P)：'),
    (English: 'Application &website:'; Localized: '應用程式網站(&W)：'),
    (English: 'Application folder na&me:'; Localized: '應用程式資料夾名稱(&M)：'),
    (English: 'Application &destination base folder:'; Localized: '應用程式目的基底資料夾(&D)：'),
    (English: 'Other:'; Localized: '其他：'),
    (English: 'Allow user to &change the application folder'; Localized: '允許使用者變更應用程式資料夾(&C)'),
    (English: 'The application doe&sn''t need a folder'; Localized: '應用程式不需要資料夾(&S)'),
    (English: 'Other application &files:'; Localized: '其他應用程式檔案(&F)：'),
    (English: 'Application &main executable file:'; Localized: '應用程式主要可執行檔(&M)：'),
    (English: 'Allow &user to start the application after Setup has finished'; Localized: '允許使用者在安裝程式完成後啟動應用程式(&U)'),
    (English: 'The application doe&sn''t have a main executable file'; Localized: '應用程式沒有主要可執行檔(&S)'),
    (English: 'Application file type na&me:'; Localized: '應用程式檔案類型名稱(&M)：'),
    (English: '&Associate a file type to the main executable'; Localized: '將檔案類型與主要可執行檔產生關聯(&A)'),
    (English: 'Application file type &extension:'; Localized: '應用程式檔案類型副檔名(&E)：'),
    (English: 'Application &Start Menu folder name:'; Localized: '應用程式「開始」功能表資料夾名稱(&S)：'),
    (English: 'Other shortcuts to the main executable:'; Localized: '主要可執行檔的其他捷徑：'),
    (English: 'Allow user to &change the Start Menu folder name'; Localized: '允許使用者變更「開始」功能表資料夾名稱(&C)'),
    (English: 'Allow user to &disable Start Menu folder creation'; Localized: '允許使用者不建立「開始」功能表資料夾(&D)'),
    (English: 'Allow user to create a deskto&p shortcut'; Localized: '允許使用者建立桌面捷徑(&P)'),
    (English: 'Create an &Uninstall shortcut in the Start Menu folder'; Localized: '在「開始」功能表資料夾中建立解除安裝捷徑(&U)'),
    (English: 'Create an &Internet shortcut in the Start Menu folder'; Localized: '在「開始」功能表資料夾中建立網際網路捷徑(&I)'),
    (English: '&Create a Start Menu shortcut but no folder'; Localized: '建立「開始」功能表捷徑但不建立資料夾(&C)'),
    (English: '&License file:'; Localized: '授權檔案(&L)：'),
    (English: '&Information file shown before installation:'; Localized: '安裝前顯示的資訊檔案(&I)：'),
    (English: 'Information file shown &after installation:'; Localized: '安裝後顯示的資訊檔案(&A)：'),
    (English: 'Install mode:'; Localized: '安裝模式：'),
    (English: '&Administrative install mode (install for all users)'; Localized: '系統管理員安裝模式 (為所有使用者安裝)(&A)'),
    (English: 'Non a&dministrative install mode (install for current user only)'; Localized: '非系統管理員安裝模式 (僅為目前使用者安裝)(&D)'),
    (English: 'Allow user to &override the install mode via the command line'; Localized: '允許使用者透過命令列覆寫安裝模式(&O)'),
    (English: 'Ask the user to &choose the install mode at startup'; Localized: '啟動時要求使用者選擇安裝模式(&C)'),
    (English: '&Languages:'; Localized: '語言(&L)：'),
    (English: '&Deselect All'; Localized: '取消全選(&D)'),
    (English: 'Custom compiler output fol&der:'; Localized: '自訂編譯器輸出資料夾(&D)：'),
    (English: 'Compiler output base &file name:'; Localized: '編譯器輸出基底檔案名稱(&F)：'),
    (English: 'Custom Setup &icon file:'; Localized: '自訂安裝程式圖示檔案(&I)：'),
    (English: 'Setup &password:'; Localized: '安裝程式密碼(&P)：'),
    (English: 'Use the password to &encrypt the application files'; Localized: '使用此密碼加密應用程式檔案(&E)'),
    (English: '&Wizard style:'; Localized: '精靈樣式(&W)：'),
    (English: 'You have successfully completed the %1.%n%nTo close this wizard and generate the new script file, click Finish.'; Localized: '您已成功完成 %1。%n%n若要關閉此精靈並產生新的指令碼檔案，請按「完成」。'),
    (English: '&Back'; Localized: '上一步(&B)'),
    (English: '''%s'' is not a valid integer value'; Localized: '「%s」不是有效的整數值'),
    (English: '''%s'' is not a valid integer value for %s type'; Localized: '「%s」不是有效的 %s 類型整數值'),
    (English: '''%s'' is not a valid floating point value'; Localized: '「%s」不是有效的浮點值'),
    (English: '''%d.%d'' is not a valid timestamp'; Localized: '「%d.%d」不是有效的時間戳記'),
    (English: '''%s'' is not a valid GUID value'; Localized: '「%s」不是有效的 GUID 值'),
    (English: 'Invalid argument to time encode'; Localized: '時間編碼的引數無效'),
    (English: 'Invalid argument to date encode'; Localized: '日期編碼的引數無效'),
    (English: 'Out of memory'; Localized: '記憶體不足'),
    (English: 'I/O error %d'; Localized: 'I/O 錯誤 %d'),
    (English: 'File not found'; Localized: '找不到檔案'),
    (English: 'Invalid filename'; Localized: '無效的檔案名稱'),
    (English: 'Too many open files'; Localized: '開啟的檔案太多'),
    (English: 'File access denied'; Localized: '檔案存取被拒'),
    (English: 'Read beyond end of file'; Localized: '讀取超出檔案結尾'),
    (English: 'Disk full'; Localized: '磁碟已滿'),
    (English: 'Invalid numeric input'; Localized: '無效的數值輸入'),
    (English: 'Division by zero'; Localized: '除以零'),
    (English: 'Range check error'; Localized: '範圍檢查錯誤'),
    (English: 'Integer overflow'; Localized: '整數溢位'),
    (English: 'Invalid floating point operation'; Localized: '無效的浮點運算'),
    (English: 'Floating point division by zero'; Localized: '浮點除以零'),
    (English: 'Floating point overflow'; Localized: '浮點溢位'),
    (English: 'Floating point underflow'; Localized: '浮點反向溢位'),
    (English: 'Invalid pointer operation'; Localized: '無效的指標作業'),
    (English: 'Invalid class typecast'; Localized: '無效的類別轉型'),
    (English: 'Access violation at address %p. %s of address %p'; Localized: '位址 %p 發生存取違規。對位址 %2:p 進行%1:s'),
    (English: 'Access violation'; Localized: '存取違規'),
    (English: 'Stack overflow'; Localized: '堆疊溢位'),
    (English: 'Control-C hit'; Localized: '按下了 Control-C'),
    (English: 'Privileged instruction'; Localized: '特殊權限指令'),
    (English: 'Operation aborted'; Localized: '作業已中止'),
    (English: 'Exception %s in module %s at %p.'#13#10'%s%s'#13#10; Localized: '例外狀況 %s 發生於模組 %s 中的位址 %p。'#13#10'%s%s'#13#10),
    (English: 'Application Error'; Localized: '應用程式錯誤'),
    (English: 'Format ''%s'' invalid or incompatible with argument'; Localized: '格式「%s」無效或與引數不相容'),
    (English: 'No argument for format ''%s'''; Localized: '格式「%s」沒有引數'),
    (English: 'Variant method calls not supported'; Localized: '不支援 Variant 方法呼叫'),
    (English: 'Read'; Localized: '讀取'),
    (English: 'Write'; Localized: '寫入'),
    (English: 'Execution'; Localized: '執行'),
    (English: 'Invalid access'; Localized: '無效的存取'),
    (English: 'Error creating variant or safe array'; Localized: '建立 Variant 或安全陣列時發生錯誤'),
    (English: 'Variant or safe array index out of bounds'; Localized: 'Variant 或安全陣列索引超出範圍'),
    (English: 'Variant or safe array is locked'; Localized: 'Variant 或安全陣列已鎖定'),
    (English: 'Invalid variant type conversion'; Localized: '無效的 Variant 類型轉換'),
    (English: 'Invalid variant operation'; Localized: '無效的 Variant 作業'),
    (English: 'Invalid NULL variant operation'; Localized: '無效的 NULL Variant 作業'),
    (English: 'Invalid variant operation (%s%.8x)'#10'%s'; Localized: '無效的 Variant 作業 (%s%.8x)'#10'%s'),
    (English: 'Could not convert variant of type (%s) into type (%s)'; Localized: '無法將類型 (%s) 的 Variant 轉換為類型 (%s)'),
    (English: 'Overflow while converting variant of type (%s) into type (%s)'; Localized: '將類型 (%s) 的 Variant 轉換為類型 (%s) 時發生溢位'),
    (English: 'Variant overflow'; Localized: 'Variant 溢位'),
    (English: 'Invalid argument'; Localized: '無效的引數'),
    (English: 'Invalid variant type'; Localized: '無效的 Variant 類型'),
    (English: 'Operation not supported'; Localized: '不支援此作業'),
    (English: 'Unexpected variant error'; Localized: '未預期的 Variant 錯誤'),
    (English: 'External exception %x'; Localized: '外部例外狀況 %x'),
    (English: 'Assertion failed'; Localized: '判斷提示失敗'),
    (English: 'Interface not supported'; Localized: '不支援這類介面'),
    (English: 'Exception in safecall method'; Localized: 'safecall 方法中發生例外狀況'),
    (English: 'Object lock not owned'; Localized: '未擁有物件鎖定'),
    (English: 'Monitor support function not initialized'; Localized: '尚未初始化 Monitor 支援函式'),
    (English: 'Feature not implemented'; Localized: '功能未實作'),
    (English: 'Method called on disposed object'; Localized: '在已處置的物件上呼叫方法'),
    (English: '%s (%s, line %d)'; Localized: '%s (%s，第 %d 行)'),
    (English: 'Abstract Error'; Localized: '抽象方法錯誤'),
    (English: 'Access violation at address %p in module ''%s'' (offset %x). %s of address %p'; Localized: '位址 %p (模組「%s」，位移 %x) 發生存取違規。對位址 %4:p 進行%3:s'),
    (English: 'System Error.  Code: %d.'#13#10'%s%s'; Localized: '系統錯誤。代碼：%d。'#13#10'%s%s'),
    (English: 'A call to an OS function failed'; Localized: '呼叫 OS 函式失敗'),
    (English: 'Jan'; Localized: '1月'),
    (English: 'Feb'; Localized: '2月'),
    (English: 'Mar'; Localized: '3月'),
    (English: 'Apr'; Localized: '4月'),
    (English: 'May'; Localized: '五月'),
    (English: 'Jun'; Localized: '6月'),
    (English: 'Jul'; Localized: '7月'),
    (English: 'Aug'; Localized: '8月'),
    (English: 'Sep'; Localized: '9月'),
    (English: 'Oct'; Localized: '10月'),
    (English: 'Nov'; Localized: '11月'),
    (English: 'Dec'; Localized: '12月'),
    (English: 'January'; Localized: '一月'),
    (English: 'February'; Localized: '二月'),
    (English: 'March'; Localized: '三月'),
    (English: 'April'; Localized: '四月'),
    (English: 'June'; Localized: '六月'),
    (English: 'July'; Localized: '七月'),
    (English: 'August'; Localized: '八月'),
    (English: 'September'; Localized: '九月'),
    (English: 'October'; Localized: '十月'),
    (English: 'November'; Localized: '十一月'),
    (English: 'December'; Localized: '十二月'),
    (English: 'Sun'; Localized: '週日'),
    (English: 'Mon'; Localized: '週一'),
    (English: 'Tue'; Localized: '週二'),
    (English: 'Wed'; Localized: '週三'),
    (English: 'Thu'; Localized: '週四'),
    (English: 'Fri'; Localized: '週五'),
    (English: 'Sat'; Localized: '週六'),
    (English: 'Sunday'; Localized: '星期日'),
    (English: 'Monday'; Localized: '星期一'),
    (English: 'Tuesday'; Localized: '星期二'),
    (English: 'Wednesday'; Localized: '星期三'),
    (English: 'Thursday'; Localized: '星期四'),
    (English: 'Friday'; Localized: '星期五'),
    (English: 'Saturday'; Localized: '星期六'),
    (English: 'Invalid source array'; Localized: '無效的來源陣列'),
    (English: 'Invalid destination array'; Localized: '無效的目的陣列'),
    (English: 'Character index out of bounds (%d)'; Localized: '字元索引超出範圍 (%d)'),
    (English: 'Start index out of bounds (%d)'; Localized: '開始索引超出範圍 (%d)'),
    (English: 'Invalid count (%d)'; Localized: '無效的計數 (%d)'),
    (English: 'Invalid destination index (%d)'; Localized: '無效的目的索引 (%d)'),
    (English: 'Invalid code page'; Localized: '無效的字碼頁'),
    (English: 'No mapping for the Unicode character exists in the target multi-byte code page'; Localized: '目標多位元組字碼頁中沒有此 Unicode 字元的對應'),
    (English: 'Invalid StringBaseIndex'; Localized: '無效的 StringBaseIndex'),
    (English: '''%s'' is not a valid %s color value'; Localized: '「%s」不是有效的 %s 色彩值'),
    (English: 'Ancestor for ''%s'' not found'; Localized: '找不到「%s」的祖系'),
    (English: 'Cannot assign a %s to a %s'; Localized: '無法將 %s 指派給 %s'),
    (English: 'Bits index out of range'; Localized: 'Bits 索引超出範圍'),
    (English: 'Can''t write to a read-only resource stream'; Localized: '無法寫入唯讀資源資料流'),
    (English: '''''%s'''' expected'; Localized: '應為「%s」'),
    (English: 'CheckSynchronize called from thread $%x, which is NOT the main thread'; Localized: '從執行緒 $%x 呼叫了 CheckSynchronize，但該執行緒不是主執行緒'),
    (English: 'Class %s not found'; Localized: '找不到類別 %s'),
    (English: 'A class named %s already exists'; Localized: '已存在名為 %s 的類別'),
    (English: 'List does not allow duplicates ($0%x)'; Localized: '清單不允許重複項目 ($0%x)'),
    (English: 'A component named %s already exists'; Localized: '已存在名為 %s 的元件'),
    (English: 'String list does not allow duplicates'; Localized: '字串清單不允許重複項目'),
    (English: 'Cannot create file "%s". %s'; Localized: '無法建立檔案「%s」。%s'),
    (English: 'Cannot open file "%s". %s'; Localized: '無法開啟檔案「%s」。%s'),
    (English: 'Identifier expected'; Localized: '應為識別項'),
    (English: 'Invalid binary value'; Localized: '無效的二進位值'),
    (English: 'Invalid stream format'; Localized: '無效的資料流格式'),
    (English: '''%s'' is an invalid mask at (%d)'; Localized: '「%s」是無效的遮罩，位於 (%d)'),
    (English: '''''%s'''' is not a valid component name'; Localized: '「%s」不是有效的元件名稱'),
    (English: 'Invalid property value'; Localized: '屬性值無效'),
    (English: 'Invalid property path'; Localized: '無效的屬性路徑'),
    (English: 'Invalid data type for ''%s'''; Localized: '「%s」的資料類型無效'),
    (English: 'Invalid string constant'; Localized: '無效的字串常數'),
    (English: 'Line too long'; Localized: '行太長'),
    (English: 'List capacity out of bounds (%d)'; Localized: '清單容量超出範圍 (%d)'),
    (English: 'List count out of bounds (%d)'; Localized: '清單計數超出範圍 (%d)'),
    (English: 'List index out of bounds (%d)'; Localized: '清單索引超出範圍 (%d)'),
    (English: '.  %s range is 0..%d'; Localized: '。%s 的範圍為 0..%d'),
    (English: '.  %s is empty'; Localized: '。%s 為空白'),
    (English: 'Out of memory while expanding memory stream'; Localized: '展開記憶體資料流時記憶體不足'),
    (English: '%s has not been registered as a COM class'; Localized: '%s 尚未註冊為 COM 類別'),
    (English: 'Printer is not currently printing'; Localized: '印表機目前並未列印'),
    (English: 'Number expected'; Localized: '應為數字'),
    (English: 'ANSI or UTF8 encoding expected'; Localized: '應為 ANSI 或 UTF8 編碼'),
    (English: '%s on line %d'; Localized: '%s (第 %d 行)'),
    (English: 'Error reading %s%s%s: %s'; Localized: '讀取 %s%s%s 時發生錯誤：%s'),
    (English: 'Printing in progress'; Localized: '正在列印'),
    (English: 'Stream read error'; Localized: '資料流讀取錯誤'),
    (English: 'Property is read-only'; Localized: '屬性為唯讀'),
    (English: 'Failed to create key %s'; Localized: '建立登錄機碼 %s 失敗'),
    (English: 'Failed to get data for ''%s'''; Localized: '取得「%s」的資料失敗'),
    (English: 'Failed to set data for ''%s'''; Localized: '設定「%s」的資料失敗'),
    (English: 'Resource %s not found'; Localized: '找不到資源 %s'),
    (English: '%s.Seek not implemented'; Localized: '未實作 %s.Seek'),
    (English: 'Operation not allowed on sorted list'; Localized: '已排序的清單不允許此作業'),
    (English: 'String expected'; Localized: '應為字串'),
    (English: '%s expected'; Localized: '應為 %s'),
    (English: '%s not in a class registration group'; Localized: '%s 不在類別註冊群組中'),
    (English: 'Property %s does not exist'; Localized: '屬性 %s 不存在'),
    (English: 'Stream write error'; Localized: '資料流寫入錯誤'),
    (English: 'Thread creation error: %s'; Localized: '執行緒建立錯誤：%s'),
    (English: 'Thread Error: %s (%d)'; Localized: '執行緒錯誤：%s (%d)'),
    (English: 'Cannot terminate an externally created thread'; Localized: '無法終止外部建立的執行緒'),
    (English: 'Cannot wait for an externally created thread'; Localized: '無法等候外部建立的執行緒'),
    (English: 'Cannot call Start on a running or suspended thread'; Localized: '無法在執行中或已暫停的執行緒上呼叫 Start'),
    (English: 'Parameter %s cannot be nil'; Localized: '參數 %s 不可為 nil'),
    (English: 'Parameter %s cannot be a negative value'; Localized: '參數 %s 不可為負值'),
    (English: 'Invalid characters in path'; Localized: '路徑中有無效的字元'),
    (English: 'Invalid characters in search pattern'; Localized: '搜尋模式中有無效的字元'),
    (English: 'Path is empty'; Localized: '路徑為空白'),
    (English: 'Search pattern is empty'; Localized: '搜尋模式為空白'),
    (English: 'The specified path is too long'; Localized: '指定的路徑太長'),
    (English: 'The specified path was not found'; Localized: '找不到指定的路徑'),
    (English: 'The path format is not supported'; Localized: '不支援此路徑格式'),
    (English: 'No help viewer that supports filters'; Localized: '沒有支援篩選的說明檢視器'),
    (English: 'String index out of range (%d).  Must be >= %d and <= %d'; Localized: '字串索引超出範圍 (%d)。必須 >= %d 且 <= %d'),
    (English: 'Invalid UTF32 character value.  Must be >= 0 and <= $10FFFF, excluding surrogate pair ranges'; Localized: '無效的 UTF32 字元值。必須 >= 0 且 <= $10FFFF，代理字組範圍除外'),
    (English: 'High surrogate char without a following low surrogate char at index: %d. Check that the string is encoded properly'; Localized: '索引 %d 處的高代理字元後面沒有低代理字元。請檢查字串的編碼是否正確'),
    (English: 'Low surrogate char without a preceding high surrogate char at index: %d. Check that the string is encoded properly'; Localized: '索引 %d 處的低代理字元前面沒有高代理字元。請檢查字串的編碼是否正確'),
    (English: 'Source and Destination arrays must not be the same'; Localized: '來源與目的陣列不可相同'),
    (English: 'SpinCount out of range. Must be between 0 and %d'; Localized: 'SpinCount 超出範圍。必須介於 0 和 %d 之間'),
    (English: 'No context-sensitive help installed'; Localized: '未安裝內容相關說明'),
    (English: 'No help found for context %d'; Localized: '找不到內容識別碼為 %d 的說明'),
    (English: 'Unable to open Index'; Localized: '無法開啟索引'),
    (English: 'Unable to open Search'; Localized: '無法開啟搜尋'),
    (English: 'Unable to find a Table of Contents'; Localized: '找不到目錄'),
    (English: 'No topic-based help system installed'; Localized: '未安裝主題式說明系統'),
    (English: 'No help found for %s'; Localized: '找不到 %s 的說明'),
    (English: 'Argument out of range'; Localized: '引數超出範圍'),
    (English: 'Argument must not be nil'; Localized: '引數不可為 nil'),
    (English: 'Item not found'; Localized: '找不到項目'),
    (English: 'Duplicates not allowed'; Localized: '不允許重複'),
    (English: 'Insufficient RTTI available to support this operation'; Localized: '可用的 RTTI 不足，無法支援此作業'),
    (English: 'Parameter count mismatch'; Localized: '參數計數不符'),
    (English: 'Parameter count exceeded'; Localized: '參數計數超出上限'),
    (English: 'Type ''%s'' is not declared in the interface section of a unit'; Localized: '類型「%s」未在單元的 interface 區段中宣告'),
    (English: 'VAR and OUT arguments must match parameter type exactly'; Localized: 'VAR 和 OUT 引數必須與參數類型完全相符'),
    (English: 'Property ''%s'' is read-only'; Localized: '屬性「%s」為唯讀'),
    (English: 'Property ''%s'' is write-only'; Localized: '屬性「%s」為唯寫'),
    (English: 'RTTI objects cannot be manually destroyed by application code'; Localized: '應用程式程式碼不可手動銷毀 RTTI 物件'),
    (English: '%s (Version %d.%d, Build %d, %5:s)'; Localized: '%s (版本 %d.%d，組建 %d，%5:s)'),
    (English: '%s Service Pack %4:d (Version %1:d.%2:d, Build %3:d, %5:s)'; Localized: '%s Service Pack %4:d (版本 %1:d.%2:d，組建 %3:d，%5:s)'),
    (English: '32-bit Edition'; Localized: '32 位元版本'),
    (English: '64-bit Edition'; Localized: '64 位元版本'),
    (English: 'Windows'; Localized: 'Windows'),
    (English: 'Windows Vista'; Localized: 'Windows Vista'),
    (English: 'Windows Server 2008'; Localized: 'Windows Server 2008'),
    (English: 'Windows 7'; Localized: 'Windows 7'),
    (English: 'Windows Server 2008 R2'; Localized: 'Windows Server 2008 R2'),
    (English: 'Windows 2000'; Localized: 'Windows 2000'),
    (English: 'Windows XP'; Localized: 'Windows XP'),
    (English: 'Windows Server 2003'; Localized: 'Windows Server 2003'),
    (English: 'Windows Server 2003 R2'; Localized: 'Windows Server 2003 R2'),
    (English: 'Windows Server 2012'; Localized: 'Windows Server 2012'),
    (English: 'Windows Server 2012 R2'; Localized: 'Windows Server 2012 R2'),
    (English: 'Windows Server 2016'; Localized: 'Windows Server 2016'),
    (English: 'Windows Server 2019'; Localized: 'Windows Server 2019'),
    (English: 'Windows Server 2022'; Localized: 'Windows Server 2022'),
    (English: 'Windows 8'; Localized: 'Windows 8'),
    (English: 'Windows 8.1'; Localized: 'Windows 8.1'),
    (English: 'Windows 10'; Localized: 'Windows 10'),
    (English: 'Windows 11'; Localized: 'Windows 11'),
    (English: 'Cannot create instance of class %s'; Localized: '無法建立類別 %s 的執行個體'),
    (English: 'Observer is not supported'; Localized: '不支援觀察者'),
    (English: 'Cannot have multiple single cast observers added to the observers collection'; Localized: '觀察者集合中不可加入多個單點傳送觀察者'),
    (English: 'The object does not implement the observer interface'; Localized: '物件未實作觀察者介面'),
    (English: 'No single cast observer with ID %d was added to the observer collection'; Localized: '觀察者集合中未加入 ID 為 %d 的單點傳送觀察者'),
    (English: 'No multi cast observer with ID %d was added to the observer collection'; Localized: '觀察者集合中未加入 ID 為 %d 的多點傳送觀察者'),
    (English: 'Observer is not available'; Localized: '觀察者無法使用'),
    (English: 'SHA2: Cannot update a finalized hash'; Localized: 'SHA2：無法更新已完成的雜湊'),
    (English: 'Must wait on at least one event'; Localized: '必須等候至少一個事件'),
    (English: 'Cannot call BeginInvoke on a TComponent in the process of destruction'; Localized: '無法在正在銷毀的 TComponent 上呼叫 BeginInvoke'),
    (English: 'OLE error %.8x'; Localized: 'OLE 錯誤 %.8x'),
    (English: 'Method ''%s'' not supported by automation object'; Localized: '自動化物件不支援方法「%s」'),
    (English: 'Variant does not reference an automation object'; Localized: 'Variant 未參考自動化物件'),
    (English: 'Dispatch methods do not support more than 64 parameters'; Localized: '分派方法不支援超過 64 個參數'),
    (English: 'A regular expression specified in RegEx is required'; Localized: '需要在 RegEx 中指定規則運算式'),
    (English: 'Error in regular expression at offset %d: %s'; Localized: '規則運算式位移 %d 處發生錯誤：%s'),
    (English: 'Successful match required'; Localized: '需要成功的比對'),
    (English: 'Index out of bounds (%d)'; Localized: '索引超出範圍 (%d)'),
    (English: 'Bitmap image is not valid'; Localized: '點陣圖影像無效'),
    (English: 'Icon image is not valid'; Localized: '圖示影像無效'),
    (English: 'Metafile is not valid'; Localized: '中繼檔無效'),
    (English: 'Invalid pixel format'; Localized: '無效的像素格式'),
    (English: 'Invalid image'; Localized: '無效的影像'),
    (English: 'Scan line index out of range'; Localized: '掃描線索引超出範圍'),
    (English: 'Cannot change the size of an icon'; Localized: '無法變更圖示的大小'),
    (English: 'Cannot change the size of a WIC Image'; Localized: '無法變更 WIC 影像的大小'),
    (English: 'Unsupported clipboard format'; Localized: '不支援的剪貼簿格式'),
    (English: 'Unsupported stream format'; Localized: '不支援的資料流格式'),
    (English: 'Out of system resources'; Localized: '系統資源不足'),
    (English: 'Canvas does not allow drawing'; Localized: '畫布不允許繪圖'),
    (English: 'Text format flag ''%s'' not supported'; Localized: '不支援文字格式旗標「%s」'),
    (English: 'Invalid image frame index %d: there are %d frames (0-%d)'; Localized: '無效的影像畫面格索引 %d：共有 %d 個畫面格 (0-%d)'),
    (English: 'Invalid image size'; Localized: '無效的影像大小'),
    (English: 'Invalid ImageList'; Localized: '無效的 ImageList'),
    (English: 'Invalid ImageList Index'; Localized: '無效的 ImageList 索引'),
    (English: 'Failed to read ImageList data from stream'; Localized: '從資料流讀取 ImageList 資料失敗'),
    (English: 'Failed to write ImageList data to stream'; Localized: '將 ImageList 資料寫入資料流失敗'),
    (English: 'Error creating window device context'; Localized: '建立視窗裝置內容時發生錯誤'),
    (English: 'Error creating window class'; Localized: '建立視窗類別時發生錯誤'),
    (English: 'Cannot focus a disabled or invisible window'; Localized: '無法聚焦已停用或不可見的視窗'),
    (English: 'Control ''%s'' has no parent window'; Localized: '控制項「%s」沒有父視窗'),
    (English: '. Path:'#13#10'%s'; Localized: '。路徑：'#13#10'%s'),
    (English: 'Parent given is not a parent of ''%s'''; Localized: '指定的父項不是「%s」的父項'),
    (English: 'Cannot hide an MDI Child Form'; Localized: '無法隱藏 MDI 子表單'),
    (English: 'Cannot change Visible in OnShow or OnHide'; Localized: '無法在 OnShow 或 OnHide 中變更 Visible'),
    (English: 'Cannot make a visible window modal'; Localized: '無法將可見的視窗設為強制回應'),
    (English: 'Scrollbar property out of range'; Localized: '捲軸屬性超出範圍'),
    (English: '%s property out of range'; Localized: '%s 屬性超出範圍'),
    (English: 'Check state can only be set when CheckBoxes is True'; Localized: '只有當 CheckBoxes 為 True 時才能設定核取狀態'),
    (English: 'Check state incompatible with treeview''s CheckStyles'; Localized: '核取狀態與樹狀檢視的 CheckStyles 不相容'),
    (English: 'Menu index out of range'; Localized: '功能表索引超出範圍'),
    (English: 'Menu inserted twice'; Localized: '功能表被插入兩次'),
    (English: 'Sub-menu is not in menu'; Localized: '子功能表不在功能表中'),
    (English: 'Not enough timers available'; Localized: '可用的計時器不足'),
    (English: 'Printer index out of range'; Localized: '印表機索引超出範圍'),
    (English: 'Printer selected is not valid'; Localized: '選取的印表機無效'),
    (English: '%s on %s'; Localized: '%s (%s)'),
    (English: 'GroupIndex cannot be less than a previous menu item''s GroupIndex'; Localized: 'GroupIndex 不可小於前一個功能表項目的 GroupIndex'),
    (English: 'Cannot create form. No MDI forms are currently active'; Localized: '無法建立表單。目前沒有使用中的 MDI 表單'),
    (English: 'Can only modify an image if it contains a bitmap'; Localized: '只有當影像包含點陣圖時才能修改'),
    (English: 'A control cannot have itself as its parent'; Localized: '控制項不可以自己作為父項'),
    (English: 'Control ''%s'' is used on a not main thread'; Localized: '控制項「%s」在非主執行緒上使用'),
    (English: '&Yes'; Localized: '是(&Y)'),
    (English: '&No'; Localized: '否(&N)'),
    (English: '&Close'; Localized: '關閉(&C)'),
    (English: '&Ignore'; Localized: '略過(&I)'),
    (English: '&Retry'; Localized: '重試(&R)'),
    (English: '&All'; Localized: '全部(&A)'),
    (English: 'Cannot drag a form'; Localized: '無法拖曳表單'),
    (English: 'Metafiles'; Localized: '中繼檔'),
    (English: 'Enhanced Metafiles'; Localized: '增強型中繼檔'),
    (English: 'Icons'; Localized: '圖示'),
    (English: 'Bitmaps'; Localized: '點陣圖'),
    (English: 'TIFF Images'; Localized: 'TIFF 影像'),
    (English: 'Warning'; Localized: '警告'),
    (English: 'Error'; Localized: '錯誤'),
    (English: 'Information'; Localized: '資訊'),
    (English: 'Confirm'; Localized: '確認'),
    (English: '&Abort'; Localized: '中止(&A)'),
    (English: 'N&o to All'; Localized: '全部皆否(&O)'),
    (English: 'Yes to &All'; Localized: '全部皆是(&A)'),
    (English: 'BkSp'; Localized: 'BkSp'),
    (English: 'Tab'; Localized: 'Tab'),
    (English: 'Esc'; Localized: 'Esc'),
    (English: 'Enter'; Localized: 'Enter'),
    (English: 'Space'; Localized: 'Space'),
    (English: 'PgUp'; Localized: 'PgUp'),
    (English: 'PgDn'; Localized: 'PgDn'),
    (English: 'End'; Localized: 'End'),
    (English: 'Home'; Localized: 'Home'),
    (English: 'Left'; Localized: 'Left'),
    (English: 'Up'; Localized: 'Up'),
    (English: 'Right'; Localized: 'Right'),
    (English: 'Down'; Localized: 'Down'),
    (English: 'Ins'; Localized: 'Ins'),
    (English: 'Del'; Localized: 'Del'),
    (English: 'Value must be between %d and %d'; Localized: '值必須介於 %d 和 %d 之間'),
    (English: 'Unable to insert a line'; Localized: '無法插入行'),
    (English: 'Invalid clipboard format'; Localized: '無效的剪貼簿格式'),
    (English: 'Clipboard does not support Icons'; Localized: '剪貼簿不支援圖示'),
    (English: 'Cannot open clipboard: %s'; Localized: '無法開啟剪貼簿：%s'),
    (English: 'Text exceeds memo capacity'; Localized: '文字超出 Memo 控制項的容量'),
    (English: 'Operation not supported on selected printer'; Localized: '選取的印表機不支援此作業'),
    (English: 'There is no default printer currently selected'; Localized: '目前未選取預設印表機'),
    (English: 'Menu ''%s'' is already being used by another form'; Localized: '功能表「%s」已由另一個表單使用'),
    (English: 'Other'; Localized: '其他'),
    (English: 'Docked control must have a name'; Localized: '已停駐的控制項必須有名稱'),
    (English: 'Error removing control from dock tree'; Localized: '從停駐樹移除控制項時發生錯誤'),
    (English: ' - Dock zone not found'; Localized: ' - 找不到停駐區域'),
    (English: ' - Dock zone has no control'; Localized: ' - 停駐區域沒有控制項'),
    (English: 'Error loading dock zone from the stream. Expecting version %d, but found %d.'; Localized: '從資料流載入停駐區域時發生錯誤。應為版本 %d，但找到的是版本 %d。'),
    (English: 'Multiselect mode must be on for this feature'; Localized: '此功能必須開啟多重選取模式'),
    (English: 'Length of value array must be >= length of prompt array'; Localized: '值陣列的長度必須 >= 提示陣列的長度'),
    (English: 'Prompt array must not be empty'; Localized: '提示陣列不可為空白'),
    (English: '&Username'; Localized: '使用者名稱(&U)'),
    (English: '&Password'; Localized: '密碼(&P)'),
    (English: '&Domain'; Localized: '網域(&D)'),
    (English: 'Login'; Localized: '登入'),
    (English: 'Expand'; Localized: '展開'),
    (English: 'Separator'; Localized: '分隔符號'),
    (English: 'Error setting %s.Count'; Localized: '設定 %s.Count 時發生錯誤'),
    (English: 'Listbox (%s) style must be virtual in order to set Count'; Localized: '清單方塊 (%s) 的樣式必須為虛擬才能設定 Count'),
    (English: 'No OnGetItem event handler assigned'; Localized: '未指派 OnGetItem 事件處理常式'),
    (English: 'ANSI'; Localized: 'ANSI'),
    (English: 'ASCII'; Localized: 'ASCII'),
    (English: 'Unicode'; Localized: 'Unicode'),
    (English: 'Big Endian Unicode'; Localized: 'Big Endian Unicode'),
    (English: 'UTF-8'; Localized: 'UTF-8'),
    (English: 'UTF-7'; Localized: 'UTF-7'),
    (English: 'Cannot remove shell notification icon'; Localized: '無法移除殼層通知圖示'),
    (English: '%s requires Windows Vista or later'; Localized: '%s 需要 Windows Vista 或更新版本'),
    (English: 'Button%d'; Localized: '按鈕 %d'),
    (English: 'RadioButton%d'; Localized: '選項按鈕 %d'),
    (English: 'Caption cannot be empty'; Localized: '按鈕文字不可為空白'),
    (English: 'Invalid canvas operation'; Localized: '無效的畫布作業'),
    (English: '%s has no owner'; Localized: '%s 沒有擁有者'),
    (English: 'Source and destination require the same owner'; Localized: '來源與目的需要相同的擁有者'),
    (English: '%s cannot be owned by a different canvas'; Localized: '%s 不可由不同的畫布擁有'),
    (English: 'Not a solid color brush'; Localized: '不是純色筆刷'),
    (English: 'Invalid brush style'; Localized: '無效的筆刷樣式'),
    (English: 'Unable to load style ''%s'''; Localized: '無法載入樣式「%s」'),
    (English: 'Unable to load styles: %s'; Localized: '無法載入樣式：%s'),
    (English: 'Style ''%s'' already registered'; Localized: '樣式「%s」已註冊'),
    (English: 'Style class ''%s'' already registered'; Localized: '樣式類別「%s」已註冊'),
    (English: 'Style ''%s'' not found'; Localized: '找不到樣式「%s」'),
    (English: 'Style class ''%s'' not found'; Localized: '找不到樣式類別「%s」'),
    (English: 'Invalid style format'; Localized: '無效的樣式格式'),
    (English: 'VCL Style File'; Localized: 'VCL 樣式檔案'),
    (English: 'Class ''%s'' is already registered for ''%s'''; Localized: '類別「%s」已為「%s」註冊'),
    (English: 'Class ''%s'' is not registered for ''%s'''; Localized: '類別「%s」未為「%s」註冊'),
    (English: '%s parameter cannot be nil'; Localized: '%s 參數不可為 nil'),
    (English: 'A StyleHook class has not been registered for %s'; Localized: '尚未為 %s 註冊 StyleHook 類別'),
    (English: 'Feature not supported by this style'; Localized: '此樣式不支援該功能'),
    (English: 'Cannot call BeginInvoke on a control with no parent or window handle'; Localized: '無法在沒有父項或視窗控制代碼的控制項上呼叫 BeginInvoke'),
    (English: 'CardPanel card index is out of range'; Localized: 'CardPanel 卡片索引超出範圍'),
    (English: 'CardPanel.ActiveCard cannot be nil'; Localized: 'CardPanel.ActiveCard 不可為 nil'),
    (English: 'Invalid index'; Localized: '無效的索引'),
    (English: 'Unable to insert an item'; Localized: '無法插入項目'),
    (English: 'Invalid owner'; Localized: '無效的擁有者'),
    (English: 'RichEdit line insertion error'; Localized: 'RichEdit 插入行錯誤'),
    (English: 'Failed to Load Stream'; Localized: '載入資料流失敗'),
    (English: 'Failed to Save Stream'; Localized: '儲存資料流失敗'),
    (English: '%s is already associated with %s'; Localized: '%s 已與 %s 產生關聯'),
    (English: 'This control requires version 4.70 or greater of COMCTL32.DLL'; Localized: '此控制項需要 COMCTL32.DLL 4.70 版或更新版本'),
    (English: 'ListView item can be added only when OwnerData is False.  Use OnData instead.'; Localized: '只有當 OwnerData 為 False 時才能新增 ListView 項目。請改用 OnData。'),
    (English: 'This "Portable Network Graphics" image is not valid because it contains invalid pieces of data (crc error)'; Localized: '此「Portable Network Graphics」影像無效，因為它包含無效的資料片段 (CRC 錯誤)'),
    (English: 'The "Portable Network Graphics" image could not be loaded because one of its main piece of data (ihdr) might be corrupted'; Localized: '無法載入此「Portable Network Graphics」影像，因為其主要資料區塊之一 (IHDR) 可能已損毀'),
    (English: 'This "Portable Network Graphics" image is invalid because it has missing image parts.'; Localized: '此「Portable Network Graphics」影像無效，因為它缺少部分影像資料。'),
    (English: 'Could not decompress the image because it contains invalid compressed data.'#13#10' Description: '; Localized: '無法解壓縮此影像，因為它包含無效的壓縮資料。'#13#10' 說明： '),
    (English: 'The "Portable Network Graphics" image contains an invalid palette.'; Localized: '此「Portable Network Graphics」影像包含無效的調色盤。'),
    (English: 'The file being read is not a valid "Portable Network Graphics" image because it contains an invalid header. This file may be corrupted, try obtaining it again'; Localized: '正在讀取的檔案不是有效的「Portable Network Graphics」影像，因為它包含無效的標頭。此檔案可能已損毀，請嘗試重新取得'),
    (English: 'This "Portable Network Graphics" image is not supported or it might be invalid.'#13#10'(IHDR chunk is not the first)'; Localized: '不支援此「Portable Network Graphics」影像，或者它可能無效。'#13#10'(IHDR 區塊不是第一個)'),
    (English: 'This "Portable Network Graphics" image is not supported because either its width or height exceeds the maximum size of 65535 pixels.'; Localized: '不支援此「Portable Network Graphics」影像，因為其寬度或高度超過 65535 像素的上限。'),
    (English: 'There is no such palette entry.'; Localized: '沒有這個調色盤項目。'),
    (English: 'This "Portable Network Graphics" image contains an unknown critical part which could not be decoded.'; Localized: '此「Portable Network Graphics」影像包含無法解碼的未知關鍵區塊。'),
    (English: 'This "Portable Network Graphics" image is encoded with an unknown compression scheme which could not be decoded.'; Localized: '此「Portable Network Graphics」影像使用無法解碼的未知壓縮配置進行編碼。'),
    (English: 'This "Portable Network Graphics" image uses an unknown interlace scheme which could not be decoded.'; Localized: '此「Portable Network Graphics」影像使用無法解碼的未知交錯配置。'),
    (English: 'This "Portable Network Graphics" image uses an unknown color type which could not be decoded.'; Localized: '此「Portable Network Graphics」影像使用無法解碼的未知色彩類型。'),
    (English: 'The chunks must be compatible to be assigned.'; Localized: '區塊必須相容才能指派。'),
    (English: 'This "Portable Network Graphics" image is invalid because the decoder found an unexpected end of the file.'; Localized: '此「Portable Network Graphics」影像無效，因為解碼器發現未預期的檔案結尾。'),
    (English: 'This "Portable Network Graphics" image contains no data.'; Localized: '此「Portable Network Graphics」影像不包含任何資料。'),
    (English: 'The program tried to add a existent critical chunk to the current image which is not allowed.'; Localized: '程式嘗試將已存在的關鍵區塊加入目前的影像，這是不允許的。'),
    (English: 'It''s not allowed to add a new chunk because the current image is invalid.'; Localized: '不允許加入新的區塊，因為目前的影像無效。'),
    (English: 'Some operation could not be performed because the system is out of resources. Close some windows and try again.'; Localized: '由於系統資源不足，某些作業無法執行。請關閉一些視窗，然後再試一次。'),
    (English: 'Setting bit transparency color is not allowed for png images containing alpha value for each pixel (COLOR_RGBALPHA and COLOR_GRAYSCALEALPHA)'; Localized: '不允許為每個像素都包含 Alpha 值的 PNG 影像 (COLOR_RGBALPHA 和 COLOR_GRAYSCALEALPHA) 設定位元透明色彩'),
    (English: 'This operation is not valid because the current image contains no valid header.'; Localized: '此作業無效，因為目前的影像沒有有效的標頭。'),
    (English: 'The new size provided for image resizing is invalid.'; Localized: '為調整影像大小提供的新大小無效。'),
    (English: 'The "Portable Network Graphics" image could not be loaded because it uses an invalid image bit depth.'; Localized: '無法載入此「Portable Network Graphics」影像，因為它使用無效的影像位元深度。'),
    (English: 'Exception '; Localized: '例外狀況 '),
    (English: 'Data cannot be accessed as %s'; Localized: '無法以 %s 存取資料'),
    (English: 'Check'; Localized: '核取'),
    (English: 'Uncheck'; Localized: '取消核取'),
    (English: 'Collapse'; Localized: '摺疊'),
    (English: 'Obsolete'; Localized: '已淘汰'),
    (English: 'Custom Messages'; Localized: '自訂訊息'),
    (English: 'Language Options'; Localized: '語言選項'),
    (English: 'Messages'; Localized: '訊息'),
    (English: 'Component'; Localized: '元件'),
    (English: 'Directory'; Localized: '資料夾'),
    (English: 'File'; Localized: '檔案'),
    (English: 'Icon'; Localized: '圖示'),
    (English: 'INI'; Localized: 'INI'),
    (English: 'Delete'; Localized: '刪除'),
    (English: 'ISSig Key'; Localized: 'ISSig 金鑰'),
    (English: 'Language'; Localized: '語言'),
    (English: 'Registry'; Localized: '登錄'),
    (English: 'Task'; Localized: '工作'),
    (English: 'Type'; Localized: '類型'),
    (English: 'Appearance'; Localized: '外觀'),
    (English: 'Application Details'; Localized: '應用程式詳細資料'),
    (English: 'Application Directory'; Localized: '應用程式資料夾'),
    (English: 'Applications in Use'; Localized: '使用中的應用程式'),
    (English: 'Compression'; Localized: '壓縮'),
    (English: 'Disk Spanning'; Localized: '磁片分割'),
    (English: 'Installation Pages'; Localized: '安裝頁面'),
    (English: 'Security'; Localized: '安全性'),
    (English: 'Start Menu Folder'; Localized: '「開始」功能表資料夾'),
    (English: 'System Requirements'; Localized: '系統需求'),
    (English: 'Uninstallation'; Localized: '解除安裝'),
    (English: 'User Information'; Localized: '使用者資訊'),
    (English: 'Version Information'; Localized: '版本資訊'),
    (English: 'Common'; Localized: '一般'));

implementation

end.
