unit IDE.LocalizeFunc.Russian;

{
  Inno Setup
  Copyright (C) 1997-2026 Jordan Russell
  Portions by Martijn Laan
  For conditions of distribution and use, see LICENSE.TXT.

  Compiler IDE Russian translations
}

interface

uses
  IDE.LocalizeFunc;

const
  RussianIDETranslations: array [0..1015] of TTranslationPair = (
    (English: 'Command-line usage:'; Localized: 'Использование командной строки:'),
    (English: 'Examples:'; Localized: 'Примеры:'),
    (English: 'script file'; Localized: 'файл сценария'),
    (English: 'wizard name'; Localized: 'имя мастера'),
    (English: 'My script'; Localized: 'Мой сценарий'),
    (English: 'My Script Wizard'; Localized: 'Мой мастер сценариев'),
    (English: 'Could not load %1: %2'; Localized: 'Не удалось загрузить %1: %2'),
    (English: 'Inno Setup Compiler'; Localized: 'Inno Setup Compiler'),
    (English: 'Example scripts...'; Localized: 'Примеры сценариев...'),
    (English: 'More files...'; Localized: 'Другие файлы сценариев...'),
    (English: 'Untitled'; Localized: 'Без названия'),
    (English: 'Preprocessor Output'; Localized: 'Вывод препроцессора'),
    (English: 'Run Parameters'; Localized: 'Параметры командной строки'),
    (English: 'Command-line parameters for %1 and %2:'; Localized: 'Параметры запуска для %1 и %2:'),
    (English: 'Inno Setup Script files'; Localized: 'Сценарии Inno Setup'),
    (English: 'All files'; Localized: 'Все файлы'),
    (English: 'Application files'; Localized: 'Файлы приложений'),
    (English: 'Documentation files'; Localized: 'Файлы документов'),
    (English: 'Rich Text Format files'; Localized: 'Файлы RTF'),
    (English: 'Registry files'; Localized: 'Файлы реестра'),
    (English: 'Icon files'; Localized: 'Файлы значков'),
    (English: 'Image files'; Localized: 'Файлы изображений'),
    (English: 'VCL Styles files'; Localized: 'Файлы стилей VCL'),
    (English: 'Inno Setup Messages files'; Localized: 'Файлы сообщений Inno Setup'),
    (English: 'Public key files'; Localized: 'Файлы публичных ключей'),
    (English: 'Text files'; Localized: 'Текстовые файлы'),
    (English: 'Inno Setup Script Wizard'; Localized: 'Мастер создания сценариев Inno Setup'),
    (English: 'Welcome'; Localized: 'Добро пожаловать'),
    (English: 'Application Information'; Localized: 'Информация о приложении'),
    (English: 'Please specify some basic information about your application.'; Localized: 'Укажите основную информацию о вашем приложении.'),
    (English: 'Application Folder'; Localized: 'Каталог установки'),
    (English: 'Please specify folder information about your application.'; Localized: 'Укажите каталог для установки вашего приложения.'),
    (English: 'Application Files'; Localized: 'Файлы приложения'),
    (English: 'Please specify the files that are part of your application.'; Localized: 'Укажите файлы, входящие в состав вашего приложения.'),
    (English: 'Please specify the source folder.'; Localized: 'Укажите папку с исходными файлами.'),
    (English: 'Should files in subfolders of "%1" also be included?'; Localized: 'Следует ли также добавить все файлы, находящиеся в подпапках "%1"?'),
    (English: 'URL:'; Localized: 'URL:'),
    (English: 'Is the file to download an archive which should be extracted?'; Localized: 'Загружаемый файл - это архив, который нужно распаковать?'),
    (English: 'Name of the file:'; Localized: 'Имя файла:'),
    (English: 'Name of the file (extension should match archive format):'; Localized: 'Имя файла (расширение должно соответствовать формату архива):'),
    (English: 'Approximate size of the file in megabytes:'; Localized: 'Примерный размер файла в МБ:'),
    (English: 'Application File Association'; Localized: 'Ассоциация файлов'),
    (English: 'Please specify which file association should be created for your application.'; Localized: 'Укажите тип файла, который следует связать с вашим приложением.'),
    (English: '%1 File'; Localized: 'Файл %1'),
    (English: 'Application Shortcuts'; Localized: 'Ярлыки приложения'),
    (English: 'Please specify which shortcuts should be created for your application.'; Localized: 'Укажите ярлыки, которые следует создать для вашего приложения.'),
    (English: 'Application Documentation'; Localized: 'Документация приложения'),
    (English: 'Please specify which documentation files should be shown by Setup during installation.'; Localized: 'Укажите файлы документов, которые следует показать в процессе установки.'),
    (English: 'Setup Install Mode'; Localized: 'Режим установки'),
    (English: 'Please specify in which install mode Setup should run.'; Localized: 'Выберите режим запуска программы установки.'),
    (English: 'Application Registry Keys And Values'; Localized: 'Ключи и значения реестра'),
    (English: 'Please specify the registry keys and values that are part of your application.'; Localized: 'Добавьте ключи и значения реестра, связанные с вашим приложением.'),
    (English: 'Setup Languages'; Localized: 'Языковая поддержка'),
    (English: 'Please specify which Setup languages should be included.'; Localized: 'Выберите языки, которые следует добавить в программу установки.'),
    (English: 'Compiler Settings'; Localized: 'Параметры компилятора'),
    (English: 'Please specify some basic compiler settings.'; Localized: 'Укажите основные параметры компилятора.'),
    (English: 'Please specify the folder.'; Localized: 'Выберите папку для вывода файла установки.'),
    (English: 'Wizard Style'; Localized: 'Стиль мастера установки'),
    (English: 'Please specify which wizard style should be used.'; Localized: 'Выберите стиль, используемый мастером установки.'),
    (English: 'Inno Setup Preprocessor'; Localized: 'Препроцессор Inno Setup'),
    (English: 'Please specify whether Inno Setup Preprocessor should be used.'; Localized: 'Укажите, следует ли использовать препроцессор Inno Setup.'),
    (English: 'The %1 can use %2 compiler directives to simplify your script. Although this is not necessary, it will make it easier to manually change the script later.%n%nDo you want the %1 to use %2 compiler directives?'; Localized: '%1 может использовать директивы компилятора %2, что позволит упростить ваш сценарий. Хотя в этом нет особой необходимости, позже будет легче вручную изменить сценарий.%n%nВы хотите, чтобы %1 использовал директивы %2?'),
    (English: '&Yes, use %1 compiler directives'; Localized: 'Д&а, использовать директивы компилятора %1'),
    (English: 'Finished'; Localized: 'Завершено'),
    (English: '&Next'; Localized: '&Далее'),
    (English: '&Finish'; Localized: '&Готово'),
    (English: 'The %1 is not complete. If you quit now, the new script file will not be generated.%n%nExit anyway?'; Localized: '%1 не закончил свою работу. Если сейчас подтвердить выход, то сценарий создан не будет.%n%nВсё равно выйти?'),
    (English: 'Please specify the application name.'; Localized: 'Пожалуйста, введите название приложения.'),
    (English: 'Please specify the application version.'; Localized: 'Пожалуйста, введите версию приложения.'),
    (English: 'Please specify the application destination base folder.'; Localized: 'Пожалуйста, укажите папку установки приложения.'),
    (English: 'Please specify the application folder name.'; Localized: 'Пожалуйста, введите название папки.'),
    (English: 'Please specify the application main executable file.'; Localized: 'Пожалуйста, укажите главный исполняемый файл приложения.'),
    (English: 'The specified application main executable file does not exist.'; Localized: 'Указанный главный исполняемый файл приложения не существует.'),
    (English: 'Please specify the application Start Menu group name.'; Localized: 'Пожалуйста, укажите папку приложения для меню ПУСК.'),
    (English: 'Please specify the destination base folder.'; Localized: 'Пожалуйста, укажите целевую папку установки.'),
    (English: 'Please specify a destination base folder other than the application folder.'; Localized: 'Пожалуйста, укажите целевую папку установки отличную от папки приложения'),
    (English: 'Please specify the destination name.'; Localized: 'Пожалуйста, укажите целевое имя.'),
    (English: 'Please select at least one language.'; Localized: 'Пожалуйста, выберите не менее одного языка поддержки.'),
    (English: '&Source URL:'; Localized: '&Адрес URL:'),
    (English: 'Script generated by the %1.'; Localized: 'Этот сценарий подготовил %1.'),
    (English: 'SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!'; Localized: 'ИНФОРМАЦИЮ О СОЗДАНИИ СЦЕНАРИЕВ СМОТРИТЕ В ДОКУМЕНТАЦИИ INNO SETUP!'),
    (English: 'NOTE: The value of %1 uniquely identifies this application. Do not use the same %1 value in installers for other applications.'; Localized: 'ПРИМЕЧАНИЕ: значение %1 является уникальным идентификатором для этого приложения.%n; Не используйте одно и тоже значение %1 для установки разных приложений.'),
    (English: '(To generate a new GUID, click Tools | Generate GUID inside the IDE.)'; Localized: '(Для создания нового GUID, выберите в меню "Инструменты" пункт "Создать GUID".)'),
    (English: '"%1" specifies that Setup cannot run on anything but x64 and Windows 11 on Arm.'; Localized: '"%1" указывает, что программа установки может работать только на системах х64 и Windows 11 на Arm.'),
    (English: '"%1" requests that the install be done in "64-bit mode" on x64 or Windows 11 on Arm.'; Localized: '"%1" требует выполнения установки в "режиме 64-бит" на системах x64 или Windows 11 на Arm.'),
    (English: 'This means it should use the native 64-bit Program Files directory and the 64-bit view of the registry.'; Localized: 'Это означает, что программа должна использовать собственный 64-разрядный каталог "Program Files" и 64-разрядное представление реестра.'),
    (English: 'Uncomment the following line to use a 64-bit installer.'; Localized: 'Раскомментируйте следующую строку, что использовать 64-разрядный установщик.'),
    (English: 'Use "%1" if all your archives are .%2 files.'; Localized: 'Укажите "%1", если все архивы имеют формат .%2.'),
    (English: 'Use "%1" if all your archives are not password-protected.'; Localized: 'Укажите "%1", если все архивы не защищены паролем.'),
    (English: 'Uncomment the following line to run in non administrative install mode (install for current user only).'; Localized: 'Раскомментируйте следующую строку для запуска инсталлятора в режиме не административной установки (только для текущего пользователя).'),
    (English: 'Remove the following line to run in administrative install mode (install for all users).'; Localized: 'Удалите следующую строку для запуска инсталлятора в режиме административной установки (для всех пользователей).'),
    (English: 'NOTE: Don''t use "%1" on any shared system files.'; Localized: 'ПРИМЕЧАНИЕ: не используйте флаг "%1" для общих системных файлов.'),
    (English: 'NOTE: Use the "%1" flag or the "%2" parameter to verify downloads.'; Localized: 'ПРИМЕЧАНИЕ: используйте флаг "%1" или параметр "%2" для верификации загрузок.'),
    (English: 'Registry data from file %1'; Localized: 'Данные реестра из файла %1'),
    (English: 'COULD NOT IMPORT %1'; Localized: 'НЕ УДАЛОСЬ ИМПОРТИРОВАТЬ %1'),
    (English: 'End of registry data from file %1'; Localized: 'Конец данных реестра из файла %1'),
    (English: 'SOME KEYS FILTERED DUE TO %1 SETTINGS!'; Localized: 'НЕКОТОРЫЕ КЛЮЧИ БЫЛИ ИСКЛЮЧЕНЫ ИЗ-ЗА НАСТРОЕК %1!'),
    (English: 'SOME VALUES WITH UNSUPPORTED TYPES SKIPPED!'; Localized: 'НЕКОТОРЫЕ ЗНАЧЕНИЯ БЫЛИ ПРОПУЩЕНЫ ИЗ-ЗА НЕПОДДЕРЖИВАЕМЫХ ТИПОВ!'),
    (English: 'Would you like to compile the new script now?'; Localized: 'Выполнить компиляцию нового сценария сейчас?'),
    (English: 'My Program'; Localized: 'My Program'),
    (English: 'My Company, Inc.'; Localized: 'My Company, Inc.'),
    (English: 'Application directory'; Localized: 'Папка приложения'),
    (English: 'Program Files directory'; Localized: 'Папка "Program Files"'),
    (English: 'Common Files directory'; Localized: 'Папка "Common Files"'),
    (English: 'Windows directory'; Localized: 'Папка Windows'),
    (English: 'Windows system directory'; Localized: 'Системная папка Windows'),
    (English: 'Setup source directory'; Localized: 'Исходная папка установки'),
    (English: 'System drive root directory'; Localized: 'Корневая папка системного диска'),
    (English: '(Custom)'; Localized: '(По выбору пользователя)'),
    (English: 'Starting compile.%1[%2]'; Localized: 'Запуск компиляции.%1[%2]'),
    (English: 'Finished.%1[%2, %3 elapsed]'; Localized: 'Компиляция завершена.%1[%2, прошло %3]'),
    (English: 'Compile aborted.'; Localized: 'Компиляция прервана.'),
    (English: 'Log size limit reached, list reset.'; Localized: 'Достигнут предел размера журнала, список сброшен.'),
    (English: '%1 started'; Localized: '%1 запущен'),
    (English: 'Terminating process'; Localized: 'Завершение процесса'),
    (English: 'Removing left-over temporary directory: %1'; Localized: 'Очистка временной папки: %1'),
    (English: 'Failed to remove temporary directory'; Localized: 'Не удалось удалить временную папку'),
    (English: '%1 Call Stack'; Localized: 'Стек секции %1'),
    (English: 'Cannot run Setup at this time. Please compile Setup successfully to completion first, with output enabled'; Localized: 'Невозможно запустить процесс установки. Пожалуйста, выполните сначала успешную сборку программы установки с выводом файла.'),
    (English: 'Cannot run Uninstall at this time. Please run Setup successfully to completion first'; Localized: 'Невозможно запустить процесс деинсталляции. Пожалуйста, выполните сначала полную установку.'),
    (English: 'Error executing "%1":%n%n%2: %3'; Localized: 'Ошибка выполнения "%1":%n%n%2: %3'),
    (English: 'Are you sure you want to abort the compile?'; Localized: 'Вы действительно хотите прервать компиляцию?'),
    (English: 'File %1:'; Localized: 'Файл %1:'),
    (English: 'Line %1:'; Localized: 'Строка %1:'),
    (English: 'Compiler Error'; Localized: 'Ошибка компиляции'),
    (English: 'Illegal null character on line %1'; Localized: 'Недопустимый нулевой символ в строке %1'),
    (English: 'Cannot find "%1"'; Localized: 'Не удаётся найти "%1"'),
    (English: 'Invalid regular expression "%1"'; Localized: 'Недопустимое регулярное выражение "%1"'),
    (English: '%1 (%2 hits):'; Localized: '%1 (%2 совпадений):'),
    (English: 'Find "%1" (%2 hits in %3 files)'; Localized: 'Поиск "%1" (%2 совпадений в %3 файлах)'),
    (English: '%1 occurrence(s) replaced.'; Localized: 'Выполнено замен: %1.'),
    (English: 'The .%1 extension was successfully associated for the current user with:%n%2'; Localized: 'Расширение .%1 было успешно связано для текущего пользователя с:%n%2'),
    (English: 'The .%1 extension was successfully associated for all users with:%n%2'; Localized: 'Расширение .%1 было успешно связано для всех пользователей с:%n%2'),
    (English: 'Error creating file association:%n%1 - %2'; Localized: 'Ошибка создания ассоциации файлов:%n%1 - %2'),
    (English: 'Unable to associate for all users without administrative privileges. Do you want to associate only for yourself instead?'; Localized: 'Невозможно выполнить ассоциацию для всех пользователей без административных привилегий. Вы хотите установить ассоциацию только для себя?'),
    (English: 'Associate'; Localized: 'Ассоциация файлов'),
    (English: 'Inno Setup Script'; Localized: 'Сценарий Inno Setup'),
    (English: 'Compi&le'; Localized: '&Компилировать'),
    (English: '&Script has %1'; Localized: '&Сценарий использует %1'),
    (English: 'Script has %1 set'; Localized: 'Сценарий использует %1'),
    (English: 'Invalid file format.'; Localized: 'Недопустимый формат файла.'),
    (English: 'The specified registry file does not exist.'; Localized: 'Указанный файл реестра не существует.'),
    (English: 'Setup'; Localized: 'Setup'),
    (English: 'Your message text.'; Localized: 'Текст сообщения.'),
    (English: 'Enter your text here...'; Localized: 'Введите здесь ваш текст сообщения...'),
    (English: 'Return values'; Localized: ' Возврат '),
    (English: 'Default'; Localized: ' По умолчанию '),
    (English: 'Shield'; Localized: ' Щит '),
    (English: 'Instruction Text'; Localized: 'Инструкция'),
    (English: 'Message Text'; Localized: 'Сообщение'),
    (English: 'user clicked %1'; Localized: 'пользователь нажал %1'),
    (English: 'OK'; Localized: 'ОК'),
    (English: 'Yes'; Localized: 'Да'),
    (English: 'No'; Localized: 'Нет'),
    (English: 'Cancel'; Localized: 'Отмена'),
    (English: 'Retry'; Localized: 'Повторить'),
    (English: 'Ignore'; Localized: 'Пропустить'),
    (English: 'Abort'; Localized: 'Прервать'),
    (English: 'Display a message box'; Localized: 'Вызов диалога сообщения'),
    (English: 'Name of the Sign Tool:'; Localized: 'Введите название:'),
    (English: 'Invalid name.'; Localized: 'Неверный формат имени или оно не указано.'),
    (English: 'Duplicate name.'; Localized: 'Это имя уже используется. Введите другое.'),
    (English: 'Command of the Sign Tool:'; Localized: 'Введите команду:'),
    (English: 'Invalid command.'; Localized: 'Неверный формат команды или она не указана.'),
    (English: '%1 must be an integer value'; Localized: '%1 должно быть целым числом'),
    (English: 'The script cannot be edited because it is read-only'; Localized: 'Сценарий доступен только для чтения и может быть отредактирован'),
    (English: 'Parameter "%1" cannot be browsed for when the "%2" flag is used'; Localized: 'Параметр "%1" невозможно увидеть пока используется флаг "%2"'),
    (English: 'Move to a parameter entry or a key/value or [Code] section'; Localized: 'Перейдите к параметру, ключу/значению или секции [Code]'),
    (English: 'Move to a parameter entry or a non-empty key/value or [Code] section'; Localized: 'Перейдите к параметру, непустому ключу/значению или секции [Code]'),
    (English: 'Select entries of one section type, and no other content'; Localized: 'Выбрать записи только одного типа секции и ничего больше'),
    (English: 'Unspecified directives are hidden because this section occurs more than once'; Localized: 'Неуказанные директивы скрыты, так как этот раздел встречается более одного раза'),
    (English: 'Unspecified directives are hidden because this is not the main script file'; Localized: 'Неуказанные директивы скрыты, так как это не основной файл сценария'),
    (English: 'Routines'; Localized: 'Процедуры и функции'),
    (English: 'Types'; Localized: 'Типы'),
    (English: 'Symbols'; Localized: 'Символы'),
    (English: 'Parameters'; Localized: 'Параметры'),
    (English: 'Locals'; Localized: 'Локальные переменные'),
    (English: 'The generated GUID will be inserted into the editor at the cursor position. Continue?'; Localized: 'Значение GUID будет вставлено в текущей позиции курсора. Продолжить?'),
    (English: 'The generated Pascal script will be inserted into the editor at the cursor position, but the cursor is not in the %1 section. Continue anyway?'; Localized: 'Код Pascal будет вставлен в текущей позиции курсора, но курсор находится вне секции %1. Продолжить?'),
    (English: 'Classic'; Localized: 'Classic'),
    (English: 'Visual Studio / Visual Studio Code'; Localized: 'Visual Studio / Visual Studio Code'),
    (English: 'Classic / Visual Studio'; Localized: 'Classic / Visual Studio'),
    (English: 'Visual Studio Code'; Localized: 'Visual Studio Code'),
    (English: 'Light'; Localized: 'Светлая'),
    (English: 'Dark'; Localized: 'Тёмная'),
    (English: 'The new language will take effect the next time you start Inno Setup Compiler.'; Localized: 'Новые настройки вступят в силу при следующем запуске Inno Setup Compiler.'),
    (English: '&New...'; Localized: '&Новый...'),
    (English: '&New'; Localized: '&Новый'),
    (English: 'Line %1'; Localized: 'Строка %1'),
    (English: '%1: %2'; Localized: '%1: %2'),
    (English: 'Back (%1)'; Localized: 'Назад (%1)'),
    (English: 'Forward (%1)'; Localized: 'Вперёд (%1)'),
    (English: 'Back'; Localized: 'Назад'),
    (English: 'Forward'; Localized: 'Вперед'),
    (English: 'Open'; Localized: 'Открыть'),
    (English: 'Run'; Localized: 'Выполнить'),
    (English: 'Save As'; Localized: 'Сохранить как'),
    (English: 'Font'; Localized: 'Шрифт'),
    (English: 'Text Color'; Localized: 'Цвет текста'),
    (English: 'Background Color'; Localized: 'Цвет фона'),
    (English: 'Ctrl+'; Localized: 'Ctrl+'),
    (English: 'Shift+'; Localized: 'Shift+'),
    (English: 'Alt+'; Localized: 'Alt+'),
    (English: 'Num %1'; Localized: 'Num %1'),
    (English: '(32-bit)'; Localized: '(32-бит)'),
    (English: '[Compiling]'; Localized: '[Компиляция]'),
    (English: '[Running]'; Localized: '[Выполнение]'),
    (English: '[Paused]'; Localized: '[Пауза]'),
    (English: 'Read only'; Localized: 'Чтение'),
    (English: 'Modified'; Localized: 'Изменён'),
    (English: 'Overwrite'; Localized: 'Замена'),
    (English: 'Insert'; Localized: 'Вставка'),
    (English: 'Tabs closed: %1'; Localized: 'Закрытые вкладки: %1'),
    (English: 'Estimated time remaining: %1'; Localized: 'Оставшееся время: %1'),
    (English: 'Average KB/sec: %1'; Localized: 'Скорость Kб/сек: %1'),
    (English: 'There was an error opening the file. Remove it from the list?'; Localized: 'При открытии файла произошла ошибка. Удалить его из списка?'),
    (English: 'The text in the %1 file has changed.%n%nDo you want to save the changes?'; Localized: 'Текст в файле "%1" был изменён.%n%nВы хотите сохранить изменения?'),
    (English: 'Please stop the compile process before performing this command.'; Localized: 'Остановите компиляцию перед выполнением этой команды.'),
    (English: 'A compile is already in progress.'; Localized: 'Процесс компиляции уже запущен.'),
    (English: 'The text in the %1 file has changed and must be saved before compiling.%n%nSave the changes and continue?'; Localized: 'Текст в файле "%1" был изменён и перед компиляцией должен быть сохранён.%n%nСохранить изменения и продолжить?'),
    (English: 'Would you like to save the script before compiling?%n%nIf you answer No, the compiled installation will be placed under your My Documents folder by default.'; Localized: 'Вы хотите сохранить сценарий перед началом компиляции?%n%nПри ответе "Нет" файл установки по умолчанию будет создан в папке "Мои документы".'),
    (English: 'The selected file is an %1 file. Go to its tab instead of opening it as the new main file?'; Localized: 'Выбранный файл является подключаемым файлом "%1". Перейти на вкладку с ним вместо открытия в качестве главного файла сценария?'),
    (English: 'The selected file is not available as a tab. Opening as the new main file instead.'; Localized: 'Выбранный файл недоступен для вкладки. Вместо этого он будет открыт в качестве главного файла сценария.'),
    (English: 'Error creating file (code %1). Could not save file'; Localized: 'Ошибка создания файла (код %1). Не удалось сохранить файл'),
    (English: 'Error creating backup file. Could not save file'; Localized: 'Ошибка создания резервной копии. Не удалось сохранить файл'),
    (English: 'Error removing existing file (code %1). Could not save file'; Localized: 'Ошибка удаления файла (код %1). Не удалось сохранить файл'),
    (English: 'Error renaming temporary file (code %1). Could not save file'; Localized: 'Ошибка переименования временного файла (код %1). Не удалось сохранить файл'),
    (English: 'Failed to open included file: %1'; Localized: 'Не удалось открыть подключаемый файл: %1'),
    (English: 'Cannot start printer document.'; Localized: 'Не удается запустить печать документа.'),
    (English: 'Are you sure you want to clear the list of recently opened files?'; Localized: 'Вы действительно хотите очистить список последних файлов?'),
    (English: 'The %1 file has been modified outside of the source editor. You might want to reload it.'; Localized: 'Файл "%1" был изменён в другом редакторе. Возможно, вам следует перезагрузить его.'),
    (English: 'The %1 file has been modified outside of the source editor.%n%nDo you want to reload the file?'; Localized: 'Файл "%1" был изменён в другом редакторе.%n%nВы хотите перезагрузить этот файл?'),
    (English: 'The %1 file has been modified outside of the source editor. Changes have also been made in the source editor.%n%nDo you want to reload the file and lose the changes made in the source editor?'; Localized: 'Файл "%1" был изменён в другом редакторе, но изменения также были сделаны и в текущем редакторе.%n%nСледует ли перезагрузить этот файл с потерей всех изменений, сделанных в текущем редакторе?'),
    (English: 'File not opened.'; Localized: 'Файл не открыт.'),
    (English: 'Go to Line'; Localized: 'Переход к строке'),
    (English: 'Line number:'; Localized: 'Введите номер строки:'),
    (English: 'Could not load file (code %1)'; Localized: 'Не удалось загрузить файл (код %1)'),
    (English: 'Could not save file (code %1)'; Localized: 'Не удалось сохранить файл (код %1)'),
    (English: 'Do you want to copy your current license key to the clipboard before opening our order page? You will need it to be able to renew it.'; Localized: 'Скопировать ваш текущий ключ лицензии в буфер обмена? Он потребуется вам на странице покупки для его обновления.'),
    (English: 'New commercial license key has been registered:%n%n%1%n%nThanks for your support!'; Localized: 'Зарегистрирован новый ключ коммерческой лицензии:%n%n%1%n%nСпасибо за вашу поддержку!'),
    (English: 'Are you sure you want to remove your commercial license key and revert to non-commercial use only?'; Localized: 'Вы действительно хотите удалить свой ключ коммерческой лицензии и вернуться к некоммерческому использованию?'),
    (English: 'Commercial license key has been removed.'; Localized: 'Ключ коммерческой лицензии был удалён.'),
    (English: 'Your version of Inno Setup has been updated! <a id="%1">See what''s new</a>.'; Localized: 'Ваша версия Inno Setup была обновлена! Нажмите <a id="%1">здесь</a>, чтобы увидеть изменения.'),
    (English: 'VS Code-style editor shortcuts added! Use the <a id="%1">Editor Keys option</a> in Options dialog.'; Localized: 'Добавлены клавиши для стиля VS Code! Нажмите <a id="%1">здесь</a>, чтобы изменить управление.'),
    (English: 'RTF Editor added, a built-in WordPad replacement! Use the <a id="%1">RTF Editor item</a> in Tools menu.'; Localized: 'Добавлен редактор RTF — встроенная замена WordPad! Выберите в меню "Инструменты" пункт <a id="%1">Редактор RTF</a>.'),
    (English: 'Inno Setup Compiler is available in your language! Use the <a id="%1">Language option</a> in Options dialog.'; Localized: 'Интерфейс Inno Setup Compiler доступен на вашем родном языке! Нажмите <a id="%1">здесь</a> и выберите его в настройках.'),
    (English: '<a id="%1">Ideas board is open!</a> Share your ideas and vote on others, this month only.'; Localized: '<a id="%1">Открыт приём предложений!</a> Делитесь своими идеями и голосуйте за идеи других — только в этом месяце.'),
    (English: 'Running a version released after your update entitlement ended. <a id="%1">Renew license</a>, <a id="%2">remove key</a>, or <a id="%3">exit</a>.'; Localized: 'Запущена версия, выпущенная после окончания вашего права на обновления. <a id="%1">Обновите лицензию</a>, <a id="%2">удалите ключ</a> или <a id="%3">выйдите</a>.'),
    (English: 'Your update entitlement is ending soon. Please <a id="%1">renew your license</a>. Thanks!'; Localized: 'Ваша подписка на получение обновлений скоро завершится. <a id="%1">Обновите свою лицензию</a>. Спасибо!'),
    (English: 'Your update entitlement has ended. Please <a id="%1">renew your license</a>. Thanks!'; Localized: 'Ваша подписка на получение обновлений закончилась. <a id="%1">Обновите свою лицензию</a>. Спасибо!'),
    (English: 'Using Inno Setup commercially? Please <a id="%1">purchase a license</a>. Thanks!'; Localized: 'Используете Inno Setup в коммерческих целях? <a id="%1">Купите лицензию</a>. Спасибо!'),
    (English: 'Uninstall'; Localized: 'Uninstall'),
    (English: '%1 exit code: 0x%2'; Localized: 'Код выхода %1: 0x%2'),
    (English: '%1 exit code: %2'; Localized: 'Код выхода %1: %2'),
    (English: 'Unable to get %1 exit code (%2 failed)'; Localized: 'Невозможно получить код выхода %1 (ошибка %2)'),
    (English: '%1 is still running; can''t get exit code'; Localized: '%1 все еще выполняется; невозможно получить код выхода'),
    (English: 'Please stop the running %1 process before performing this command.'; Localized: 'Перед выполнением этой команды остановите запущенный процесс %1.'),
    (English: 'This command will detach the debugger from the running %1 process. Continue?'; Localized: 'Эта команда отсоединит отладчик от запущенного процесса %1. Продолжить?'),
    (English: 'The changes you made will not take effect until you re-compile.%n%nContinue running anyway?'; Localized: 'Внесенные изменения вступят в силу только после перекомпиляции.%n%nПродолжить выполнение?'),
    (English: 'A pause is already pending.'; Localized: 'Процесс выполнения уже приостановлен.'),
    (English: 'No code was generated for the current line.'; Localized: 'Для текущей строки код не создан.'),
    (English: 'This will unconditionally terminate the running %1 process. Continue?'; Localized: 'Выполнение этой команды приведёт к немедленному завершению процесса %1. Продолжить?'),
    (English: 'Note that if %1 is currently in the installation phase, any changes made to the system thus far will not be undone, nor will uninstall data be written.'; Localized: 'Обратите внимание: если установка %1 в данный момент находится в процессе выполнения, все изменения, внесенные в систему до этого момента, не будут отменены и данные для удаления не будут записаны.'),
    (English: 'Evaluate'; Localized: 'Значение константы'),
    (English: 'Constant to evaluate (for example, "%1"):'; Localized: 'Имя константы (например, "%1"):'),
    (English: 'Evaluate Result'; Localized: 'Результат'),
    (English: 'Evaluate Error'; Localized: 'Ошибка'),
    (English: 'An unknown error occurred.'; Localized: 'Произошла неизвестная ошибка.'),
    (English: '%1 = "%2"'; Localized: '%1 = "%2"'),
    (English: '%1 = Exception: %2'; Localized: '%1 = Исключение: %2'),
    (English: '%1 = Unknown error'; Localized: '%1 = Неизвестная ошибка'),
    (English: 'Unknown error'; Localized: 'Неизвестная ошибка'),
    (English: 'Line %1:%n%2'; Localized: 'Строка %1:%n%2'),
    (English: 'Runtime Error'; Localized: 'Ошибка выполнения'),
    (English: '%1 (Update entitlement ended)'; Localized: '%1 (Подписка завершилась)'),
    (English: '%1 (Update entitlement ended but updated anyway)'; Localized: '%1 (Подписка завершилась, но обновление было сделано)'),
    (English: 'Non-commercial use only'; Localized: 'Только для некоммерческого использования'),
    (English: 'Single User'; Localized: 'Single User'),
    (English: 'Team'; Localized: 'Team'),
    (English: 'Enterprise'; Localized: 'Enterprise'),
    (English: 'Inno Setup %1 License'; Localized: 'Inno Setup %1 License'),
    (English: '%1, %2.'; Localized: '%1, %2.'),
    (English: 'Includes updates until %1, major and minor.'; Localized: 'Доступны обновления до %1, основные и второстепенные'),
    (English: 'Includes all future updates, major and minor.'; Localized: 'Доступны все будущие обновления, основные и второстепенные.'),
    (English: '%1 Entries Designer'; Localized: 'Конструктор записей %1'),
    (English: '&Insert'; Localized: '&Вставить'),
    (English: '&Parameters...'; Localized: '&Параметры...'),
    (English: 'Remo&ve'; Localized: 'Уд&алить'),
    (English: 'Add Fol&der...'; Localized: 'Добавить пап&ку...'),
    (English: '&Add File(s)...'; Localized: 'Добавить фай&л(ы)...'),
    (English: '&Files:'; Localized: '&Файлы:'),
    (English: 'Add D&ownload...'; Localized: '&Загрузить...'),
    (English: 'Go to File'; Localized: 'Перейти к файлу'),
    (English: 'Enter Commercial License Key'; Localized: 'Коммерческая лицензия'),
    (English: 'Paste your license key below'; Localized: 'Вставьте свой ключ лицензии'),
    (English: 'Close'; Localized: 'Закрыть'),
    (English: 'Filter'; Localized: 'Фильтр'),
    (English: 'Inspector Menu'; Localized: 'Инспектор'),
    (English: 'Sections'; Localized: 'Секции'),
    (English: 'New Main Script (%1)'; Localized: 'Новый сценарий (%1)'),
    (English: 'Open Main Script (%1)'; Localized: 'Открыть сценарий (%1)'),
    (English: 'Save (%1)'; Localized: 'Сохранить (%1)'),
    (English: 'Stop Compile (%1)'; Localized: 'Завершить компиляцию (%1)'),
    (English: 'Target Setup (%1)'; Localized: 'Отладка Setup (%1)'),
    (English: 'Target Uninstall (%1)'; Localized: 'Отладка Uninstall (%1)'),
    (English: 'Help (%1)'; Localized: 'Справка (%1)'),
    (English: 'Main Script'; Localized: 'Главный сценарий'),
    (English: 'Close Banner'; Localized: 'Закрыть'),
    (English: '&File'; Localized: '&Файл'),
    (English: '&Open...'; Localized: '&Открыть...'),
    (English: 'Open &Recent'; Localized: '&Последние файлы'),
    (English: '&Clear Recently Opened'; Localized: '&Очистить список последних файлов'),
    (English: '&Save'; Localized: '&Сохранить'),
    (English: 'Save &As...'; Localized: 'Сохранить &как...'),
    (English: 'Save &Encoding'; Localized: 'Сохранить в ко&дировке'),
    (English: '&Auto (ANSI or UTF-8)'; Localized: '&Автоматически (ANSI или UTF-8)'),
    (English: '&UTF-8'; Localized: '&UTF-8'),
    (English: 'UTF-8 with &BOM'; Localized: 'UTF-8 с &BOM'),
    (English: 'Sa&ve All'; Localized: 'Сох&ранить все'),
    (English: '&Print...'; Localized: 'Пе&чать...'),
    (English: 'E&xit'; Localized: 'Вы&ход'),
    (English: '&Edit'; Localized: '&Правка'),
    (English: '&Undo'; Localized: '&Отменить'),
    (English: '&Redo'; Localized: '&Повторить'),
    (English: 'Cu&t'; Localized: 'Выреза&ть'),
    (English: '&Copy'; Localized: '&Копировать'),
    (English: '&Paste'; Localized: 'Вст&авить'),
    (English: 'De&lete'; Localized: 'У&далить'),
    (English: 'Select &All'; Localized: '&Выделить все'),
    (English: 'Add Next &Occurrence'; Localized: 'Добавить следующее вхо&ждение'),
    (English: '&Select All Occurrences'; Localized: 'Выделить все в&хождения'),
    (English: 'Select All Find &Matches'; Localized: 'В&ыделить все найденные совпадения'),
    (English: '&Find...'; Localized: '&Найти...'),
    (English: 'F&ind in Files...'; Localized: 'Найти в &файлах...'),
    (English: 'Find &Next'; Localized: 'На&йти следующее'),
    (English: 'Find Pre&vious'; Localized: 'Найти пр&едыдущее'),
    (English: 'R&eplace...'; Localized: '&Заменить...'),
    (English: 'Use Regular E&xpressions'; Localized: 'Использовать ре&гулярные выражения'),
    (English: 'Fol&d Section'; Localized: 'Сверн&уть секцию'),
    (English: 'Unfold Section'; Localized: '&Развернуть секцию'),
    (English: 'Go to File...'; Localized: 'Перейти к файлу...'),
    (English: '&Go to Line...'; Localized: 'Перейт&и к строке...'),
    (English: 'Toggle Line Comment'; Localized: 'Переключить комментарий строки'),
    (English: 'Go To Matching Brace'; Localized: 'Перейти к парной скобке'),
    (English: '&View'; Localized: '&Вид'),
    (English: '&Zoom'; Localized: '&Масштаб'),
    (English: 'Zoom &In'; Localized: 'Уве&личить'),
    (English: 'Zoom &Out'; Localized: 'У&меньшить'),
    (English: '&Reset'; Localized: 'И&сходный'),
    (English: '&Toolbar'; Localized: '&Панель инструментов'),
    (English: 'Na&vigator'; Localized: '&Навигатор'),
    (English: '&Inspector'; Localized: '&Инспектор'),
    (English: 'St&atus Bar'; Localized: '&Строка состояния'),
    (English: '&Next Tab'; Localized: 'С&ледующая вкладка'),
    (English: '&Previous Tab'; Localized: 'Пре&дыдущая вкладка'),
    (English: 'C&lose Tab'; Localized: '&Закрыть вкладку'),
    (English: 'Re&open Tab'; Localized: 'Переоткрыть вкладк&у'),
    (English: 'Reopen &All Tabs'; Localized: 'Перео&ткрыть все вкладки'),
    (English: 'C&lose Current Tab'; Localized: 'З&акрыть текущую вкладку'),
    (English: 'Focus Navi&gator'; Localized: 'Перейти к нави&гатору'),
    (English: 'Focus And &Select Navigator'; Localized: 'Открыть навигатор для вы&бора'),
    (English: '&Compiler Output'; Localized: 'Сообщения &компилятора'),
    (English: '&Debug Output'; Localized: 'Сообщения &отладки'),
    (English: 'D&ebug Call Stack'; Localized: 'Стек &вызовов'),
    (English: '&Find Results'; Localized: '&Результаты поиска'),
    (English: '&Hide Bottom Pane'; Localized: 'Скрыть ни&жнюю панель'),
    (English: '&Word Wrap'; Localized: 'П&еренос по словам'),
    (English: '&Go to'; Localized: '&Перейти к'),
    (English: 'Show all known directives'; Localized: 'Показывать все известные директивы'),
    (English: 'Follow cursor'; Localized: 'Следить за курсором'),
    (English: 'Quote new directive values'; Localized: 'Заключать значения новых директив в кавычки'),
    (English: 'Quote new parameter values'; Localized: 'Заключать значения новых параметров в кавычки'),
    (English: '&Help'; Localized: 'По&мощь'),
    (English: '&Build'; Localized: '&Сборка'),
    (English: '&Compile'; Localized: '&Компилировать'),
    (English: 'S&top Compile'; Localized: '&Завершить компиляцию'),
    (English: '&Low Priority During Compile'; Localized: '&Низкий приоритет при компиляции'),
    (English: '&Disable Output'; Localized: 'Отключить &вывод'),
    (English: 'Disable Co&mpression'; Localized: 'Отключить &сжатие'),
    (English: 'Disable &Signing'; Localized: 'Отключить &цифровую подпись'),
    (English: 'Disable Signcheck &Validation'; Localized: 'Отключить &проверку целостности'),
    (English: '&Open Output Folder'; Localized: 'Открыть п&апку вывода'),
    (English: '&Run'; Localized: '&Отладка'),
    (English: '&Run...'; Localized: '&Выполнить...'),
    (English: 'Run to &Cursor'; Localized: 'Выполнить до &курсора'),
    (English: 'Step &Into'; Localized: 'Шаг с &заходом'),
    (English: 'Step &Over'; Localized: 'Шаг с &обходом'),
    (English: 'Step Out'; Localized: 'Шаг до выхода'),
    (English: 'Toggle &Breakpoint'; Localized: 'Переключить &точку останова'),
    (English: '&Delete All Breakpoints'; Localized: 'У&далить все точки останова'),
    (English: 'P&ause'; Localized: 'П&риостановить'),
    (English: '&Terminate'; Localized: 'З&авершить'),
    (English: '&Evaluate Constant...'; Localized: 'З&начения констант...'),
    (English: 'Target &Setup'; Localized: 'Отладка &Setup'),
    (English: 'Target &Uninstall'; Localized: 'Отладка &Uninstall'),
    (English: '&Tools'; Localized: '&Инструменты'),
    (English: '&Add/Remove Programs'; Localized: '&Добавление/Удаление программ'),
    (English: 'Generate &GUID'; Localized: '&Создать GUID'),
    (English: 'Generate %1 Entries...'; Localized: 'Создать записи %1...'),
    (English: 'Generate %1 Call...'; Localized: 'Создать вызов %1...'),
    (English: '&Configure Sign Tools...'; Localized: 'Конфигурация &цифровой подписи...'),
    (English: 'R&TF Editor...'; Localized: '&Редактор RTF...'),
    (English: '&Options...'; Localized: '&Настройки...'),
    (English: 'Purchase or Renew Commercial &License'; Localized: 'Купить или обновить коммерческую &лицензию'),
    (English: 'Enter Commercial License &Key...'; Localized: 'Ввести &ключ коммерческой лицензии...'),
    (English: 'Remove Commercial License Key'; Localized: 'Удалить ключ коммерческой лицензии'),
    (English: '&Donate'; Localized: '&Поддержать развитие Inno Setup'),
    (English: '&Keyboard And Mouse Commands'; Localized: 'Сочетания клавиш и управление &мышкой'),
    (English: 'Regular E&xpressions'; Localized: '&Регулярные выражения'),
    (English: 'Inno &Setup Documentation'; Localized: 'Спр&авка Inno Setup'),
    (English: 'Inno Setup &Example Scripts'; Localized: 'Примеры сц&енариев Inno Setup'),
    (English: 'Inno Setup &FAQ'; Localized: 'Inno Setup в вопросах и о&тветах'),
    (English: 'Inno Setup &Mailing List'; Localized: '&Список рассылки Inno Setup'),
    (English: 'Inno Setup &Revision History'; Localized: 'Истори&я версий Inno Setup'),
    (English: 'Inno Setup &Web Site'; Localized: '&Домашняя страница Inno Setup'),
    (English: 'Inno Setup &Preprocessor Documentation'; Localized: 'Справка по препро&цессору Inno Setup'),
    (English: '&About Inno Setup'; Localized: '&О программе Inno Setup'),
    (English: '%1 Call Designer'; Localized: 'Конструктор вызова %1'),
    (English: 'Instruction'; Localized: 'Инструкция:'),
    (English: 'Message'; Localized: 'Сообщение:'),
    (English: 'Buttons'; Localized: ' Кнопки '),
    (English: ' Type '; Localized: ' Тип '),
    (English: 'Suppressible'; Localized: 'Подавляемый'),
    (English: ' Flags '; Localized: ' Флаги '),
    (English: 'Default button'; Localized: 'Кнопка в фокусе'),
    (English: ' Icon '; Localized: ' Значок '),
    (English: ' Return values '; Localized: ' Возвращаемые значения '),
    (English: '&Preview'; Localized: '&Просмотр'),
    (English: 'Options'; Localized: 'Настройки'),
    (English: ' Miscellaneous '; Localized: ' Разное '),
    (English: 'Show &Welcome dialog at startup'; Localized: 'Показывать окно пр&иветствия при запуске'),
    (English: 'Use the Inno Setup &Script Wizard'; Localized: 'Использовать Мастер с&ценариев Inno Setup'),
    (English: 'Automatically sa&ve before compiling'; Localized: '&Автосохранение сценария перед сборкой'),
    (English: 'Create &backups when saving'; Localized: 'Создавать &резервные копии при сохранении'),
    (English: 'Allow &Undo after save'; Localized: 'Разрешить операцию &отмены после сохранения'),
    (English: 'Display &full path in title bar'; Localized: 'Показывать полный путь в за&головке окна'),
    (English: '&Pause on exceptions'; Localized: '&Приостанавливать отладку на исключениях'),
    (English: '&Launch Setup/Uninstall as administrator'; Localized: 'Запускать Setup/Uninstall как админи&стратор'),
    (English: 'Colori&ze "Compiler Output" view'; Localized: 'Использовать по&дсветку сообщений компилятора'),
    (English: 'Automatically open %1 files'; Localized: 'Автоматически открывать файлы %1'),
    (English: 'Automatically show preprocessor output'; Localized: 'Показывать вывод препроцессора'),
    (English: 'Menu &keys:'; Localized: '&Управление:'),
    (English: 'Automatically reload files'; Localized: 'Автоматически перезагружать файлы'),
    (English: 'Allow Undo after reload'; Localized: 'Разрешить отмену после перезагрузки файлов'),
    (English: 'Keep new %1 files closed'; Localized: 'Держать новые файлы %1 закрытыми'),
    (English: 'Language:'; Localized: 'Язык:'),
    (English: ' Inspector '; Localized: ' Инспектор '),
    (English: ' Editor '; Localized: ' Редактор '),
    (English: 'Invoke autoco&mplete automatically'; Localized: 'Использовать &функцию автозавершения'),
    (English: 'Use syntax &highlighting'; Localized: 'Использовать си&нтаксическую подсветку'),
    (English: 'U&nderline syntax errors'; Localized: 'Подчеркивать синтакси&ческие ошибки'),
    (English: 'Allow cursor to move beyond &end of lines'; Localized: 'Переме&щать каретку за пределы конца строк'),
    (English: 'Enable section f&olding'; Localized: '&Включить сворачивание секций'),
    (English: 'Use tab cha&racter'; Localized: 'Использовать символ та&буляции'),
    (English: 'Auto &indent mode'; Localized: 'Умный ре&жим отступа'),
    (English: 'Show indentation &guides'; Localized: 'Показывать границы о&тступов'),
    (English: 'Font:'; Localized: 'Шрифт:'),
    (English: 'AaBbXxZz'; Localized: 'AaBbXxZz'),
    (English: '&Change...'; Localized: 'И&зменить...'),
    (English: '&Tab Width:'; Localized: '&Ширина TAB:'),
    (English: 'Show &line numbers in gutter'; Localized: 'Показывать ну&мерацию строк'),
    (English: 'T&heme:'; Localized: 'Т&ема:'),
    (English: 'Highlight occurrences of current selection'; Localized: 'Подсвечивать вхождения текущего выделения'),
    (English: 'Highlight occurrences of current wor&d'; Localized: 'Подсвечивать в&хождения текущего слова'),
    (English: 'Ke&ys:'; Localized: '&Клавиши:'),
    (English: 'Show whitespace'; Localized: 'Показывать пробелы'),
    (English: 'Smart Home key'; Localized: 'Умный режим [Home]'),
    (English: '&Associate .%1 files with this compiler'; Localized: 'Связать файлы .%1 с этим компил&ятором'),
    (English: '&Windows registry file (.%1) to import:'; Localized: '&Выберите файл реестра Windows для импорта (.%1):'),
    (English: 'B&rowse...'; Localized: '&Обзор...'),
    (English: 'Settings (for all keys and values):'; Localized: 'Параметры (для всех ключей и значений):'),
    (English: 'Also delete keys which are not empty'; Localized: 'Также удалить ключи, которые не являются пустыми'),
    (English: 'Delete keys which are empty on uninstall'; Localized: 'Во время деинсталляции удалить пустые ключи'),
    (English: 'Delete values on uninstall'; Localized: 'Во время деинсталляции удалить значения'),
    (English: 'Minimum Windows version:'; Localized: 'Создать для версии Windows не ниже:'),
    (English: 'RTF Editor'; Localized: 'Редактор RTF'),
    (English: 'New (%1)'; Localized: 'Новый (%1)'),
    (English: 'Open (%1)'; Localized: 'Открыть (%1)'),
    (English: 'Cut (%1)'; Localized: 'Вырезать (%1)'),
    (English: 'Copy (%1)'; Localized: 'Копировать (%1)'),
    (English: 'Paste (%1)'; Localized: 'Вставить (%1)'),
    (English: 'Undo (%1)'; Localized: 'Отменить (%1)'),
    (English: 'Redo (%1)'; Localized: 'Повторить (%1)'),
    (English: 'Bold (%1)'; Localized: 'Полужирный (%1)'),
    (English: 'Italic (%1)'; Localized: 'Наклонный (%1)'),
    (English: 'Underline (%1)'; Localized: 'Подчёркнутый (%1)'),
    (English: '&Bold'; Localized: 'Полу&жирный'),
    (English: '&Italic'; Localized: '&Курсив'),
    (English: '&Underline'; Localized: 'По&дчёркнутый'),
    (English: '&Font...'; Localized: '&Шрифт...'),
    (English: '&Increase Font Size'; Localized: 'Увеличить &размер шрифта'),
    (English: '&Decrease Font Size'; Localized: 'Уменьшить ра&змер шрифта'),
    (English: 'Text &Color...'; Localized: 'Цвет &текста...'),
    (English: '&Background Color...'; Localized: 'Цвет &фона...'),
    (English: 'Reset &Colors'; Localized: '&Сбросить настройки цвета'),
    (English: 'Align &Left'; Localized: 'Выровнять по &левому краю'),
    (English: '&Center'; Localized: 'Выровнять по &центру'),
    (English: 'Align &Right'; Localized: 'Выровнять по &правому краю'),
    (English: 'Bulle&ts'; Localized: '&Маркеры'),
    (English: 'Increase &Indent'; Localized: 'Увеличить отс&туп'),
    (English: 'Decrease Inden&t'; Localized: 'Уменьшить отст&уп'),
    (English: 'Configure Sign Tools'; Localized: 'Конфигурация цифровой подписи'),
    (English: ' Sign Tools '; Localized: ' Инструменты цифровой подписи '),
    (English: '&Add...'; Localized: '&Добавить...'),
    (English: '&Edit...'; Localized: 'Из&менить...'),
    (English: 'Be notified by e-mail of new Inno Setup releases'; Localized: 'Подписаться на рассылку о новых выпусках Inno Setup'),
    (English: 'Subscribe'; Localized: 'Подписка'),
    (English: ' New file '; Localized: ' Новый файл '),
    (English: 'Create a new &empty script file'; Localized: 'Создать &пустой файл сценария'),
    (English: 'Create a new script file using the &Script Wizard'; Localized: 'Создать новый файл сценария с помощью &Мастера'),
    (English: ' Open file '; Localized: ' Открыть файл '),
    (English: 'Open an e&xisting script file'; Localized: 'Открыть существующий &файл сценария'),
    (English: '&Don''t show this dialog again'; Localized: '&Больше не показывать этот диалог'),
    (English: 'Script Wizard File'; Localized: 'Мастер сценария'),
    (English: 'bold'; Localized: 'bold'),
    (English: ' = required'; Localized: ' = обязательные поля'),
    (English: ' Destination '; Localized: ' Вывод данных '),
    (English: 'Destination &base folder:'; Localized: '&Основная целевая папка:'),
    (English: 'Destination &subfolder:'; Localized: 'Целевая подпап&ка:'),
    (English: 'Destination &name:'; Localized: '&Целевое имя:'),
    (English: ' Source '; Localized: ' Исходные данные '),
    (English: '&Source file or folder:'; Localized: 'Ис&ходный файл или папка:'),
    (English: '&Recurse subfolders'; Localized: '&Добавить подпапки'),
    (English: '&Include empty subfolders'; Localized: '&Включая пустые подпапки'),
    (English: '&Extract archive'; Localized: 'И&звлечь архив'),
    (English: 'Welcome to the %1'; Localized: 'Вас приветствует %1'),
    (English: 'This wizard will guide you through the process of creating a new Inno Setup script file. The results will be used to generate a new script file which can be compiled directly or saved on disk for later use.%n%n'+'Not all features of Inno Setup are covered by this wizard. See the documentation for details on creating Inno Setup script files.%n%nClick Next to continue, or Cancel to exit this wizard.'; Localized: 'Этот Мастер поможет вам создать простейший сценарий Inno Setup для вашего приложения. ' +
              'Полученный результат вы можете использовать для компиляции проекта или сохранить на диск для последующего использования.%n%n' +
              'Имейте в виду, что этот Мастер охватывает не все функции Inno Setup. Обратитесь к справочной документации, чтобы узнать более подробные сведения о создании сценариев.%n%n' +
              'Нажмите "Далее", чтобы продолжить работу Мастера, или "Отмена", чтобы завершить его работу.'),
    (English: 'Application na&me:'; Localized: 'Н&азвание приложения:'),
    (English: 'Application &version:'; Localized: '&Версия приложения:'),
    (English: 'Application &publisher:'; Localized: '&Издатель приложения:'),
    (English: 'Application &website:'; Localized: '&Сайт приложения:'),
    (English: 'Application folder na&me:'; Localized: 'Н&азвание папки для установки приложения:'),
    (English: 'Application &destination base folder:'; Localized: '&Основной путь установки приложения:'),
    (English: 'Other:'; Localized: 'Другие параметры:'),
    (English: 'Allow user to &change the application folder'; Localized: '&Разрешить пользователю изменять путь установки'),
    (English: 'The application doe&sn''t need a folder'; Localized: 'Для приложения н&е требуется папка установки'),
    (English: 'Other application &files:'; Localized: 'Другие &файлы приложения:'),
    (English: 'Application &main executable file:'; Localized: '&Главный исполняемый файл приложения:'),
    (English: 'Allow &user to start the application after Setup has finished'; Localized: '&Разрешить пользователю запуск приложения после завершения установки'),
    (English: 'The application doe&sn''t have a main executable file'; Localized: 'Приложение н&е имеет главного исполняемого файла'),
    (English: 'Application file type na&me:'; Localized: 'Наименование &типа файла:'),
    (English: '&Associate a file type to the main executable'; Localized: '&Связать тип файла с основным исполняемым файлом'),
    (English: 'Application file type &extension:'; Localized: '&Расширение файла:'),
    (English: 'Application &Start Menu folder name:'; Localized: 'Имя папки приложения в меню &ПУСК:'),
    (English: 'Other shortcuts to the main executable:'; Localized: 'Дополнительные ярлыки для главного исполняемого файла:'),
    (English: 'Allow user to &change the Start Menu folder name'; Localized: 'Разрешить пользователю из&менять имя папки в меню ПУСК'),
    (English: 'Allow user to &disable Start Menu folder creation'; Localized: 'Разрешить пользователю о&тменить создание папки в меню ПУСК'),
    (English: 'Allow user to create a deskto&p shortcut'; Localized: 'Разрешить пользователю создание ярлыка на &Рабочем столе'),
    (English: 'Create an &Uninstall shortcut in the Start Menu folder'; Localized: 'Создать ярлык д&еинсталляции в папке меню ПУСК'),
    (English: 'Create an &Internet shortcut in the Start Menu folder'; Localized: 'Создать &ярлык интернет ссылки в папке меню ПУСК'),
    (English: '&Create a Start Menu shortcut but no folder'; Localized: '&Создать ярлык в меню ПУСК, но без папки'),
    (English: '&License file:'; Localized: 'Файл &лицензии:'),
    (English: '&Information file shown before installation:'; Localized: 'Файл с ин&формацией, отображаемой перед установкой:'),
    (English: 'Information file shown &after installation:'; Localized: 'Файл с информацией, отображаемой &после установки:'),
    (English: 'Install mode:'; Localized: 'Режим установки:'),
    (English: '&Administrative install mode (install for all users)'; Localized: 'С правами &администратора (для всех пользователей)'),
    (English: 'Non a&dministrative install mode (install for current user only)'; Localized: '&Без прав администратора (только для текущего пользователя)'),
    (English: 'Allow user to &override the install mode via the command line'; Localized: 'Разрешить пе&реопределение режима установки в командной строке'),
    (English: 'Ask the user to &choose the install mode at startup'; Localized: 'Предлагать пользователю &выбор режима установки при запуске'),
    (English: '&Languages:'; Localized: 'Язык&и установки:'),
    (English: '&Deselect All'; Localized: 'Отменить в&се'),
    (English: 'Custom compiler output fol&der:'; Localized: 'Папк&а вывода готового файла установки:'),
    (English: 'Compiler output base &file name:'; Localized: 'Название &файла установки:'),
    (English: 'Custom Setup &icon file:'; Localized: 'Файл знач&ка установки:'),
    (English: 'Setup &password:'; Localized: '&Пароль для установки:'),
    (English: 'Use the password to &encrypt the application files'; Localized: 'Использовать пароль для &шифрования файлов приложения'),
    (English: '&Wizard style:'; Localized: '&Стиль мастера:'),
    (English: 'You have successfully completed the %1.%n%nTo close this wizard and generate the new script file, click Finish.'; Localized: '%1 успешно собрал все данные.%n%nЧтобы завершить работу Мастера и создать сценарий, нажмите "Готово".'),
    (English: '&Back'; Localized: '&Назад'),
    (English: '''%s'' is not a valid integer value'; Localized: '''%s'' не является допустимым целым числом'),
    (English: '''%s'' is not a valid integer value for %s type'; Localized: '''%s'' не является допустимым целым числом для типа %s'),
    (English: '''%s'' is not a valid floating point value'; Localized: '''%s'' не является допустимым числом с плавающей точкой'),
    (English: '''%d.%d'' is not a valid timestamp'; Localized: '''%d.%d'' не является допустимой временной меткой'),
    (English: '''%s'' is not a valid GUID value'; Localized: '''%s'' не является допустимым значением GUID'),
    (English: 'Invalid argument to time encode'; Localized: 'Неверный аргумент для кодирования времени'),
    (English: 'Invalid argument to date encode'; Localized: 'Неверный аргумент для кодирования даты'),
    (English: 'Out of memory'; Localized: 'Недостаточно памяти'),
    (English: 'I/O error %d'; Localized: 'Ошибка ввода/вывода %d'),
    (English: 'File not found'; Localized: 'Файл не найден'),
    (English: 'Invalid filename'; Localized: 'Неверное имя файла'),
    (English: 'Too many open files'; Localized: 'Слишком много открытых файлов'),
    (English: 'File access denied'; Localized: 'Доступ к файлу запрещён'),
    (English: 'Read beyond end of file'; Localized: 'Чтение за пределами конца файла'),
    (English: 'Disk full'; Localized: 'Диск переполнен'),
    (English: 'Invalid numeric input'; Localized: 'Неверный числовой ввод'),
    (English: 'Division by zero'; Localized: 'Деление на ноль'),
    (English: 'Range check error'; Localized: 'Ошибка проверки диапазона'),
    (English: 'Integer overflow'; Localized: 'Переполнение целого числа'),
    (English: 'Invalid floating point operation'; Localized: 'Неверная операция с плавающей точкой'),
    (English: 'Floating point division by zero'; Localized: 'Деление на ноль с плавающей точкой'),
    (English: 'Floating point overflow'; Localized: 'Переполнение при операции с плавающей точкой'),
    (English: 'Floating point underflow'; Localized: 'Переполнение вниз при операции с плавающей точкой'),
    (English: 'Invalid pointer operation'; Localized: 'Неверная операция с указателем'),
    (English: 'Invalid class typecast'; Localized: 'Неверное приведение типа класса'),
    (English: 'Access violation at address %p. %s of address %p'; Localized: 'Нарушение доступа по адресу %p. %s по адресу %p'),
    (English: 'Access violation'; Localized: 'Нарушение доступа'),
    (English: 'Stack overflow'; Localized: 'Переполнение стека'),
    (English: 'Control-C hit'; Localized: 'Нажата комбинация Control-C'),
    (English: 'Privileged instruction'; Localized: 'Привилегированная инструкция'),
    (English: 'Operation aborted'; Localized: 'Операция прервана'),
    (English: 'Exception %s in module %s at %p.'#13#10'%s%s'#13#10; Localized: 'Исключение %s в модуле %s по адресу %p.'#13#10'%s%s'#13#10),
    (English: 'Application Error'; Localized: 'Ошибка приложения'),
    (English: 'Format ''%s'' invalid or incompatible with argument'; Localized: 'Формат ''%s'' недопустим или несовместим с аргументом'),
    (English: 'No argument for format ''%s'''; Localized: 'Нет аргумента для формата ''%s'''),
    (English: 'Variant method calls not supported'; Localized: 'Вызов методов Variant не поддерживается'),
    (English: 'Read'; Localized: 'Чтение'),
    (English: 'Write'; Localized: 'Запись'),
    (English: 'Execution'; Localized: 'Выполнение'),
    (English: 'Invalid access'; Localized: 'Неверный доступ'),
    (English: 'Error creating variant or safe array'; Localized: 'Ошибка создания Variant или SafeArray'),
    (English: 'Variant or safe array index out of bounds'; Localized: 'Индекс Variant или SafeArray вне диапазона'),
    (English: 'Variant or safe array is locked'; Localized: 'Variant или SafeArray заблокирован'),
    (English: 'Invalid variant type conversion'; Localized: 'Неверное преобразование типа Variant'),
    (English: 'Invalid variant operation'; Localized: 'Неверная операция с Variant'),
    (English: 'Invalid NULL variant operation'; Localized: 'Неверная операция с NULL Variant'),
    (English: 'Invalid variant operation (%s%.8x)'#10'%s'; Localized: 'Неверная операция с Variant (%s%.8x)'#10'%s'),
    (English: 'Could not convert variant of type (%s) into type (%s)'; Localized: 'Не удалось преобразовать Variant типа (%s) в тип (%s)'),
    (English: 'Overflow while converting variant of type (%s) into type (%s)'; Localized: 'Переполнение при преобразовании Variant типа (%s) в тип (%s)'),
    (English: 'Variant overflow'; Localized: 'Переполнение Variant'),
    (English: 'Invalid argument'; Localized: 'Неверный аргумент'),
    (English: 'Invalid variant type'; Localized: 'Неверный тип Variant'),
    (English: 'Operation not supported'; Localized: 'Операция не поддерживается'),
    (English: 'Unexpected variant error'; Localized: 'Неожиданная ошибка Variant'),
    (English: 'External exception %x'; Localized: 'Внешнее исключение %x'),
    (English: 'Assertion failed'; Localized: 'Утверждение не выполнено'),
    (English: 'Interface not supported'; Localized: 'Интерфейс не поддерживается'),
    (English: 'Exception in safecall method'; Localized: 'Исключение в методе safecall'),
    (English: 'Object lock not owned'; Localized: 'Блокировка объекта не принадлежит текущему потоку'),
    (English: 'Monitor support function not initialized'; Localized: 'Функция поддержки монитора не инициализирована'),
    (English: 'Feature not implemented'; Localized: 'Функциональность не реализована'),
    (English: 'Method called on disposed object'; Localized: 'Вызов метода у уничтоженного объекта'),
    (English: '%s (%s, line %d)'; Localized: '%s (%s, строка %d)'),
    (English: 'Abstract Error'; Localized: 'Абстрактная ошибка'),
    (English: 'Access violation at address %p in module ''%s'' (offset %x). %s of address %p'; Localized: 'Нарушение доступа по адресу %p в модуле ''%s'' (смещение %x). %s по адресу %p'),
    (English: 'System Error.  Code: %d.'#13#10'%s%s'; Localized: 'Системная ошибка. Код: %d.'#13#10'%s%s'),
    (English: 'A call to an OS function failed'; Localized: 'Вызов функции ОС завершился неудачей'),
    (English: 'Jan'; Localized: 'Янв'),
    (English: 'Feb'; Localized: 'Фев'),
    (English: 'Mar'; Localized: 'Мар'),
    (English: 'Apr'; Localized: 'Апр'),
    (English: 'May'; Localized: 'Май'),
    (English: 'Jun'; Localized: 'Июн'),
    (English: 'Jul'; Localized: 'Июл'),
    (English: 'Aug'; Localized: 'Авг'),
    (English: 'Sep'; Localized: 'Сен'),
    (English: 'Oct'; Localized: 'Окт'),
    (English: 'Nov'; Localized: 'Ноя'),
    (English: 'Dec'; Localized: 'Дек'),
    (English: 'January'; Localized: 'Январь'),
    (English: 'February'; Localized: 'Февраль'),
    (English: 'March'; Localized: 'Март'),
    (English: 'April'; Localized: 'Апрель'),
    (English: 'June'; Localized: 'Июнь'),
    (English: 'July'; Localized: 'Июль'),
    (English: 'August'; Localized: 'Август'),
    (English: 'September'; Localized: 'Сентябрь'),
    (English: 'October'; Localized: 'Октябрь'),
    (English: 'November'; Localized: 'Ноябрь'),
    (English: 'December'; Localized: 'Декабрь'),
    (English: 'Sun'; Localized: 'Вс'),
    (English: 'Mon'; Localized: 'Пн'),
    (English: 'Tue'; Localized: 'Вт'),
    (English: 'Wed'; Localized: 'Ср'),
    (English: 'Thu'; Localized: 'Чт'),
    (English: 'Fri'; Localized: 'Пт'),
    (English: 'Sat'; Localized: 'Сб'),
    (English: 'Sunday'; Localized: 'Воскресенье'),
    (English: 'Monday'; Localized: 'Понедельник'),
    (English: 'Tuesday'; Localized: 'Вторник'),
    (English: 'Wednesday'; Localized: 'Среда'),
    (English: 'Thursday'; Localized: 'Четверг'),
    (English: 'Friday'; Localized: 'Пятница'),
    (English: 'Saturday'; Localized: 'Суббота'),
    (English: 'Invalid source array'; Localized: 'Неверный исходный массив'),
    (English: 'Invalid destination array'; Localized: 'Неверный целевой массив'),
    (English: 'Character index out of bounds (%d)'; Localized: 'Индекс символа вне диапазона (%d)'),
    (English: 'Start index out of bounds (%d)'; Localized: 'Начальный индекс вне диапазона (%d)'),
    (English: 'Invalid count (%d)'; Localized: 'Неверное количество (%d)'),
    (English: 'Invalid destination index (%d)'; Localized: 'Неверный целевой индекс (%d)'),
    (English: 'Invalid code page'; Localized: 'Неверная кодовая страница'),
    (English: 'No mapping for the Unicode character exists in the target multi-byte code page'; Localized: 'Для символа Unicode не найдено соответствия в целевой многобайтовой кодовой странице'),
    (English: 'Invalid StringBaseIndex'; Localized: 'Неверный StringBaseIndex'),
    (English: '''%s'' is not a valid %s color value'; Localized: '''%s'' не является допустимым значением цвета %s'),
    (English: 'Ancestor for ''%s'' not found'; Localized: 'Предок для ''%s'' не найден'),
    (English: 'Cannot assign a %s to a %s'; Localized: 'Невозможно присвоить %s для %s'),
    (English: 'Bits index out of range'; Localized: 'Индекс бита вне диапазона'),
    (English: 'Can''t write to a read-only resource stream'; Localized: 'Невозможно записать в поток только для чтения'),
    (English: '''''%s'''' expected'; Localized: 'Ожидалось ''''%s'''''),
    (English: 'CheckSynchronize called from thread $%x, which is NOT the main thread'; Localized: 'CheckSynchronize вызван из потока $%x, который НЕ является главным потоком'),
    (English: 'Class %s not found'; Localized: 'Класс %s не найден'),
    (English: 'A class named %s already exists'; Localized: 'Класс с именем %s уже существует'),
    (English: 'List does not allow duplicates ($0%x)'; Localized: 'Список не допускает дубликатов ($0%x)'),
    (English: 'A component named %s already exists'; Localized: 'Компонент с именем %s уже существует'),
    (English: 'String list does not allow duplicates'; Localized: 'Список строк не допускает дубликатов'),
    (English: 'Cannot create file "%s". %s'; Localized: 'Невозможно создать файл "%s". %s'),
    (English: 'Cannot open file "%s". %s'; Localized: 'Невозможно открыть файл "%s". %s'),
    (English: 'Identifier expected'; Localized: 'Ожидался идентификатор'),
    (English: 'Invalid binary value'; Localized: 'Неверное двоичное значение'),
    (English: 'Invalid stream format'; Localized: 'Неверный формат потока'),
    (English: '''%s'' is an invalid mask at (%d)'; Localized: '''%s'' – недопустимая маска в позиции (%d)'),
    (English: '''''%s'''' is not a valid component name'; Localized: '''''%s'''' – недопустимое имя компонента'),
    (English: 'Invalid property value'; Localized: 'Недопустимое значение свойства'),
    (English: 'Invalid property path'; Localized: 'Недопустимый путь свойства'),
    (English: 'Invalid data type for ''%s'''; Localized: 'Недопустимый тип данных для ''%s'''),
    (English: 'Invalid string constant'; Localized: 'Недопустимая строковая константа'),
    (English: 'Line too long'; Localized: 'Строка слишком длинная'),
    (English: 'List capacity out of bounds (%d)'; Localized: 'Ёмкость списка превышена (%d)'),
    (English: 'List count out of bounds (%d)'; Localized: 'Количество элементов списка вне диапазона (%d)'),
    (English: 'List index out of bounds (%d)'; Localized: 'Индекс списка вне диапазона (%d)'),
    (English: '.  %s range is 0..%d'; Localized: '. Диапазон %s: 0..%d'),
    (English: '.  %s is empty'; Localized: '.  %s пуст'),
    (English: 'Out of memory while expanding memory stream'; Localized: 'Недостаточно памяти при расширении потока'),
    (English: '%s has not been registered as a COM class'; Localized: '%s не зарегистрирован как COM-класс'),
    (English: 'Printer is not currently printing'; Localized: 'Принтер в данный момент не печатает'),
    (English: 'Number expected'; Localized: 'Ожидалось число'),
    (English: 'ANSI or UTF8 encoding expected'; Localized: 'Ожидается кодировка ANSI или UTF-8'),
    (English: '%s on line %d'; Localized: '%s в строке %d'),
    (English: 'Error reading %s%s%s: %s'; Localized: 'Ошибка чтения %s%s%s: %s'),
    (English: 'Printing in progress'; Localized: 'Идёт печать'),
    (English: 'Stream read error'; Localized: 'Ошибка чтения потока'),
    (English: 'Property is read-only'; Localized: 'Свойство доступно только для чтения'),
    (English: 'Failed to create key %s'; Localized: 'Не удалось создать ключ %s'),
    (English: 'Failed to get data for ''%s'''; Localized: 'Не удалось получить данные для ''%s'''),
    (English: 'Failed to set data for ''%s'''; Localized: 'Не удалось установить данные для ''%s'''),
    (English: 'Resource %s not found'; Localized: 'Ресурс %s не найден'),
    (English: '%s.Seek not implemented'; Localized: '%s.Seek не реализован'),
    (English: 'Operation not allowed on sorted list'; Localized: 'Операция не разрешена для отсортированного списка'),
    (English: 'String expected'; Localized: 'Ожидалась строка'),
    (English: '%s expected'; Localized: 'Ожидалось %s'),
    (English: '%s not in a class registration group'; Localized: '%s не входит в группу регистрации классов'),
    (English: 'Property %s does not exist'; Localized: 'Свойство %s не существует'),
    (English: 'Stream write error'; Localized: 'Ошибка записи в поток'),
    (English: 'Thread creation error: %s'; Localized: 'Ошибка создания потока: %s'),
    (English: 'Thread Error: %s (%d)'; Localized: 'Ошибка потока: %s (%d)'),
    (English: 'Cannot terminate an externally created thread'; Localized: 'Невозможно завершить поток, созданный извне'),
    (English: 'Cannot wait for an externally created thread'; Localized: 'Невозможно дождаться завершения потока, созданного извне'),
    (English: 'Cannot call Start on a running or suspended thread'; Localized: 'Невозможно вызвать Start для уже запущенного или приостановленного потока'),
    (English: 'Parameter %s cannot be nil'; Localized: 'Параметр %s не может быть nil'),
    (English: 'Parameter %s cannot be a negative value'; Localized: 'Параметр %s не может быть отрицательным'),
    (English: 'Invalid characters in path'; Localized: 'Недопустимые символы в пути'),
    (English: 'Invalid characters in search pattern'; Localized: 'Недопустимые символы в шаблоне поиска'),
    (English: 'Path is empty'; Localized: 'Путь пуст'),
    (English: 'Search pattern is empty'; Localized: 'Шаблон поиска пуст'),
    (English: 'The specified path is too long'; Localized: 'Указанный путь слишком длинный'),
    (English: 'The specified path was not found'; Localized: 'Указанный путь не найден'),
    (English: 'The path format is not supported'; Localized: 'Формат пути не поддерживается'),
    (English: 'No help viewer that supports filters'; Localized: 'Не найден просмотрщик справки, поддерживающий фильтры'),
    (English: 'String index out of range (%d).  Must be >= %d and <= %d'; Localized: 'Индекс строки вне диапазона (%d). Должен быть >= %d и <= %d'),
    (English: 'Invalid UTF32 character value.  Must be >= 0 and <= $10FFFF, excluding surrogate pair ranges'; Localized: 'Недопустимое значение символа UTF32. Должно быть >= 0 и <= $10FFFF, исключая диапазоны суррогатных пар'),
    (English: 'High surrogate char without a following low surrogate char at index: %d. Check that the string is encoded properly'; Localized: 'Старший суррогат без следующего младшего суррогата по индексу: %d. Проверьте корректность кодировки строки'),
    (English: 'Low surrogate char without a preceding high surrogate char at index: %d. Check that the string is encoded properly'; Localized: 'Младший суррогат без предшествующего старшего суррогата по индексу: %d. Проверьте корректность кодировки строки'),
    (English: 'Source and Destination arrays must not be the same'; Localized: 'Исходный и конечный массивы не должны совпадать'),
    (English: 'SpinCount out of range. Must be between 0 and %d'; Localized: 'SpinCount вне диапазона. Должен быть между 0 и %d'),
    (English: 'No context-sensitive help installed'; Localized: 'Контекстная справка не установлена'),
    (English: 'No help found for context %d'; Localized: 'Справка не найдена для контекста %d'),
    (English: 'Unable to open Index'; Localized: 'Не удалось открыть индекс'),
    (English: 'Unable to open Search'; Localized: 'Не удалось открыть поиск'),
    (English: 'Unable to find a Table of Contents'; Localized: 'Не удалось найти оглавление'),
    (English: 'No topic-based help system installed'; Localized: 'Система справочной помощи по темам не установлена'),
    (English: 'No help found for %s'; Localized: 'Справка не найдена для %s'),
    (English: 'Argument out of range'; Localized: 'Аргумент вне диапазона'),
    (English: 'Argument must not be nil'; Localized: 'Аргумент не может быть nil'),
    (English: 'Item not found'; Localized: 'Элемент не найден'),
    (English: 'Duplicates not allowed'; Localized: 'Дубликаты не допускаются'),
    (English: 'Insufficient RTTI available to support this operation'; Localized: 'Недостаточно RTTI для выполнения этой операции'),
    (English: 'Parameter count mismatch'; Localized: 'Несоответствие количества параметров'),
    (English: 'Parameter count exceeded'; Localized: 'Превышено количество параметров'),
    (English: 'Type ''%s'' is not declared in the interface section of a unit'; Localized: 'Тип ''%s'' не объявлен в секции interface модуля'),
    (English: 'VAR and OUT arguments must match parameter type exactly'; Localized: 'Аргументы VAR и OUT должны точно соответствовать типу параметра'),
    (English: 'Property ''%s'' is read-only'; Localized: 'Свойство ''%s'' только для чтения'),
    (English: 'Property ''%s'' is write-only'; Localized: 'Свойство ''%s'' только для записи'),
    (English: 'RTTI objects cannot be manually destroyed by application code'; Localized: 'Объекты RTTI не могут быть вручную уничтожены кодом приложения'),
    (English: '%s (Version %d.%d, Build %d, %5:s)'; Localized: '%s (версия %d.%d, сборка %d, %5:s)'),
    (English: '%s Service Pack %4:d (Version %1:d.%2:d, Build %3:d, %5:s)'; Localized: '%s Service Pack %4:d (версия %1:d.%2:d, сборка %3:d, %5:s)'),
    (English: '32-bit Edition'; Localized: '32-bit Edition'),
    (English: '64-bit Edition'; Localized: '64-bit Edition'),
    (English: 'Windows'; Localized: 'Windows'),
    (English: 'Windows Vista'; Localized: 'Windows Vista'),
    (English: 'Windows Server 2008'; Localized: 'Windows Server 2008'),
    (English: 'Windows 7'; Localized: 'Windows 7'),
    (English: 'Windows Server 2008 R2'; Localized: 'Windows Server 2008 R2'),
    (English: 'Windows 2000'; Localized: 'Windows 2000'),
    (English: 'Windows XP'; Localized: 'Windows XP'),
    (English: 'Windows Server 2003'; Localized: 'Windows Server 2003'),
    (English: 'Windows Server 2003 R2'; Localized: 'Windows Server 2003 R2'),
    (English: 'Windows Server 2012'; Localized: 'Windows Server 2012'),
    (English: 'Windows Server 2012 R2'; Localized: 'Windows Server 2012 R2'),
    (English: 'Windows Server 2016'; Localized: 'Windows Server 2016'),
    (English: 'Windows Server 2019'; Localized: 'Windows Server 2019'),
    (English: 'Windows Server 2022'; Localized: 'Windows Server 2022'),
    (English: 'Windows 8'; Localized: 'Windows 8'),
    (English: 'Windows 8.1'; Localized: 'Windows 8.1'),
    (English: 'Windows 10'; Localized: 'Windows 10'),
    (English: 'Windows 11'; Localized: 'Windows 11'),
    (English: 'Cannot create instance of class %s'; Localized: 'Невозможно создать экземпляр класса %s'),
    (English: 'Observer is not supported'; Localized: 'Наблюдатель не поддерживается'),
    (English: 'Cannot have multiple single cast observers added to the observers collection'; Localized: 'Невозможно добавить несколько single cast наблюдателей в коллекцию'),
    (English: 'The object does not implement the observer interface'; Localized: 'Объект не реализует интерфейс наблюдателя'),
    (English: 'No single cast observer with ID %d was added to the observer collection'; Localized: 'Single cast наблюдатель с ID %d не был добавлен в коллекцию'),
    (English: 'No multi cast observer with ID %d was added to the observer collection'; Localized: 'Multi cast наблюдатель с ID %d не был добавлен в коллекцию'),
    (English: 'Observer is not available'; Localized: 'Наблюдатель недоступен'),
    (English: 'SHA2: Cannot update a finalized hash'; Localized: 'SHA2: невозможно обновить финализированный хеш'),
    (English: 'Must wait on at least one event'; Localized: 'Необходимо дождаться хотя бы одного события'),
    (English: 'Cannot call BeginInvoke on a TComponent in the process of destruction'; Localized: 'Невозможно вызвать BeginInvoke для TComponent, который находится в процессе уничтожения'),
    (English: 'OLE error %.8x'; Localized: 'Ошибка OLE %.8x'),
    (English: 'Method ''%s'' not supported by automation object'; Localized: 'Метод ''%s'' не поддерживается автоматизацией объекта'),
    (English: 'Variant does not reference an automation object'; Localized: 'Variant не ссылается на объект автоматизации'),
    (English: 'Dispatch methods do not support more than 64 parameters'; Localized: 'Dispatch-методы не поддерживают более 64 параметров'),
    (English: 'A regular expression specified in RegEx is required'; Localized: 'Требуется регулярное выражение, указанное в RegEx'),
    (English: 'Error in regular expression at offset %d: %s'; Localized: 'Ошибка в регулярном выражении по смещению %d: %s'),
    (English: 'Successful match required'; Localized: 'Требуется успешное совпадение'),
    (English: 'Index out of bounds (%d)'; Localized: 'Индекс вне диапазона (%d)'),
    (English: 'Bitmap image is not valid'; Localized: 'Изображение Bitmap недействительно'),
    (English: 'Icon image is not valid'; Localized: 'Изображение Icon недействительно'),
    (English: 'Metafile is not valid'; Localized: 'Метафайл недействителен'),
    (English: 'Invalid pixel format'; Localized: 'Неверный формат пикселей'),
    (English: 'Invalid image'; Localized: 'Неверное изображение'),
    (English: 'Scan line index out of range'; Localized: 'Индекс строки сканирования вне диапазона'),
    (English: 'Cannot change the size of an icon'; Localized: 'Невозможно изменить размер значка'),
    (English: 'Cannot change the size of a WIC Image'; Localized: 'Невозможно изменить размер WIC Image'),
    (English: 'Unsupported clipboard format'; Localized: 'Неподдерживаемый формат буфера обмена'),
    (English: 'Unsupported stream format'; Localized: 'Неподдерживаемый формат потока'),
    (English: 'Out of system resources'; Localized: 'Недостаточно системных ресурсов'),
    (English: 'Canvas does not allow drawing'; Localized: 'Холст не позволяет рисование'),
    (English: 'Text format flag ''%s'' not supported'; Localized: 'Флаг формата текста ''%s'' не поддерживается'),
    (English: 'Invalid image frame index %d: there are %d frames (0-%d)'; Localized: 'Неверный индекс кадра изображения %d: всего %d кадров (0-%d)'),
    (English: 'Invalid image size'; Localized: 'Неверный размер изображения'),
    (English: 'Invalid ImageList'; Localized: 'Неверный ImageList'),
    (English: 'Invalid ImageList Index'; Localized: 'Неверный индекс ImageList'),
    (English: 'Failed to read ImageList data from stream'; Localized: 'Не удалось прочитать данные ImageList из потока'),
    (English: 'Failed to write ImageList data to stream'; Localized: 'Не удалось записать данные ImageList в поток'),
    (English: 'Error creating window device context'; Localized: 'Ошибка создания контекста устройства окна'),
    (English: 'Error creating window class'; Localized: 'Ошибка создания класса окна'),
    (English: 'Cannot focus a disabled or invisible window'; Localized: 'Невозможно установить фокус на отключённое или невидимое окно'),
    (English: 'Control ''%s'' has no parent window'; Localized: 'Элемент управления ''%s'' не имеет родительского окна'),
    (English: '. Path:'#13#10'%s'; Localized: '. Путь:'#13#10'%s'),
    (English: 'Parent given is not a parent of ''%s'''; Localized: 'Указанный родитель не является родителем ''%s'''),
    (English: 'Cannot hide an MDI Child Form'; Localized: 'Невозможно скрыть дочернюю MDI-форму'),
    (English: 'Cannot change Visible in OnShow or OnHide'; Localized: 'Невозможно изменить Visible в обработчиках OnShow или OnHide'),
    (English: 'Cannot make a visible window modal'; Localized: 'Невозможно сделать видимое окно модальным'),
    (English: 'Scrollbar property out of range'; Localized: 'Свойство полосы прокрутки вне диапазона'),
    (English: '%s property out of range'; Localized: 'Свойство %s вне диапазона'),
    (English: 'Check state can only be set when CheckBoxes is True'; Localized: 'Состояние флажка можно устанавливать только когда CheckBoxes = True'),
    (English: 'Check state incompatible with treeview''s CheckStyles'; Localized: 'Состояние флажка несовместимо со стилем CheckStyles дерева'),
    (English: 'Menu index out of range'; Localized: 'Индекс меню вне диапазона'),
    (English: 'Menu inserted twice'; Localized: 'Меню вставлено дважды'),
    (English: 'Sub-menu is not in menu'; Localized: 'Подменю отсутствует в меню'),
    (English: 'Not enough timers available'; Localized: 'Недостаточно таймеров'),
    (English: 'Printer index out of range'; Localized: 'Индекс принтера вне диапазона'),
    (English: 'Printer selected is not valid'; Localized: 'Выбранный принтер недействителен'),
    (English: '%s on %s'; Localized: '%s на %s'),
    (English: 'GroupIndex cannot be less than a previous menu item''s GroupIndex'; Localized: 'GroupIndex не может быть меньше GroupIndex предыдущего пункта меню'),
    (English: 'Cannot create form. No MDI forms are currently active'; Localized: 'Невозможно создать форму. В данный момент нет активных MDI-форм'),
    (English: 'Can only modify an image if it contains a bitmap'; Localized: 'Можно изменять только изображение, содержащее bitmap'),
    (English: 'A control cannot have itself as its parent'; Localized: 'Элемент управления не может быть своим собственным родителем'),
    (English: 'Control ''%s'' is used on a not main thread'; Localized: 'Элемент управления ''%s'' используется не в главном потоке'),
    (English: '&Yes'; Localized: 'Д&а'),
    (English: '&No'; Localized: '&Нет'),
    (English: '&Close'; Localized: '&Закрыть'),
    (English: '&Ignore'; Localized: 'П&ропустить'),
    (English: '&Retry'; Localized: '&Повторить'),
    (English: '&All'; Localized: 'В&се'),
    (English: 'Cannot drag a form'; Localized: 'Невозможно перетащить форму'),
    (English: 'Metafiles'; Localized: 'Метафайлы'),
    (English: 'Enhanced Metafiles'; Localized: 'Улучшенные метафайлы'),
    (English: 'Icons'; Localized: 'Значки'),
    (English: 'Bitmaps'; Localized: 'Рисунки'),
    (English: 'TIFF Images'; Localized: 'Изображения TIFF'),
    (English: 'Warning'; Localized: 'Предупреждение'),
    (English: 'Error'; Localized: 'Ошибка'),
    (English: 'Information'; Localized: 'Информация'),
    (English: 'Confirm'; Localized: 'Подтверждение'),
    (English: '&Abort'; Localized: 'Пр&ервать'),
    (English: 'N&o to All'; Localized: 'Нет для все&х'),
    (English: 'Yes to &All'; Localized: '&Да для всех'),
    (English: 'BkSp'; Localized: 'BkSp'),
    (English: 'Tab'; Localized: 'Tab'),
    (English: 'Esc'; Localized: 'Esc'),
    (English: 'Enter'; Localized: 'Enter'),
    (English: 'Space'; Localized: 'Space'),
    (English: 'PgUp'; Localized: 'PgUp'),
    (English: 'PgDn'; Localized: 'PgDn'),
    (English: 'End'; Localized: 'End'),
    (English: 'Home'; Localized: 'Home'),
    (English: 'Left'; Localized: 'Left'),
    (English: 'Up'; Localized: 'Up'),
    (English: 'Right'; Localized: 'Right'),
    (English: 'Down'; Localized: 'Down'),
    (English: 'Ins'; Localized: 'Ins'),
    (English: 'Del'; Localized: 'Del'),
    (English: 'Value must be between %d and %d'; Localized: 'Значение должно быть между %d и %d'),
    (English: 'Unable to insert a line'; Localized: 'Невозможно вставить строку'),
    (English: 'Invalid clipboard format'; Localized: 'Неверный формат буфера обмена'),
    (English: 'Clipboard does not support Icons'; Localized: 'Буфер обмена не поддерживает значки'),
    (English: 'Cannot open clipboard: %s'; Localized: 'Не удалось открыть буфер обмена: %s'),
    (English: 'Text exceeds memo capacity'; Localized: 'Текст превышает ёмкость Memo'),
    (English: 'Operation not supported on selected printer'; Localized: 'Операция не поддерживается на выбранном принтере'),
    (English: 'There is no default printer currently selected'; Localized: 'Не выбран принтер по умолчанию'),
    (English: 'Menu ''%s'' is already being used by another form'; Localized: 'Меню ''%s'' уже используется другой формой'),
    (English: 'Other'; Localized: 'Другое'),
    (English: 'Docked control must have a name'; Localized: 'Закреплённый элемент управления должен иметь имя'),
    (English: 'Error removing control from dock tree'; Localized: 'Ошибка удаления элемента управления из дерева закрепления'),
    (English: ' - Dock zone not found'; Localized: ' - Зона закрепления не найдена'),
    (English: ' - Dock zone has no control'; Localized: ' - Зона закрепления не содержит элемент управления'),
    (English: 'Error loading dock zone from the stream. Expecting version %d, but found %d.'; Localized: 'Ошибка загрузки зоны закрепления из потока. Ожидалась версия %d, найдена %d.'),
    (English: 'Multiselect mode must be on for this feature'; Localized: 'Для этой функции должен быть включён режим множественного выбора'),
    (English: 'Length of value array must be >= length of prompt array'; Localized: 'Длина массива значений должна быть >= длины массива подсказок'),
    (English: 'Prompt array must not be empty'; Localized: 'Массив подсказок не может быть пустым'),
    (English: '&Username'; Localized: 'П&ользователь'),
    (English: '&Password'; Localized: '&Пароль'),
    (English: '&Domain'; Localized: '&Домен'),
    (English: 'Login'; Localized: 'Логин'),
    (English: 'Expand'; Localized: 'Раскрыть'),
    (English: 'Separator'; Localized: 'Разделитель'),
    (English: 'Error setting %s.Count'; Localized: 'Ошибка установки %s.Count'),
    (English: 'Listbox (%s) style must be virtual in order to set Count'; Localized: 'Стиль Listbox (%s) должен быть virtual для установки Count'),
    (English: 'No OnGetItem event handler assigned'; Localized: 'Не назначен обработчик события OnGetItem'),
    (English: 'ANSI'; Localized: 'ANSI'),
    (English: 'ASCII'; Localized: 'ASCII'),
    (English: 'Unicode'; Localized: 'Unicode'),
    (English: 'Big Endian Unicode'; Localized: 'Big Endian Unicode'),
    (English: 'UTF-8'; Localized: 'UTF-8'),
    (English: 'UTF-7'; Localized: 'UTF-7'),
    (English: 'Cannot remove shell notification icon'; Localized: 'Невозможно удалить значок уведомления оболочки'),
    (English: '%s requires Windows Vista or later'; Localized: '%s требует Windows Vista или выше'),
    (English: 'Button%d'; Localized: 'Button%d'),
    (English: 'RadioButton%d'; Localized: 'RadioButton%d'),
    (English: 'Caption cannot be empty'; Localized: 'Заголовок не может быть пустым'),
    (English: 'Invalid canvas operation'; Localized: 'Неверная операция с холстом'),
    (English: '%s has no owner'; Localized: '%s не имеет владельца'),
    (English: 'Source and destination require the same owner'; Localized: 'Источник и назначение должны иметь одного владельца'),
    (English: '%s cannot be owned by a different canvas'; Localized: '%s не может принадлежать другому холсту'),
    (English: 'Not a solid color brush'; Localized: 'Не сплошная цветная кисть'),
    (English: 'Invalid brush style'; Localized: 'Неверный стиль кисти'),
    (English: 'Unable to load style ''%s'''; Localized: 'Не удалось загрузить стиль ''%s'''),
    (English: 'Unable to load styles: %s'; Localized: 'Не удалось загрузить стили: %s'),
    (English: 'Style ''%s'' already registered'; Localized: 'Стиль ''%s'' уже зарегистрирован'),
    (English: 'Style class ''%s'' already registered'; Localized: 'Класс стиля ''%s'' уже зарегистрирован'),
    (English: 'Style ''%s'' not found'; Localized: 'Стиль ''%s'' не найден'),
    (English: 'Style class ''%s'' not found'; Localized: 'Класс стиля ''%s'' не найден'),
    (English: 'Invalid style format'; Localized: 'Неверный формат стиля'),
    (English: 'VCL Style File'; Localized: 'Файл VCL Style'),
    (English: 'Class ''%s'' is already registered for ''%s'''; Localized: 'Класс ''%s'' для ''%s'' уже зарегистрирован'),
    (English: 'Class ''%s'' is not registered for ''%s'''; Localized: 'Класс ''%s'' для ''%s''не зарегистрирован'),
    (English: '%s parameter cannot be nil'; Localized: '%s параметр не может быть nil'),
    (English: 'A StyleHook class has not been registered for %s'; Localized: 'Класс StyleHook не зарегистрирован для %s'),
    (English: 'Feature not supported by this style'; Localized: 'Функция не поддерживается этим стилем'),
    (English: 'Cannot call BeginInvoke on a control with no parent or window handle'; Localized: 'Невозможно вызвать BeginInvoke для элемента управления без родителя или дескриптора окна'),
    (English: 'CardPanel card index is out of range'; Localized: 'Индекс карточки CardPanel вне диапазона'),
    (English: 'CardPanel.ActiveCard cannot be nil'; Localized: 'CardPanel.ActiveCard не может быть nil'),
    (English: 'Invalid index'; Localized: 'Недопустимый индекс'),
    (English: 'Unable to insert an item'; Localized: 'Невозможно вставить элемент'),
    (English: 'Invalid owner'; Localized: 'Недопустимый владелец'),
    (English: 'RichEdit line insertion error'; Localized: 'Ошибка вставки строки RichEdit'),
    (English: 'Failed to Load Stream'; Localized: 'Не удалось загрузить поток'),
    (English: 'Failed to Save Stream'; Localized: 'Не удалось сохранить поток'),
    (English: '%s is already associated with %s'; Localized: '%s уже связан с %s'),
    (English: 'This control requires version 4.70 or greater of COMCTL32.DLL'; Localized: 'Этот элемент управления требует COMCTL32.DLL версии 4.70 или выше'),
    (English: 'ListView item can be added only when OwnerData is False.  Use OnData instead.'; Localized: 'Элемент ListView можно добавить только когда OwnerData = False. Используйте событие OnData.'),
    (English: 'This "Portable Network Graphics" image is not valid because it contains invalid pieces of data (crc error)'; Localized: 'Это изображение "Portable Network Graphics" недействительно, так как содержит повреждённые данные (ошибка CRC)'),
    (English: 'The "Portable Network Graphics" image could not be loaded because one of its main piece of data (ihdr) might be corrupted'; Localized: 'Изображение "Portable Network Graphics" не может быть загружено, поскольку один из его основных блоков данных (IHDR) может быть повреждён'),
    (English: 'This "Portable Network Graphics" image is invalid because it has missing image parts.'; Localized: 'Это изображение "Portable Network Graphics" недействительно, так как в нём отсутствуют части изображения.'),
    (English: 'Could not decompress the image because it contains invalid compressed data.'#13#10' Description: '; Localized: 'Не удалось распаковать изображение, поскольку оно содержит повреждённые сжатые данные.'#13#10'Описание: '),
    (English: 'The "Portable Network Graphics" image contains an invalid palette.'; Localized: 'Изображение "Portable Network Graphics" содержит недопустимую палитру.'),
    (English: 'The file being read is not a valid "Portable Network Graphics" image because it contains an invalid header. This file may be corrupted, try obtaining it again'; Localized: 'Файл, который читается, не является корректным изображением "Portable Network Graphics", так как содержит недопустимый заголовок. Файл может быть повреждён, попробуйте получить его заново.'),
    (English: 'This "Portable Network Graphics" image is not supported or it might be invalid.'#13#10'(IHDR chunk is not the first)'; Localized: 'Это изображение "Portable Network Graphics" не поддерживается или недействительно.'#13#10'(Блок IHDR не является первым).'),
    (English: 'This "Portable Network Graphics" image is not supported because either its width or height exceeds the maximum size of 65535 pixels.'; Localized: 'Это изображение "Portable Network Graphics" не поддерживается, так как его ширина или высота превышает максимальный размер 65535 пикселей.'),
    (English: 'There is no such palette entry.'; Localized: 'Такой записи в палитре нет.'),
    (English: 'This "Portable Network Graphics" image contains an unknown critical part which could not be decoded.'; Localized: 'Это изображение "Portable Network Graphics" содержит неизвестную критическую часть, которая не может быть декодирована.'),
    (English: 'This "Portable Network Graphics" image is encoded with an unknown compression scheme which could not be decoded.'; Localized: 'Это изображение "Portable Network Graphics" закодировано неизвестным методом сжатия, который не может быть декодирован.'),
    (English: 'This "Portable Network Graphics" image uses an unknown interlace scheme which could not be decoded.'; Localized: 'Это изображение "Portable Network Graphics" использует неизвестную схему чересстрочной развёртки, которая не может быть декодирована.'),
    (English: 'This "Portable Network Graphics" image uses an unknown color type which could not be decoded.'; Localized: 'Это изображение "Portable Network Graphics" использует неизвестный тип цвета, который не может быть декодирован.'),
    (English: 'The chunks must be compatible to be assigned.'; Localized: 'Блоки должны быть совместимы для присвоения.'),
    (English: 'This "Portable Network Graphics" image is invalid because the decoder found an unexpected end of the file.'; Localized: 'Это изображение "Portable Network Graphics" недействительно, поскольку декодер обнаружил неожиданный конец файла.'),
    (English: 'This "Portable Network Graphics" image contains no data.'; Localized: 'Это изображение "Portable Network Graphics" не содержит данных.'),
    (English: 'The program tried to add a existent critical chunk to the current image which is not allowed.'; Localized: 'Программа попыталась добавить уже существующий критический блок в текущее изображение, что запрещено.'),
    (English: 'It''s not allowed to add a new chunk because the current image is invalid.'; Localized: 'Невозможно добавить новый блок, так как текущее изображение недействительно.'),
    (English: 'Some operation could not be performed because the system is out of resources. Close some windows and try again.'; Localized: 'Некоторые операции не могут быть выполнены, так как система исчерпала ресурсы. Закройте несколько окон и попробуйте снова.'),
    (English: 'Setting bit transparency color is not allowed for png images containing alpha value for each pixel (COLOR_RGBALPHA and COLOR_GRAYSCALEALPHA)'; Localized: 'Установка цвета прозрачности не разрешена для PNG-изображений, содержащих альфа-канал для каждого пикселя (COLOR_RGBALPHA и COLOR_GRAYSCALEALPHA)'),
    (English: 'This operation is not valid because the current image contains no valid header.'; Localized: 'Эта операция недействительна, так как текущее изображение не содержит корректного заголовка.'),
    (English: 'The new size provided for image resizing is invalid.'; Localized: 'Указанный новый размер для изменения изображения недействителен.'),
    (English: 'The "Portable Network Graphics" image could not be loaded because it uses an invalid image bit depth.'; Localized: 'Изображение "Portable Network Graphics" не может быть загружено, так как использует недопустимую глубину цвета.'),
    (English: 'Exception '; Localized: 'Исключение '),
    (English: 'Data cannot be accessed as %s'; Localized: 'Невозможно получить доступ к данным как %s'),
    (English: 'Check'; Localized: 'Отметить'),
    (English: 'Uncheck'; Localized: 'Снять отметку'),
    (English: 'Collapse'; Localized: 'Свернуть'),
    (English: 'Obsolete'; Localized: 'Устаревшие'),
    (English: 'Custom Messages'; Localized: 'Другие сообщения'),
    (English: 'Language Options'; Localized: 'Языковые параметры'),
    (English: 'Messages'; Localized: 'Сообщения'),
    (English: 'Component'; Localized: 'Компонент'),
    (English: 'Directory'; Localized: 'Каталог'),
    (English: 'File'; Localized: 'Файл'),
    (English: 'Icon'; Localized: 'Ярлык'),
    (English: 'INI'; Localized: 'INI'),
    (English: 'Delete'; Localized: 'Удаление'),
    (English: 'ISSig Key'; Localized: 'Ключ ISSig'),
    (English: 'Language'; Localized: 'Язык'),
    (English: 'Registry'; Localized: 'Реестр'),
    (English: 'Task'; Localized: 'Задача'),
    (English: 'Type'; Localized: 'Тип'),
    (English: 'Appearance'; Localized: 'Внешний вид'),
    (English: 'Application Details'; Localized: 'Сведения о приложении'),
    (English: 'Application Directory'; Localized: 'Каталог приложения'),
    (English: 'Applications in Use'; Localized: 'Запущенные приложения'),
    (English: 'Compression'; Localized: 'Компрессия'),
    (English: 'Disk Spanning'; Localized: 'Разделение на диски'),
    (English: 'Installation Pages'; Localized: 'Страницы установки'),
    (English: 'Security'; Localized: 'Безопасность'),
    (English: 'Start Menu Folder'; Localized: 'Папка меню ПУСК'),
    (English: 'System Requirements'; Localized: 'Системные требования'),
    (English: 'Uninstallation'; Localized: 'Деинсталляция'),
    (English: 'User Information'; Localized: 'Информация о пользователе'),
    (English: 'Version Information'; Localized: 'Информация о версии'),
    (English: 'Common'; Localized: 'Общие'));

implementation

end.
