unit IDE.LocalizeFunc.Japanese;

{
  Inno Setup
  Copyright (C) 1997-2026 Jordan Russell
  Portions by Martijn Laan
  For conditions of distribution and use, see LICENSE.TXT.

  Compiler IDE Japanese translations
}

interface

uses
  IDE.LocalizeFunc;

const
  JapaneseIDETranslations: array [0..497] of TTranslationPair = (
    (English: 'Command line usage:'; Localized: 'コマンドラインの使用法:'),
    (English: 'Examples:'; Localized: '使用例:'),
    (English: 'script file'; Localized: 'スクリプトファイル'),
    (English: 'wizard name'; Localized: 'ウィザード名'),
    (English: 'My script'; Localized: 'マイ スクリプト'),
    (English: 'My Script Wizard'; Localized: 'マイ スクリプトウィザード'),
    (English: 'Could not load %1: %2'; Localized: '%1 を読み込めませんでした: %2'),
    (English: 'Inno Setup Compiler'; Localized: 'Inno Setup コンパイラー'),
    (English: 'Example scripts...'; Localized: 'サンプルスクリプト...'),
    (English: 'More files...'; Localized: 'その他のファイル...'),
    (English: 'Untitled'; Localized: '無題'),
    (English: 'Preprocessor Output'; Localized: 'プリプロセッサー出力'),
    (English: 'Run Parameters'; Localized: '実行パラメーター'),
    (English: 'Command line parameters for %1 and %2:'; Localized: '%1 と %2 のコマンドラインパラメーター:'),
    (English: 'Inno Setup Script files'; Localized: 'Inno Setup スクリプトファイル'),
    (English: 'All files'; Localized: 'すべてのファイル'),
    (English: 'Application files'; Localized: 'アプリケーションファイル'),
    (English: 'Documentation files'; Localized: 'ドキュメントファイル'),
    (English: 'Registry files'; Localized: 'レジストリファイル'),
    (English: 'Icon files'; Localized: 'アイコンファイル'),
    (English: 'Inno Setup Script Wizard'; Localized: 'Inno Setup スクリプトウィザード'),
    (English: 'Welcome'; Localized: 'ようこそ'),
    (English: 'Application Information'; Localized: 'アプリケーション情報'),
    (English: 'Please specify some basic information about your application.'; Localized: 'アプリケーションの基本的な情報を指定してください。'),
    (English: 'Application Folder'; Localized: 'アプリケーションフォルダー'),
    (English: 'Please specify folder information about your application.'; Localized: 'アプリケーションのフォルダー情報を指定してください。'),
    (English: 'Application Files'; Localized: 'アプリケーションファイル'),
    (English: 'Please specify the files that are part of your application.'; Localized: 'アプリケーションを構成するファイルを指定してください。'),
    (English: 'Please specify the source folder.'; Localized: 'ソースフォルダーを指定してください。'),
    (English: 'Should files in subfolders of "%1" also be included?'; Localized: '"%1" のサブフォルダー内のファイルも含めますか？'),
    (English: 'URL:'; Localized: 'URL:'),
    (English: 'Is the file to download an archive which should be extracted?'; Localized: 'ダウンロードするファイルは、展開すべきアーカイブですか？'),
    (English: 'Name of the file:'; Localized: 'ファイルの名前:'),
    (English: 'Name of the file (extension should match archive format):'; Localized: 'ファイルの名前 (拡張子はアーカイブ形式と一致する必要があります):'),
    (English: 'Approximate size of the file in megabytes:'; Localized: 'ファイルのおおよそのサイズ (メガバイト):'),
    (English: 'Application File Association'; Localized: 'アプリケーションのファイルの関連付け'),
    (English: 'Please specify which file association should be created for your application.'; Localized: 'アプリケーションに対して作成するファイルの関連付けを指定してください。'),
    (English: '%1 File'; Localized: '%1 ファイル'),
    (English: 'Application Shortcuts'; Localized: 'アプリケーションのショートカット'),
    (English: 'Please specify which shortcuts should be created for your application.'; Localized: 'アプリケーションに対して作成するショートカットを指定してください。'),
    (English: 'Application Documentation'; Localized: 'アプリケーションのドキュメント'),
    (English: 'Please specify which documentation files should be shown by Setup during installation.'; Localized: 'インストール中にセットアップが表示するドキュメントファイルを指定してください。'),
    (English: 'Setup Install Mode'; Localized: 'セットアップのインストールモード'),
    (English: 'Please specify in which install mode Setup should run.'; Localized: 'セットアップを実行するインストールモードを指定してください。'),
    (English: 'Application Registry Keys And Values'; Localized: 'アプリケーションのレジストリキーと値'),
    (English: 'Please specify the registry keys and values that are part of your application.'; Localized: 'アプリケーションを構成するレジストリキーと値を指定してください。'),
    (English: 'Setup Languages'; Localized: 'セットアップの言語'),
    (English: 'Please specify which Setup languages should be included.'; Localized: '含めるセットアップの言語を指定してください。'),
    (English: 'Compiler Settings'; Localized: 'コンパイラー設定'),
    (English: 'Please specify some basic compiler settings.'; Localized: 'コンパイラーの基本的な設定を指定してください。'),
    (English: 'Please specify the folder.'; Localized: 'フォルダーを指定してください。'),
    (English: 'Wizard Style'; Localized: 'ウィザードスタイル'),
    (English: 'Please specify which wizard style should be used.'; Localized: '使用するウィザードスタイルを指定してください。'),
    (English: 'Inno Setup Preprocessor'; Localized: 'Inno Setup プリプロセッサー'),
    (English: 'Please specify whether Inno Setup Preprocessor should be used.'; Localized: 'Inno Setup プリプロセッサーを使用するかどうかを指定してください。'),
    (English: 'The %1 can use %2 compiler directives to simplify your script. Although this is not necessary, it will make it easier to manually change the script later.%n%nDo you want the %1 to use %2 compiler directives?'; Localized: '%1 は、%2 コンパイラーディレクティブを使用してスクリプトを簡素化できます。これは必須ではありませんが、後でスクリプトを手動で変更する作業が容易になります。%n%n%1 で %2 コンパイラーディレクティブを使用しますか？'),
    (English: '&Yes, use %1 compiler directives'; Localized: 'はい、%1 コンパイラーディレクティブを使用する(&Y)'),
    (English: 'Finished'; Localized: '完了'),
    (English: '&Next'; Localized: '次へ(&N)'),
    (English: '&Finish'; Localized: '完了(&F)'),
    (English: 'The %1 is not complete. If you quit now, the new script file will not be generated.%n%nExit anyway?'; Localized: '%1 は完了していません。ここで終了すると、新しいスクリプトファイルは生成されません。%n%nそれでも終了しますか？'),
    (English: 'Please specify the application name.'; Localized: 'アプリケーション名を指定してください。'),
    (English: 'Please specify the application version.'; Localized: 'アプリケーションのバージョンを指定してください。'),
    (English: 'Please specify the application destination base folder.'; Localized: 'アプリケーションのインストール先ベースフォルダーを指定してください。'),
    (English: 'Please specify the application folder name.'; Localized: 'アプリケーションのフォルダー名を指定してください。'),
    (English: 'Please specify the application main executable file.'; Localized: 'アプリケーションのメイン実行ファイルを指定してください。'),
    (English: 'Please specify the application Start Menu group name.'; Localized: 'アプリケーションのスタートメニューのグループ名を指定してください。'),
    (English: 'Please specify the destination base folder.'; Localized: 'インストール先ベースフォルダーを指定してください。'),
    (English: 'Please specify a destination base folder other than the application folder'; Localized: 'アプリケーションフォルダー以外のインストール先ベースフォルダーを指定してください'),
    (English: 'Please select at least one language.'; Localized: '少なくとも 1 つの言語を選択してください。'),
    (English: '&Source URL:'; Localized: 'ソース URL(&S):'),
    (English: 'Script generated by the %1.'; Localized: 'このスクリプトは %1 によって生成されました。'),
    (English: 'SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!'; Localized: 'Inno Setup スクリプトファイルの作成方法の詳細については、ドキュメントを参照してください！'),
    (English: 'NOTE: The value of %1 uniquely identifies this application. Do not use the same %1 value in installers for other applications.'; Localized: '注意: %1 の値はこのアプリケーションを一意に識別します。他のアプリケーションのインストーラーで同じ %1 の値を使用しないでください。'),
    (English: '(To generate a new GUID, click Tools | Generate GUID inside the IDE.)'; Localized: '(新しい GUID を生成するには、IDE 内で「ツール」|「GUID の生成」をクリックしてください。)'),
    (English: '"%1" specifies that Setup cannot run on anything but x64 and Windows 11 on Arm.'; Localized: '"%1" は、セットアップが x64 および Arm 版 Windows 11 以外では実行できないことを指定します。'),
    (English: '"%1" requests that the install be done in "64-bit mode" on x64 or Windows 11 on Arm.'; Localized: '"%1" は、x64 または Arm 版 Windows 11 で「64 ビットモード」でインストールを実行するように要求します。'),
    (English: 'This means it should use the native 64-bit Program Files directory and the 64-bit view of the registry.'; Localized: 'これは、ネイティブの 64 ビット Program Files フォルダーおよびレジストリの 64 ビットビューを使用することを意味します。'),
    (English: 'Uncomment the following line to use a 64-bit installer.'; Localized: '64 ビットインストーラーを使用するには、次の行のコメントを解除してください。'),
    (English: 'Use "%1" if all your archives are .%2 files.'; Localized: 'すべてのアーカイブが .%2 ファイルの場合は "%1" を使用してください。'),
    (English: 'Use "%1" if all your archives are not password-protected.'; Localized: 'すべてのアーカイブがパスワードで保護されていない場合は "%1" を使用してください。'),
    (English: 'Uncomment the following line to run in non administrative install mode (install for current user only).'; Localized: '非管理者インストールモード (現在のユーザーのみにインストール) で実行するには、次の行のコメントを解除してください。'),
    (English: 'Remove the following line to run in administrative install mode (install for all users).'; Localized: '管理者インストールモード (すべてのユーザーにインストール) で実行するには、次の行を削除してください。'),
    (English: 'NOTE: Don''t use "%1" on any shared system files.'; Localized: '注意: 共有システムファイルには "%1" を使用しないでください。'),
    (English: 'NOTE: Use the "%1" flag or the "%2" parameter to verify downloads.'; Localized: '注意: ダウンロードを検証するには、"%1" フラグまたは "%2" パラメーターを使用してください。'),
    (English: 'Registry data from file %1'; Localized: 'ファイル %1 のレジストリデータ'),
    (English: 'COULD NOT IMPORT %1'; Localized: '%1 をインポートできませんでした'),
    (English: 'End of registry data from file %1'; Localized: 'ファイル %1 のレジストリデータの終わり'),
    (English: 'SOME KEYS FILTERED DUE TO %1 SETTINGS!'; Localized: '%1 設定により一部のキーが除外されました！'),
    (English: 'SOME VALUES WITH UNSUPPORTED TYPES SKIPPED!'; Localized: 'サポートされていない型の一部の値がスキップされました！'),
    (English: 'Would you like to compile the new script now?'; Localized: '新しいスクリプトを今すぐコンパイルしますか？'),
    (English: 'My Program'; Localized: 'マイ プログラム'),
    (English: 'My Company, Inc.'; Localized: 'My Company, Inc.'),
    (English: 'Application directory'; Localized: 'アプリケーションフォルダー'),
    (English: 'Program Files directory'; Localized: 'Program Files フォルダー'),
    (English: 'Common Files directory'; Localized: 'Common Files フォルダー'),
    (English: 'Windows directory'; Localized: 'Windows フォルダー'),
    (English: 'Windows system directory'; Localized: 'Windows システムフォルダー'),
    (English: 'Setup source directory'; Localized: 'セットアップソースフォルダー'),
    (English: 'System drive root directory'; Localized: 'システムドライブのルートフォルダー'),
    (English: '(Custom)'; Localized: '(カスタム)'),
    (English: 'Starting compile.%1[%2]'; Localized: 'コンパイルを開始しています。%1[%2]'),
    (English: 'Finished.%1[%2, %3 elapsed]'; Localized: '完了しました。%1[%2, %3 経過]'),
    (English: 'Compile aborted.'; Localized: 'コンパイルを中止しました。'),
    (English: 'Log size limit reached, list reset.'; Localized: 'ログサイズの上限に達したため、リストをリセットしました。'),
    (English: '%1 started'; Localized: '%1 を開始しました'),
    (English: 'Terminating process'; Localized: 'プロセスを終了しています'),
    (English: 'Removing left-over temporary directory: %1'; Localized: '残された一時フォルダーを削除しています: %1'),
    (English: 'Failed to remove temporary directory'; Localized: '一時フォルダーを削除できませんでした'),
    (English: '%1 Call Stack'; Localized: '%1 コール スタック'),
    (English: 'Cannot run Setup at this time. Please compile Setup successfully to completion first, with output enabled'; Localized: '現在セットアップを実行できません。先に出力を有効にして、セットアップを最後まで正常にコンパイルしてください'),
    (English: 'Cannot run Uninstall at this time. Please run Setup successfully to completion first'; Localized: '現在アンインストールを実行できません。先にセットアップを最後まで正常に実行してください'),
    (English: 'Error executing "%1":%n%n%2: %3'; Localized: '"%1" の実行中にエラーが発生しました:%n%n%2: %3'),
    (English: 'Are you sure you want to abort the compile?'; Localized: 'コンパイルを中止してもよろしいですか？'),
    (English: 'File %1:'; Localized: 'ファイル %1:'),
    (English: 'Line %1:'; Localized: '行 %1:'),
    (English: 'Compiler Error'; Localized: 'コンパイラーエラー'),
    (English: 'Illegal null character on line %1'; Localized: '%1 行目に不正な null 文字があります'),
    (English: 'Cannot find "%1"'; Localized: '"%1" が見つかりません'),
    (English: 'Invalid regular expression "%1"'; Localized: '無効な正規表現 "%1"'),
    (English: '%1 (%2 hits):'; Localized: '%1 (%2 ヒット):'),
    (English: 'Find "%1" (%2 hits in %3 files)'; Localized: '"%1" の検索 (%3 ファイル中 %2 ヒット)'),
    (English: '%1 occurrence(s) replaced.'; Localized: '%1 個の出現箇所を置換しました。'),
    (English: 'The .%1 extension was successfully associated for the current user with:%n%2'; Localized: '.%1 拡張子は、現在のユーザーに対して次のものに正常に関連付けられました:%n%2'),
    (English: 'The .%1 extension was successfully associated for all users with:%n%2'; Localized: '.%1 拡張子は、すべてのユーザーに対して次のものに正常に関連付けられました:%n%2'),
    (English: 'Error creating file association:%n%1 - %2'; Localized: 'ファイルの関連付けの作成中にエラーが発生しました:%n%1 - %2'),
    (English: 'Unable to associate for all users without administrative privileges. Do you want to associate only for yourself instead?'; Localized: '管理者権限がないため、すべてのユーザーに対して関連付けることができません。代わりに現在のユーザーに対してのみ関連付けますか？'),
    (English: 'Associate'; Localized: '関連付け'),
    (English: 'Inno Setup Script'; Localized: 'Inno Setup スクリプト'),
    (English: 'Compi&le'; Localized: 'コンパイル(&L)'),
    (English: '&Script has %1'; Localized: 'スクリプトに %1 があります(&S)'),
    (English: 'Script has %1 set'; Localized: 'スクリプトに %1 が設定されています'),
    (English: 'Invalid file format.'; Localized: '無効なファイル形式です。'),
    (English: 'Setup'; Localized: 'セットアップ'),
    (English: 'Your message text.'; Localized: 'メッセージのテキスト。'),
    (English: 'Enter your text here...'; Localized: 'ここにテキストを入力してください...'),
    (English: 'Return values'; Localized: '戻り値'),
    (English: 'Default'; Localized: '既定'),
    (English: 'Shield'; Localized: 'シールド'),
    (English: 'Instruction Text'; Localized: '指示テキスト'),
    (English: 'Message Text'; Localized: 'メッセージテキスト'),
    (English: 'user clicked %1'; Localized: 'ユーザーが %1 をクリックしました'),
    (English: 'OK'; Localized: 'OK'),
    (English: 'Yes'; Localized: 'はい'),
    (English: 'No'; Localized: 'いいえ'),
    (English: 'Cancel'; Localized: 'キャンセル'),
    (English: 'Retry'; Localized: '再試行'),
    (English: 'Ignore'; Localized: '無視'),
    (English: 'Abort'; Localized: '中止'),
    (English: 'Display a message box'; Localized: 'メッセージボックスを表示する'),
    (English: 'Name of the Sign Tool:'; Localized: '署名ツールの名前:'),
    (English: 'Invalid name.'; Localized: '無効な名前です。'),
    (English: 'Duplicate name.'; Localized: '名前が重複しています。'),
    (English: 'Command of the Sign Tool:'; Localized: '署名ツールのコマンド:'),
    (English: 'Invalid command.'; Localized: '無効なコマンドです。'),
    (English: 'The generated GUID will be inserted into the editor at the cursor position. Continue?'; Localized: '生成された GUID は、エディターのカーソル位置に挿入されます。続行しますか？'),
    (English: 'The generated Pascal script will be inserted into the editor at the cursor position, but the cursor is not in the %1 section. Continue anyway?'; Localized: '生成された Pascal スクリプトは、エディターのカーソル位置に挿入されますが、カーソルは %1 セクション内にありません。それでも続行しますか？'),
    (English: 'Classic'; Localized: 'クラシック'),
    (English: 'Visual Studio / Visual Studio Code'; Localized: 'Visual Studio / Visual Studio Code'),
    (English: 'Classic / Visual Studio'; Localized: 'クラシック / Visual Studio'),
    (English: 'Visual Studio Code'; Localized: 'Visual Studio Code'),
    (English: 'Light'; Localized: 'ライト'),
    (English: 'Dark'; Localized: 'ダーク'),
    (English: '&New...'; Localized: '新規(&N)...'),
    (English: '&New'; Localized: '新規(&N)'),
    (English: 'Line %1'; Localized: '行 %1'),
    (English: '%1: %2'; Localized: '%1: %2'),
    (English: 'Back (%1)'; Localized: '戻る (%1)'),
    (English: 'Forward (%1)'; Localized: '進む (%1)'),
    (English: 'Ctrl+'; Localized: 'Ctrl+'),
    (English: 'Shift+'; Localized: 'Shift+'),
    (English: 'Alt+'; Localized: 'Alt+'),
    (English: 'Num %1'; Localized: 'Num %1'),
    (English: '(32-bit)'; Localized: '(32 ビット)'),
    (English: '[Compiling]'; Localized: '[コンパイル中]'),
    (English: '[Running]'; Localized: '[実行中]'),
    (English: '[Paused]'; Localized: '[一時停止中]'),
    (English: 'Read only'; Localized: '読み取り専用'),
    (English: 'Modified'; Localized: '変更あり'),
    (English: 'Overwrite'; Localized: '上書き'),
    (English: 'Insert'; Localized: '挿入'),
    (English: 'Tabs closed: %1'; Localized: '閉じたタブ数: %1'),
    (English: 'Estimated time remaining: %1'; Localized: '推定残り時間: %1'),
    (English: 'Average KB/sec: %1'; Localized: '平均 KB/秒: %1'),
    (English: 'There was an error opening the file. Remove it from the list?'; Localized: 'ファイルを開くときにエラーが発生しました。リストから削除しますか？'),
    (English: 'The text in the %1 file has changed.%n%nDo you want to save the changes?'; Localized: '%1 ファイルのテキストが変更されています。%n%n変更を保存しますか？'),
    (English: 'Please stop the compile process before performing this command.'; Localized: 'このコマンドを実行する前に、コンパイルプロセスを停止してください。'),
    (English: 'A compile is already in progress.'; Localized: 'コンパイルは既に実行中です。'),
    (English: 'The text in the %1 file has changed and must be saved before compiling.%n%nSave the changes and continue?'; Localized: '%1 ファイルのテキストが変更されているため、コンパイル前に保存する必要があります。%n%n変更を保存して続行しますか？'),
    (English: 'Would you like to save the script before compiling?%n%nIf you answer No, the compiled installation will be placed under your My Documents folder by default.'; Localized: 'コンパイル前にスクリプトを保存しますか？%n%n「いいえ」を選択すると、コンパイルされたインストーラーは既定でマイ ドキュメントフォルダーの下に配置されます。'),
    (English: 'The selected file is an %1 file. Go to its tab instead of opening it as the new main file?'; Localized: '選択されたファイルは %1 ファイルです。新しいメインファイルとして開く代わりに、そのタブに移動しますか？'),
    (English: 'The selected file is not available as a tab. Opening as the new main file instead.'; Localized: '選択されたファイルはタブとして利用できません。代わりに新しいメインファイルとして開きます。'),
    (English: 'Error creating file (code %1). Could not save file'; Localized: 'ファイルの作成中にエラーが発生しました (コード %1)。ファイルを保存できませんでした'),
    (English: 'Error creating backup file. Could not save file'; Localized: 'バックアップファイルの作成中にエラーが発生しました。ファイルを保存できませんでした'),
    (English: 'Error removing existing file (code %1). Could not save file'; Localized: '既存のファイルの削除中にエラーが発生しました (コード %1)。ファイルを保存できませんでした'),
    (English: 'Error renaming temporary file (code %1). Could not save file'; Localized: '一時ファイルの名前変更中にエラーが発生しました (コード %1)。ファイルを保存できませんでした'),
    (English: 'Failed to open included file: %1'; Localized: 'インクルードファイルを開けませんでした: %1'),
    (English: 'Cannot start printer document.'; Localized: '印刷ジョブを開始できません。'),
    (English: 'Are you sure you want to clear the list of recently opened files?'; Localized: '最近使ったファイルのリストをクリアしてもよろしいですか？'),
    (English: 'The %1 file has been modified outside of the source editor. You might want to reload it.'; Localized: '%1 ファイルがソースエディター外で変更されました。再読み込みすることをお勧めします。'),
    (English: 'The %1 file has been modified outside of the source editor.%n%nDo you want to reload the file?'; Localized: '%1 ファイルがソースエディター外で変更されました。%n%nファイルを再読み込みしますか？'),
    (English: 'The %1 file has been modified outside of the source editor. Changes have also been made in the source editor.%n%nDo you want to reload the file and lose the changes made in the source editor?'; Localized: '%1 ファイルがソースエディター外で変更されました。ソースエディター内でも変更が行われています。%n%nファイルを再読み込みして、ソースエディターで行った変更を破棄しますか？'),
    (English: 'File not opened.'; Localized: 'ファイルが開かれていません。'),
    (English: 'Go to Line'; Localized: '行へ移動'),
    (English: 'Line number:'; Localized: '行番号:'),
    (English: 'Do you want to copy your current license key to the clipboard before opening our order page? You will need it to be able to renew it.'; Localized: '注文ページを開く前に、現在のライセンスキーをクリップボードにコピーしますか？更新の際に必要になります。'),
    (English: 'New commercial license key has been registered:%n%n%1%n%nThanks for your support!'; Localized: '新しい商用ライセンスキーが登録されました:%n%n%1%n%nご支援ありがとうございます！'),
    (English: 'Are you sure you want to remove your commercial license key and revert to non-commercial use only?'; Localized: '商用ライセンスキーを削除して、非商用利用のみに戻してもよろしいですか？'),
    (English: 'Commercial license key has been removed.'; Localized: '商用ライセンスキーが削除されました。'),
    (English: 'Your version of Inno Setup has been updated! <a id="%1">See what''s new</a>.'; Localized: 'ご使用の Inno Setup のバージョンが更新されました！<a id="%1">新機能を見る</a>。'),
    (English: 'VS Code-style editor shortcuts added! Use the <a id="%1">Editor Keys option</a> in Options dialog.'; Localized: 'VS Code スタイルのエディターショートカットが追加されました！「オプション」ダイアログで <a id="%1">エディターの「キー」オプション</a>を使用してください。'),
    (English: '<a id="%1">Ideas board is open!</a> Share your ideas and vote on others, this month only.'; Localized: '<a id="%1">アイデアボードが公開されました！</a> あなたのアイデアを共有し、他の人のアイデアに投票してください。今月限定です。'),
    (English: 'Running a version released after your update entitlement ended. <a id="%1">Renew license</a>, <a id="%2">remove key</a>, or <a id="%3">exit</a>.'; Localized: 'アップデート権の終了後にリリースされたバージョンを実行しています。<a id="%1">ライセンスを更新</a>、<a id="%2">キーを削除</a>、または <a id="%3">終了</a>。'),
    (English: 'Your update entitlement is ending soon. Please <a id="%1">renew your license</a>. Thanks!'; Localized: 'アップデート権はまもなく終了します。<a id="%1">ライセンスを更新</a>してください。よろしくお願いします！'),
    (English: 'Your update entitlement has ended. Please <a id="%1">renew your license</a>. Thanks!'; Localized: 'アップデート権が終了しました。<a id="%1">ライセンスを更新</a>してください。よろしくお願いします！'),
    (English: 'Using Inno Setup commercially? Please <a id="%1">purchase a license</a>. Thanks!'; Localized: 'Inno Setup を商用利用していますか？<a id="%1">ライセンスを購入</a>してください。よろしくお願いします！'),
    (English: 'Uninstall'; Localized: 'アンインストール'),
    (English: '%1 exit code: 0x%2'; Localized: '%1 の終了コード: 0x%2'),
    (English: '%1 exit code: %2'; Localized: '%1 の終了コード: %2'),
    (English: 'Unable to get %1 exit code (%2 failed)'; Localized: '%1 の終了コードを取得できません (%2 が失敗しました)'),
    (English: '%1 is still running; can''t get exit code'; Localized: '%1 はまだ実行中のため、終了コードを取得できません'),
    (English: 'Please stop the running %1 process before performing this command.'; Localized: 'このコマンドを実行する前に、実行中の %1 プロセスを停止してください。'),
    (English: 'This command will detach the debugger from the running %1 process. Continue?'; Localized: 'このコマンドは、実行中の %1 プロセスからデバッガーを切り離します。続行しますか？'),
    (English: 'The changes you made will not take effect until you re-compile.%n%nContinue running anyway?'; Localized: '行った変更は、再コンパイルするまで反映されません。%n%nこのまま実行を続行しますか？'),
    (English: 'A pause is already pending.'; Localized: '一時停止は既に保留中です。'),
    (English: 'No code was generated for the current line.'; Localized: '現在の行に対して生成されたコードはありません。'),
    (English: 'This will unconditionally terminate the running %1 process. Continue?'; Localized: 'これにより、実行中の %1 プロセスが無条件に強制終了されます。続行しますか？'),
    (English: 'Note that if %1 is currently in the installation phase, any changes made to the system thus far will not be undone, nor will uninstall data be written.'; Localized: '%1 が現在インストールフェーズにある場合、これまでにシステムに加えられた変更は元に戻されず、アンインストール情報も書き込まれないことに注意してください。'),
    (English: 'Evaluate'; Localized: '評価'),
    (English: 'Constant to evaluate (for example, "%1"):'; Localized: '評価する定数 (例: "%1"):'),
    (English: 'Evaluate Result'; Localized: '評価結果'),
    (English: 'Evaluate Error'; Localized: '評価エラー'),
    (English: 'An unknown error occurred.'; Localized: '不明なエラーが発生しました。'),
    (English: '%1 = "%2"'; Localized: '%1 = "%2"'),
    (English: '%1 = Exception: %2'; Localized: '%1 = 例外: %2'),
    (English: '%1 = Unknown error'; Localized: '%1 = 不明なエラー'),
    (English: 'Unknown error'; Localized: '不明なエラー'),
    (English: 'Line %1:%n%2'; Localized: '行 %1:%n%2'),
    (English: 'Runtime Error'; Localized: '実行時エラー'),
    (English: '%1 (Update entitlement ended)'; Localized: '%1 (アップデート権終了)'),
    (English: '%1 (Update entitlement ended but updated anyway)'; Localized: '%1 (アップデート権は終了済みですが更新されました)'),
    (English: 'Non-commercial use only'; Localized: '非商用利用のみ'),
    (English: 'Single User'; Localized: 'Single User'),
    (English: 'Team'; Localized: 'Team'),
    (English: 'Enterprise'; Localized: 'Enterprise'),
    (English: 'Inno Setup %1 License'; Localized: 'Inno Setup %1 ライセンス'),
    (English: '%1, %2.'; Localized: '%1、%2。'),
    (English: 'Includes updates until %1, major and minor.'; Localized: '%1 までのメジャーおよびマイナーアップデートを含みます。'),
    (English: 'Includes all future updates, major and minor.'; Localized: '将来のすべてのメジャーおよびマイナーアップデートを含みます。'),
    (English: '%1 Entries Designer'; Localized: '%1 エントリデザイナー'),
    (English: '&Insert'; Localized: '挿入(&I)'),
    (English: '&Parameters...'; Localized: 'パラメーター(&P)...'),
    (English: 'Remo&ve'; Localized: '削除(&V)'),
    (English: 'Add Fol&der...'; Localized: 'フォルダーの追加(&D)...'),
    (English: '&Add File(s)...'; Localized: 'ファイルの追加(&A)...'),
    (English: '&Files:'; Localized: 'ファイル(&F):'),
    (English: 'D&ownload...'; Localized: 'ダウンロード(&O)...'),
    (English: 'Go to File'; Localized: 'ファイルに移動'),
    (English: 'Enter Commercial License Key'; Localized: '商用ライセンスキーの入力'),
    (English: 'Paste your license key below'; Localized: 'ライセンスキーを下に貼り付けてください'),
    (English: 'Close'; Localized: '閉じる'),
    (English: 'New Main Script (%1)'; Localized: '新しいメインスクリプト (%1)'),
    (English: 'Open Main Script (%1)'; Localized: 'メインスクリプトを開く (%1)'),
    (English: 'Save (%1)'; Localized: '保存 (%1)'),
    (English: 'Stop Compile (%1)'; Localized: 'コンパイルの停止 (%1)'),
    (English: 'Target Setup (%1)'; Localized: 'セットアップをターゲットに設定 (%1)'),
    (English: 'Target Uninstall (%1)'; Localized: 'アンインストールをターゲットに設定 (%1)'),
    (English: 'Help (%1)'; Localized: 'ヘルプ (%1)'),
    (English: 'Main Script'; Localized: 'メインスクリプト'),
    (English: 'Close Banner'; Localized: 'バナーを閉じる'),
    (English: '&File'; Localized: 'ファイル(&F)'),
    (English: '&Open...'; Localized: '開く(&O)...'),
    (English: 'Open &Recent'; Localized: '最近使ったファイル(&R)'),
    (English: '&Clear Recently Opened'; Localized: '最近使ったファイルをクリア(&C)'),
    (English: '&Save'; Localized: '保存(&S)'),
    (English: 'Save &As...'; Localized: '名前を付けて保存(&A)...'),
    (English: 'Save &Encoding'; Localized: 'エンコードを指定して保存(&E)'),
    (English: '&Auto (ANSI or UTF-8)'; Localized: '自動(&A) (ANSI または UTF-8)'),
    (English: '&UTF-8'; Localized: 'UTF-8(&U)'),
    (English: 'UTF-8 with &BOM'; Localized: 'BOM 付き UTF-8(&B)'),
    (English: 'Sa&ve All'; Localized: 'すべて保存(&V)'),
    (English: '&Print...'; Localized: '印刷(&P)...'),
    (English: 'E&xit'; Localized: '終了(&X)'),
    (English: '&Edit'; Localized: '編集(&E)'),
    (English: '&Undo'; Localized: '元に戻す(&U)'),
    (English: '&Redo'; Localized: 'やり直し(&R)'),
    (English: 'Cu&t'; Localized: '切り取り(&T)'),
    (English: '&Copy'; Localized: 'コピー(&C)'),
    (English: '&Paste'; Localized: '貼り付け(&P)'),
    (English: 'De&lete'; Localized: '削除(&L)'),
    (English: 'Select &All'; Localized: 'すべて選択(&A)'),
    (English: 'Add Next &Occurrence'; Localized: '次の出現箇所を追加(&O)'),
    (English: '&Select All Occurrences'; Localized: 'すべての出現箇所を選択(&S)'),
    (English: 'Select All Find &Matches'; Localized: 'すべての検索一致箇所を選択(&M)'),
    (English: '&Find...'; Localized: '検索(&F)...'),
    (English: 'F&ind in Files...'; Localized: 'ファイル内を検索(&I)...'),
    (English: 'Find &Next'; Localized: '次を検索(&N)'),
    (English: 'Find Pre&vious'; Localized: '前を検索(&V)'),
    (English: 'R&eplace...'; Localized: '置換(&E)...'),
    (English: 'Use Regular E&xpressions'; Localized: '正規表現を使用(&X)'),
    (English: 'Fol&d Section'; Localized: 'セクションの折りたたみ(&D)'),
    (English: '&Unfold Section'; Localized: 'セクションの展開(&U)'),
    (English: 'Go to File...'; Localized: 'ファイルに移動...'),
    (English: '&Go to Line...'; Localized: '行へ移動(&G)...'),
    (English: 'Toggle Line Comment'; Localized: '行コメントの切り替え'),
    (English: 'Go To Matching Brace'; Localized: '対応するかっこへ移動'),
    (English: '&View'; Localized: '表示(&V)'),
    (English: '&Zoom'; Localized: 'ズーム(&Z)'),
    (English: 'Zoom &In'; Localized: '拡大(&I)'),
    (English: 'Zoom &Out'; Localized: '縮小(&O)'),
    (English: '&Reset'; Localized: 'リセット(&R)'),
    (English: '&Toolbar'; Localized: 'ツール バー(&T)'),
    (English: 'St&atus Bar'; Localized: 'ステータス バー(&A)'),
    (English: '&Next Tab'; Localized: '次のタブ(&N)'),
    (English: '&Previous Tab'; Localized: '前のタブ(&P)'),
    (English: 'C&lose Tab'; Localized: 'タブを閉じる(&L)'),
    (English: 'Re&open Tab'; Localized: 'タブを再度開く(&O)'),
    (English: 'Reopen &All Tabs'; Localized: 'すべてのタブを再度開く(&A)'),
    (English: 'C&lose Current Tab'; Localized: '現在のタブを閉じる(&L)'),
    (English: '&Compiler Output'; Localized: 'コンパイラー出力(&C)'),
    (English: '&Debug Output'; Localized: 'デバッグ出力(&D)'),
    (English: 'D&ebug Call Stack'; Localized: 'デバッグ コール スタック(&E)'),
    (English: '&Find Results'; Localized: '検索結果(&F)'),
    (English: '&Hide Bottom Pane'; Localized: '下部ペインを非表示(&H)'),
    (English: '&Word Wrap'; Localized: '折り返し(&W)'),
    (English: '&Build'; Localized: 'ビルド(&B)'),
    (English: '&Compile'; Localized: 'コンパイル(&C)'),
    (English: 'S&top Compile'; Localized: 'コンパイルの停止(&T)'),
    (English: '&Low Priority During Compile'; Localized: 'コンパイル中は低優先度(&L)'),
    (English: '&Disable Output'; Localized: '出力を無効化(&D)'),
    (English: 'Disable Co&mpression'; Localized: '圧縮を無効化(&M)'),
    (English: 'Disable &Signing'; Localized: '署名を無効化(&S)'),
    (English: 'Disable Signcheck &Validation'; Localized: '署名チェックの検証を無効化(&V)'),
    (English: '&Open Output Folder'; Localized: '出力フォルダーを開く(&O)'),
    (English: '&Run'; Localized: '実行(&R)'),
    (English: '&Run...'; Localized: '実行(&R)...'),
    (English: 'Run to &Cursor'; Localized: 'カーソル位置まで実行(&C)'),
    (English: 'Step &Into'; Localized: 'ステップ イン(&I)'),
    (English: 'Step &Over'; Localized: 'ステップ オーバー(&O)'),
    (English: 'Step Out'; Localized: 'ステップ アウト'),
    (English: 'Toggle &Breakpoint'; Localized: 'ブレークポイントの切り替え(&B)'),
    (English: '&Delete All Breakpoints'; Localized: 'すべてのブレークポイントを削除(&D)'),
    (English: 'P&ause'; Localized: '一時停止(&A)'),
    (English: '&Terminate'; Localized: '強制終了(&T)'),
    (English: '&Evaluate Constant...'; Localized: '定数の評価(&E)...'),
    (English: 'Target &Setup'; Localized: 'セットアップをターゲットに設定(&S)'),
    (English: 'Target &Uninstall'; Localized: 'アンインストールをターゲットに設定(&U)'),
    (English: '&Tools'; Localized: 'ツール(&T)'),
    (English: '&Add/Remove Programs'; Localized: 'プログラムの追加と削除(&A)'),
    (English: 'Generate &GUID'; Localized: 'GUID の生成(&G)'),
    (English: 'Generate %1 Entries...'; Localized: '%1 エントリの生成...'),
    (English: 'Generate %1 Call...'; Localized: '%1 呼び出しの生成...'),
    (English: '&Configure Sign Tools...'; Localized: '署名ツールの構成(&C)...'),
    (English: '&Options...'; Localized: 'オプション(&O)...'),
    (English: '&Help'; Localized: 'ヘルプ(&H)'),
    (English: 'Purchase or Renew Commercial &License'; Localized: '商用ライセンスの購入または更新(&L)'),
    (English: 'Enter Commercial License &Key...'; Localized: '商用ライセンスキーの入力(&K)...'),
    (English: 'Remove Commercial License Key'; Localized: '商用ライセンスキーの削除'),
    (English: '&Donate'; Localized: '寄付(&D)'),
    (English: '&Keyboard And Mouse Commands'; Localized: 'キーボードとマウスのコマンド(&K)'),
    (English: 'Regular E&xpressions'; Localized: '正規表現(&X)'),
    (English: 'Inno &Setup Documentation'; Localized: 'Inno Setup ドキュメント(&S)'),
    (English: 'Inno Setup &Example Scripts'; Localized: 'Inno Setup サンプルスクリプト(&E)'),
    (English: 'Inno Setup &FAQ'; Localized: 'Inno Setup FAQ(&F)'),
    (English: 'Inno Setup &Mailing List'; Localized: 'Inno Setup メーリングリスト(&M)'),
    (English: 'Inno Setup &Revision History'; Localized: 'Inno Setup 改訂履歴(&R)'),
    (English: 'Inno Setup &Web Site'; Localized: 'Inno Setup Web サイト(&W)'),
    (English: 'Inno Setup &Preprocessor Documentation'; Localized: 'Inno Setup プリプロセッサードキュメント(&P)'),
    (English: '&About Inno Setup'; Localized: 'Inno Setup のバージョン情報(&A)'),
    (English: '%1 Call Designer'; Localized: '%1 呼び出しデザイナー'),
    (English: 'Instruction'; Localized: '指示'),
    (English: 'Message'; Localized: 'メッセージ'),
    (English: 'Text Button1'; Localized: 'ボタン 1 のテキスト'),
    (English: 'Button2'; Localized: 'ボタン 2'),
    (English: 'Button3'; Localized: 'ボタン 3'),
    (English: ' Message '; Localized: ' メッセージ '),
    (English: ' Type'; Localized: ' 種類'),
    (English: 'Suppressible'; Localized: '抑制可能'),
    (English: ' Flags '; Localized: ' フラグ '),
    (English: 'Default button'; Localized: '既定のボタン'),
    (English: ' Icon '; Localized: ' アイコン '),
    (English: ' Buttons '; Localized: ' ボタン '),
    (English: ' Return values '; Localized: ' 戻り値 '),
    (English: '&Preview'; Localized: 'プレビュー(&P)'),
    (English: 'Options'; Localized: 'オプション'),
    (English: ' Miscellaneous '; Localized: ' その他 '),
    (English: 'Show &Welcome dialog at startup'; Localized: '起動時にようこそダイアログを表示(&W)'),
    (English: 'Use the Inno Setup &Script Wizard'; Localized: 'Inno Setup スクリプトウィザードを使用(&S)'),
    (English: 'Automatically sa&ve before compiling'; Localized: 'コンパイル前に自動的に保存(&V)'),
    (English: 'Create &backups when saving'; Localized: '保存時にバックアップを作成(&B)'),
    (English: 'Allow &Undo after save'; Localized: '保存後に元に戻すことを許可(&U)'),
    (English: 'Display &full path in title bar'; Localized: 'タイトル バーに完全なパスを表示(&F)'),
    (English: '&Pause on exceptions'; Localized: '例外発生時に一時停止(&P)'),
    (English: 'Always &launch Setup/Uninstall as administrator'; Localized: 'セットアップ/アンインストールを常に管理者として起動(&L)'),
    (English: 'Colori&ze "Compiler Output" view'; Localized: '「コンパイラー出力」ビューに色を付ける(&Z)'),
    (English: 'Automatically open %1 files'; Localized: '%1 ファイルを自動的に開く'),
    (English: 'Automatically show preprocessor output'; Localized: 'プリプロセッサー出力を自動的に表示'),
    (English: 'Menu &keys:'; Localized: 'メニューキー(&K):'),
    (English: 'Automatically reload files'; Localized: 'ファイルを自動的に再読み込み'),
    (English: 'Allow Undo after reload'; Localized: '再読み込み後に元に戻すことを許可'),
    (English: 'Keep new %1 files closed'; Localized: '新しい %1 ファイルを閉じたままにする'),
    (English: ' Editor '; Localized: ' エディター '),
    (English: 'Invoke autoco&mplete automatically'; Localized: 'オートコンプリートを自動的に呼び出す(&M)'),
    (English: 'Use syntax &highlighting'; Localized: '構文の強調表示を使用(&H)'),
    (English: 'U&nderline syntax errors'; Localized: '構文エラーに下線を引く(&N)'),
    (English: 'Allow cursor to move beyond &end of lines'; Localized: 'カーソルが行末を越えて移動することを許可(&E)'),
    (English: 'Enable section f&olding'; Localized: 'セクションの折りたたみを有効化(&O)'),
    (English: 'Use tab cha&racter'; Localized: 'タブ文字を使用(&R)'),
    (English: 'Auto &indent mode'; Localized: '自動インデントモード(&I)'),
    (English: 'Show indentation &guides'; Localized: 'インデント ガイドを表示(&G)'),
    (English: 'Font:'; Localized: 'フォント:'),
    (English: 'AaBbXxZz'; Localized: 'AaBbXxZz'),
    (English: '&Change...'; Localized: '変更(&C)...'),
    (English: '&Tab Width:'; Localized: 'タブ幅(&T):'),
    (English: 'Show &line numbers in gutter'; Localized: 'ガターに行番号を表示(&L)'),
    (English: 'T&heme:'; Localized: 'テーマ(&H):'),
    (English: 'Highlight occurrences of current selection'; Localized: '現在の選択範囲の出現箇所を強調表示'),
    (English: 'Highlight occurrences of current wor&d'; Localized: '現在の単語の出現箇所を強調表示(&D)'),
    (English: 'Ke&ys:'; Localized: 'キー(&Y):'),
    (English: 'Show whitespace'; Localized: '空白文字を表示'),
    (English: 'Smart Home key'; Localized: 'スマート Home キー'),
    (English: '&Associate .%1 files with this compiler'; Localized: '.%1 ファイルをこのコンパイラーに関連付ける(&A)'),
    (English: '&Windows registry file (.%1) to import:'; Localized: 'インポートする Windows レジストリファイル (.%1)(&W):'),
    (English: 'B&rowse...'; Localized: '参照(&R)...'),
    (English: 'Settings (for all keys and values):'; Localized: '設定 (すべてのキーと値に対して):'),
    (English: 'Also delete keys which are not empty'; Localized: '空でないキーも削除する'),
    (English: 'Delete keys which are empty on uninstall'; Localized: 'アンインストール時に空のキーを削除する'),
    (English: 'Delete values on uninstall'; Localized: 'アンインストール時に値を削除する'),
    (English: 'Minimum Windows version:'; Localized: 'Windows の最小バージョン:'),
    (English: 'Configure Sign Tools'; Localized: '署名ツールの構成'),
    (English: ' Sign Tools '; Localized: ' 署名ツール '),
    (English: '&Add...'; Localized: '追加(&A)...'),
    (English: '&Edit...'; Localized: '編集(&E)...'),
    (English: 'Be notified by e-mail of new Inno Setup releases'; Localized: '新しい Inno Setup のリリース通知を電子メールで受け取る'),
    (English: 'Subscribe'; Localized: '登録'),
    (English: ' New file '; Localized: ' 新しいファイル '),
    (English: 'Create a new &empty script file'; Localized: '新しい空のスクリプトファイルを作成(&E)'),
    (English: 'Create a new script file using the &Script Wizard'; Localized: 'スクリプトウィザードを使用して新しいスクリプトファイルを作成(&S)'),
    (English: ' Open file '; Localized: ' ファイルを開く '),
    (English: 'Open an e&xisting script file'; Localized: '既存のスクリプトファイルを開く(&X)'),
    (English: '&Don''t show this dialog again'; Localized: 'このダイアログを再度表示しない(&D)'),
    (English: 'Script Wizard File'; Localized: 'スクリプトウィザードファイル'),
    (English: 'bold'; Localized: '太字'),
    (English: ' = required'; Localized: ' = 必須'),
    (English: ' Destination '; Localized: ' インストール先 '),
    (English: 'Destination &base folder:'; Localized: 'インストール先ベースフォルダー(&B):'),
    (English: 'Destination &subfolder:'; Localized: 'インストール先サブフォルダー(&S):'),
    (English: 'Destination &name:'; Localized: 'インストール先の名前(&N):'),
    (English: ' Source '; Localized: ' ソース '),
    (English: '&Source file or folder:'; Localized: 'ソースファイルまたはフォルダー(&S):'),
    (English: '&Recurse subfolders'; Localized: 'サブフォルダーを再帰的に処理(&R)'),
    (English: '&Include empty subfolders'; Localized: '空のサブフォルダーを含める(&I)'),
    (English: '&Extract archive'; Localized: 'アーカイブを展開(&E)'),
    (English: 'Welcome to the %1'; Localized: '%1 へようこそ'),
    (English: 'This wizard will guide you through the process of creating a new Inno Setup script file. The results will be used to generate a new script file which can be compiled directly or saved on disk for later use.'; Localized: 'このウィザードは、新しい Inno Setup スクリプトファイルを作成する手順をご案内します。入力内容は、直接コンパイルすることも、後で使用するためにディスクに保存することもできる新しいスクリプトファイルの生成に使用されます。'),
    (English: 'Not all features of Inno Setup are covered by this wizard. See the documentation for details on creating Inno Setup script files.%n%nClick Next to continue, or Cancel to exit this wizard.'; Localized: 'Inno Setup のすべての機能がこのウィザードでカバーされているわけではありません。Inno Setup スクリプトファイルの作成方法の詳細については、ドキュメントを参照してください。%n%n続行するには「次へ」を、このウィザードを終了するには「キャンセル」をクリックしてください。'),
    (English: 'Application na&me:'; Localized: 'アプリケーション名(&M):'),
    (English: 'Application &version:'; Localized: 'アプリケーションのバージョン(&V):'),
    (English: 'Application &publisher:'; Localized: 'アプリケーションの発行元(&P):'),
    (English: 'Application &website:'; Localized: 'アプリケーションの Web サイト(&W):'),
    (English: 'Application folder na&me:'; Localized: 'アプリケーションフォルダー名(&M):'),
    (English: 'Application &destination base folder:'; Localized: 'アプリケーションのインストール先ベースフォルダー(&D):'),
    (English: 'Other:'; Localized: 'その他:'),
    (English: 'Allow user to &change the application folder'; Localized: 'ユーザーがアプリケーションフォルダーを変更できるようにする(&C)'),
    (English: 'The application doe&sn''t need a folder'; Localized: 'アプリケーションにフォルダーは不要(&S)'),
    (English: 'Other application &files:'; Localized: 'その他のアプリケーションファイル(&F):'),
    (English: 'Application &main executable file:'; Localized: 'アプリケーションのメイン実行ファイル(&M):'),
    (English: 'Allow &user to start the application after Setup has finished'; Localized: 'セットアップ完了後にユーザーがアプリケーションを起動できるようにする(&U)'),
    (English: 'The application doe&sn''t have a main executable file'; Localized: 'アプリケーションにメイン実行ファイルがない(&S)'),
    (English: 'Application file type na&me:'; Localized: 'アプリケーションのファイルの種類の名前(&M):'),
    (English: '&Associate a file type to the main executable'; Localized: 'メイン実行ファイルにファイルの種類を関連付ける(&A)'),
    (English: 'Application file type &extension:'; Localized: 'アプリケーションのファイルの種類の拡張子(&E):'),
    (English: 'Application &Start Menu folder name:'; Localized: 'アプリケーションのスタートメニューフォルダー名(&S):'),
    (English: 'Other shortcuts to the main executable:'; Localized: 'メイン実行ファイルへのその他のショートカット:'),
    (English: 'Allow user to &change the Start Menu folder name'; Localized: 'ユーザーがスタートメニューフォルダー名を変更できるようにする(&C)'),
    (English: 'Allow user to &disable Start Menu folder creation'; Localized: 'ユーザーがスタートメニューフォルダーの作成を無効にできるようにする(&D)'),
    (English: 'Allow user to create a deskto&p shortcut'; Localized: 'ユーザーがデスクトップショートカットを作成できるようにする(&P)'),
    (English: 'Create an &Uninstall shortcut in the Start Menu folder'; Localized: 'スタートメニューフォルダーにアンインストールのショートカットを作成(&U)'),
    (English: 'Create an &Internet shortcut in the Start Menu folder'; Localized: 'スタートメニューフォルダーにインターネットショートカットを作成(&I)'),
    (English: '&Create a shortcut to the main executable in the Start Menu Programs folder'; Localized: 'スタートメニューのプログラムフォルダーにメイン実行ファイルへのショートカットを作成(&C)'),
    (English: '&License file:'; Localized: 'ライセンスファイル(&L):'),
    (English: '&Information file shown before installation:'; Localized: 'インストール前に表示する情報ファイル(&I):'),
    (English: 'Information file shown &after installation:'; Localized: 'インストール後に表示する情報ファイル(&A):'),
    (English: 'Install mode:'; Localized: 'インストールモード:'),
    (English: '&Administrative install mode (install for all users)'; Localized: '管理者インストールモード(&A) (すべてのユーザーにインストール)'),
    (English: 'Non a&dministrative install mode (install for current user only)'; Localized: '非管理者インストールモード(&D) (現在のユーザーのみにインストール)'),
    (English: 'Allow user to &override the install mode via the command line'; Localized: 'ユーザーがコマンドラインでインストールモードを上書きできるようにする(&O)'),
    (English: 'Ask the user to &choose the install mode at startup'; Localized: '起動時にユーザーにインストールモードの選択を求める(&C)'),
    (English: '&Languages:'; Localized: '言語(&L):'),
    (English: '&Deselect All'; Localized: 'すべて選択解除(&D)'),
    (English: 'Custom compiler output fol&der:'; Localized: 'カスタムコンパイラー出力フォルダー(&D):'),
    (English: 'Compiler output base &file name:'; Localized: 'コンパイラー出力のベースファイル名(&F):'),
    (English: 'Custom Setup &icon file:'; Localized: 'カスタムセットアップアイコンファイル(&I):'),
    (English: 'Setup &password:'; Localized: 'セットアップパスワード(&P):'),
    (English: 'Use the password to &encrypt the application files'; Localized: 'パスワードを使用してアプリケーションファイルを暗号化(&E)'),
    (English: '&Wizard style:'; Localized: 'ウィザードスタイル(&W):'),
    (English: 'You have successfully completed the %1.%n%nTo close this wizard and generate the new script file, click Finish.'; Localized: '%1 が正常に完了しました。%n%nこのウィザードを閉じて新しいスクリプトファイルを生成するには、「完了」をクリックしてください。'),
    (English: '&Back'; Localized: '戻る(&B)'));

implementation

end.
