unit IDE.LocalizeFunc.Czech;

{
  Inno Setup
  Copyright (C) 1997-2026 Jordan Russell
  Portions by Martijn Laan
  For conditions of distribution and use, see LICENSE.TXT.

  Compiler IDE Czech translations
}

interface

uses
  IDE.LocalizeFunc;

const
  CzechIDETranslations: array [0..495] of TTranslationPair = (
    (English: 'Command line usage:'; Localized: 'Použití příkazového řádku:'),
    (English: 'Examples:'; Localized: 'Příklady:'),
    (English: 'script file'; Localized: 'soubor skriptu'),
    (English: 'wizard name'; Localized: 'název průvodce'),
    (English: 'My script'; Localized: 'Můj skript'),
    (English: 'My Script Wizard'; Localized: 'Můj průvodce skriptem'),
    (English: 'Could not load %1: %2'; Localized: 'Nelze načíst %1: %2'),
    (English: 'Inno Setup Compiler'; Localized: 'Inno Setup Compiler'),
    (English: 'Example scripts...'; Localized: 'Ukázkové skripty...'),
    (English: 'More files...'; Localized: 'Další soubory...'),
    (English: 'Untitled'; Localized: 'Bez názvu'),
    (English: 'Preprocessor Output'; Localized: 'Výstup preprocesoru'),
    (English: 'Run Parameters'; Localized: 'Parametry spuštění'),
    (English: 'Command line parameters for %1 and %2:'; Localized: 'Parametry příkazového řádku pro %1 a %2:'),
    (English: 'Inno Setup Script files'; Localized: 'Soubory skriptů Inno Setup'),
    (English: 'All files'; Localized: 'Všechny soubory'),
    (English: 'Application files'; Localized: 'Soubory aplikace'),
    (English: 'Documentation files'; Localized: 'Soubory dokumentace'),
    (English: 'Registry files'; Localized: 'Soubory registru'),
    (English: 'Icon files'; Localized: 'Soubory ikon'),
    (English: 'Inno Setup Script Wizard'; Localized: 'Průvodce skriptem Inno Setup'),
    (English: 'Welcome'; Localized: 'Vítejte'),
    (English: 'Application Information'; Localized: 'Informace o aplikaci'),
    (English: 'Please specify some basic information about your application.'; Localized: 'Zadejte základní informace o své aplikaci.'),
    (English: 'Application Folder'; Localized: 'Složka aplikace'),
    (English: 'Please specify folder information about your application.'; Localized: 'Zadejte informace o složce své aplikace.'),
    (English: 'Application Files'; Localized: 'Soubory aplikace'),
    (English: 'Please specify the files that are part of your application.'; Localized: 'Zadejte soubory, které jsou součástí vaší aplikace.'),
    (English: 'Please specify the source folder.'; Localized: 'Zadejte zdrojovou složku.'),
    (English: 'Should files in subfolders of "%1" also be included?'; Localized: 'Mají být zahrnuty také soubory v podsložkách "%1"?'),
    (English: 'URL:'; Localized: 'URL:'),
    (English: 'Is the file to download an archive which should be extracted?'; Localized: 'Je soubor ke stažení archiv, který se má extrahovat?'),
    (English: 'Name of the file:'; Localized: 'Název souboru:'),
    (English: 'Name of the file (extension should match archive format):'; Localized: 'Název souboru (přípona by měla odpovídat formátu archivu):'),
    (English: 'Approximate size of the file in megabytes:'; Localized: 'Přibližná velikost souboru v megabajtech:'),
    (English: 'Application File Association'; Localized: 'Přidružení souboru aplikace'),
    (English: 'Please specify which file association should be created for your application.'; Localized: 'Zadejte, které přidružení souboru se má pro vaši aplikaci vytvořit.'),
    (English: '%1 File'; Localized: 'Soubor %1'),
    (English: 'Application Shortcuts'; Localized: 'Zástupci aplikace'),
    (English: 'Please specify which shortcuts should be created for your application.'; Localized: 'Zadejte, kteří zástupci se mají pro vaši aplikaci vytvořit.'),
    (English: 'Application Documentation'; Localized: 'Dokumentace aplikace'),
    (English: 'Please specify which documentation files should be shown by Setup during installation.'; Localized: 'Zadejte, které soubory dokumentace má Setup zobrazit během instalace.'),
    (English: 'Setup Install Mode'; Localized: 'Režim instalace'),
    (English: 'Please specify in which install mode Setup should run.'; Localized: 'Zadejte, ve kterém režimu instalace má Setup běžet.'),
    (English: 'Application Registry Keys And Values'; Localized: 'Klíče a hodnoty registru aplikace'),
    (English: 'Please specify the registry keys and values that are part of your application.'; Localized: 'Zadejte klíče a hodnoty registru, které jsou součástí vaší aplikace.'),
    (English: 'Setup Languages'; Localized: 'Jazyky instalace'),
    (English: 'Please specify which Setup languages should be included.'; Localized: 'Zadejte, které jazyky instalace mají být zahrnuty.'),
    (English: 'Compiler Settings'; Localized: 'Nastavení kompilátoru'),
    (English: 'Please specify some basic compiler settings.'; Localized: 'Zadejte základní nastavení kompilátoru.'),
    (English: 'Please specify the folder.'; Localized: 'Zadejte složku.'),
    (English: 'Wizard Style'; Localized: 'Styl průvodce'),
    (English: 'Please specify which wizard style should be used.'; Localized: 'Zadejte, který styl průvodce se má použít.'),
    (English: 'Inno Setup Preprocessor'; Localized: 'Inno Setup Preprocessor'),
    (English: 'Please specify whether Inno Setup Preprocessor should be used.'; Localized: 'Zadejte, zda se má použít Inno Setup Preprocessor.'),
    (English: 'The %1 can use %2 compiler directives to simplify your script. Although this is not necessary, it will make it easier to manually change the script later.%n%nDo you want the %1 to use %2 compiler directives?'; Localized: '%1 může pro zjednodušení vašeho skriptu používat direktivy kompilátoru %2. I když to není nutné, usnadní to pozdější ruční úpravy skriptu.%n%nMá %1 používat direktivy kompilátoru %2?'),
    (English: '&Yes, use %1 compiler directives'; Localized: '&Ano, používat direktivy kompilátoru %1'),
    (English: 'Finished'; Localized: 'Dokončeno'),
    (English: '&Next'; Localized: '&Další'),
    (English: '&Finish'; Localized: '&Dokončit'),
    (English: 'The %1 is not complete. If you quit now, the new script file will not be generated.%n%nExit anyway?'; Localized: '%1 není dokončen. Pokud nyní skončíte, nový soubor skriptu nebude vygenerován.%n%nPřesto ukončit?'),
    (English: 'Please specify the application name.'; Localized: 'Zadejte název aplikace.'),
    (English: 'Please specify the application version.'; Localized: 'Zadejte verzi aplikace.'),
    (English: 'Please specify the application destination base folder.'; Localized: 'Zadejte cílovou základní složku aplikace.'),
    (English: 'Please specify the application folder name.'; Localized: 'Zadejte název složky aplikace.'),
    (English: 'Please specify the application main executable file.'; Localized: 'Zadejte hlavní spustitelný soubor aplikace.'),
    (English: 'Please specify the application Start Menu group name.'; Localized: 'Zadejte název složky aplikace v nabídce Start.'),
    (English: 'Please specify the destination base folder.'; Localized: 'Zadejte cílovou základní složku.'),
    (English: 'Please specify a destination base folder other than the application folder'; Localized: 'Zadejte jinou cílovou základní složku než složku aplikace'),
    (English: 'Please select at least one language.'; Localized: 'Vyberte alespoň jeden jazyk.'),
    (English: '&Source URL:'; Localized: '&Zdrojová URL:'),
    (English: 'Script generated by the %1.'; Localized: 'Tento skript vytvořil %1.'),
    (English: 'SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!'; Localized: 'PODROBNOSTI O VYTVÁŘENÍ SOUBORŮ SKRIPTŮ INNO SETUP NAJDETE V DOKUMENTACI!'),
    (English: 'NOTE: The value of %1 uniquely identifies this application. Do not use the same %1 value in installers for other applications.'; Localized: 'POZNÁMKA: Hodnota %1 jednoznačně identifikuje tuto aplikaci. Nepoužívejte stejnou hodnotu %1 v instalátorech jiných aplikací.'),
    (English: '(To generate a new GUID, click Tools | Generate GUID inside the IDE.)'; Localized: '(Chcete-li vygenerovat nový GUID, klikněte v IDE na Nástroje | Vygenerovat GUID.)'),
    (English: '"%1" specifies that Setup cannot run on anything but x64 and Windows 11 on Arm.'; Localized: '"%1" určuje, že Setup může běžet pouze na x64 a Windows 11 on Arm.'),
    (English: '"%1" requests that the install be done in "64-bit mode" on x64 or Windows 11 on Arm.'; Localized: '"%1" požaduje, aby instalace proběhla v "64bitovém režimu" na x64 nebo Windows 11 on Arm.'),
    (English: 'This means it should use the native 64-bit Program Files directory and the 64-bit view of the registry.'; Localized: 'To znamená, že by se měl použít nativní 64bitový adresář Program Files a 64bitové zobrazení registru.'),
    (English: 'Uncomment the following line to use a 64-bit installer.'; Localized: 'Zrušte komentář u následujícího řádku, chcete-li použít 64bitový instalátor.'),
    (English: 'Use "%1" if all your archives are .%2 files.'; Localized: 'Použijte "%1", pokud jsou všechny vaše archivy soubory .%2.'),
    (English: 'Use "%1" if all your archives are not password-protected.'; Localized: 'Použijte "%1", pokud žádný z vašich archivů není chráněn heslem.'),
    (English: 'Uncomment the following line to run in non administrative install mode (install for current user only).'; Localized: 'Zrušte komentář u následujícího řádku, chcete-li spustit instalaci v režimu bez práv správce (instalace jen pro aktuálního uživatele).'),
    (English: 'Remove the following line to run in administrative install mode (install for all users).'; Localized: 'Odeberte následující řádek, chcete-li spustit instalaci v režimu pro správce (instalace pro všechny uživatele).'),
    (English: 'NOTE: Don''t use "%1" on any shared system files.'; Localized: 'POZNÁMKA: Nepoužívejte "%1" u žádných sdílených systémových souborů.'),
    (English: 'NOTE: Use the "%1" flag or the "%2" parameter to verify downloads.'; Localized: 'POZNÁMKA: K ověření stažených souborů použijte příznak "%1" nebo parametr "%2".'),
    (English: 'Registry data from file %1'; Localized: 'Data registru ze souboru %1'),
    (English: 'COULD NOT IMPORT %1'; Localized: 'NELZE IMPORTOVAT %1'),
    (English: 'End of registry data from file %1'; Localized: 'Konec dat registru ze souboru %1'),
    (English: 'SOME KEYS FILTERED DUE TO %1 SETTINGS!'; Localized: 'NĚKTERÉ KLÍČE BYLY ODFILTROVÁNY KVŮLI NASTAVENÍ %1!'),
    (English: 'SOME VALUES WITH UNSUPPORTED TYPES SKIPPED!'; Localized: 'NĚKTERÉ HODNOTY S NEPODPOROVANÝMI TYPY BYLY PŘESKOČENY!'),
    (English: 'Would you like to compile the new script now?'; Localized: 'Chcete nyní nový skript zkompilovat?'),
    (English: 'My Program'; Localized: 'Můj program'),
    (English: 'My Company, Inc.'; Localized: 'My Company, Inc.'),
    (English: 'Application directory'; Localized: 'Adresář aplikace'),
    (English: 'Program Files directory'; Localized: 'Adresář Program Files'),
    (English: 'Common Files directory'; Localized: 'Adresář Common Files'),
    (English: 'Windows directory'; Localized: 'Adresář Windows'),
    (English: 'Windows system directory'; Localized: 'Systémový adresář Windows'),
    (English: 'Setup source directory'; Localized: 'Zdrojový adresář instalace'),
    (English: 'System drive root directory'; Localized: 'Kořenový adresář systémového disku'),
    (English: '(Custom)'; Localized: '(Vlastní)'),
    (English: 'Starting compile.%1[%2]'; Localized: 'Spouští se kompilace.%1[%2]'),
    (English: 'Finished.%1[%2, %3 elapsed]'; Localized: 'Dokončeno.%1[%2, uplynulo %3]'),
    (English: 'Compile aborted.'; Localized: 'Kompilace přerušena.'),
    (English: 'Log size limit reached, list reset.'; Localized: 'Dosažen limit velikosti protokolu, seznam byl vynulován.'),
    (English: '%1 started'; Localized: '%1 spuštěn'),
    (English: 'Terminating process'; Localized: 'Ukončování procesu'),
    (English: 'Removing left-over temporary directory: %1'; Localized: 'Odebírání zbylého dočasného adresáře: %1'),
    (English: 'Failed to remove temporary directory'; Localized: 'Nepodařilo se odebrat dočasný adresář'),
    (English: '%1 Call Stack'; Localized: 'Zásobník volání %1'),
    (English: 'Cannot run Setup at this time. Please compile Setup successfully to completion first, with output enabled'; Localized: 'Setup nyní nelze spustit. Nejprve úspěšně zkompilujte Setup až do konce se zapnutým výstupem'),
    (English: 'Cannot run Uninstall at this time. Please run Setup successfully to completion first'; Localized: 'Uninstall nyní nelze spustit. Nejprve úspěšně spusťte Setup až do konce'),
    (English: 'Error executing "%1":%n%n%2: %3'; Localized: 'Chyba při spuštění "%1":%n%n%2: %3'),
    (English: 'Are you sure you want to abort the compile?'; Localized: 'Opravdu chcete přerušit kompilaci?'),
    (English: 'File %1:'; Localized: 'Soubor %1:'),
    (English: 'Line %1:'; Localized: 'Řádek %1:'),
    (English: 'Compiler Error'; Localized: 'Chyba kompilátoru'),
    (English: 'Illegal null character on line %1'; Localized: 'Neplatný nulový znak na řádku %1'),
    (English: 'Cannot find "%1"'; Localized: 'Nelze najít "%1"'),
    (English: 'Invalid regular expression "%1"'; Localized: 'Neplatný regulární výraz "%1"'),
    (English: '%1 (%2 hits):'; Localized: '%1 (počet výskytů: %2):'),
    (English: 'Find "%1" (%2 hits in %3 files)'; Localized: 'Najít "%1" (počet výskytů: %2, počet souborů: %3)'),
    (English: '%1 occurrence(s) replaced.'; Localized: 'Počet nahrazených výskytů: %1.'),
    (English: 'The .%1 extension was successfully associated for the current user with:%n%2'; Localized: 'Přípona .%1 byla úspěšně přidružena pro aktuálního uživatele k:%n%2'),
    (English: 'The .%1 extension was successfully associated for all users with:%n%2'; Localized: 'Přípona .%1 byla úspěšně přidružena pro všechny uživatele k:%n%2'),
    (English: 'Error creating file association:%n%1 - %2'; Localized: 'Chyba při vytváření přidružení souboru:%n%1 - %2'),
    (English: 'Unable to associate for all users without administrative privileges. Do you want to associate only for yourself instead?'; Localized: 'Bez oprávnění správce nelze přidružit pro všechny uživatele. Chcete místo toho přidružit jen pro sebe?'),
    (English: 'Associate'; Localized: 'Přidružit'),
    (English: 'Inno Setup Script'; Localized: 'Skript Inno Setup'),
    (English: 'Compi&le'; Localized: 'Kompi&lovat'),
    (English: '&Script has %1'; Localized: '&Skript obsahuje %1'),
    (English: 'Script has %1 set'; Localized: 'Skript má nastaveno %1'),
    (English: 'Invalid file format.'; Localized: 'Neplatný formát souboru.'),
    (English: 'Setup'; Localized: 'Setup'),
    (English: 'Your message text.'; Localized: 'Text vaší zprávy.'),
    (English: 'Enter your text here...'; Localized: 'Sem zadejte text...'),
    (English: 'Return values'; Localized: 'Návratové hodnoty'),
    (English: 'Default'; Localized: 'Výchozí'),
    (English: 'Shield'; Localized: 'Štít'),
    (English: 'Instruction Text'; Localized: 'Text pokynu'),
    (English: 'Message Text'; Localized: 'Text zprávy'),
    (English: 'user clicked %1'; Localized: 'uživatel klikl na %1'),
    (English: 'OK'; Localized: 'OK'),
    (English: 'Yes'; Localized: 'Ano'),
    (English: 'No'; Localized: 'Ne'),
    (English: 'Cancel'; Localized: 'Zrušit'),
    (English: 'Retry'; Localized: 'Opakovat'),
    (English: 'Ignore'; Localized: 'Ignorovat'),
    (English: 'Abort'; Localized: 'Přerušit'),
    (English: 'Display a message box'; Localized: 'Zobrazit okno se zprávou'),
    (English: 'Name of the Sign Tool:'; Localized: 'Název nástroje pro podepisování:'),
    (English: 'Invalid name.'; Localized: 'Neplatný název.'),
    (English: 'Duplicate name.'; Localized: 'Duplicitní název.'),
    (English: 'Command of the Sign Tool:'; Localized: 'Příkaz nástroje pro podepisování:'),
    (English: 'Invalid command.'; Localized: 'Neplatný příkaz.'),
    (English: 'The generated GUID will be inserted into the editor at the cursor position. Continue?'; Localized: 'Vygenerovaný GUID bude vložen do editoru na pozici kurzoru. Pokračovat?'),
    (English: 'The generated Pascal script will be inserted into the editor at the cursor position, but the cursor is not in the %1 section. Continue anyway?'; Localized: 'Vygenerovaný skript Pascal bude vložen do editoru na pozici kurzoru, ale kurzor není v sekci %1. Přesto pokračovat?'),
    (English: 'Classic'; Localized: 'Klasické'),
    (English: 'Visual Studio / Visual Studio Code'; Localized: 'Visual Studio / Visual Studio Code'),
    (English: 'Classic / Visual Studio'; Localized: 'Klasické / Visual Studio'),
    (English: 'Visual Studio Code'; Localized: 'Visual Studio Code'),
    (English: 'Light'; Localized: 'Světlý'),
    (English: 'Dark'; Localized: 'Tmavý'),
    (English: 'The new language will take effect the next time you start Inno Setup Compiler.'; Localized: 'Nový jazyk se projeví při příštím spuštění aplikace Inno Setup Compiler.'),
    (English: '&New...'; Localized: '&Nový...'),
    (English: '&New'; Localized: '&Nový'),
    (English: 'Line %1'; Localized: 'Řádek %1'),
    (English: '%1: %2'; Localized: '%1: %2'),
    (English: 'Back (%1)'; Localized: 'Zpět (%1)'),
    (English: 'Forward (%1)'; Localized: 'Vpřed (%1)'),
    (English: 'Ctrl+'; Localized: 'Ctrl+'),
    (English: 'Shift+'; Localized: 'Shift+'),
    (English: 'Alt+'; Localized: 'Alt+'),
    (English: 'Num %1'; Localized: 'Num %1'),
    (English: '(32-bit)'; Localized: '(32-bit)'),
    (English: '[Compiling]'; Localized: '[Kompilace]'),
    (English: '[Running]'; Localized: '[Spuštěno]'),
    (English: '[Paused]'; Localized: '[Pozastaveno]'),
    (English: 'Read only'; Localized: 'Pouze pro čtení'),
    (English: 'Modified'; Localized: 'Změněno'),
    (English: 'Overwrite'; Localized: 'Přepisování'),
    (English: 'Insert'; Localized: 'Vkládání'),
    (English: 'Tabs closed: %1'; Localized: 'Zavřené karty: %1'),
    (English: 'Estimated time remaining: %1'; Localized: 'Odhadovaný zbývající čas: %1'),
    (English: 'Average KB/sec: %1'; Localized: 'Průměr KB/s: %1'),
    (English: 'There was an error opening the file. Remove it from the list?'; Localized: 'Při otevírání souboru došlo k chybě. Odebrat jej ze seznamu?'),
    (English: 'The text in the %1 file has changed.%n%nDo you want to save the changes?'; Localized: 'Text v souboru %1 byl změněn.%n%nChcete změny uložit?'),
    (English: 'Please stop the compile process before performing this command.'; Localized: 'Před provedením tohoto příkazu zastavte proces kompilace.'),
    (English: 'A compile is already in progress.'; Localized: 'Kompilace již probíhá.'),
    (English: 'The text in the %1 file has changed and must be saved before compiling.%n%nSave the changes and continue?'; Localized: 'Text v souboru %1 byl změněn a před kompilací musí být uložen.%n%nUložit změny a pokračovat?'),
    (English: 'Would you like to save the script before compiling?%n%nIf you answer No, the compiled installation will be placed under your My Documents folder by default.'; Localized: 'Chcete skript před kompilací uložit?%n%nPokud odpovíte Ne, zkompilovaná instalace bude ve výchozím nastavení umístěna do složky Dokumenty.'),
    (English: 'The selected file is an %1 file. Go to its tab instead of opening it as the new main file?'; Localized: 'Vybraný soubor je soubor %1. Přejít na jeho kartu místo otevření jako nového hlavního souboru?'),
    (English: 'The selected file is not available as a tab. Opening as the new main file instead.'; Localized: 'Vybraný soubor není k dispozici jako karta. Otevře se místo toho jako nový hlavní soubor.'),
    (English: 'Error creating file (code %1). Could not save file'; Localized: 'Chyba při vytváření souboru (kód %1). Soubor nelze uložit'),
    (English: 'Error creating backup file. Could not save file'; Localized: 'Chyba při vytváření záložního souboru. Soubor nelze uložit'),
    (English: 'Error removing existing file (code %1). Could not save file'; Localized: 'Chyba při odebírání existujícího souboru (kód %1). Soubor nelze uložit'),
    (English: 'Error renaming temporary file (code %1). Could not save file'; Localized: 'Chyba při přejmenování dočasného souboru (kód %1). Soubor nelze uložit'),
    (English: 'Failed to open included file: %1'; Localized: 'Nepodařilo se otevřít vložený soubor: %1'),
    (English: 'Cannot start printer document.'; Localized: 'Nelze spustit tiskovou úlohu.'),
    (English: 'Are you sure you want to clear the list of recently opened files?'; Localized: 'Opravdu chcete vymazat seznam naposledy otevřených souborů?'),
    (English: 'The %1 file has been modified outside of the source editor. You might want to reload it.'; Localized: 'Soubor %1 byl změněn mimo editor zdrojového kódu. Možná jej budete chtít znovu načíst.'),
    (English: 'The %1 file has been modified outside of the source editor.%n%nDo you want to reload the file?'; Localized: 'Soubor %1 byl změněn mimo editor zdrojového kódu.%n%nChcete soubor znovu načíst?'),
    (English: 'The %1 file has been modified outside of the source editor. Changes have also been made in the source editor.%n%nDo you want to reload the file and lose the changes made in the source editor?'; Localized: 'Soubor %1 byl změněn mimo editor zdrojového kódu. Změny byly provedeny také v editoru zdrojového kódu.%n%nChcete soubor znovu načíst a přijít o změny provedené v editoru zdrojového kódu?'),
    (English: 'File not opened.'; Localized: 'Soubor nebyl otevřen.'),
    (English: 'Go to Line'; Localized: 'Přejít na řádek'),
    (English: 'Line number:'; Localized: 'Číslo řádku:'),
    (English: 'Do you want to copy your current license key to the clipboard before opening our order page? You will need it to be able to renew it.'; Localized: 'Chcete před otevřením naší objednávkové stránky zkopírovat svůj aktuální licenční klíč do schránky? Budete jej potřebovat k obnovení licence.'),
    (English: 'New commercial license key has been registered:%n%n%1%n%nThanks for your support!'; Localized: 'Nový komerční licenční klíč byl zaregistrován:%n%n%1%n%nDěkujeme za vaši podporu!'),
    (English: 'Are you sure you want to remove your commercial license key and revert to non-commercial use only?'; Localized: 'Opravdu chcete odebrat svůj komerční licenční klíč a vrátit se pouze k nekomerčnímu použití?'),
    (English: 'Commercial license key has been removed.'; Localized: 'Komerční licenční klíč byl odebrán.'),
    (English: 'Your version of Inno Setup has been updated! <a id="%1">See what''s new</a>.'; Localized: 'Vaše verze Inno Setup byla aktualizována! <a id="%1">Podívejte se na novinky</a>.'),
    (English: 'VS Code-style editor shortcuts added! Use the <a id="%1">Editor Keys option</a> in Options dialog.'; Localized: 'Byly přidány klávesové zkratky editoru ve stylu VS Code! Použijte možnost <a id="%1">Klávesy editoru</a> v dialogu Možnosti.'),
    (English: 'Inno Setup Compiler is available in your language! Use the <a id="%1">Language option</a> in Options dialog.'; Localized: 'Inno Setup Compiler je k dispozici ve vašem jazyce! Použijte možnost <a id="%1">Jazyk</a> v dialogu Možnosti.'),
    (English: '<a id="%1">Ideas board is open!</a> Share your ideas and vote on others, this month only.'; Localized: '<a id="%1">Nástěnka nápadů je otevřená!</a> Sdílejte své nápady a hlasujte o ostatních, pouze tento měsíc.'),
    (English: 'Running a version released after your update entitlement ended. <a id="%1">Renew license</a>, <a id="%2">remove key</a>, or <a id="%3">exit</a>.'; Localized: 'Používáte verzi vydanou po skončení vašeho nároku na aktualizace. <a id="%1">Obnovit licenci</a>, <a id="%2">odebrat klíč</a> nebo <a id="%3">ukončit</a>.'),
    (English: 'Your update entitlement is ending soon. Please <a id="%1">renew your license</a>. Thanks!'; Localized: 'Váš nárok na aktualizace brzy skončí. <a id="%1">Obnovte si licenci</a>. Děkujeme!'),
    (English: 'Your update entitlement has ended. Please <a id="%1">renew your license</a>. Thanks!'; Localized: 'Váš nárok na aktualizace skončil. <a id="%1">Obnovte si licenci</a>. Děkujeme!'),
    (English: 'Using Inno Setup commercially? Please <a id="%1">purchase a license</a>. Thanks!'; Localized: 'Používáte Inno Setup komerčně? <a id="%1">Zakupte si licenci</a>. Děkujeme!'),
    (English: 'Uninstall'; Localized: 'Uninstall'),
    (English: '%1 exit code: 0x%2'; Localized: 'Návratový kód %1: 0x%2'),
    (English: '%1 exit code: %2'; Localized: 'Návratový kód %1: %2'),
    (English: 'Unable to get %1 exit code (%2 failed)'; Localized: 'Nelze získat návratový kód %1 (%2 selhalo)'),
    (English: '%1 is still running; can''t get exit code'; Localized: '%1 stále běží; nelze získat návratový kód'),
    (English: 'Please stop the running %1 process before performing this command.'; Localized: 'Před provedením tohoto příkazu zastavte běžící proces %1.'),
    (English: 'This command will detach the debugger from the running %1 process. Continue?'; Localized: 'Tento příkaz odpojí ladicí program od běžícího procesu %1. Pokračovat?'),
    (English: 'The changes you made will not take effect until you re-compile.%n%nContinue running anyway?'; Localized: 'Provedené změny se projeví až po opětovné kompilaci.%n%nPřesto pokračovat ve spuštění?'),
    (English: 'A pause is already pending.'; Localized: 'Pozastavení již čeká na provedení.'),
    (English: 'No code was generated for the current line.'; Localized: 'Pro aktuální řádek nebyl vygenerován žádný kód.'),
    (English: 'This will unconditionally terminate the running %1 process. Continue?'; Localized: 'Tímto bezpodmínečně ukončíte běžící proces %1. Pokračovat?'),
    (English: 'Note that if %1 is currently in the installation phase, any changes made to the system thus far will not be undone, nor will uninstall data be written.'; Localized: 'Mějte na paměti, že pokud je %1 právě ve fázi instalace, dosud provedené změny systému nebudou vráceny zpět a nebudou zapsány ani informace pro odinstalaci.'),
    (English: 'Evaluate'; Localized: 'Vyhodnotit'),
    (English: 'Constant to evaluate (for example, "%1"):'; Localized: 'Konstanta k vyhodnocení (například "%1"):'),
    (English: 'Evaluate Result'; Localized: 'Výsledek vyhodnocení'),
    (English: 'Evaluate Error'; Localized: 'Chyba vyhodnocení'),
    (English: 'An unknown error occurred.'; Localized: 'Došlo k neznámé chybě.'),
    (English: '%1 = "%2"'; Localized: '%1 = "%2"'),
    (English: '%1 = Exception: %2'; Localized: '%1 = Výjimka: %2'),
    (English: '%1 = Unknown error'; Localized: '%1 = Neznámá chyba'),
    (English: 'Unknown error'; Localized: 'Neznámá chyba'),
    (English: 'Line %1:%n%2'; Localized: 'Řádek %1:%n%2'),
    (English: 'Runtime Error'; Localized: 'Chyba za běhu'),
    (English: '%1 (Update entitlement ended)'; Localized: '%1 (Nárok na aktualizace skončil)'),
    (English: '%1 (Update entitlement ended but updated anyway)'; Localized: '%1 (Nárok na aktualizace skončil, ale přesto aktualizováno)'),
    (English: 'Non-commercial use only'; Localized: 'Pouze nekomerční použití'),
    (English: 'Single User'; Localized: 'Jeden uživatel'),
    (English: 'Team'; Localized: 'Tým'),
    (English: 'Enterprise'; Localized: 'Enterprise'),
    (English: 'Inno Setup %1 License'; Localized: 'Licence Inno Setup %1'),
    (English: '%1, %2.'; Localized: '%1, %2.'),
    (English: 'Includes updates until %1, major and minor.'; Localized: 'Zahrnuje aktualizace do %1, hlavní i dílčí.'),
    (English: 'Includes all future updates, major and minor.'; Localized: 'Zahrnuje všechny budoucí aktualizace, hlavní i dílčí.'),
    (English: '%1 Entries Designer'; Localized: 'Návrhář položek %1'),
    (English: '&Insert'; Localized: '&Vložit'),
    (English: '&Parameters...'; Localized: '&Parametry...'),
    (English: 'Remo&ve'; Localized: 'O&debrat'),
    (English: 'Add Fol&der...'; Localized: 'Přidat s&ložku...'),
    (English: '&Add File(s)...'; Localized: 'Přidat &soubory...'),
    (English: '&Files:'; Localized: 'S&oubory:'),
    (English: 'Add D&ownload...'; Localized: 'Přidat sta&hování...'),
    (English: 'Go to File'; Localized: 'Přejít na soubor'),
    (English: 'Enter Commercial License Key'; Localized: 'Zadat komerční licenční klíč'),
    (English: 'Paste your license key below'; Localized: 'Vložte svůj licenční klíč níže'),
    (English: 'Close'; Localized: 'Zavřít'),
    (English: 'New Main Script (%1)'; Localized: 'Nový hlavní skript (%1)'),
    (English: 'Open Main Script (%1)'; Localized: 'Otevřít hlavní skript (%1)'),
    (English: 'Save (%1)'; Localized: 'Uložit (%1)'),
    (English: 'Stop Compile (%1)'; Localized: 'Zastavit kompilaci (%1)'),
    (English: 'Target Setup (%1)'; Localized: 'Nastavit jako cíl Setup (%1)'),
    (English: 'Target Uninstall (%1)'; Localized: 'Nastavit jako cíl Uninstall (%1)'),
    (English: 'Help (%1)'; Localized: 'Nápověda (%1)'),
    (English: 'Main Script'; Localized: 'Hlavní skript'),
    (English: 'Close Banner'; Localized: 'Zavřít banner'),
    (English: '&File'; Localized: '&Soubor'),
    (English: '&Open...'; Localized: '&Otevřít...'),
    (English: 'Open &Recent'; Localized: 'Otevřít na&posledy otevřené'),
    (English: '&Clear Recently Opened'; Localized: '&Vymazat naposledy otevřené'),
    (English: '&Save'; Localized: '&Uložit'),
    (English: 'Save &As...'; Localized: 'Uložit &jako...'),
    (English: 'Save &Encoding'; Localized: 'Uložit &kódování'),
    (English: '&Auto (ANSI or UTF-8)'; Localized: '&Automaticky (ANSI nebo UTF-8)'),
    (English: '&UTF-8'; Localized: '&UTF-8'),
    (English: 'UTF-8 with &BOM'; Localized: 'UTF-8 s &BOM'),
    (English: 'Sa&ve All'; Localized: 'Uložit &vše'),
    (English: '&Print...'; Localized: '&Tisk...'),
    (English: 'E&xit'; Localized: 'Kone&c'),
    (English: '&Edit'; Localized: '&Upravit'),
    (English: '&Undo'; Localized: '&Zpět'),
    (English: '&Redo'; Localized: 'Znov&u'),
    (English: 'Cu&t'; Localized: 'Vy&jmout'),
    (English: '&Copy'; Localized: '&Kopírovat'),
    (English: '&Paste'; Localized: '&Vložit'),
    (English: 'De&lete'; Localized: '&Odstranit'),
    (English: 'Select &All'; Localized: 'Vy&brat vše'),
    (English: 'Add Next &Occurrence'; Localized: 'Při&dat další výskyt'),
    (English: '&Select All Occurrences'; Localized: 'Vyb&rat všechny výskyty'),
    (English: 'Select All Find &Matches'; Localized: 'Vybrat všechny s&hody hledání'),
    (English: '&Find...'; Localized: '&Najít...'),
    (English: 'F&ind in Files...'; Localized: 'Najít v &souborech...'),
    (English: 'Find &Next'; Localized: 'Najít d&alší'),
    (English: 'Find Pre&vious'; Localized: 'Najít &předchozí'),
    (English: 'R&eplace...'; Localized: 'Nahrad&it...'),
    (English: 'Use Regular E&xpressions'; Localized: 'Použít re&gulární výrazy'),
    (English: 'Fol&d Section'; Localized: 'Sba&lit sekci'),
    (English: '&Unfold Section'; Localized: 'Rozbalit sek&ci'),
    (English: 'Go to File...'; Localized: 'Přejít na soubor...'),
    (English: '&Go to Line...'; Localized: 'Přejít na řád&ek...'),
    (English: 'Toggle Line Comment'; Localized: 'Přepnout komentář řádku'),
    (English: 'Go To Matching Brace'; Localized: 'Přejít na odpovídající závorku'),
    (English: '&View'; Localized: '&Zobrazit'),
    (English: '&Zoom'; Localized: 'Př&iblížení'),
    (English: 'Zoom &In'; Localized: '&Přiblížit'),
    (English: 'Zoom &Out'; Localized: '&Oddálit'),
    (English: '&Reset'; Localized: 'O&bnovit'),
    (English: '&Toolbar'; Localized: 'Pa&nel nástrojů'),
    (English: 'St&atus Bar'; Localized: '&Stavový řádek'),
    (English: '&Next Tab'; Localized: 'Další ka&rta'),
    (English: '&Previous Tab'; Localized: '&Předchozí karta'),
    (English: 'C&lose Tab'; Localized: 'Z&avřít kartu'),
    (English: 'Re&open Tab'; Localized: 'Znovu &otevřít kartu'),
    (English: 'Reopen &All Tabs'; Localized: 'Zno&vu otevřít všechny karty'),
    (English: 'C&lose Current Tab'; Localized: 'Z&avřít aktuální kartu'),
    (English: '&Compiler Output'; Localized: 'Výstup &kompilátoru'),
    (English: '&Debug Output'; Localized: 'Výstup &ladění'),
    (English: 'D&ebug Call Stack'; Localized: 'Záso&bník volání ladění'),
    (English: '&Find Results'; Localized: 'Výsledky &hledání'),
    (English: '&Hide Bottom Pane'; Localized: 'Skrýt &dolní podokno'),
    (English: '&Word Wrap'; Localized: 'Zala&mování řádků'),
    (English: '&Build'; Localized: 'S&estavení'),
    (English: '&Compile'; Localized: '&Kompilovat'),
    (English: 'S&top Compile'; Localized: '&Zastavit kompilaci'),
    (English: '&Low Priority During Compile'; Localized: '&Nízká priorita během kompilace'),
    (English: '&Disable Output'; Localized: 'Zakázat &výstup'),
    (English: 'Disable Co&mpression'; Localized: 'Zakázat ko&mpresi'),
    (English: 'Disable &Signing'; Localized: 'Zakázat &podepisování'),
    (English: 'Disable Signcheck &Validation'; Localized: 'Zakázat ověření sign&check'),
    (English: '&Open Output Folder'; Localized: '&Otevřít výstupní složku'),
    (English: '&Run'; Localized: 'S&pustit'),
    (English: '&Run...'; Localized: '&Spustit...'),
    (English: 'Run to &Cursor'; Localized: 'Spustit &ke kurzoru'),
    (English: 'Step &Into'; Localized: 'Krokovat s &vnořením'),
    (English: 'Step &Over'; Localized: 'Krokovat &bez vnoření'),
    (English: 'Step Out'; Localized: 'Krokovat s vystoupením'),
    (English: 'Toggle &Breakpoint'; Localized: 'Přepnout &zarážku'),
    (English: '&Delete All Breakpoints'; Localized: 'O&dstranit všechny zarážky'),
    (English: 'P&ause'; Localized: 'P&ozastavit'),
    (English: '&Terminate'; Localized: '&Ukončit'),
    (English: '&Evaluate Constant...'; Localized: 'Vy&hodnotit konstantu...'),
    (English: 'Target &Setup'; Localized: '&Nastavit jako cíl Setup'),
    (English: 'Target &Uninstall'; Localized: 'Nastavit &jako cíl Uninstall'),
    (English: '&Tools'; Localized: '&Nástroje'),
    (English: '&Add/Remove Programs'; Localized: '&Přidat nebo odebrat programy'),
    (English: 'Generate &GUID'; Localized: 'Vygenerovat &GUID'),
    (English: 'Generate %1 Entries...'; Localized: 'Vygenerovat položky %1...'),
    (English: 'Generate %1 Call...'; Localized: 'Vygenerovat volání %1...'),
    (English: '&Configure Sign Tools...'; Localized: '&Konfigurovat nástroje pro podepisování...'),
    (English: '&Options...'; Localized: '&Možnosti...'),
    (English: '&Help'; Localized: 'Nápo&věda'),
    (English: 'Purchase or Renew Commercial &License'; Localized: 'Zakoupit nebo obnovit komerční &licenci'),
    (English: 'Enter Commercial License &Key...'; Localized: '&Zadat komerční licenční klíč...'),
    (English: 'Remove Commercial License Key'; Localized: 'Odebrat komerční licenční klíč'),
    (English: '&Donate'; Localized: '&Přispět'),
    (English: '&Keyboard And Mouse Commands'; Localized: 'Příkazy &klávesnice a myši'),
    (English: 'Regular E&xpressions'; Localized: 'Re&gulární výrazy'),
    (English: 'Inno &Setup Documentation'; Localized: 'Dokumentace Inno &Setup'),
    (English: 'Inno Setup &Example Scripts'; Localized: '&Ukázkové skripty Inno Setup'),
    (English: 'Inno Setup &FAQ'; Localized: 'Časté dotazy k Inno Setup (&FAQ)'),
    (English: 'Inno Setup &Mailing List'; Localized: 'E-&mailová konference Inno Setup'),
    (English: 'Inno Setup &Revision History'; Localized: '&Historie revizí Inno Setup'),
    (English: 'Inno Setup &Web Site'; Localized: '&Webové stránky Inno Setup'),
    (English: 'Inno Setup &Preprocessor Documentation'; Localized: '&Dokumentace k Inno Setup Preprocessor'),
    (English: '&About Inno Setup'; Localized: '&O aplikaci Inno Setup'),
    (English: '%1 Call Designer'; Localized: 'Návrhář volání %1'),
    (English: 'Instruction'; Localized: 'Pokyn'),
    (English: 'Message'; Localized: 'Zpráva'),
    (English: 'Buttons'; Localized: 'Tlačítka'),
    (English: ' Type '; Localized: ' Typ '),
    (English: 'Suppressible'; Localized: 'Potlačitelné'),
    (English: ' Flags '; Localized: ' Příznaky '),
    (English: 'Default button'; Localized: 'Výchozí tlačítko'),
    (English: ' Icon '; Localized: ' Ikona '),
    (English: ' Return values '; Localized: ' Návratové hodnoty '),
    (English: '&Preview'; Localized: '&Náhled'),
    (English: 'Options'; Localized: 'Možnosti'),
    (English: ' Miscellaneous '; Localized: ' Různé '),
    (English: 'Show &Welcome dialog at startup'; Localized: 'Při spuštění zobrazit dialo&g Vítejte'),
    (English: 'Use the Inno Setup &Script Wizard'; Localized: 'Používat Průvodce &skriptem Inno Setup'),
    (English: 'Automatically sa&ve before compiling'; Localized: 'Před kompilací automatick&y ukládat'),
    (English: 'Create &backups when saving'; Localized: 'Při ukládání vytvářet &zálohy'),
    (English: 'Allow &Undo after save'; Localized: 'Povolit &Zpět po uložení'),
    (English: 'Display &full path in title bar'; Localized: 'Zobrazovat úplnou &cestu v záhlaví'),
    (English: '&Pause on exceptions'; Localized: 'Pozastavit při vý&jimkách'),
    (English: '&Launch Setup/Uninstall as administrator'; Localized: 'Setup/Uninstall spo&uštět jako správce'),
    (English: 'Colori&ze "Compiler Output" view'; Localized: 'Oba&rvit zobrazení "Výstup kompilátoru"'),
    (English: 'Automatically open %1 files'; Localized: 'Automaticky otevírat soubory %1'),
    (English: 'Automatically show preprocessor output'; Localized: 'Automaticky zobrazovat výstup preprocesoru'),
    (English: 'Menu &keys:'; Localized: 'Klávesy &nabídek:'),
    (English: 'Automatically reload files'; Localized: 'Automaticky znovu načítat soubory'),
    (English: 'Allow Undo after reload'; Localized: 'Povolit Zpět po opětovném načtení'),
    (English: 'Keep new %1 files closed'; Localized: 'Nové soubory %1 ponechat zavřené'),
    (English: 'Language:'; Localized: 'Jazyk:'),
    (English: ' Editor '; Localized: ' Editor '),
    (English: 'Invoke autoco&mplete automatically'; Localized: '&Automaticky vyvolávat automatické dokončování'),
    (English: 'Use syntax &highlighting'; Localized: 'Použít zvýraznění synta&xe'),
    (English: 'U&nderline syntax errors'; Localized: 'Podtr&hávat syntaktické chyby'),
    (English: 'Allow cursor to move beyond &end of lines'; Localized: 'Povolit pohyb kurzoru za kon&ec řádků'),
    (English: 'Enable section f&olding'; Localized: 'Povolit s&kládání sekcí'),
    (English: 'Use tab cha&racter'; Localized: 'Použít znak ta&bulátoru'),
    (English: 'Auto &indent mode'; Localized: 'Rež&im automatického odsazení'),
    (English: 'Show indentation &guides'; Localized: 'Zobrazovat vo&dítka odsazení'),
    (English: 'Font:'; Localized: 'Písmo:'),
    (English: 'AaBbXxZz'; Localized: 'AaBbXxZz'),
    (English: '&Change...'; Localized: 'Z&měnit...'),
    (English: '&Tab Width:'; Localized: 'Šířka &tabulátoru:'),
    (English: 'Show &line numbers in gutter'; Localized: 'Zobrazovat čís&la řádků na okraji'),
    (English: 'T&heme:'; Localized: 'M&otiv:'),
    (English: 'Highlight occurrences of current selection'; Localized: 'Zvýraznit výskyty aktuálního výběru'),
    (English: 'Highlight occurrences of current wor&d'; Localized: 'Z&výraznit výskyty aktuálního slova'),
    (English: 'Ke&ys:'; Localized: 'Kláves&y:'),
    (English: 'Show whitespace'; Localized: 'Zobrazit prázdné znaky'),
    (English: 'Smart Home key'; Localized: 'Chytrá klávesa Home'),
    (English: '&Associate .%1 files with this compiler'; Localized: '&Přidružit soubory .%1 k tomuto kompilátoru'),
    (English: '&Windows registry file (.%1) to import:'; Localized: 'Soubor registru &Windows (.%1) k importu:'),
    (English: 'B&rowse...'; Localized: 'P&rocházet...'),
    (English: 'Settings (for all keys and values):'; Localized: 'Nastavení (pro všechny klíče a hodnoty):'),
    (English: 'Also delete keys which are not empty'; Localized: 'Odstranit také klíče, které nejsou prázdné'),
    (English: 'Delete keys which are empty on uninstall'; Localized: 'Při odinstalaci odstranit klíče, které jsou prázdné'),
    (English: 'Delete values on uninstall'; Localized: 'Při odinstalaci odstranit hodnoty'),
    (English: 'Minimum Windows version:'; Localized: 'Minimální verze Windows:'),
    (English: 'Configure Sign Tools'; Localized: 'Konfigurovat nástroje pro podepisování'),
    (English: ' Sign Tools '; Localized: ' Nástroje pro podepisování '),
    (English: '&Add...'; Localized: '&Přidat...'),
    (English: '&Edit...'; Localized: '&Upravit...'),
    (English: 'Be notified by e-mail of new Inno Setup releases'; Localized: 'Dostávejte e-mailem upozornění na nová vydání Inno Setup'),
    (English: 'Subscribe'; Localized: 'Přihlásit se k odběru'),
    (English: ' New file '; Localized: ' Nový soubor '),
    (English: 'Create a new &empty script file'; Localized: 'Vytvořit nový &prázdný soubor skriptu'),
    (English: 'Create a new script file using the &Script Wizard'; Localized: '&Vytvořit nový soubor skriptu pomocí Průvodce skriptem'),
    (English: ' Open file '; Localized: ' Otevřít soubor '),
    (English: 'Open an e&xisting script file'; Localized: 'Otevřít e&xistující soubor skriptu'),
    (English: '&Don''t show this dialog again'; Localized: '&Tento dialog příště nezobrazovat'),
    (English: 'Script Wizard File'; Localized: 'Soubor Průvodce skriptem'),
    (English: 'bold'; Localized: 'tučně'),
    (English: ' = required'; Localized: ' = povinné'),
    (English: ' Destination '; Localized: ' Cíl '),
    (English: 'Destination &base folder:'; Localized: 'Cílová &základní složka:'),
    (English: 'Destination &subfolder:'; Localized: 'Cílová &podsložka:'),
    (English: 'Destination &name:'; Localized: 'Cílový &název:'),
    (English: ' Source '; Localized: ' Zdroj '),
    (English: '&Source file or folder:'; Localized: 'Zdrojový &soubor nebo složka:'),
    (English: '&Recurse subfolders'; Localized: 'P&rocházet podsložky rekurzivně'),
    (English: '&Include empty subfolders'; Localized: 'Za&hrnout prázdné podsložky'),
    (English: '&Extract archive'; Localized: '&Extrahovat archiv'),
    (English: 'Welcome to the %1'; Localized: 'Vítá vás %1'),
    (English: 'This wizard will guide you through the process of creating a new Inno Setup script file. The results will be used to generate a new script file which can be compiled directly or saved on disk for later use.%n%nNot all features of Inno Setup are covered by this wizard. See the documentation for details on creating Inno Setup script files.%n%nClick Next to continue, or Cancel to exit this wizard.'; Localized: 'Tento průvodce vás provede procesem vytváření nového souboru skriptu Inno Setup. Výsledky budou použity k vygenerování nového souboru skriptu, který lze přímo zkompilovat nebo uložit na disk pro pozdější použití.%n%nTento průvodce nepokrývá všechny funkce Inno Setup. Podrobnosti o vytváření souborů skriptů Inno Setup najdete v dokumentaci.%n%nPokračujte kliknutím na Další, nebo tohoto průvodce ukončete kliknutím na Zrušit.'),
    (English: 'Application na&me:'; Localized: '&Název aplikace:'),
    (English: 'Application &version:'; Localized: 'Ve&rze aplikace:'),
    (English: 'Application &publisher:'; Localized: '&Vydavatel aplikace:'),
    (English: 'Application &website:'; Localized: '&Web aplikace:'),
    (English: 'Application folder na&me:'; Localized: '&Název složky aplikace:'),
    (English: 'Application &destination base folder:'; Localized: '&Cílová základní složka aplikace:'),
    (English: 'Other:'; Localized: 'Jiné:'),
    (English: 'Allow user to &change the application folder'; Localized: 'Povolit uživateli z&měnit složku aplikace'),
    (English: 'The application doe&sn''t need a folder'; Localized: '&Aplikace nepotřebuje složku'),
    (English: 'Other application &files:'; Localized: '&Ostatní soubory aplikace:'),
    (English: 'Application &main executable file:'; Localized: 'Hla&vní spustitelný soubor aplikace:'),
    (English: 'Allow &user to start the application after Setup has finished'; Localized: 'Povolit &uživateli spustit aplikaci po dokončení instalace'),
    (English: 'The application doe&sn''t have a main executable file'; Localized: '&Aplikace nemá hlavní spustitelný soubor'),
    (English: 'Application file type na&me:'; Localized: '&Název typu souboru aplikace:'),
    (English: '&Associate a file type to the main executable'; Localized: '&Přidružit typ souboru k hlavnímu spustitelnému souboru'),
    (English: 'Application file type &extension:'; Localized: 'Příp&ona typu souboru aplikace:'),
    (English: 'Application &Start Menu folder name:'; Localized: '&Název složky aplikace v nabídce Start:'),
    (English: 'Other shortcuts to the main executable:'; Localized: 'Ostatní zástupci hlavního spustitelného souboru:'),
    (English: 'Allow user to &change the Start Menu folder name'; Localized: 'Povolit uživateli z&měnit název složky nabídky Start'),
    (English: 'Allow user to &disable Start Menu folder creation'; Localized: 'Povolit uživateli za&kázat vytvoření složky nabídky Start'),
    (English: 'Allow user to create a deskto&p shortcut'; Localized: 'Povolit uživateli vytvořit zástupce na &ploše'),
    (English: 'Create an &Uninstall shortcut in the Start Menu folder'; Localized: 'Vytvořit zástupce &Uninstall ve složce nabídky Start'),
    (English: 'Create an &Internet shortcut in the Start Menu folder'; Localized: 'Vytvořit &internetového zástupce ve složce nabídky Start'),
    (English: '&Create a Start Menu shortcut but no folder'; Localized: '&Vytvořit zástupce v nabídce Start, ale žádnou složku'),
    (English: '&License file:'; Localized: 'Soubor &licence:'),
    (English: '&Information file shown before installation:'; Localized: '&Informační soubor zobrazený před instalací:'),
    (English: 'Information file shown &after installation:'; Localized: 'Informační soubor zobrazený &po instalaci:'),
    (English: 'Install mode:'; Localized: 'Režim instalace:'),
    (English: '&Administrative install mode (install for all users)'; Localized: '&Režim instalace pro správce (instalace pro všechny uživatele)'),
    (English: 'Non a&dministrative install mode (install for current user only)'; Localized: 'Režim instalace &bez práv správce (instalace jen pro aktuálního uživatele)'),
    (English: 'Allow user to &override the install mode via the command line'; Localized: 'Povolit uživateli &přepsat režim instalace přes příkazový řádek'),
    (English: 'Ask the user to &choose the install mode at startup'; Localized: 'Při spuštění požádat uživatele o &volbu režimu instalace'),
    (English: '&Languages:'; Localized: '&Jazyky:'),
    (English: '&Deselect All'; Localized: 'Z&rušit výběr všech'),
    (English: 'Custom compiler output fol&der:'; Localized: '&Vlastní výstupní složka kompilátoru:'),
    (English: 'Compiler output base &file name:'; Localized: 'Zá&kladní název souboru výstupu kompilátoru:'),
    (English: 'Custom Setup &icon file:'; Localized: 'Vlastní soubor &ikony pro Setup:'),
    (English: 'Setup &password:'; Localized: '&Heslo pro Setup:'),
    (English: 'Use the password to &encrypt the application files'; Localized: 'Použít heslo k zašifrování &souborů aplikace'),
    (English: '&Wizard style:'; Localized: '&Styl průvodce:'),
    (English: 'You have successfully completed the %1.%n%nTo close this wizard and generate the new script file, click Finish.'; Localized: 'Úspěšně jste dokončili %1.%n%nChcete-li tohoto průvodce zavřít a vygenerovat nový soubor skriptu, klikněte na Dokončit.'),
    (English: '&Back'; Localized: '&Zpět'));

implementation

end.
