unit IDE.LocalizeFunc.ChineseSimplified;

{
  Inno Setup
  Copyright (C) 1997-2026 Jordan Russell
  Portions by Martijn Laan
  For conditions of distribution and use, see LICENSE.TXT.

  Compiler IDE Chinese (Simplified) translations
}

interface

uses
  IDE.LocalizeFunc;

const
  ChineseSimplifiedIDETranslations: array [0..970] of TTranslationPair = (
    (English: 'Command-line usage:'; Localized: '命令行用法：'),
    (English: 'Examples:'; Localized: '示例：'),
    (English: 'script file'; Localized: '脚本文件'),
    (English: 'wizard name'; Localized: '向导名称'),
    (English: 'My script'; Localized: '我的脚本'),
    (English: 'My Script Wizard'; Localized: '我的脚本向导'),
    (English: 'Could not load %1: %2'; Localized: '无法加载 %1: %2'),
    (English: 'Inno Setup Compiler'; Localized: 'Inno Setup Compiler'),
    (English: 'Example scripts...'; Localized: '示例脚本...'),
    (English: 'More files...'; Localized: '更多文件...'),
    (English: 'Untitled'; Localized: '未命名'),
    (English: 'Preprocessor Output'; Localized: '预处理器输出'),
    (English: 'Run Parameters'; Localized: '运行参数'),
    (English: 'Command-line parameters for %1 and %2:'; Localized: '%1 和 %2 的命令行参数：'),
    (English: 'Inno Setup Script files'; Localized: 'Inno Setup 脚本文件'),
    (English: 'All files'; Localized: '所有文件'),
    (English: 'Application files'; Localized: '应用程序文件'),
    (English: 'Documentation files'; Localized: '文档文件'),
    (English: 'Rich Text Format files'; Localized: '富文本格式文件'),
    (English: 'Registry files'; Localized: '注册表文件'),
    (English: 'Icon files'; Localized: '图标文件'),
    (English: 'Inno Setup Script Wizard'; Localized: 'Inno Setup 脚本向导'),
    (English: 'Welcome'; Localized: '欢迎'),
    (English: 'Application Information'; Localized: '应用程序信息'),
    (English: 'Please specify some basic information about your application.'; Localized: '请指定应用程序的基本信息。'),
    (English: 'Application Folder'; Localized: '应用程序文件夹'),
    (English: 'Please specify folder information about your application.'; Localized: '请指定应用程序的文件夹信息。'),
    (English: 'Application Files'; Localized: '应用程序文件'),
    (English: 'Please specify the files that are part of your application.'; Localized: '请指定应用程序包含的文件。'),
    (English: 'Please specify the source folder.'; Localized: '请指定源文件夹。'),
    (English: 'Should files in subfolders of "%1" also be included?'; Localized: '是否也要包含“%1”的子文件夹中的文件？'),
    (English: 'URL:'; Localized: 'URL:'),
    (English: 'Is the file to download an archive which should be extracted?'; Localized: '要下载的文件是否为需要解压的压缩包？'),
    (English: 'Name of the file:'; Localized: '文件名：'),
    (English: 'Name of the file (extension should match archive format):'; Localized: '文件名 (扩展名应与压缩包格式一致)：'),
    (English: 'Approximate size of the file in megabytes:'; Localized: '文件的大致大小 (MB)：'),
    (English: 'Application File Association'; Localized: '应用程序文件关联'),
    (English: 'Please specify which file association should be created for your application.'; Localized: '请指定要为应用程序创建的文件关联。'),
    (English: '%1 File'; Localized: '%1 文件'),
    (English: 'Application Shortcuts'; Localized: '应用程序快捷方式'),
    (English: 'Please specify which shortcuts should be created for your application.'; Localized: '请指定要为应用程序创建的快捷方式。'),
    (English: 'Application Documentation'; Localized: '应用程序文档'),
    (English: 'Please specify which documentation files should be shown by Setup during installation.'; Localized: '请指定安装期间安装程序应显示的文档文件。'),
    (English: 'Setup Install Mode'; Localized: '安装程序的安装模式'),
    (English: 'Please specify in which install mode Setup should run.'; Localized: '请指定安装程序以哪种安装模式运行。'),
    (English: 'Application Registry Keys And Values'; Localized: '应用程序注册表项和值'),
    (English: 'Please specify the registry keys and values that are part of your application.'; Localized: '请指定应用程序包含的注册表项和值。'),
    (English: 'Setup Languages'; Localized: '安装程序语言'),
    (English: 'Please specify which Setup languages should be included.'; Localized: '请指定要包含的安装程序语言。'),
    (English: 'Compiler Settings'; Localized: '编译器设置'),
    (English: 'Please specify some basic compiler settings.'; Localized: '请指定基本的编译器设置。'),
    (English: 'Please specify the folder.'; Localized: '请指定文件夹。'),
    (English: 'Wizard Style'; Localized: '向导样式'),
    (English: 'Please specify which wizard style should be used.'; Localized: '请指定要使用的向导样式。'),
    (English: 'Inno Setup Preprocessor'; Localized: 'Inno Setup 预处理器'),
    (English: 'Please specify whether Inno Setup Preprocessor should be used.'; Localized: '请指定是否使用 Inno Setup 预处理器。'),
    (English: 'The %1 can use %2 compiler directives to simplify your script. Although this is not necessary, it will make it easier to manually change the script later.%n%nDo you want the %1 to use %2 compiler directives?'; Localized: '%1 可以使用 %2 编译器指令来简化您的脚本。这不是必需的，但会让以后手动修改脚本变得更容易。%n%n您希望 %1 使用 %2 编译器指令吗？'),
    (English: '&Yes, use %1 compiler directives'; Localized: '是，使用 %1 编译器指令(&Y)'),
    (English: 'Finished'; Localized: '完成'),
    (English: '&Next'; Localized: '下一步(&N)'),
    (English: '&Finish'; Localized: '完成(&F)'),
    (English: 'The %1 is not complete. If you quit now, the new script file will not be generated.%n%nExit anyway?'; Localized: '%1 尚未完成。如果现在退出，将不会生成新的脚本文件。%n%n仍要退出吗？'),
    (English: 'Please specify the application name.'; Localized: '请指定应用程序名称。'),
    (English: 'Please specify the application version.'; Localized: '请指定应用程序版本。'),
    (English: 'Please specify the application destination base folder.'; Localized: '请指定应用程序的目标基文件夹。'),
    (English: 'Please specify the application folder name.'; Localized: '请指定应用程序文件夹名称。'),
    (English: 'Please specify the application main executable file.'; Localized: '请指定应用程序的主可执行文件。'),
    (English: 'The specified application main executable file does not exist.'; Localized: '指定的应用程序主可执行文件不存在。'),
    (English: 'Please specify the application Start Menu group name.'; Localized: '请指定应用程序的开始菜单组名称。'),
    (English: 'Please specify the destination base folder.'; Localized: '请指定目标基文件夹。'),
    (English: 'Please specify a destination base folder other than the application folder.'; Localized: '请指定一个不同于应用程序文件夹的目标基文件夹。'),
    (English: 'Please specify the destination name.'; Localized: '请指定目标名称。'),
    (English: 'Please select at least one language.'; Localized: '请至少选择一种语言。'),
    (English: '&Source URL:'; Localized: '源 URL(&S)：'),
    (English: 'Script generated by the %1.'; Localized: '此脚本由 %1 生成。'),
    (English: 'SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!'; Localized: '有关创建 Inno Setup 脚本文件的详细信息，请参阅文档！'),
    (English: 'NOTE: The value of %1 uniquely identifies this application. Do not use the same %1 value in installers for other applications.'; Localized: '注意：%1 的值唯一标识此应用程序。不要在其他应用程序的安装程序中使用相同的 %1 值。'),
    (English: '(To generate a new GUID, click Tools | Generate GUID inside the IDE.)'; Localized: '（要生成新的 GUID，请在 IDE 中点击“工具”|“生成 GUID”。）'),
    (English: '"%1" specifies that Setup cannot run on anything but x64 and Windows 11 on Arm.'; Localized: '“%1”指定安装程序只能在 x64 和 Arm 版 Windows 11 上运行。'),
    (English: '"%1" requests that the install be done in "64-bit mode" on x64 or Windows 11 on Arm.'; Localized: '“%1”请求在 x64 或 Arm 版 Windows 11 上以“64 位模式”进行安装。'),
    (English: 'This means it should use the native 64-bit Program Files directory and the 64-bit view of the registry.'; Localized: '这表示它应使用原生的 64 位 Program Files 目录和注册表的 64 位视图。'),
    (English: 'Uncomment the following line to use a 64-bit installer.'; Localized: '取消注释以下行以使用 64 位安装程序。'),
    (English: 'Use "%1" if all your archives are .%2 files.'; Localized: '如果您的所有压缩包都是 .%2 文件，请使用“%1”。'),
    (English: 'Use "%1" if all your archives are not password-protected.'; Localized: '如果您的所有压缩包都未使用密码保护，请使用“%1”。'),
    (English: 'Uncomment the following line to run in non administrative install mode (install for current user only).'; Localized: '取消注释以下行以在非管理员安装模式 (仅为当前用户安装) 下运行。'),
    (English: 'Remove the following line to run in administrative install mode (install for all users).'; Localized: '删除以下行以在管理员安装模式 (为所有用户安装) 下运行。'),
    (English: 'NOTE: Don''t use "%1" on any shared system files.'; Localized: '注意：不要对任何共享系统文件使用“%1”。'),
    (English: 'NOTE: Use the "%1" flag or the "%2" parameter to verify downloads.'; Localized: '注意：使用“%1”标志或“%2”参数来验证下载。'),
    (English: 'Registry data from file %1'; Localized: '来自文件 %1 的注册表数据'),
    (English: 'COULD NOT IMPORT %1'; Localized: '无法导入 %1'),
    (English: 'End of registry data from file %1'; Localized: '来自文件 %1 的注册表数据结束'),
    (English: 'SOME KEYS FILTERED DUE TO %1 SETTINGS!'; Localized: '由于 %1 设置，部分注册表项已被筛除！'),
    (English: 'SOME VALUES WITH UNSUPPORTED TYPES SKIPPED!'; Localized: '已跳过部分类型不受支持的值！'),
    (English: 'Would you like to compile the new script now?'; Localized: '要立即编译新脚本吗？'),
    (English: 'My Program'; Localized: '我的程序'),
    (English: 'My Company, Inc.'; Localized: 'My Company, Inc.'),
    (English: 'Application directory'; Localized: '应用程序目录'),
    (English: 'Program Files directory'; Localized: 'Program Files 目录'),
    (English: 'Common Files directory'; Localized: 'Common Files 目录'),
    (English: 'Windows directory'; Localized: 'Windows 目录'),
    (English: 'Windows system directory'; Localized: 'Windows 系统目录'),
    (English: 'Setup source directory'; Localized: '安装程序源目录'),
    (English: 'System drive root directory'; Localized: '系统驱动器根目录'),
    (English: '(Custom)'; Localized: '(自定义)'),
    (English: 'Starting compile.%1[%2]'; Localized: '正在开始编译。%1[%2]'),
    (English: 'Finished.%1[%2, %3 elapsed]'; Localized: '已完成。%1[%2，耗时 %3]'),
    (English: 'Compile aborted.'; Localized: '编译已中止。'),
    (English: 'Log size limit reached, list reset.'; Localized: '已达到日志大小上限，列表已重置。'),
    (English: '%1 started'; Localized: '%1已启动'),
    (English: 'Terminating process'; Localized: '正在终止进程'),
    (English: 'Removing left-over temporary directory: %1'; Localized: '正在删除遗留的临时目录: %1'),
    (English: 'Failed to remove temporary directory'; Localized: '删除临时目录失败'),
    (English: '%1 Call Stack'; Localized: '%1 调用堆栈'),
    (English: 'Cannot run Setup at this time. Please compile Setup successfully to completion first, with output enabled'; Localized: '目前无法运行安装程序。请先在启用输出的情况下成功完成安装程序的编译'),
    (English: 'Cannot run Uninstall at this time. Please run Setup successfully to completion first'; Localized: '目前无法运行卸载程序。请先成功运行安装程序至完成'),
    (English: 'Error executing "%1":%n%n%2: %3'; Localized: '执行“%1”时出错:%n%n%2: %3'),
    (English: 'Are you sure you want to abort the compile?'; Localized: '确定要中止编译吗？'),
    (English: 'File %1:'; Localized: '文件 %1:'),
    (English: 'Line %1:'; Localized: '行 %1:'),
    (English: 'Compiler Error'; Localized: '编译器错误'),
    (English: 'Illegal null character on line %1'; Localized: '第 %1 行存在非法的 null 字符'),
    (English: 'Cannot find "%1"'; Localized: '找不到“%1”'),
    (English: 'Invalid regular expression "%1"'; Localized: '无效的正则表达式“%1”'),
    (English: '%1 (%2 hits):'; Localized: '%1 (%2 个匹配):'),
    (English: 'Find "%1" (%2 hits in %3 files)'; Localized: '查找“%1”(%3 个文件中 %2 个匹配)'),
    (English: '%1 occurrence(s) replaced.'; Localized: '已替换 %1 处。'),
    (English: 'The .%1 extension was successfully associated for the current user with:%n%2'; Localized: '已成功为当前用户将 .%1 扩展名关联到:%n%2'),
    (English: 'The .%1 extension was successfully associated for all users with:%n%2'; Localized: '已成功为所有用户将 .%1 扩展名关联到:%n%2'),
    (English: 'Error creating file association:%n%1 - %2'; Localized: '创建文件关联时出错:%n%1 - %2'),
    (English: 'Unable to associate for all users without administrative privileges. Do you want to associate only for yourself instead?'; Localized: '没有管理员权限，无法为所有用户建立关联。是否改为仅为您自己建立关联？'),
    (English: 'Associate'; Localized: '关联'),
    (English: 'Inno Setup Script'; Localized: 'Inno Setup 脚本'),
    (English: 'Compi&le'; Localized: '编译(&L)'),
    (English: '&Script has %1'; Localized: '脚本中已有 %1(&S)'),
    (English: 'Script has %1 set'; Localized: '脚本中已设置 %1'),
    (English: 'Invalid file format.'; Localized: '文件格式无效。'),
    (English: 'The specified registry file does not exist.'; Localized: '指定的注册表文件不存在。'),
    (English: 'Setup'; Localized: '安装'),
    (English: 'Your message text.'; Localized: '您的消息文本。'),
    (English: 'Enter your text here...'; Localized: '在此输入您的文本...'),
    (English: 'Return values'; Localized: '返回值'),
    (English: 'Default'; Localized: '默认'),
    (English: 'Shield'; Localized: '盾牌'),
    (English: 'Instruction Text'; Localized: '指示文本'),
    (English: 'Message Text'; Localized: '消息文本'),
    (English: 'user clicked %1'; Localized: '用户点击了 %1'),
    (English: 'OK'; Localized: '确定'),
    (English: 'Yes'; Localized: '是'),
    (English: 'No'; Localized: '否'),
    (English: 'Cancel'; Localized: '取消'),
    (English: 'Retry'; Localized: '重试'),
    (English: 'Ignore'; Localized: '忽略'),
    (English: 'Abort'; Localized: '中止'),
    (English: 'Display a message box'; Localized: '显示消息框'),
    (English: 'Name of the Sign Tool:'; Localized: '签名工具名称：'),
    (English: 'Invalid name.'; Localized: '名称无效。'),
    (English: 'Duplicate name.'; Localized: '名称重复。'),
    (English: 'Command of the Sign Tool:'; Localized: '签名工具命令：'),
    (English: 'Invalid command.'; Localized: '命令无效。'),
    (English: '%1 must be an integer value'; Localized: '%1 必须是整数值'),
    (English: 'The script cannot be edited because it is read-only'; Localized: '脚本是只读的，无法编辑'),
    (English: 'Move to a key/value section or parameter entry'; Localized: '请移动到键/值节或参数条目'),
    (English: 'Unspecified directives are hidden because this section occurs more than once'; Localized: '由于此节出现了多次，未指定的指令已隐藏'),
    (English: 'Unspecified directives are hidden because this is not the main script file'; Localized: '由于这不是主脚本文件，未指定的指令已隐藏'),
    (English: 'Compiler'; Localized: '编译器'),
    (English: 'Compression'; Localized: '压缩'),
    (English: 'Installer'; Localized: '安装程序'),
    (English: 'Cosmetic'; Localized: '外观'),
    (English: 'Common'; Localized: '常规'),
    (English: 'The generated GUID will be inserted into the editor at the cursor position. Continue?'; Localized: '生成的 GUID 将插入到编辑器中的光标位置。是否继续？'),
    (English: 'The generated Pascal script will be inserted into the editor at the cursor position, but the cursor is not in the %1 section. Continue anyway?'; Localized: '生成的 Pascal 脚本将插入到编辑器中的光标位置，但光标不在 %1 节中。仍要继续吗？'),
    (English: 'Classic'; Localized: '经典'),
    (English: 'Visual Studio / Visual Studio Code'; Localized: 'Visual Studio / Visual Studio Code'),
    (English: 'Classic / Visual Studio'; Localized: '经典 / Visual Studio'),
    (English: 'Visual Studio Code'; Localized: 'Visual Studio Code'),
    (English: 'Light'; Localized: '浅色'),
    (English: 'Dark'; Localized: '深色'),
    (English: 'The new language will take effect the next time you start Inno Setup Compiler.'; Localized: '新语言将在您下次启动 Inno Setup Compiler 时生效。'),
    (English: '&New...'; Localized: '新建(&N)...'),
    (English: '&New'; Localized: '新建(&N)'),
    (English: 'Line %1'; Localized: '行 %1'),
    (English: '%1: %2'; Localized: '%1: %2'),
    (English: 'Back (%1)'; Localized: '后退 (%1)'),
    (English: 'Forward (%1)'; Localized: '前进 (%1)'),
    (English: 'Back'; Localized: '后退'),
    (English: 'Forward'; Localized: '前进'),
    (English: 'Open'; Localized: '打开'),
    (English: 'Run'; Localized: '运行'),
    (English: 'Save As'; Localized: '另存为'),
    (English: 'Font'; Localized: '字体'),
    (English: 'Text Color'; Localized: '文字颜色'),
    (English: 'Background Color'; Localized: '背景颜色'),
    (English: 'Ctrl+'; Localized: 'Ctrl+'),
    (English: 'Shift+'; Localized: 'Shift+'),
    (English: 'Alt+'; Localized: 'Alt+'),
    (English: 'Num %1'; Localized: 'Num %1'),
    (English: '(32-bit)'; Localized: '(32 位)'),
    (English: '[Compiling]'; Localized: '[正在编译]'),
    (English: '[Running]'; Localized: '[正在运行]'),
    (English: '[Paused]'; Localized: '[已暂停]'),
    (English: 'Read only'; Localized: '只读'),
    (English: 'Modified'; Localized: '已修改'),
    (English: 'Overwrite'; Localized: '改写'),
    (English: 'Insert'; Localized: '插入'),
    (English: 'Tabs closed: %1'; Localized: '已关闭标签页: %1'),
    (English: 'Estimated time remaining: %1'; Localized: '预计剩余时间: %1'),
    (English: 'Average KB/sec: %1'; Localized: '平均 KB/秒: %1'),
    (English: 'There was an error opening the file. Remove it from the list?'; Localized: '打开文件时出错。要将其从列表中移除吗？'),
    (English: 'The text in the %1 file has changed.%n%nDo you want to save the changes?'; Localized: '%1 文件中的文本已更改。%n%n要保存更改吗？'),
    (English: 'Please stop the compile process before performing this command.'; Localized: '请在执行此命令前停止编译过程。'),
    (English: 'A compile is already in progress.'; Localized: '编译已在进行中。'),
    (English: 'The text in the %1 file has changed and must be saved before compiling.%n%nSave the changes and continue?'; Localized: '%1 文件中的文本已更改，必须在编译前保存。%n%n要保存更改并继续吗？'),
    (English: 'Would you like to save the script before compiling?%n%nIf you answer No, the compiled installation will be placed under your My Documents folder by default.'; Localized: '要在编译前保存脚本吗？%n%n如果选择“否”，编译生成的安装程序默认将放置在您的“我的文档”文件夹下。'),
    (English: 'The selected file is an %1 file. Go to its tab instead of opening it as the new main file?'; Localized: '所选文件是 %1 文件。要转到它的标签页而不是将其打开为新的主文件吗？'),
    (English: 'The selected file is not available as a tab. Opening as the new main file instead.'; Localized: '所选文件没有对应的标签页。将改为将其打开为新的主文件。'),
    (English: 'Error creating file (code %1). Could not save file'; Localized: '创建文件时出错 (代码 %1)。无法保存文件'),
    (English: 'Error creating backup file. Could not save file'; Localized: '创建备份文件时出错。无法保存文件'),
    (English: 'Error removing existing file (code %1). Could not save file'; Localized: '移除现有文件时出错 (代码 %1)。无法保存文件'),
    (English: 'Error renaming temporary file (code %1). Could not save file'; Localized: '重命名临时文件时出错 (代码 %1)。无法保存文件'),
    (English: 'Failed to open included file: %1'; Localized: '打开包含的文件失败: %1'),
    (English: 'Cannot start printer document.'; Localized: '无法启动打印文档。'),
    (English: 'Are you sure you want to clear the list of recently opened files?'; Localized: '确定要清空最近打开的文件列表吗？'),
    (English: 'The %1 file has been modified outside of the source editor. You might want to reload it.'; Localized: '%1 文件已在源编辑器之外被修改。您可能需要重新加载它。'),
    (English: 'The %1 file has been modified outside of the source editor.%n%nDo you want to reload the file?'; Localized: '%1 文件已在源编辑器之外被修改。%n%n要重新加载该文件吗？'),
    (English: 'The %1 file has been modified outside of the source editor. Changes have also been made in the source editor.%n%nDo you want to reload the file and lose the changes made in the source editor?'; Localized: '%1 文件已在源编辑器之外被修改，并且源编辑器中也做了更改。%n%n要重新加载该文件并放弃在源编辑器中所做的更改吗？'),
    (English: 'File not opened.'; Localized: '文件未打开。'),
    (English: 'Go to Line'; Localized: '转到行'),
    (English: 'Line number:'; Localized: '行号：'),
    (English: 'Could not load file (code %1)'; Localized: '无法加载文件 (代码 %1)'),
    (English: 'Could not save file (code %1)'; Localized: '无法保存文件 (代码 %1)'),
    (English: 'Do you want to copy your current license key to the clipboard before opening our order page? You will need it to be able to renew it.'; Localized: '要在打开订购页面之前将您当前的许可证密钥复制到剪贴板吗？续订时需要用到它。'),
    (English: 'New commercial license key has been registered:%n%n%1%n%nThanks for your support!'; Localized: '新的商业许可证密钥已注册:%n%n%1%n%n感谢您的支持！'),
    (English: 'Are you sure you want to remove your commercial license key and revert to non-commercial use only?'; Localized: '确定要移除您的商业许可证密钥并改回仅限非商业使用吗？'),
    (English: 'Commercial license key has been removed.'; Localized: '商业许可证密钥已移除。'),
    (English: 'Your version of Inno Setup has been updated! <a id="%1">See what''s new</a>.'; Localized: '您的 Inno Setup 版本已更新！<a id="%1">看看有哪些新变化</a>。'),
    (English: 'VS Code-style editor shortcuts added! Use the <a id="%1">Editor Keys option</a> in Options dialog.'; Localized: '已添加 VS Code 风格的编辑器快捷键！请在“选项”对话框中使用<a id="%1">“编辑器按键”选项</a>。'),
    (English: 'RTF Editor added, a built-in WordPad replacement! Use the <a id="%1">RTF Editor item</a> in Tools menu.'; Localized: '已添加 RTF 编辑器，它是内置的写字板替代品！请在“工具”菜单中使用<a id="%1">“RTF 编辑器”项</a>。'),
    (English: 'Inno Setup Compiler is available in your language! Use the <a id="%1">Language option</a> in Options dialog.'; Localized: 'Inno Setup Compiler 已提供您的语言版本！请在“选项”对话框中使用<a id="%1">“语言”选项</a>。'),
    (English: '<a id="%1">Ideas board is open!</a> Share your ideas and vote on others, this month only.'; Localized: '<a id="%1">创意板已开放！</a>分享您的想法并为其他人的想法投票，仅限本月。'),
    (English: 'Running a version released after your update entitlement ended. <a id="%1">Renew license</a>, <a id="%2">remove key</a>, or <a id="%3">exit</a>.'; Localized: '正在运行更新权益结束后发布的版本。<a id="%1">续订许可证</a>、<a id="%2">移除密钥</a>或<a id="%3">退出</a>。'),
    (English: 'Your update entitlement is ending soon. Please <a id="%1">renew your license</a>. Thanks!'; Localized: '您的更新权益即将到期。请<a id="%1">续订您的许可证</a>。谢谢！'),
    (English: 'Your update entitlement has ended. Please <a id="%1">renew your license</a>. Thanks!'; Localized: '您的更新权益已到期。请<a id="%1">续订您的许可证</a>。谢谢！'),
    (English: 'Using Inno Setup commercially? Please <a id="%1">purchase a license</a>. Thanks!'; Localized: '在商业使用 Inno Setup 吗？请<a id="%1">购买许可证</a>。谢谢！'),
    (English: 'Uninstall'; Localized: '卸载'),
    (English: '%1 exit code: 0x%2'; Localized: '%1 退出代码: 0x%2'),
    (English: '%1 exit code: %2'; Localized: '%1 退出代码: %2'),
    (English: 'Unable to get %1 exit code (%2 failed)'; Localized: '无法获取 %1 的退出代码 (%2 失败)'),
    (English: '%1 is still running; can''t get exit code'; Localized: '%1 仍在运行；无法获取退出代码'),
    (English: 'Please stop the running %1 process before performing this command.'; Localized: '请在执行此命令前停止正在运行的 %1 进程。'),
    (English: 'This command will detach the debugger from the running %1 process. Continue?'; Localized: '此命令会将调试器与正在运行的 %1 进程分离。是否继续？'),
    (English: 'The changes you made will not take effect until you re-compile.%n%nContinue running anyway?'; Localized: '您所做的更改在重新编译之前不会生效。%n%n仍要继续运行吗？'),
    (English: 'A pause is already pending.'; Localized: '已有一个暂停请求在等待处理。'),
    (English: 'No code was generated for the current line.'; Localized: '当前行没有生成任何代码。'),
    (English: 'This will unconditionally terminate the running %1 process. Continue?'; Localized: '这将无条件终止正在运行的 %1 进程。是否继续？'),
    (English: 'Note that if %1 is currently in the installation phase, any changes made to the system thus far will not be undone, nor will uninstall data be written.'; Localized: '请注意，如果 %1 当前处于安装阶段，则迄今为止对系统所做的更改将不会被撤销，也不会写入卸载数据。'),
    (English: 'Evaluate'; Localized: '求值'),
    (English: 'Constant to evaluate (for example, "%1"):'; Localized: '要求值的常量 (例如“%1”)：'),
    (English: 'Evaluate Result'; Localized: '求值结果'),
    (English: 'Evaluate Error'; Localized: '求值错误'),
    (English: 'An unknown error occurred.'; Localized: '发生未知错误。'),
    (English: '%1 = "%2"'; Localized: '%1 = “%2”'),
    (English: '%1 = Exception: %2'; Localized: '%1 = 异常: %2'),
    (English: '%1 = Unknown error'; Localized: '%1 = 未知错误'),
    (English: 'Unknown error'; Localized: '未知错误'),
    (English: 'Line %1:%n%2'; Localized: '行 %1:%n%2'),
    (English: 'Runtime Error'; Localized: '运行时错误'),
    (English: '%1 (Update entitlement ended)'; Localized: '%1 (更新权益已结束)'),
    (English: '%1 (Update entitlement ended but updated anyway)'; Localized: '%1 (更新权益已结束但仍进行了更新)'),
    (English: 'Non-commercial use only'; Localized: '仅限非商业使用'),
    (English: 'Single User'; Localized: 'Single User'),
    (English: 'Team'; Localized: 'Team'),
    (English: 'Enterprise'; Localized: 'Enterprise'),
    (English: 'Inno Setup %1 License'; Localized: 'Inno Setup %1 许可证'),
    (English: '%1, %2.'; Localized: '%1，%2。'),
    (English: 'Includes updates until %1, major and minor.'; Localized: '包含截至 %1 的主要和次要更新。'),
    (English: 'Includes all future updates, major and minor.'; Localized: '包含未来的所有主要和次要更新。'),
    (English: '%1 Entries Designer'; Localized: '%1 条目设计器'),
    (English: '&Insert'; Localized: '插入(&I)'),
    (English: '&Parameters...'; Localized: '参数(&P)...'),
    (English: 'Remo&ve'; Localized: '移除(&V)'),
    (English: 'Add Fol&der...'; Localized: '添加文件夹(&D)...'),
    (English: '&Add File(s)...'; Localized: '添加文件(&A)...'),
    (English: '&Files:'; Localized: '文件(&F)：'),
    (English: 'Add D&ownload...'; Localized: '添加下载(&O)...'),
    (English: 'Go to File'; Localized: '转到文件'),
    (English: 'Enter Commercial License Key'; Localized: '输入商业许可证密钥'),
    (English: 'Paste your license key below'; Localized: '在下方粘贴您的许可证密钥'),
    (English: 'Close'; Localized: '关闭'),
    (English: 'Filter'; Localized: '筛选'),
    (English: 'New Main Script (%1)'; Localized: '新建主脚本 (%1)'),
    (English: 'Open Main Script (%1)'; Localized: '打开主脚本 (%1)'),
    (English: 'Save (%1)'; Localized: '保存 (%1)'),
    (English: 'Stop Compile (%1)'; Localized: '停止编译 (%1)'),
    (English: 'Target Setup (%1)'; Localized: '将目标设为安装 (%1)'),
    (English: 'Target Uninstall (%1)'; Localized: '将目标设为卸载 (%1)'),
    (English: 'Help (%1)'; Localized: '帮助 (%1)'),
    (English: 'Main Script'; Localized: '主脚本'),
    (English: 'Close Banner'; Localized: '关闭横幅'),
    (English: '&File'; Localized: '文件(&F)'),
    (English: '&Open...'; Localized: '打开(&O)...'),
    (English: 'Open &Recent'; Localized: '最近打开的文件(&R)'),
    (English: '&Clear Recently Opened'; Localized: '清空最近打开的文件(&C)'),
    (English: '&Save'; Localized: '保存(&S)'),
    (English: 'Save &As...'; Localized: '另存为(&A)...'),
    (English: 'Save &Encoding'; Localized: '保存编码(&E)'),
    (English: '&Auto (ANSI or UTF-8)'; Localized: '自动(&A) (ANSI 或 UTF-8)'),
    (English: '&UTF-8'; Localized: 'UTF-8(&U)'),
    (English: 'UTF-8 with &BOM'; Localized: '带 BOM 的 UTF-8(&B)'),
    (English: 'Sa&ve All'; Localized: '全部保存(&V)'),
    (English: '&Print...'; Localized: '打印(&P)...'),
    (English: 'E&xit'; Localized: '退出(&X)'),
    (English: '&Edit'; Localized: '编辑(&E)'),
    (English: '&Undo'; Localized: '撤销(&U)'),
    (English: '&Redo'; Localized: '重做(&R)'),
    (English: 'Cu&t'; Localized: '剪切(&T)'),
    (English: '&Copy'; Localized: '复制(&C)'),
    (English: '&Paste'; Localized: '粘贴(&P)'),
    (English: 'De&lete'; Localized: '删除(&L)'),
    (English: 'Select &All'; Localized: '全选(&A)'),
    (English: 'Add Next &Occurrence'; Localized: '添加下一个匹配项(&O)'),
    (English: '&Select All Occurrences'; Localized: '选择所有匹配项(&S)'),
    (English: 'Select All Find &Matches'; Localized: '选择所有查找匹配项(&M)'),
    (English: '&Find...'; Localized: '查找(&F)...'),
    (English: 'F&ind in Files...'; Localized: '在文件中查找(&I)...'),
    (English: 'Find &Next'; Localized: '查找下一个(&N)'),
    (English: 'Find Pre&vious'; Localized: '查找上一个(&V)'),
    (English: 'R&eplace...'; Localized: '替换(&E)...'),
    (English: 'Use Regular E&xpressions'; Localized: '使用正则表达式(&X)'),
    (English: 'Fol&d Section'; Localized: '折叠节(&D)'),
    (English: '&Unfold Section'; Localized: '展开节(&U)'),
    (English: 'Go to File...'; Localized: '转到文件...'),
    (English: '&Go to Line...'; Localized: '转到行(&G)...'),
    (English: 'Toggle Line Comment'; Localized: '切换行注释'),
    (English: 'Go To Matching Brace'; Localized: '转到匹配的括号'),
    (English: '&View'; Localized: '查看(&V)'),
    (English: '&Zoom'; Localized: '缩放(&Z)'),
    (English: 'Zoom &In'; Localized: '放大(&I)'),
    (English: 'Zoom &Out'; Localized: '缩小(&O)'),
    (English: '&Reset'; Localized: '重置(&R)'),
    (English: '&Toolbar'; Localized: '工具栏(&T)'),
    (English: '&Inspector'; Localized: '检查器(&I)'),
    (English: 'St&atus Bar'; Localized: '状态栏(&A)'),
    (English: '&Next Tab'; Localized: '下一个标签页(&N)'),
    (English: '&Previous Tab'; Localized: '上一个标签页(&P)'),
    (English: 'C&lose Tab'; Localized: '关闭标签页(&L)'),
    (English: 'Re&open Tab'; Localized: '重新打开标签页(&O)'),
    (English: 'Reopen &All Tabs'; Localized: '重新打开所有标签页(&A)'),
    (English: 'C&lose Current Tab'; Localized: '关闭当前标签页(&L)'),
    (English: '&Compiler Output'; Localized: '编译输出(&C)'),
    (English: '&Debug Output'; Localized: '调试输出(&D)'),
    (English: 'D&ebug Call Stack'; Localized: '调试调用堆栈(&E)'),
    (English: '&Find Results'; Localized: '查找结果(&F)'),
    (English: '&Hide Bottom Pane'; Localized: '隐藏底部窗格(&H)'),
    (English: '&Word Wrap'; Localized: '自动换行(&W)'),
    (English: '&Build'; Localized: '生成(&B)'),
    (English: '&Compile'; Localized: '编译(&C)'),
    (English: 'S&top Compile'; Localized: '停止编译(&T)'),
    (English: '&Low Priority During Compile'; Localized: '编译期间低优先级(&L)'),
    (English: '&Disable Output'; Localized: '禁用输出(&D)'),
    (English: 'Disable Co&mpression'; Localized: '禁用压缩(&M)'),
    (English: 'Disable &Signing'; Localized: '禁用签名(&S)'),
    (English: 'Disable Signcheck &Validation'; Localized: '禁用签名检查验证(&V)'),
    (English: '&Open Output Folder'; Localized: '打开输出文件夹(&O)'),
    (English: '&Run'; Localized: '运行(&R)'),
    (English: '&Run...'; Localized: '运行(&R)...'),
    (English: 'Run to &Cursor'; Localized: '运行到光标处(&C)'),
    (English: 'Step &Into'; Localized: '步入(&I)'),
    (English: 'Step &Over'; Localized: '步过(&O)'),
    (English: 'Step Out'; Localized: '步出'),
    (English: 'Toggle &Breakpoint'; Localized: '切换断点(&B)'),
    (English: '&Delete All Breakpoints'; Localized: '删除所有断点(&D)'),
    (English: 'P&ause'; Localized: '暂停(&A)'),
    (English: '&Terminate'; Localized: '终止(&T)'),
    (English: '&Evaluate Constant...'; Localized: '求值常量(&E)...'),
    (English: 'Target &Setup'; Localized: '将目标设为安装(&S)'),
    (English: 'Target &Uninstall'; Localized: '将目标设为卸载(&U)'),
    (English: '&Tools'; Localized: '工具(&T)'),
    (English: '&Add/Remove Programs'; Localized: '程序和功能(&A)'),
    (English: 'Generate &GUID'; Localized: '生成 GUID(&G)'),
    (English: 'Generate %1 Entries...'; Localized: '生成 %1 条目...'),
    (English: 'Generate %1 Call...'; Localized: '生成 %1 调用...'),
    (English: '&Configure Sign Tools...'; Localized: '配置签名工具(&C)...'),
    (English: 'R&TF Editor...'; Localized: 'RTF 编辑器(&T)...'),
    (English: '&Options...'; Localized: '选项(&O)...'),
    (English: '&Help'; Localized: '帮助(&H)'),
    (English: 'Purchase or Renew Commercial &License'; Localized: '购买或续订商业许可证(&L)'),
    (English: 'Enter Commercial License &Key...'; Localized: '输入商业许可证密钥(&K)...'),
    (English: 'Remove Commercial License Key'; Localized: '移除商业许可证密钥'),
    (English: '&Donate'; Localized: '捐赠(&D)'),
    (English: '&Keyboard And Mouse Commands'; Localized: '键盘和鼠标命令(&K)'),
    (English: 'Regular E&xpressions'; Localized: '正则表达式(&X)'),
    (English: 'Inno &Setup Documentation'; Localized: 'Inno Setup 文档(&S)'),
    (English: 'Inno Setup &Example Scripts'; Localized: 'Inno Setup 示例脚本(&E)'),
    (English: 'Inno Setup &FAQ'; Localized: 'Inno Setup 常见问题(&F)'),
    (English: 'Inno Setup &Mailing List'; Localized: 'Inno Setup 邮件列表(&M)'),
    (English: 'Inno Setup &Revision History'; Localized: 'Inno Setup 修订历史(&R)'),
    (English: 'Inno Setup &Web Site'; Localized: 'Inno Setup 网站(&W)'),
    (English: 'Inno Setup &Preprocessor Documentation'; Localized: 'Inno Setup 预处理器文档(&P)'),
    (English: '&About Inno Setup'; Localized: '关于 Inno Setup(&A)'),
    (English: '%1 Call Designer'; Localized: '%1 调用设计器'),
    (English: 'Instruction'; Localized: '指示'),
    (English: 'Message'; Localized: '消息'),
    (English: 'Buttons'; Localized: '按钮'),
    (English: ' Type '; Localized: ' 类型 '),
    (English: 'Suppressible'; Localized: '可抑制'),
    (English: ' Flags '; Localized: ' 标志 '),
    (English: 'Default button'; Localized: '默认按钮'),
    (English: ' Icon '; Localized: ' 图标 '),
    (English: ' Return values '; Localized: ' 返回值 '),
    (English: '&Preview'; Localized: '预览(&P)'),
    (English: 'Options'; Localized: '选项'),
    (English: ' Miscellaneous '; Localized: ' 其他 '),
    (English: 'Show &Welcome dialog at startup'; Localized: '启动时显示欢迎对话框(&W)'),
    (English: 'Use the Inno Setup &Script Wizard'; Localized: '使用 Inno Setup 脚本向导(&S)'),
    (English: 'Automatically sa&ve before compiling'; Localized: '编译前自动保存(&V)'),
    (English: 'Create &backups when saving'; Localized: '保存时创建备份(&B)'),
    (English: 'Allow &Undo after save'; Localized: '保存后允许撤销(&U)'),
    (English: 'Display &full path in title bar'; Localized: '在标题栏中显示完整路径(&F)'),
    (English: '&Pause on exceptions'; Localized: '在出现异常时暂停(&P)'),
    (English: '&Launch Setup/Uninstall as administrator'; Localized: '以管理员身份启动安装/卸载(&L)'),
    (English: 'Colori&ze "Compiler Output" view'; Localized: '为“编译输出”视图着色(&Z)'),
    (English: 'Automatically open %1 files'; Localized: '自动打开 %1 文件'),
    (English: 'Automatically show preprocessor output'; Localized: '自动显示预处理器输出'),
    (English: 'Menu &keys:'; Localized: '菜单键(&K)：'),
    (English: 'Automatically reload files'; Localized: '自动重新加载文件'),
    (English: 'Allow Undo after reload'; Localized: '重新加载后允许撤销'),
    (English: 'Keep new %1 files closed'; Localized: '使新的 %1 文件保持关闭'),
    (English: 'Language:'; Localized: '语言：'),
    (English: ' Inspector '; Localized: ' 检查器 '),
    (English: 'Show all known directives'; Localized: '显示所有已知指令'),
    (English: 'Quote new directive values'; Localized: '为新指令值加引号'),
    (English: 'Quote new parameter values'; Localized: '为新参数值加引号'),
    (English: ' Editor '; Localized: ' 编辑器 '),
    (English: 'Invoke autoco&mplete automatically'; Localized: '自动调用自动完成(&M)'),
    (English: 'Use syntax &highlighting'; Localized: '使用语法突出显示(&H)'),
    (English: 'U&nderline syntax errors'; Localized: '为语法错误添加下划线(&N)'),
    (English: 'Allow cursor to move beyond &end of lines'; Localized: '允许光标移动到行尾之外(&E)'),
    (English: 'Enable section f&olding'; Localized: '启用节折叠(&O)'),
    (English: 'Use tab cha&racter'; Localized: '使用制表符(&R)'),
    (English: 'Auto &indent mode'; Localized: '自动缩进模式(&I)'),
    (English: 'Show indentation &guides'; Localized: '显示缩进参考线(&G)'),
    (English: 'Font:'; Localized: '字体：'),
    (English: 'AaBbXxZz'; Localized: 'AaBbXxZz'),
    (English: '&Change...'; Localized: '更改(&C)...'),
    (English: '&Tab Width:'; Localized: '制表符宽度(&T)：'),
    (English: 'Show &line numbers in gutter'; Localized: '在装订线中显示行号(&L)'),
    (English: 'T&heme:'; Localized: '主题(&H)：'),
    (English: 'Highlight occurrences of current selection'; Localized: '突出显示当前选区的出现位置'),
    (English: 'Highlight occurrences of current wor&d'; Localized: '突出显示当前单词的出现位置(&D)'),
    (English: 'Ke&ys:'; Localized: '按键(&Y)：'),
    (English: 'Show whitespace'; Localized: '显示空白字符'),
    (English: 'Smart Home key'; Localized: '智能 Home 键'),
    (English: '&Associate .%1 files with this compiler'; Localized: '将 .%1 文件与此编译器关联(&A)'),
    (English: '&Windows registry file (.%1) to import:'; Localized: '要导入的 Windows 注册表文件 (.%1)(&W)：'),
    (English: 'B&rowse...'; Localized: '浏览(&R)...'),
    (English: 'Settings (for all keys and values):'; Localized: '设置 (针对所有项和值)：'),
    (English: 'Also delete keys which are not empty'; Localized: '同时删除非空的项'),
    (English: 'Delete keys which are empty on uninstall'; Localized: '卸载时删除为空的项'),
    (English: 'Delete values on uninstall'; Localized: '卸载时删除值'),
    (English: 'Minimum Windows version:'; Localized: '最低 Windows 版本：'),
    (English: 'RTF Editor'; Localized: 'RTF 编辑器'),
    (English: 'New (%1)'; Localized: '新建 (%1)'),
    (English: 'Open (%1)'; Localized: '打开 (%1)'),
    (English: 'Cut (%1)'; Localized: '剪切 (%1)'),
    (English: 'Copy (%1)'; Localized: '复制 (%1)'),
    (English: 'Paste (%1)'; Localized: '粘贴 (%1)'),
    (English: 'Undo (%1)'; Localized: '撤销 (%1)'),
    (English: 'Redo (%1)'; Localized: '重做 (%1)'),
    (English: 'Bold (%1)'; Localized: '加粗 (%1)'),
    (English: 'Italic (%1)'; Localized: '斜体 (%1)'),
    (English: 'Underline (%1)'; Localized: '下划线 (%1)'),
    (English: '&Bold'; Localized: '加粗(&B)'),
    (English: '&Italic'; Localized: '斜体(&I)'),
    (English: '&Underline'; Localized: '下划线(&U)'),
    (English: '&Font...'; Localized: '字体(&F)...'),
    (English: '&Increase Font Size'; Localized: '增大字号(&I)'),
    (English: '&Decrease Font Size'; Localized: '减小字号(&D)'),
    (English: 'Text &Color...'; Localized: '文字颜色(&C)...'),
    (English: '&Background Color...'; Localized: '背景颜色(&B)...'),
    (English: 'Reset &Colors'; Localized: '重置颜色(&C)'),
    (English: 'Align &Left'; Localized: '左对齐(&L)'),
    (English: '&Center'; Localized: '居中(&C)'),
    (English: 'Align &Right'; Localized: '右对齐(&R)'),
    (English: 'Bulle&ts'; Localized: '项目符号(&T)'),
    (English: 'Increase &Indent'; Localized: '增加缩进(&I)'),
    (English: 'Decrease Inden&t'; Localized: '减少缩进(&T)'),
    (English: 'Configure Sign Tools'; Localized: '配置签名工具'),
    (English: ' Sign Tools '; Localized: ' 签名工具 '),
    (English: '&Add...'; Localized: '添加(&A)...'),
    (English: '&Edit...'; Localized: '编辑(&E)...'),
    (English: 'Be notified by e-mail of new Inno Setup releases'; Localized: '通过电子邮件获取 Inno Setup 新版本的通知'),
    (English: 'Subscribe'; Localized: '订阅'),
    (English: ' New file '; Localized: ' 新建文件 '),
    (English: 'Create a new &empty script file'; Localized: '创建新的空脚本文件(&E)'),
    (English: 'Create a new script file using the &Script Wizard'; Localized: '使用脚本向导创建新的脚本文件(&S)'),
    (English: ' Open file '; Localized: ' 打开文件 '),
    (English: 'Open an e&xisting script file'; Localized: '打开现有的脚本文件(&X)'),
    (English: '&Don''t show this dialog again'; Localized: '不再显示此对话框(&D)'),
    (English: 'Script Wizard File'; Localized: '脚本向导文件'),
    (English: 'bold'; Localized: '粗体'),
    (English: ' = required'; Localized: ' = 必填'),
    (English: ' Destination '; Localized: ' 目标 '),
    (English: 'Destination &base folder:'; Localized: '目标基文件夹(&B)：'),
    (English: 'Destination &subfolder:'; Localized: '目标子文件夹(&S)：'),
    (English: 'Destination &name:'; Localized: '目标名称(&N)：'),
    (English: ' Source '; Localized: ' 源 '),
    (English: '&Source file or folder:'; Localized: '源文件或文件夹(&S)：'),
    (English: '&Recurse subfolders'; Localized: '递归处理子文件夹(&R)'),
    (English: '&Include empty subfolders'; Localized: '包含空的子文件夹(&I)'),
    (English: '&Extract archive'; Localized: '解压压缩包(&E)'),
    (English: 'Welcome to the %1'; Localized: '欢迎使用 %1'),
    (English: 'This wizard will guide you through the process of creating a new Inno Setup script file. The results will be used to generate a new script file which can be compiled directly or saved on disk for later use.%n%n'+'Not all features of Inno Setup are covered by this wizard. See the documentation for details on creating Inno Setup script files.%n%nClick Next to continue, or Cancel to exit this wizard.';
     Localized: '本向导将指导您完成创建新的 Inno Setup 脚本文件的过程。所填写的内容将用于生成新的脚本文件，生成的脚本文件既可以直接编译，也可以保存到磁盘以供以后使用。%n%n'+'本向导并未涵盖 Inno Setup 的所有功能。有关创建 Inno Setup 脚本文件的详细信息，请参阅文档。%n%n点击“下一步”继续，或点击“取消”退出本向导。'),
    (English: 'Application na&me:'; Localized: '应用程序名称(&M)：'),
    (English: 'Application &version:'; Localized: '应用程序版本(&V)：'),
    (English: 'Application &publisher:'; Localized: '应用程序发布者(&P)：'),
    (English: 'Application &website:'; Localized: '应用程序网站(&W)：'),
    (English: 'Application folder na&me:'; Localized: '应用程序文件夹名称(&M)：'),
    (English: 'Application &destination base folder:'; Localized: '应用程序目标基文件夹(&D)：'),
    (English: 'Other:'; Localized: '其他：'),
    (English: 'Allow user to &change the application folder'; Localized: '允许用户更改应用程序文件夹(&C)'),
    (English: 'The application doe&sn''t need a folder'; Localized: '应用程序不需要文件夹(&S)'),
    (English: 'Other application &files:'; Localized: '其他应用程序文件(&F)：'),
    (English: 'Application &main executable file:'; Localized: '应用程序主可执行文件(&M)：'),
    (English: 'Allow &user to start the application after Setup has finished'; Localized: '允许用户在安装程序完成后启动应用程序(&U)'),
    (English: 'The application doe&sn''t have a main executable file'; Localized: '应用程序没有主可执行文件(&S)'),
    (English: 'Application file type na&me:'; Localized: '应用程序文件类型名称(&M)：'),
    (English: '&Associate a file type to the main executable'; Localized: '将文件类型关联到主可执行文件(&A)'),
    (English: 'Application file type &extension:'; Localized: '应用程序文件类型扩展名(&E)：'),
    (English: 'Application &Start Menu folder name:'; Localized: '应用程序开始菜单文件夹名称(&S)：'),
    (English: 'Other shortcuts to the main executable:'; Localized: '主可执行文件的其他快捷方式：'),
    (English: 'Allow user to &change the Start Menu folder name'; Localized: '允许用户更改开始菜单文件夹名称(&C)'),
    (English: 'Allow user to &disable Start Menu folder creation'; Localized: '允许用户禁用开始菜单文件夹的创建(&D)'),
    (English: 'Allow user to create a deskto&p shortcut'; Localized: '允许用户创建桌面快捷方式(&P)'),
    (English: 'Create an &Uninstall shortcut in the Start Menu folder'; Localized: '在开始菜单文件夹中创建卸载快捷方式(&U)'),
    (English: 'Create an &Internet shortcut in the Start Menu folder'; Localized: '在开始菜单文件夹中创建 Internet 快捷方式(&I)'),
    (English: '&Create a Start Menu shortcut but no folder'; Localized: '创建开始菜单快捷方式但不创建文件夹(&C)'),
    (English: '&License file:'; Localized: '许可协议文件(&L)：'),
    (English: '&Information file shown before installation:'; Localized: '安装前显示的信息文件(&I)：'),
    (English: 'Information file shown &after installation:'; Localized: '安装后显示的信息文件(&A)：'),
    (English: 'Install mode:'; Localized: '安装模式：'),
    (English: '&Administrative install mode (install for all users)'; Localized: '管理员安装模式(&A) (为所有用户安装)'),
    (English: 'Non a&dministrative install mode (install for current user only)'; Localized: '非管理员安装模式(&D) (仅为当前用户安装)'),
    (English: 'Allow user to &override the install mode via the command line'; Localized: '允许用户通过命令行覆盖安装模式(&O)'),
    (English: 'Ask the user to &choose the install mode at startup'; Localized: '在启动时要求用户选择安装模式(&C)'),
    (English: '&Languages:'; Localized: '语言(&L)：'),
    (English: '&Deselect All'; Localized: '全部取消选择(&D)'),
    (English: 'Custom compiler output fol&der:'; Localized: '自定义编译器输出文件夹(&D)：'),
    (English: 'Compiler output base &file name:'; Localized: '编译器输出基文件名(&F)：'),
    (English: 'Custom Setup &icon file:'; Localized: '自定义安装程序图标文件(&I)：'),
    (English: 'Setup &password:'; Localized: '安装程序密码(&P)：'),
    (English: 'Use the password to &encrypt the application files'; Localized: '使用密码加密应用程序文件(&E)'),
    (English: '&Wizard style:'; Localized: '向导样式(&W)：'),
    (English: 'You have successfully completed the %1.%n%nTo close this wizard and generate the new script file, click Finish.'; Localized: '您已成功完成 %1。%n%n点击“完成”关闭此向导并生成新的脚本文件。'),
    (English: '&Back'; Localized: '上一步(&B)'),
    (English: '''%s'' is not a valid integer value'; Localized: '''%s'' 不是有效的整数值'),
    (English: '''%s'' is not a valid integer value for %s type'; Localized: '''%s'' 不是 %s 类型的有效整数值'),
    (English: '''%s'' is not a valid floating point value'; Localized: '''%s'' 不是有效的浮点数值'),
    (English: '''%d.%d'' is not a valid timestamp'; Localized: '''%d.%d'' 不是有效的时间戳'),
    (English: '''%s'' is not a valid GUID value'; Localized: '''%s'' 不是有效的 GUID 值'),
    (English: 'Invalid argument to time encode'; Localized: '时间编码的参数无效'),
    (English: 'Invalid argument to date encode'; Localized: '日期编码的参数无效'),
    (English: 'Out of memory'; Localized: '内存不足'),
    (English: 'I/O error %d'; Localized: 'I/O 错误 %d'),
    (English: 'File not found'; Localized: '找不到文件'),
    (English: 'Invalid filename'; Localized: '无效的文件名'),
    (English: 'Too many open files'; Localized: '打开的文件过多'),
    (English: 'File access denied'; Localized: '文件访问被拒绝'),
    (English: 'Read beyond end of file'; Localized: '读取超出文件末尾'),
    (English: 'Disk full'; Localized: '磁盘已满'),
    (English: 'Invalid numeric input'; Localized: '无效的数字输入'),
    (English: 'Division by zero'; Localized: '除以零'),
    (English: 'Range check error'; Localized: '范围检查错误'),
    (English: 'Integer overflow'; Localized: '整数溢出'),
    (English: 'Invalid floating point operation'; Localized: '无效的浮点运算'),
    (English: 'Floating point division by zero'; Localized: '浮点数除以零'),
    (English: 'Floating point overflow'; Localized: '浮点数上溢'),
    (English: 'Floating point underflow'; Localized: '浮点数下溢'),
    (English: 'Invalid pointer operation'; Localized: '无效的指针操作'),
    (English: 'Invalid class typecast'; Localized: '无效的类类型转换'),
    (English: 'Access violation at address %p. %s of address %p'; Localized: '在地址 %p 处发生访问冲突。%s地址 %p 时出错'),
    (English: 'Access violation'; Localized: '访问冲突'),
    (English: 'Stack overflow'; Localized: '堆栈溢出'),
    (English: 'Control-C hit'; Localized: '按下了 Control-C'),
    (English: 'Privileged instruction'; Localized: '特权指令'),
    (English: 'Operation aborted'; Localized: '操作已中止'),
    (English: 'Exception %s in module %s at %p.'#13#10'%s%s'#13#10; Localized: '模块 %s 中 %p 处发生异常 %s。'#13#10'%s%s'#13#10),
    (English: 'Application Error'; Localized: '应用程序错误'),
    (English: 'Format ''%s'' invalid or incompatible with argument'; Localized: '格式 ''%s'' 无效或与参数不兼容'),
    (English: 'No argument for format ''%s'''; Localized: '格式 ''%s'' 缺少参数'),
    (English: 'Variant method calls not supported'; Localized: '不支持 Variant 方法调用'),
    (English: 'Read'; Localized: '读取'),
    (English: 'Write'; Localized: '写入'),
    (English: 'Execution'; Localized: '执行'),
    (English: 'Invalid access'; Localized: '无效访问'),
    (English: 'Error creating variant or safe array'; Localized: '创建 Variant 或安全数组时出错'),
    (English: 'Variant or safe array index out of bounds'; Localized: 'Variant 或安全数组的索引超出范围'),
    (English: 'Variant or safe array is locked'; Localized: 'Variant 或安全数组已锁定'),
    (English: 'Invalid variant type conversion'; Localized: '无效的 Variant 类型转换'),
    (English: 'Invalid variant operation'; Localized: '无效的 Variant 操作'),
    (English: 'Invalid NULL variant operation'; Localized: '无效的 NULL Variant 操作'),
    (English: 'Invalid variant operation (%s%.8x)'#10'%s'; Localized: '无效的 Variant 操作 (%s%.8x)'#10'%s'),
    (English: 'Could not convert variant of type (%s) into type (%s)'; Localized: '无法将类型 (%s) 的 Variant 转换为类型 (%s)'),
    (English: 'Overflow while converting variant of type (%s) into type (%s)'; Localized: '将类型 (%s) 的 Variant 转换为类型 (%s) 时发生溢出'),
    (English: 'Variant overflow'; Localized: 'Variant 溢出'),
    (English: 'Invalid argument'; Localized: '无效的参数'),
    (English: 'Invalid variant type'; Localized: '无效的 Variant 类型'),
    (English: 'Operation not supported'; Localized: '不支持此操作'),
    (English: 'Unexpected variant error'; Localized: '意外的 Variant 错误'),
    (English: 'External exception %x'; Localized: '外部异常 %x'),
    (English: 'Assertion failed'; Localized: '断言失败'),
    (English: 'Interface not supported'; Localized: '不支持此接口'),
    (English: 'Exception in safecall method'; Localized: 'safecall 方法中发生异常'),
    (English: 'Object lock not owned'; Localized: '未持有对象锁'),
    (English: 'Monitor support function not initialized'; Localized: '监视器支持函数未初始化'),
    (English: 'Feature not implemented'; Localized: '功能未实现'),
    (English: 'Method called on disposed object'; Localized: '对已释放的对象调用了方法'),
    (English: '%s (%s, line %d)'; Localized: '%s (%s, 第 %d 行)'),
    (English: 'Abstract Error'; Localized: '抽象错误'),
    (English: 'Access violation at address %p in module ''%s'' (offset %x). %s of address %p'; Localized: '在模块 ''%s'' (偏移 %x) 的地址 %p 处发生访问冲突。%s地址 %p 时出错'),
    (English: 'System Error.  Code: %d.'#13#10'%s%s'; Localized: '系统错误。代码: %d。'#13#10'%s%s'),
    (English: 'A call to an OS function failed'; Localized: 'OS 函数调用失败'),
    (English: 'Jan'; Localized: '1月'),
    (English: 'Feb'; Localized: '2月'),
    (English: 'Mar'; Localized: '3月'),
    (English: 'Apr'; Localized: '4月'),
    (English: 'May'; Localized: '5月'),
    (English: 'Jun'; Localized: '6月'),
    (English: 'Jul'; Localized: '7月'),
    (English: 'Aug'; Localized: '8月'),
    (English: 'Sep'; Localized: '9月'),
    (English: 'Oct'; Localized: '10月'),
    (English: 'Nov'; Localized: '11月'),
    (English: 'Dec'; Localized: '12月'),
    (English: 'January'; Localized: '1月'),
    (English: 'February'; Localized: '2月'),
    (English: 'March'; Localized: '3月'),
    (English: 'April'; Localized: '4月'),
    (English: 'June'; Localized: '6月'),
    (English: 'July'; Localized: '7月'),
    (English: 'August'; Localized: '8月'),
    (English: 'September'; Localized: '9月'),
    (English: 'October'; Localized: '10月'),
    (English: 'November'; Localized: '11月'),
    (English: 'December'; Localized: '12月'),
    (English: 'Sun'; Localized: '日'),
    (English: 'Mon'; Localized: '一'),
    (English: 'Tue'; Localized: '二'),
    (English: 'Wed'; Localized: '三'),
    (English: 'Thu'; Localized: '四'),
    (English: 'Fri'; Localized: '五'),
    (English: 'Sat'; Localized: '六'),
    (English: 'Sunday'; Localized: '星期日'),
    (English: 'Monday'; Localized: '星期一'),
    (English: 'Tuesday'; Localized: '星期二'),
    (English: 'Wednesday'; Localized: '星期三'),
    (English: 'Thursday'; Localized: '星期四'),
    (English: 'Friday'; Localized: '星期五'),
    (English: 'Saturday'; Localized: '星期六'),
    (English: 'Invalid source array'; Localized: '无效的源数组'),
    (English: 'Invalid destination array'; Localized: '无效的目标数组'),
    (English: 'Character index out of bounds (%d)'; Localized: '字符索引超出范围 (%d)'),
    (English: 'Start index out of bounds (%d)'; Localized: '起始索引超出范围 (%d)'),
    (English: 'Invalid count (%d)'; Localized: '无效的计数 (%d)'),
    (English: 'Invalid destination index (%d)'; Localized: '无效的目标索引 (%d)'),
    (English: 'Invalid code page'; Localized: '无效的代码页'),
    (English: 'No mapping for the Unicode character exists in the target multi-byte code page'; Localized: '目标多字节代码页中不存在此 Unicode 字符的映射'),
    (English: 'Invalid StringBaseIndex'; Localized: '无效的 StringBaseIndex'),
    (English: '''%s'' is not a valid %s color value'; Localized: '''%s'' 不是有效的 %s 颜色值'),
    (English: 'Ancestor for ''%s'' not found'; Localized: '找不到 ''%s'' 的先祖'),
    (English: 'Cannot assign a %s to a %s'; Localized: '无法将 %s 赋给 %s'),
    (English: 'Bits index out of range'; Localized: '位索引超出范围'),
    (English: 'Can''t write to a read-only resource stream'; Localized: '无法写入只读的资源流'),
    (English: '''''%s'''' expected'; Localized: '需要 ''''%s'''''),
    (English: 'CheckSynchronize called from thread $%x, which is NOT the main thread'; Localized: 'CheckSynchronize 是从线程 $%x 调用的，而它不是主线程'),
    (English: 'Class %s not found'; Localized: '找不到类 %s'),
    (English: 'A class named %s already exists'; Localized: '名为 %s 的类已存在'),
    (English: 'List does not allow duplicates ($0%x)'; Localized: '列表不允许重复 ($0%x)'),
    (English: 'A component named %s already exists'; Localized: '名为 %s 的组件已存在'),
    (English: 'String list does not allow duplicates'; Localized: '字符串列表不允许重复'),
    (English: 'Cannot create file "%s". %s'; Localized: '无法创建文件“%s”。%s'),
    (English: 'Cannot open file "%s". %s'; Localized: '无法打开文件“%s”。%s'),
    (English: 'Identifier expected'; Localized: '需要标识符'),
    (English: 'Invalid binary value'; Localized: '无效的二进制值'),
    (English: 'Invalid stream format'; Localized: '无效的流格式'),
    (English: '''%s'' is an invalid mask at (%d)'; Localized: '''%s'' 在 (%d) 处是无效的掩码'),
    (English: '''''%s'''' is not a valid component name'; Localized: '''''%s'''' 不是有效的组件名'),
    (English: 'Invalid property value'; Localized: '无效的属性值'),
    (English: 'Invalid property path'; Localized: '无效的属性路径'),
    (English: 'Invalid data type for ''%s'''; Localized: '''%s'' 的数据类型无效'),
    (English: 'Invalid string constant'; Localized: '无效的字符串常量'),
    (English: 'Line too long'; Localized: '行太长'),
    (English: 'List capacity out of bounds (%d)'; Localized: '列表容量超出范围 (%d)'),
    (English: 'List count out of bounds (%d)'; Localized: '列表计数超出范围 (%d)'),
    (English: 'List index out of bounds (%d)'; Localized: '列表索引超出范围 (%d)'),
    (English: '.  %s range is 0..%d'; Localized: '.  %s 的范围为 0..%d'),
    (English: '.  %s is empty'; Localized: '.  %s 为空'),
    (English: 'Out of memory while expanding memory stream'; Localized: '扩展内存流时内存不足'),
    (English: '%s has not been registered as a COM class'; Localized: '%s 尚未注册为 COM 类'),
    (English: 'Printer is not currently printing'; Localized: '打印机当前未在打印'),
    (English: 'Number expected'; Localized: '需要数字'),
    (English: 'ANSI or UTF8 encoding expected'; Localized: '需要 ANSI 或 UTF8 编码'),
    (English: '%s on line %d'; Localized: '%s (第 %d 行)'),
    (English: 'Error reading %s%s%s: %s'; Localized: '读取 %s%s%s 时出错: %s'),
    (English: 'Printing in progress'; Localized: '正在打印'),
    (English: 'Stream read error'; Localized: '流读取错误'),
    (English: 'Property is read-only'; Localized: '属性是只读的'),
    (English: 'Failed to create key %s'; Localized: '创建项 %s 失败'),
    (English: 'Failed to get data for ''%s'''; Localized: '获取 ''%s'' 的数据失败'),
    (English: 'Failed to set data for ''%s'''; Localized: '设置 ''%s'' 的数据失败'),
    (English: 'Resource %s not found'; Localized: '找不到资源 %s'),
    (English: '%s.Seek not implemented'; Localized: '%s.Seek 未实现'),
    (English: 'Operation not allowed on sorted list'; Localized: '排序列表不允许此操作'),
    (English: 'String expected'; Localized: '需要字符串'),
    (English: '%s expected'; Localized: '需要 %s'),
    (English: '%s not in a class registration group'; Localized: '%s 不在类注册组中'),
    (English: 'Property %s does not exist'; Localized: '属性 %s 不存在'),
    (English: 'Stream write error'; Localized: '流写入错误'),
    (English: 'Thread creation error: %s'; Localized: '线程创建错误: %s'),
    (English: 'Thread Error: %s (%d)'; Localized: '线程错误: %s (%d)'),
    (English: 'Cannot terminate an externally created thread'; Localized: '无法终止外部创建的线程'),
    (English: 'Cannot wait for an externally created thread'; Localized: '无法等待外部创建的线程'),
    (English: 'Cannot call Start on a running or suspended thread'; Localized: '无法对正在运行或已挂起的线程调用 Start'),
    (English: 'Parameter %s cannot be nil'; Localized: '参数 %s 不能为 nil'),
    (English: 'Parameter %s cannot be a negative value'; Localized: '参数 %s 不能为负值'),
    (English: 'Invalid characters in path'; Localized: '路径中包含无效字符'),
    (English: 'Invalid characters in search pattern'; Localized: '搜索模式中包含无效字符'),
    (English: 'Path is empty'; Localized: '路径为空'),
    (English: 'Search pattern is empty'; Localized: '搜索模式为空'),
    (English: 'The specified path is too long'; Localized: '指定的路径太长'),
    (English: 'The specified path was not found'; Localized: '找不到指定的路径'),
    (English: 'The path format is not supported'; Localized: '不支持此路径格式'),
    (English: 'No help viewer that supports filters'; Localized: '没有支持筛选器的帮助查看器'),
    (English: 'String index out of range (%d).  Must be >= %d and <= %d'; Localized: '字符串索引超出范围 (%d)。必须 >= %d 且 <= %d'),
    (English: 'Invalid UTF32 character value.  Must be >= 0 and <= $10FFFF, excluding surrogate pair ranges'; Localized: '无效的 UTF32 字符值。必须 >= 0 且 <= $10FFFF，不包括代理项对范围'),
    (English: 'High surrogate char without a following low surrogate char at index: %d. Check that the string is encoded properly'; Localized: '索引 %d 处存在没有后续低位代理项的高位代理项。请检查字符串是否已正确编码'),
    (English: 'Low surrogate char without a preceding high surrogate char at index: %d. Check that the string is encoded properly'; Localized: '索引 %d 处存在没有前置高位代理项的低位代理项。请检查字符串是否已正确编码'),
    (English: 'Source and Destination arrays must not be the same'; Localized: '源数组和目标数组不能相同'),
    (English: 'SpinCount out of range. Must be between 0 and %d'; Localized: 'SpinCount 超出范围。必须介于 0 和 %d 之间'),
    (English: 'No context-sensitive help installed'; Localized: '未安装区分上下文的帮助'),
    (English: 'No help found for context %d'; Localized: '找不到上下文 %d 的帮助'),
    (English: 'Unable to open Index'; Localized: '无法打开“索引”'),
    (English: 'Unable to open Search'; Localized: '无法打开“搜索”'),
    (English: 'Unable to find a Table of Contents'; Localized: '找不到目录'),
    (English: 'No topic-based help system installed'; Localized: '未安装基于主题的帮助系统'),
    (English: 'No help found for %s'; Localized: '找不到 %s 的帮助'),
    (English: 'Argument out of range'; Localized: '参数超出范围'),
    (English: 'Argument must not be nil'; Localized: '参数不能为 nil'),
    (English: 'Item not found'; Localized: '找不到项'),
    (English: 'Duplicates not allowed'; Localized: '不允许重复'),
    (English: 'Insufficient RTTI available to support this operation'; Localized: '没有足够的 RTTI 来支持此操作'),
    (English: 'Parameter count mismatch'; Localized: '参数数量不匹配'),
    (English: 'Parameter count exceeded'; Localized: '参数数量超出'),
    (English: 'Type ''%s'' is not declared in the interface section of a unit'; Localized: '类型 ''%s'' 未在单元的 interface 部分中声明'),
    (English: 'VAR and OUT arguments must match parameter type exactly'; Localized: 'VAR 和 OUT 参数必须与参数类型完全匹配'),
    (English: 'Property ''%s'' is read-only'; Localized: '属性 ''%s'' 是只读的'),
    (English: 'Property ''%s'' is write-only'; Localized: '属性 ''%s'' 是只写的'),
    (English: 'RTTI objects cannot be manually destroyed by application code'; Localized: 'RTTI 对象不能由应用程序代码手动销毁'),
    (English: '%s (Version %d.%d, Build %d, %5:s)'; Localized: '%s (版本 %d.%d，内部版本 %d，%5:s)'),
    (English: '%s Service Pack %4:d (Version %1:d.%2:d, Build %3:d, %5:s)'; Localized: '%s Service Pack %4:d (版本 %1:d.%2:d，内部版本 %3:d，%5:s)'),
    (English: '32-bit Edition'; Localized: '32 位版本'),
    (English: '64-bit Edition'; Localized: '64 位版本'),
    (English: 'Windows'; Localized: 'Windows'),
    (English: 'Windows Vista'; Localized: 'Windows Vista'),
    (English: 'Windows Server 2008'; Localized: 'Windows Server 2008'),
    (English: 'Windows 7'; Localized: 'Windows 7'),
    (English: 'Windows Server 2008 R2'; Localized: 'Windows Server 2008 R2'),
    (English: 'Windows 2000'; Localized: 'Windows 2000'),
    (English: 'Windows XP'; Localized: 'Windows XP'),
    (English: 'Windows Server 2003'; Localized: 'Windows Server 2003'),
    (English: 'Windows Server 2003 R2'; Localized: 'Windows Server 2003 R2'),
    (English: 'Windows Server 2012'; Localized: 'Windows Server 2012'),
    (English: 'Windows Server 2012 R2'; Localized: 'Windows Server 2012 R2'),
    (English: 'Windows Server 2016'; Localized: 'Windows Server 2016'),
    (English: 'Windows Server 2019'; Localized: 'Windows Server 2019'),
    (English: 'Windows Server 2022'; Localized: 'Windows Server 2022'),
    (English: 'Windows 8'; Localized: 'Windows 8'),
    (English: 'Windows 8.1'; Localized: 'Windows 8.1'),
    (English: 'Windows 10'; Localized: 'Windows 10'),
    (English: 'Windows 11'; Localized: 'Windows 11'),
    (English: 'Cannot create instance of class %s'; Localized: '无法创建类 %s 的实例'),
    (English: 'Observer is not supported'; Localized: '不支持观察者'),
    (English: 'Cannot have multiple single cast observers added to the observers collection'; Localized: '不能向观察者集合添加多个单播观察者'),
    (English: 'The object does not implement the observer interface'; Localized: '对象未实现观察者接口'),
    (English: 'No single cast observer with ID %d was added to the observer collection'; Localized: '观察者集合中未添加 ID 为 %d 的单播观察者'),
    (English: 'No multi cast observer with ID %d was added to the observer collection'; Localized: '观察者集合中未添加 ID 为 %d 的多播观察者'),
    (English: 'Observer is not available'; Localized: '观察者不可用'),
    (English: 'SHA2: Cannot update a finalized hash'; Localized: 'SHA2: 无法更新已完成的哈希'),
    (English: 'Must wait on at least one event'; Localized: '必须至少等待一个事件'),
    (English: 'Cannot call BeginInvoke on a TComponent in the process of destruction'; Localized: '无法对正在销毁过程中的 TComponent 调用 BeginInvoke'),
    (English: 'OLE error %.8x'; Localized: 'OLE 错误 %.8x'),
    (English: 'Method ''%s'' not supported by automation object'; Localized: '自动化对象不支持方法 ''%s'''),
    (English: 'Variant does not reference an automation object'; Localized: 'Variant 未引用自动化对象'),
    (English: 'Dispatch methods do not support more than 64 parameters'; Localized: 'Dispatch 方法不支持超过 64 个参数'),
    (English: 'A regular expression specified in RegEx is required'; Localized: '需要在 RegEx 中指定正则表达式'),
    (English: 'Error in regular expression at offset %d: %s'; Localized: '正则表达式在偏移 %d 处有错误: %s'),
    (English: 'Successful match required'; Localized: '需要成功匹配'),
    (English: 'Index out of bounds (%d)'; Localized: '索引超出范围 (%d)'),
    (English: 'Bitmap image is not valid'; Localized: '位图图像无效'),
    (English: 'Icon image is not valid'; Localized: '图标图像无效'),
    (English: 'Metafile is not valid'; Localized: '图元文件无效'),
    (English: 'Invalid pixel format'; Localized: '无效的像素格式'),
    (English: 'Invalid image'; Localized: '无效的图像'),
    (English: 'Scan line index out of range'; Localized: '扫描线索引超出范围'),
    (English: 'Cannot change the size of an icon'; Localized: '无法更改图标的大小'),
    (English: 'Cannot change the size of a WIC Image'; Localized: '无法更改 WIC 图像的大小'),
    (English: 'Unsupported clipboard format'; Localized: '不支持的剪贴板格式'),
    (English: 'Unsupported stream format'; Localized: '不支持的流格式'),
    (English: 'Out of system resources'; Localized: '系统资源不足'),
    (English: 'Canvas does not allow drawing'; Localized: '画布不允许绘图'),
    (English: 'Text format flag ''%s'' not supported'; Localized: '不支持文本格式标志 ''%s'''),
    (English: 'Invalid image frame index %d: there are %d frames (0-%d)'; Localized: '无效的图像帧索引 %d: 共有 %d 帧 (0-%d)'),
    (English: 'Invalid image size'; Localized: '无效的图像大小'),
    (English: 'Invalid ImageList'; Localized: '无效的 ImageList'),
    (English: 'Invalid ImageList Index'; Localized: '无效的 ImageList 索引'),
    (English: 'Failed to read ImageList data from stream'; Localized: '从流读取 ImageList 数据失败'),
    (English: 'Failed to write ImageList data to stream'; Localized: '向流写入 ImageList 数据失败'),
    (English: 'Error creating window device context'; Localized: '创建窗口设备上下文时出错'),
    (English: 'Error creating window class'; Localized: '创建窗口类时出错'),
    (English: 'Cannot focus a disabled or invisible window'; Localized: '无法将焦点设置到已禁用或不可见的窗口'),
    (English: 'Control ''%s'' has no parent window'; Localized: '控件 ''%s'' 没有父窗口'),
    (English: '. Path:'#13#10'%s'; Localized: '. 路径:'#13#10'%s'),
    (English: 'Parent given is not a parent of ''%s'''; Localized: '给定的父级不是 ''%s'' 的父级'),
    (English: 'Cannot hide an MDI Child Form'; Localized: '无法隐藏 MDI 子窗体'),
    (English: 'Cannot change Visible in OnShow or OnHide'; Localized: '无法在 OnShow 或 OnHide 中更改 Visible'),
    (English: 'Cannot make a visible window modal'; Localized: '无法将可见窗口设为模态'),
    (English: 'Scrollbar property out of range'; Localized: '滚动条属性超出范围'),
    (English: '%s property out of range'; Localized: '%s 属性超出范围'),
    (English: 'Check state can only be set when CheckBoxes is True'; Localized: '仅当 CheckBoxes 为 True 时才能设置检查状态'),
    (English: 'Check state incompatible with treeview''s CheckStyles'; Localized: '检查状态与树视图的 CheckStyles 不兼容'),
    (English: 'Menu index out of range'; Localized: '菜单索引超出范围'),
    (English: 'Menu inserted twice'; Localized: '菜单被插入了两次'),
    (English: 'Sub-menu is not in menu'; Localized: '子菜单不在菜单中'),
    (English: 'Not enough timers available'; Localized: '没有足够多的可用计时器'),
    (English: 'Printer index out of range'; Localized: '打印机索引超出范围'),
    (English: 'Printer selected is not valid'; Localized: '选定的打印机无效'),
    (English: '%s on %s'; Localized: '%s (%s)'),
    (English: 'GroupIndex cannot be less than a previous menu item''s GroupIndex'; Localized: 'GroupIndex 不能小于前一个菜单项的 GroupIndex'),
    (English: 'Cannot create form. No MDI forms are currently active'; Localized: '无法创建窗体。当前没有活动的 MDI 窗体'),
    (English: 'Can only modify an image if it contains a bitmap'; Localized: '仅当图像包含位图时才能修改它'),
    (English: 'A control cannot have itself as its parent'; Localized: '控件不能将自身作为父级'),
    (English: 'Control ''%s'' is used on a not main thread'; Localized: '控件 ''%s'' 在非主线程中被使用'),
    (English: '&Yes'; Localized: '是(&Y)'),
    (English: '&No'; Localized: '否(&N)'),
    (English: '&Close'; Localized: '关闭(&C)'),
    (English: '&Ignore'; Localized: '忽略(&I)'),
    (English: '&Retry'; Localized: '重试(&R)'),
    (English: '&All'; Localized: '全部(&A)'),
    (English: 'Cannot drag a form'; Localized: '无法拖动窗体'),
    (English: 'Metafiles'; Localized: '图元文件'),
    (English: 'Enhanced Metafiles'; Localized: '增强型图元文件'),
    (English: 'Icons'; Localized: '图标'),
    (English: 'Bitmaps'; Localized: '位图'),
    (English: 'TIFF Images'; Localized: 'TIFF 图像'),
    (English: 'Warning'; Localized: '警告'),
    (English: 'Error'; Localized: '错误'),
    (English: 'Information'; Localized: '信息'),
    (English: 'Confirm'; Localized: '确认'),
    (English: '&Abort'; Localized: '中止(&A)'),
    (English: 'N&o to All'; Localized: '全否(&O)'),
    (English: 'Yes to &All'; Localized: '全是(&A)'),
    (English: 'BkSp'; Localized: 'BkSp'),
    (English: 'Tab'; Localized: 'Tab'),
    (English: 'Esc'; Localized: 'Esc'),
    (English: 'Enter'; Localized: 'Enter'),
    (English: 'Space'; Localized: 'Space'),
    (English: 'PgUp'; Localized: 'PgUp'),
    (English: 'PgDn'; Localized: 'PgDn'),
    (English: 'End'; Localized: 'End'),
    (English: 'Home'; Localized: 'Home'),
    (English: 'Left'; Localized: 'Left'),
    (English: 'Up'; Localized: 'Up'),
    (English: 'Right'; Localized: 'Right'),
    (English: 'Down'; Localized: 'Down'),
    (English: 'Ins'; Localized: 'Ins'),
    (English: 'Del'; Localized: 'Del'),
    (English: 'Value must be between %d and %d'; Localized: '值必须介于 %d 和 %d 之间'),
    (English: 'Unable to insert a line'; Localized: '无法插入行'),
    (English: 'Invalid clipboard format'; Localized: '无效的剪贴板格式'),
    (English: 'Clipboard does not support Icons'; Localized: '剪贴板不支持图标'),
    (English: 'Cannot open clipboard: %s'; Localized: '无法打开剪贴板: %s'),
    (English: 'Text exceeds memo capacity'; Localized: '文本超出了备注的容量'),
    (English: 'Operation not supported on selected printer'; Localized: '选定的打印机不支持此操作'),
    (English: 'There is no default printer currently selected'; Localized: '当前未选择默认打印机'),
    (English: 'Menu ''%s'' is already being used by another form'; Localized: '菜单 ''%s'' 已被另一个窗体使用'),
    (English: 'Docked control must have a name'; Localized: '停靠的控件必须有名称'),
    (English: 'Error removing control from dock tree'; Localized: '从停靠树中移除控件时出错'),
    (English: ' - Dock zone not found'; Localized: ' - 找不到停靠区'),
    (English: ' - Dock zone has no control'; Localized: ' - 停靠区没有控件'),
    (English: 'Error loading dock zone from the stream. Expecting version %d, but found %d.'; Localized: '从流中加载停靠区时出错。应为版本 %d，但找到 %d。'),
    (English: 'Multiselect mode must be on for this feature'; Localized: '此功能要求启用多选模式'),
    (English: 'Length of value array must be >= length of prompt array'; Localized: '值数组的长度必须 >= 提示数组的长度'),
    (English: 'Prompt array must not be empty'; Localized: '提示数组不能为空'),
    (English: '&Username'; Localized: '用户名(&U)'),
    (English: '&Password'; Localized: '密码(&P)'),
    (English: '&Domain'; Localized: '域(&D)'),
    (English: 'Login'; Localized: '登录'),
    (English: 'Expand'; Localized: '展开'),
    (English: 'Separator'; Localized: '分隔符'),
    (English: 'Error setting %s.Count'; Localized: '设置 %s.Count 时出错'),
    (English: 'Listbox (%s) style must be virtual in order to set Count'; Localized: '要设置 Count，列表框 (%s) 的样式必须为虚拟样式'),
    (English: 'No OnGetItem event handler assigned'; Localized: '未分配 OnGetItem 事件处理程序'),
    (English: 'ANSI'; Localized: 'ANSI'),
    (English: 'ASCII'; Localized: 'ASCII'),
    (English: 'Unicode'; Localized: 'Unicode'),
    (English: 'Big Endian Unicode'; Localized: 'Big Endian Unicode'),
    (English: 'UTF-8'; Localized: 'UTF-8'),
    (English: 'UTF-7'; Localized: 'UTF-7'),
    (English: 'Cannot remove shell notification icon'; Localized: '无法移除 shell 通知图标'),
    (English: '%s requires Windows Vista or later'; Localized: '%s 需要 Windows Vista 或更高版本'),
    (English: 'Button%d'; Localized: '按钮%d'),
    (English: 'RadioButton%d'; Localized: '单选按钮%d'),
    (English: 'Caption cannot be empty'; Localized: '标题不能为空'),
    (English: 'Invalid canvas operation'; Localized: '无效的画布操作'),
    (English: '%s has no owner'; Localized: '%s 没有所有者'),
    (English: 'Source and destination require the same owner'; Localized: '源和目标必须具有相同的所有者'),
    (English: '%s cannot be owned by a different canvas'; Localized: '%s 不能由其他画布所有'),
    (English: 'Not a solid color brush'; Localized: '不是纯色画笔'),
    (English: 'Invalid brush style'; Localized: '无效的画笔样式'),
    (English: 'Unable to load style ''%s'''; Localized: '无法加载样式 ''%s'''),
    (English: 'Unable to load styles: %s'; Localized: '无法加载样式: %s'),
    (English: 'Style ''%s'' already registered'; Localized: '样式 ''%s'' 已注册'),
    (English: 'Style class ''%s'' already registered'; Localized: '样式类 ''%s'' 已注册'),
    (English: 'Style ''%s'' not found'; Localized: '找不到样式 ''%s'''),
    (English: 'Style class ''%s'' not found'; Localized: '找不到样式类 ''%s'''),
    (English: 'Invalid style format'; Localized: '无效的样式格式'),
    (English: 'VCL Style File'; Localized: 'VCL 样式文件'),
    (English: 'Class ''%s'' is already registered for ''%s'''; Localized: '类 ''%s'' 已为 ''%s'' 注册'),
    (English: 'Class ''%s'' is not registered for ''%s'''; Localized: '类 ''%s'' 未为 ''%s'' 注册'),
    (English: '%s parameter cannot be nil'; Localized: '%s 参数不能为 nil'),
    (English: 'A StyleHook class has not been registered for %s'; Localized: '尚未为 %s 注册 StyleHook 类'),
    (English: 'Feature not supported by this style'; Localized: '此样式不支持该功能'),
    (English: 'Cannot call BeginInvoke on a control with no parent or window handle'; Localized: '无法在没有父级或窗口句柄的控件上调用 BeginInvoke'),
    (English: 'CardPanel card index is out of range'; Localized: 'CardPanel 的卡片索引超出范围'),
    (English: 'CardPanel.ActiveCard cannot be nil'; Localized: 'CardPanel.ActiveCard 不能为 nil'),
    (English: 'Invalid index'; Localized: '无效的索引'),
    (English: 'Unable to insert an item'; Localized: '无法插入项'),
    (English: 'Invalid owner'; Localized: '无效的所有者'),
    (English: 'RichEdit line insertion error'; Localized: 'RichEdit 行插入错误'),
    (English: 'Failed to Load Stream'; Localized: '加载流失败'),
    (English: 'Failed to Save Stream'; Localized: '保存流失败'),
    (English: '%s is already associated with %s'; Localized: '%s 已与 %s 关联'),
    (English: 'This control requires version 4.70 or greater of COMCTL32.DLL'; Localized: '此控件需要 COMCTL32.DLL 的 4.70 或更高版本'),
    (English: 'ListView item can be added only when OwnerData is False.  Use OnData instead.'; Localized: '仅当 OwnerData 为 False 时才能添加 ListView 项。请改用 OnData。'),
    (English: 'This "Portable Network Graphics" image is not valid because it contains invalid pieces of data (crc error)'; Localized: '此"Portable Network Graphics"图像包含无效的数据块 (CRC 错误)，因此无效'),
    (English: 'The "Portable Network Graphics" image could not be loaded because one of its main piece of data (ihdr) might be corrupted'; Localized: '无法加载"Portable Network Graphics"图像，它的一个主要数据块 (ihdr) 可能已损坏'),
    (English: 'This "Portable Network Graphics" image is invalid because it has missing image parts.'; Localized: '此"Portable Network Graphics"图像缺少图像部件，因此无效。'),
    (English: 'Could not decompress the image because it contains invalid compressed data.'#13#10' Description: '; Localized: '图像包含无效的压缩数据，无法解压。'#13#10' 说明: '),
    (English: 'The "Portable Network Graphics" image contains an invalid palette.'; Localized: '"Portable Network Graphics"图像包含无效的调色板。'),
    (English: 'The file being read is not a valid "Portable Network Graphics" image because it contains an invalid header. This file may be corrupted, try obtaining it again'; Localized: '正在读取的文件包含无效的头，因此不是有效的"Portable Network Graphics"图像。此文件可能已损坏，请尝试重新获取'),
    (English: 'This "Portable Network Graphics" image is not supported or it might be invalid.'#13#10'(IHDR chunk is not the first)'; Localized: '此"Portable Network Graphics"图像不受支持，或者可能无效。'#13#10'(IHDR 块不是第一个块)'),
    (English: 'This "Portable Network Graphics" image is not supported because either its width or height exceeds the maximum size of 65535 pixels.'; Localized: '此"Portable Network Graphics"图像的宽度或高度超过了 65535 像素的最大大小，因此不受支持。'),
    (English: 'There is no such palette entry.'; Localized: '不存在这样的调色板项。'),
    (English: 'This "Portable Network Graphics" image contains an unknown critical part which could not be decoded.'; Localized: '此"Portable Network Graphics"图像包含无法解码的未知关键部分。'),
    (English: 'This "Portable Network Graphics" image is encoded with an unknown compression scheme which could not be decoded.'; Localized: '此"Portable Network Graphics"图像使用无法解码的未知压缩方案进行编码。'),
    (English: 'This "Portable Network Graphics" image uses an unknown interlace scheme which could not be decoded.'; Localized: '此"Portable Network Graphics"图像使用无法解码的未知隔行扫描方案。'),
    (English: 'This "Portable Network Graphics" image uses an unknown color type which could not be decoded.'; Localized: '此"Portable Network Graphics"图像使用无法解码的未知颜色类型。'),
    (English: 'The chunks must be compatible to be assigned.'; Localized: '要赋值，块之间必须兼容。'),
    (English: 'This "Portable Network Graphics" image is invalid because the decoder found an unexpected end of the file.'; Localized: '解码器遇到了意外的文件结尾，因此此"Portable Network Graphics"图像无效。'),
    (English: 'This "Portable Network Graphics" image contains no data.'; Localized: '此"Portable Network Graphics"图像不包含任何数据。'),
    (English: 'The program tried to add a existent critical chunk to the current image which is not allowed.'; Localized: '程序试图向当前图像添加已存在的关键块，这是不允许的。'),
    (English: 'It''s not allowed to add a new chunk because the current image is invalid.'; Localized: '当前图像无效，因此不允许添加新的块。'),
    (English: 'Some operation could not be performed because the system is out of resources. Close some windows and try again.'; Localized: '由于系统资源不足，无法执行某些操作。请关闭一些窗口后重试。'),
    (English: 'Setting bit transparency color is not allowed for png images containing alpha value for each pixel (COLOR_RGBALPHA and COLOR_GRAYSCALEALPHA)'; Localized: '对于每个像素都包含 alpha 值的 PNG 图像 (COLOR_RGBALPHA 和 COLOR_GRAYSCALEALPHA)，不允许设置位透明色'),
    (English: 'This operation is not valid because the current image contains no valid header.'; Localized: '当前图像不包含有效的头，因此此操作无效。'),
    (English: 'The new size provided for image resizing is invalid.'; Localized: '为调整图像大小而提供的新大小无效。'),
    (English: 'The "Portable Network Graphics" image could not be loaded because it uses an invalid image bit depth.'; Localized: '由于使用了无效的图像位深度，无法加载"Portable Network Graphics"图像。'),
    (English: 'Exception '; Localized: '异常 '),
    (English: 'Data cannot be accessed as %s'; Localized: '无法以 %s 的形式访问数据'),
    (English: 'Check'; Localized: '勾选'),
    (English: 'Uncheck'; Localized: '取消勾选'),
    (English: 'Collapse'; Localized: '折叠'));

implementation

end.
