name: build2

on:
  push:
  workflow_dispatch:

env:
  HOME: "${{github.workspace}}\\home"

jobs:
  build2:
    # Only set the topic `has-issrc-build2-env` if the secrets are available
    if: contains(github.event.repository.topics, 'has-issrc-build2-env') && github.ref != 'refs/heads/copilot-review'
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Initialize build environment
        env:
          ISSRC_BUILD2_ENV_ZIP_PASSWORD: ${{ secrets.ISSRC_BUILD2_ENV_ZIP_PASSWORD }}
          ISSRC_BUILD2_ENV_ZIP_URL: ${{ secrets.ISSRC_BUILD2_ENV_ZIP_URL }}
        run: |
          (New-Object Net.WebClient).DownloadFile($env:ISSRC_BUILD2_ENV_ZIP_URL, "issrc-build-env.zip")
          & "C:\\Program Files\\7-Zip\\7z.exe" x -oissrc-build-env -p"$env:ISSRC_BUILD2_ENV_ZIP_PASSWORD" issrc-build-env.zip
          if (!(Test-Path issrc-build-env\bin\dcc32.exe)) {
            Write-Host "Failed to extract dcc32.exe"
            Exit 1
          }
          Remove-Item issrc-build-env.zip
          $DELPHIXEROOT = (Get-Item .\issrc-build-env).FullName
          "DELPHIXEROOT=$DELPHIXEROOT" | Out-File -NoNewLine -Encoding ascii -Append "$env:GITHUB_ENV"
      - name: Build issrc
        run: |
          "set DELPHIXEROOT=$env:DELPHIXEROOT" | Out-File -Encoding ascii compilesettings.bat
          "set ISSIGTOOL_KEY_FILE=${{github.workspace}}\mykey.isprivatekey" | Out-File -NoNewline -Encoding ascii -Append compilesettings.bat
          "set DELPHIXEROOT=$env:DELPHIXEROOT" | Out-File -NoNewline -Encoding ascii ISHelp\ISHelpGen\compilesettings.bat
          "set HHCEXE=%ProgramFiles(x86)%\HTML Help Workshop\hhc.exe" | Out-File -NoNewline -Encoding ascii ISHelp\compilesettings.bat
          .\build.bat
      - name: Clean up temporary files
        if: always()
        shell: bash
        run: rm -rf mykey.isprivatekey
